### ISSUE TITLE
Logistic Crafting Table resetting configuration upon logout

### ISSUE THREAD

**Issue by AbdielKavash** [RS485/LogisticsPipes#1000]
Modpack: FTB Infinity Evolved v2.5.0
Logistics Pipes version: 0.9.3.114
Playing singleplayer.

I've set up an LP system with autocrafting using Logistic Crafting Tables. However, whenever I log out to the main menu and log back in, several of the LCTs at random "forget" their configuration (recipe) - the GUI turns blank as if I never set the pattern in it. This is not just a visual glitch, the affected tables are unable to craft until I set up the pattern again.

Which tables are affected seems to be completely random, the same table might be fine for several resets in a row, and then break later. It is not based on proximity or chunks, sometimes one table breaks and another directly on top of it is fine. As a guess, 30-50% of my crafting tables get affected with each logout.

Only tables that are actually connected to a LP network seem to be affected, if I put down an isolated table and not connect it to anything, or if I disconnect my crafting tables from the network by breaking a pipe, the bug does not occur with those tables.

Finally, and I know this might sound really odd: my setup is high in the sky (around y=200). The bug happens when I log out that high. When I log out with my character much lower (around y=100), the bug seems much less frequent if not non-existent. Logistic Crafting Tables set up both up high and down low are affected when the bug happens though.

I'll gladly provide any additional information as needed.

**Comment by SonOfTheStars** [comment]
@AbdielKavash could you provide a download for the World or some Images for me to re-create this in a test environment?

**Comment by AbdielKavash** [comment]
World download:

https://www.dropbox.com/s/rl74hrpanncu069/Crafting%20Test.zip?dl=0

I have disconnected most of the LP system to make debugging easier for you. Only the crafting tables are connected. The bug still occurs.

To reproduce: set a crafting recipe (I use 1 wood -> 2 planks, but any recipe is affected) in several crafting tables (I use 10 or so). Log out and log in again. Check the GUI of the crafting tables you used. Sometimes several of them are missing the recipe. Sometimes you need to log out and back in several times for the bug to occur, but it almost always happens after 2-3 logouts.

Logistic Crafting Table GUI before logging out: http://i.imgur.com/o4aFy9s.png

After logging out and back in: http://i.imgur.com/TeKGLlX.png

Some details I didn't mention earlier: I'm playing Expert mode, and I got the pack from the FTB launcher (not sure if any of this matters, but putting it here just in case).

**Comment by SonOfTheStars** [comment]
@AbdielKavash 
Works fine on Servers, appears to be an issue with SSP...

**Comment by matthew117** [comment]
It seems to happen when you restart the server during SMP too or if the area is not chunkloaded; basically, any time the LogisticsCraftingTable is reloaded from file.

It seems to be related to this exception:
https://gist.github.com/matthew117/601b8d3b37fbbba61c0f81bd21b10f76

**Comment by codewarrior0** [comment]
If you are using MineTweaker, this may be a threading issue with MineTweaker: https://github.com/stanhebben/MineTweaker3/issues/297

**Comment by bziemons** [comment]
Probably related to #1460
