### ISSUE TITLE
Crash when hovering over items in Request menu

### ISSUE THREAD

**Issue by AntiCompositeNumber** [RS485/LogisticsPipes#1001]
Whenever I try to request something using a request pipe, the game crashes when I hover over the item. 
Minecraft 1.7.10, Forge 10.12.4.1614, BuildCraft 7.1.16, and Logistics Pipes 0.9.3.121, on Linux with MultiMC.

Here is the Minecraft crash report: [crash-2016-05-07_21.25.55-client.txt](https://github.com/RS485/LogisticsPipes/files/253700/crash-2016-05-07_21.25.55-client.txt)

And the log from just starting, loading the world, and crashing: [latest (copy).txt](https://github.com/RS485/LogisticsPipes/files/253702/latest.copy.txt)

**Comment by Rue82** [comment]
I am getting the same crash and it is happening in the logistics request tables as well.  Minecraft 1.7.10, Forge 10.13.4.1558, BuildCraft 7.1.16 and Logistcs Pipes 0.9.3.121 on Windows 10 with MultiMC.

[crash-2016-05-08_02.10.25-client.txt](https://github.com/RS485/LogisticsPipes/files/253871/crash-2016-05-08_02.10.25-client.txt)

 tried downgrading to a older version of Logistics Pipes 0.9.3.114 and got the same crash.

[crash-2016-05-08_05.55.55-client.txt](https://github.com/RS485/LogisticsPipes/files/253870/crash-2016-05-08_05.55.55-client.txt)

But when i downgraded to BC 6.4.16 and LP 0.8.3.106 it did not crash on me when i looked in either the Request Table or the Request Pipe.

**Comment by bziemons** [comment]
Could you try downgrading NEI?

**Comment by AntiCompositeNumber** [comment]
Upgrading NEI and CCC to the Latest (not Recommended) version fixes the problem. I should have tried that already, but I didn't.

**Comment by Rue82** [comment]
Actually i was able to upgrade to a recommended version just had to be a little more recent.
NEI 1.0.4.107 and CCC to 1.6.44 seemed to work for me.

**Comment by AntiCompositeNumber** [comment]
Either way, it's fixed in a newer version.
