### ISSUE TITLE
Logistics pipes interaction with Storage Drawers issue

### ISSUE THREAD

**Issue by ren-** [RS485/LogisticsPipes#1004]
Hello,

I started to experience a weird delay when active requesting something from a specific set of drawers vis drawer controller.
It does not matter if it is a crafting recipe that requests an item or me. The item does not move out of the drawers for at least 2-5 minutes.

Request 5 redstone via request table ->(drawer controller is 2 blocks away) the item reaches the table after 5 minutes.

Any ideas? I've tried replacing the table and drawer. The controller is connected with a pipe that has polymorphic itemsink and provider module.

No tps issues, maximum of 8 ms total tick time.

EDIT: Installed crafting monitoring upgrade. http://puu.sh/oMFrz/981f149a17.png 
drag to resize or shift-drag to move
It is always stuck at this router ID, takes minutes for it to stay this way, then after 2-8 minutes items start to travel.

**Comment by SonOfTheStars** [comment]
@ren- Hows your Servers TPS?
LP is known to choke hard when the TPS is bad or the Network Connection suffers severe ping spikes/generally high ping.

Could well be a Packet issue by LP, but it sounds like youre having problems with bad TPS/Network

To check your TPS, type /tps ot /cofh tps into the chat. If youre allowed to do that, Ittl show a bunch of numbers. You'll want to look for TPS being lower than 20.0/sec(Wich would be bad) or High update Times, shown by MS higher than 50

**Comment by ren-** [comment]
Sorry forgot to mention, that the TPS is always full, I only get up to 8 ms of tick time.

**Comment by ren-** [comment]
It only happens with the specific drawer controller, ANYthing else on the network works perfectly. I am pulling my hair out. @Bitterholz

**Comment by SonOfTheStars** [comment]
Sounds much like a interaction Bug...Make sure to post this issue in Storage Drawers Github too

**Comment by ren-** [comment]
@Bitterholz Will do. You could connect to the server for a second. It would make this way easier, but I understand if this is not possible. Thanks.

**Comment by SonOfTheStars** [comment]
If you tell me what pack you has there

**Comment by ren-** [comment]
Infinity Evolved: Skyblock

**Comment by SonOfTheStars** [comment]
@ren- you can tweet me server stuff and such here: https://twitter.com/Bitterholz

**Comment by ren-** [comment]
@Bitterholz Could you follow me back? I can't send you a direct message otherwise. https://twitter.com/claymoreh

**Comment by ren-** [comment]
The problem was that the pipe connecting to the drawers was too busy. Another was attached to the drawer controller and the issue is gone. Thank you @Bitterholz for taking the time to come to my server and solve this. :)
