### ISSUE TITLE
infinity evolved skyblock crash

### ISSUE THREAD

**Issue by DnTheMn** [RS485/LogisticsPipes#1008]
my graphics are up to date and others in the are also crash.
it occurs when placing a crafting sign creator on the crafting pipe removing the nbt data on the pipe (removing the sign) fixes it here is the log
http://pastebin.com/4qZKd64S

**Comment by hron84** [comment]
Can you make a screenshot about the problematic setup? Also, what graphics card do you use and what driver (or where did you get it)? Did you disabled `Advanced OpenGL` in `Video Settings`? Did you tried to turn down other quality settings (like mipmap, switching to fast graphic, etc)?

It smells like a driver issue anyway and I am not pretty sure if LP devs can help you.

**Comment by SonOfTheStars** [comment]
@DnTheMn Have you tried redownloading your Client and/or Server modpack?

A Screenshot would be handy too.

And the Logistics Pipes version you run.

**Comment by DnTheMn** [comment]
i had to roll back ,but it wasnt just me that was crashing there were others when you get near that pipe it you crash to desktop hense no crash report Advanced OpenGL is diasbled and the graphics were on fast

**Comment by hron84** [comment]
I've no other ideas. Try out with a different machine with non-Intel VGA.

**Comment by SonOfTheStars** [comment]
It could be GPU driver related...How many others have the probelm? and does their GPU match yours?

Search for new Driver versions or even Betas. Try again if you find some!

**Comment by DnTheMn** [comment]
two others and im not exactly sure if the if the graphics are the same the problem isn't resolved but its not a high priority seeing we reverted to a back up thanks for your help in anycase
