### ISSUE TITLE
LP doesn't work with Advanced Solar Panels' Molecular Transformer

### ISSUE THREAD

**Issue by Zettt** [RS485/LogisticsPipes#1010]
Attaching a chassis with a crafting module inside, to create 1 Sunnarium Piece from 1 piece of Glowstone Dust, causes the item to disappear. LP does insert the item, but it never gets inserted into the machine. I suppose this has to do with LP, but I am sorry if I reported this incorrectly, and it's an Advanced Solars issue.

**Comment by Zettt** [comment]
Piping in from the sides. I just tested it with a hopper on top and bottom, and that seems to do the trick.

**Comment by davboecki** [comment]
Could you please provide us with more information like version of the involved mods and a link to the particular mod in question.

**Comment by hron84** [comment]
[Advanced Solar Panels](http://forum.industrial-craft.net/index.php?page=Thread&threadID=3291)

I guess he is also a FTB Infinity user.
