### ISSUE TITLE
Crash when wooden fluid pipe disabled

### ISSUE THREAD

**Issue by Usernm0** [RS485/LogisticsPipes#1011]
I disable fluid pipes in buildcraft config file and game crashes when try to make recipe for logistics fluid extraction pipe:

java.lang.RuntimeException: Invalid shaped ore recipe: w, I, I, logisticspipes.items.ItemLogisticsPipe@48641d17, w, null, 1xitem.PipeFluidExtractor@0

Can you fix this dependency, because i use minetweaker and change recipes for logistic pipes.

**Comment by SonOfTheStars** [comment]
Ill implement a null check for those

**Comment by SonOfTheStars** [comment]
@Usernm0 For now, try and go into the Logistics pipes config file, and set:
EnableBetaRecipes=true

This will enable the use of beta non Buildcraft recipes and SHOULD mitigate your Problem!

**Comment by hron84** [comment]
@Bitterholz is this setting stable now?

**Comment by SonOfTheStars** [comment]
@hron84 The "EnablebetaRecipes" one?
That was stable from the start!

For disabling Wooden Pipes, not yet!

**Comment by hron84** [comment]
> That was stable from the start!

Cool!

**Comment by bziemons** [comment]
Fixed in 0.10. We can live with that bug for 0.9. That BC config option is just not supported then, no real harm.
