### ISSUE TITLE
Prioritized Providers [Enhancement]

### ISSUE THREAD

**Issue by TomShkurti** [RS485/LogisticsPipes#1012]
Would it be possible to give various types of Provider pipes a numerical priority?

As an example of where this would be useful:

I currently have an automated rubber farm that consumes fertilizer and a fair bit of power, and tries to fill up a chest with its rubber output- whenever there is space in the chest, the farm comes online and fills it. However, I also have a secondary process milling planks that produces some rubber on the side and stores it in its own chest, but only when it needs to make planks. I would like to be able to have my logistics network draw rubber FIRST from the "windfall" chest if I have spare rubber inside it, and only when that is empty go to the farm chest and begin extracting from something that consumes resources to guarantee a reliable rubber supply.

**Comment by SonOfTheStars** [comment]
rather would suggest a simple GUI setable priority.
Doesnt requre diffrent Pipes/Modules

**Comment by AEnterprise** [comment]
i thought LP already pulled from the first one it finds (so the closest one)

**Comment by cleverca22** [comment]
i would do that by putting a provider pipe on the sawmill's left-overs

and then putting a crafting pipe on the full farm, configured to make 1 rubber with 0 inputs

i suspect (but havent confirmed) that it will prefer a provider over a crafter

**Comment by TomShkurti** [comment]
Just verified that Clever's trick does indeed work. It's sort of hackish, but unless somebody can come up with a compelling need for more than two priority levels in a supply network I think I'm content with leaving the issue here.
