### ISSUE TITLE
Logistic Pipe Stall report

### ISSUE THREAD

**Issue by Brend-Smits** [RS485/LogisticsPipes#1014]
Hello, 
My server is running the Tekkit Legends Modpack and I've been experiencing Stall reports the past few days.
The origin of the issue is at Logisitics Pipes.
Here is the stall report: http://hastebin.com/kaqirewebu.avrasm
We're running version: logisticspipes-0.9.3.70

If you need additional information. Don't hesitate to ask!

**Comment by davboecki** [comment]
Please Update your LP version. Some time ago there was some work done in that area of the code. SO please update your version and report again if you are still having that issue.

**Comment by Brend-Smits** [comment]
I would love to update it, although I'm currently in a modpack and I can't just update my mods without clients having to update it as well. I know it's a pain.. Very sorry.
Do you have an idea of what version this was changed? 
Maybe if the version only has server sided changes, we can try to update it and change the version in the mcmod.info ?

Thanks for your reply!

**Comment by SonOfTheStars** [comment]
No you wont be able to do that.
You have to update both sides.

TBH i do not recommend Tekkit Packs since they often use outdated versions and dont update.
Youll have to update your pack yourself if you want to have up to date content.

Simple mcmod.info editing will NEVER help you with any mod issues

**Comment by Brend-Smits** [comment]
You can edit the Bytecode of a mod and change the version numbers. That will make it work, it does help in some cases. 
Just wondering around which version this was changed/fixed. 

There is an update planned for Tekkit Legends, I might be able to make a suggestion the the person updating it.

**Comment by SonOfTheStars** [comment]
You may try. But its highly likely you will fail to fix the problem.

I recommend you either update yourself.

**Comment by davboecki** [comment]
We are currently at build 122 so a long way from 70. I'm sorry but there were so many changes including network changes, that you have to have the same version on both clients and the server.
