### ISSUE TITLE
Items missing names

### ISSUE THREAD

**Issue by craft90** [RS485/LogisticsPipes#1015]
I have run into quite the annoying bug. As I'm from Sweden I run Minecraft translated into Swedish. However that causes an issue with Logistics Pipes. About 80% of all the pipes have no name. They're just titled "Unnamed". Switching to English (US) fixes the issue though.

**Comment by SonOfTheStars** [comment]
Thats probably due to Logistics Pipes currently missing a swedish Translation!

@davboecki and @theZorro266 have a crowdin setup for LP though, so feel free to help us Localise Logistics Pipes for your respective region ;)

**Comment by craft90** [comment]
Yeah but some of the pipes do have names like the liquid ones and the chassis. And all pipes have description. So I'm not sure it's just a localization issue. But I don't know anything about programing. Which means I don't think I'd be the best to try to localize something.

**Comment by SonOfTheStars** [comment]
Its working for German and English, so i can asure you, there are just some Pipes that arent Localised YET
Maybe someone couldn't really make up the right name for Them

**Comment by Matryoshika** [comment]
Hmmm, I should be able to get a good Swedish translation of the .lang file, might take a day or two, and then the added time of the pull-req being accepted.

Just wish that we Swedes actually had a good translation of "Unrouted", "Orutten" sounds odd, and is more commonly used as the negative term of "rotten" xD
(I work with translating/interpreting Swedish-English-Japanese)

**Comment by SonOfTheStars** [comment]
You can allways keep it to its english name if there is no direct or pleasing indirect translation.

**Comment by HadesDurin** [comment]
maybe some other meaning may help of unrouted, try non-routed, uncontrolled, non-controlled
hope it helps a bit

**Comment by craft90** [comment]
I wish I could help more but I know nothing about coding. How about "oriktad"?

**Comment by SonOfTheStars** [comment]
@craft90 You can Help ;)
You just need to go to https://github.com/RS485/LogisticsPipes-Language/blob/master/sv_SE.lang

And Name the Pipes in there after the "=". For example:
- item.PipeItemsBasicLogistics=TRANSLATEDNAME  (This names the Basic Logistics Pipe)

You can go on and on with that. Ill try and get you all the item Refferences (item.WHATEVER) so you can help name them.

You can use the [EDIT]-Button(Little Pen icon on the top right of the Fileview) to Fork and edit that Localisation File.

OR you can be stylish and get https://www.sourcetreeapp.com/ and fork the Logistics Localisation Repository to create your own Pull Requests AND be ready for further useage of Github LIKE A PRO!
There is plenty of Youtube tutorials on how to Fork a Repository and how to use Sourcetree. There is actually ZERO Coding involved ;)

**Comment by hron84** [comment]
@Bitterholz not related to swedish translation, but there is a serious problem if LP cannot fall back to english names if some translations are missing. Or is this a MC issue?

**Comment by AEnterprise** [comment]
MC itself falls back to english if the translation key isn't present in the currently selected language

in this case i suspect the problem here is that they keys are pressent but there is no localization string so MC catches that problem by subsituting "Unnamed" for the empty string, removing the non localized entries should cause MC to fall back to english for those unless LP does something differently

**Comment by hron84** [comment]
@davboecki fix sent to RS485/LogisticsPipes-Language#4 but it fixes only "Unnamed" items, not the missing swedish translation, as I don't speak swedish.

**Comment by AEnterprise** [comment]
atleast they will be able so see the english names, that's an improvement

**Comment by davboecki** [comment]
That fix is included in build [123](http://ci.rs485.network/job/LogisticsPipes-0.9-mc17-bc7/123/).

**Comment by hron84** [comment]
@davboecki thanks for the quick reply.

@AEnterprise yeah, that's why I did it. English names are much more helpful than "call me Unnamed".

**Comment by hron84** [comment]
@craft90 btw, if you have some spare time it would be very kind for the LP community if you could complete the swedish translation. We'd really appreciate it.
