### ISSUE TITLE
[Question] Logistics System Entrance Pipe

### ISSUE THREAD

**Issue by Leytek** [RS485/LogisticsPipes#1016]
How can i push unrouted items in Logistics System Entrance Pipe out of any inventory(Chests etc), using only LP, without any other mod ?
Currently it seems impossible.

**Comment by HadesDurin** [comment]
you need an extraction module in a chassis pipe to do so

**Comment by Leytek** [comment]
@HadesDurin Extraction module sends items to matched Sink modules (or Terminus etc ), so Logistics System Entrance Pipe will route items just to a next pipe.
Logistics System Entrance Pipe need un-routable items to send them to matched Logistics System Destination Pipe, so wooden pipe from BC, for example, works well, but any kind of stuff from LP does not.

**Comment by SonOfTheStars** [comment]
@Leytek Well the easiest way to leave Unroutable Items in an Inventory, is to just attach a Quicksort Module.
The Quicksort will /ONLY/ ever extract items that have a SET destination. It will not Extract any items that do not have a Destination set. Even Default Routes do not count.

By doing that, you should have your Unroutable Items nice and openly Presented in your Chest

**Comment by Leytek** [comment]
@Bitterholz My main idea: there is only one way how i can make Entrance Pipe send items to matched Destination Pipe - by using wooden pipe (or stuff like that from other mods) to push items into Entrance Pipe. There is no way do that by using only LP.

**Comment by SonOfTheStars** [comment]
Well thats because of it being a functionality outeside of the Design of LP...
Entrance Pipes arent designed to accept items form inside a LP System, more than, as the name allready states, from somewhere OUTSIDE the System.

So yeah using something from outside LP is actually required for the System Entrance Pipe to work the way its supposed to be

**Comment by Leytek** [comment]
Well, may close.
