### ISSUE TITLE
using guiscreen tree view

### ISSUE THREAD

**Issue by AEnterprise** [RS485/LogisticsPipes#1021]
I am making a JEI addon mod that will create lists of items needed to make a specific item and tree views of how to assemble it all.

Would you guys mind if i dig around in the LP code for using the guiscreen to make such a tree view? If not could i maybe get some pointers on where the main code for it is? LP is very complex and not sure where all the parts of it are.

**Comment by davboecki** [comment]
Sure feel free to dig around.
Most of the RequestTreeView is inside this class:
https://github.com/RS485/LogisticsPipes/blob/stable-bc7/common/logisticspipes/gui/popup/RequestMonitorPopup.java

Feel free to ask any questions if you have them.
But be warned, that code is functional but not pretty.

**Comment by AEnterprise** [comment]
i'll base my code on some parts of it (mainly interested in the GL enable/dissable commands as they can be tricky)

i have some idea's on how to make this a bit cleaner but i'd have to write it first to be sure it doesn't become a huge mess

**Comment by hron84** [comment]
@AEnterprise this sounds really cool!
