### ISSUE TITLE
Do not send items to crafting still all components are ready

### ISSUE THREAD

**Issue by Dijkstra1-zz** [RS485/LogisticsPipes#1028]
Do not try and craft something unless all components are ready. Also do not try craft anything if something is already crafting where on that pipe.

**Comment by davboecki** [comment]
?

**Comment by SonOfTheStars** [comment]
We would love to get a better explaination of your Issue, In propper english Sentences please.
Use of Pictures or Videos is advised!

Else we wont be able to help you.

**Comment by Dijkstra1-zz** [comment]
Say i wanted craft enderium at a alloy smelter

It will send Ender to pearls to the alloy smelter, and then it can not put in tin, silver and platinum, to make the enderium base, what I ask is that LP check I do not have enderium base yet do not send ender pearls and pyrotheum until, the enderium base is ready.

**Comment by davboecki** [comment]
I'm sorry but you are going to have to setup two seperate machines to craft that. In order to implement that feature we would need to redesign one of the core features of LP and for that reason it's just not feasable.
