### ISSUE TITLE
OreDict Based ItemSink Module Not Working

### ISSUE THREAD

**Issue by panda2134** [RS485/LogisticsPipes#1029]
I put the ore into the slot in the module,and the oredict name displayed.
However,when i reopened the gui of the module,i found that the oredict name was not added
there're no buttons like ok or cancel.
![2016-06-25_21 49 40](https://cloud.githubusercontent.com/assets/7239200/16357089/1c7026ce-3b1f-11e6-88e6-0843ca024455.png)

**Comment by AEnterprise** [comment]
you see oreGold on the right, there it displays all oredict tags of the item, this this case there is only 1, you need to click that to add it to the list below that is saved

**Comment by panda2134** [comment]
Thanks... I'd better close this
