### ISSUE TITLE
Crafting tree disappeared

### ISSUE THREAD

**Issue by lesdmark** [RS485/LogisticsPipes#1030]
I have the Crafting Monitoring upgrade installed and after briefly working to show me crafting the tab no longer shows up when you start to craft something automatically in the table. is there a hotkey for this or is something just broken I'm using version 0.9.3.114 in infinity evolved skyblock.

**Comment by j2ghz** [comment]
Is this the same as #973 ?

**Comment by bziemons** [comment]
Same as #973
