### ISSUE TITLE
Polymorphic ME Interface

### ISSUE THREAD

**Issue by QORTEC** [RS485/LogisticsPipes#1036]
I just started playing with AE and noticed that the Polymorphic ItemSink Module does not currently work with the ME Interface.

Since the Provider/QuickSort Module can "see every item in the ME network";
Would it be possible to implement this for the Polymorphic ItemSink Module as well?

**Comment by hron84** [comment]
AE integration is still on the way. Check #786

**Comment by QORTEC** [comment]
I'm not sure I did differently but the Polymorphic Interface seams to work with the ME Interface. 
-- I will close this issue.
