### ISSUE TITLE
Problems with the FPS due to new models

### ISSUE THREAD

**Issue by ProFFesor117** [RS485/LogisticsPipes#1038]
Hello.
Is there any way to revert to the old model of pipes in the current version?
Just because of the new models much FPS sags.

Sorry for english (Google translate)

**Comment by AEnterprise** [comment]
right click with the pipe controller item (not sure of it's exact name, it looks like a red remote/gps thing) in the air and turn off the new renderer there

**Comment by loordgek** [comment]
also update to the last version @davboecki fixed the render and it OMG way better thank you dav :)

**Comment by ProFFesor117** [comment]
Thank you guys.
