### ISSUE TITLE
My game crashes every time I open the request logistics pipe.

### ISSUE THREAD

**Issue by ivangouba** [RS485/LogisticsPipes#1039]
This is a photo of my setup:
![2016-07-27_18 52 04](https://cloud.githubusercontent.com/assets/8239883/17184270/a5634842-542b-11e6-9e31-1c9a12b98c57.png)

This is the crash report:
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 27/07/16 18:46
Description: Rendering screen

java.lang.NoSuchMethodError: codechicken.lib.gui.GuiDraw.drawMultilineTip(Lnet/minecraft/client/gui/FontRenderer;IILjava/util/List;)V
    at logisticspipes.proxy.nei.NEIProxy.renderItemToolTip(NEIProxy.java:68)
    at logisticspipes.asm.wrapper.generated.NEIProxyWrapper.renderItemToolTip(.LP|ASM.dynamic:132)
    at logisticspipes.utils.gui.GuiGraphics.displayItemToolTip(GuiGraphics.java:114)
    at logisticspipes.utils.gui.GuiGraphics.displayItemToolTip(GuiGraphics.java:83)
    at logisticspipes.gui.orderer.GuiOrderer.func_146979_b(GuiOrderer.java:141)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
    at logisticspipes.utils.gui.LogisticsBaseGuiScreen.func_73863_a(LogisticsBaseGuiScreen.java:192)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at logisticspipes.proxy.nei.NEIProxy.renderItemToolTip(NEIProxy.java:68)
    at logisticspipes.asm.wrapper.generated.NEIProxyWrapper.renderItemToolTip(.LP|ASM.dynamic:132)
    at logisticspipes.utils.gui.GuiGraphics.displayItemToolTip(GuiGraphics.java:114)
    at logisticspipes.utils.gui.GuiGraphics.displayItemToolTip(GuiGraphics.java:83)
    at logisticspipes.gui.orderer.GuiOrderer.func_146979_b(GuiOrderer.java:141)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
    at logisticspipes.utils.gui.LogisticsBaseGuiScreen.func_73863_a(LogisticsBaseGuiScreen.java:192)

-- Screen render details --
Details:
    Screen name: logisticspipes.gui.orderer.NormalGuiOrderer
    Mouse location: Scaled: (178, 45). Absolute: (713, 896)
    Screen size: Scaled: (480, 270). Absolute: (1920, 1080). Scale factor of 4

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [GCEntityClientPlayerMP['yasser1515'/118, l='MpServer', x=-184,49, y=65,62, z=-182,03]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-156,4,-184), Chunk: (at 4,0,8 in -10,-12; contains blocks -160,0,-192 to -145,255,-177), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Level time: 148041 game time, 107398 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 32 total; [EntityCreeper['Creeper'/3715, l='MpServer', x=-241,50, y=48,00, z=-174,50], EntitySpider['Spider'/68, l='MpServer', x=-185,91, y=64,00, z=-183,47], EntityItem['item.item.egg'/75, l='MpServer', x=-167,47, y=64,13, z=-233,78], EntityChicken['Chicken'/76, l='MpServer', x=-166,56, y=64,00, z=-224,47], EntitySquid['Squid'/77, l='MpServer', x=-161,47, y=61,00, z=-194,53], EntitySquid['Squid'/78, l='MpServer', x=-161,47, y=61,18, z=-193,53], EntitySquid['Squid'/79, l='MpServer', x=-162,44, y=61,00, z=-193,55], EntitySheep['Sheep'/80, l='MpServer', x=-128,72, y=64,00, z=-219,53], EntitySpider['Spider'/81, l='MpServer', x=-132,06, y=68,00, z=-178,03], EntityCow['Cow'/82, l='MpServer', x=-139,97, y=64,00, z=-124,06], EntityCow['Cow'/83, l='MpServer', x=-126,69, y=64,00, z=-220,75], EntitySkeleton['Skeleton'/4125, l='MpServer', x=-258,50, y=49,00, z=-261,50], EntityZombie['Zombie'/1312, l='MpServer', x=-147,50, y=46,00, z=-160,50], EntityCow['Cow'/97, l='MpServer', x=-106,84, y=64,00, z=-128,16], EntityZombie['Zombie'/2593, l='MpServer', x=-123,50, y=44,00, z=-208,50], EntitySkeleton['Skeleton'/43, l='MpServer', x=-264,44, y=19,00, z=-112,91], EntityBat['Bat'/44, l='MpServer', x=-263,94, y=19,10, z=-112,25], EntityCreeper['Creeper'/3756, l='MpServer', x=-259,50, y=40,00, z=-160,50], EntityBat['Bat'/45, l='MpServer', x=-264,31, y=19,10, z=-111,35], EntityBat['Bat'/49, l='MpServer', x=-251,47, y=26,10, z=-187,44], EntityBat['Bat'/50, l='MpServer', x=-245,50, y=26,10, z=-183,84], EntitySpider['Spider'/51, l='MpServer', x=-247,50, y=26,00, z=-183,75], EntitySpider['Spider'/52, l='MpServer', x=-243,56, y=26,00, z=-186,06], EntityBat['Bat'/53, l='MpServer', x=-235,31, y=46,77, z=-205,57], GCEntityClientPlayerMP['yasser1515'/118, l='MpServer', x=-184,49, y=65,62, z=-182,03], EntityPig['Pig'/55, l='MpServer', x=-221,09, y=64,00, z=-220,97], EntityZombie['Zombie'/1655, l='MpServer', x=-120,50, y=50,00, z=-235,50], EntityChicken['Chicken'/56, l='MpServer', x=-206,53, y=64,00, z=-232,56], EntityItem['item.item.egg'/57, l='MpServer', x=-205,69, y=64,13, z=-236,88], EntityPig['Pig'/58, l='MpServer', x=-206,34, y=64,00, z=-207,16], EntitySkeleton['Skeleton'/59, l='MpServer', x=-197,69, y=60,90, z=-205,59], EntitySquid['Squid'/60, l='MpServer', x=-196,69, y=60,03, z=-203,40]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 271171912 bytes (258 MB) / 1385168896 bytes (1321 MB) up to 2863661056 bytes (2731 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1566 51 mods loaded, 41 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1566-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1566} [Minecraft Forge](forge-1.7.10-10.13.4.1566-1.7.10.jar) 
    UCHIJAAAA   appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.3.74} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJAAAA   appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.1.2} [CoFH Core](CoFHCore-[1.7.10]3.1.2-325.jar) 
    UCHIJAAAA   BuildCraft|Core{7.1.17} [BuildCraft](buildcraft-7.1.17.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.1.17} [BC Silicon](buildcraft-7.1.17.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.1.17} [BC Transport](buildcraft-7.1.17.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.1.17} [BC Builders](buildcraft-7.1.17.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.1.17} [BC Energy](buildcraft-7.1.17.jar) 
    UCHIJAAAA   BuildCraft|Robotics{7.1.17} [BC Robotics](buildcraft-7.1.17.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.1.17} [BC Factory](buildcraft-7.1.17.jar) 
    UCHIJAAAA   cfm{3.4.8} [§9MrCrayfish's Furniture Mod](cfm-3.4.8-mc1.7.10.jar) 
    UCHIJAAAA   Eln{51} [Electrical Age](ElectricalAge_BETA-1.11_r51.jar) 
    UCHIJAAAA   IC2{2.2.736-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.736-experimental.jar) 
    UCHIJAAAA   GalacticraftCore{3.0.11} [Galacticraft Core](GalacticraftCore-1.7-3.0.11.333.jar) 
    UCHIJAAAA   GalacticraftMars{3.0.11} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.11.333.jar) 
    UCHIJAAAA   ImmibisCore{59.0.1} [Immibis Core](immibis-core-59.0.1.jar) 
    UCHIJAAAA   ThermalFoundation{1.7.10R1.2.4} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.4-114.jar) 
    UCHIJAAAA   ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion](ThermalExpansion-[1.7.10]4.1.2-240.jar) 
    UCHIJAAAA   LogisticsPipes{0.9.3.126} [Logistics Pipes](logisticspipes-0.9.3.126.jar) 
    UCHIJAAAA   MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   Railcraft{9.7.0.0} [Railcraft](Railcraft_1.7.10-9.7.0.0.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   PowerConverters{1.7.10_3.3.0-jenkins.74} [Power Converters](PowerConverters-1.7.10_3.3.0-jenkins.74.jar) 
    UCHIJAAAA   ResourceLoader{1.2} [Resource Loader](ResourceLoader-1.2.jar) 
    UCHIJAAAA   ashjacksimukraftreloaded{1.0.4a} [Sim-U-Kraft Reloaded](Sim-U-Kraft Reloaded - 1.0.4a.jar) 
    UCHIJAAAA   ThermalDynamics{1.7.10R1.2.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.2.0-171.jar) 
    UCHIJAAAA   universalcoins{1.7.10-1.6.5} [Universal Coins](UniversalCoins-1.7.10-1.6.5.jar) 
    UCHIJAAAA   worldedit{6.0-beta-01} [WorldEdit](worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
    UD  MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.82' Renderer: 'GeForce GTX 660/PCIe/SSE2'
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.1.2-325
    ThermalFoundation: -[1.7.10]1.2.4-114
    ThermalExpansion: -[1.7.10]4.1.2-240
    MineFactoryReloaded: -[1.7.10]2.8.1-174
    ThermalDynamics: -[1.7.10]1.2.0-171
    AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Launched Version: 1.7.10-Forge10.13.4.1566-1.7.10
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 660/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.82, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [FlowsHD_1.7.2]
Current Language: English (UK)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by bziemons** [comment]
Definitely a proxy error in LP (NoClassDefFound should be replaced by the general LinkageError in logisticspipes.asm.wrapper.LogisticsWrapperHandler). The error with NEI itself should have been fixes.
