### ISSUE TITLE
Rolling Machine and Crafting Pipes

### ISSUE THREAD

**Issue by Flow86** [RS485/LogisticsPipes#104]
Hi,

could it be that the rolling machine is not longer supported by the crafting pipes? since it feeds it with the ingredients, but doesnt extract the result

**Comment by bziemons** [comment]
Will be looked into.

**Comment by bziemons** [comment]
ArtForz just said in IRC, it worked on the latest build with latest RailCraft. Can you check again with that?

**Comment by Flow86** [comment]
okay I'll give it a try, but first I have to update a lot of mods ;-)

**Comment by bziemons** [comment]
How is it going?
