### ISSUE TITLE
Feature Idea, New Pipes: Crafting Import Pipe and Advanced Crafting Pipe/Module

### ISSUE THREAD

**Issue by EvilCooky** [RS485/LogisticsPipes#1040]
**Crafting Import Pipe**
A Pipe that can pull Items from Machines/Chests or act as system input when coming from BC pipes.
It checks all running crafting processes if the item is the result of one and marks that process as complete.
If the item belongs to no process, it simply enters the system with standart passive routing.

**Advanced Crafting Pipe/Module**
A better version of the Crafting Pipe/Module with three extra features.
**Feature 1**
Multiple slots for crafting results ( 4 would be good)
**Feature 2**
A toggleable feature.
When recieving a crafting command, it holds the items untill all neccessarry items are present and then pushes them into the machine.
Example: lever
The reciepe needs cobblestone and a stick.
The Advanced crafting pipe recieves the cobblestone, but holds it in its internal inventory untill it recieves the stick. Only then will it push them into the crafter.
This can help with some complexe crafting operations that need all their items at the same time.
Items also should always be pushed into the machine in the order specified in the reciepe.
**Feature 3**
A toggleable feature.
When multible crafting operations are requested, the Pipe only sends in one set of items and waits for the crafting result.
Then the next set of items is sent.

**Comment by SonOfTheStars** [comment]
Dont see the need for any of this really...all doable with what you allready have.

**Comment by hron84** [comment]
@evilcooky please tell us how it improves the current system. Neither the suggested features are impossible now. Lp has a very old friendship with bc pipes, they act as an integrant part of the Lp system. Byproduct handling is possible with an upgrade on normal crafty pipes. 

Maybe it's just me but I can't see the point.

**Comment by bziemons** [comment]
Sadly, there was no reply on @hron84's request 😞
