### ISSUE TITLE
ID 4286 always has 0 amount and is unable to request (Tekkit Legends)

### ISSUE THREAD

**Issue by jaymsDooku** [RS485/LogisticsPipes#1041]
Hello, I'm not sure if this is a problem with Tekkit Legends or Logistics Pipes but I thought I'd raise an issue here first.
Essentially, the problem is that the item with an ID of 4286:0 (Name: "10k Coolant Cell" from the IC2 mod) always returns 0 when using 'getItemAmount' even when there is clearly items available. I have used 'getAvailableItems' to done some debugging and found that it acknowledges the existence of 4286:0 as it returns it there, but it always returns 0 in 'getItemAmount' and all 'makeRequest' calls are unsuccessful.
Any idea what the problem/cause is?

**Comment by hron84** [comment]
Errm, could you please rephrase your problem including describing your setup, which (computer?) mod been involved, and giving us some version numbers (LP for example)? A screenshot about your setup would be even better.

**Comment by bziemons** [comment]
It might be that IC2 has a different metadata and LP never requested the "correct" item. Sorry for the late reply, but cannot find a solution now. Currently LP refuses to work with CC..
