### ISSUE TITLE
Drawers and Logistics

### ISSUE THREAD

**Issue by Hakameda** [RS485/LogisticsPipes#1042]
We have a max size drawer cube, 252525 and seem to get some pretty big fps spikes anytime an item goes into or leave the cube.

Any chance of looking into this, Perhaps its the Calculation of removing it with logistics, Or how the drawers themselves search for an item, Perhaps rendering so many?

1 Controller in the very middle, One Slave that pulls items out, One slave for putting items in

![2016-07-28_19 08 41](https://cloud.githubusercontent.com/assets/1900223/17234509/eec39066-54f6-11e6-87f8-e4ece11fbe3e.png)

![2016-07-28_19 08 33](https://cloud.githubusercontent.com/assets/1900223/17234510/f26328a8-54f6-11e6-9f06-2335c666fff7.png)

**Comment by 1n5aN1aC** [comment]
See #909 It's basically the same thing.

**Comment by Hakameda** [comment]
Actually, No delay or such. Only fps drops. If i'm not in the area and request. Items arrive right away and no issues. Though if others are there when i request, They get the fps drop even while items show up instantly

**Comment by Hakameda** [comment]
https://github.com/jaquadro/StorageDrawers/issues/322

**Comment by Hakameda** [comment]
https://github.com/jaquadro/StorageDrawers/issues/322

**Comment by bziemons** [comment]
Re-implemented in https://github.com/RS485/LogisticsPipes/commit/fc0bb26d82c9872343634499429f86a04a83dd15

Hopefully fixed all problems mentioned here

**Comment by Hakameda** [comment]
That's amazingOn Jun. 27, 2020 7:11 p.m., Benedikt Ziemons <notifications@github.com> wrote:
Re-implemented in fc0bb26
Hopefully fixed all problems mentioned here
