### ISSUE TITLE
Items disappear when crafting pipe puts them into a logistics crafting table

### ISSUE THREAD

**Issue by pfmoore** [RS485/LogisticsPipes#1048]
I've got an intermittent problem with my crafting tables. Sometimes, when a crafting pipe places items into the table they appear to just disappear. So the craft fails and the system gets stuck with an incomplete craft.

For example, I have a pipe/table set up for redstone torches. I requested 2, and I saw the sticks and redstone travel down the pipe to the table. But when I looked in the table's GUI, there were no items in there, and yet the craft remained incomplete (I saw no items coming out of the table, and the pipe still showed the purple "crafting in progress" particles. The statistics table shows the craft as still ongoing, too.

Manually adding the items to the table completes the craft, but the items the pipe placed there are gone - not a problem for cheap items like sticks and redstone, but I don't want to have this happen with an expensive craft!

This is the latest version, 0.9.3.126, in the FTB Infinity Skyblock pack version 1.2.0 (the latest version of the pack).

**Comment by hron84** [comment]
Could you please screenshot your current setup and the configuration of the table and also the pipe?

**Comment by pfmoore** [comment]
Sure - I'll do that this evening. I've not had much luck pinning the problem down to a specific scenario yet, though, but I'll try to do that when setting up the screenshots.

**Comment by SonOfTheStars** [comment]
Is there, by chance, another Inventory connected to the Crafting Pipe? I had a simmilar issue once were items would disappear, where i didnt notice i hate the pipe connect to some other inventory.
Sometimes the Crafting pipe then sends the items to the wrong inventory.
Or, if youre using Buildcraft Pipes instead of UnroutedTransportPipes from LP, to connect between your routed pipes, its entirely possible that somewhere down the line, those pipes touch an inventory and added the items there.

**Comment by pfmoore** [comment]
OK, some screenshots at http://imgur.com/a/V3nXQ

The redstone torch craft I've used as an example was failing most if not all of the time last night. Unfortunately, when i tried to reproduce the issue tonight, it's working OK. While I understand that "nothing's changed" is a useless thing to say (I _was_ working elsewhere in my world after I got the issue last night) I honestly don't think that I did anything that should have affected the behaviour of the crafting array.

If I can get any sort of consistent behaviour, I'll try to catch it on screenshot. And if I can see any pattern to the behaviour, I'll capture that as well. But I don't know how likely it is that I will - as at the moment, I'm mostly avoiding using autocrafting because fixing it when it breaks is a pain, so I'm tending to prefer manual crafting.

If there's any experiments you can suggest that might help determine what's happening, I'm happy to try those, too.

**Comment by pfmoore** [comment]
I've not managed to reproduce the issue, and I've been using auto-crafting pretty heavily, to try to get it to fail again. I'm inclined to write it off as something wrong with my setup, although I've no idea what. So unless you can think of anything in the code that might have caused this sort of behaviour, there's nothing much more to do and the issue can be closed. Thanks for your comments.

**Comment by hron84** [comment]
@pfmoore the "elsewhere" is far enough to cause a chunk unloading? The crafting are is chunkloaded?

**Comment by pfmoore** [comment]
No, elsewhere was at most one chunk away, and anyway I have my whole base chunkloaded (using the FTB utils chunkloading that's part of the Infinity Evolved Skyblock pack).

**Comment by hron84** [comment]
@pfmoore Hmm... that's strange then. Thanks for clarification.

**Comment by SonOfTheStars** [comment]
With NEI integration, theres often an issue, where while IC2 is present in the modpack, shift+clicking the recipe in would cause vanilla items to get assigned some random Metadata, seeable as large numer behind the ID.
For example: Stone#1:1663851891
If that happens, you can fix it by manually setting the items position in the grid up.

For your particular issue, it seems like items got sent somewhere or ended up in some place they didnt belong to on the way.
You probably fixed it by accident.
