### ISSUE TITLE
Error and terminate connection by request item on Request Pipe / MK2

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#1051]
Hi,

this problem will be happen, if i request iron ingots, cobblestone and some more items.
On rest items like gold ingot or redstone still works fine.
MC runs normal, only on request spcific items i get error and terminate connection

i used on my Server FTB Infinity Evolved.
used versions of mods are
buildcraft-7.1.16
buildcraft-compat-7.1.5
logisticspipes-0.9.3.126

Java runs on current version (1.8.0_102)

Server runs on 6GB RAM 31%-60% used
and client on 32GB RAM 29% used

thx for help
greetings

**Comment by bziemons** [comment]
We do need the error logs to fix the problem.
