### ISSUE TITLE
chassis pipes missing modules take much longer to process, possibly causing server timeouts

### ISSUE THREAD

**Issue by dualinfinities** [RS485/LogisticsPipes#1052]
I've had some issues with my server timing out constantly the past few weeks, and after installing opis and sampler, I've found that chassis pipes with fewer modules than their capacity almost always cause lag, both tick and frame.
 while you could use chassis with fewer slots in most cases, chassis performing fewer than 8 but more than 4 operations are very problematic.
while the issue ultimately needs to be fixed completely, a quick and effective stopgap measure is to make blank modules just that, BLANK modules that can be used as filler items that tell the pipe to do simply skip that modules operation (right now adding blank modules to a chassis pipe crashes the game, which you should probably take a look at).
a tooltip should probably be added to the chassis pipes and blank module in that case to make it obvious you need to do this.

I'm running the latest publicly available version on curseforge, 0.9.3.126.

**Comment by bziemons** [comment]
I've found no indication whatsoever that in the current code there is any waste in performance with the array of modules in a chassis pipe.
