### ISSUE TITLE
Soldering station autocrafting bug

### ISSUE THREAD

**Issue by Sakata-MC** [RS485/LogisticsPipes#1055]
Crafting pipes and soldering station are not working.

**Expected**:  Solder an item, put product at top left "program" (?) slot. Import recipe in pipe, order item. Items are put in 'ghost' slots, item is produced, crafting pipe is satisfied.

**Actual**: Solder an item, put product at top left "progam" (?) slot. Import recipe, order item.
Items are put in crafting grid part of inventory only (including iron ingot "fuel") and nothing is crafted.

The ghost items are indeed there.  They do look odd though.  Items are inserted in correct quantity, but not in correct slots, so soldering station never crafts the item.

**Comment by TomShkurti** [comment]
Confirmed, and consider this a broader issue: any sort of non-manual item insertion will simply fill up the slots in one-through-nine order (through-ten, counting the iron ingot slot), ignoring the ghost items completely.

**Comment by bziemons** [comment]
The soldering station was removed from LP
