### ISSUE TITLE
Item request interface quantities

### ISSUE THREAD

**Issue by firelizzard18** [RS485/LogisticsPipes#1060]
At some point, logistics request tables and other (item) request interfaces lost the ability to show detailed quantities. Used to be you could hold shift and hover over an item in the request interface and it would show a tooltip with the actual quantity.

Additionally, it would be really nice if (short) quantities would show a little more, as in 1523 displays as 1K5 instead of 1K.

**Comment by hron84** [comment]
1K5 :-1: 
1.5K :+1:

**Comment by davboecki** [comment]
@firelizzard18 Have you tried holding down Ctrl instead of shift.
@hron84 1.5K doesn't fit. There is Only space for 3 Chars that the reason for 0M1 ... and why we could only add 1K5 which is actually a valid form of 1500.

**Comment by firelizzard18** [comment]
@davboecki Ctrl totally works, thanks

**Comment by hron84** [comment]
@davboecki ohh, i didn't know the 3 char limit. Then 1K5 is the best choice.
