### ISSUE TITLE
Take a tik time up with an Extraxtor modules

### ISSUE THREAD

**Issue by AnthonyEvo** [RS485/LogisticsPipes#1063]
Dear developer! You made an outstanding modification for Minecraft which became one of the most popular and i'm happy to play with it! In a process of gaming i found some weak point in the mode. It is in Extractor Module family. When inventory which connect to the system by this module is not empty, everything works well. But when inventory becomes empty and consist more then 45 slots tik time on a server jumps up to 5-6 ms for each extraction module. I hope my message can make your modification better!

**Comment by 1n5aN1aC** [comment]
Although not a solution for servers, using a quicksort module would salve the problem in your own worlds, at least.

They're much smarter about extraction, with the caveat that sometimes it takes them a couple seconds to respond to new items.

**Comment by AnthonyEvo** [comment]
We already use them, but i have to tell about it to everyone who join our server. You project includ into FTB InfiTech. I can close recipes for Extrating modules or try to fix it by myself, i hope for your support.

**Comment by AEnterprise** [comment]
i think the only possible 'fix' for this is extractors no longer checking entire inventories every tick (like the quicksort) but other then that i doubt something can be done about it

**Comment by bziemons** [comment]
Fixed in 86015c19e41781cd92c80b0a5b72946ca344a450
