### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Hexeption** [RS485/LogisticsPipes#1066]
.

**Comment by loordgek** [comment]
why did you do that ??
@davboecki and @theZorro266 would love your help

**Comment by Hexeption** [comment]
Sure i close it because i forgot 1.10 buildcraft is not out yet. I can help out with updating 😄

**Comment by bziemons** [comment]
If we are going to update, we would do it without BuildCraft, I guess.

**Comment by AEnterprise** [comment]
buildcraft is being updated, it just takes time, also alot of things are rewritten

**Comment by Hexeption** [comment]
Cool Cool 👍
