### ISSUE TITLE
Feature request: give firewall pipes a 'direction'

### ISSUE THREAD

**Issue by firelizzard18** [RS485/LogisticsPipes#1068]
I have two logistics networks, the main network and my personal network. I'd like to be able to connect the two with a firewall pipe or something such that I can request things from my personal network OR the main network via a request pipe on my personal network; but request pipes on the main network should not be able to see anything in my personal network.

Like a private network and the public internet, with a firewall between.

But I can see no way of doing that with firewall pipes or security stations.

**Comment by 1n5aN1aC** [comment]
You can currently do this with the really "hacky" solution of using 2 security stations, along with 2 iron pipes.

Iron pipes make the logistics network "one direction" just like they do outside the LP network.

**Comment by firelizzard18** [comment]
@1n5aN1aC, thanks for the idea. I may use it, but probably not.

**Comment by 1n5aN1aC** [comment]
Also, I misspoke.  I meant 2 firewall pipes.  not Security stations.

**Comment by firelizzard18** [comment]
Turns out iron pipes do what I want
