### ISSUE TITLE
remote orderer stating twice the actual-amount stored.

### ISSUE THREAD

**Issue by usafphoenix** [RS485/LogisticsPipes#1070]
playing FTB infinity evolved skyblock and got to making logisticspipes. first time i've gotten into the mod, but noticed something pretty quick...the remote orderer apparently is reporting double the amount of every item stored in the network. (if i put 16 diamonds in, it says there are 32).

**Comment by usafphoenix** [comment]
broke down the network and rebuilt it. happens sometimes, but i'm having trouble tracing the cause consistently.

**Comment by usafphoenix** [comment]
(how does your mod report quantities?) i'm guessing it's a ticking-issue where more than one controller slave are reporting the quantity of a single storage-location that they are both connected to / within range of)

**Comment by usafphoenix** [comment]
cause found. i'm dumb. well, sortof.

if a Storage Drawer network has more than one connection point to logistics pipes (ex: storage controller + controller slave), and their points contain a provider module, this results in both points counting the drawers that each can access (overlapping the entire system because of how storage drawers works) prior to being sent to the remote orderer. admittingly, i am new to some aspects of both mods, but i did find the cause. note to self: a storage drawer network only needs a single provider module...even if multiple controller slaves are necessary to expand the network. ...cool.

**Comment by bziemons** [comment]
Okay, great 👍
