### ISSUE TITLE
Logistics Pipes causing server desync-type crash in IE Skyblock

### ISSUE THREAD

**Issue by flipperbaby** [RS485/LogisticsPipes#1071]
Posted about this on [Reddit](https://www.reddit.com/r/FeedTheBeastCrashes/comments/572zsq/infinity_evolved_skyblock_stalls_out_510_minutes/) and the [FTB forums](https://forum.feed-the-beast.com/threads/infinity-evolved-sp-desync-after-5-10-minutes.175342/#post-1752274) before I tried breaking the Logistics Power Junction block, which seems to fix everything.

The game will load fine and run for ~5-30 minutes before everything server-side goes unresponsive. It's very reproducible on [this world](https://www.dropbox.com/s/17vlya5h3xfv4zn/Autumn%20-%20Copy.7z?dl=0); it's happened on two different systems so far. Seems like whatever is happening doesn't throw any actual errors either- aside from a lack of anything obvious in the logs,  this save has the forge configs on for removing erroring entities/tile entities.

At this point I'm posting more for posterity than for assistance- I'll probably want to switch things over to AE anyway- but naturally I'd appreciate knowing what's specifically causing the issue so I can avoid it in the future.

**Comment by bziemons** [comment]
Please retry with newest build 0.9.3.130

**Comment by flipperbaby** [comment]
Thank you for the reply, very much appreciated. Unfortunately those backups
are long gone by now; I had ended up scrapping the logi network and
replacing with AE.

On Sat, May 20, 2017 at 10:20 AM, Benedikt Ziemons <notifications@github.com

**Comment by bziemons** [comment]
That's fine. Sorry for the long delay until now.
