### ISSUE TITLE
ItemModuleInformationManager.removeInformation breaks ItemIdentifier.getOrCreateTag

### ISSUE THREAD

**Issue by firelizzard18** [RS485/LogisticsPipes#1072]
In my mod, I am adding NBT tags to items to track them. If I add an NBT tag to a logistics itemsink and then try to add it to a chassis, minecraft crashes. The issue is that

  1. [`removeInformation`](https://github.com/RS485/LogisticsPipes/blob/b7a0b9bb2a3ebe2837460aea74b815d77fb0396b/common/logisticspipes/logisticspipes/ItemModuleInformationManager.java#L89-L93) sets any NBT tags on the stack that are not in it's filter to null; and
  2. [`getOrCreateTag`](https://github.com/RS485/LogisticsPipes/blob/b7a0b9bb2a3ebe2837460aea74b815d77fb0396b/common/logisticspipes/utils/item/ItemIdentifier.java#L330) calls `NBTTagCompound.copy`;
  3. Which attempts to call `NBTBase.copy` (or a override thereof) on each value;
  4. Which will throw a `NullPointerException` if any of the values are empty.

**Comment by bziemons** [comment]
Thanks for the detailed description :+1:
