### ISSUE TITLE
Unrouted transport pipes have invisible icons with the old renderer

### ISSUE THREAD

**Issue by Revemohl** [RS485/LogisticsPipes#1073]
![image](http://i.imgur.com/aXjRdlO.png)

Well yeah. The new renderer works properly but my toaster already has enough framerate problems as it is, so I'd rather not give it a few more.

**Comment by SonOfTheStars** [comment]
Well yeah there is currently not really a point to use the Old render. We added the new one for a Reason.

Old render really is nothing but a fallback anymore. Neither does it boost your performance by a noticable amount. Item Transfer on the new renderer is actually vastly better.

And yes this is intended because the pipe Texture/Model are not backwards compatible.

**Comment by hron84** [comment]
> And yes this is intended because the pipe Texture/Model are not backwards compatible.

There is no way to fall back to a static icon if the renderer cannot render an icon?

**Comment by SonOfTheStars** [comment]
I think the problem is, we dont have any modell/texture for fallback...hence the blank.
And also, what would it look like...it would probably be in a similar gray, wich would easily be confused with BC Stone-Pipes

**Comment by Bitterholz** [comment]
And again...what for are you even wanting to use Fallback renderer?

**Comment by hron84** [comment]
But item name is different, and we display names everywhere, right? Yeah, it's not an optimal solution but at least _some_. A non-obvious icon is better than no icon.

**Comment by bziemons** [comment]
The way @Bitterholz talks might make someone think, we all have the same opinion on this. The old renderer is there for two reasons actually. The first one being the design choice some people do, as the old pipes could be described as retro design. The second is performance: @davboecki and me obviously packed quite a few vertices into the new models, which obviously make more work for any GPU.

I discourage the saying that "there is no point in using the old renderer" and we should work on this issue.

**Comment by hron84** [comment]
Thanks, Mr. Zorro :-)

**Comment by bziemons** [comment]
The old renderer is not available anymore in recent LP versions
