### ISSUE TITLE
Gain independence from BC

### ISSUE THREAD

**Issue by GUIpsp** [RS485/LogisticsPipes#108]
We currently depend on BC for almost everything.

We should slowly transition away from it

**Comment by bziemons** [comment]
I do not disagree.. sadly

**Comment by ruifung** [comment]
@theZorro266 Double negative? Does this mean you agree? Or did you mean "I do not agree"?

**Comment by AartBluestoke** [comment]
there is no chance to even begin implementing our own pipe or transport code until my open PR with BC is accepted. Until then all pipe mods must use concrete subclasses of BC's tile and pipe class.

**Comment by bziemons** [comment]
@ruifung It means exactly what I said :D I do agree

**Comment by GUIpsp** [comment]
@AartBluestoke You should link that pull request

**Comment by AartBluestoke** [comment]
https://github.com/BuildCraft/BuildCraft/pull/905

**Comment by target-san** [comment]
I'd sound a heretical thought.
LP would need major rewrite at some point, possibly with moving away from BC pipes.

**Comment by davboecki** [comment]
mostly done. Only recipes are are missing but that's part of another issue.

**Comment by bziemons** [comment]
Fixed in dcf1c2eff481ef2d0514023e6cc8bb87d7170e47
