### ISSUE TITLE
thank you asie

### ISSUE THREAD

**Issue by loordgek** [RS485/LogisticsPipes#1080]
@asiekierka i see that you are updating LP

https://github.com/asiekierka/LogisticsPipes

**Comment by asiekierka** [comment]
I tried and I gave up. I would honestly vouch for a rewrite at this point, both the hackiness/glue-together-ness/cruft of certain areas of it and the amount of BC code copy-pasted into it make me ill. Sorry.

**Comment by loordgek** [comment]
do you want to work on a rewrite?? 
you did what to make your own version, LP classic ?

**Comment by asiekierka** [comment]
I considered that, but LP is not the kind of design I'm *that* interested
in. If I were to redesign it, though, I'd definitely cut down on the
features and make saner, more generic interfaces based on capabilities to
replace the proxy hell.

2016-12-26 17:42 GMT+01:00 loordgek <notifications@github.com>:

**Comment by loordgek** [comment]
do it make your own version w/ a good api to allow @davboecki and @theZorro266 to add there own stuff to it

**Comment by asiekierka** [comment]
No plans for it, sorry.
