### ISSUE TITLE
Bug with auto-crafting.

### ISSUE THREAD

**Issue by ivangouba** [RS485/LogisticsPipes#1081]
If I request one item of a recipe that crafts more items (e.g. if I request one basic logistics pipe when the recipe produces eight logistics pipes), I will get the amount I requested and the rest will pop out of the crafting pipe, getting lost if I don't personally go and grab it.

I am running logistics pipes 0.9.3.108. I couldn't try any newer versions because on the newer versions my game crashes every time I try to click something in the request table.

**Comment by 1n5aN1aC** [comment]
Do you have another place in your system for the extra pieces to be put?

If there is no other valid destination for the extras to be stored in, this will happen, and is intended in that situation.

**Comment by ivangouba** [comment]
Aww that was the issue, thank you so much.
