### ISSUE TITLE
Feature request: Don't request more stacks than there are slots

### ISSUE THREAD

**Issue by Baughn** [RS485/LogisticsPipes#1086]
Imagine you're centrifuging Gregtech ores, and have a backlog of a few dozen impure dust variants. There are two things you'd like to do:

- Some dusts need to be supplied only in multiples of N, where N ranges from 4 to 20-ish.
- The centrifuge only has two slots. Attempting to supply more than three stacks of dust at once will always fail.

The only way I've found to do the former is by using an active supplier module / supplier pipe. I've yet to find any way to accomplish the latter; no matter what combination of chassis, module or pipe I try, LP persists in delivering one stack of every dust that is requested.

How am I meant to accomplish this?

**Comment by bziemons** [comment]
Usually machines provide their maximum size of contents in the API. How do you connect the machine when you get that error?

**Comment by Baughn** [comment]
I had a pipe connected directly to a Gregtech centrifuge. I believe I tried several different variants of supplier and chassis pipes...

However, I have since given up on playing Gregtech, so I can't confirm this anymore.

It seems like the basic IInventory API should be sufficient, though.

**Comment by bziemons** [comment]
We'll just close this now. This seems to specific, as misusing APIs is not our problem.
