### ISSUE TITLE
Conflict with Thut's Elevators

### ISSUE THREAD

**Issue by Zacraft210** [RS485/LogisticsPipes#1088]
Hello!

I've made professional modpack for years now for multiple server hosts and gaming groups. This modpack (Realm of Brostice) is a personal modpack of mine for a group a friends.

There seems to be a conflict between Thut's Elevators and Logistics Pipes. Here is the crash report:
http://pastebin.com/zPciCLnD
The crash continued after another launch. I was able to determine the conflict by removing Logistics Pipes from the modpack and running again. Launch was successful.

I keep a log of all activity/actions while building or updating a modpack. Here is a link to the Build log for this modpack. 
https://docs.google.com/spreadsheets/d/1gMGYCBOiway9c_U_MhivJrEXOuT_jAuaIN3NnySiP_s/edit?usp=sharing
The sheet labeled "BUILD LOG RoB 4.0" lines 200-232 is where the details of this conflict can be found.

**Comment by bziemons** [comment]
We try to load the OpenComputers API, which is not there. No idea why that triggers Thut's Elevators at all. It seems like it's not our fault.

**Comment by davboecki** [comment]
Looks rather the other way around. Thut's Elevators has a dependency on the OpenComputers API which can't be found. I'm not sure why LP would cause this...

**Comment by bziemons** [comment]
Closed, as we do not expect our fault and there was no more activity.
