### ISSUE TITLE
Feature Request: New / Additional Crafting options via the Request Table

### ISSUE THREAD

**Issue by Bomave** [RS485/LogisticsPipes#1090]
Hello :-),

I hope this idea hasn't been posted yet. I tried to look it up by searching the enhancement issues but couldn't find it.

Today I came across a question with the painting machine from Ender IO. I always try to cover up as many recipes as possible in my autocrafting system in many (maybe too many) machines but sometimes it's just not enough because a machine can have so many recipes. How do I cover up all those recipes?

My idea was to add the option in the Request Table that you can select a specific machine in a list of specified machines, open it's interface, place your items in the slots and let the system put the items into that machine to do the job. This specific machine will need to be connected to a new pipe which could be called "Too Many Recipes Pipe" or something. I'm sure you can find a better name for it :-). Also you should be given the option to select how many times it should craft / smelt / alloy smelt it. If you then try to smelt or alloy smelt something in the same machine it would be blocked and give you the hint that it's blocked until the order before has been completed or put it in the next available machine with the "Too Many Recipes Pipe".

Side question: What is the Crafting Cleanup Upgrade actually doing?

Thanks in advance!

Bomave

**Comment by bziemons** [comment]
Hey, we talked about this idea and we didn't think this would fit into LP.
LP in my opinion is mostly about setting up an autonomous and letting that run. Except for the requesting part there is no user interaction and you would recommend extending that user interaction. I don't know if I like that.

~~The Crafting Cleanup Upgrade is for extracting items once a crafting task is complete. You can apply it to a crafting pipe and select an item that should be taken out after crafting. E.g. an empty bucket, when there is a recipe that uses a full water bucket, but the crafting grid always leaves behind an empty one.~~

**Comment by davboecki** [comment]
Just to clarify the usage of the **Cleanup Upgrade**. The Cleanup Upgrade, like the name says is used to cleanup your Crafting Table or Machines. It does**n't** have a real usecase in normal crafting operations as it only triggers when the crafting pipe has nothing to do and not after every crafting task. For those kind of tasks, where there is a byproduct with every crafting step, you need to use an **Byproduct Extraction Upgrade**. It allows you to specify an item that is extracted in combination with every crafting task. 
The Cleanup Upgarde comes into play, when a crafting task is canceled. As in these cases the items already inside the crafting table will stay there, any only the selected crafting task and all the related tasks are canceled. This can happen when you break a pipe out of a current running crafting task, or when the server restarts. It's more for people tinkering around with a new setup where they destroy parts of that system when they run different tests and not for day to day use (At least that's the intention).
