### ISSUE TITLE
{Bug Came Back Again} Logistics Pipes Losing and Duplicating Items - Dedicated Server on other machine

### ISSUE THREAD

**Issue by Cybotive** [RS485/LogisticsPipes#1091]
So my setup is a Request Table connected to a power junction which is in turn connected to mk3 chassis pipes on Alchemical Chests (I also tried Iron Chests mod and Vanilla). Inside the chassis pipes are poly itemsink, mod based itemsink, and provider modules. the very last chest just has provider and itemsink set to default path. I have 8 chests in a row, and when i sorted stuff, I could always see the package in the pipe ending up in the right spot, but the request table wouldn't show it, and even if it did, the chest would be completely empty to my view. Now I'm using Mk2 pipes because i realized i dont need the poly itemsinks. What I did was troubleshot that if i broke it off after 3 chests, it works fine. So what i did, was after the 3 chassis pipes connected to chests, I put 1 basic log. pipe. After that is 4 more chassis pipes with alchemical chests, so far so good and its working as expected. It took me hours to troubleshoot this bug. It just didnt like my row of 8 chests. The duplicating comes from me taking items out of chests that actually showed up in the chest. If i took the item, the request table still saw it and would give me a duplicate if i asked for it.

Update: bug came back again, so the below setup is not actually working. I just updated from build 50 something to i think 128 (latest), on both server and client, and it didn't fix it. Also, it seems not be bugged in singleplayer. Only on my server is it bugged.

This is my working setup:
![2017-03-29_14 45 15](https://cloud.githubusercontent.com/assets/19524327/24478104/7a057476-148e-11e7-897e-89cff3287fa1.png)
![2017-03-29_14 45 45](https://cloud.githubusercontent.com/assets/19524327/24478107/7bdd3036-148e-11e7-98ee-cc189c333fe0.png)

**Comment by hron84** [comment]
Do you use Bukkit / Sponge / Spigot on the server?
