### ISSUE TITLE
Logistics Pipes

### ISSUE THREAD

**Issue by TMPJoker** [RS485/LogisticsPipes#1097]
Dear Authors, I was wondering if you have discontinued logistics and if so, I would like to take it up witha. Buddy of mine and make a legacy version, my email is ytremors@gmail.com, please contact with response if you want

**Comment by 1n5aN1aC** [comment]
...There was even a commit like 2 days ago.

I don't know if there's any plans to update to 1.10, but it's definitely still getting some love.

**Comment by bziemons** [comment]
You can, of course, take the source code and make a legacy version with your buddy. But I am afraid that we have not discontinued Logistics Pipes. We just had a lot of other things happening in life.
