### ISSUE TITLE
Supplier pipe partial requests

### ISSUE THREAD

**Issue by MrTJP** [RS485/LogisticsPipes#11]
a supplier pipe set to partial requests will request one item, wait until it receives it, then request another, over and over until it satisfies the settings.  It wont request multiple items at once..

never mind.  had to do with the way forestry machines accept items.

**Comment by AartBluestoke** [comment]
when partial requests fail, it instantly re-trys at 1/2 the size, until either 1 is not available, or it finds a size that works. 
The next request is twice the size of one of the previous one that succeeded, or only 1 if the previous request didn't.

That means that partial providers on uses about the same cpu as partial off, especially in the case where a large amount is requested and non is available.

**Comment by MrTJP** [comment]
the forestry farm block was reporting only 1 inventory size open.  so, it had to keep doing it 1 by 1, until all 64 were in there.

**Comment by AartBluestoke** [comment]
closing this as i do not believe there is an issue here.

suppliers do throttle down when ingredients are not available. if a request fails, then next request will be for 1 ingredient, so supplying 2 items, one of which is not available will resort to supplying the other 1 at a time. 

Requests double on each success. if all requested items are delivered, max is set to 1024 items.
