### ISSUE TITLE
Logistic pipes cause server shutdown

### ISSUE THREAD

**Issue by dnangel8042110** [RS485/LogisticsPipes#1101]
Yesterday, I was playing Project Ozone 2 (currently using LP build 128).
When I put a TE power supplier upgrade into a crafting pipe MK3, the server shutdown.
I'm not the server owner, so I can't see the crash report or something.
Other players still keep playing after server reboot in the case of my base doesn't get chunk load.

**Comment by davboecki** [comment]
Please contact the server owner, so that you can post a crash report here, because without one there is nothing we can do.
And we would need to know what was connected to that crafting pipe MK3 as well.

**Comment by dnangel8042110** [comment]
The server owner just removed the pipe.
What connected to the MK3 were 3 cobblestone pipes and a logistic crafting table without any config.
I wonder if you can test it in your development environment, if none of issue shows up, I might consider that as a hard drive issue, and report to my server owner as well.
Thanks for the effort you guys made.

**Comment by hron84** [comment]
@dnangel8042110 could you make a screenshot about your exact configuration?

**Comment by dnangel8042110** [comment]
Sorry, I already abandoned that world.
