### ISSUE TITLE
Active supplier loop in chassis caused ores to disappear.

### ISSUE THREAD

**Issue by Hking0036** [RS485/LogisticsPipes#1102]
I have a chassis connected to a chest that ores sort into. I set up crafting tables with crafting pipes to craft bars into blocks so that it would take up less space, I also set up crafting tables with pipes to craft blocks back into bars, So if you request 11 bars it can uncraft a block and spit 2 bars out at you. However, once I set up the active supplier module to supply the chest with blocks infinitely it repeatedly sent them back and forth, crafting blocks, then returning them to the chest, then taking them out, making bars, and recrafting them into blocks infinitely. Drained all the power in the system. I changed the setting on the module and it stopped sending them out, however now about 3/4 of everything that got sorted has disappeared and I'm not sure where. I checked all the crafting tables and only a few have maybe 1 or 2 bars, not the stacks that it was sorting in the first place. I'm running logisticspipes-0.9.3.132.

Opened a testing world and the same thing happens with supplier/provider pipes individually as well.

Also, are there any plans for OreDict on the crafting tables too? For some reason forestry tin/copper blocks take precedence over the others, but I only have IC2 worldgen on, so I had to make two crafting tables.

**Comment by Hking0036** [comment]
Here's a 7z with the exact mods and configs, with a copy of the world as it is currently, and a backup from the day before where I tried to make it replicable: https://drive.google.com/open?id=0B09ZqzABOnZTWmRTLTE1RVBNY2s

**Comment by 1n5aN1aC** [comment]
1.  The tables have oredict, you just have to use the fuzzy table & the upgrade for the crafting pipe.
2.  The behavior you experienced is expected, as it was trying to craft as many blocks as it could, so it was getting ingots from blocks.  :)  You have to use one of a variety of workarounds to get that functionality.  I prefer to use StorageDrawers.
3.  However, the disappearance of your items is perplexing though, that definitely shouldn't happen, even in an infinite loop like that....

**Comment by Hking0036** [comment]
I think it just flowed too much into the pipes at once and they despawned, no issues since. Thanks for the advice on storage drawers.

**Comment by hron84** [comment]
@Hking0036 Also, Storage Drawers cab help you in oredict issues too, as they autoconvert ingots in a same oredict entry. Just make sure you "format" the drawer with the ingot you want  to use later. So, if you prefer Forestry copper/tin ingots over IC2 ones (this is totally understandable) then you have to use Forestry ingots to configure the drawer (even if you just cheat them in, if you use the lock key, drawer will not forget the ingot, you can throw the cheated items out after it). Later, in crafting tasks you can use forestry ingots for recipes.
