### ISSUE TITLE
Crafting table treated as default route

### ISSUE THREAD

**Issue by usafphoenix** [RS485/LogisticsPipes#1105]
So it took me some time, but i found after trying to craft some quantum solar panels, that the panels went missing (located them a few weeks after cheating in a replacement due to thinking it was a glitch or item was dropped into world and despawned)...found them in a crafting table that had a pipe that wasn't configured.
So my idea is this: you know how the logistics system bridge/connector pipe often used with enderstorage has three different colors for the square to signify link status? (green, yellow,red)... is it possible to do the same on a crafting pipe that isn't configured? If configured and matches table: green, if pipe or table has a mis-match recipe: red, if there is no recipe and crafting table will be treated as a default route: yellow.
(or whatever). This because it's often difficult to find that one table that has a pipe but was never actually configured once you have a chunk FULL of them. lol.
Or maybe have the pipe show a red outline until it has a recipe in it? idk. Or maybe i should just not be an idiot and place down a whole bunch of crafting tables and pipes all at once....that works too >.>

**Comment by usafphoenix** [comment]
...or maybe just have in the tooltips for the pipe, that if placed down next to a tileentity with inventory and not configured, it may be treated as a default route and your items may be difficult to find lol

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
