### ISSUE TITLE
Upgrades not showing up in NEI

### ISSUE THREAD

**Issue by Fortist** [RS485/LogisticsPipes#1106]
I tried looking through the issues, but maybe Im dyslexic but I cant seem to find a similar issue.
Anyway for some time now, every so often, when I look up logistics pipes in NEI the pipe upgrades are gone and I have no idea what causes this.

![noupgrads](https://user-images.githubusercontent.com/5784537/28184398-406e9bc4-67e1-11e7-8133-65d7af3b313a.png)

**Comment by mgdgfbhevdyeh** [comment]
i have same isseus

**Comment by bziemons** [comment]
And what did you search for?
