### ISSUE TITLE
Items disappearing after autocrafted in logistics crafting table

### ISSUE THREAD

**Issue by Xtermin** [RS485/LogisticsPipes#1107]
Hey, hope you can help
I'm auto-crafting hardened Pulverizers on a skyblock.
I started in a regular crafting table however that wouldnt accept my basic pulverizers, therefore i used a fuzzy with a fuzzy upgrade on the crafting pipe. 
The request for the pulverizer is accepted but as soon as all the items are in the crafting table they get used up and i get a golden stary animation to show its working, but all the pulverizers i should be receiving just vanish.
Hope someone can enlighten me as to what I'm doing wrong

**Comment by hron84** [comment]
Could you please provide us version numbers? Like, LP version, ThermalExpansion version, and Forge. It could be help devs to make more relevant aswer to your problem. Also please try out newest LP jar if it is possible.
