### ISSUE TITLE
Secure Request and Provider Pipes 

### ISSUE THREAD

**Issue by TomShkurti** [RS485/LogisticsPipes#1108]
I'd like to see an upgrade for provider pipes that will allow them to 'stamp' some sort of security card that can be placed in request tables/pipes. Then, only tables that have a copy of the card can request what the pipe is providing. This would be useful in situations such as the following: you have a chest full of food, and a chest full of diamonds; you want to be able to access the food from anywhere in a large public area, but the diamonds only from a personal request table in your base; but so that you can access the food from your personal table as well (and to keep things simpler) both have to be on the same logistics network. You could connect the food chest to a regular provider pipe, and the diamonds chest to a secure one, and only produce one card that is put in your personal request table.

**Comment by davboecki** [comment]
This is mostly what the firewall pipe was designed to do. It lets you define items that are either black- or whitelisted. Your Idea sounds interesting, but is probably to complicated as soon as autocrafting is involved.
