### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by Greg9711** [RS485/LogisticsPipes#1109]
So back in may on one closed issue that was called "Logistics Pipes", theZorro266 said "We just had a lot of other things happening in life" as a response. With that said does that mean you guys have a bit more time now and are there any slight plans for logistics pipes getting to a newer version? The reason i´m asking is that i really love this mod, its my favourite of all time and everytime i play a newer modpack i wish logistics pipes to be here. There is no rush if there still isn´t enough time or you guys don´t feel like updating is yet thats perfectly fine, just would like to have some clarity.

Sincerely,

some guy on the internet

**Comment by hron84** [comment]
@Greg9711 Logistics PIpes is a very old and complex mod and needs a lot of love _before_ it could be ported into 1.8+. There were some guys around who tried it hard but failed or did not have enough time to finish. As far as I know, @Bitterholz was one of them. I love it too but I absolutely understand what's going on and also a _lot_ of players stuck on 1.7 and play actively, requesting features and bugfixes. Also there is a lot of content-heavy modpack on 1.7 that depends on LP heavily and it also generates fixable issues.

**Comment by SonOfTheStars** [comment]
@Greg9711 @hron84 Actually, LogisticsPipes2 is under quite active development. A link to it is in the readme under Other Repositories/Projects.

I can happily announce that we have working routed transfer and are about to implement rendering item travel

**Comment by hron84** [comment]
@Bitterholz really? It's so awesome, you make a great progression! What do you think when we can have something that we can happily break and report issues against? :smiley:

**Comment by SonOfTheStars** [comment]
No idea when we will give an Alpha version. Were still on a very debug ish state of the implementation.

Like currently you can send an item from a source to all destinations, i.e. take N items out of an adjacent inventory for N other destinations and send them down their paths

**Comment by SonOfTheStars** [comment]
If you want to talk about the current state further, visit our repo ;)

**Comment by hron84** [comment]
I'd glad, but sadly I currently have no time. But I can't wait seeing LP in the fresh, 1.10-1.11 era. I definitelly don't want to see our old friend die.

**Comment by SonOfTheStars** [comment]
Also in a fresh look and design

**Comment by Greg9711** [comment]
YEEEEEEEES. And thanks for the response, i´m looking forward to what will happen. :)

**Comment by SonOfTheStars** [comment]
@Greg9711 take a look at [Logistics Pipes 2](https://github.com/Bitterholz/LP2)

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/issues/1117
