### ISSUE TITLE
"Built-in" provider in request table?

### ISSUE THREAD

**Issue by iarspider** [RS485/LogisticsPipes#1110]
Is it possible to make Request Table to look inside it's inventory when requesting items for manual crafting (using "+/++/+++" buttons)? This is very useful for chained recipes (e.g. Storage Drawers upgrades)

**Comment by hron84** [comment]
I'd be a big fan of this. I always empty my request table just because LP does not handle its inventory correctly and force-requests items even if it is not really needed.

**Comment by Aeraggo** [comment]
Agreed, would be useful. The tilde (~) icon will request just what's needed to complete the recipe, taking the inventory contents into account, however that's only useful if you're crafting just a single/couple of something at a time.

**Comment by Mattabase** [comment]
Yeah the tables needs some quality of life love in 1.12

This being one of them. I will edit this will more later.

**Comment by bziemons** [comment]
Added in *Logistics Request Table Improvements* in https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
