### ISSUE TITLE
MC 1.10.2

### ISSUE THREAD

**Issue by Trellinane** [RS485/LogisticsPipes#1111]
Any chance of a 1.10.2 Port?

**Comment by hron84** [comment]
#977 #1109 

DUPE.

**Comment by SonOfTheStars** [comment]
@Trellinane take a look at [Logistics Pipes 2](https://github.com/Bitterholz/LP2)

**Comment by bziemons** [comment]
:horse_racing:

**Comment by davboecki** [comment]
See https://github.com/RS485/LogisticsPipes/issues/1117
