### ISSUE TITLE
Chassis with Crafting Module cannot select OreDict, IgnDamage, IgnNBT, or OrePrefix like Crafting Logistics Pipes can

### ISSUE THREAD

**Issue by Tyler799** [RS485/LogisticsPipes#1112]
See title. The Crafting Logistics pipe can select OreDict, IgnDamage, IgnNBT, or OrePrefix for any material in a crafting recipe.

A chassis pipe with a crafting module cannot. As far as I can tell, it's impossible to fix. Fuzzy module can't be applied to chassis pipes, so that's out of the question.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
