### ISSUE TITLE
Disabling of new textures

### ISSUE THREAD

**Issue by DragonGamees** [RS485/LogisticsPipes#1113]
Hello, How in Logistix Pips to include render old textures instead of new ones?

**Comment by loordgek** [comment]
it has it use the network tool on air and you can select the old one

**Comment by DragonGamees** [comment]
More in detail please. And I can do it without compilation?

**Comment by 1n5aN1aC** [comment]
He is saying you can't easily do it out of game.

Once in-game, you can use the network tool" by right-clicking with it in the open air, and it will give you an in-game configuration GUI, where you can enable the old or new textures from in game!
