### ISSUE TITLE
Feature request - distributed autocrafting

### ISSUE THREAD

**Issue by Nightcaste** [RS485/LogisticsPipes#1114]
I would like it if it were possible to set up multiple autocrafting points for making the same thing and have LP evenly spread the load across those points.  

For example, the Thermal Expansion induction smelter for making steel requires iron and pulverized coal in specific ratios.  

Due to the processing time, I would like to set up three or four of these machines, and have the LP give each of them a portion of the job to do.

The currently available item moving options don't really account for this, and you end up with mismatched quantities gumming up your machines.

Maybe some kind of chassis module that lets you link the specified locations as a group, and when you establish the crafting recipe you can specify that it gets sent to that group?

I don't know how hard it would be to make this happen, and I'm not sure I'm explaining it clearly.

**Comment by bziemons** [comment]
I guess I do not completely understand.. what does not work with the current distribution of autocrafting?
