### ISSUE TITLE
Items disappear when logistics crafting table outputs them into a logistics crafting pipe

### ISSUE THREAD

**Issue by Bitek1993** [RS485/LogisticsPipes#1116]
I have a problem, i made a request system using logistics pipes, and now i'm making a crafting system, and when i for example request for 1 copper cable from Industrial craft 2, the logistics crafting table should make 6 cables (because that's their amount while crafting) send one to me, and leave 5 cables inside, but this 5 cables are disappearing, and i don't want to waste my copper and other items. i've also connected provider logistics pipes to craftings, so the next time, another items, won't be used, because, pipes will take already done items from the Logistics crafting, but they can't. Please help! And sorry for ma bad English.

**Comment by loordgek** [comment]
do you have a default pipe setup ??

**Comment by Bitek1993** [comment]
what does it mean? the only thing i've changed in my pipes is that in output of for example copper cable crafting is only one copper cable, not six, and I thought the others will stay inside

**Comment by loordgek** [comment]
i dont think you can do that

**Comment by Bitek1993** [comment]
but when i set it to 6 cables on output, and i order only one, the others are dissapearing, what can i do with that?

**Comment by loordgek** [comment]
place a basic pipe on a chest and set it to default route

**Comment by Bitek1993** [comment]
thank you very much, now i can also connect this chest to the provider pipe, and it actually solves all my problems, thanks again
