### ISSUE TITLE
Any chance of this mod going to 1.12 ? 

### ISSUE THREAD

**Issue by Roman-Simik** [RS485/LogisticsPipes#1117]
Title says it all :) if yes, what are the expectations for the time when this will be done? I really dont need any better or new functions, this mod have everything I need, just need to be ported to the new versions

**Comment by loordgek** [comment]
this is dead look at https://github.com/SonOfTheStars/LP2
lp2 will skip 1.12

**Comment by Roman-Simik** [comment]
And LP 2 project is for which version? there's not any description of that. Is it done or not, Im missing any info on that LP2.

**Comment by davboecki** [comment]
Just as a note, this is dormant not dead.
We have been working on an update in the background but our time is super limited right now, so we can't even test what we have done.
For those that are still watching this, and want to help us test what we have got so far, this is a one time permission to DM me on discord and request an LP version for you to test and report bugs to us.
But be warned. Testing means testing. There are bugs in there that WILL DESTROY your world.

**Comment by Roman-Simik** [comment]
@davboecki I'm interested in that! Where I can contact you? (can't find you on discord by your github name).

**Comment by loordgek** [comment]
it is just davboecki on discord

**Comment by Roman-Simik** [comment]
@davboecki @loordgek I need also four digit code to be able to add him. like "davboecki#****"

**Comment by loordgek** [comment]
no you dont

**Comment by loordgek** [comment]
![knipsel](https://user-images.githubusercontent.com/4789835/44795583-534b4800-abab-11e8-9779-b0a8d4f70bd1.PNG)

**Comment by Roman-Simik** [comment]
I'm not that dumb, tried this but when i type "@davboecki" or only "davboecki", it finds nothing
![image](https://user-images.githubusercontent.com/41468539/44795835-f0a67c00-abab-11e8-83ba-55a92212a96b.png)

**Comment by loordgek** [comment]
![dav](https://user-images.githubusercontent.com/4789835/44796411-3a439680-abad-11e8-899c-cfd3d8f12efa.PNG)
works for me

**Comment by Roman-Simik** [comment]
Idk, what's the problem, but that's not the problem we want to solve, can you try provide me the four digit code?

**Comment by loordgek** [comment]
https://discord.gg/Jp7jkQ he is in there that is the channel for LP2

**Comment by davboecki** [comment]
You can find me in our RS485 discord here: https://discord.gg/6vPP3A8

**Comment by bziemons** [comment]
Test builds are now available here: https://ci.rs485.network/job/LogisticsPipes-0.10-mc112/

Have fun.
