### ISSUE TITLE
Tesseracts eat liquid routed through them

### ISSUE THREAD

**Issue by AartBluestoke** [RS485/LogisticsPipes#113]
any liquid routed into a tesseract does not make it out the other side.

**Comment by ArtForz** [comment]
Expected behaviour I think, you're not supposed to send LP fakeliquidcontainers over anything not a LP

**Comment by AartBluestoke** [comment]
It means that things like creosote production has to be in the vicinity of the wooden tie crafter; and make water delivery to carpenters anoying, with a water source needed inside each sub-network, and closer than any other reachable by tesseract.

it also means that you can't use extractors, as they will happily sink infinite amount of liquid to any source on the network, (provide/supply doesn't work yet, with the supplier still having an item interface, not a liquid interface like on the basic liquid pipe)

**Comment by bziemons** [comment]
You mean liquid containers routed through an item tesseract removes them? No way, I have done that before..

**Comment by AartBluestoke** [comment]
@theZorro266 doesn't work for me in the latest dev : 
![image](https://f.cloud.github.com/assets/1892829/736060/7a656f04-e308-11e2-97aa-6c6d1dd102de.png)

**Comment by bziemons** [comment]
Fixed in f6cfa474582b6de578b2f866a5a989311444f73b
