### ISSUE TITLE
java.util.ConcurrentModificationException (maybe an issue with tesseracts )

### ISSUE THREAD

**Issue by d1223m** [RS485/LogisticsPipes#114]
(With build 565)

```
  Minecraft has crashed!      
  ----------------------      
```

Minecraft has stopped running because it encountered a problem; Ticking tile entity

A full error report has been saved to /Applications/MultiMC.app/Contents/Resources/instances/Kuyas Playing/minecraft/crash-reports/crash-2013-07-02_18.39.28-server.txt - Please include a copy of that file (Not this screen!) if you report this crash to anyone; without it, they will not be able to help fix the crash :(

--- BEGIN ERROR REPORT c6bd1b3b --------
Full report at:
/Applications/MultiMC.app/Contents/Resources/instances/Kuyas Playing/minecraft/crash-reports/crash-2013-07-02_18.39.28-server.txt
Please show that file to Mojang, NOT just this screen!

Generated 7/2/13 6:39 PM

-- Head --
Stacktrace:
    at java.util.AbstractList$Itr.checkForComodification(AbstractList.java:372)
    at java.util.AbstractList$Itr.next(AbstractList.java:343)
    at logisticspipes.pipes.basic.CoreRoutedPipe.getQueuedForItemStack(CoreRoutedPipe.java:1042)
    at logisticspipes.transport.PipeTransportLogistics.resolveDestination(PipeTransportLogistics.java:171)
    at buildcraft.transport.PipeTransportItems.entityEntering(PipeTransportItems.java:114)
    at buildcraft.transport.TileGenericPipe.entityEntering(TileGenericPipe.java:362)
    at buildcraft.transport.TileGenericPipe.entityEntering(TileGenericPipe.java:379)
    at thermalexpansion.util.Utils.addToAdjPipe(Utils.java:123)
    at thermalexpansion.block.tesseract.TileTesseractItem.receiveItem(TileTesseractItem.java:131)
    at thermalexpansion.block.tesseract.TileTesseractItem.sendItem(TileTesseractItem.java:111)
    at thermalexpansion.block.tesseract.TileTesseractItem.func_70299_a(TileTesseractItem.java:238)
    at buildcraft.core.inventory.InventoryIteratorSided$InvSlot.setStackInSlot(InventoryIteratorSided.java:61)
    at buildcraft.core.inventory.TransactorSimple.addToSlot(TransactorSimple.java:78)
    at buildcraft.core.inventory.TransactorSimple.tryPut(TransactorSimple.java:48)
    at buildcraft.core.inventory.TransactorSimple.inject(TransactorSimple.java:35)
    at buildcraft.core.inventory.Transactor.add(Transactor.java:15)
    at buildcraft.core.utils.Utils.addToRandomInventory(Utils.java:82)
    at buildcraft.factory.TileQuarry.mineStack(TileQuarry.java:446)
    at buildcraft.factory.TileQuarry.positionReached(TileQuarry.java:414)
    at buildcraft.factory.TileQuarry.moveHead(TileQuarry.java:769)
    at buildcraft.factory.TileQuarry.func_70316_g(TileQuarry.java:154)

-- Tile entity being ticked --
Details:
    Name: Machine // buildcraft.factory.TileQuarry
    Block type: ID #1918 (tile.machineBlock // buildcraft.factory.BlockQuarry)
    Block data value: 5 / 0x5 / 0b0101
    Block location: World: (224,63,-81), Chunk: (at 0,3,15 in 14,-6; contains blocks 224,0,-96 to 239,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Actual block type: ID #1918 (tile.machineBlock // buildcraft.factory.BlockQuarry)
    Actual block data value: 5 / 0x5 / 0b0101
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2202)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:546)

-- Affected level --
Details:
    Level name: A Whole New World
    All players: 1 total; [EntityPlayerMP['d1223m'/103, l='A Whole New World', x=-247.84, y=65.00, z=117.95]]
    Chunk stats: ServerChunkCache: 748 Drop: 0
    Level seed: -3792136650513045325
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (112,64,-61), Chunk: (at 0,4,3 in 7,-4; contains blocks 112,0,-64 to 127,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 19292136 game time, 21429148 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 5929 (now: true), thunder time: 39297 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:654)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:573)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:127)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:470)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)

-- System Details --
Details:
    Minecraft Version: 1.5.2
    Operating System: Mac OS X (x86_64) version 10.7.5
    Java Version: 1.6.0_45, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 391001000 bytes (372 MB) / 878370816 bytes (837 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 3 total; -XX:MaxPermSize=128m -Xms512m -Xmx1024m
    AABB Pool Size: 1625 (91000 bytes; 0 MB) allocated, 1454 (81424 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 6, tallocated: 62
    FML: MCP v7.51 FML v5.2.23.738 Minecraft Forge 7.8.1.738 46 mods loaded, 46 mods active
    mcp{7.51} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{5.2.23.738} [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{7.8.1.738} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHFramework{1.5.2.5} [CoFH Framework](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{0.8.6.15} [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.5.2.25} [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{1.5.2.5} [CoFHCore](CoFHCore-1.5.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHWorld{1.5.2.5} [CoFHWorld](CoFHCore-1.5.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ChickenChunks{1.3.2.11} [ChickenChunks](ChickenChunks 1.3.2.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ComputerCraft{1.53} [ComputerCraft](ComputerCraft1.53.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CCTurtle{1.53} [ComputerCraft Turtles](ComputerCraft1.53.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderStorage{1.4.2.11} [EnderStorage](EnderStorage 1.4.2.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtrabiomesXL{3.13.4} [ExtrabiomesXL](ExtrabiomesXL-universal-1.5.2-3.13.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    factorization{0.7.37} [Factorization](Factorization-0.7.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    factorization.misc{0.7.37} [Factorization Miscellaneous Nonsense](Factorization-0.7.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    factorization.dimensionalSlice{0.7.37} [Factorization Dimensional Slices](Factorization-0.7.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.54b} [Inventory Tweaks](InventoryTweaks-1.54b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{3.7.1} [BuildCraft](buildcraft-A-3.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{3.7.1} [BC Energy](buildcraft-A-3.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion{2.4.6.0} [Thermal Expansion](ThermalExpansion-2.4.6.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2{1.115.348-lf} [IndustrialCraft 2](industrialcraft-2_1.115.348-lf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forestry{2.2.8.1} [Forestry for Minecraft](forestry-A-2.2.8.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{3.0.5e} [Thaumcraft](Thaumcraft3.0.5e.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{3.7.1} [BC Builders](buildcraft-A-3.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{3.7.1} [BC Transport](buildcraft-A-3.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{3.7.1} [BC Silicon](buildcraft-A-3.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{3.7.1} [BC Factory](buildcraft-A-3.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Railcraft{7.2.1.0} [Railcraft](Railcraft_1.5.2-7.2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TwilightForest{1.18.1} [The Twilight Forest](twilightforest-1.18.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GregTech_Addon{MC151} [GregTech-Addon](gregtechmod%282%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LogisticsPipes|Main{0.7.3.dev.565} [Logistics Pipes](LogisticsPipes-MC1.5.2-0.7.3.dev.565.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIPlugins{1.0.9.2} [NEI Plugins](NEIPlugins-1.0.9.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OCS{1.5.2.0} [OpenCCSensors](OpenCCSensors-1.5.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MiscPeripherals{3.3} [MiscPeripherals](miscperipherals-3.3e.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenPeripheral{0.1.7} [OpenPeripheral](OpenPeripheral-0.1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    iChunUtil{1.0.1} [iChunUtil](iChunUtil1.0.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PortalGun{1.5.2} [PortalGun](PortalGun1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SoulShards{1.0.16} [Soul Shards](SoulShards-1.0.36-universal-srg.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_ReiMinimap{v3.3_06 [1.5.2]} [mod_ReiMinimap]([1.5.2]ReiMinimap_v3.3_06.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BinnieCore{1.6-pre17} [Binnie Core](extra-bees-1.6-pre17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraBees{1.6-pre17} [Extra Bees](extra-bees-1.6-pre17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{5.2.6.430} [Iron Chest](ironchest-universal-1.5.2-5.2.6.430.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MagicBees{2.0.2} [Magic Bees](magicbees-2.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AdvancedSolarPanel{3.3.7} [Advanced Solar Panels](mod_AdvancedSolarPanels_3_3_7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GraviSuite{1.9.2} [Gravitation Suite](mod_zGraviSuite_1_9_2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OmniTools{3.1.6.0} [OmniTools](OmniTools-3.1.6.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 965 (54040 bytes; 0 MB) allocated, 786 (44016 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['d1223m'/103, l='A Whole New World', x=-247.84, y=65.00, z=117.95]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

java.util.ConcurrentModificationException
    at java.util.AbstractList$Itr.checkForComodification(AbstractList.java:372)
    at java.util.AbstractList$Itr.next(AbstractList.java:343)
    at logisticspipes.pipes.basic.CoreRoutedPipe.getQueuedForItemStack(CoreRoutedPipe.java:1042)
    at logisticspipes.transport.PipeTransportLogistics.resolveDestination(PipeTransportLogistics.java:171)
    at buildcraft.transport.PipeTransportItems.entityEntering(PipeTransportItems.java:114)
    at buildcraft.transport.TileGenericPipe.entityEntering(TileGenericPipe.java:362)
    at buildcraft.transport.TileGenericPipe.entityEntering(TileGenericPipe.java:379)
    at thermalexpansion.util.Utils.addToAdjPipe(Utils.java:123)
    at thermalexpansion.block.tesseract.TileTesseractItem.receiveItem(TileTesseractItem.java:131)
    at thermalexpansion.block.tesseract.TileTesseractItem.sendItem(TileTesseractItem.java:111)
    at thermalexpansion.block.tesseract.TileTesseractItem.func_70299_a(TileTesseractItem.java:238)
    at buildcraft.core.inventory.InventoryIteratorSided$InvSlot.setStackInSlot(InventoryIteratorSided.java:61)
    at buildcraft.core.inventory.TransactorSimple.addToSlot(TransactorSimple.java:78)
    at buildcraft.core.inventory.TransactorSimple.tryPut(TransactorSimple.java:48)
    at buildcraft.core.inventory.TransactorSimple.inject(TransactorSimple.java:35)
    at buildcraft.core.inventory.Transactor.add(Transactor.java:15)
    at buildcraft.core.utils.Utils.addToRandomInventory(Utils.java:82)
    at buildcraft.factory.TileQuarry.mineStack(TileQuarry.java:446)
    at buildcraft.factory.TileQuarry.positionReached(TileQuarry.java:414)
    at buildcraft.factory.TileQuarry.moveHead(TileQuarry.java:769)
    at buildcraft.factory.TileQuarry.func_70316_g(TileQuarry.java:154)
    at net.minecraft.world.World.func_72939_s(World.java:2202)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:546)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:654)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:573)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:127)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:470)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
--- END ERROR REPORT a4a5cf38 ----------

**Comment by d1223m** [comment]
(edited) IRC follow up for reference:

20:53 <+ArtForz> aye, please issue, this looks weird
20:54 <+ArtForz> looks like a quarry sticking something into a tesseract that beams it to another tesseract that sticks it into a basic LP
20:55 < kuya> ahh
20:55 < kuya> i have a question about tesseracts
20:55 < kuya> does LP do something funky with them?
20:55 < kuya> because weird things are happening that i dont expect to happen
20:55 <+ArtForz> yea
20:56 < kuya> stuff is getting routed to a tesseract when i dont really want it to be so i presumed something odd was happening
20:56 <+ArtForz> we have some rather... special code to allow LP to route items over tesseracts under certain conditions
20:56 <+ArtForz> basically if you have 2 tesseracts set to send/recv and one LP on each ... the whole thing acts as a routed LP link

20:58 < kuya> i have a send only and a recieve only and stuff on the send only network is getting routed to the tesseract like it knows where its going
20:58 <+ArtForz> what I don't get is how we can get a comodificationexception here?

20:58 @theZorro266 maybe because of what he just said
20:58 < kuya> my instant reaction is that routing via tesseracts is going to be confusing to user and dev :)
20:59 @theZorro266 That makes no sense :D
20:59 <+ArtForz> afaict the only things touching queuedDataForUnroutedItems is getQueuedForItemStack and queueUnroutedItemInformation
21:00 < kuya> what i said makes no sense?
21:00 <+ArtForz> no, the exception
21:00 < kuya> aha
21:00 <+ArtForz> getQueuedForItemStack is only called from transport.resolveDestination

21:01 <+ArtForz> hrrrrrm

21:03 <+ArtForz> queueUnroutedItemInformation is called from tesseractconnection.transmit (makes sense)
21:03 < kuya> certainly the tesseracts with two networks is the last thing i changed and iv not has this before
21:04 <+ArtForz> theZorro266: you could be right with the sync issue...

21:07 < kuya> slightly different topic... how could i disable this tesseract linking? its not really what i want :)
21:07 < kuya> i suppose enderchests wouldnt link?
21:07 <+ArtForz> I have a hunch about what's going on

21:08 <+ArtForz> what prevents clientside stuff calling SpecialTileConnection.trnasmit?
21:09 <+ArtForz> which then ends up calling TesseractConnection.getConnections
21:10 <+ArtForz> which then does SimpleServiceLocator.thermalExpansionProxy.getConnectedTesseracts(tile) <- pretty sure this gets _server_ side tiles
21:10 <+ArtForz> and things quickly go boom from there.
21:12 <+ArtForz> now how on earth to repro that...
21:12 -!- samrg472 is now known as tst
21:12 < kuya> maybe if i go afk again? :D
21:13 <+ArtForz> gah, can't think straight today
21:14 <+ArtForz> please file a issue, I'm way too tired to try follow this call chain and how we might end up mixing server and client tiles

**Comment by ArtForz** [comment]
Whoops, sorry for the auto-close... please check if dev build 569 still does that.

**Comment by bziemons** [comment]
@DZCreeper I know what you say is true, but I do not know if that comment belongs here.
@d1223m Can you test if it works, please?

**Comment by d1223m** [comment]
I have changed my setup but I have no crashes like this since.

**Comment by bziemons** [comment]
Then I just assume this is fixed, until someone has the issue again and opens a new ticket.
