### ISSUE TITLE
link to changes for 1.6.1

### ISSUE THREAD

**Issue by AartBluestoke** [RS485/LogisticsPipes#116]
https://docs.google.com/spreadsheet/ccc?key=0AhdLhUzgJSx2dFdsMk1SbDdQRTdQMXVuenBEcmpHbmc#gid=0

and 
http://titanpad.com/7uXjfWGt4x

links posted in #minecraftForge

**Comment by Flow86** [comment]
those changes do NOT reflect the changes in the current forge for mc 1.6.1, but its a good start to look at.
