### ISSUE TITLE
Action speed upgrade effects do not diminish after module removal

### ISSUE THREAD

**Issue by davisjw** [RS485/LogisticsPipes#1161]
Branch: dev-mc1122

Replication:
mk{n} chassis, extractor module, module upgrade, apply action speed upgrade
- remove action speed upgrade after applying; extraction speed does not decrease
- reapplying action speed upgrade after removal; extraction speed increases to next speed up
- this affect remains after extraction module removal/reinsertion
- replacing the pipe removes the affect
- does not drop any additional action speed upgrades when the pipe is broken after removing the modules (eg. not a dup bug)

**Comment by davisjw** [comment]
Submitted pull request with fix.
Unable to replicate after fix applied

**Comment by dblsaiko** [comment]
Fixed in https://github.com/RS485/LogisticsPipes/commit/97cb9f0d70cd28ec70f5c109051195a3a46ca8b5
