### ISSUE TITLE
State of the mod

### ISSUE THREAD

**Issue by 016Nojr** [RS485/LogisticsPipes#1163]
It's a rare case I ever ask about this, but I am curious since I am working on a pack that is considering adding Logistics Pipes to it.

How much work is left/planned before an alpha or beta will be released on Curse, I have used the builds on Jenkins, but publishing the pack requires all mods to be hosted on Curse.

**Comment by bziemons** [comment]
I'm gonna copy whats been in Discord yesterday. There is no ETA, but this is an incomplete  list of things left doing:

> [9:03 AM] davboecki: Well BC and TD integration for a start
> [9:03 AM] davboecki: I just yesterday resurected computer support
> [9:03 AM] davboecki: most mod compatibility was gone
> [9:03 AM] davboecki: Still need to check out the complete energy system.
> [9:04 AM] davboecki: finish removing the MK2 and MK3 variants for speed
> [9:04 AM] davboecki: Then there is currenlly an overhaul of the crafting logic in process
> [9:05 AM] davboecki: Any way to many small things listed in our bugtracker

I do not think the crafting (or generally requesting) overhaul is going in before a Curse release, but thats the current state we are working on. Feel free to hit us up on Discord and ask questions there :)

**Comment by 016Nojr** [comment]
Thanks for the answer @theZorro266, Is there a Discord link somewhere?

**Comment by dblsaiko** [comment]
Here: https://discord.gg/6vPP3A8

**Comment by 016Nojr** [comment]
Thanks
