### ISSUE TITLE
Soldering Station Crash

### ISSUE THREAD

**Issue by TimGoll** [RS485/LogisticsPipes#1168]
https://gist.github.com/TimGoll/e411508b837aa05273677d728d041d28

MC 1.12.2
Forge *.68
Logisticspipes: 0.10.1.92

I tried to open the Gui with a rightklick and it instantly crashed

**Comment by TimGoll** [comment]
It does only happen at this GUI, the others are fine

**Comment by dblsaiko** [comment]
Yup, my bad
Although the soldering station currently has no recipes at all so you're not missing out :P

**Comment by davboecki** [comment]
Just FYI. Soldering Station is on the to be removed list.

**Comment by TimGoll** [comment]
Okay. Perfect, thanks. I'll hide it with crafttweaker for now :)
