### ISSUE TITLE
Missing support for newer Minecraft versions

### ISSUE THREAD

**Issue by werwolfberlin** [RS485/LogisticsPipes#1170]
Is it possible to bring this wonderful addon to a newer minecraft version? I loved it. There is no satisfying replacement in the newer modpacks. :-(

**Comment by dblsaiko** [comment]
It's currently being developed for 1.12.2... There's builds on the [CI](https://ci.rs485.network/job/LogisticsPipes-0.10-mc112/)

Warning: it's currently alpha though and some stuff is still missing.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/issues/1117
