### ISSUE TITLE
Parsing error loading recipe logisticspipes:sign_creator

### ISSUE THREAD

**Issue by Maxwelljones** [RS485/LogisticsPipes#1171]
Not sure from where this is coming from, but the item (sign creator) has then no crafting recipe.

[latest.log](https://github.com/RS485/LogisticsPipes/files/2608288/latest.log)

Forge: 14.23.5.2768
Logistics Pipes version: 0.10.1.77

I guess it's coming from another mod, but can't figure out.

**Comment by dblsaiko** [comment]
Oh, right. Ugh, this was caused by a fix for another bug.
