### ISSUE TITLE
Stability question. 

### ISSUE THREAD

**Issue by mindcloud69** [RS485/LogisticsPipes#1173]
Is the 1.12.2 version sable enough for use in a single player game with the understanding that it is still in beta?

**Comment by bziemons** [comment]
It is not even in beta. And this question cannot be answered. I know for a fact that there are items which will be removed before beta. Also backwards compatibility is not the biggest concern. So probably not, but you have to decide for yourself.

We will publish our builds on CurseForge when the beta comes out. If you want beta builds, have an eye on our CurseForge project https://minecraft.curseforge.com/projects/logistics-pipes

**Comment by mindcloud69** [comment]
Thank you and I appreciate all your work.
