### ISSUE TITLE
Add "G" case to item stack size.

### ISSUE THREAD

**Issue by davboecki** [RS485/LogisticsPipes#1178]
https://github.com/RS485/LogisticsPipes/blob/dev-mc1122/common/logisticspipes/utils/string/StringUtils.java#L105
Because: 
![image](https://user-images.githubusercontent.com/1119689/49284485-08d0b480-f495-11e8-8017-80e6481d7fb5.png)

**Comment by Bernasss12** [comment]
I'm working on this one

**Comment by dblsaiko** [comment]
Implemented in 0e18a85.
