### ISSUE TITLE
Crash on RF Supplier Upgrade

### ISSUE THREAD

**Issue by Ernti** [RS485/LogisticsPipes#1182]
Game crashes when an RF supplier upgrade is applied to pipe.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LogisticsPipesCoreLoader (logisticspipes-0.10.1.108.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 12/11/18 6:37 PM
Description: Ticking block entity

java.lang.IllegalStateException: stream has already been operated upon or closed
	at java.util.stream.AbstractPipeline.spliterator(AbstractPipeline.java:338)
	at java.util.stream.ReferencePipeline.iterator(ReferencePipeline.java:139)
	at logisticspipes.pipes.basic.PowerSupplierHandler.update(PowerSupplierHandler.java:84)
	at logisticspipes.pipes.basic.CoreRoutedPipe.enabledUpdateEntity(CoreRoutedPipe.java:338)
	at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:439)
	at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_73660_a(LogisticsTileGenericPipe.java:211)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.stream.AbstractPipeline.spliterator(AbstractPipeline.java:338)
	at java.util.stream.ReferencePipeline.iterator(ReferencePipeline.java:139)
	at logisticspipes.pipes.basic.PowerSupplierHandler.update(PowerSupplierHandler.java:84)
	at logisticspipes.pipes.basic.CoreRoutedPipe.enabledUpdateEntity(CoreRoutedPipe.java:338)
	at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:439)
	at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_73660_a(LogisticsTileGenericPipe.java:211)

-- Block entity being ticked --
Details:
	Name: logisticspipes:pipe // logisticspipes.pipes.basic.LogisticsTileGenericPipe
	Block type: ID #291 (tile.logisticspipes.pipe // logisticspipes.pipes.basic.LogisticsBlockGenericPipe // logisticspipes:pipe)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (1012,4,-151), Chunk: (at 4,0,9 in 63,-10; contains blocks 1008,0,-160 to 1023,255,-145), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Actual block type: ID #291 (tile.logisticspipes.pipe // logisticspipes.pipes.basic.LogisticsBlockGenericPipe // logisticspipes:pipe)
	Actual block data value: 0 / 0x0 / 0b0000
	LP-Version: 0.10.1.108:false
	Pipe: logisticspipes.pipes.PipeItemsBasicLogistics
	Transport: ~~NULL~~
	Router: ServerRouter: {ID: 3, UUID: beab587d-6d50-4b94-beec-2e358a3a2c1d, AT: (0, 1012, 4, -151), Version: 1), Destroied: false}
	stillNeedReplace: false
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World-
	All players: 1 total; [EntityPlayerMP['d3m0nic34gle'/0, l='New World-', x=1013.23, y=4.00, z=-148.86]]
	Chunk stats: ServerChunkCache: 2401 Drop: 0
	Level seed: -5737580964361858401
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (1009,4,-156), Chunk: (at 1,0,4 in 63,-10; contains blocks 1008,0,-160 to 1023,255,-145), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Level time: 5948 game time, 5948 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 92849 (now: false), thunder time: 156094 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2122452552 bytes (2024 MB) / 3992977408 bytes (3808 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2795 Optifine OptiFine_1.12.2_HD_U_E3_pre 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version      | Source                                          | Signature                                |
	|:------ |:------------------- |:------------ |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2       | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                 | 9.42         | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2795.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2795 | forge-1.12.2-14.23.5.2795.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | buildcraftlib       | 7.99.20      | buildcraft-all-7.99.20.jar                      | None                                     |
	| LCHIJA | buildcraftcore      | 7.99.20      | buildcraft-all-7.99.20.jar                      | None                                     |
	| LCHIJA | buildcraftbuilders  | 7.99.20      | buildcraft-all-7.99.20.jar                      | None                                     |
	| LCHIJA | buildcrafttransport | 7.99.20      | buildcraft-all-7.99.20.jar                      | None                                     |
	| LCHIJA | buildcraftsilicon   | 7.99.20      | buildcraft-all-7.99.20.jar                      | None                                     |
	| LCHIJA | buildcraftcompat    | 7.99.20      | buildcraft-all-7.99.20.jar                      | None                                     |
	| LCHIJA | buildcraftenergy    | 7.99.20      | buildcraft-all-7.99.20.jar                      | None                                     |
	| LCHIJA | buildcraftfactory   | 7.99.20      | buildcraft-all-7.99.20.jar                      | None                                     |
	| LCHIJA | buildcraftrobotics  | 7.99.20      | buildcraft-all-7.99.20.jar                      | None                                     |
	| LCHIJA | codechickenlib      | 3.2.2.353    | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux        | 2.1.0        | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore            | 4.6.1        | CoFHCore-1.12.2-4.6.1.22-universal.jar          | None                                     |
	| LCHIJA | cofhworld           | 1.3.0        | CoFHWorld-1.12.2-1.3.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalfoundation   | 2.6.1        | ThermalFoundation-1.12.2-2.6.1.22-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalexpansion    | 5.5.2        | ThermalExpansion-1.12.2-5.5.2.39-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | logisticspipes      | 0.10.1.108   | logisticspipes-0.10.1.108.jar                   | 4ab9c640e37baa2d4eca3354863a84d2c06bee42 |

	Loaded coremods (and transformers): 
LogisticsPipesCoreLoader (logisticspipes-0.10.1.108.jar)
  logisticspipes.asm.LogisticsClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['d3m0nic34gle'/0, l='New World-', x=1013.23, y=4.00, z=-148.86]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3_pre
	OptiFine Build: 20181203-111256
	Render Distance Chunks: 24
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 416.81
	OpenGlRenderer: GeForce GTX 1080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by dblsaiko** [comment]
It's trying to call stuff on that stream multiple times. Yeah, that won't work. Fix incoming :P
