### ISSUE TITLE
Exception loading model when minimap Mod Active

### ISSUE THREAD

**Issue by Ernti** [RS485/LogisticsPipes#1183]
Tested with Xaero's Minimap and Voxel map(litemod)

Game starts but every Logistics Pipe is pink(no texture)

**Comment by dblsaiko** [comment]
It works for me, tested it with MapWriter 2 and JourneyMap. Not sure what the ones you have tested do differently.

**Comment by davboecki** [comment]
The only thing I can think of, is that it is linked to #1186 .

**Comment by davboecki** [comment]
Looks like https://github.com/RS485/LogisticsPipes/issues/1199 is broader. Moving discussion there,
