### ISSUE TITLE
Suggestion: Option to disable NBT checking for crafting pipes/chips

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#1184]
Minecraft: 1.12.2
Logistics Pipes: 0.10.1.109
Forge: 14.23.5.2768

I recently have installed the mod in a huge modpack, and it appears to have trouble with NBT tags for some items. Since I can't disable the crafting NBT checks it refuses to craft the item. Having the option to disable the NBT checking would solve this problem.

**Comment by kyazuki** [comment]
Logistics Fuzzy Crafting Table & Logistics Crafting Pipe(installed Fuzzy Upgrade) may solve it.

**Comment by ghost** [comment]
> Logistics Fuzzy Crafting Table & Logistics Crafting Pipe(installed Fuzzy Upgrade) may solve it.

I'll have to check this out, thanks.
