### ISSUE TITLE
Active supplier module & Supplier pipe infinite request

### ISSUE THREAD

**Issue by ArmaWizard** [RS485/LogisticsPipes#1185]
Active supplier modules and supplier pipes request infinite items when connected to ANY inventory.

**Test setup:**

Logistics MK2 - Active supplier module - Bulk 50 (30 cobblestone) - Vanilla chest
Items keep coming indefinitely, regardless of what setting.

**Comment by bziemons** [comment]
Current workaround: Downgrade to build 100 or below
