### ISSUE TITLE
[1.12.2]Soldering Station Recipe?

### ISSUE THREAD

**Issue by kyazuki** [RS485/LogisticsPipes#1187]
I can't look Mk2,3 Modules' recipes on jei.
How can I know recipes on Soldering Station?

**Comment by dblsaiko** [comment]
The soldering station is currently not implemented (and afaik to be removed)

Which modules are you talking about? Some of the Mk2+ stuff is also going to be removed in favor of upgrades

**Comment by kyazuki** [comment]
Thanks!

I want Extractor Module Mk3.
Mk1 is too slow...

**Comment by dblsaiko** [comment]
There's upgrades for that. I think you're looking for the Item Extraction Upgrade, and Item Stack Extraction Upgrade. (You can apply upgrades to modules using the Module Upgrade)

**Comment by kyazuki** [comment]
I didn't use Upgrades in older version, so I don't notice it.
Thank you!
