### ISSUE TITLE
Crafting Pipe doesn't take output from Advanced Crafting Table

### ISSUE THREAD

**Issue by Ernti** [RS485/LogisticsPipes#1188]
Crafting works fine but the output stays in the crafting table.

**Comment by bziemons** [comment]
I guess you mean the BuildCraft Advanced Crafting Table? That was (in all those years of LP and BC) always the case. The Advanced Crafting Table does output to a nearby inventory automatically. So put a chest right next to it and use the satellite pipe. That's what that is for. If you have more questions, ask right away :)

**Comment by Ernti** [comment]
It has worked before without a chest. But even the import and open buttons from the crafting pipe aren't working...
