### ISSUE TITLE
something isn't naming buildcraft facades right : Requested: 6 Facade < BROKEN (0:0 )>

### ISSUE THREAD

**Issue by AartBluestoke** [RS485/LogisticsPipes#119]
Requested: 1 Wooden Transport Pipe
Request successful!
Requested: 6 Facade < BROKEN (0:0 )>
Request successful!

not sure if it is BC or LP with this issue as the tooltip in the remote requester is correct.

**Comment by davboecki** [comment]
It's LP. LP only uses ItemId And Metadata to determine the items name. The name is checked client side so the server sends the ItemID and metaData to the client and he generates the message. In new buildcraft versions the facade type is saved inside the NBTTagCompound which is not used by LP to check the item name.

**Comment by ArtForz** [comment]
Fixed in 4780384
