### ISSUE TITLE
[1.12.2]Some problems

### ISSUE THREAD

**Issue by kyazuki** [RS485/LogisticsPipes#1191]
1. EU transport doesn't work.
   EU provider & transport/eu supplier module doesn't supply eu to IC2 machines.

2. Supplier pipe/module are strange.
  All modes work as Infinitie Mode.

**Comment by kyazuki** [comment]
3. Item Sink Module doesn't work to Black Hole Unit(from Industrial Foregoing) which inculdes some items.
   Basic Logistics pipe work normally.

**Comment by hron84** [comment]
Could you please add versions here? Mods, Forge...

**Comment by kyazuki** [comment]
Sorry, logisticspipes-0.10.1.109.jar and forge-1.12.2-14.23.5.2796-universal.jar

Oops, I accidentally close this issue.

**Comment by davboecki** [comment]
Could you please open a separate issue for each of your issues, otherwise keeping track of them is going to be difficult. (You don't need to open one for the supplier pipe, that is a known issue at the moment)

**Comment by kyazuki** [comment]
OK, Thanks!
