### ISSUE TITLE
[1.12.2] crafting pipe can not use the furnace

### ISSUE THREAD

**Issue by baka-gourd** [RS485/LogisticsPipes#1193]
**Crafting pipe** **cannot** extract the objects in the furnace.
But the pipe can be put into the item.

**Comment by NarigudoBR** [comment]
is it the vanilla furnace? if it is, use a satellite pipe with the crafting pipe attached to a hopper bellow the furnace

**Comment by baka-gourd** [comment]
@NarigudoBR 
Hmm,I found a way.
satellite pipe(e.g. Iron ingots x8)
vanilla furnace
crafting pipe(e.g. coal x1)
This structure do not use a hopper.

**Comment by bziemons** [comment]
Honestly, I do not understand what you mean. Can you attach screenshots of your original build?

**Comment by baka-gourd** [comment]
> Honestly, I do not understand what you mean. Can you attach screenshots of your original build?

Crafting pipes cannot pull items from above.
![2019-01-11 14-01-47](https://user-images.githubusercontent.com/36119339/51015989-7d753380-15a9-11e9-9732-52b7db4e41d4.png)
(1.7.10)
![2019-01-11_14 04 43](https://user-images.githubusercontent.com/36119339/51016092-f5435e00-15a9-11e9-989d-edd99d477676.png)
(1.12.2)
1.12.2 can not be automated using the method of 1.7.10, at least the furnace can not.
            ---------------By Google Translate
I am a Chinese player, so please forgive me in English.

**Comment by dblsaiko** [comment]
Yeah, that's probably because the vanilla furnace is now sided, as in the slot in the inventory that gets accessed varies per side. Top is input, bottom is output, the rest is fuel, iirc.

**Comment by bziemons** [comment]
Yeah, almost correct. Bottom is fuel and output, sides are fuel only and top is input only. So as it was said before by @baka-gourd: crafting pipe below with feeding fuel normally and the input via a satellite pipe on the top works fine.
This can be closed.
