### ISSUE TITLE
{1.12.2] packethandler NPE

### ISSUE THREAD

**Issue by Yoghurt4C** [RS485/LogisticsPipes#1195]
https://paste.dimdev.org/nogupifele.mccrash

**Comment by davboecki** [comment]
Any more information about this issue? When did this happen? Caused this a crash?

**Comment by Yoghurt4C** [comment]
happened spontaneously, caused repeated crashes (suppressed by vanillafix but seemingly endlessly replicating) until reboot

**Comment by davboecki** [comment]
And without vanillafix?
Oh and could you post a full log?

**Comment by davboecki** [comment]
Oh and could you post a full log?

**Comment by Yoghurt4C** [comment]
[2019-01-08-2.log](https://github.com/RS485/LogisticsPipes/files/2753338/2019-01-08-2.log)

**Comment by bziemons** [comment]
There should only be one way of the buffer becoming null: when two threads work on the same memory address. That makes sense in this case, because the error is thrown in the packet decompressor thread here. I have synchronized the appropriate parts of the code.

Please re-test with build 111.
