### ISSUE TITLE
LiteLoader mod causes "PurpleBlack" texture error.  

### ISSUE THREAD

**Issue by CrossVas** [RS485/LogisticsPipes#1199]
Minecraft setup:
- MC Version: 1.12.2
- Forge Version: 1.12.2-forge1.12.2-14.23.5.2780
- LP Version: #_[110](http://ci.rs485.network/job/LogisticsPipes-0.10-mc112/110/)
- CCL Version: CodeChickenLib-1.12.2-3.2.2.353-universal
- LiteLoader Version: liteloader-1.12.2-SNAPSHOT-r4CC2BB0-b4-4

Also got this in log file on load (might help /or not)
[log.txt](https://github.com/RS485/LogisticsPipes/files/2753422/log.txt)

**Comment by davboecki** [comment]
Could you post a full log?

**Comment by CrossVas** [comment]
[latest.log](https://github.com/RS485/LogisticsPipes/files/2753541/latest.log)

**Comment by davboecki** [comment]
This has probably been fixed by https://github.com/RS485/LogisticsPipes/issues/1186 as well. It would be great if you could check if this error still happens in the newest version.

**Comment by CrossVas** [comment]
Yep, sorry for late respons.
I've just tried the latest version of LP (0.10.1.122) and it seems to be fixed.
Thanks!

**Comment by bziemons** [comment]
Thanks for checking :)
