### ISSUE TITLE
Migrate to forge's ISidedInventory

### ISSUE THREAD

**Issue by GUIpsp** [RS485/LogisticsPipes#120]
(bug because mods have started killing forge's ISided)

**Comment by AartBluestoke** [comment]
I agree that we will need to remove forge ISided soon, it has been @deprecated for a while. As it is still in forge (as of 2013-07-09) we won't remove it quite yet. We will check again before doing our first 1.6 release, but it appears that ISided is still in forge for atleast another version.

**Comment by Flow86** [comment]
its removed:

Build 1.6.2-9.10.0.786
    cpw: Remove forge ISidedInventory, deprecated since 1.5.

**Comment by GUIpsp** [comment]
@Flow86 We will remove it when we go to 1.6

**Comment by AartBluestoke** [comment]
done in 16 branch
