### ISSUE TITLE
[1.12.2]Black Hole Unit/Tank (from Industrial Foregoing)

### ISSUE THREAD

**Issue by kyazuki** [RS485/LogisticsPipes#1200]
Item Sink Module doesn't work to Black Hole Unit(from Industrial Foregoing) which inculdes some items.
Basic Logistics pipe work normally.

Logstics Fluid Basic Pipe doesn't fill Black Hole Tank.

**Comment by bziemons** [comment]
I guess this already worked last year and this issue was just overseen. Just tested it with and everything works as expected.
