### ISSUE TITLE
Caught exception from Logistics Pipes (logisticspipes)

### ISSUE THREAD

**Issue by MairuFrost** [RS485/LogisticsPipes#1206]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Logistics Pipes (logisticspipes)
[crash-2019-02-13_01.05.27-client.txt](https://github.com/RS485/LogisticsPipes/files/2859597/crash-2019-02-13_01.05.27-client.txt)

Logistics Pipe 112
CodeChicken Lib 1.12.2-3.2.2.353-universal

**Comment by davboecki** [comment]
You need to use the normal jar, not the dev.jar
