### ISSUE TITLE
Logistic pipes 0.10.1.112 fail on load with latest thermal dynamics

### ISSUE THREAD

**Issue by Electrofried** [RS485/LogisticsPipes#1207]
Latest version (and last one) exit on load when used with newer versions of thermal dynamics on both client and server.   Attached relevant part of logs.

[logistic crash.txt](https://github.com/RS485/LogisticsPipes/files/2872715/logistic.crash.txt)

**Comment by HFinner** [comment]
Can confirm I am also having this issue
