### ISSUE TITLE
[Feature Request] Button to request available resource

### ISSUE THREAD

**Issue by tjsd** [RS485/LogisticsPipes#1208]
In the UI for the request table I would like a button to request the remaining items.

Like if there was 47 lapis left, just a one click request all.

**Comment by bziemons** [comment]
Does the ~ button not fit your needs?

**Comment by davboecki** [comment]
I think he want's to just request all of one item. Nothing to do with the crafting part of the request table.

If that is the case just use Ctrl + A to "select all" items of the current selected item. It will set the request amount to the total number of available items.

**Comment by tjsd** [comment]
ctrl + a completly solves my issue, I had no idea that was an option!
