### ISSUE TITLE
Compability issue with Gregtech CE machines

### ISSUE THREAD

**Issue by tjsd** [RS485/LogisticsPipes#1209]
LP doesn't access the inventory of Gregtech Community Edition blocks in the correct way.

**Comment by SonOfTheStars** [comment]
To clear this up:

- Chassis pipes are able to insert an Item into the pipe, but unable to extract it.
- Same for crafting pipes
- Satellite pipes are completely unable to insert items at all, regardless of what side they are mounted to

**Comment by Cyprex** [comment]
>Chassis pipes are able to insert an Item into the pipe, but unable to extract it.

Into the pipe? Did you mean into the machine?

**Comment by davboecki** [comment]
The remaining problem with the satellite pipe should be fixed with https://github.com/RS485/LogisticsPipes/commit/eb617b906d8dd3ea386c3b89d30bc77ed9726008

Everything else should have been fixed, already.
