### ISSUE TITLE
old pipe textures 1.12

### ISSUE THREAD

**Issue by Spenny519** [RS485/LogisticsPipes#1211]
is there a way to get the old pipe textures in 1.12?

**Comment by davboecki** [comment]
No only the new pipe textures and models were ported to 1.12

**Comment by spikespaz** [comment]
This is dumb. This is all so stupid. I'm glad you guys want to use your fancy new OBJ renderer but the models and textures just do not fit with the theme of the rest of the game and they look silly compared to BuildCraft pipes. Why must you be different and force it down our throats? The least you could do is leave the option in to use the old textures and models for f*s sake.

**Comment by bziemons** [comment]
@spikespaz you went way overboard with that comment. The old models did not work with newer Minecraft versions and needed to be ported. Davboecki set the priority to release for MC 1.12, but we welcome your pull request to add back the old models and textures. How do you like that?

**Comment by spikespaz** [comment]
@bziemons Accepted!
