### ISSUE TITLE
Advanced Extractor Module sends items to default route even with a valid destination

### ISSUE THREAD

**Issue by DrizzitDudden** [RS485/LogisticsPipes#1215]
#### Modpack and LP version
Enigmatica 2 version 1.62 for Minecraft 1.12.2
Logistics Pipes 0.10.1 #112

#### Issue description
The Advanced Extractor Module appears to pull 2 items or stacks per operation with one going to the expected destination and the other to a default route. Regular Extractor Module works as expected.

#### Steps to reproduce the issue

1. System has 3 chests. 
a. 1st has a chassis with Advanced Extractor Module. "Dump Chest"
b. 2nd has a Chassis with Polymorphic ItemSink Module. "Cobblestone Chest"
c. 3rd has a Chassis with ItemSink Module set to Default Route. "Overflow Chest"
2. Place 1 cobblestone in Cobblestone Chest.
3. Place multiple cobblestone in Dump Chest.

#### What's the expected result?

- All cobblestone should be sent to the Cobblestone Chest.

#### What's the actual result?

- Around half of the cobblestone will arrive in the Overflow Chest.

#### Additional details / screenshot

- [Imgur album showing steps to replicate](https://imgur.com/a/1H1baOB)
- [Youtube video demonstrating bug](https://youtu.be/7RAKOrNStQg)

**Comment by hron84** [comment]
Beautifully documented issue! :-)

**Comment by davboecki** [comment]
Thanks for this greatly documented Issue. With this, I was able to track down the problem in no time and fix it. Greatly appreciated.
