### ISSUE TITLE
 bug with vanillafix mod

### ISSUE THREAD

**Issue by llronaldoll** [RS485/LogisticsPipes#1217]
the texture of most of the blocks and items in Logistic pipes and Buildcraft do not appear when Vanillafix is ​​added to the modpack @

**Comment by hron84** [comment]
Please give us some version numbers (forge/Logistics Pipes/VanillaFix). Also please ensure you use the latest version of all mods and Forge.

**Comment by davboecki** [comment]
Probably fixed by https://github.com/RS485/LogisticsPipes/issues/1186. If not please reopen the issue.
