### ISSUE TITLE
Requester crashes the game when it tries to show tooltips

### ISSUE THREAD

**Issue by Buff555** [RS485/LogisticsPipes#1221]
I would have reported it sooner but Github was giving me issues with the login system. This happens every time I hover over an item in the requester block. My setup is very simple. It's just two crystal chests joined together by basic pipes and an MK8 Chase with a provider and extractor card. The system is powered by galacticraft's solar panel.
[crash-2019-04-17_17.03.04-client.txt](https://github.com/RS485/LogisticsPipes/files/3100113/crash-2019-04-17_17.03.04-client.txt)

**Comment by kni0002** [comment]
I'm getting the same issue, I have a logistics system setup, chests full of stuff ect. but when I open the table and tool tips appear it crashes
[crash-2019-05-19_00.20.57-client.txt](https://github.com/RS485/LogisticsPipes/files/3194154/crash-2019-05-19_00.20.57-client.txt)
