### ISSUE TITLE
Missing bee related pipes?

### ISSUE THREAD

**Issue by v1993** [RS485/LogisticsPipes#1223]
I'm playing on minecraft 1.12.2 and all bee related pipes (analyzer, beesink, etc.) seems missing.

Are they deleted, not yet implemented or is it a bug? Of course, forestry is installed and working. If it matters, I've installed LP after world creation.

**Comment by Ihamfp** [comment]
They got removed here: https://github.com/RS485/LogisticsPipes/commit/4d4af4d13b12d9f280b77f155cd699ea5a9bcf5b

**Comment by v1993** [comment]
Why? Those pipes are really useful…

**Comment by bziemons** [comment]
Explanation is here: #1167
