### ISSUE TITLE
[1.12.2] Configurable number prefixes

### ISSUE THREAD

**Issue by Bernasss12** [RS485/LogisticsPipes#1225]
Add config option to choose between:

**[K]ilo - [M]ega - [G]iga** _(Default)_
or 
**[K]ilo - [M]illion - [B]illion**

Only changes one character but there are mixed opinions

**Comment by hron84** [comment]
**Private Opinion Warning**

Since the SI prefix system is used in MC in general, I don't see it makes sense to change this behavior in LP. Mekanism, AE and many other mods use SI prefixes to shorten the displayed values, if LP would provide the feature you request other mods would not follow, so you could end up displaying incoherent values. It would look bad.

**Comment by Bernasss12** [comment]
I only used G because it was what the issue to add it asked for, whilst discussing with other developers we all had the same opinion that Billions made more sense and is more widely used but even then LP isn't the widely used mod anyways, no other mod uses the 0M1 notation instead of 0.1M.
That's why I thought I would bring this up as an issue and implement it myself if necessary

**Comment by bziemons** [comment]
> [...] whilst discussing with other developers we all had the same opinion that Billions made more sense and is more widely used [...]

Even if I saw [K]ilo - [M]illion - [B]illion in the past, I didn't agree. But if people want it, I am fine with making a config option for it.

**Comment by hron84** [comment]
Keep in your mind, English terminology is bit misleading about these prefixes. Billion (at least) in Hungarian language means thousand times more than in english (`1_000_000 ^ 2` not `1000 ^ 3`). I can imagine there are more languages where it could cause confusions. SI prefixes are more standards and less language-dependent.

**Comment by bziemons** [comment]
It is very much the same in German @hron84 

But we haven't decided yet, if this issue is ever going to be implemented. I am open for PRs, but I wouldn't give this priority in my own work queue.

**Comment by dblsaiko** [comment]
Kilo doesn't really fit with Million and Billion imo since it's like a different "unit". You'd have to replace it with Thousand, but I'm not a huge fan of that

**Comment by bziemons** [comment]
@therealfarfetchd to be fair, the default option would still be what you and me would prefer. But preferences are preferences and because some people said they would prefer the other in Discord, I would agree with a config option.

**Comment by dblsaiko** [comment]
Yeah, of course, I don't have anything against a config option. I'm just saying that it's kinda inconsistent the way it's proposed right now.

**Comment by Bernasss12** [comment]
Since there have been no comments since almost 2 years ago and I wasn't the main driving force on having non-SI number prefixes, upon rewriting the code I decided to completely abandon the idea unless someone has a concrete idea of what alternatives there should be. The proposed changes I currently have worked on still follow the [SI](https://en.wikipedia.org/wiki/Metric_prefix) and go up to the `exa- | E` prefix since Long values cannot go over that.
