### ISSUE TITLE
Can we move the run dir from /run/assets to just /run?

### ISSUE THREAD

**Issue by dblsaiko** [RS485/LogisticsPipes#1238]
Removes one level of subdirectories (and nothing apart from assets is in /run anyway) and is consistent with like every other mod's dev env

**Comment by davboecki** [comment]
How do those mods handle the difference between client and server? Because in our config it is not only assets but also assets_server.

**Comment by dblsaiko** [comment]
Ahh, so that's why this is a thing. They don't. Is it necessary to seperate client and server files though? The only thing that I could think of right now is to test how the mod handles configuration mismatch between client and server, since you can easily change the config files seperately. But that kinda seems like an edge case.

**Comment by davboecki** [comment]
That's a good question. I have no idea if it is necessary or not to have them seperated. For me it just feels right that they are in seperate folders but I cannot put the finger on why I feel that way...

**Comment by bziemons** [comment]
I like server and client separated as well, but I'd like /run (as with every other mod in default) and /run_server (or similar) more.

**Comment by dblsaiko** [comment]
That's actually what I was going to suggest if not keeping them both in /run, except for /run-server as the server directory, since that naming style (using `-` as seperator) seems to be used most frequently (on Linux, at least) and you rarely see files/dirs with `_` in the name. On top of that it's slightly easier to type, since you need to hold down shift to type the `_`
