### ISSUE TITLE
Player unable to craft when joined to multiplayer LAN

### ISSUE THREAD

**Issue by Anaksanamune** [RS485/LogisticsPipes#1245]
Player 2 (who joins LAN game) is unable to craft unrouted logistics pipes (other LP blocks may have the problem - currently untested).
Player 1 (host) is able to create them.

Confirmed player 2 is able to craft item in single player game (with identical mods / config loaded).

Player 2 crash reports attached:

[crash-2019-06-07_23.39.51-client.txt](https://github.com/RS485/LogisticsPipes/files/3268364/crash-2019-06-07_23.39.51-client.txt)
[crash-2019-06-07_23.22.19-client.txt](https://github.com/RS485/LogisticsPipes/files/3268365/crash-2019-06-07_23.22.19-client.txt)
[crash-2019-06-07_23.11.12-client.txt](https://github.com/RS485/LogisticsPipes/files/3268366/crash-2019-06-07_23.11.12-client.txt)

**Comment by bziemons** [comment]
Can you try again with the most recent build?

**Comment by bziemons** [comment]
Fixed in build 140
