### ISSUE TITLE
[1.12 - 0.10.2.143] Crash (prevented by vanillafix)

### ISSUE THREAD

**Issue by zabi94** [RS485/LogisticsPipes#1247]
Singleplayer, Forge 14.23.5.2838

Crashed by placing two basic log. pipes adjacent to each other. Placing them too quickly seems to have a higher chance of crashing

https://paste.dimdev.org/iqanudiciv.mccrash

**Comment by bziemons** [comment]
You could downgrade to build 142 for a workaround

**Comment by davboecki** [comment]
Fixed by: https://github.com/RS485/LogisticsPipes/commit/afe22a762a1e9d2fb0cdbd73f696530039d386ce
