### ISSUE TITLE
Request Pipe should be able to search enchanted books 

### ISSUE THREAD

**Issue by d1223m** [RS485/LogisticsPipes#125]
As the topic says. ( Id really prefer it wasnt like the NEI search that searches all the comments ( or whatever they are called ) of all items, I find that quite annoying - though it would be an improvement )

**Comment by Vexatos** [comment]
:+1:

**Comment by ruifung** [comment]
Or, search by keywords, allowing a search like Enchanted Bane to return a result for Enchanted Book with the enchantment Bane of Arthropods.

**Comment by bziemons** [comment]
@ruifung That would be a new ticket. Although it would duplicate another ticket a bit.
