### ISSUE TITLE
Extraction module pulls only after input inventory is empty

### ISSUE THREAD

**Issue by mikiones** [RS485/LogisticsPipes#1253]
if i take manually item from input slot the extraction module pulls the item, 

![image](https://user-images.githubusercontent.com/1821412/59521498-4d1d2280-8ec4-11e9-9093-5537416853ac.png)

**Comment by mikiones** [comment]
![image](https://user-images.githubusercontent.com/1821412/59526496-f66a1580-8ed0-11e9-8ce2-da40ff8378bd.png)
![image](https://user-images.githubusercontent.com/1821412/59526523-03870480-8ed1-11e9-9016-f1439d293383.png)

got it in debugger not really sure what's wrong, lugs like it try route input item ? iron bar ? 

It breaks loop and return.

**Comment by dblsaiko** [comment]
Yeah I'm thinking that those slots are the same inventory handler, and whatever mod that is doesn't let LP pull out of the first slot, and instead of skipping it it just gives up

**Comment by mikiones** [comment]
It’s gregtech ce 

It break up @195

**Comment by mikiones** [comment]
The inventory handler looks like got proper input and output inventories, why extractor would try export from input slot ? Or this is not always true for tile entities ?

**Comment by mikiones** [comment]
![image](https://user-images.githubusercontent.com/1821412/59531981-58317c00-8edf-11e9-9777-cbdb42564e9f.png)

gregtech item handler treats input and output as single inv ? and size return total size, slot 1 => first slot in iput handler. ..

**Comment by mikiones** [comment]
not sure if proper fix, but it fixes my problem.

**Comment by mikiones** [comment]
adv extractor still got same issue, didn't notice thy not share tick implementation
