### ISSUE TITLE
add 'regulator' upgrade for sink and retrieve cards/pipes

### ISSUE THREAD

**Issue by mikiones** [RS485/LogisticsPipes#1258]
would change behaviour to act like old'good'e rp2 regulator where to items are sinked only when exact amount no more no less can be inserted into inventory, for retriever don't pull until exact amount is present to pull,  possible option for match singe slot or all slots to match requirements.

**Comment by Hasunemiku2015** [comment]
I think it is good for automations of presice machineries , so I would hope that it could be added .
While for balancing , i think it should have a relatively expensive recipe

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
