### ISSUE TITLE
Project table with Request Pipe GUI

### ISSUE THREAD

**Issue by d1223m** [RS485/LogisticsPipes#126]
Think: a crafting table, with the ability to request items so you can stay on one GUI and be able to craft and request.

**Comment by bziemons** [comment]
I like the idea :+1:

**Comment by davboecki** [comment]
Me too. Already had some situations where this would have been useful.

**Comment by Vexatos** [comment]
:+1:

**Comment by Flow86** [comment]
:+1:

**Comment by Vexatos** [comment]
Might be made with a button leading to the Reques GUI.

**Comment by AartBluestoke** [comment]
i propose changing a logistics crafting table also changes an attached crafting pipe
that way a "craft now" button can be added to the LACT, which will cause it to pull from the network and do a craft to its own inventory

**Comment by bziemons** [comment]
The LCT should not have manual crafting. Also that means it will request everything from the crafting pipe, even if you have the things in it's inventory.

**Comment by davboecki** [comment]
Added.
