### ISSUE TITLE
process module cards in order of priority 

### ISSUE THREAD

**Issue by mikiones** [RS485/LogisticsPipes#1260]
process module cards  in order of importance
first crafting,
sinks
extract

so extract card will never 'steal' output from crafting in porcess.

**Comment by mikiones** [comment]
also suspend item sinks until crafting is finished.

**Comment by davboecki** [comment]
I don't get what you want to achieve with this. In my opinion, if you put an extractor and a crafting pipe into one and the same chassis and they start to fight over the output then that is a user error and you should not do that inside your chassis pipe.

**Comment by bziemons** [comment]
> so extract card will never 'steal' output from crafting in porcess.

they have different action speed and they act in different ticks sometimes. This can't be done. Basically what @davboecki said.

**Comment by mikiones** [comment]
So crafting card don’t know is in process of crafting ?

**Comment by mikiones** [comment]
So it forces to have 2 same machine one for passive processing and another for crafting...

**Comment by davboecki** [comment]
Yes, it does. We used to be "one pipe per task". At some point, we introduced crafting modules which allows there to be 8 tasks per machine but that's the limit. 

Basically it's a design decision we made years ago and we don't plan to change that.

**Comment by mikiones** [comment]
fair point, then shouldn't then it not allow to put crafting with extracting module it it not intend to work together ?

**Comment by davboecki** [comment]
Not in my opinion. Simply because what is currently happening is exactly what I would expect to happen. So like I said I consider this a user error and not every possible error needs to be prevented. If we would start to do that, we would only be implementing countermeasures to stuff like this and not rework or add new features.
