### ISSUE TITLE
Crash with QuickSort Module

### ISSUE THREAD

**Issue by rcooknet** [RS485/LogisticsPipes#1266]
My world crashed and now fails to load after inserting a QuickSort Module into a Mk2 Chasis. It had been previously running at the same location using a Mk1 Chasis.  I upgraded the Chasis and reinserted the QuickSort Module and the game immediately crashed.

Modpack is Omnifactory v1.0.5, using Logistics Pipes 0.10.1.112 

https://pastebin.com/DCuVaYLH

**Comment by bziemons** [comment]
Please update to the latest build and see if the problem persists

**Comment by rcooknet** [comment]
I updated the pack with logisticspipes-0.10.2.150 and was not able to reproduce the issue.

**Comment by davboecki** [comment]
OK, then I will close this issue. If you happen to have this bug again, please reopen the issue, or create a new one.
