### ISSUE TITLE
Compact Machines Compatibility

### ISSUE THREAD

**Issue by Notlucky101** [RS485/LogisticsPipes#1272]
Can you make it compatible with compact machines?
Also if that is no possible will you be implementing  connect between dimensions?

**Comment by dblsaiko** [comment]
What is broken regarding interop with compact machines?

**Comment by Notlucky101** [comment]
Pipe will not connect to side were the tunnel indicates. If the tunnel indicates the west side the pipe will not connect on the outside of the west side of the compact machine wall. Its like connecting enderio interdimensional block, in the overworld the compact machine is a single block but with in the block it can be up 13 x 13 x13  room.

**Comment by dblsaiko** [comment]
Did you intend to close this?

**Comment by Notlucky101** [comment]
did i close this? did not mean tool

**Comment by nyasara** [comment]
I will note that you can connect between dimensions with the inventory system connector and ender chests. I use this extensively, including into compact machine dimensions. You just need to make sure the other dimension stays loaded.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
