### ISSUE TITLE
Feature request: deep storage provider pipe

### ISSUE THREAD

**Issue by 128-bit-guy** [RS485/LogisticsPipes#1273]
Instead of special compatibility for deep storage unit blocks, it would be nice to have deep storage provider pipe/module. It will be able to provide item of one type. If item of that type is requested, it will try to extract item from block each tick, until there won't be any items in deep storage unit for some time or request will be completed.

**Comment by davboecki** [comment]
Could you elaborate a little bit more, why you want to have a separate pipe and not just for the normal provider pipe to be able to read and access the deep storage unit's content.

**Comment by 128-bit-guy** [comment]
Yes, default providers are better, nevermind.
