### ISSUE TITLE
Crash with Thermal Expansion (Cache)

### ISSUE THREAD

**Issue by Rapha2101** [RS485/LogisticsPipes#1276]
I placed a cache signalum on a doubled Quick Sort module pipe. 

The game crashed whilst ticking block entity
Error: java.lang.UnsupportedOperationException: Couldn't extract the already sended items from the inventory.

[crash-2019-06-19_18.36.18-server.txt](https://github.com/RS485/LogisticsPipes/files/3307162/crash-2019-06-19_18.36.18-server.txt)

**Comment by bziemons** [comment]
Cannot reproduce with the most recent build. Can you re-test and if the crash still happens, upload a screenshot and a description of your pipe connecting to the buffer?
