### ISSUE TITLE
Items pop out of a basic pipe behind an iron pipe

### ISSUE THREAD

**Issue by bziemons** [RS485/LogisticsPipes#128]
Item Sinked stone did pop out of the pipe instead of going into the chest.

![screenshot](https://f.cloud.github.com/assets/1096713/814630/7ac3d7a2-ef19-11e2-89af-fe8d8b388eb5.png)

**Comment by ruifung** [comment]
I thought iron pipes seprate the LP network?

**Comment by AartBluestoke** [comment]
iron pipes are fully active one-way power and routing providers.

**Comment by ruifung** [comment]
Ah. I understand now.

**Comment by davboecki** [comment]
Fixed in newest dev.
