### ISSUE TITLE
Suggestion / Request

### ISSUE THREAD

**Issue by Notlucky101** [RS485/LogisticsPipes#1281]
I don't use buildcraft because I have mods that do the same and or better then buildcraft. If it is possible can  you add a way to cover the pipes, or make forge micro blocks compatible with the logistics mod.

**Comment by Bernasss12** [comment]
I may be wrong, and if so please someone correct me, but I was pretty sure LP pipes are multi block compatible.

**Comment by davboecki** [comment]
It is. In fact, we do NOT support BuildCraft facades in MC 1.12.

**Comment by Notlucky101** [comment]
no they are not. The cover does not sit on top
