### ISSUE TITLE
Forgemicro blocks cover

### ISSUE THREAD

**Issue by Notlucky101** [RS485/LogisticsPipes#1282]
The forgemicroblocks cover does not sit on top. when but down it is slightly higher then the block surrounding it.

**Comment by Bernasss12** [comment]
Could you please provide image examples?

**Comment by dblsaiko** [comment]
This happens since LP does not support Forge Multipart.

**Comment by Notlucky101** [comment]
I know so can you provide something that will cover the pipes or make
compatible?

**Comment by dblsaiko** [comment]
LP has MCMultiPart compatibility, you can use that I guess, with Chisels 
& Bits to make covers. On top of that, I don't know of any mods that 
have both MCMP and FMP compatibility, so I don't know if it's at all 
possible.

**Comment by Notlucky101** [comment]
I Just tried chisel and bits and it will do the trick for now...thank you

**Comment by bziemons** [comment]
Closed, because of MCMP compatibility.
