### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Notlucky101** [RS485/LogisticsPipes#1283]
Can I have multiple recipes in one logistics crafting pipe. For example I want to pull out iron dust and  make ingots, or pull out copper dust to make copper ingots, but I don't want to create multiple furnaces or each type. One furnace for all types of metal dust, in that way if I have a recipe that require metal dust and something else I can do that, without having to worry about automatically that dust getting smelted into a ingot. In other words I pipe = multi ore dust order on demand.  Another example is that a ran out of ingots do when a recipe require a particular ingot it will take out of the storage the dust of that ore and smelt into a ingot.

**Comment by dblsaiko** [comment]
Nope, use chassis pipes and crafting modules instead if you need multiple crafting recipes in one pipe.
