### ISSUE TITLE
Bee Sink Error

### ISSUE THREAD

**Issue by spidey1958** [RS485/LogisticsPipes#129]
Using the binnie-mods 1.7.0b and forestry 2.2.8.4(611) it lost the bee settings in my bee synch pipes. I reset them and everything is fine. I exit the game when I next load the save gives an array error. I try again and world loads but all bee sink pipes have lost there settings again.

**Comment by bziemons** [comment]
Please tell us the Logistics Pipes version you are using and provide a full crash log over pastebin or similar.

**Comment by spidey1958** [comment]
I can't recreate the error but every time I go into my bee synch pipes the gui is all questions marks. It seems to keep the setting in terms of sorting if I set and close but next time I open GIU is blank again. Using version 0.7.3.dev.595

**Comment by ArtForz** [comment]
Reproduced. Looking into it
