### ISSUE TITLE
Pipe Controller causing game crash

### ISSUE THREAD

**Issue by Anaksanamune** [RS485/LogisticsPipes#1294]
#1292 shows the set up used (same pipe).

Pipe controller on chassis then click on tabs 1 - 4,finally click back on tab 1 and the game crashes, logs attached.
[crash-2019-06-22_21.15.12-server.txt](https://github.com/RS485/LogisticsPipes/files/3317270/crash-2019-06-22_21.15.12-server.txt)
[crash-2019-06-22_21.22.52-server.txt](https://github.com/RS485/LogisticsPipes/files/3317271/crash-2019-06-22_21.22.52-server.txt)
[crash-2019-06-22_21.33.42-server.txt](https://github.com/RS485/LogisticsPipes/files/3317272/crash-2019-06-22_21.33.42-server.txt)

**Comment by davboecki** [comment]
Could it be, that not all of your LP system is chunkloaded when you use the pipe Controller?

**Comment by davboecki** [comment]
Should be fixed with build 168.
