### ISSUE TITLE
[Request] Highspeed pipes going up or down

### ISSUE THREAD

**Issue by Taris36** [RS485/LogisticsPipes#1295]
Would it be possible to have the highspeed curve, line, and s curve pipes be able to go up or down? I am only seeing them go horizontally except for the gain tube, which only goes up 1 m at a time.

**Comment by davboecki** [comment]
We can discuss this for sure, but I intentionally did not create HS tubes going up or down. 
This was a design decision, based on the fact that they go fast, which is for long distances. 
You can think of it as items having to fight gravity when going up or down and thus HS Tubes are not possible vertically.

**Comment by Taris36** [comment]
If it is gravity inspired, then down would make sense while up would be as you said. If not that's ok too. I still love this mod. :)

**Comment by davboecki** [comment]
Items going down would need to be stopped and if gravity accelerates them things would go boom. 

And only allowing down not up would only confuse players.

**Comment by StarkRG** [comment]
You could, instead, use the method Thermal Dynamics does with its long-distance viaducts whereby transitioning from a regular viaduct to a long-distance one requires a couple of seconds to build up energy before moving forward at the higher speed.

**Comment by hron84** [comment]
But viaducts are for players, not for items/fluids. Holding up items/fluids on a pipe can cause jam and crafting request confusion. -1 on this.

**Comment by StarkRG** [comment]
I'd say that would just be part of the design process. Perhaps high-speed pipes don't route for requests by crafting pipes and modules meaning you'd need a local storage depot for machines or crafting tables. The crafting result would travel via the high-speed pipe, just not the ingredients.

**Comment by bziemons** [comment]
that sounds too complicated

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
