### ISSUE TITLE
[Suggestion] Buffer Upgrade

### ISSUE THREAD

**Issue by thatsIch** [RS485/LogisticsPipes#13]
Imho Buffering is one of the biggest problems in LP, since if you have not enough space in the target processing, it will bounce all time until finished. It would help greatly if you have something which can simulate an inventory as the MK3 Crafting pipes but maybe with a more generic way with an upgrade via upgrade manager. 

Maybe using for example barrels from factorization which enables you to buffer only 1 item but then 64 stacks at once or chests from IronChest mod where the buffer is determined on the chest-type you put in (iron chest less buffer than a diamond chest)

**Comment by AartBluestoke** [comment]
the problem with crafting pipes (and other thing in LP) is there isn't a list of things which are reserved for sending, but not eligible for sending yet, so when a crafting pipe requests 58 stacks of stuff, the 5 providers in different places happily try to send them as soon as they are able to ... @ArtForz  perhaps we should check for space in inventory before sending active?

**Comment by AartBluestoke** [comment]
passive routing is a bit better as qsort and extractors do not over-stuff their destination now, only crafters with full buffers will bounce items repeatedly.

active sending could do with the same fix, but it is more complex, as you can't just abort an active send and try later when other inventories have space.

**Comment by MrTJP** [comment]
And with the new mechanic of splitting things up now, this isnt necessary... because if something is overstuffed i believe it wont send to there anymore...

**Comment by AartBluestoke** [comment]
extractors and qsorts wont, crafters will happily re-request stuff which bounces, which providers will happily send to bounce again.
either providers or crafters need an inventory space check before sending/re-requesting. 
thats why i didn't close this issue.

**Comment by MrTJP** [comment]
In other words, dont send items if we know its gonna bounce anyway, because this way items wont zip around for no reason or need to be requested again by the crafter.

**Comment by AartBluestoke** [comment]
latest dev fixes providers sending to crafters also, but hasn't had much bug testing.
crafters will send all they can, to bounce off other crafters to a chest to be provided, and suppliers already cut of delivery when they have enough.

crafter mk 3's have a nice buffer built in, and the latest dev flushes the buffer in a sensible way once crafting is done.

**Comment by AartBluestoke** [comment]
Items already sent are now counted as in the final destination, except for crafting pipes sending items 
(because it is better to store newly crafted items in storage and allow more to be crafted)

If there are any further issues, please re-open this, or raise a new one.
