### ISSUE TITLE
Problems with the Satellite pipes

### ISSUE THREAD

**Issue by Notlucky101** [RS485/LogisticsPipes#1302]
Satellite problem

**Comment by Notlucky101** [comment]
I believe I have set up everything right.
![2019-06-23_20 08 50](https://user-images.githubusercontent.com/42447191/59989408-d1258780-95f3-11e9-93a1-ff8f7d3d768c.png)
![2019-06-23_20 08 59](https://user-images.githubusercontent.com/42447191/59989418-e0a4d080-95f3-11e9-8555-3b2733f6e48a.png)
![2019-06-23_20 09 05](https://user-images.githubusercontent.com/42447191/59989427-ebf7fc00-95f3-11e9-8c16-af8f29dbefc5.png)
![2019-06-23_20 09 13](https://user-images.githubusercontent.com/42447191/59989437-f3b7a080-95f3-11e9-8f5e-185093b6d6db.png)
![2019-06-23_20 09 22](https://user-images.githubusercontent.com/42447191/59989441-f9ad8180-95f3-11e9-97ee-61ac78d6d2cb.png)

I have a redstone furnace and at the back is the mk5, on the side is a chest with a satellite pipe.
I have named the satellite pipes ingots and set all the crafting modules to ingots.
The problem is I did a test and order 32 copper and 32 nickel. the copper or the nickel does not enter the chest. I have set the back of the furnace to input and output. So the copper works but the nickel does not go in the que(chest). I have set the back of the furnace to output only and neither on works.
the furnace side where the chest sits is always input.

**Comment by bziemons** [comment]
Why do you think the last three slots in a crafting module/pipe look different?

**Comment by Notlucky101** [comment]
Ahh now I feel silly thx
