### ISSUE TITLE
guide book crashes/stuck in quickstart

### ISSUE THREAD

**Issue by CaptPanda** [RS485/LogisticsPipes#1307]
So reaching the end of logistics pipes guide book's quickstart, there are no further options. upon re-opening the book, you get this:

![image](https://user-images.githubusercontent.com/17532101/60100090-e7952580-9750-11e9-9a92-8ca338180fd7.png)

Clicking the arrow to go right crashes the game, giving this error:
https://pastebin.com/SUjwZCNN

**Comment by Bernasss12** [comment]
While the fix isn't published I suggest you try to get a new book and avoid closing it on the 10th page as this is a bug and will happen again if you do that.

**Comment by dblsaiko** [comment]
I'll fix it in a bit.

**Comment by dblsaiko** [comment]
Closed in 0afbd6b.
