### ISSUE TITLE
understanding issue: terminus module

### ISSUE THREAD

**Issue by Flow86** [RS485/LogisticsPipes#131]
Hi,

I don't know how to get the terminus module working:

network:
- itemsink (wood) at chest A
- itemsink (default) at chest B
- terminus (wood) at chest C

results:
- as long as chest A is not full, the wood does go into chest A (_OK_)
- soon as chest A is full, wood goes into default chest B (???)
- soon as chest B is full, wood gets dropped (definitly _FAIL_)

I thought terminus modules are simply "low priority" item-sinks - but it seems that the default item sink has a higher priority than terminus, or the terminus module doesnt work at all?

What am I doing wrong here?

**Comment by ruifung** [comment]
You are doing nothing wrong from what I see, having terminus modules higher priority then default routes is the original routing priority. 
Reference: http://logisticspipes.wikia.com/wiki/Basic_Mechanics#Routing

**Comment by Flow86** [comment]
then something simply does not work or somethings wrong by design - since the terminus module is never be used as a destination when a default destination does exist

**Comment by bziemons** [comment]
The terminus is working here. What build are you using so I can test it with that?

**Comment by ArtForz** [comment]
Cant' reproduce here either, Dev 595.

**Comment by davboecki** [comment]
Could you post an image of your setup?

**Comment by Flow86** [comment]
its too complicated constructed to post a single image, but easy setup:

terminus (stone) -> chest1 -> provider pipe
itemsink (default) -> chest2 -> provider pipe
itemsink (stone) -> chest3 -> provider pipe

now fill chest1, if you put in another stone, it will travel to chest2 instead of chest3, first if chest2 is full too, the terminus matches. it seems that this order is used:

itemsink ("item") -> itemsink (default) -> terminus ("item")

but as long no "terminus (default)" exists, its a bit problematic :/

**Comment by bziemons** [comment]
Update and replace the pipes. This may be a bug with the routing table issue we had.

**Comment by AartBluestoke** [comment]
@Flow86 does this issue still persist

**Comment by Flow86** [comment]
yes thats fixed.

My understanding problem was, that the pipe does NOT work until an inventory is attached. I "only" had the pipe between an unrouted part and the routed part. that's currently not working.

In the irc we had the conclusion an "use-unrouted-exit-as-unlimited inventory-upgrade" would be a nice feature
