### ISSUE TITLE
Fluid satellite pipes are un-selectable in the fluid crafting upgrade GUI

### ISSUE THREAD

**Issue by Sarioah** [RS485/LogisticsPipes#1310]
Using LP build 173, I set up a bunch of both normal satellite and fluid satellite pipes and give them all unique names. I add a fluid crafting upgrade to a crafting module and attempt to assign a fluid satellite pipe to that fluid. The list that appears shows only _normal_ satellite pipes, and I cannot see any of the fluid satellite pipes...

Effectively this means fluid crafting is entirely broken at the moment  :(

**Comment by davboecki** [comment]
Fixed by: https://github.com/RS485/LogisticsPipes/commit/60beb69b3ef76690b1e2675d5133f75fd1c0deba
