### ISSUE TITLE
Fluid Satellite pipes specified in fluid upgrade modules won't save between server restarts

### ISSUE THREAD

**Issue by Sarioah** [RS485/LogisticsPipes#1312]
Using LP 179, I place and name a fluid satellite pipe. I then target that pipe using either a crafting card in a chassis, fitted with the fluid crafting upgrade, or a crafting pipe, also fitted with the fluid crafting upgrade.

The setting sticks after closing the GUI, and the pipe crafts using fluid just fine, until I restart the server. Once logging back on, the fluid satellite pipe specified in the crafting card or pipe just says "off". Fluid type and amount are saved, but not the actual satellite pipe ID. Trying to request the item that card is supposed to craft will deliver any physical items to the right places, but no fluids will ever be delivered...

Note: dummy recipe just for demonstration:
![2019-06-27_21 05 25](https://user-images.githubusercontent.com/3851003/60261595-a0a95a80-991f-11e9-9a59-c9eae094211a.png)

**Comment by Sarioah** [comment]
Some extra information:
The cards that get wiped after a restart appear to be using "liquidSatelliteId:" tag, and the ones that work fine after a restart are using "liquidSatelliteUUIDArray0:" tag....

This one works fine, liquid goes to the right place, but it gets reset to "off" after a server restart:
![Screenshot (293)](https://user-images.githubusercontent.com/3851003/60382980-7e921280-9aae-11e9-9b03-977f4785e004.png)

This one stays working after a restart:
![Screenshot (294)](https://user-images.githubusercontent.com/3851003/60382984-7fc33f80-9aae-11e9-9f2d-66aeabf131cf.png)

**Comment by Sarioah** [comment]
Ok yeah it seems that cards with advanced satellite + fluid crafting upgrades have their fluid satellite specification saved, but that is not happening with cards that **only** have a fluid crafting upgrade...

Only those "liquidSatelliteUUIDArray" tags are present after the restart, the "liquidSatelliteID" tags are empty.

**Comment by Sarioah** [comment]
Further info: the cards lose their fluid satellite ID if you simply pull them out of the chassis and replace them; no need to restart the server...

**Comment by bziemons** [comment]
That still happens with the newest build, right?

**Comment by Sarioah** [comment]
Yeah, everything in this issue is still present in 183.

**Comment by Turmfalke2** [comment]
hi
@davboecki can you please reopen this? Just tested it with 206 and the issue still exists.

Steps to reproduce:
1. load the world, change the fluid module's satellite pipe from off to the correct satellite pipe.
2. go back to the main menu
3. load the world again, note that is is again configured to off

I was doing this in SP, not sure whether that matters.

**Comment by Turmfalke2** [comment]
The new bug appears to be timing related, if I wait a few minutes between step 1 and 2 the settings do save.

**Comment by bziemons** [comment]
That is most probably related to #1460
