### ISSUE TITLE
Placing an anvil-named crafting card in a chassis crashes the client

### ISSUE THREAD

**Issue by Sarioah** [RS485/LogisticsPipes#1314]
Using LP 179, I name a crafting card inside an anvil. I then try to place the card in a MKV pipe chassis, which causes the client to crash with a "java.lang.IllegalArgumentException: Invalid null NBT value with key RepairCost" error:

[crash-2019-06-28_13.48.14-client.txt](https://github.com/RS485/LogisticsPipes/files/3337486/crash-2019-06-28_13.48.14-client.txt)

Server remains running, and upon logging in the named crafting card is still in my inventory.

**Comment by bziemons** [comment]
I have never tried naming anything from LP in an anvil :laughing: Good catch, I guess

**Comment by bziemons** [comment]
May be related to #1072

**Comment by Sarioah** [comment]
Yeah I was hoping to have an "at a glance" way of identifying cards without having to click all the ! buttons to see what's on them.

Was not to be, at least not on this version :D
