### ISSUE TITLE
[Request] A pipe or module for crafting fluids as needed

### ISSUE THREAD

**Issue by StarkRG** [RS485/LogisticsPipes#1317]
The fluid crafting upgrade is great for supplying an item recipe with fluid, but it means you have to keep a constant supply of every possible fluid. By having a way to actually craft a fluid on demand this problem would be eliminated. By adding the "fluid crafting upgrade" to it you would create something that could combine two fluids into another.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/issues/303
