### ISSUE TITLE
Crash on Logistics Request Table

### ISSUE THREAD

**Issue by eduardopilati** [RS485/LogisticsPipes#1318]
Hello,

Almost every time I request an item from the Logistics Request Table there is a render error and the game closes. The same does not happen when I request from the Request Logistics Pipe.

I'm with Latest Version, logs attached.

[crash-2019-07-01_20.58.55-client.txt](https://github.com/RS485/LogisticsPipes/files/3350727/crash-2019-07-01_20.58.55-client.txt)

**Comment by davboecki** [comment]
What do you request when you request from the Request Table?

**Comment by eduardopilati** [comment]
I had a problem with creepers and needed to restore a backup prior to setting up my logistics network.

after restoring the backup I recreated the network and the logistics crafting table and the problem no longer occurred.
