### ISSUE TITLE
Problems with request pipe? or something else?

### ISSUE THREAD

**Issue by Notlucky101** [RS485/LogisticsPipes#1320]
Ok I was doing some testing, extensive testing and I found a problem, or think it is a problem.
So I will start with a picture.
![2019-07-03_10 16 43](https://user-images.githubusercontent.com/42447191/60615937-29435300-9d85-11e9-8eb3-1c33e15f0009.png)

So I am going to request copper ingots. I none in my inventory, but I have some pulverized copper.
So I order 62 ingots, 62 dust = 62 ingots. This is what happens
![2019-07-03_10 16 34](https://user-images.githubusercontent.com/42447191/60616203-cd2cfe80-9d85-11e9-95a6-773c4e42e1a6.png)
Just for testing purposed I set up the furnace like so
![2019-07-03_11 39 16](https://user-images.githubusercontent.com/42447191/60616862-4da02f00-9d87-11e9-8703-28b7af5f0cf6.png)
![2019-07-03_11 39 22](https://user-images.githubusercontent.com/42447191/60616875-5133b600-9d87-11e9-9519-8233ec6b51f3.png)
![2019-07-03_11 39 27](https://user-images.githubusercontent.com/42447191/60616886-555fd380-9d87-11e9-9240-8d7f632b6894.png)
![2019-07-03_10 28 48](https://user-images.githubusercontent.com/42447191/60616894-5b55b480-9d87-11e9-9dfc-633579e0c48f.png)
![2019-07-03_10 29 03](https://user-images.githubusercontent.com/42447191/60616923-66a8e000-9d87-11e9-9eb2-a15d495844c8.png)
![2019-07-03_10 29 09](https://user-images.githubusercontent.com/42447191/60616932-6a3c6700-9d87-11e9-96a4-9ae7e0f6729d.png)
![2019-07-03_10 29 14](https://user-images.githubusercontent.com/42447191/60616936-6f011b00-9d87-11e9-8230-83a5368ed5ae.png)

and my inventory is set up like so...
![2019-07-03_10 28 19](https://user-images.githubusercontent.com/42447191/60616966-7e806400-9d87-11e9-8c2c-151e34ff7ab0.png)
![2019-07-03_10 27 22](https://user-images.githubusercontent.com/42447191/60616987-8b9d5300-9d87-11e9-996e-a3d09c5ed619.png)
then with itemsink
![2019-07-03_10 27 46](https://user-images.githubusercontent.com/42447191/60617025-a079e680-9d87-11e9-9759-4ae024cccb58.png)
and then with polymorfic
![2019-07-03_10 27 58](https://user-images.githubusercontent.com/42447191/60617050-aff92f80-9d87-11e9-9336-c8ccfce9b773.png)
all configuration result in the same thing.

**Comment by bziemons** [comment]
when you have 62 copper dust in the system, can you request 31 copper ingots and tell us what happens?

**Comment by Ommina** [comment]
I'm confused by your crafting card recipe.  In it, you are saying that one dust  (sent to normal input), **and** one dust (sent to satellite input) creates one ingot.  That's two dusts to create one ingot.

You request 62 ingots.  You have 62 dust.  As such, you're missing 62 dust, exactly as it replies.

Edit:  Gah.  What @theZorro266 said.

**Comment by Notlucky101** [comment]
now if I order 128 ingots and the machine only holds 64 where do the rest
of the ingots go? It that not what the satellite pipe is for?

**Comment by Notlucky101** [comment]
I just watch an older lets play on logistics pipes and I see how it works now...sigh..ok I will get this...
