### ISSUE TITLE
Logistics Pipes with(out) BuildCraft

### ISSUE THREAD

**Issue by kobliznik** [RS485/LogisticsPipes#1323]
Hello, I really appresiate somebody took over development of this great mod again so I can believe in using this mod again in modpack instead of annoying Applied Energistics, but there is one fatal thing, and that's BuildCraft with their MJ energy and incompatibility with RF or GregTech EU as dependency..

Can somebody tell me if you (mod developers) plan your own pipe API to make Logistics Pipes completely independent on BuildCraft?

Thank you so much for your time. Best regards.

**Comment by Bernasss12** [comment]
Good news! LP is in fact not dependent on BuildCraft. And is also actually compatible with both EU and RF energies.

**Comment by kobliznik** [comment]
Lol, I tried it a few weeks ago and minecraft has required BuildCraft as dependency of LP mod.. This is awesome, thanks a lot.

**Comment by Bernasss12** [comment]
If you are using curse to download the mod maybe you downloaded an old version since the current version is still in beta and their page prioritizes releases. 
Anyway, have fun with LP!
