### ISSUE TITLE
[189] Crash on world generation

### ISSUE THREAD

**Issue by xJon** [RS485/LogisticsPipes#1328]
Log: https://pastebin.com/xWv7nPbb
Any idea? Thanks!

**Comment by davboecki** [comment]
Are you sure this is the initial crash?
Normally this happens when something else crashes and the player gets unloaded, but through vanillafix some part of MC is still running expecting there to be a player.

**Comment by xJon** [comment]
This is the initial (first & only) crash log, if that's what you mean. In game there was the VanillaFix "issue with LogisticsPipes mod" toast.
But I understand it could be weird VanillaFix stuff. I also generated a few worlds and it happened only once.

**Comment by xJon** [comment]
Seems to happen every time I generate a new world? all crashes are identical (also using build 191 now).
Log: https://pastebin.com/PHM2cSMV

**Comment by hron84** [comment]
For clarity, could you please try it out without VanillaFix and post that crash log if it appears?

**Comment by xJon** [comment]
Using 191, and without VanillaFix, stopped the crash upon creating a new world, but actually did not prevent the error and caused the world to have 99% of resources for tick and 0~1 fps.
Here's the error from the log: https://pastebin.com/A9VrXqx1

**Comment by davboecki** [comment]
OK, could you please upload a full log, not just the crash report.

**Comment by xJon** [comment]
Yes, here:
[2019-07-13-1.log](https://github.com/RS485/LogisticsPipes/files/3388906/2019-07-13-1.log)

**Comment by xJon** [comment]
To be fair, I just tested a different pack (without VanillaFix) and upon world creation got a similar error mentioning a different mod: https://pastebin.com/kEUNajfk
The problems I reported might not be caused by LogisticsPipes exclusively. Sorry for the mess of information reported.

**Comment by davboecki** [comment]
While I still think there is something else going on here: https://github.com/RS485/LogisticsPipes/commit/a93046f1770b07077f9370d09795a87fe2fa8a72 this should prevent the crash from our side.

**Comment by xJon** [comment]
👍
