### ISSUE TITLE
Itemstack extraction upgrade cannot be applied to extractor module

### ISSUE THREAD

**Issue by Anaksanamune** [RS485/LogisticsPipes#1329]
Not really a bug as the tool-tip doesn't say it should be allowed, however the extractor is slow with both action speed and item extraction upgrades so it would be nice to allow stack movements.

**Comment by Anaksanamune** [comment]
Looks like my server was running slow, don't think this is an issue

**Comment by davboecki** [comment]
https://imgur.com/61NuBPY
Just as a reference.

**Comment by Anaksanamune** [comment]
Thanks I has no idea you could stack modules - maybe worth documenting?
