### ISSUE TITLE
Leaving module config recenters mouse cursor

### ISSUE THREAD

**Issue by Mr-Turing** [RS485/LogisticsPipes#1333]
Pressig esc to leave any Module Config screen (such as crafting, provider, etc) when those are in a chassis will recenter the mouse on the screen.

**Comment by davboecki** [comment]
There is not much we can do about this. When you go from a module back to the chassis pipe the GUI closes and a new one gets opened. In between these two GUIs the mouse is centred by Minecraft which wants to track it for normal operation in the 3D world.
