### ISSUE TITLE
Autocrafting with GTCE Machines does not correctly re-request excess crafting material

### ISSUE THREAD

**Issue by ZenDarva** [RS485/LogisticsPipes#1334]
Task: Autocraft 128 glass
Expected output 128 glass
Result:	64 glass in request table
		64 sand in default route
		Chassis with crafting card still sparkling expecting craft
		
Extra oddity:
		If you place 64 sand in the electric furnace to fulfil the crafting requirement, after LP pulls out the 64 glass, it will send another 64 sand to the Furnace, and leave the Glass in the furnace.

Environment setup:
		Modpack: Omnifactory 1.2.1, with Logistic Pipes updated to 0.10.2.195, Forge version 14.23.5.2838
		Logistic Request Table
		Crate with mk 5 chassis, Item Sink set to default route, and provider module
		Electric Furnace with Mk 5 Chassis, and a crafting module set to convert sand to glass.
		Appropriate power, and connecting pipes.

**Comment by bziemons** [comment]
Actually this sounds like #1291 now that I think about it. That would not only apply to GT machines then. I haven't been able to reproduce the issue though.

**Comment by ZenDarva** [comment]
I can give you a test world, and a minimal multimc instance that reproduces it if that would help. It occurs 100% of the time in my testing.

**Comment by and-reas-se** [comment]
I have experienced this same issue, also in the omnifactory pack and with GTCE machines.

**Comment by Mr-Turing** [comment]
Yep, one of my biggest hurdles right now with LP is large batch crafting. I've found the same issue with it only resending the inputs after it extracts the output.
Omnifactory with LP 195

**Comment by voidsong-dragonfly** [comment]
I have reproduced this with the latest version of LP as well. (Version 0.10.2.218)

**Comment by davboecki** [comment]
This should hopefully be fixed by: https://github.com/RS485/LogisticsPipes/commit/8d2a4fe08d46255211c3674299f4176a09af7792
