### ISSUE TITLE
Logistics Pipes ignore pipe plugs

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#134]
Buildcraft added an item called the pipe plug to allow pipes to be separated where they would normally connect together, similar to a sandstone pipe, but is an attachment to the pipe like facades. Logistics pipes bypass this plug, however. I didn't test it extensively, but I placed a provider pipe, covered one of its sides with a pipe plug, placed a chest on that side, then connected a supplier pipe to the pipe network to supply cobblestone to a chest. I put cobblestone in the chest that was next to the provider with a plug on it and the pipe still pulled the cobblestone from the chest, sending it to the chest with the supplier.

Pipe plugs can be a really great tool to allow for much a much more complex and compact array of pipe networks, but they need to work first.

Hope I've been helpful at least, to bring this to the attention of the devs. Have a nice day.

**Comment by AartBluestoke** [comment]
try using a disconnection upgrade.
plugs are a new bc concept -- i'm not sure LP checks for plugged pipes ...

**Comment by davboecki** [comment]
Should be fixed in 1.6
