### ISSUE TITLE
Disconnection module

### ISSUE THREAD

**Issue by Notlucky101** [RS485/LogisticsPipes#1340]
how to I tell the pipe what side to disconnect from? I right click on the side I do want connection to, but nothing works..

**Comment by PrototypeTrousers** [comment]
The "Pipe controller" will let you configure the disconnect module

**Comment by SonOfTheStars** [comment]
@Notlucky101 You will need to install the upgrade, then go to the pipes UI, where the upgrade should have a button next to it. Click the button and rightclick the side of the pipe you want to disconnect using the UI that pops up.
