### ISSUE TITLE
Ingredients removed from crafting module recipies come back after game restart

### ISSUE THREAD

**Issue by and-reas-se** [RS485/LogisticsPipes#1344]
I was reconfiguring a crafting module to send ingredients to a satellite pipe instead of inputing items directly, so I added the ingredients to the satellite slots and then clicked the regular slots to remove them from there. It worked fine until I restarted the game, when I did they were back in the regular slots (and still in the satellite slots).

If I remove them again and restart the same thing happens, I can reproduce it every time with multiple modules in different chassi pipes. I'm using build 195.

**Comment by bziemons** [comment]
This must be re-tested after 07292eb78b44ed8909cd48c6474a461d3309315e
