### ISSUE TITLE
Action Speed Upgrade should be applicable to Fluid Extractor Pipes

### ISSUE THREAD

**Issue by StarkRG** [RS485/LogisticsPipes#1346]
The rate that Fluid Extractor Pipes operate is excruciatingly slow, on par with an un-upgraded extractor module. It's not an issue with the extractor module due to the existence of action speed upgrades, however, these upgrades can't be applied to fluid extractor pipes and there doesn't seem to be any other method of speeding them up.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
