### ISSUE TITLE
Add faster item speed upgrade (mk2, mk3, ...)

### ISSUE THREAD

**Issue by ndsf** [RS485/LogisticsPipes#1349]
Applying single item speed upgrade doesn't make a noticeable difference, and it takes more than 8 upgrades to become fast enough. It would be nice if  there are more advanced item speed upgrades.

**Comment by bziemons** [comment]
That's the reason why they stack and you can put up to 16 item speed upgrades in one upgrade slot. Applying 64 makes the items considerably faster. There is no need for a better upgrade, just put more in there.
