### ISSUE TITLE
BeeTrait Module

### ISSUE THREAD

**Issue by Nightreaver** [RS485/LogisticsPipes#135]
I have an idea of module working like Bee Analyzer.

You can set up 1 bee-trait per module like lifespan short (or everything else than short) or fertility min/max and so on

the module then filters the bees out, which match this filter so you can automate bee DNA manipulation/changing.

it's simliar like extracting bees which are _unknown_ and need to be analysed

**Comment by AartBluestoke** [comment]
a type of selective bee extractor, to match the bee-sink module? an
interesting idea.

On 7/30/13, Nightreaver notifications@github.com wrote:

> I have an idea of module working like Bee Analyzer.
> 
> You can set up 1 bee-trait per module like lifespan short (or everything
> else than short) or fertility min/max and so on
> 
> the module then filters bee out, which match this filter
> 
> so you can automate bee DNA manipulation/changing
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/RS485/LogisticsPipes-Dev/issues/135

## 

“Getting information off the Internet is like taking a drink from a fire
hydrant.”
_– Mitchell Kapor_

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
