### ISSUE TITLE
Recipe dependency not functional or non existent.

### ISSUE THREAD

**Issue by BrickVoid** [RS485/LogisticsPipes#1351]
I have tried to craft Dark Steel ingots in the Omnifactory modpack, using GregTech Alloy Smelter, and even with multiple Alloy Smelters, it will not correctly craft the required prerequisite ingots.

To create a Dark Steel ingot from scratch, the system must first smelt iron ingots into wrought iron ingots, it must also pulverize coal or charcoal into pulverized of same. For some unknown reason, these items are getting sent to the Default Route in my system, instead of getting sent to the appropriate Alloy Smelter. This is also happening for the other steps in the process of creating Dark Steel ingots.

I have set up the GregTech machines as if they were connected to an Applied Energistics Interface. That is, with the output side to the back of the machine, and with the machine allowing input from the output side. Auto Eject is set to on, IE the orange square appears on the machine's input output face. I have chosen the Mk.5 Chassis Pipe with Crafting card(s) installed inside for each recipe as the pipe the machine is connected to.

My system was taking ingredients for each step of making a Dark Steel ingot and inserting them as it came across them, it did not even attempt to try and wait for the correct ingredients to be inserted into the Alloy Smelter. This suggests, as the title of this issue proposes, that recipe dependency is either not functional or it is non existent, that is, it does not currently exist in Logistics Pipes.

Logistics Pipes seems to handle recipes that require multiple steps properly, as I can have it craft Emerald Drawer upgrades just fine without issues. It is just failing to consider at all the smelting side of recipes. I don't know if GregTech machines can be set up to not accept ingredients that are not the correct material for a recipe. It would therefore fall to Logistics Pipes itself to have a handling function written for complicated GregTech recipes.

As a side note I am looking into updating the Logistics Pipes build in Omnifactory, unfortunately I cannot figure out how to find the build the Logistics Pipes mod in the pack wants me to update to. I don't see a link to build numbers anywhere on this issue tracker. Perhaps I am blind or it has somehow been misplaced.

**Comment by Mr-Turing** [comment]
Regarding the update, you can just do it through the Twitch client or download the latest from the jenkins link on the readme.

Regarding your issue, for a craft to be considered done, the Crafting pipe or module must extract the items itself from the inventory. Since you have the pipe on the output side, the machine will place it in the network and the craft won't be considered, the pipe will forever wait for the items to be available.
Instead, set the output to any other machine side, like the wiring one for example.
![image](https://user-images.githubusercontent.com/4960732/62262695-02ae2180-b3f0-11e9-86eb-7a8f6988e06c.png)
This works just fine.

**Comment by BrickVoid** [comment]
It's still an issue, because of the incorrect items being inserted into recipes, said recipes that are dependent on the prerequisite items being crafted. It's also an issue because apparently Logistics Pipes is not compliant if it's being given an item and is not checking if it has an existing destination for it to be sent to. It's also annoyingly complicated to build a compact setup with what you describe. I have had issues with items being set up in the manner in which you describe and they are still not properly being crafted. Logistics pipes had been set up on an Alloy Smelter set to make red alloy ingots for it's own FPGA. It would not, however, insert that same item into a GregTech Wiremill even though it had the correct recipe for the red alloy wires in it's attached Chassis Pipe.

I had this set up as you described in your response, and it still would not send the items to the correct destination. There absolutely needs to be some kind of diagnostic tool that can tell someone why an ordered component in a recipe failed, and tell them why the system failed to do what it was supposed to do with the item. It also shouldn't cost a lot of raw materials to make, if it is to exist as an item in the player's inventory. This diagnostic tool should preferably be capable of showing all items ordered for whatever reason, if it is to do with a crafting recipe or processing recipe.

Further to that, this problem has existed since 1.7.10 days in Logistics Pipes. It's particularly an issue with BuildCraft chipsets, because the BuildCraft chipset gets placed in the nearest valid inventory or spat out of the Assembly Table. I know you're not dealing with earlier versions, I just want you to know that this is an issue with any mod that uses a non-compliant method of sending items out of it's machines.

**Comment by Ioandar** [comment]
omnicraft: I use a separate alloy smelter for each type. MK1 with crafting module on top 
Works for the most parts but not for massive orders. Then I may get iron in both slots with no place for coal dust to smelt (known shortcome that has already been discussed by devs. maybe fix ahead)
Same with Wiremills, Same with compacters, pretty much everything. 

Maybe we need a blocking-mode like AE2 has it for crafting? 
"no new recipes are serviced by this machine until the current crafting-operation has finished"

I sometimes have a purple haze at a machine that I can not explain the reason for
When I check the chain and resolve missing items, suddly then chain break lose, puts the missing item in which then will not be taken out because the order was already fullfilled.

We need a tool ingame to check the chain and find the false chains and the reason behind

some crafting-chains in omnicraft are long and take a while
I wish there was a optional "DingDing" from the table, when the long running crafting finally arrives

btw: kudos for the fluid handling. "have 72mB in this machine at all time" Awesome work! AE2 cries

**Comment by Ioandar** [comment]
@Mr-Turing 

To update LP in omnicraft
* get your build from here: https://ci.rs485.network/job/LogisticsPipes-0.10-mc112/
* find the omnifactory instance folder
* make a new folder "mods_unused" in it
* move the installed LPversion to "mods_unused" (if anything goes bad, you can go back)
* put the new LPversion in "mods"
* make a copy of your savegame (if anything goes bad, you can go back)
CTRL-C, CTRL-V on your savegame (eg "Tommy")
mine looks like that
saves/tommy
save/tommy - Kopie

Before I start a new a minecraft session, I delete the copy and make a new one -> lava is hot!

I currently run LP203 with omnicraft 1.2.1

**Comment by BrickVoid** [comment]
@loandar I believe Mr. Turing was responding to me, since I was the OP in the creation of this issue. Thank you for your comments, it seems that Logistics Pipes is very flaky in how it handles recipe processing, especially when multiple steps for the same machine exist. I also am not happy about the situation regarding "Logistics Pipes has to extract the item itself" that Mr. Turing mentioned. In most other crafting mods they usually will accept that a machine can output items to them, and therefore I firmly believe that this is an issue with Logistics Pipes. It's an issue because people should not have to worry about setting up a machine to a Logistics Pipe the wrong way, the mod should just go and handle what it is given, properly and without routing it incorrectly.

If I give a machine a processing recipe via a Logistics Pipes connection, I expect the connection to be handle all possible instances of configuration the machine is capable of, and adjust automatically to the situation at hand. Given how procedural programming works these days, there is no excuse not to have extremely robust code that expects to handle an unknown machine in whatever manner the machine's mod author programmed it for. This is how a lot of mods are working in 1.12 and soon, in 1.13 and 1.14 or higher. By the time Logistics Pipes gets updated to the next Minecraft version, I fully expect that it is even more robust than ever and is fully capable of getting the crafting jobs assigned to it done in a properly programmed fashion.

**Comment by bziemons** [comment]
> BrickVoid: By the time Logistics Pipes gets updated to the next Minecraft version, I fully expect that it is even more robust than ever and is fully capable of getting the crafting jobs assigned to it done in a properly programmed fashion.

I'll just leave this here:

> Too-DAMN-Much: oh no, i expect disappointment and that's because that's all you people ever have for me

PS: Honestly: I can only counter with sarcastic humor here :) If you (the reader) can't make out anything wrong with the quotes above, you are probably wrong here.

**Comment by BrickVoid** [comment]
Is it too much to ask that Logistics Pipes actually examines items being inserted into it's pipes for the fulfillment of recipes it's trying to craft instead of being dumb and just sending them to a default route? That makes zero sense from a program execution flow perspective.

theZorro266's comment makes even less sense now than it did when I first read it.

Logistics dictionary definition: https://www.dictionary.com/browse/logistics

See definition 2, this is why I used to like the concept of Logistics Pipes so much, because I actually and really expect it to fulfill it's operations as per this definition of Logistics. What the authors of this port have is the problem of Logistics Pipes that don't actually do anything except one tiny part of that definition of logistics.

**Comment by Fabi2607** [comment]
:horse_racing:

**Comment by davboecki** [comment]
> Is it too much to ask that Logistics Pipes actually examines items being inserted into its pipes for the fulfilment of recipes it's trying to craft instead of being dumb and just sending them to a default route? 

Well, It is not too much to ask and in fact, it is already on our todo list. But the way you go about asking for it is just too much. We all work on this voluntary and in our free time. We don't work for you, we don't get paid by you and we owe you nothing. Every mod out there is provided as-is and you can not expect them to be bugfree. 
We don't expect people to give us anything in return for providing this mod to them except for decency and respect. You appear to be missing both here at the moment. You expect us to put work into our mod and feel like we are mandated to do it. We are not. Not by our mod name or by the fact that we try to provide a good Minecraft mod. And trying to argue or shame us into doing so will only result in the opposite action. 
Your attitude is not welcome here, please adjust it and use LP as it is.
