### ISSUE TITLE
Can't add any upgrade to chassis

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#1352]
I don't understand how to add upgrades to my modules, like extractors I saw some video here about some upgrade boxes into the chassis but I've updated to the last version and I don't have them https://imgur.com/a/CWh7lqe

**Comment by Bernasss12** [comment]
You have to add a `Module Upgrade` upgrade to your chassis pipe, then you'll have the two slots for your module's upgrades :)

**Comment by ghost** [comment]
Thank you :)
