### ISSUE TITLE
Crash when placing recipe in logistics request table with JEI and not selecting oredict item

### ISSUE THREAD

**Issue by adnub** [RS485/LogisticsPipes#1355]
Version:
Minecraft 1.12.2
Forge 8.0.99.99
logisticspipes-0.10.2.183

Steps to reproduce:
- Get a Logitics request table
- Lookup up an item in JEI which has oredict items. (e.g. a chest)
- Click an oredict item (In this case, the wooden planks)
- In the menu that allows you to select an option, don't select anything
- Press the select button

Result:
Game crashes

Expected result:
Window closes, keeping the original selection.

Note:
It is also possible to first select something, and deselecting it again by clicking an empty space. It gives the same result.

Crash report:
https://pastebin.com/02xDZ8an

**Comment by davboecki** [comment]
Fixed by: https://github.com/RS485/LogisticsPipes/commit/4c3f443565045082fb023e89469daf94d03ab886
Please Update.
