### ISSUE TITLE
Request: more slots for crafting in pipe and module

### ISSUE THREAD

**Issue by Ioandar** [RS485/LogisticsPipes#1356]
Hi,

Omnifactory has crafting recipes with more than 6 items
LP only has 6 slots for items (and 3 more via satellite)
I resolve that for now by using a satellite pipe on the machine

Is it possible to bump it by 1?

cheers, 

P.S.: It is awesome to see how good LP already works and how much direwolf20 struggles with fluid handling. With LP it is a pieces of cake to set up providers and suppliers as needed and they work so fine!
edit:spölling

**Comment by davboecki** [comment]
If you set the satelite pipe to off you can already use the 3 slots for ingrediants on the pipe itself.

**Comment by Ioandar** [comment]
Did not know! You guys are awesome!!! Thanky for LP
