### ISSUE TITLE
2 crafting modules of many remember their stored recipes wrong

### ISSUE THREAD

**Issue by Ioandar** [RS485/LogisticsPipes#1357]
Hi,

each time I load my omnicraft-savegame, I have 2 modules that are configured wrong

Here is my crafting module, it works all fine
<img src="https://i.ibb.co/54xqTyR/2019-08-04-22-53-22.png" alt="2019-08-04-22-53-22" border="0" />

exit minecraft - Come back (start minecraft - load savegame)

check crafting module. wtf? 
<img src="https://i.ibb.co/7XX9dMQ/2019-08-04-17-39-37.png" alt="2019-08-04-17-39-37" border="0" />

Before I used this module directly but decided to use a satellite was the right thing to do 
I removed the mats on the left, set the satellite number and put the items on the right

I have another module that behaves that way with different mats

ofc I can replace the module with fresh new one but I wanted to let you guys know
I happens each time I load the savegame. Only those 2 modules...

What am I missing or doing wrong?

**Comment by Ioandar** [comment]
I have put that savegame to download
will replace the 2 modules now with brand new ones. that should fix the little hickup

Here is the download link - it is the save from 05.08.2019
[https://www.tomtomtom.net/games/minecraft/index.php](https://www.tomtomtom.net/games/minecraft/index.php)

btw: 
I have 8 crafting modules with cleared recipes in my chest (no recipe, unset satellite).
They do not stack, so I guess they still have hidden data inside them
Is there a way to clear them (furnace them does not work) to make them shiny as newly crafted?

edit: spölling

**Comment by and-reas-se** [comment]
Seems like a duplicate of #1344

**Comment by Ioandar** [comment]
oh, you are right. I searched before posting but totally missed that

I will close this one to have the bug in 1 place.
