### ISSUE TITLE
Quicksort module not so quick

### ISSUE THREAD

**Issue by and-reas-se** [RS485/LogisticsPipes#1358]
The quicksort module seems very slow compared to what I remember in LP for previous versions of minecraft. If you put it on an inventory with a large amount of different slots, like a crate, where only a couple have a valid destination, it can take minutes before it's processed all items in that crate and sent them on their way. And put it on an applied energistics interface to process a lot of items in digital storage and you might as well leave the game running while you go eat dinner if you're waiting on it to process the contents.

Not sure if a bug or intended change, but thought I'd check if this was known or not. Just seems odd, especially if you compare it to how fast an extract module with a few upgrades can process an inventory of the same size.

**Comment by davboecki** [comment]
The QuickSort module has two modes for performance reasons. It is intended to stay on a chest, mostly a default route, that has items in it that don't have a destination.

The two modes are slow and fast.
If an item could be sorted into the system that position is slot position is stored, and the module moves to the fast mode if it hasn't already been there. 
After cycling through the complete inventory and the stored slot is reached again the module moves to the slow mode. 
This ensures that not too much performance is consumed by the quicksort modules.

If you have a system where items appear inside the chest and the quicksort module is not fast enough I would recommend to change that over to an extractor module and add another chest as default route with the quick sort on it if needed.
