### ISSUE TITLE
[Suggestion] Make Modules stack again

### ISSUE THREAD

**Issue by Ioandar** [RS485/LogisticsPipes#1360]
I am playing omnifactory using mainly LP

I have many modules that I currently not use but keep for upcoming tasks

They are all empty and look the same when using their UI

BUT they do not stack anymore, because they have some hidden data that differs

Suggestion:
* add a shapeless recipe to reset them to state "new" (like clearing conduit-filters)
* add a furnace recipe to reset them to state "new" (like gendustry does with their dna)
* _add own idea here_

Goal should be to reset modules back to the state they had when crafted so they stack with other empty modules of same type

**Comment by bziemons** [comment]
> add a shapeless recipe to reset them to state "new" 

that was in the previous versions and probably will be the way to go. The reset recipes were removed because of that new JSON foo.

**Comment by Ioandar** [comment]
For those impatient. you can make your own file in **omifactory** in minecraft/scripts
name it "logpipesAdd.lz" or whatever and use the recipes you wish to alter like

```
	recipes.addShapeless("Erase Crafting Module",
	<logisticspipes:module_crafter>,
	[<logisticspipes:module_crafter>]);

	recipes.addShapeless("Erase Active Supplier Module",
	<logisticspipes:module_active_supplier>,
	[<logisticspipes:module_active_supplier>]);

```

**Comment by bziemons** [comment]
It just works. I have no idea why and when it was added.. the shapeless recipes are there, they are not shown in JEI, but they just work.. I have to fix my glasses, because I was sure this wasn't working three weeks before.
