### ISSUE TITLE
[Suggestion] Make Crafting Table and Pipes a bit harder to break

### ISSUE THREAD

**Issue by Ioandar** [RS485/LogisticsPipes#1361]
I dont know how many time I have clicked my drill on pipes or table.

Yes I am somewhat clumsy with my drill but spilling the Items all over the place or snapping a crafting pipe by mistake is annoying since you have to reconfigure them. 

A just punishment you might say but I beg the lords of LP to show mercy :)

* Is it possible to make them a little harder to break by drill?
* Maybe make them insta-break with a wrench for those mass-pipe-removers like enderIO does?

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
