### ISSUE TITLE
Re-used crafting modules partially revert to old inputs after restarting

### ISSUE THREAD

**Issue by StarkRG** [RS485/LogisticsPipes#1362]
When re-using crafting modules, I'll click to remove the old inputs and output, then put in the new ones. This works perfectly fine until after restarting the game (even just exiting a single player world to the title screen). Any spot that used to have items, but was now left blank now has the old items back. 

It's hard to explain what I mean so here's a screen shot:
![image](https://user-images.githubusercontent.com/451657/62828681-a2a94d80-bc2f-11e9-9cbd-c0f5783d6ab0.png)

The old recipe used clay, but I removed that by clicking on the slot to remove it. Then I put in the new ingredient (vibrant alloy ingot) and the output (two vibrant alloy wires). But after a restart, the clay is back, but the vibrant stuff is still there.

**Comment by Ioandar** [comment]
Ye, have the same. Seems some data re-appear. See  #1344 or my dupe #1357

currently I lava those. 

there is currently no way to reset them propper to factory settings but will be in future. See  #1360

**Comment by StarkRG** [comment]
I tried to search for an existing issue, clearly I failed. Someone can list this as a dupe. :)

My workaround solution is to use crafttweaker to make a recipe that takes a crafting module as an input and outputs a new crafting module.

**Comment by Ioandar** [comment]
Just close this one. 

I also failed at search and made entry :)

**Comment by Ioandar** [comment]
@StarkRG 

How did you set the recipe in omnifactory logpipes.zs? recipes.addShapeless....?

**Comment by StarkRG** [comment]
I created a new script so I can copy it over if/when the pack updates. The line I used is:

`recipes.addShapeless("Erase Crafting Module",<logisticspipes:module_crafter>,[<logisticspipes:module_crafter>]);`

**Comment by Ioandar** [comment]
@StarkRG 

Thank you very much! I will do that too right now!

edit: I followed your lead and made a new script. worked perfect. now they stack again. /cheer

edit2: I made myself another entry. Those modules do not stack anymore if you only look at them :)

```
	recipes.addShapeless("Erase Active Supplier Module",
	<logisticspipes:module_active_supplier>,
	[<logisticspipes:module_active_supplier>]);
```
