### ISSUE TITLE
[Suggestion] Any chance to ever see this awesome little dudes again? (robot)

### ISSUE THREAD

**Issue by Ioandar** [RS485/LogisticsPipes#1363]
Heya! 

Searching for something else, I just stumbled over this vid from @davboecki 

[Dōmo arigatō Mr Roboto](https://www.youtube.com/watch?v=woJA9MQQtfg
)

Warning my negromancy is strong today. vid is from 2015 but still awesome!

I totally love those little Dudes. 
Are they BC only or is there at least a tiny chance we will see them ever again some time? 
Long term goal maybe?

**Comment by davboecki** [comment]
Those are heavily based on BCs Robots. It would be hard to implement them ourselves so If at all it is really really low on the todo list.
