### ISSUE TITLE
Full localization support

### ISSUE THREAD

**Issue by Vexatos** [RS485/LogisticsPipes#137]
I would like to see every item and block, not only pipes, translatable, otherwise one part of the mod would be translated, the other would stay English; If a full localization support was added, and everything could be translated, the mod would definitely be much more fun to play in other languages.

**Comment by labpaw** [comment]
:+1:

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes-Dev/commit/f77c6bf75bada0df8f2e8f7a36598a55db051cb3

**Comment by Vexatos** [comment]
I am really looking forward to this: Also: Great that you are going to use the 'vanilla' localization handler! That means the files now have to be UTF-8 without BOM encoded, instead of ISO 8859-1, which is great because it removes the need for tedious conversion of special characters.

**Comment by davboecki** [comment]
There is still a lot of stuff hardcoded inside LP so if someone sees anything Just post it here so we can fix that.

**Comment by bziemons** [comment]
Can you actually localize everything now?

**Comment by bziemons** [comment]
If there are still entries without localization, please open a new issue naming those.
