### ISSUE TITLE
Crafting Module not functioning as expected

### ISSUE THREAD

**Issue by SigmaSnake** [RS485/LogisticsPipes#1370]
https://cdn.discordapp.com/attachments/484022895186542605/618517939569557525/2019-09-03_13.47.20.png
https://cdn.discordapp.com/attachments/484022895186542605/618521981427384339/2019-09-03_14.03.51.png

The system is completely disconnected from AE and I have all the ingredients necessary for the awakened draconium blocks in the crate there. When I tell the system to craft it, it complains I have no awakened draconium instead of crafting it. It should also be noted, that I was able to successfully request each of the items from the crate without issue.

Also, this is on version 203, as 204 as issues with AE atm.

**Comment by SigmaSnake** [comment]
Interesting thing of note - Crafting Pipes work just fine

**Comment by dblsaiko** [comment]
Can't reproduce with d1ead19. I think you have the wrong recipe in the crafting pipe, Awakened Draconium Blocks require Draconic Cores here, not Wyvern Cores.

**Comment by SigmaSnake** [comment]
@therealfarfetchd I will check when I get the chance, however, I will say that I wish they required draconic cores. I can craft draconic cores in a crafting table and they don't need fusion crafting.

**Comment by dblsaiko** [comment]
here's my test setup, by the way: https://streamable.com/1z1wi

**Comment by SigmaSnake** [comment]
@therealfarfetchd Regardless of whether it depends on wyvern cores or draconic cores, I think it might be because DE is on hard mode on ATM3, you should do Wyvern Cores, such that the Awakened Draconium depends on the Wyvern Cores in the same pipe. Cause part of it, was having more than one recipe in the same pipe I think.

**Comment by SigmaSnake** [comment]
Ok, tested on the new LP version and it works as expected. Must have been fixed in the newer versions/commits :)
