### ISSUE TITLE
Chisel & Bits Question

### ISSUE THREAD

**Issue by Greg9711** [RS485/LogisticsPipes#1378]
Do i need any other mods than Logistics Pipes and Chisel & Bits for them to work together? It doesn´t work for me with the newest versions of both mods.
logisticspipes-0.10.2.207
chiselsandbits-14.33
Or did the interaction get disabled at any point?

**Comment by dblsaiko** [comment]
Yep, you need MCMultiPart.

**Comment by Greg9711** [comment]
Thanks
