### ISSUE TITLE
Game crash when using the search bar in request pipe/table on server [0.10.2.208]

### ISSUE THREAD

**Issue by Christopher117** [RS485/LogisticsPipes#1380]
Game simply crash when typing a caracter in the searchbar :

See Log for more detail.

Thx :)

[crash-2019-09-21_21.48.45-client.txt](https://github.com/RS485/LogisticsPipes/files/3639038/crash-2019-09-21_21.48.45-client.txt)

Edit 1 :
It also happens on the game of other players (not only on my side).

Edit 2 :
I try without OptiFine but the same thing happens.

**Comment by Christopher117** [comment]
Ok I finally could find where the problem came from.
Some tools had kept an old enchantment of a mod that I delete since, and when one of them was present in a chest, it was crashing the game during the search.
This enchantment was now invisible, so no choice to throw almost all my enchanted tools into the fire ^^ '

**Comment by bziemons** [comment]
we should still fix the crash

**Comment by hron84** [comment]
Save those poor tools from lava! :D
