### ISSUE TITLE
[Suggestion] Have the logistic programmer show the pipe/module/upgrade recipe it made for when you right-click with it

### ISSUE THREAD

**Issue by Christopher117** [RS485/LogisticsPipes#1381]
The recipes are quite complicated to obtain with the recipe book. if the logistic programmer could directly show the recipe for which it was programmed it would be really cool :)

I do not know if it would be easy to do or not, in any case thank you for bringing back this great mod :)

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
