### ISSUE TITLE
[Suggestion] Directed firewall pipes

### ISSUE THREAD

**Issue by Turmfalke2** [RS485/LogisticsPipes#1383]
hi,
We used to be able to to do this with iron pipes, but ever since the split from buildcraft we are lacking this functionality. 

Right now I have a set of machines/recipes that really slow. I would therefore like to avoid directly requesting from them and only use finished products from a supplier/provider chest. The idea was therefor to install a firewall pipes that blocks craft requests, but allows item requests. However the slow crafting machines require dependencies from the main network.  
I don't see how to do that without iron pipes.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
