### ISSUE TITLE
Cannot display Chinese translation normally

### ISSUE THREAD

**Issue by yuanzhw** [RS485/LogisticsPipes#1390]
minecraft 1.12.2
forge1.12.2-14.23.5.2847
lp 0.10.2.208

All item label display in English, but some detail is in Chinese.

**Comment by bziemons** [comment]
That's probably because they weren't translated yet. Have a look at https://github.com/RS485/LogisticsPipes-Language/blob/master/zh_cn.lang

**Comment by yuanzhw** [comment]
> That's probably because they weren't translated yet. Have a look at https://github.com/RS485/LogisticsPipes-Language/blob/master/zh_cn.lang

I have checked this file, all the label of items have Chinese translations, but doesn't display in game. I have installed about 20 mods, include TE, IC etc. All of these mods can display Chinese translation normally. So, I think it may be something about language setting is incorrect.

**Comment by dblsaiko** [comment]
All the item and block localization keys changed, so these keys in that file effectively point to nothing. Compare with https://github.com/RS485/LogisticsPipes/blob/dev-mc1122/resources/assets/logisticspipes/lang/en_us.lang
