### ISSUE TITLE
Creative Tab ItemSink Module causing server crash

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#1391]
Attempting to use the Creative Tab ItemSink Module is causing my server to get stuck in a crash loop (had to restore from backup to be able to enter the world again). Client side did not crash.

Minecraft 1.12.2
Forge 2847
[Star Tech Modpack v2.3.1](https://www.curseforge.com/minecraft/modpacks/star-tech/files/2809246)
Logistics Pipes 0.10.2.211
Crash log: https://pastebin.com/NhqwJY7Y

**Comment by bziemons** [comment]
Fixed in the 0.10.3.5 build: https://ci.rs485.network/job/LogisticsPipes-0.10-mc1122-fg3/5/
