### ISSUE TITLE
Crash with Silent Gear.

### ISSUE THREAD

**Issue by NJM1564** [RS485/LogisticsPipes#1394]
When trying to search threw the Logistics request table any time a Silent Gear should show up it crashes to desktop.

[crash-2019-11-19_21.57.06-client.txt](https://github.com/RS485/LogisticsPipes/files/3867116/crash-2019-11-19_21.57.06-client.txt)

**Comment by dblsaiko** [comment]
Could you check if commit f2fb2ba fixes it, please?

**Comment by NJM1564** [comment]
Looks good.

**Comment by dblsaiko** [comment]
Alright, great.
