### ISSUE TITLE
Forge Multi-Part Support [Suggestion?]

### ISSUE THREAD

**Issue by dmb1881** [RS485/LogisticsPipes#1397]
Not quite sure if the LP supports multipart yet or not (judging by not being able to place C&B's in same block with LP) 
https://imgur.com/jFChaNC

**Comment by bziemons** [comment]
Chisels and Bits should work (at least it does for me). Are there any errors about LP in client/server log? Could you provide the versions of Forge/C&B/LP?

**Comment by dmb1881** [comment]
I'm heading to work right now so I won't be able to give a full report but I can at least tell you the pack I was using. I am playing the ATM3: Expert Shedding Tiers pack, version 1.0.1.

**Comment by dmb1881** [comment]
Quick question: does the mod use forge multipart, or mcmultipart? I think the pack only has one version installed

**Comment by dblsaiko** [comment]
Both Chisels & Bits and Logistics Pipes are only compatible with MCMultiPart.

**Comment by dmb1881** [comment]
Oh ok, maybe that's why it's not working, only forge multipart is installed on the server, I'll test this to confirm it fixed when I get home.

**Comment by dmb1881** [comment]
Yeah, it was because forge multipart was in the pack and not MCMultipart.

**Comment by hron84** [comment]
@dmb1881 consider to report it to AllTheMods. // cc @oly2o6

**Comment by dmb1881** [comment]
already reported it to Oly and it's in the pack.

**Comment by hron84** [comment]
Cool.
