### ISSUE TITLE
Requester pipe will request more than its connected inventory can hold

### ISSUE THREAD

**Issue by OmaiGrundles** [RS485/LogisticsPipes#1398]
Steps to reproduce:

Attach chest(henceforth known as 'Chest P') to a provider pipe.
Attach chest(henceforth known as 'Chest R') to a requester pipe.
Fill chest R with cobblestone until only one slot is empty
Put 2 or more items with different names in Chest P (none of them cobblestone)
Set the requester filter to all item types put in Chest P

When the requester activates, it will repeat the request for every one of its filters, even though it can only store one stack of items. This causes the remaining items to hover in the pipe for a few seconds before popping back out into the world.

This issue also happens with inventories with only one input slot in the first place. I discovered this when trying to setup ore processing using a Industrialcraft macerator.

I am unsure if this is an intended thing, but I don't remember it being like this back in 1.7.10 at least.

Using version 0.10.2.212

**Comment by bziemons** [comment]
Do you mean the supplier pipe? They both always did this, yes, because they might connect to multiple inventories and there is no check in place to check them all. What would work is the chassis pipe with an active supplier module. This setup should check for space in the inventory.
