### ISSUE TITLE
[Suggestion] Name Based Module

### ISSUE THREAD

**Issue by dmb1881** [RS485/LogisticsPipes#1399]
Since we have no way to organize ore's chests or ingots into a single chest without the polymorph module (Which isn't always practical). So I propose a name based module, where you can type in a certain word such as "Ingot" and based on that will search for any items with the name Ingot in them and sort them into that appropriate chest. I know this isn't the most ideal module, but I can't think of a better way of implementing it.

**Comment by hron84** [comment]
I better to see a partial OreDict matching module, like how Mekanism OreDict filter works: you can either specify the full OreDict key (oreDiamond, ingotCopper) or just a part of it (ore*, *Marble). 
Name-Based Module can be disturbed if someone names an item in Anvil that somehow matches with the filter (think about a diamond pickaxe named "Gold Digger") and a whole subsystem become stuck chewing on an unrprocessable item.

**Comment by bziemons** [comment]
Names are sadly not available on the server-side
