### ISSUE TITLE
jenkins link broken

### ISSUE THREAD

**Issue by davisjw** [RS485/LogisticsPipes#1407]
the ci.rs485.network link appears to be an invalid page when [linked from github readme and the rs485.network page].  Based on the inclusion of a travis.yml it seems like you may have migrated from jenkins to travis ci 👍 (in part or whole).  any visibility?

**Comment by dblsaiko** [comment]
Nope, the travis.yml has been there for a while, Jenkins should still be a thing. I'm guessing it's just broken right now.

**Comment by bziemons** [comment]
Thanks for reporting. It's back now.
