### ISSUE TITLE
JEI behaviour with Request table or Crafting table

### ISSUE THREAD

**Issue by Opicka879** [RS485/LogisticsPipes#1408]
Im not sure, if i just dont understand how to do it correctly or there is an issue. But im not able to open and transfer whole recipe to Crafting table or Request table from JEI, but separate things only. It is very annoying. Can you explain me, how open and cope whole recipe eventually fix the issue?

Sry for my english.

**Comment by Greg9711** [comment]
If you´re trying to get the recipe with mouse1 then it will "give" you an ghost item to set recipes in crafting pipes for example without you actually having the item itself, try hovering over the item you want in JEI and press R that should bring up the recipe and you can put it into the request table.

**Comment by Opicka879** [comment]
Omg, im so dummy. I did forget about "R". Ty for help ;)
