### ISSUE TITLE
can't see the slot for speed upgrades

### ISSUE THREAD

**Issue by red-mist** [RS485/LogisticsPipes#1409]
Logistics pipes version 0.10.2.214 mc1.12

I tried right-clicking the upgrade in with no luck; and there doesn't seem to be a slot for them in the gui (as I've seen in some other posts).
I added it manually to an all the mods3remix instance; could it be a config thing or something?
I'm used to the previous version so probably something I'm missing :)

![action speed](https://user-images.githubusercontent.com/12532628/72225706-d4c92d80-3588-11ea-88b2-25d88016e00a.jpg)

**Comment by Greg9711** [comment]
There is an Upgrade (its black) that you need for chassis pipes to accept upgrades for the modules

**Comment by bziemons** [comment]
What Greg said. It's called the Module Upgrade in recent versions.
