### ISSUE TITLE
The new Request Table and the Logistics Crafting Table need a Texture.

### ISSUE THREAD

**Issue by davboecki** [RS485/LogisticsPipes#141]
The texture that is currently assigned to the Request Table was only assigned for development. I'm open for suggestions for a correct texture for the Request Table. Same for the Logistics Crafting Table. If anybody has any suggestions that would be nice.

**Comment by ghost** [comment]
Do you care what resolution they are in? I was thinking about doing some 32x32 textures but I can downscale to 16x16 if you want.

**Comment by AartBluestoke** [comment]
feel free to submit at 32x32 (the same resolution as the others would work also)

Given this is the most expensive and sophisticated block on LP, i'm not against it having a higher quality texture, but dav might prefer consistency (not that there are any other blocks competing with this).

**Comment by davboecki** [comment]
As long as it looks fine with other 16x16 textures I'm completely fine with an 32x32 texture.

**Comment by ghost** [comment]
Here are some 16x16 textures that I think suit the recipe more.

https://dl.dropboxusercontent.com/u/107143465/16x16%20ReqTable.zip

Here are some 32x32 that are the same look but higher resolution and the textures are just slightly altered versions of Faithful32.

https://dl.dropboxusercontent.com/u/107143465/32x32%20ReqTable.zip

Let me know if you want anything changed.

**Comment by davboecki** [comment]
Thank you very much. We added the 16x16 version to the source code.

**Comment by ghost** [comment]
To be honest, I don't know what LCT stands for. I haven't played with the newer versions much, if you tell me what it is then I can make something for it.

**Comment by davboecki** [comment]
Logistics Crafting Table

**Comment by GUIpsp** [comment]
@DZCreeper Any update on this? :)

**Comment by ghost** [comment]
Not sure if these are good enough, but I can do some adjustments if you want.

https://dl.dropboxusercontent.com/u/107143465/16x16%20Logistics%20Crafting%20Table.zip

https://dl.dropboxusercontent.com/u/107143465/32x32%20Logistics%20Crafting%20Table.zip

Let me know if you would like anymore artwork done and sorry for taking so long, I forgot about this until I got the email alert from GUIpsp saying my name.

Edit: Also didn't know which number went with which block side so there are some duplicates in my zip files.

**Comment by davboecki** [comment]
I realy like that style. Looks really good.
If you don't mind, it would be absolutly awesome if you could make something in that style for the Power Junction and the Security Station as well. Only thing I would like to have is something like the red and green displays on both of them.
Just to start making LP's block look a little bit more like the same style.

**Comment by GUIpsp** [comment]
@DZCreeper <obligatory email notification>

**Comment by ghost** [comment]
Sorry, been a bit swamped lately between work and hobby work. After I get quite drunk for New Years I will probably make an attempt and throw it out a few times before settling on one.

**Comment by GUIpsp** [comment]
@DZCreeper
