### ISSUE TITLE
[Crash] Basic Logistics Pipe with Extractor Module crashes server

### ISSUE THREAD

**Issue by evertn** [RS485/LogisticsPipes#1410]
I have a MK1 chassis with an extractor module connected to an AE Interface. The extractor module is upgraded with 2 stack upgrades.

After a while this causes de server to crash: https://pastebin.com/YTc6PSyQ

It'll crash everytime after a restart.

Im assuming the crash is caused because the AE-system it is extracting from is now empty (It didnt have much in it yet). I have a similar set up extracting from a RFTools Modular Storage, which is not giving any issues when empty. Assuming its an issue between AE and the extractor module.

UPDATE: 

I temporarily removed LP from the server to get the world to start up again. Indeed the coordinates given in the crash report are at where this setup was positioned.

Going to re-add LP again (since I do use this mod quite a lot), guess I just have to avoid this specific setup for now.

**Comment by bziemons** [comment]
Fixed in 86015c19e41781cd92c80b0a5b72946ca344a450
