### ISSUE TITLE
Crafting Pipe signs render performance

### ISSUE THREAD

**Issue by Sakata-MC** [RS485/LogisticsPipes#1411]
Per @2xsaiko request I'm posting this here.
There is a performance issue with Crafting Signs that he stated might be able to be fixed by 'baking' the signs created by the LP sign creator, if they're crafting signs, as they are static once set by the import on the pipe.

**Comment by bziemons** [comment]
Right, there is a branch reflecting this change: https://github.com/RS485/LogisticsPipes/tree/framebuffersigns
It almost works and tests show better performance with signs, but we still have a big performance problem with chunk baking and that got worse iirc.

**Comment by dominic-jones** [comment]
The render performance is interestingly also a problem when these signs are not even on-screen.

I had a large two-chunk room containing all of one wall with crafting tables and signs. If I was looking in the direction of this room, the performance would slide from 60fps down to around 10. This would be the case no matter which direction I was looking from, or how many walls/floors were in the way.

This room was the eastern most room of my base, so basically any time I was looking east dropped the framerate considerably. I have eventually migrated to AE2, and pulling down this wall showed a large before/after gain, so I'm convinced it was these signs.

They are both useful, and visually appealing, so thank you for working on them!

I don't suppose it's as simple as adding a kind of occlusion culling?

**Comment by bziemons** [comment]
Merged a first fix for 0.10.4.19
