### ISSUE TITLE
Every time i restart my game, the selection of satellite pipes will be reset to 'none'

### ISSUE THREAD

**Issue by YI1219** [RS485/LogisticsPipes#1416]
![error](https://user-images.githubusercontent.com/49354523/75248246-c79d9080-580e-11ea-870f-c1fcdd176c29.png)
As the picture shows, the selection of fluid satellite pipe will be reset, but the selection of the type of the liquid will be saved. Is that because of some wrong configs? Can i fix it with your help?

**Comment by bziemons** [comment]
Related to #1460
