### ISSUE TITLE
Problems with Teleport Pipes

### ISSUE THREAD

**Issue by jacksonsecrist** [RS485/LogisticsPipes#1418]
I am using a logistics pipes sorting system, and it is in a remote part of my base, so i am using buildcraft teleport pipes to take the sorted items and send them to their respective locations.

When sending items through a teleport pipe to then be processed by a furnace or macerator, etc, there isnt an issue. However, when sending directly to a chest for storage, the item is received by said chest saying for example:
" !!!Aluminum Ingot!!!!
Item with stored LogisticsPipes routing information
Drop to remove routing information and get original items back"

This is a pain in the butt because this means if the same item comes in different batches, it will not stack. Not sure how to fix this.

**Comment by dblsaiko** [comment]
I think inserting them into the inventories via LP pipes would solve that. There's no way for BC pipes to store LP routing information so has to store that in the item itself, but that information will get removed when the items enter into a LP pipe again.

**Comment by Bernasss12** [comment]
Can you please show some screen shots showing how you have that network setup? I mainly want to understand how the items are getting out of the LP network and into a chest.
