### ISSUE TITLE
Autocrafting with programer

### ISSUE THREAD

**Issue by schmegle** [RS485/LogisticsPipes#1419]
I am trying to auto craft a crafting pipe, and I can craft them one at a time but when I try and craft 2 it says I don't have enough programmers. is their another way so that I don't have to make 20 programmers for every recipe I want to autocrat

**Comment by ybeauchamph** [comment]
You should leave a Logistics programmer inside the Crafting table programmed for the specific item but **remove it from the crafting pipe**.
Since it it not consumed, the crafting table will be able to craft the item without logistics pipe sending it a programmer for every item.
