### ISSUE TITLE
与BuildCraft模组的联动

### ISSUE THREAD

**Issue by wstc1997** [RS485/LogisticsPipes#1420]
I'd like to ask the developers if the new version 0.10.2.216 does not support the Facade of buildcraft

**Comment by Bernasss12** [comment]
No, the current versions of Logistics Pipes do not support BuildCraft's Facades.
The alternative to cover your pipes up is to use [MCMultiPart](https://www.curseforge.com/minecraft/mc-mods/mcmultipart) blocks. For example [Chisel and Bits](https://www.curseforge.com/minecraft/mc-mods/chisels-bits) should work like a facade with LP pipes.

**Comment by wstc1997** [comment]
In the version of 1.12.2,Logistics Item Card have no recipes.
