### ISSUE TITLE
Redstone signal on item amount (level emitter)

### ISSUE THREAD

**Issue by RoelofvdG** [RS485/LogisticsPipes#1422]
I was wondering if it is possible to add a pipe/module/block/upgrade that can emit a redstone signal when a certain amount of items is (not) present in the LP system. Basically a relational operator on a certain item amount (<, >, =, etc.). This was also mentioned in an issue dating back to 2014, (#526), but it would add more dependency on BC. Afaik LP is now pretty much free of BC, and adding aforementioned functionality could be done without BC. It is also mentioned in #1135, but no particular attention is paid to it. It also appears (part of) the functionality already exists in the form of the item amount sign.

Maybe it can already be done, but I can not figure out how. Compatibility with RS seems to not exist, and AE2 only goes one way. BC gates work, but can only do <x% comparisons, which doesn't help much for turning on/off a tree farm for example, and makes it useless when using drawers/barrels. RFTools's level emitter and inventory scanner also do not seem to work. 

PS: massive kudos for porting to 1.12, LP is by far my favourite mod and now I can play something other than 1.7.10 😛

**Comment by bziemons** [comment]
This is definitely what #1135 is for, please continue on that issue.
