### ISSUE TITLE
Creative Tab ItemSink Module server crash

### ISSUE THREAD

**Issue by pitris90** [RS485/LogisticsPipes#1427]
When I want to use Creative Tab ItemSink module in my sort sytem on my server, server will crash and only Forge option _removeErroringEntities_ or _removeErroringTileEntities_ will remove pipe with CreativeTabItemSink module...

Minecraft 1.12.2
Forge 2854
My own modpack
Logistic Pipes 0.10.2.216
Crash log: https://pastebin.com/q2hYmhbU

**Comment by Bernasss12** [comment]
Original issue:  #1391
