### ISSUE TITLE
The automatic crafting system is creating a huge delay.

### ISSUE THREAD

**Issue by NelkGames** [RS485/LogisticsPipes#1429]
I started setting up an area for automatic craftings, after I connected the tubes to the system, my game got a horrible delay.
at first I didn't notice that this was the problem, I removed some mods, put more memory in the game, but I continued with the problem.
now, after having removed much of my system, I disconnected the crafting area and the game returned to normal.

-I am using version 0.10.3.6, the previous one also had this problem.
![Screenshot_2](https://user-images.githubusercontent.com/19228548/80730090-8613b500-8adf-11ea-9ead-ab49803aa668.png)
![Screenshot_1](https://user-images.githubusercontent.com/19228548/80730095-8744e200-8adf-11ea-9fa8-9ff6a0318969.png)

**Comment by bziemons** [comment]
I would need profiling or at least sampling data to understand whats going on. Will test more crafting performance in the future, but right now there are more issues with actually developing on the mod hence the 0.10.3 ForgeGradle 3 version. A Java update has broken ForgeGradle 2 hacks and the development team is not going to fix that.

**Comment by NelkGames** [comment]
I can send the files, I just need to know what they are, I'm not very familiar with these types of issues :/

**Comment by bziemons** [comment]
You would actually need the tools to create those files. You could give me your server's debug log though. There could be something in there. It probably is several megabytes, so please compress it and you should be able to append it to a comment here on GitHub

**Comment by NelkGames** [comment]
here are the files, if you need a list of the mods I'm using I can also send
[logs.zip](https://github.com/RS485/LogisticsPipes/files/4560652/logs.zip)

**Comment by bziemons** [comment]
nah, sorry. From looking at the log files I haven't found a problem with LP directly. Do you have any LP pipes connected to other mods (like EnderIO, TD Item Ducts, BuildCraft)? If yes, can you remove those connections and see if that makes it any better?

**Comment by NelkGames** [comment]
well, I have other mods with inventory systems, but none of them connect directly to LP, on the other hand, I'm using an addon that makes LP have an inventory connection with Applied Energistic
https://www.curseforge.com/minecraft/mc-mods/logistics-bridge
so far I haven't had any performance problems, even not using the automatic workbenches, but I can place them to see if this problem still exists

**Comment by bziemons** [comment]
Also, while you're at it.. please check if your whole LP system is chunk-loaded. In the past there were some performance problems with that

**Comment by NelkGames** [comment]
I just tested it and everything is working correctly, the delay is gone :D
I am not using the latest version (10.3.29) because the LP addon is crashing before the game starts, but the previous version (10.3.28) is ok and I no longer have the problem with crafting pipes =)

I would also like to take the opportunity to give a suggestion, it would be good if the fuzzy upgrade could be used in Supplier Pipes.

**Comment by bziemons** [comment]
I'd close this for now, hoping that we'd find the cause next time it happens. This is not reproducible at the moment.
