### ISSUE TITLE
Inconsistent behavior with Item Extraction Upgrades

### ISSUE THREAD

**Issue by aaronhowser1** [RS485/LogisticsPipes#1434]
My setup
![image](https://user-images.githubusercontent.com/15698722/80959460-77bde580-8dcc-11ea-8a0c-156772222897.png)
The Chassis on the left has only an Extractor Module with no upgrades, and the Basic Log Pipe is set to be the default route.

When I reconnect them and allow it to work once, then disconnect them again, it sends 1 item.
![image](https://user-images.githubusercontent.com/15698722/80959524-98863b00-8dcc-11ea-9271-0407f168b9ff.png)

After I move the items back to the first chest, install a Module Upgrade and a single Item Extraction Upgrade, then reconnect and allow it to work once, it takes 4 items.
![image](https://user-images.githubusercontent.com/15698722/80959676-e56a1180-8dcc-11ea-98fe-48238f56712f.png)

After moving the items back and allow it to work once again, it takes 8 items:
![image](https://user-images.githubusercontent.com/15698722/80959733-0468a380-8dcd-11ea-9b1e-bc6756885eb6.png)

After moving the items back __again__ and allowing it to work once, it takes 16 items:
![image](https://user-images.githubusercontent.com/15698722/80959778-2104db80-8dcd-11ea-80e3-e8b399bae733.png)

And then it takes 32 items, and then stops increasing and takes 32 items every time.

After **removing** the upgrade, it now takes 64 items at a time. (I've stopped breaking and replacing the pipe).

If I install 2 upgrades, it removes 4 stacks at a time. Adding any more upgrades does not increase this.

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/80960020-9e305080-8dcd-11ea-8313-0ef775ccb05e.png)
I'm making quests for Logistics Pipes, and this is the first stumbling block so far.

**Comment by aaronhowser1** [comment]
This is also probably related to #1431

**Comment by bziemons** [comment]
Yes, from what you describe it is exactly #1431 

Am I missing something? It seems like the upgrades are kinda breaking the functionality which they are upgrading

**Comment by aaronhowser1** [comment]
#1431 was me removing upgrades, while this is upgrades not working correctly while installed

**Comment by bziemons** [comment]
Code-wise it'll probably be the same bug, so I'll duplicate this.

**Comment by bziemons** [comment]
> ![image](https://user-images.githubusercontent.com/15698722/80960020-9e305080-8dcd-11ea-8313-0ef775ccb05e.png)
> I'm making quests for Logistics Pipes, and this is the first stumbling block so far.

That looks very nice by the way :)
