### ISSUE TITLE
It's difficult to specify an amount of items to request in Suppliers

### ISSUE THREAD

**Issue by aaronhowser1** [RS485/LogisticsPipes#1436]
If you hold half a stack of Stone in the cursor and click on one of the slots, it sometimes puts only one in
![image](https://user-images.githubusercontent.com/15698722/80963161-097d2100-8dd4-11ea-808b-a82b35944f71.png)
Sometimes when you click it again, it goes up to 2
![image](https://user-images.githubusercontent.com/15698722/80963196-139f1f80-8dd4-11ea-8ef1-0d3f5231501b.png)
or sometimes it goes down 1
![image](https://user-images.githubusercontent.com/15698722/80963210-1a2d9700-8dd4-11ea-9171-ca9bea091dab.png)
and sometimes, it puts in 32 like it's supposed to.
![image](https://user-images.githubusercontent.com/15698722/80963219-21ed3b80-8dd4-11ea-9100-15a5c3f7d823.png)

I notice there's some other mildly obscure interactions, like right clicking while holding nothing to halve the amount, or right clicking while holding something to increase the amount by one. These should probably be written down somewhere.

**Comment by bziemons** [comment]
Yes that functionality goes back before modded multiplayer. I think it accumulated some bugs though, like the jump by 2. If someone has an idea for a better way to change the count without big changes, please write them down in here.

**Comment by aaronhowser1** [comment]
Why not just make it always use the amount you put in? So if you put in 32 Stone, it always puts in 32 Stone

**Comment by bziemons** [comment]
I would like to be able to have a different amount than I have in my hand. Also with JEI you are only able to drag in an ItemStack with a single item. I do like to change that count.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
