### ISSUE TITLE
You need a LOT of Item Speed Upgrades before it makes much of a difference

### ISSUE THREAD

**Issue by aaronhowser1** [RS485/LogisticsPipes#1438]
![image](https://user-images.githubusercontent.com/15698722/80967829-9e841800-8ddc-11ea-9e4f-e1223cda7079.png)
With no upgrades, it takes about two seconds for an item to transfer.

With only one upgrade, it doesn't make a noticeable difference. Even with 16, it's only like 50% faster. You have to have a whole stack before it about matches the speed of an impulse itemduct.

**Comment by bziemons** [comment]
Right that works as intended. That's why you can stack up to 16 speed upgrades in one slot.
