### ISSUE TITLE
ItemStack Extraction Upgrade doesn't increase the amount sent at a time to a full stack

### ISSUE THREAD

**Issue by aaronhowser1** [RS485/LogisticsPipes#1439]
![image](https://user-images.githubusercontent.com/15698722/80969028-962cdc80-8dde-11ea-9063-589b88ea65ac.png)
being sent to
![image](https://user-images.githubusercontent.com/15698722/80969105-afce2400-8dde-11ea-8d2e-19f7f01e6036.png)
but only sends 8 at a time
![image](https://user-images.githubusercontent.com/15698722/80969141-bd83a980-8dde-11ea-9e37-f2f59bd49fcb.png)

**Comment by bziemons** [comment]
that is correct. The name might be a bit misleading. Upgrading a provider with it will make that work on  up until 9 provide tasks (given it has 8 ItemStack extraction upgrades) at the same time and it would theoretically extract `8 * (int) Math.pow(2, getUpgradeManager().getItemExtractionUpgrade()) = 8 * 2^(upgrade count)` items *combined* at maximum. That would be 2048 items per worktick (not every tick, see action speed upgrade) with 8 ItemStack extraction upgrades.

**Comment by aaronhowser1** [comment]
So it's explicitly only for multitasking, basically? It only really does anything if multiple destinations are pulling from it?

**Comment by bziemons** [comment]
no, e.g. with those 8 upgrades it would take up to 2048 items for one task, if that task needs that many items at once. I haven't tested this extreme case and I am not sure if it would take from more than one stack from the attached inventory, but given a Deep Storage Unit or something similar it should work like that.

**Comment by bziemons** [comment]
The following is implemented in thew new async extractor now: The rule above applies to the item extraction upgrade. And the itemstack extraction upgrade increases the amount of stacks to look at in the attached inventory.
