### ISSUE TITLE
[Suggestion] Since Opaque Upgrades can't be placed on Unrouted Transport Pipes, maybe it should just permanently make items that pass through them invisible?

### ISSUE THREAD

**Issue by aaronhowser1** [RS485/LogisticsPipes#1440]
So instead of having to have every pipe be at least a Basic Logistics Pipe, instead it just toggles visibility on that item.
![image](https://user-images.githubusercontent.com/15698722/80969510-5286a280-8ddf-11ea-8ef7-e7851a37f8f0.png)
There's an Opaque Upgrade in this intersection, but it only makes items invisible while they're specifically in that pipe. They're immediately visible again when they leave it, which kind of defeats the whole point.

**Comment by aaronhowser1** [comment]
Also, "Opaque" is a bit of a weird name for something that makes things *invisible*. Unless it's meant to change the texture of the pipe too?

**Comment by bziemons** [comment]
Actually there is a OpaquePipes config option, so I'd suggest using that if it is desired. The definition of the word comes from the ThermalDynamics ducts with the same name. Setting the config option (on the server) or upgrading pipes with that will actually not even send the client information about items in that pipe. Additionally or when just set in the client's config it will just not render items in the pipes.

That said I like the idea of the item being invisible until it hits another pipe that does not have this upgrade and it should be doable storing this information with the traveling item as well.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
