### ISSUE TITLE
Request Pipe Mk2 isn't faster than Mk1

### ISSUE THREAD

**Issue by aaronhowser1** [RS485/LogisticsPipes#1442]
![image](https://user-images.githubusercontent.com/15698722/81041086-87900500-8e72-11ea-8a39-73d3e1e57847.png)
I've tested requesting two stacks of an item in this chest with both an Mk1 and Mk2 pipe, and I noticed no difference. The tooltip for the Mk2 says it's faster than the Mk1, but I couldn't see it.

The Mk1 took about 13 seconds from requesting 2 stacks to the last batch of 8 items arriving, and the Mk2 took about the same. Both even brought it in batches of 8 items.

**Comment by bziemons** [comment]
Might be a copy-paste bug in the language file, because other than having a logistics disk slot or being able to open its GUI without a wrench in the past, I cannot remember any other differences.
