### ISSUE TITLE
Crash when right clicking newly spawned Disk onto Request Pipe Mk2

### ISSUE THREAD

**Issue by aaronhowser1** [RS485/LogisticsPipes#1443]
https://paste.dimdev.org/oqugehaneb.mccrash
It does put a Disk in the slot, though
![image](https://user-images.githubusercontent.com/15698722/81041286-1ac93a80-8e73-11ea-8cd4-3cd8f6927338.png)
Clicking the Disk in the slot drops it into the world, duplicating it.
![image](https://user-images.githubusercontent.com/15698722/81041307-274d9300-8e73-11ea-8feb-8b2f1d62e705.png)

What is the disk even supposed to be used for?

**Comment by bziemons** [comment]
It enables macro requests, so you could request a bunch of items in one click.

**Comment by bziemons** [comment]
Sorry, I cannot reproduce the crash and the log is not accessible anymore. Can you reproduce it with the latest build? If yes, could you re-upload the crash?
