### ISSUE TITLE
Logistics Fuzzy Crafting Table recipe is much simpler than the normal one

### ISSUE THREAD

**Issue by aaronhowser1** [RS485/LogisticsPipes#1446]
![image](https://user-images.githubusercontent.com/15698722/81050337-6dabed80-8e85-11ea-9a1c-6d44feafd161.png)
![image](https://user-images.githubusercontent.com/15698722/81050352-743a6500-8e85-11ea-9971-c6332ec9f52c.png)

**Comment by bziemons** [comment]
I think the recipe for the fuzzy one should actually need a basic crafting table instead of the frame.
