### ISSUE TITLE
Issue supplying Auto Workbench from BuildCraft with ItemSink module

### ISSUE THREAD

**Issue by Fogapod** [RS485/LogisticsPipes#1447]
### Versions
* Logistics Pipes: `0.10.2.218`
* BuildCraft: `7.99.23`
* Minecraft: `1.12.2`
* Forge: `14.23.5.2847`

### Problem
Items go to default route instead of ItemSink destination into Auto Workbench.

### Steps to reproduce
Setup:
![2020-05-05_12 15 35](https://user-images.githubusercontent.com/22667809/81051590-a4582700-8eca-11ea-956a-7fb894280687.png)
Basic pipe on the left is set to default rote.

ItemSink module in Chasis pipe on the right has these settings:
![image](https://user-images.githubusercontent.com/22667809/81051809-16c90700-8ecb-11ea-8277-18f583950bbd.png)

Auto Workbench inventory:
![image](https://user-images.githubusercontent.com/22667809/81051874-33653f00-8ecb-11ea-9f91-986a4c514b27.png)

When I put items inside hopper, they go to the default route not even trying to enter Auto Workbench.
This is caused by items being in any other than 1st slot in Auto Workbench.

As soon as I move item to the left, items start coming in:
![image](https://user-images.githubusercontent.com/22667809/81052189-aec6f080-8ecb-11ea-9f59-2a4e54988f30.png)
(until they overflow 1 stack and go to 2nd slot)

This looks like a Logistics Pipes bug because basic pipe with same settings as ItemSink module always supply items properly.

**Comment by bziemons** [comment]
Since the `roomForItem` method has been refactored, this needs to be re-tested.

**Comment by Fogapod** [comment]
Are these changes released yet or master should be used? Or are they on different branch?

**Comment by bziemons** [comment]
Yes, the changes are in the latest release: [0.10.3.33](https://ci.rs485.network/job/LogisticsPipes-0.10-mc1122-fg3/33/) also available on CurseForge
