### ISSUE TITLE
issues for 1.6; 

### ISSUE THREAD

**Issue by AartBluestoke** [RS485/LogisticsPipes#145]
16 almost compiles, just a few residual issues:

ASM:
Resolved.
## 

Textures: 
done other than liquids
## 

Fluids
- [x] converting of fluids to an ItemIdentifier, as fluids are not Items any more.
- [x] rendering code needs an update
## 

Network:
resolved, other than fluid NBT tags

**Comment by jeffreykog** [comment]
RelaunchClassLoader -> net.minecraft.launchwrapper.LaunchClassLoader

IClassTransformer -> net.minecraft.launchwrapper.IClassTransformer

**Comment by AartBluestoke** [comment]
updated initial post, 16 only has some fluid handling to do.

**Comment by GUIpsp** [comment]
- [x] Update IC2 integration
- [x] [Update NEI integration](http://puu.sh/4ipz3.txt)

**Comment by davboecki** [comment]
Fluid stuff seems to work now. Even the settings converting from old 1.5 worlds seems to do it's job correcly.
