### ISSUE TITLE
[1.12.2] Trying to sort an Open Computers Cable crashes the client

### ISSUE THREAD

**Issue by fkrisi11** [RS485/LogisticsPipes#1453]
Here is the crashlog: https://pastebin.com/1D2EjiQ8

I just put a cable from Open Computers into the request table's sort slot, to try to store it in the LP system, and it crashed the client.
This crash happens every single time when trying to sort that cable.

Minecraft version: 1.12.2
Logistics Pipes version: logisticspipes-0.10.3.14
Forge version: forge-1.12.2-14.23.5.2847

**Comment by fkrisi11** [comment]
This also makes it impossible to auto-craft said cable, as it shows up as "air" in the request table.
Requesting that "air" (as it shows up in the request table) says in chat, that the Cable was requested (it has the correct name in chat), but as expected, when the cable tries to make its way through the LP system, it crashes the client with the very same log as above.

**Comment by fkrisi11** [comment]
Opening a request table that has a cable in its storage causes this crash: https://pastebin.com/E7Bh3zdt

**Comment by bziemons** [comment]
This is giving other problems as well. Still investigating.

**Comment by bziemons** [comment]
This has to be fixed on OpenComputer's side. There is no way we can handle an ItemStack that isn't empty but says so.

**Comment by bziemons** [comment]
I saw this again and I think I am going to close this here. I am following the issue on OC and I'll see if it gets fixed. There really is nothing to do on our end.
