### ISSUE TITLE
Project Red Relocation Frame issue

### ISSUE THREAD

**Issue by Zeloz42** [RS485/LogisticsPipes#1456]
As far as I can tell, when just the Project Red mods (Base, Compat, Integration, Lighting, Mechanical, World) and Logistics Pipes and Forgelin are installed, when placing a cover on a relocation frame and then moving it results in this error after a few seconds and the frame blocks that had covers on them vanish/delete: [17:14:51] [Server thread/WARN]: SavedMultipart at BlockPos{x=210, y=77, z=270} still exists after 600 ticks!

**Comment by bziemons** [comment]
Just to make sure, what kind of cover are we talking about?

**Comment by Zeloz42** [comment]
Hello,

The covers are the standard forge micro blocks, panels also work too (they’re used to either make the frames not attach to things and additionally for aesthetics).

**Comment by busti** [comment]
The issue has been described in more detail here:  
https://github.com/MrTJP/ProjectRed/issues/1568
