### ISSUE TITLE
logisticspipes.ticks error

### ISSUE THREAD

**Issue by epeeforteyt** [RS485/LogisticsPipes#1457]
Hello, I have this error when I log into my map server, I don't know where it can come from, any idea?

thank you :)

[crash-2020-05-12_20.21.45-client.txt](https://github.com/RS485/LogisticsPipes/files/4617739/crash-2020-05-12_20.21.45-client.txt)
[crash-2020-05-12_19.58.53-client.txt](https://github.com/RS485/LogisticsPipes/files/4617740/crash-2020-05-12_19.58.53-client.txt)

**Comment by bziemons** [comment]
I am guessing there was a timing issue involved, but considering this happened twice already, it might also be another mod. I added a check that doesn't update the pipe on the client, if there is no data for it. This shouldn't harm and the pipe will hopefully get another update.
