### ISSUE TITLE
Issue for w00tc0d3: Remote Order Issue

### ISSUE THREAD

**Issue by jztech101** [RS485/LogisticsPipes#146]
> w00tc0d3: Version: LogisticsPipes-MC1.5.2-0.7.3.dev.563
> w00tc0d3: I have basically setup a system to pull let LP see my AE storage
> w00tc0d3: and when I remote order a item, it pulls the items out of the AE, crafts them with LP, but, if I order 3 of them, and I have 2 in stock, 2 go in the chest, the other 1 gets crafted but goes in the AE system

Needs Testing on Latest Dev Build

**Comment by davboecki** [comment]
I suspect he used a chassie pipe as a destination. Then this bug should be fixed.
