### ISSUE TITLE
Unable to craft Chassis Mk1

### ISSUE THREAD

**Issue by yves-chevallier** [RS485/LogisticsPipes#1462]
I have made all the researches: 

![image](https://user-images.githubusercontent.com/52489316/82620207-31dc8c00-9bd8-11ea-9792-0c20a10ed1a4.png)

But I am still unable to craft the Chassis MK1:

![image](https://user-images.githubusercontent.com/52489316/82620252-46208900-9bd8-11ea-906f-dbae0fc07a38.png)

I am running on `logisticspipes-0.10.3.14`, MC `1.12.2`.  (the 0.10.3.14 doesn't work on my server an exception occurs).

**Comment by bziemons** [comment]
I cannot seem to reproduce that issue with the newest version:
![Screenshot from 2020-05-22 03-58-01](https://user-images.githubusercontent.com/1096713/82623454-83891480-9be0-11ea-8543-0b06437d04a6.png)

Do you have any recipe altering mods installed? e.g. CraftTweaker. Also I don't quite get your last sentence. What LP version do you have now? 0.10.3.14 ? What exception is being thrown in the latest version? Can you show me the tooltip of the Logistics Programmer item? Does it say "Logistics Chassis Mk1" ?

**Comment by yves-chevallier** [comment]
Ok my mistake. I did not understand that I need to load the program into the programmer. Now it works!
