### ISSUE TITLE
there is no extractor module MK2

### ISSUE THREAD

**Issue by GabrielitoPL** [RS485/LogisticsPipes#1466]
Hello, I realized that LP does not exist the module mk2 extractor and there is only the normal one and an advanced assumption of it and I say of course why it only adds boxes but does not extract faster which is not a bad idea either, but it would be very useful to extract with greater speed or am I missing something wrong ?. And I tried to use the active provider module and provider module to extract but it consumes too much resources to manufacture them and I have to improve the chassis logistics to place everything I have to do in my progress in the game and that implies more resources than I have to collect and consume more diamonds and that makes it difficult for people who create massive constructions as in my case in the issue of mining resources by automating with industrialcraft machines but well as the mod is in alpha state I don't know if you can add these modules or have any new functionality or something you sent me lost, as I see new things in this version because maybe I missed something, I follow this mod since 1.4 .7 a greeting
Game versión 1.12.2
Versión Logisticspipes-0.10.3.14.jar

**Comment by bziemons** [comment]
Adding the Module Upgrade to the chassis pipe allows you to upgrade the extractor module with Action Speed and Item Extraction Upgrades. Those should do what you want
