### ISSUE TITLE
Crash on Startup with Latest Versions of Both Logistics Bridges and Pipes

### ISSUE THREAD

**Issue by Gryffen1971** [RS485/LogisticsPipes#1467]
Minecraft Version:  1.12.2
Forge Version:  Latest Version for 1.12.2
Logistics Pipes:  0.10.3.29
Logistics Bridges:  1.3.2

After updating Logistics Bridges and Pipes to there latest version the game crashes at Stage 2/7
Error is listed below and Crash Log is provided.

Here is what the error is;

java.lang.IllegalAccessError: no such constructor: com.tom.logisticsbridge.pipe.BridgePipe.<init>(Item)void/newInvokeSpecial

[Crash Log](https://pastebin.com/ET9JDrVi)
I've also reported it on the Issue Page for Logistics Bridges

**Comment by bziemons** [comment]
To be fixed in the Logistics Bridge mod.

**Comment by Gryffen1971** [comment]
Ok, just wanted to let you know.
