### ISSUE TITLE
Sneaky Upgrades should work with non-item-sinking modules

### ISSUE THREAD

**Issue by gholms** [RS485/LogisticsPipes#1470]
Sneaky Upgrades are currently documented as working only with pipes and item-sinking modules, but it would be useful to be able to use them with other modules as well.  By way of example, a Chassis connected to the bottom of a vanilla furnace could have a Crafting Module that uses a Sneaky Upgrade to insert ore into the top of the furnace as well as an Active Supplier Module that uses a Sneaky Upgrade to insert coal into the furnace's side.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
