### ISSUE TITLE
Double-clicking an entry in the satellite selection dialog should close the dialog

### ISSUE THREAD

**Issue by gholms** [RS485/LogisticsPipes#1471]
To select which Satellite Pipe a given Crafting Pipe or Module should use one needs to open up a dialog box with a list of reachable Satellite Pipes, click one, then click Select.  It would be faster to let a double-click on an entry in the list select that entry and close the dialog box.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
