### ISSUE TITLE
Clicking Save when naming Satellite Pipes should close the naming dialog

### ISSUE THREAD

**Issue by gholms** [RS485/LogisticsPipes#1472]
Naming a Satellite Pipe involves typing its name into a text box, clicking "Save", and closing the dialog box.  There are no other buttons or other functionality in this dialog, so pressing the return key while the text box is active or clicking "Save" or should save the new name box and immediately close the dialog to save a little bit of effort.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
