### ISSUE TITLE
Null string whenever placing multiple satellite pipes

### ISSUE THREAD

**Issue by AiJermain** [RS485/LogisticsPipes#1474]
I am working on a pack for a Twitch community and am running into a issue where whenever you place to many of the Satellite pipes it causes a client crash the server works fine but the client crashes each time to many are placed. 

https://pastebin.com/3zZSY23a

**Comment by bziemons** [comment]
> This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff.

**Comment by SonOfTheStars** [comment]
I have run into the exact same issue just a few moments ago. It happened as I had a liquid satellite pipe in my hands and accidentally right clicked the ground on which another liquid satellite pipe was already standing.

**Comment by AiJermain** [comment]
> I have run into the exact same issue just a few moments ago. It happened as I had a liquid satellite pipe in my hands and accidentally right clicked the ground on which another liquid satellite pipe was already standing.

Yes that is exactly when I got the error. I just noticed Bziemons response so hopefully he can fix it once I re upload the error message. 


> > This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff.

Sorry for the late reply I will try to upload it again once I get back home!
