### ISSUE TITLE
Crash when transfering recipes from JEI to Fuzzy Crafting Table

### ISSUE THREAD

**Issue by whitebear60** [RS485/LogisticsPipes#1475]
When I tried to transfer recipe of Solar Flux Reborn Solar Mirror, the game has crashed. Crashlog attached.
[Crashlog on Pastebin](https://pastebin.com/N1R5deBy)

**Comment by whitebear60** [comment]
Minecraft 1.12.2
Forge 14.23.5.2854
Logistics Pipes 0.10.3.34

**Comment by whitebear60** [comment]
I have forgot to say that this crash appear also when I try to transfer any recipe to any Logistics Pipes' Crafting Table, such as Logistics Crafting Table or Logistics Request Table, not just in Fuzzy Crafting Table.

**Comment by misamisk** [comment]
https://pastebin.com/UbyuDt3A
