### ISSUE TITLE
Sink Modules void items oversent to them

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#1477]
**Description:** Inserting items into a routed pipe and having it sink to a default location sees the item voided if the sink inventory is full. It appears not to report that the inventory is full or attempt to resend it to the next location if there is one. Instead, the items simply vanish from existance.

**Build Version:** 10.3.33/35

**Mode:** Dedicated Server

**Comment by bziemons** [comment]
Cannot reproduce this. Can you check and find out more on why this is happening?

**Comment by SonOfTheStars** [comment]
It turns out this was a mistake by me. The items werent deleted, they was a hidden second inventory page to the storage mod I was using. The button to access that second inventory page was hidden due to a UI overlapping issue so it only seemed to delete the items but they were actualy just hidde away from me.
