### ISSUE TITLE
ComputerCraft Took too long

### ISSUE THREAD

**Issue by bziemons** [RS485/LogisticsPipes#148]
Version 0.7.3.dev.632

```
Took too long (getAvailableItems,logisticspipes.pipes.PipeItemsRequestLogistics)
```

This error should not be pushed to the serverlog.
Also might there be a way to prevent this? Well, except going back to the event system.

**Comment by ArtForz** [comment]
Mitigated, we now only log a warning if a CC call takes too long instead of spamming a stacktrace to stdout
