### ISSUE TITLE
Crash when loading recipes from JEI to LogisticsPipes' Crafting Tables

### ISSUE THREAD

**Issue by whitebear60** [RS485/LogisticsPipes#1480]
#1475 This issue is reference to my previous issue. It is not fixed. In LogisticsPipes 0.10.3.36 this crash still appear.

**Comment by whitebear60** [comment]
I can provide a video demonstration if needed

**Comment by whitebear60** [comment]
Video Reproduce: https://youtu.be/k3ku1Iz3DWg

**Comment by bziemons** [comment]
Can you please attach the crash log? The issue might still look the same, but the same crash just isn't possible.

**Comment by whitebear60** [comment]
One minute.

**Comment by whitebear60** [comment]
Crash log on Pastebin: https://pastebin.com/6XU0RCbr

**Comment by whitebear60** [comment]
I provided video for more details. And it is not depend on recipe that I trying to transfer to Crafting Table

**Comment by bziemons** [comment]
Thanks for your patience :) Made it possibly to use JEI in my dev env now… I was missing it anyway in there

**Comment by whitebear60** [comment]
It is not critical. I have more confused that JEI integration has worked earlier, but it is not work now. I will test with new release and write here if it will not work. Please, re-open the issue. I will close it if this crash will not appear anymore.

**Comment by bziemons** [comment]
From my perspective it is better to leave all issues closed that are supposedly fixed. It's not like I have the time to go over issues and close them if needed. We are missing the automation to close after inactivity as well.

**Comment by whitebear60** [comment]
I have tested in LP 0.10.3.38 and it crashes

**Comment by bziemons** [comment]
Can you attach the current crash log then?

**Comment by whitebear60** [comment]
https://pastebin.com/UbyuDt3A

**Comment by bziemons** [comment]
Yeah, that's for 0.10.3.36. Can you upload the current crashlog?

**Comment by whitebear60** [comment]
I had a mistake yesterday. The game isn't crashed, but the unexpected end of game occured. When I have tried to import the recipe from JEI to Logistics Request table, Minecraft shutted down its internal server and show me this screen:
![Screen Shot 2020-06-17 at 19 39 07](https://user-images.githubusercontent.com/42472132/84925675-ef24ab80-b0d2-11ea-83e3-a0fb82867b5f.png)
[latest.log on Pastebin](https://pastebin.com/vSFwH6R3)

**Comment by bziemons** [comment]
From our license:

> As a prerequisite, a user must own a legally acquired copy of Minecraft

since I don't see that being the case, I wont give any support.
