### ISSUE TITLE
Items thrown in the world when there are no space in Logistics Crafting Table

### ISSUE THREAD

**Issue by whitebear60** [RS485/LogisticsPipes#1482]
When I request many of any craftable item that needs other crafts (for example, if system can craft Oak Wood Planks from Oak Wood and I'm request pistons (in chests that system can access present: Oak Wood, Iron Ingots, Redstone and Cobblestone), the system cannot put items to the Logistics Crafting Tables and throws it in the world.

Video: https://youtu.be/L4HxFagEynM

LP v.10.2.218

**Comment by bziemons** [comment]
Do you have a default route with a provider module/pipe ?

**Comment by whitebear60** [comment]
Yes

**Comment by bziemons** [comment]
where would that be in the video you have put in the description?

**Comment by whitebear60** [comment]
Maybe I has not set a default route. Thanks for the feedback.
