### ISSUE TITLE
Logistics Program Compiler damage  appear BUG

### ISSUE THREAD

**Issue by yueshangyue** [RS485/LogisticsPipes#1483]
Logistics Program Compiler will cause an unknown BUG Forestry backpack to break when it is destroyed and it will freeze when the game exits 

Poor English may not be very accurate

**Comment by bziemons** [comment]
I don't exactly understand the problem. Could you try to explain it step by step?

**Comment by yueshangyue** [comment]
Take out the Logistics Disk inside and destroy it will not crash my world
However, I just used Logistics Crafting Table and just used Just Enough Items to add recipes with one click and found another bug
And recorded a short video

https://youtu.be/hNqIguaUeDc

**Comment by bziemons** [comment]
@yueshangyue on which LP version was that video made?

**Comment by yueshangyue** [comment]
0.10.3.38

**Comment by yueshangyue** [comment]
The same situation still appears after the 39 version update

**Comment by bziemons** [comment]
Should be fixed in build 40
