### ISSUE TITLE
Interacting with the Crafting Manager GUI causes a NoSuchFieldError

### ISSUE THREAD

**Issue by Flame500** [RS485/LogisticsPipes#1485]
When clicking anywhere in the Crafting manager's UI, it crashes the game giving a java.lang.NoSuchFieldError: modules

The crash seems to happen when clicking anywhere in the GUI, however, as long as you don't click in the GUI, nothing happens, you can break it, place it, and open the menu just fine. Currently using the 0.10.3.36 version.

Crashlog: https://pastebin.com/DWTwdhFa

**Comment by bziemons** [comment]
The crash is in Logistics Bridge, have you updated Logistics Bridge?

**Comment by Flame500** [comment]
Updated both Logistic Bridge and (due to dependancies) Logistic Pipes, which seems to have fixed the issue.
