### ISSUE TITLE
Remote Orderer on Chassis Pipe

### ISSUE THREAD

**Issue by charles7926** [RS485/LogisticsPipes#1487]
When using a Remote Orderer on a chassis pipe, everything requested is rejected.  For example, I use a remote orderer on a Logistics Chassis MkII connected to a Macerator.  I request a stack of Cobblestone.  The cobblestone are requested, but do not enter the Macerator, they just return to their chest.  This occurs on all machines and chests I have tested (BC Objects, Forestry objects, Factorization objects)

Edit: Forge 6.6.0.515, Logistics pipes 83, 84, and 85

**Comment by MrTJP** [comment]
the pipe you click on to do the requests is not considered, so doing it on the actual pipe connected to the macerator won't work.  Do it on another pipe.

**Comment by bziemons** [comment]
But that's still a bug, MrTJP.

**Comment by MrTJP** [comment]
i know its a "bug" but its been that way forever.  Just throwing that out there.

**Comment by charles7926** [comment]
I remember being able to do this in previous versions.

Edit:  Yep, just checked on a backup I have.  Using Forge 6.5.0.489 and LogisticsPipes-MC1.4.6-0.6.9.74, I can click the remote orderer on a chassis MkII connected to a macerator and the cobblestone will enter the macerator and be macerated into sand.  Doing the same on LogisticsPipes-MC1.4.7-0.7.0.85 the cobblestone is rejected from the macerator is sent back to its chest.

**Comment by AartBluestoke** [comment]
somewhere along the way i think, while fixing a bug to do with passive providers sinking more items than were requested, we change things to bounce un-requested items. When a chassi revives the items the remote orderer requested it finds that they are not able to be sunk by any module, and as such get bounced as undeliverable.

**Comment by MrTJP** [comment]
i thought this was about the bug where if you requested it from a crafting pipe, the item that THAT pipe crafts would be unavailable…

**Comment by ArtForz** [comment]
Pretty sure this is the same change that prevents passive suppliers from oversupplying their attached inv...
I _guess_ we could just check if the item arriving at a chassi destination is activerouted, and if so unconditionally try to sink it (no chassi module can actively request things, so by exclusion anything activerouted to it must have been from remote ordering on it).

**Comment by Michal-MK** [comment]
![lp1](https://user-images.githubusercontent.com/12874766/124147833-58355200-da8f-11eb-85c4-660ad0d8004f.png)

The above setup works on latest dev branch, the chest contains ore and requesting that ore at the chassis inserts the ore into the macerator. Was it fixed at some point in 2020-21?

**Comment by bziemons** [comment]
> The above setup works on latest dev branch, the chest contains ore and requesting that ore at the chassis inserts the ore into the macerator. Was it fixed at some point in 2020-21?

Probably. Thanks for checking!
