### ISSUE TITLE
Smaller liquid request numbers

### ISSUE THREAD

**Issue by Alphaminion** [RS485/LogisticsPipes#149]
Not too sure if this is implemented yet somewhere and I can't find it but it would be nice to be able to request amounts of liquid smaller than 1 bucket without having to click buttons 100+ times.

I'm using the Tinkers Construct mod and as 1 ingot equates to 144/1000 of a bucket of molten metal these smaller increments when requesting a liquid would be amazing.

**Comment by ArtForz** [comment]
For manual requesting, scrollwheel, shift-scrollwheel, ctrl-scrollwheel and shift-ctrl-scrollwheel are your friends.

**Comment by bziemons** [comment]
Tell us if you do not have a mousewheel, otherwise I assume this ticket as solved.
