### ISSUE TITLE
LP Items can not be crafted

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#1495]
Issue: Items using the Logistics Programmer in their recipe can no longer be crafted. This appears to be because the recipes ask for a Programmer without any data on it.
![image](https://user-images.githubusercontent.com/3910862/85947806-2bff6680-b94d-11ea-8111-b6aaa33fcdb4.png)

This means neither normal nor Autocrafting works AT ALL.

Build: 0.10.3.44

Mode: Dedicated Server

Blame: 7c4044768804976d5414b9b9a5b949ccc22ac4a8

**Comment by bziemons** [comment]
Fixed in build 45
