### ISSUE TITLE
LP doesn't connect to AE2 interface. 

### ISSUE THREAD

**Issue by Acerixx** [RS485/LogisticsPipes#1497]
Bug exist in new version LP 10.3.46

modpack modlist:
ae2stuff-0.7.0.4-mc1.12.2.jar
AE2WTLib-1.12.2-1.0.34.jar
alchemistry-1.12.2-41.jar
alib-1.0.12.jar
alternatingflux-0.12.2-2.jar
appliedenergistics2-rv6-stable-7.jar
AutoRegLib-1.3-32.jar
Baubles-1.12-1.5.2.jar
bdlib-1.14.3.12-mc1.12.2.jar
binnie-mods-1.12.2-2.5.1.203.jar
blockcraftery-1.12.2-1.3.1.jar
Botania r1.10-363.jar
BuildingGadgets-2.8.3.jar
careerbees-0.4.0.jar
CD4017BE_lib-1.12.2-6.5.0.2.jar
Chameleon-1.12-4.1.3.jar
Charset-Audio-0.5.6.3.jar
Charset-Lib-0.5.6.4.jar
Chisel-MC1.12.2-1.0.2.45.jar
cloudcontrol_v1.0.0formc1.12.2.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
CoFHCore-1.12.2-4.6.6.1-universal.jar
CoFHWorld-1.12.2-1.4.0.1-universal.jar
Commons0815-1.12.2-1.3.7.jar
Computronics-1.12.2-1.6.6.jar
craftingstation-0.1.7c.jar
CraftingTweaks_1.12.2-8.1.9.jar
CraftTweaker2-1.12-4.1.20.574.jar
CreativeCore_v1.10.16_mc1.12.2.jar
CTM-MC1.12.2-1.0.2.31.jar
customstuff4-1.12.2-0.5.3.jar
DummyCoreUnofficial-2.4.112.5.jar
DynamicSurroundings-1.12.2-3.6.1.0.jar
enchantingwiththaumcraft-1.2.jar
EnderCore-1.12.2-0.5.76.jar
EnderIO-1.12.2-5.2.59.jar
EnderIO-endergy-1.12.2-5.2.59.jar
EnderStorage-1.12.2-2.4.6.137-universal.jar
engineersdecor-1.12.2-1.1.0.jar
engineerstools-1.12.2-1.0.5.jar
engineers_doors-1.12.2-0.8.0.jar
FasterLadderClimbing-1.12-0.1-146.jar
FastLeafDecay-v14.jar
foamfix-0.10.10-1.12.2.jar
forestry_1.12.2-5.8.2.387.jar
ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar
Forgelin-1.8.4.jar
ForgeMultipart-1.12.2-2.6.2.83-universal.jar
funky-locomotion-1.12.2-1.1.2.jar
GunpowderLib-1.12.2-1.0.jar
HammerLib-1.12.2-2.0.6.19.jar
Immersive-IO-1.12.2-0.9.5.jar
ImmersiveCables-1.12.2-1.3.2.jar
ImmersiveEngineering-0.12-98.jar
immersivepetroleum-1.12.2-1.1.9.jar
ImmersivePosts-0.2.1.jar
immersivetech-1.12-1.3.10.jar
industrialforegoing-1.12.2-1.12.13-237.jar
IndustrialWires-1.7-36.jar
IntegrationForegoing-1.12.2-1.10.jar
ironchest-1.12.2-7.0.72.847.jar
jeibees-0.9.0.5-mc1.12.2.jar
jei_1.12.2-4.15.0.296.jar
journeymap-1.12.2-5.7.1.jar
JustEnoughPetroleum-0.1.jar
JustEnoughResources-1.12.2-0.9.2.60.jar
LagGoggles-1.12.2-5.8-132.jar
librarianlib-1.12.2-4.21.jar
LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar
logisticspipes-0.10.3.46.jar
MagicBees-1.12.2-3.1.10.jar
malisiscore-1.12.2-6.5.1.jar
malisisdoors-1.12.2-7.3.0.jar
mcjtylib-1.12-3.5.4.jar
Mekanism-1.12.2-9.8.3.390.jar
MineralTracker-0.9.1.jar
ModularPowersuits-1.12.2-1.0.46.jar
moreoverlays-1.15.1-mc1.12.2.jar
MrTJPCore-1.12.2-2.1.4.43-universal.jar
mysticallib-1.12.2-1.7.0.jar
NoMoreRecipeConflict-0.13(1.12.2).jar
noRecipeBook_v1.2.2formc1.12.2.jar
NuclearCraft-2o.2.7-1.12.2.jar
Numina-1.12.2-1.0.38.jar
ocdevices-MC1.12.2-1.0.0-44.jar
oceio-1.12.2-1.0.001.jar
ocsensors-1.0.4-b23.jar
OfflineSkins-1.12.2-v6.jar
OpenBlocks-1.12.2-1.8.1.jar
OpenComputers-MC1.12.2-1.7.5.192.jar
OpenGlasses-MC1.12.2-2.2-50.jar
OpenLights-MC1.12.2-0.1.0.8.jar
OpenModsLib-1.12.2-0.12.2.jar
OpenPrinter-1.12.2-0.1.0.9.jar
OpenPython-MC1.12.2-OC1.7-1.0.1.jar
openscreens-1.12.2-1.0.1.jar
OpenSecurity-1.12.2-1.0-41.jar
OpenTerrainGenerator-1.12.2 - v8.3.jar
OptiFine_1.12.2_HD_U_F5.jar
OreLib-1.12.2-3.6.0.1.jar
p455w0rdslib-1.12.2-2.3.161.jar
Placebo-1.12.2-1.6.0.jar
ProjectRed-1.12.2-4.9.4.120-Base.jar
ProjectRed-1.12.2-4.9.4.120-compat.jar
ProjectRed-1.12.2-4.9.4.120-integration.jar
ProjectRed-1.12.2-4.9.4.120-lighting.jar
Psi-r1.1-78.jar
psipherals-1.1.0.jar
QMD-0.8.0-1.12.2.jar
Quark-r1.6-179.jar
QuarkOddities-1.12.2.jar
railcraft-12.0.0.jar
RedstoneControl-1.12.2-0.3.0.7.jar
RedstoneFlux-1.12-2.1.1.1-universal.jar
rftools-1.12-7.73.jar
rftoolsctrl-1.12-2.0.2.jar
rftoolsdim-1.12-5.71.jar
rftoolspower-1.12-1.2.0.jar
rftpwr_oc-0.2.jar
rpsideas-2.4.2.jar
sampler-1.84.jar
SimplyJetpacks2-1.12.2-2.2.14.67.jar
StorageDrawers-1.12.2-5.4.2.jar
tesla-core-lib-1.12.2-1.0.17.jar
Thaumcraft-1.12.2-6.1.BETA26.jar
ThaumicAdditions-1.12.2-12.4.3.jar
ThaumicAugmentation-1.12.2-1.1.19.jar
thaumicbases-3.3.352.6r.jar
thaumicbrewing-1.0.2.jar
thaumicenergistics-2.2.4.jar
thaumicperiphery-0.3.1.jar
ThaumicRestoration-1.4.0.jar
thaumictinkerer-1.12.2-5.0-620a0c5.jar
thaumicwonders-1.8.2.jar
Thaumic_Gadgets_1.12.2_0.1.5.1_tb.26.jar
theoneprobe-1.12-1.4.28.jar
ThermalCultivation-1.12.2-0.3.6.1-universal.jar
ThermalDynamics-1.12.2-2.5.6.1-universal.jar
ThermalExpansion-1.12.2-5.5.7.1-universal.jar
ThermalFoundation-1.12.2-2.6.7.1-universal.jar
ThermalInnovation-1.12.2-0.3.6.1-universal.jar
thermallogistics-0.2-29.jar
TickCentral-2.6.jar
Toast Control-1.12.2-1.8.1.jar
torchmaster_1.12.2-1.8.1.81.jar
UnlimitedChiselWorks-0.3.4.jar
UnlimitedChiselWorks-Botany-0.1.2.jar
Vanilla_Vistas 1.1.jar
WirelessCraftingTerminal-1.12.2-3.12.97.jar
XL-Food-Mod-1.12.2-1.9.2.jar
zettaindustries-1.3-1.12.2-161.jar

**Comment by pjvesely** [comment]
I believe I am having a related issue: 
After upgrading from 10.3.41 to 10.3.46, a specific logistics chassis which was connected to an AE2 interface started crashing my server.
Upon deleting that chassis with an editor and booting up again, all other Logistics Pipes connected to AE2 interfaces appear to have disconnected.
[crash-2020-06-29_21.57.22-server.txt](https://github.com/RS485/LogisticsPipes/files/4847911/crash-2020-06-29_21.57.22-server.txt)

**Comment by bziemons** [comment]
Thanks for reporting it, fixed in build 47
