### ISSUE TITLE
Is this module of version 0.10.3 not compatible with IC2

### ISSUE THREAD

**Issue by wstc1997** [RS485/LogisticsPipes#1498]
Is this module of version 0.10.3 not compatible with IC2, because I installed this module and IC2, but the EU Power Supplier Upgrade in the module cannot be used, and there is no module for IC2.

请问0.10.3版本的此模组是否无法和IC2兼容，因为我安装了这个模组和IC2，但是模组中的EU Power Supplier Upgrade无法使用，而且没有和供IC2使用的模块。

**Comment by bziemons** [comment]
Power transportation is not implemented in any version for MC 1.12.2, but it is on the list of requested features: https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
