### ISSUE TITLE
extractor stopped working

### ISSUE THREAD

**Issue by Turmfalke2** [RS485/LogisticsPipes#150]
My LP system is connected to a small AE system for storage, for that I have an chassis mk1 with a item sink (Default) connected to an ME interface. This worked fine for a long time, except just now I noticed that my extractor won't pull items unless it has another destination. In this case a chest with basic pipe.

I currently also have a quarry running that pumps it's items through LP system in the AE system.

LP version 622
AE version 11.e

E:
I just removed the basic pipe and the chest again, now it's extracting the items again and routes them to the interface. This very fishy.

**Comment by AartBluestoke** [comment]
sounds like a routing table didn't get updated correctly.

**Comment by AartBluestoke** [comment]
routing table update have probably been fixed,
Could you please update to the latest dev and re-open this if you see any further issues?
http://ci.thezorro266.com/job/LogisticsPipes-Dev/
