### ISSUE TITLE
Download channel

### ISSUE THREAD

**Issue by wstc1997** [RS485/LogisticsPipes#1503]
Can I provide a download channel directly on the MC China website（https://www.mcmod.cn/）? This will make it easier for MC players in China to download this mod. Because in some areas of China, players can’t log in to Curse Forge, and they don’t know how to download from Git Hub.The details are shown in the picture.![UeFwAf.png](https://s1.ax1x.com/2020/07/09/UeFwAf.png)![UeFaHP.png](https://s1.ax1x.com/2020/07/09/UeFaHP.png)

**Comment by bziemons** [comment]
I assumed that exactly was the question in #1501 ? Please go ahead
