### ISSUE TITLE
Crafting Logistics Pipe MK2, Crafting Logistics Pipe MK3 and Provider Logistics Pipe MK2 in the 1.12.2

### ISSUE THREAD

**Issue by wstc1997** [RS485/LogisticsPipes#1505]
Hello author, I have not found Crafting Logistics Pipe MK2, Crafting Logistics Pipe MK3 and Provider Logistics Pipe MK2 in the 1.12.2 version. Are these items not yet added or have they been removed?

**Comment by bziemons** [comment]
They have been removed in favor of upgrades.
