### ISSUE TITLE
Satellite Pipes show several ghost names

### ISSUE THREAD

**Issue by TMPJoker** [RS485/LogisticsPipes#1510]
I made a satellite pipe with the name "Glass Tubes", and another satellite pipe named "assembler", however after breaking the pipes, the satellite select menu seems to have the names still 8 times over, and those pipes no longer exist,

**Comment by bziemons** [comment]
Fixed in bb7538c68d3af913ea424ba6fe211bf50c9eb51c, 9dcdc40351bb10afdcf5b43927d78dfa118f3fbf
