### ISSUE TITLE
Show output item's name after "crafting module"

### ISSUE THREAD

**Issue by ndsf** [RS485/LogisticsPipes#1512]
Which makes it easier to find a specific crafting module in a logistics chassis.
![image](https://user-images.githubusercontent.com/32725248/89187110-605ee600-d5cf-11ea-9f77-26842f870b09.png)
![image](https://user-images.githubusercontent.com/32725248/89187326-b764bb00-d5cf-11ea-8025-324a702a1e04.png)

**Comment by bziemons** [comment]
Thanks for suggesting adding this information, but there is already #869 and I like having it in the tooltip for the simple reason of space left in the chassis GUI.
