### ISSUE TITLE
Logistics pipes .jar corruption

### ISSUE THREAD

**Issue by FakeLook** [RS485/LogisticsPipes#1516]
As the title said, after our server updated to 2.0.5 my base is practically unusable, since every time i look at a logistic pipe my game crashes.
[crash-2020-08-08_05.48.27-client.txt](https://github.com/RS485/LogisticsPipes/files/5044594/crash-2020-08-08_05.48.27-client.txt)

When i created new creative singleplayer world to try and find the cause, it crashes upon me opening my creative inventory.
[crash-2020-08-08_05.58.06-client.txt](https://github.com/RS485/LogisticsPipes/files/5044605/crash-2020-08-08_05.58.06-client.txt)

closest i got to rendering anything from logistic pipes is a floppy and pipe programmer in the FTB quests and even then it screwed up the whole page.
![image](https://user-images.githubusercontent.com/17618734/89702095-63463780-d93d-11ea-9eb2-1be286e8d0a5.png)

**Comment by FakeLook** [comment]
redownloading the modpack fixed the issue, might be just a bad download

**Comment by FakeLook** [comment]
My logistic pipes .jar randomly corrupts when playing FTB Interactions this happens irrelevant of the pack updating or not. tested the drive Interactions is installed on and it is fine. Also only log. pipes get corrupted. when this happens again i will provide the corrupted .jar.

**Comment by bziemons** [comment]
Open the issue again when you have the jar then.
