### ISSUE TITLE
Clean up of texture files

### ISSUE THREAD

**Issue by justin0a0** [RS485/LogisticsPipes#152]
While trying to determine what to texture there is a whole slew of duplicate files scattered around even the old files for the <1.5 mods sprite sheets are still in the pack and all GUIs are still not in the mods folder.
Would be really helpful if they could be cleaned up to make things much easier on us.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes-Dev/commit/138e1fc7e28331fdd607d577f36341ec284653a9
That should be all or did I miss something.

**Comment by justin0a0** [comment]
maybe the 0.png in the solid blocks thats just a pink image and how are fluids drawn now if not by those images?

**Comment by davboecki** [comment]
They are using the icon rendering code from the liquid itself.
