### ISSUE TITLE
Logistics result pipe doesnt extract items after craft is completed

### ISSUE THREAD

**Issue by Sharkum** [RS485/LogisticsPipes#1522]
Sometimes the request pipe doesnt extract the items out of the machine after a craft. It does behave once I break and replace the entire manager satelite and result pipe network. It is really annoying and it just randomly happens to any result pipe. The pipe shows that it need to complete the craft in its tab but it still doesn't extract it.

**Comment by davboecki** [comment]
You mention the result pipe in your title. But talk about a request pipe in the text. If you are taking about a result pipe, (which I guess you are from the context), that is not part of LP but of the LogisticsBridge Mod. If so please open an issue here: https://github.com/tom5454/LogisticsBridge/issues
