### ISSUE TITLE
Players disconnected when trying to join, LP error

### ISSUE THREAD

**Issue by Enterprise12nx01** [RS485/LogisticsPipes#1525]
Randomly after a server restart, when any players try to join this error appears on the server and they are disconnected.
using logisticspipes-0.10.3.62.jar
Latest.log: https://pastebin.com/0J8agYAg

**Comment by bziemons** [comment]
Is this only happening with 0.10.3.62 and not e.g. 0.10.3.51?

**Comment by Enterprise12nx01** [comment]
i will give it a try tomorrow

**Comment by Enterprise12nx01** [comment]
Update, with version 51 that error does not happen! @bziemons

**Comment by Enterprise12nx01** [comment]
Any news on this problem? again the issue was not present on version 51, upon changing the version players were able to join without the error/kick

**Comment by bziemons** [comment]
This issue will be updated as soon as there is news
