### ISSUE TITLE
Rendering Crash - High Speed Pipes

### ISSUE THREAD

**Issue by Craken761** [RS485/LogisticsPipes#1526]
Playing FTB Interactions, and on logging in to the world, on looking at Logistic Pipes, the game crashes. Crash logs attached, sometimes it will be a CCL rendering issue, and sometimes a tick issue.

This possibly may be linked to other issues, but not sure.

[crash-2020-08-31_15.49.40-server.txt](https://github.com/RS485/LogisticsPipes/files/5151009/crash-2020-08-31_15.49.40-server.txt)
[crash-2020-08-31_15.49.20-client.txt](https://github.com/RS485/LogisticsPipes/files/5151010/crash-2020-08-31_15.49.20-client.txt)
[crash-2020-08-31_15.49.09-server.txt](https://github.com/RS485/LogisticsPipes/files/5151011/crash-2020-08-31_15.49.09-server.txt)
[crash-2020-08-31_15.48.44-server.txt](https://github.com/RS485/LogisticsPipes/files/5151012/crash-2020-08-31_15.48.44-server.txt)
[crash-2020-08-31_15.45.12-server.txt](https://github.com/RS485/LogisticsPipes/files/5151013/crash-2020-08-31_15.45.12-server.txt)
[crash-2020-08-31_15.44.57-client.txt](https://github.com/RS485/LogisticsPipes/files/5151014/crash-2020-08-31_15.44.57-client.txt)
[crash-2020-08-31_15.44.17-client.txt](https://github.com/RS485/LogisticsPipes/files/5151015/crash-2020-08-31_15.44.17-client.txt)
[crash-2020-08-31_15.43.24-server.txt](https://github.com/RS485/LogisticsPipes/files/5151016/crash-2020-08-31_15.43.24-server.txt)
[crash-2020-08-31_15.42.57-server.txt](https://github.com/RS485/LogisticsPipes/files/5151017/crash-2020-08-31_15.42.57-server.txt)
[crash-2020-08-31_15.42.35-client.txt](https://github.com/RS485/LogisticsPipes/files/5151018/crash-2020-08-31_15.42.35-client.txt)
[crash-2020-08-31_15.41.53-client.txt](https://github.com/RS485/LogisticsPipes/files/5151019/crash-2020-08-31_15.41.53-client.txt)
[crash-2020-08-31_15.37.18-client.txt](https://github.com/RS485/LogisticsPipes/files/5151020/crash-2020-08-31_15.37.18-client.txt)
[crash-2020-08-31_15.33.54-client.txt](https://github.com/RS485/LogisticsPipes/files/5151021/crash-2020-08-31_15.33.54-client.txt)
[crash-2020-08-31_15.33.25-client.txt](https://github.com/RS485/LogisticsPipes/files/5151022/crash-2020-08-31_15.33.25-client.txt)
[crash-2020-08-31_15.33.15-server.txt](https://github.com/RS485/LogisticsPipes/files/5151023/crash-2020-08-31_15.33.15-server.txt)
[crash-2020-08-31_15.30.22-client.txt](https://github.com/RS485/LogisticsPipes/files/5151024/crash-2020-08-31_15.30.22-client.txt)
[crash-2020-08-31_15.29.42-client.txt](https://github.com/RS485/LogisticsPipes/files/5151025/crash-2020-08-31_15.29.42-client.txt)

**Comment by bMeasel** [comment]
Same thing was happening to me with rendering the logistic pipe program compiler. After I removed it from the world, I have not gotten a CCL caught an exception error.

**Comment by dominic-jones** [comment]
I've seen this error a few times. It seems random, as if on loading the world it did not load right that time. There's a lot of passive CCL errors, which are annoying but fine. But when you interact with the problem block it hard crashes (for me it was the statistics table). 

Also on FTB Interactions

**Comment by XelfXendr** [comment]
Same problem here.  Once it was the logistic pipe program compiler. Now 4 Logistics Crafting Tables are causing the exception. Always the same ones. Interacting with them doesn't crash the game though.

**Comment by bziemons** [comment]
Important part: https://gist.github.com/bziemons/f2b1db431d37ba2de8041d25cdecf8b4
