### ISSUE TITLE
DEV 646 Unable to Remove Crafting Table

### ISSUE THREAD

**Issue by ReportBot9009** [RS485/LogisticsPipes#153]
I am running DEV 646 Logistics Pipes on Minecraft 1.5.2 and Forge 738 and am unable to remove the Crafting Table.  I am running 148 mods at the moment.  I try to remove it with wrenches, omniwrench, pick axe, axe, hands.  Creative mode won't break it either.  I wish there was more information to give.

Here is a list of mods taken from a recent crash report (this has nothing to do with LP, just a reference for all the mods):

Forge{7.8.1.738} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Snowfall{1.2.0} [Snowfall](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Chemcraft_Core{1.3.1} [Chemcraft Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{0.8.7.3} [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHFramework{1.5.2.5} [CoFH Framework](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ImmibisMicroblocks{55.0.7} [Immibis's Microblocks](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    InfiniBows{1.0.0 build 10} [Infinity Bow Fix](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.5.2.28} [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PowerCrystalsCore{1.1.8B1} [PowerCrystals Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_bspkrsCore{v2.09(1.5.2)} [bspkrsCore]([1.5.2]bspkrsCorev2.09.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TreeCapitator{Forge 1.5.2.r14} [TreeCapitator]([1.5.2]TreeCapitator.Forge.1.5.2.r14.Uni.CoreMod.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Chemcraft_Network{1.0.0} [Chemcraft Network](Chemcraft Core 1.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{1.5.2.5} [CoFHCore](CoFHCore-1.5.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHWorld{1.5.2.5} [CoFHWorld](CoFHCore-1.5.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    denLib{3.0.14} [denLib](denLib-1.5.2-3.0.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CreeperCollateral{2.0.2} [CreeperCollateral](CreeperCollateral-1.5.2-2.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights{1.1.9} [Dynamic Lights](DynamicLights_1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_onFire{1.0.2} [Dynamic Lights on burning](DynamicLights_1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_creepers{1.0.2} [Dynamic Lights on Creepers](DynamicLights_1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_dropItems{1.0.2} [Dynamic Lights on ItemEntities](DynamicLights_1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_mobEquipment{1.0.0} [Dynamic Lights on Mob Equipment](DynamicLights_1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_flameArrows{1.0.0} [Dynamic Lights on Flame enchanted Arrows](DynamicLights_1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_otherPlayers{1.0.2} [Dynamic Lights Other Player Light](DynamicLights_1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_thePlayer{1.0.4} [Dynamic Lights Player Light](DynamicLights_1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GuiAPI{0.15.6} [GuiAPI](GuiAPI-0.15.6-1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ImmibisMicroblocksInstallCheck{55.0.7} [Immibis's Microblocks (Checks for incorrect installation, ignore this)](immibis-microblocks-55.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DamageIndicatorsMod{2.7.0.1} [Damage Indicators](1.5.2 DamageIndicators v2.7.0.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bau5_ProjectBench{1.7.4} [Project Bench]([1.5.2]ProjectBench-v1.7.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    workingSponges{1.3.3} [Working Sponges]([1.5.2]WorkingSponges-1.3.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{3.7.2-2-g3a9acc3} [BuildCraft](buildcraft-universal-1.5.2-3.7.2.2.271.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{3.7.2-2-g3a9acc3} [BC Factory](buildcraft-universal-1.5.2-3.7.2.2.271.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{3.7.2-2-g3a9acc3} [BC Transport](buildcraft-universal-1.5.2-3.7.2.2.271.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{3.7.2-2-g3a9acc3} [BC Silicon](buildcraft-universal-1.5.2-3.7.2.2.271.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    APUnofficial{2.3.1} [Additional Pipes](AdditionalPipes2.3.1-BC3.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion{2.4.6.0} [Thermal Expansion](ThermalExpansion-2.4.6.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2{1.116.364-lf} [IndustrialCraft 2](industrialcraft-2_1.116.364-lf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{3.7.2-2-g3a9acc3} [BC Builders](buildcraft-universal-1.5.2-3.7.2.2.271.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{3.7.2-2-g3a9acc3} [BC Energy](buildcraft-universal-1.5.2-3.7.2.2.271.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded{1.5.1R2.7.0B8} [MineFactory Reloaded](MineFactoryReloaded-2.7.0B8-1106.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppliedEnergistics{rv12.b} [Applied Energistics](appeng-rv12-b-mc15x.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AtomicScience{0.6.1} [Atomic Science](Atomic_Science_v0.6.1.80.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Backpack{1.9.11} [Backpack](backpack-1.9.11-1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BetterDungeons{1.8} [Better dungeons](BetterDungeons.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.3.1} [BiblioCraft](BiblioCraft[v1.3.1].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Natura{2.1.4} [Natura](Natura_1.5.1_2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiomesOPlenty{@VERSION@} [Biomes O' Plenty](Biomes-O-Plenty-0.5.9.2-1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtrabiomesXL{3.13.4} [ExtrabiomesXL](ExtrabiomesXL-universal-1.5.2-3.13.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatForestryPre{1.5.1R2.7.0B8} [MFR Compat: Forestry (2)](MineFactoryReloaded-2.7.0B8-1106.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forestry{2.2.8.4} [Forestry for Minecraft](forestry-A-2.2.8.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BinnieCore{1.7.0b} [Binnie Core](binnie-mods-1.7.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraBees{1.7.0b} [Extra Bees](binnie-mods-1.7.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraTrees{1.7.0b} [Extra Trees](binnie-mods-1.7.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Additional-Buildcraft-Objects{1.0.6.159} [Additional Buildcraft Objects](buildcraft-Z-additional-buildcraft-objects-1.0.6.159.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Condensed Block{3.0.0} [Condensed Block](CBM.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ChargePads{2.7.0} [Charge Pads](chargepads-1.5.2-universal-2.7.0.86.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ChestTransporter{1.1.6} [Chest Transporter](chestTransporter_1.1.6_Universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CompactWindmills{1.0.1.3} [CompactWindmills](CompactWindmills+v.1.0.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    craftguide{1.5.2} [CraftGuide](CraftGuide-1.6.7.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CustomRecipes{4.2.0} [Custom Recipes](Custom Recipes SMP 4.3.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CustomSpawner{2.2.3.d1} [DrZhark's CustomSpawner](CustomMobSpawner 2.2.3 DEV-R1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DenPipes{2.0.7} [DenPipes](DenPipes-1.5.2-2.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MoCreatures{5.2.4.d1} [DrZhark's Mo'Creatures Mod](DrZharks MoCreatures Mod v5.2.4 DEV-R1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    dynamictanks{0.1.28} [Dynamic Liquid Tanks](DynamicLiquidTanks 0.1.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ElectricExpansion{2.3.0.51} [Electric Expansion](ElectricExpansion_v2.3.0.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    eplus{1.15.5} [Enchanting Plus](EnchantingPlus-1.15.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderStorage{1.4.2.16} [EnderStorage](EnderStorage 1.4.2.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnhancedCore{1.1} [EnhancedCore](EnhancedCore_1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EP2{1.0.6 (Build: 24)} [EnhancedPortals 2](EnhancedPortals-2_1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    extracells{1.2.2b} [ExtraCells](ExtraCells-universal-1.2.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraUtilities{0.2.4g} [Extra Utilities](extrautils - 0.2.4g.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    factorization{0.7.37} [Factorization](Factorization-0.7.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    factorization.misc{0.7.37} [Factorization Miscellaneous Nonsense](Factorization-0.7.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    factorization.dimensionalSlice{0.7.37} [Factorization Dimensional Slices](Factorization-0.7.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GregsLighting{1.8.4} [Greg's Lighting](GregsLighting-1.8.4-mc1.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    iChunUtil{1.0.1} [iChunUtil](iChunUtil1.0.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ImmibisCore{55.1.6} [Immibis Core](immibis-core-55.1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AdvancedMachines{55.0.3} [Advanced Machines](Immibis - Advanced-Machines-55.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DimensionalAnchors{55.0.3} [Dimensional Anchors](immibis - dimensional-anchor-55.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.54b} [Inventory Tweaks](InventoryTweaks-1.54b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{5.2.8.447} [Iron Chest](ironchest-universal-1.5.2-5.2.8.447.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LiquidXP{55.1.6} [Liquid XP](liquid-xp-55.1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{3.0.5h1} [Thaumcraft](Thaumcraft3.0.5h.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LogisticsPipes|Main{0.7.3.dev.646} [Logistics Pipes](LogisticsPipes-MC1.5.2-0.7.3.dev.646.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Magical-Crops{2.1.2a} [Magical Crops](magical_crops_1.5.1.2.1.2a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.5.2_1.4.2.3} [Tinkers' Construct](TConstruct_1.5.2_1.4.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MagicBees{2.1.1} [Magic Bees](magicbees-2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MapWriter{2.0} [MapWriter](mapwriter-2.0.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mekanism{5.5.6} [Mekanism](Mekanism-v5.5.6.124.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MekanismGenerators{5.5.6} [MekanismGenerators](MekanismGenerators-v5.5.6.124.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MekanismTools{5.5.6} [MekanismTools](MekanismTools-v5.5.6.124.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MFFS{3.1.0} [Modular Force Field System](MFFS_v3.1.0.175.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MFR Compat Forestry Trees{1.0} [MFR Compat Forestry Trees](MFR-ForestryTrees-1.5.2-1.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MFR Compat Extra Trees{1.0} [MFR Compat Extra Trees](MFR-ForestryTrees-1.5.2-1.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatAppliedEnergistics{1.5.1R2.7.0B8} [MFR Compat: Applied Energistics](MineFactoryReloaded-2.7.0B8-1106.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatAtum{1.5.1R2.7.0B8} [MFR Compat: Atum](MineFactoryReloaded-2.7.0B8-1106.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatBackTools{1.5.1R2.7.0B8} [MFR Compat: BackTools](MineFactoryReloaded-2.7.0B8-1106.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatChococraft{1.5.1R2.7.0B8} [MFR Compat: Chococraft](MineFactoryReloaded-2.7.0B8-1106.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatExtraBiomes{1.5.1R2.7.0B8} [MFR Compat: ExtraBiomes](MineFactoryReloaded-2.7.0B8-1106.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatForestry{1.5.1R2.7.0B8} [MFR Compat: Forestry](MineFactoryReloaded-2.7.0B8-1106.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatIC2{1.5.1R2.7.0B8} [MFR Compat: IC2](MineFactoryReloaded-2.7.0B8-1106.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatMagicalCrops{1.5.1R2.7.0B8} [MFR Compat: Magical Crops](MineFactoryReloaded-2.7.0B8-1106.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mystcraft{0.10.5.00} [Mystcraft](mystcraft-uni-1.5.2-0.10.5.00.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatMystcraft{1.5.1R2.7.0B8} [MFR Compat: Mystcraft](MineFactoryReloaded-2.7.0B8-1106.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatPams{1.5.1R2.7.0B8} [MFR Compat: Pam's Mods](MineFactoryReloaded-2.7.0B8-1106.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Railcraft{7.2.3.0} [Railcraft](Railcraft_1.5.2-7.2.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatRailcraft{1.5.1R2.7.0B8} [MFR Compat: Railcraft](MineFactoryReloaded-2.7.0B8-1106.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatRP2{1.5.1R2.7.0B8} [MFR Compat: RP2](MineFactoryReloaded-2.7.0B8-1106.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatSufficientBiomes{1.5.1R2.7.0B8} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-2.7.0B8-1106.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MFReloaded|CompatThaumcraft{1.5.1R2.7.0B8} [MFR Compat: Thaumcraft](MineFactoryReloaded-2.7.0B8-1106.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatThermalExpansion{1.5.1R2.7.0B8} [MFR Compat: Thermal Expansion](MineFactoryReloaded-2.7.0B8-1106.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TwilightForest{1.18.2} [The Twilight Forest](twilightforest-1.18.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatTwilightForest{1.5.1R2.7.0B8} [MFR Compat: TwilightForest](MineFactoryReloaded-2.7.0B8-1106.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatVanilla{1.5.1R2.7.0B8} [MFR Compat: Vanilla](MineFactoryReloaded-2.7.0B8-1106.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatXyCraft{1.5.1R2.7.0B8} [MFR Compat: XyCraft](MineFactoryReloaded-2.7.0B8-1106.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AdvancedSolarPanel{3.3.7} [Advanced Solar Panels](mod_AdvancedSolarPanels_3_3_7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_playerEnchantments{1.3.3Unoffial} [mod_playerEnchantments](Mod_MorePlayerEnchantmentsv1.5.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PML2{1.5.2.1} [Portable Mining Laser](mod_PML2.152.1.256.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GraviSuite{1.9.3} [Gravitation Suite](mod_zGraviSuite_1_9_3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mmmPowersuits{0.7.1-578} [MachineMuse's Modular Powersuits](ModularPowersuits-0.7.1-578.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MoreFurnaces{1.3.4c} [More Furnaces](moreFurnaces-1.3.4c-universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PowersuitAddons{0.3.0-175} [Andrew2448's Modular Powersuits Addon](MPSA-0.3.0-175_MPS-561+.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MultiPageChest{1.2.3} [Multi Page Chest](multiPageChest_1.2.3_Universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Natura|CompatMineFactoryReloaded{0.1} [Natura compat: MFR](Natura_1.5.1_2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIPlugins{1.0.9.3} [NEI Plugins](NEIPlugins-1.0.9.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NetherOres{1.5.1R2.1.5} [Nether Ores](NetherOres-2.1.5-75.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ObsidiPlates{1.5.0} [Obsidian Pressure Plates](obsidiplates-1.5.2-universal-1.5.0.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenBlocks{1.0.0} [OpenBlocks](OpenBlocks-1.0.0-beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PortalGun{1.5.2} [PortalGun](PortalGun1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PowerConverters{1.5.1R2.3.1} [Power Converters](PowerConverters-2.3.1-59.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    randomthings{1.5} [Random Things](Random Things [1.5].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedLogic{55.4.1} [RedLogic](redlogic-55.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    JAKJ_RedstoneInMotion{1.2.0.1} [Redstone In Motion](RedstoneInMotion_1.2.0.1_mc1.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SAP_Man{1.4.2} [SanAndreasPs Managers](SAP_ManPack_v142.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TStormFix{1.0} [Thunderstorm Fix](SAP_ManPack_v142.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SoulShards{1.0.16} [Soul Shards](SoulShards-1.0.36-universal-srg.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SpecialMobs{2.5.2} [Special Mobs](SpecialMobs 2.5.2 for MC 1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    StevesCarts{2.0.0.a122} [Steve's Carts](StevesCarts2.0.0.a122.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct|CompatMineFactoryReloaded{0.1} [TConstruct Compat: MFR](TConstruct_1.5.2_1.4.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    KBITC3EssenceAddon{2.3.2} [ThaumCraft3 Essence Addons](Thaumcraft KBI TC3 Essentia Everything Addon for 1.5.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicTinkerer{1.0.8} [Thaumic Tinkerer](Thaumic Tinkerer [1.0.8].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    KBItinkersmelt{1.2.1} [KBI Tinker's Construct Smeltery Addon](Tinkers Construct Recovery Addon 1.2.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Translocator{1.1.0.3} [Translocator](Translocator 1.1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TurretMod3{3.0.1} [Turret Mod v3](TurretMod_v3.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WirelessRedstoneCore{1.7} [Wireless Redstone](WirelessRedstone-Universal-v1.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_ZanMinimap{0.9.4} [mod_ZanMinimap](ZansMinimap1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OmniTools{3.1.6.0} [OmniTools](OmniTools-3.1.6.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LWJGL: 2.4.2
    OpenGL: GeForce GTX 460/PCIe/SSE2 GL version 4.3.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Texture Pack: Minecraft Enhanced v1.5.2 128x.zip

**Comment by bziemons** [comment]
Did you mean "Request Table"? And if so, that has just been fixed in https://github.com/RS485/LogisticsPipes-Dev/commit/fd8e36b4ea1f0196f402936169ea7daf6cc2271f and a new build will be available in minutes.

**Comment by ReportBot9009** [comment]
I am sorry, I did mean Request Table.  Great news!  Can't wait to check it out!

Thank you very much.

**Comment by bziemons** [comment]
Not sure if that fix works yet. There might be the need of another fix, but we are working on it.
