### ISSUE TITLE
Satellite Pipe Selection GUI Spam

### ISSUE THREAD

**Issue by timmyow7** [RS485/LogisticsPipes#1530]
Issue seemed to have started around since breaking and replacing some satellite pipes and result pipes from Logistics Bridge to clear a pending craft but could be wrong, not sure where issue lies but the GUI is more generic so posted here. From FTB Interactions v2.0.9.

Image shows the issue, it's creating duplicate entries for the same device, and as time goes on when I check the gui it has more duplicates. The entries now take some time to load because of the duplicates.

![lp](https://user-images.githubusercontent.com/70984158/92535888-35039280-f230-11ea-88b1-57d1c98977c0.png)

**Comment by bziemons** [comment]
Fixed in bb7538c68d3af913ea424ba6fe211bf50c9eb51c
