### ISSUE TITLE
Inventory System Connector Channel Issue

### ISSUE THREAD

**Issue by Strosam** [RS485/LogisticsPipes#1532]
I'm currently using version 0.10.3.62 of Logistics Pipes as part of the Omnifactory pack. I tried setting up the inventory system connector using ender storage and initially had it working. Recently though, I have been unable to open up the channel select gui. When I click "Change" nothing happens, even after waiting for a minute or two. 

What's strange is that this only happens in that particular world, in a creative world it works just fine.

**Comment by Strosam** [comment]
[Log.txt](https://github.com/RS485/LogisticsPipes/files/6289364/Log.txt)

I realize this would've been really helpful when I first made that comment. I tried again using version 0.10.3.40 and still ran into the same problems. The error shows up towards the end of the log just before it starts saving the world.

**Comment by bziemons** [comment]
Thanks! Looking at the error, it seems to be a duplicate of #1426. That was fixed in build 77 of version 0.10.3. Can you check with this? https://ci.rs485.network/job/LogisticsPipes-0.10-mc1122-fg3/77/ or any newer build.

**Comment by Strosam** [comment]
That fixed it, thanks!
