### ISSUE TITLE
Logistic pipes old renderer on 1.12.2

### ISSUE THREAD

**Issue by Mega2223** [RS485/LogisticsPipes#1549]
I've searched if someone has already asked this, the answer I found is that you can switch it off using the Logistics Pipe Controller's interface, but when I open mine I can only set the max distance for the New Renderer, I tried changing it to 0 and It does nothing, am I doing something wrong?
![image](https://user-images.githubusercontent.com/59067466/97465855-3fcdd000-1921-11eb-9bce-eaf25c81036e.png)

**Comment by bziemons** [comment]
Hi! This was already requested in #1211 but there was no development in this direction. We're still happy to take PRs, but afaik there is no plan to make this happen.
