### ISSUE TITLE
i dont know what you did last updates - Supplier Pipe + Alveary

### ISSUE THREAD

**Issue by Nightreaver** [RS485/LogisticsPipes#155]
But i tried to use my alveary which should be filled with frames an uran in the correct blocks

but know... its not working anymore

it "destroed" around 250 uran ore and over 100 frames...

i've changed nothing except LP update...

when you take look at the supplier pipe.. it requests correctly, the frame arrives, enter the alveary but... when you have a look at it, its empty!
same with uran...

so, did you change anything with this?  i dont like my items to end up in the void -.-'

LP dev 646

**Comment by davboecki** [comment]
From which version did you update ?

**Comment by ArtForz** [comment]
Nothing immediately comes to mind... what extrabees version?

**Comment by Nightreaver** [comment]
From something between 632 and 637.

Extrabees 1.7.1 (binniemods 1.7.1)

**Comment by ArtForz** [comment]
Known bug in extrabees: https://bitbucket.org/binnie567/extra-trees/issue/33/automating-frame-housing-issue-171

**Comment by AartBluestoke** [comment]
marked resolved in extra bees 172
