### ISSUE TITLE
[Feature Request] Increase supplier logistic pipe/module limit

### ISSUE THREAD

**Issue by StevenDoesStuffs** [RS485/LogisticsPipes#1555]
Currently, the supplier module can supplier a max of 127 of a single type of item to its connected inventory. It would be great if this limit were increased. 

The situation I'm currently in is that I've automated the production of some resource and would like to keep a large amount (> 127) of it stocked in the system, so I have a supplier pipe attached to some large storage block (e.g modular storage).
This obviously wouldn't work with infinite mode, since instead of stopping after a certain point, it'd just keep going until it filled the whole thing.

**Comment by bziemons** [comment]
Hi! Thanks for suggesting this, but the feature request is already listed with "New supplier pipe GUI" on https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
