### ISSUE TITLE
Stack can not be invalid

### ISSUE THREAD

**Issue by NickCloudAT** [RS485/LogisticsPipes#1575]
I get the following error when ordering certain things that should be crafted with logistic pipes: https://pastebin.com/PPEYjTkd

I did not change anything on the server, I just restarted it and then it occured. I tried the latest STABLE logistic pipes version for 1.12.2 and also the latest beta build.

**Comment by bziemons** [comment]
Please look out for `Cannot make stack from item … -- item creates and empty stack!` in your log, since some other mod is doing weird things here :) Thanks

**Comment by NickCloudAT** [comment]
Hm okay,

I actually just downloaded the latest beta build now (0.10.3.83) and now my Server refuses to start at all and crashes.. https://pastebin.com/7kJyFRgk

**Comment by Bernasss12** [comment]
So technically I am the one who broke it

**Comment by bziemons** [comment]
> I actually just downloaded the latest beta build now (0.10.3.83) and now my Server refuses to start at all and crashes.. https://pastebin.com/7kJyFRgk

Fixed that crash in in ca770b93341b705ac5d9360c72eee83e2f4e0146
