### ISSUE TITLE
Fluid Supplier pipe accesses opposite side of Gregtech CE machine

### ISSUE THREAD

**Issue by KaktuszSok** [RS485/LogisticsPipes#1576]
The logistics fluid supplier pipe does not request fluids when attached to a GTCE input hatch as such:
![image](https://user-images.githubusercontent.com/12380380/111886089-f5321a80-89cb-11eb-8a6e-9f69cf915f42.png)
But it does work when the input hatch is rotated 180 degrees (i.e. the "input" side is on the opposite side to where the pipe is connected).

This may also be the case with other gregtech machines (i.e. single-block machines).

Forge v2854
LP 0.10.3.81
GTCE 1.11.1.632
Gregicality 0.21.3

**Comment by bziemons** [comment]
I have to check again with the mod. As far as I can tell right now I recently inverted the sides while actually fixing our behavior of asking for the wrong side.

**Comment by SonOfTheStars** [comment]
I can confirm this behavior. When adding a fluid satellite to the front of the machine, the pipe is only able to insert the fluid when you enable "Enable Input from Output Side" on the machine. Output side being the opposite of the front face by default.

**Comment by SonOfTheStars** [comment]
PS: If I change the output side with a wrench to point at a different face, the pipe starts to work.

**Comment by bziemons** [comment]
Fixed in 4d02dccb9f2b8111ec5489c7a59767571a9715f2

(tested with a Thermal Expansion machine)
