### ISSUE TITLE
Pipes not transmitting power

### ISSUE THREAD

**Issue by mon-ales** [RS485/LogisticsPipes#1578]
Hello, 
I was about to power up my industrial craft machines using logistics pipes, but before beginning i noticed that there wasn't a crafting recipe for the power upgrades for the pipes. So I've created a new creative world, testing out those upgrades. Sadly those upgrades don't work at all. Is there a way to fix it, or it just needs to be implemented?

Thanks!

**Comment by bziemons** [comment]
Hi this is on the [list of feature requests](https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests) as the point "Add back power transportation". There is no ETA on this and for feature requests we prefer that wiki page as the number of issues is too high.
