### ISSUE TITLE
Satellites arent removed from list on Dedicated Server

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#1585]
When destroying a Satellite Pipe (Fluid or Item) on our dedicated FTP Interactions server, the satellite name is not unregistered and stays behind until the server is restarted. Effectively not allowing  us to use the same name again.

Mode: Dedicated Server
Forge Version: 14.23.5.2847
LP Version: 0.10.3.94 Alpha

There are no apparent errors in the Log.

**Comment by Bernasss12** [comment]
Just to be sure this was without LogisticsBridge installed or in the network?

**Comment by Bernasss12** [comment]
Because once again while trying to reproduce it on a dedicated server I can't seem to be able to "break" the satellite pipe list.

**Comment by bziemons** [comment]
Related to duplicates in #1586
