### ISSUE TITLE
Intermittent crafting 

### ISSUE THREAD

**Issue by Rithenar** [RS485/LogisticsPipes#1587]
First time playing with mod so I may be doing something wrong - if so, thanks in advance for the guidance.

I have a Logistic Crafting Table with a Mk5 Chassis where I have been putting crafting modules for different recipes. If I request an item that has several sub crafting recipes, I sometimes get the output and sometimes not. I see all the items needed for the recipe going into the crafting table, but nothing gets processed.  You can see here all the items are in the table 
![image](https://user-images.githubusercontent.com/9939332/115126458-c68c6d00-9f94-11eb-8155-23938877461e.png)

And the recipes are there and valid
![image](https://user-images.githubusercontent.com/9939332/115126474-d60bb600-9f94-11eb-9daa-e7fef7f38e66.png)
![image](https://user-images.githubusercontent.com/9939332/115126479-de63f100-9f94-11eb-9e07-62204e29cf4e.png)
![image](https://user-images.githubusercontent.com/9939332/115126486-e91e8600-9f94-11eb-9af6-c2e99370e68a.png)
![image](https://user-images.githubusercontent.com/9939332/115126490-f2a7ee00-9f94-11eb-81ed-d2b87443ea7c.png)

But they just stay there and nothing happens.

All I can think is that the crafting table cannot handle multiple recipes stored in the chassis and I need to use separate tables?

I see purple sparkles in the chassis pipe and not sure if that means something
![image](https://user-images.githubusercontent.com/9939332/115126519-37cc2000-9f95-11eb-9b02-fbbfac54b290.png)

**Comment by Bernasss12** [comment]
You have to set the recipe in the Crafting Table itself, and then attach a crafting pipe/module to it. When you attach the pipe/module you can set it up just by clicking the `Import` button.

> All I can think is that the crafting table cannot handle multiple recipes stored in the chassis and I need to use separate tables?

This is true, you can only have one recipe per table.

**Comment by Rithenar** [comment]
That is unfortunate. I will have to have a whole room full of craters. Oh well. Thanks Bernasss12
