### ISSUE TITLE
Unable to configure Liquid Provider Pipe

### ISSUE THREAD

**Issue by EL2020** [RS485/LogisticsPipes#159]
I am having a bug with your mod. I can't give a crash report because it is not that type of bug. After a while in my Minecraft world, I can't click on a Liquid Provider Pipe.  It just won't let me. I don't get errors or anything. I just can't. I have used a Buildcraft and Omnitools wrench. I was using a MultiMC Instance if that help.

**Comment by davboecki** [comment]
A liquid provider pipe doesn't have a GUI.

**Comment by AartBluestoke** [comment]
perhaps a chat message "no config options for pipe" with pipes without a gui?

**Comment by jeffreykog** [comment]
Or just an empty gui with only your inventory

**Comment by AartBluestoke** [comment]
the important thing is to inform the user that no action is normal.
i'm sure that if a blank gui is shown we would see a bug report here
'Gui X is blank'

On 8/12/13, Jeffrey Kog notifications@github.com wrote:

> Or just an empty gui with only your inventory
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/RS485/LogisticsPipes-Dev/issues/159#issuecomment-22465396

## 

“Getting information off the Internet is like taking a drink from a fire
hydrant.”
_– Mitchell Kapor_
