### ISSUE TITLE
Free LP&AE energy!

### ISSUE THREAD

**Issue by NoX-programer** [RS485/LogisticsPipes#160]
Idea of bug https://github.com/RS485/LogisticsPipes-Dev/issues/158 made me to investigate further and this is what we got.
We need to build incomplete 5*5 rectangle of basic logistics pipes and attach ME interfaces and ME controllers between them as shown here: 
![2013-08-12_19 19 42](https://f.cloud.github.com/assets/4730256/948472/eee48204-0368-11e3-9f8a-7718a9d28570.png)
 also attach logistics power junction for example to left side. Give then some power to it and stop. It is not necessary to fill it completely.
We can attach any logistics pipes to the right bottom corner basic pipe and also any AE devices to (for example) bottom AE segment and what we have? Unlimited power! Because power isn't drains from logistics power junction. Even ME controllers shows online status and zero energy consumption: 
![2013-08-12_19 20 04](https://f.cloud.github.com/assets/4730256/948501/7eb0f4c6-0369-11e3-903b-4f95610e0c2f.png)
Okay, enough fun, here is solution I suggest: do not accept power from ME interfaces, never! It's only logistics power junction function. But it just my opinion.
By the way, this bug on AE tracker: http://ae-mod.info/Tracker/0367/

**Comment by AlgorithmX2** [comment]
@AartBluestoke

Tested this, it appears I can resolve this by call canProvidePower as well as usePower, this appears to be more in line with how LP works internally.

Since it seemed to work fine without this when testing it seemed like an unnecessary step.

Would you like me to implement this change? or would you like to look into why calling usePower can return phantom power?

Let me know, I'm cool either way.

**Comment by davboecki** [comment]
I tested this as well, from what i see the problem is, that for some reason canUseEnergy returns true on LP side while the useEnergy command returns false. I don't know if it is an LP or AE problem, , or both but a quickfiy from LP side would be to check the return of useEnergy as well.

**Comment by davboecki** [comment]
That should fix it for now, but it would still be interesting to know how canUseEnergy can return something else then useEnergy.

**Comment by AlgorithmX2** [comment]
Not sure, i'll implement my change as well. Seems like a good idea to use the same usage pattern on my side as well.
