### ISSUE TITLE
Make Crafting Managers work without a Satellite / Result pipe

### ISSUE THREAD

**Issue by dimitriye98** [RS485/LogisticsPipes#1607]
This seems simple and obvious enough that it may actually be a conscious balancing decision rather than an oversight, (in which case feel free to close this issue) but it'd be nice if a crafting manager could be used without satellite / result pipes, i.e. as simply a really really big chassis pipe which is restricted to crafting modules. There are plenty of situations where the large list of recipes provided by a crafting manager is necessary while the satellite and / or result functionality isn't needed.

**Comment by Bernasss12** [comment]
The crafting manager is actually a part o the [Logistics Bridge](https://github.com/tom5454/LogisticsBridge) mod so there's nothing we can do about that

**Comment by dimitriye98** [comment]
Oof, sorry about that, JEI labeled it as from Logistics Pipes
