### ISSUE TITLE
Remote Request Table

### ISSUE THREAD

**Issue by 123FLO321** [RS485/LogisticsPipes#161]
I am thinking of an item similar to the remote order but with the request table gui.
Would it be overpowered or should it just be expensive and use a lot of energy?

**Comment by bziemons** [comment]
To give my part, I'll just quote what I already say:

> theZorro266: To be honest, that item would do a bit too much
> theZorro266: With a remote orderer you can order items to a remote orderer pipe
> theZorro266: But with that item you could take the items out of the item, which would be transportation of items then
> theZorro266: Also you can craft with it

**Comment by 123FLO321** [comment]
Technically it's just a tesseract and a request table as an item so it's not that op in my opinion.

**Comment by AartBluestoke** [comment]
if you wish this functionality, just use some type of portable crafting table - pocket crafting table, MPS power fist, EE2 minum stone (and i'm sure there are others)

Closing as a bit too OP. If we were to implement this, it would eat several inventory slots, and cost _a little_ bit of energy.
