### ISSUE TITLE
Crafting Module: Incorrectly saving/loading state when edited in player inventory and chassis pipe

### ISSUE THREAD

**Issue by 123FLO321** [RS485/LogisticsPipes#1612]
After a server restart sometimes the ingredients specified in the "satellite"-part get duplicated into the first slot.

before restart:
![image](https://user-images.githubusercontent.com/1949038/119977491-caaaa200-bfb8-11eb-89e8-4d6685fc6ecc.png)

after restart:
![image](https://user-images.githubusercontent.com/1949038/119979394-2e35cf00-bfbb-11eb-9279-1dc59ac23717.png)

**Comment by 123FLO321** [comment]
Way to reproduce: 

- Open Crafting Module in inventory and set a crafting there (sets NBD of module)
![image](https://user-images.githubusercontent.com/1949038/121701793-8f889280-cad1-11eb-9189-1600e94d9e91.png)

- Place In Chassis Pipe and edit recipe (does not update NBD of module)
![image](https://user-images.githubusercontent.com/1949038/121701906-adee8e00-cad1-11eb-8b42-e55c4e18cb1e.png)

- Reload world
- Now both recipes are now loaded (combined from NBD of module and of pipe)
![image](https://user-images.githubusercontent.com/1949038/121702478-366d2e80-cad2-11eb-8d02-227ab1508139.png)

**Comment by Bernasss12** [comment]
I can add that this issue is not exclusive to the Crafting Module
