### ISSUE TITLE
BUG of OreDict ItemSink module

### ISSUE THREAD

**Issue by wstc1997** [RS485/LogisticsPipes#1619]
Hello author, the OreDict ItemSink module in the 0.10.3.114 version of this module has some problems.
After I set an Ore Dict in it, I opened the GUI again and the OreDict disappeared
I put a video below.

**Comment by wstc1997** [comment]
[https://drive.google.com/file/d/1sLSaTVKyyI3Vn0LVEQgY9dd800WODK-3/view?usp=sharing](url)

**Comment by bziemons** [comment]
Duplicate of #1609
