### ISSUE TITLE
Items going everywhere 

### ISSUE THREAD

**Issue by Highcreamo** [RS485/LogisticsPipes#1628]
Im playing on 1.12.2 version and no mather what modules/pipes I use, items just go stranding through the whole network and after a really long time they find the way. I don't have buildcraft installed (if it has any affect)

**Comment by Timeslice42** [comment]
What does "go stranding" mean? And which version of Logistics Pipes are you using (always mention that in an issue)?

**Comment by KorewaLidesu** [comment]
First, make sure there is Default Route and that Default Route doesnt full
Second, if you try to do mass-crafting, use other mods instead or atleast speed your machine
