### ISSUE TITLE
Crafting Pipe importing Fuzzy Crafting Table recipes incorrectly

### ISSUE THREAD

**Issue by Timeslice42** [RS485/LogisticsPipes#1636]
Ever since the crafting pipe was changed to "compact" the items when importing a recipe, any fuzzy flags on ingredients in the bottom (two?) row(s) get imported into the wrong slots on the crafting pipe.

**Comment by KorewaLidesu** [comment]
> Ever since the crafting pipe was changed to "compact" the items when importing a recipe, any fuzzy flags on ingredients in the bottom (two?) row(s) get imported into the wrong slots on the crafting pipe.

It is import from crafting table slot

**Comment by Timeslice42** [comment]
> > Ever since the crafting pipe was changed to "compact" the items when importing a recipe, any fuzzy flags on ingredients in the bottom (two?) row(s) get imported into the wrong slots on the crafting pipe.
> 
> It is import from crafting table slot

Yes, that is the bug.

**Comment by bziemons** [comment]
It is on the list of feature requests already as "Add support for fuzzy upgrade in the crafting module/pipe", see https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
