### ISSUE TITLE
OreDict Fuzzy Flag not respecting IgnoreDamage/IgnoreNBT Flags on Crafting Pipes/Modules AKA OreDict Fuzzy Flag doesn't stay Fuzzy

### ISSUE THREAD

**Issue by Timeslice42** [RS485/LogisticsPipes#1637]
LP: 0.10.4.5

This is an odd one. Say you have a recipe which takes an <ore:craftingHammer> tool and an iron ingot to make an iron plate, and you have the tool marked as [OreDict] in the Fuzzy Crafting Table and Crafting Pipe/Module, it doesn't *stay* fuzzy when crafting multiple recipes. It takes the first item it finds with that ore dictionary entry and looks for duplicates of that exact item (even if it's also set to ignoreNBT and ignoreDamage).

That is to say, if your system has two hammers with 50/100 durability and two hammers with 100/100 durability, and you try and craft two iron plates, it will work fine. BUT if you try to instead craft four plates at that time it will FAIL, because it's looking for FOUR hammers with 50/100 durability (or 100/100, depending on which one it found first), which don't exist, despite there being four usable hammers in the system.

**Comment by KorewaLidesu** [comment]
Recipe function work as intended
What you should do: Put hammer to logistic crafting table, remove hammer from recipe in crafting pipe

**Comment by Timeslice42** [comment]
> Recipe function work as intended
> What you should do: Put hammer to logistic crafting table, remove hammer from recipe in crafting pipe

That's an entirely separate issue and is unrelated to this bug. And no, it is absolutely not intended for the system to request items that do not exist and then fail when there are items that *do* exist that fulfill a crafting recipe.

P.S. Stop stalking me ;P
