### ISSUE TITLE
Broken priority of itemsinks and other itemsinks

### ISSUE THREAD

**Issue by pitris90** [RS485/LogisticsPipes#1639]
Hi, 
I would like to report that there is possibly some broken priority check or something, because clear itemsink modules aren't prioritized before mod based item sinks or polymorphic itemsinks....

**Comment by Colland** [comment]
Also ran into this problem in FTB infinity evolved. Polymorphic itemsink module and a regular itemsink module with specified items have the same priority, items going to whichever is closest in the network.
