### ISSUE TITLE
Terminus / Quicksort bug

### ISSUE THREAD

**Issue by Flow86** [RS485/LogisticsPipes#164]
In this picture you see the problem:

in both "edge"barrels there are terminus and quicksort modules, the middle chest is full, now both chest keep sending the items to each other all the time.

any way to avoid/fix that behaviour?

![minecraft-logi-terminus](https://f.cloud.github.com/assets/656249/962709/8a73d120-04f4-11e3-8d0f-866b5e1058f7.png)

**Comment by ArtForz** [comment]
Err, that's how quicksorts work. They send to anything that's > default route priority.
So 2 chests/barrels/whatever each with a quicksort and a itemsink or terminus will happily send items to each other all day long.

**Comment by Flow86** [comment]
hmm okay, so there's no way to avoid that - hmm perhaps I should simply use gates/wires to disable the pipes as long the middle chest is full

**Comment by AartBluestoke** [comment]
@Flow86 suppliers now have an infinite supply mode, so provide the edges and infinite supply the middle :)

**Comment by Flow86** [comment]
yes thats a good idea with the inifinite supply mode, but in my current setup I would need an "active supplier module". so I simply disable the quicksort modules via bc-wire/gate currently, thats working okay for me
