### ISSUE TITLE
Satellite Logistic pipes making duplicate entries

### ISSUE THREAD

**Issue by EShezzerA** [RS485/LogisticsPipes#1641]
logisticspipes-0.10.3.114

![image](https://user-images.githubusercontent.com/87674765/128017914-0bc3d9d2-bd55-469f-9261-c3951534f0ad.png)
![image](https://user-images.githubusercontent.com/87674765/128017949-6a2c0513-6749-4a83-82a8-ef9336aca73c.png)

so for e.g. of what I am doing here, I have a Metal press from immersive engineering and I'm using a SatelliteLP to insert metals into the press, and a crafting pipe at the end to collect the Gears. 
However in the crafting pipe Satellite part, I go to click on the Satellite pipe needed but I see multiple duplicates of the same pipe, this also happens on other machines that I have a satelliteLP attached to, e.g. Pulverizers from Thermal Expansion.

**Comment by bziemons** [comment]
This is actually a Logistics Bridge issue and was reported before, see #1586
