### ISSUE TITLE
Liquid loss when piping into a Tinker's Construct smeltery

### ISSUE THREAD

**Issue by Malexion** [RS485/LogisticsPipes#165]
With Logi-Pipes: 0.7.3.ftb.631
Tinkers construct: 1.4.2.1
For easy testing the FTB Unleashed version 1.1.3 has both of these mod versions.

First I pipe liquid metal out of a Tinker's Construct Smeltery, doesn't seem to matter which kind and I pipe it into any form of container or tank, railcraft, portable tank, tinkers construct tank.

This first step is accomplished by using a smeltery drain block and an attached liquiduct and then just force out the liquid and make sure the lever is off once it has finished emptying the smeltery. My setup looks as below:
http://i.imgur.com/CU9xebu.jpg

For this example I have melted 16 copper ore which amounts to 4608mb, as tinkers construct has each ingots worth of liquid metal = 144mb and thus 32 ingots worth is in the smeltery and then pumped out to a tank.

Below the tank I have setup a logi pipe system to pull liquid from the tank on request from a request pipe attached to another smeltery drain which will pour any liquid requested back into the smeltery. 

First I requested 4000 mb to be poured back into the smeltery, and then I requested the last 608 mb and the following is what I saw when I right clicked the smeltery controller: 
http://i.imgur.com/pMQibYZ.jpg

Now this is unusual firstly because when liquid metal enters the smeltery or is melted down, information either about how much mb or on how many ingots + nuggets worth of metal is shown whenever you move your mouse over the metal in the tank in the smeltery controller gui, and in this case nothing more is displayed but the name. Secondly the liquid amount that re-entered the tank is far lower than what was originally there. 

If the liquid is once more piped out of the smeltery after all those steps have been completed it would seem that only 608 mb of molten copper remained. As shown by this picture here of the request pipe after the metal is piped back out of the smeltery into the tank.
http://i.imgur.com/EDDkOYY.jpg

I have tried a similar setup without logi-pipes and it has worked, so somewhere within the logi-pipe request some liquid metal was lost, and i'm not really sure how but it seems to be the interaction with the request pipe and the smeltery drain.

Here is an additional thread with another fellow player who was also testing some of the interaction between the smeltery and logistics pipes:
http://forum.feed-the-beast.com/threads/storing-liquid-metal-in-iron-tanks.28996/

**Comment by ArtForz** [comment]
Should be fixed by c1bb7ebaf12cd8898d1c52f93d3c4318ed914591 in Dev 674

**Comment by Malexion** [comment]
Cool
