### ISSUE TITLE
NO upgrades are working

### ISSUE THREAD

**Issue by hochhause** [RS485/LogisticsPipes#1651]
hey, first up, im using the curseforge version, idk if its outdated.
my issue is, that none of the upgrades(not modules) are working. neither do the modules have upgrade slots if i rightclick the chassis with the pipe controller(neither with the pipe manager but why shoudl they). if there is any known solving please help

edit: the crafting monitoring upgrade seems to work.

**Comment by Bernasss12** [comment]
I can't see to reproduce this issue, I can definitely add upgrades to pipes as well as to modules in chassis pipes.
For you to use upgrades in the chassis pipes you need to use a Module Upgrade item as an upgrade to that pipe and then you'll have the upgrade slots per module.
