### ISSUE TITLE
Change signature

### ISSUE THREAD

**Issue by twixi** [RS485/LogisticsPipes#1656]
I`m translate gui buttons in blocks, after changes when server is start i have error:
[Client thread/ERROR] [LogisticsPipes]: The mod LogisticsPipes is expecting signature 4ab9c640e37baa2d4eca3354863a84d2c06bee42 for source logistics_pipes.jar, however there is no signature matching that description
(im remove meta-info folder)

**Comment by twixi** [comment]
Have new error **LogisticsPipes FMLLoadingPlugin wasn't loaded. Your download seems to be corrupt/modified. Please redownload LP from**

**Comment by bziemons** [comment]
Signatures are listed in https://github.com/RS485/LogisticsPipes#builds and `4ab9c640e37baa2d4eca3354863a84d2c06bee42` does not match any of ours.
To check if your file is exactly as we built it, you can e.g. upload the files here to see if this is the case: https://ci.rs485.network/fingerprintCheck
