### ISSUE TITLE
1.12.2 - Energy of the Industrial Craft through the pipes of the Logistics Pipes does not work

### ISSUE THREAD

**Issue by Davidcerq** [RS485/LogisticsPipes#1660]
Can someone help me?
The energy of the industrial craft through the pipes of the logistics pipes does not enter the machine.
I don't know which mod this bug is from, I've tried different versions of each mod and it doesn't solve.

Minecraft 1.12.2
Industrial Craft 2.8.221
Logistics Pipes 0.10.4.7

I warned the owner of the other mod
[https://bt.industrial-craft.net/view.php?id=2781](https://bt.industrial-craft.net/view.php?id=2781)

Images:
![2022-05-19_22 48 28](https://user-images.githubusercontent.com/105936284/169564579-699a3b55-10d8-4d53-b95c-0000d2baf220.png)
![2022-05-19_22 49 54](https://user-images.githubusercontent.com/105936284/169564606-d11a1044-2be2-4d9d-a0de-2b971102e863.png)

**Comment by bziemons** [comment]
Power transportation is not supported in LP for Minecraft 1.12, because it wasn't updated and tested. The related recipes are not craftable. It is on the list of feature requests as "Add back power transportation": https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
