### ISSUE TITLE
IC2C machine inventory not accessible until at least 1 item is added to the inventory

### ISSUE THREAD

**Issue by Lumpous** [RS485/LogisticsPipes#1663]
The IC2C macerator and rotary macerator are only "seen" as a valid destination for supplier pipe and modules if there is at least one item of the type to be exported in the machine.

Tested with all 6 available sides and automation upgrade in the IC2C machine.

logisticspipes-0.10.4.11.jar
IC2Classic 1.12-1.5.5.2.1.jar
forge-1.12.2-14.23.5.2860.jar

java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)

Pipe Settings:
![image](https://user-images.githubusercontent.com/112988030/189486818-9e4f5877-9d21-49c6-a09c-c81bbc5fb3d3.png)

IC2C Automation Upgrade:
![image](https://user-images.githubusercontent.com/112988030/189486844-fa2987f5-3da4-4d8d-b3e3-5725c716d0db.png)

Stock in storage:
![image](https://user-images.githubusercontent.com/112988030/189486871-294776e3-ced6-401c-899d-2cc9fbbeef02.png)

Machine and Pipe placement:
![image](https://user-images.githubusercontent.com/112988030/189486897-87ac7958-7223-48fc-bc07-570acfdd7f12.png)

**Comment by matthew117** [comment]
I have also observed this behaviour

**Comment by bziemons** [comment]
This is a bug from IC2C modifying the ItemStack in their `IItemHandler.insertItem`. The documentation of that function states "stack – ItemStack to insert. This must not be modified by the item handler.". I'll open a bug report on their GitHub. Fixed the issue nonetheless.

**Comment by Speiger** [comment]
Yeah derp on my side, I will address this the moment i am not 150% used up by IC2cs 1.19 port.
