### ISSUE TITLE
Server Crashes when I try to craft

### ISSUE THREAD

**Issue by sharanSuri2003** [RS485/LogisticsPipes#1670]
The server crashes (1.12.2) when i try to craft anything from the logistics pipes mod through the logistics crafting table, the crafting pipe does not even import the recipe so after manually setting the recipe the server crashes

**Comment by Bernasss12** [comment]
A bit more information would be very helpful, could you provide the crash log?

**Comment by sharanSuri2003** [comment]
Yes my bad here is the log
Edit: sent the wrong one
Edit:
Correct Log: https://mclo.gs/LlmOgRL

**Comment by Bernasss12** [comment]
Can you tell me which recipe you were trying to use? It's weird enough that the pipe didn't let you import it

**Comment by sharanSuri2003** [comment]
I was try to make the recipe for the logistics crafting table

**Comment by Bernasss12** [comment]
I really can't seem to reproduce this issue, if you could show your setup, like pipe and crafting table placement as well as their guis showing the configurations

**Comment by sharanSuri2003** [comment]
Apparently i just replaced the JAR file of the mod after redownloading, it seems to be fixed now and working as intended
Must be a curseforge issue while downloading then

**Comment by Bernasss12** [comment]
I'm glad to hear that! If anything else is broken don't hesitate to open another issue
