### ISSUE TITLE
Disconnection Upgrade GUI crash

### ISSUE THREAD

**Issue by wstc1997** [RS485/LogisticsPipes#1674]
Opening the GUI of Disconnection Upgrade crashes the game

version:0.10.4.3

**Comment by bziemons** [comment]
Please submit the debug log file or at least the crash report.

**Comment by 1idenburg** [comment]
Same issue here. Fresh modpack install on me and my friends game. I think it has to do with rendering the upgrade GUI.



> Please submit the debug log file or at least the crash report.

https://mclo.gs/PaMvkPR
