### ISSUE TITLE
fluid crafting upgrade reset fluid type after loading save what am i doing wrong ? bug ?

### ISSUE THREAD

**Issue by redfoxrommy** [RS485/LogisticsPipes#1678]
İts happen in forestry carpenter recipies . Just for fluid types . Amounth of fluids stay correct as selected. 1.12.2

**Comment by bziemons** [comment]
Should be fixed in [0.10.4.37](https://ci.rs485.network/job/LogisticsPipes-0.10.4/37/artifact/build/libs/logisticspipes-0.10.4.37.jar)
