### ISSUE TITLE
Request: Fluids as crafting results

### ISSUE THREAD

**Issue by Rundas01** [RS485/LogisticsPipes#1684]
In some scenarios (especially when playing GregTech), it would be convenient if fluids could be set as a crafting result. A pipe or module could do the job.

**Comment by bziemons** [comment]
Feature requests go here: https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests -- and since this request is so common, it is on number 2 :) Sadly not too easy to implement, otherwise it would've already happened.
