### ISSUE TITLE
Invalid version in the mcmod.info, which breaks all dependencies

### ISSUE THREAD

**Issue by IhHr** [RS485/LogisticsPipes#1688]
Invalid mcmod.info lines:
>     "version": "${version}",
>     "mcversion": "${mcversion}",

Minecraft log (the version.properties is a common warning, but LP metadata fallback at the end is wrong now):
>      [Client thread/WARN] [FML]: Mod logisticspipes is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version ${version}

Which in turn breaks all dependent mods:
![](https://i.imgur.com/W5gvleG.png)

**Comment by IhHr** [comment]
Applies to builds 35 and above (up to the latest 41).
Build 34 has correct properties.

**Comment by bziemons** [comment]
Thanks, will have a look

**Comment by bziemons** [comment]
Fixed in 117da018e206f5b5a09901076cd8d1d40230d2a3, [0.10.4.42](https://ci.rs485.network/job/LogisticsPipes-0.10.4/42/artifact/build/libs/logisticspipes-0.10.4.42.jar)
