### ISSUE TITLE
Chassis Mk2 not connecting

### ISSUE THREAD

**Issue by jedineeper** [RS485/LogisticsPipes#169]
This is regarding a problem in the latest jenkins build (677)

Sorry, I've not been able to find a set of steps to accurately reproduce this yet, but I've had it occur twice on our server so far and the only fix was to restart the server at which point everything resets and works fine. I'll keep trying to work out what we "do" to set this off but here are the details of what happens in case anyone else has experienced it and can chip in.

Small-medium LP network (~40 barrels, 10 chests, ~35 autocrafting/LP-crafting tables)

Newly placed MK2 chassis will not report as connected to the network - edge markers will remain red when connected despite their being a valid connection.

Once this is "triggered" existing chassis/pipes will work fine but any newly placed pipes will not work and any existing working pipes picked up and relaid will be broken in this fashion.

I've double checked the network, can't find any pipes that are "red" other than ones I place after this state triggers.

I've tried the following things to "fix" this ingame but so far only a server reboot resolves it.
- destroying, replacing (any) chassis on the network
- removing modules and reinserting
- crafting a brand new chassis pipe
- placing a chassis in several other places on my network including directly to the basic LP linking to my power block
- disconnecting the power and reconnecting
- checked there was power (max LP at all time)
- disconnecting my quick sorter module/chest from the network

Again, appreciate not having repro steps makes this difficult to spot and I will update if I do get any more info but wanted to make you aware.

Thanks,
Neeps

**Comment by ArtForz** [comment]
Once they start doing that... are newly placed pipes staying completely red (= not getting routing) or going red/green (= routed but not powered)?
If completely red, we suspect it's the background routing table update threads dying or getting stuck... Dev 679 fixed a wait that could end up being infinite if a pipe stopped ticking (chunk/dim unload?) at _just_ the right/wrong time.

**Comment by AartBluestoke** [comment]
Neeps, are there any messages in the server log? The only way i can think of this happening is if the routing threads died, or got into an infinite loop.

The only place an infinite loop could happen is fixed by dev 679, if some pipes somehow got into an "impossible" situation causing the routing table update threads hung. Could you please re-open this if you observe this with the new dev?

http://ci.thezorro266.com/job/LogisticsPipes-Dev
