### ISSUE TITLE
1.7.10 Versions of the mod not available?

### ISSUE THREAD

**Issue by Kanzaji** [RS485/LogisticsPipes#1696]
Hey there 👋
I realised 1.7.10 mods have been archived/removed from the CurseForge site, and the archive site on the CF page is not available, could I get a reason for removal of LogisticsPipes on version 1.7.10 from the CF Page, or their archival?
Thanks in advance 😄

EDIT: I found the Security report with the vurnability of the mod between some versions, however it appears that there were versions for 1.7.10 that didn't contain the issue 😅

**Comment by bziemons** [comment]
On CurseForge there were only vulnerable versions. Try version [0.10.0.77](https://ci.rs485.network/view/Logistics%20Pipes%20Archive/job/LogisticsPipes-0.10-mc17-bc7/77/artifact/build/libs/logisticspipes-0.10.0.77.jar) from the [archive](https://ci.rs485.network/view/Logistics%20Pipes%20Archive/).

**Comment by toastonrye** [comment]
Is it possible to update the versions on CurseForge, to fix old modpacks like Project Ozone 2?
Or not, because it's been archived?

**Comment by bziemons** [comment]
I think it makes more sense to use a mitigation now.
I know https://www.curseforge.com/minecraft/mc-mods/serializationisbad is a well-tested one, used by some public modded servers. I made a quick test of it myself when I was looking into the vulnerability.
