### ISSUE TITLE
ArrayIndexOutOfBoundsException with IC2 Classic reactor, Iron Chests

### ISSUE THREAD

**Issue by xJon** [RS485/LogisticsPipes#1698]
(Originally reported over https://github.com/xJon/Tekkit-2/issues/225)
Log: https://mclo.gs/8kozRXE#L4880
Is this something that can be prevented from LogisticsPipes' end?

> So the main gist of the bug is: the QuickSort module is clearing the inventory of the Reactor which it should not do.

**Comment by xJon** [comment]
@Speiger Do you have an idea of what's happening?

**Comment by Speiger** [comment]
@xJon somehow the reactor think it is has 12 chambers attached to it....
that is the crash...

Note that the reactor itself has a logic that at most can have 6 chambers attached.
What you report is "impossible" within IC2C unless something else messes with it.
Like the variable that is caching the result isn't modified outside of the internal "updateSize logic" and that ALWAYS resets it to the base value, and the iterator itself is only 6 elements... so how it can get to 12 elements when it is a 6 element iterator is like:
WHAT THE FUCK...

**Comment by xJon** [comment]
@Speiger Does reading/seeing about the setup over https://github.com/xJon/Tekkit-2/issues/225#issue-1902643971 help to make sense of it?

**Comment by Speiger** [comment]
No nothing in there makes sense to me.
There is not even a indicator for me of "why" this is an issue...
Sorry :/

**Comment by Dylankjy** [comment]
> @xJon somehow the reactor think it is has 12 chambers attached to it.... that is the crash...
> 
> Note that the reactor itself has a logic that at most can have 6 chambers attached. What you report is "impossible" within IC2C unless something else messes with it. Like the variable that is caching the result isn't modified outside of the internal "updateSize logic" and that ALWAYS resets it to the base value, and the iterator itself is only 6 elements... so how it can get to 12 elements when it is a 6 element iterator is like: WHAT THE FUCK...

I was the one who set up the reactors in the screenshot provided over at the Tekkit 2 Issue tracker.
For confirmation, all of the reactors only have 6 chambers attached to them.

**Comment by Dylankjy** [comment]
> @xJon somehow the reactor think it is has 12 chambers attached to it.... that is the crash...
> 
> Note that the reactor itself has a logic that at most can have 6 chambers attached. What you report is "impossible" within IC2C unless something else messes with it. Like the variable that is caching the result isn't modified outside of the internal "updateSize logic" and that ALWAYS resets it to the base value, and the iterator itself is only 6 elements... so how it can get to 12 elements when it is a 6 element iterator is like: WHAT THE FUCK...

@Speiger I was the one who set up the reactors in the screenshot provided over at the Tekkit 2 Issue tracker.
For confirmation, all of the reactors only have 6 chambers attached to them.

**Comment by Speiger** [comment]
@Dylankjy the problem is not that you placed down more then 6 reactor chambers.
The problem is that the logic is not CAPABLE to DETECT more then 6 chambers.
So that this happens is like as if you had been hit by an cosmic ray...

**Comment by bziemons** [comment]
It would be great if someone could test this issue with build [0.10.4.47](https://ci.rs485.network/job/LogisticsPipes-0.10.4/47/artifact/build/libs/logisticspipes-0.10.4.47.jar).

**Comment by xJon** [comment]
@Dylankjy @xiaoxinny Any chance you can help test it out?

**Comment by xiaoxinny** [comment]
Apologies, I have already tested this out. It appears to work perfectly fine now, thank you!

**Comment by bziemons** [comment]
@xiaoxinny awesome, thanks :)
