### ISSUE TITLE
logistics pipes mod not working as intended 

### ISSUE THREAD

**Issue by Isabellawolf** [RS485/LogisticsPipes#1700]
hey so i don't know if its a recent thing in a update or something but for some reason when i put items into a chest with a extraction pipe with all module slots used the system only take's a certain amount of items with delay in between extraction's as i have played with this mod in the past i know for a fact that when you put items into a chest with an logistics system it is meant to take all items at the same time with no delay plz let me know if this is a bug or if this is a recent change to the mod 

just in case you need the pack name and version and the mod version here they are 
pack name: FTB Presents Direwolf20
pack version:1.12.2
mod version: 0.10.3.114.jar Release

plz let me know if i need to change or update to the latest version

**Comment by bziemons** [comment]
Hey, please retest after an update to [0.10.4.49](https://ci.rs485.network/job/LogisticsPipes-0.10.4/49/artifact/build/libs/logisticspipes-0.10.4.49.jar).

**Comment by Isabella324** [comment]
hey just a heads up every time i place a pipe down my game lags EVERY time i play down a pipe even with on power connected to it also plz let us use the old render again as the new one just lags games out i have a very good pc and even that has an issue with the mod as for testing i am in the process of setting up a system to sort my inv out will let you know if update has fix the issues or not

**Comment by Isabella324** [comment]
also this is the same person i just have 2 accounts on here some time i forget one or the other accounts passwords lol

**Comment by Isabella324** [comment]
![image](https://github.com/RS485/LogisticsPipes/assets/155318599/ba0b124d-7ab4-447e-9725-a8d2e2df7869)
 so it is still taking items out with delay it will take certain amount of items out of the chest then waits and then  repeats the same thing over and over again until the chest is empty even with 4 pipes connect to said chest with all pipe slots full with extracting modules and i am on the latest ver of the mod as you have stated for me to do

**Comment by Celestial0579** [comment]
Seems to be the same issue as [here](https://github.com/RS485/LogisticsPipes/issues/1649) ? I've posted some details there yesterday.
