### ISSUE TITLE
Logistics Pipes IC2 Power Supplier Upgrade not working

### ISSUE THREAD

**Issue by Ramog** [RS485/LogisticsPipes#1712]
MC Version: 1.12.2
Mod Version: logisticspipes-0.10.4.49
Modpack: Tekkit SMP

If you setup an `EU Power Provider` and create a working [power network for your LP-System](https://ftb.fandom.com/wiki/Getting_Started_(Logistics_Pipes)#Transporting_Power) it will not work unless you leave the world and load it again.
**But even then** only the laser beam in the pipes shows up, no power is put into the machine that the `IC2 Power Supplier Upgrade` is attached to.
I was told that this is unique to EU, the RF part of this system seems to work without problem.

This was both tested with IC2Classic-1.12.2-1.5.11 and industrialcraft-2-2.8.222-ex112, didn't work for either.
##### Beam not showing up right after setting it up 
![2024-11-24_12 35 57](https://github.com/user-attachments/assets/5d706c6d-c4d1-4bc6-ae51-3fcc6d2cbd04)
##### Beam showing up after relogging
![2024-11-24_12 36 22](https://github.com/user-attachments/assets/f972f5a9-2b9b-4382-b980-7eedbba4b830)
##### Still no energy in the Macerator even after the beam showed up
![2024-11-24_12 36 29](https://github.com/user-attachments/assets/242e78de-51aa-41cb-a7e9-fa59877c202f)

**Comment by bziemons** [comment]
Hi, the power transfer unfortunately does not work since the upgrade to 1.12 and is on [the list of feature requests to implement (Add back power transportation)](https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests).
