### ISSUE TITLE
Crash With Dev 680.  MMMPowersuits Conflict?

### ISSUE THREAD

**Issue by ReportBot9009** [RS485/LogisticsPipes#172]
There is a crash with the Dev 680 that points to a MMMPowersuits conflict?

The crash is a java.lang.AbstractMethodError

Here are the crashes via Pastebin:

Minecraft Crash:
http://pastebin.com/SGQaHmkQ

Crash Report:
http://pastebin.com/X2MLy1Yy

**Comment by davboecki** [comment]
The current version of LP is build againt build 534 of MMMPowersuits. As it says here http://www.machinemuse.net/download.php.

**Comment by ReportBot9009** [comment]
I have installed MMMPowersuits 534 from the site and this is the error I am still getting with Logistics Dev680.

I have refreshed the config files of both mods just to be sure.

Minecraft Crash:
http://pastebin.com/QYqcRruv

Crash Report:
http://pastebin.com/zAdMCQns

**Comment by davboecki** [comment]
Now your version of ModularPowersuits-Addons is not compatible with that MPS version.

**Comment by ReportBot9009** [comment]
Oh gosh, my mistake.  It seems that Logistics 679 plays well with MMMPowersuits 635 and MPSA 186, so I'll just stick with that for now. That MMM build is coming on 3 months old and I was hoping the newest builds fixed some graphical glitches.  

Sorry for wasting time and thank you for the help.

**Comment by davboecki** [comment]
Now you can also use newer MPS versions. https://github.com/RS485/LogisticsPipes-Dev/commit/62af9080d7cd358544bcbdbf784771e2c40140e2

**Comment by ReportBot9009** [comment]
Oh wow!  Thank you so much!  This is fantastic! :)

Did.. Did I ever say you guys are, along with very very few others, the best Dev Team in Minecraft?  Well, you are.
