### ISSUE TITLE
Firewall pipe causing significant world-lag

### ISSUE THREAD

**Issue by jedineeper** [RS485/LogisticsPipes#174]
Hi guys,

We're on -dev #780 now and I've found a problem with firewall pipes. 

I setup a "micro" LP network to act as a buffer to convert coal to coal coke (1:1 conversion) using a coke oven from the Railcraft mod. I don't believe the problem is related to the mod interaction.

Here's a description of the mini network...

A chest containing 10 stacks of coal has a Mk2 chassis with an item sink module (coalcoke) and a provider module (coal) on it.

The Mk2 is linked to a supplier pipe which is connected to the coke oven and is set to keep the oven full of coal (which it pulls from the chest)

Also linked to the coal oven wall and to the supplier pipe is a Mk1 chassis which contains an extractor module mk2 that pulls the coal coke out.

It's pretty simple and is only 3 pipes, the interface to my main network is a crafting pipe which attaches to the front of the chest and has 1coal as an input and 1coalcoke as an output.

Where I'm having trouble is the final pipe which is the firewall pipe I use to link the Mk2 chassis on the mini network to the crafting pipe on the main network (bypassing the chest). The firewall pipe is set to block everything, but allow power (to power the mini network)

When the firewall is in place the TPS on the server increases from 4 to 20-30 :(

This was constantly reproducible on my world, I could sit and break and replace the firewall pipe to get the lag. Putting a basic LP pipe in its place to directly link the mini network to the main network allowed everything to work correctly (it just pulls coal from my network's main coal provider pipe once the chest is empty of coal, which I didn't want)

Let me know if I can provide any further info or if it is unclear.

Thanks,
Craig

**Comment by Flow86** [comment]
Hi,
I think you wanted to say "decreases from 20-30 to 4" ? since "more" are better.

But I think its reproducable - I havent used a firewall pipe since it almost killed my complete server (really large lp network) since it reduced the tps to <1. (And got a crash after destroying the pipe, but then it worked again)

perhaps something's a bit wrong in the firewall "pathfinding".

**Comment by davboecki** [comment]
From 1.6 dev build 36 and up the filtering code has been nearly compleatly reworked. If there is still an issue with the firewall pipe please open a new issue.
