### ISSUE TITLE
Ability to halt network actions with the security station

### ISSUE THREAD

**Issue by AartBluestoke** [RS485/LogisticsPipes#175]
similar to https://github.com/RS485/LogisticsPipes/issues/732

Problem: cutting power to the network spills objects, so there is no easy way to turn a network off.

The security station should have a button on it's gui and/or a pipe-gate action which blocks all actions on the network.

Blocks All Actions: all provide, craft, and extract actions. This will allow items "in flight" to find a destination without spilling, but also allow a sensible shutdown of the network.

Bonus points if it is remotely activatable (probably by the network analyzer).

**Comment by ghost** [comment]
Redstone signal to the Logistics Power Junction should do this.

**Comment by bziemons** [comment]
@DZCreeper No. For the reasons above: "Blocks all actions" does not fit for a power junction.

**Comment by bziemons** [comment]
See https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests  
*Pause Requests*
