### ISSUE TITLE
NPE on startup.

### ISSUE THREAD

**Issue by ThoBekMic** [RS485/LogisticsPipes#178]
I get this, upon client startup:

http://pastebin.com/pAsSBdZx

**Comment by davboecki** [comment]
Do you use id resolver?

**Comment by ThoBekMic** [comment]
Sorry for the late reply. No, I use IDfix:

http://www.minecraftforum.net/topic/1928632-162smpforge-idfix-resolve-id-conflicts-automatically/

I'd think that if it was an ID conflict, it would tell me. But that's maybe not the case, since you're asking?

**Comment by davboecki** [comment]
http://www.minecraftforum.net/topic/1831791-152buildcraft-logistics-pipes/page__st__260#entry24276318 that's all i curently know.

**Comment by t999uk** [comment]
have you tried using the default minecraft launcher rather then the magic launcher

**Comment by ThoBekMic** [comment]
t999uk: I have not. I'll try that.

**Comment by ThoBekMic** [comment]
Looks like the same error:

http://pastebin.com/TD1bAvSA

**Comment by ThoBekMic** [comment]
Tried with the vanilla launcher. Same result. Also tried setting the block ID manually, just to see if that was causing the issue with my IDfix. I did not touch the item IDs though.

**Comment by ThoBekMic** [comment]
Right, found out that it bugs with IDfix. For some reason it's working now, with IDfix. Maybe it's because I manually assigned IDs for Logistics Pipes manually in IDfix. Closing this issue.
