### ISSUE TITLE
LP doesn't check if mps's power fist have the omniwrench selected

### ISSUE THREAD

**Issue by Algent** [RS485/LogisticsPipes#179]
If you right click a Logipipe with a powerfist it open the GUI even when omniwrench isn't selected.

I was thinking it was a powersuit bug but EnderIO author managed to fix it:
https://github.com/CrazyPants/EnderIO/issues/36
https://github.com/CrazyPants/EnderIO/commit/9c66edc235075b67a24436c1b6f0f33273beb1f5

**Comment by ArtForz** [comment]
Implemented in 3d7b1cba37
