### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by MrVoltz** [RS485/LogisticsPipes#189]
> 16:21:57 [WARNING] Failed to handle packet for MrVoltz/89.102.89.54: java.lang.RuntimeException: java.lang.NullPointerException
> java.lang.RuntimeException: java.lang.NullPointerException
> at logisticspipes.network.PacketHandler.onPacketData(PacketHandler.java:84)
> at logisticspipes.network.PacketHandler.onPacketData(PacketHandler.java:72)
> at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:265)
> at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:254)
> at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:88)
> at net.minecraft.network.NetServerHandler.func_72501_a(NetServerHandler.java:2406)
> at net.minecraft.network.packet.Packet250CustomPayload.func_73279_a(SourceFile:59)
> at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:442)
> at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:223)
> at net.minecraft.network.NetworkListenThread.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:53)
> at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java)
> at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(SourceFile:30)
> at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:431)
> at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320)
> at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:307)
> at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:199)
> at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
> Caused by: java.lang.NullPointerException

Using TickThreading and MCPC+. Sometimes, one of pipes in my logistics system get bugged and when I open Logistics Request Table or click at Request Pipe, the server kick me with message Internal Server Error.

**Comment by davboecki** [comment]
Versions?

**Comment by MrVoltz** [comment]
LogisticsPipes-MC1.5.2-0.7.3.dev.683
TickThreading-1.5.2.186
mcpc-plus-1.5.2-R1.1-forge738-B643

I have automatic peat farm. Next to farm hatch I have chassis with advanced extractor MK3 which extracts peat and dirt. Then I have 40 peat-fired engines and next to each of them I have supplier pipe in partial mode with 8 peat set in them.

![2013-09-27_17 24 38](https://f.cloud.github.com/assets/5212649/1227026/9a282a72-278a-11e3-9d01-4bfdd805b11f.png)

![2013-09-27_17 26 18](https://f.cloud.github.com/assets/5212649/1227018/861c47ca-278a-11e3-93b0-c762a8c19b94.png)

When it gets bugged, i must break and place the provider pipe.

P.S: What means Bulk50 and Bulk100 in supplier pipes?

**Comment by AartBluestoke** [comment]
I would guess the problem is
Tick threading.  Minecraft's inventory system isn't thread safe. Could you
remove TR and report if the problem either way?

Also, which mod do you have CPU usage concerns about, such that you feel
the need for it?

**Comment by MrVoltz** [comment]
I'm running multiplayer server. Everyone has tons of IC2 cables and buildcraft/logistics pipes, so the server can't keep at 20 TPS. With TickThreading it is ok and usually aren't any lags.

**Comment by AartBluestoke** [comment]
I don't believe that logistics pipes is responsible for  the lag. In my
recent experience of had been the ic2 power network that is the main lag
cause.  If you feel that lp is causing any significant lag,  please profile
the server while it is running and report your findings here (with the
profile linked/attached here,  if possible)

(if you have gui access to the server then jvisualvm,  sample mode is an
excellent idea.  It doesn't interference with a running server in any way.
Don't use profile mode,  that causes huge lag until the server is
restarted. Jvisualvm is part of all jdk installations.)

**Comment by GUIpsp** [comment]
It's also worth noting that nallar has stopped working on TT

**Comment by davboecki** [comment]
Oh and by the way could you please post the full stack traces because the important part is missing at the end.
