### ISSUE TITLE
Requests fail with 'You are missing' messages even when the item is available in a request pipe

### ISSUE THREAD

**Issue by Jean0** [RS485/LogisticsPipes#19]
Sometimes the request system blocks and says that items are missing even if they are displayed in the interface with an amount available. I had this problem before in regular release-84 then I upgraded to dev-177, which seemed to solve it(or it didn't occur), then when I upgraded to #181 and #182 today the issue returned.

![2013-02-13_13 55 15](https://f.cloud.github.com/assets/3584291/152879/ec3827b2-75de-11e2-9d36-00d089922116.png)

This happens for both available and craftable items.

**Comment by ArtForz** [comment]
181 broke providers
183 fixed them again

**Comment by Jean0** [comment]
seems to be broken again in 194, but only for some items this time.
