### ISSUE TITLE
Bug in build 53 - Memory Leak

### ISSUE THREAD

**Issue by miuirussia** [RS485/LogisticsPipes#195]
Memory leak!

---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 02.10.13 22:49
Description: Ticking tile entity

java.lang.NoClassDefFoundError: logisticspipes/routing/RoutedEntityItem
    at logisticspipes.proxy.buildcraft.BuildCraftProxy.CreateRoutedItem(BuildCraftProxy.java:191)
    at logisticspipes.proxy.buildcraft.BuildCraftProxy.CreateRoutedItem(BuildCraftProxy.java:198)
    at logisticspipes.pipes.PipeItemsProviderLogistics.sendStack(PipeItemsProviderLogistics.java:176)
    at logisticspipes.pipes.PipeItemsProviderLogistics.enabledUpdateEntity(PipeItemsProviderLogistics.java:244)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:403)
    at buildcraft.transport.TileGenericPipe.func_70316_g(TileGenericPipe.java:169)
    at net.minecraft.world.World.func_72939_s(World.java:2209)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:552)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:666)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:585)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:175)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:582)
Caused by: java.lang.ClassNotFoundException: logisticspipes.routing.RoutedEntityItem
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:179)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 13 more
Caused by: java.lang.OutOfMemoryError: PermGen space
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:792)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:171)
    ... 15 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at logisticspipes.proxy.buildcraft.BuildCraftProxy.CreateRoutedItem(BuildCraftProxy.java:191)
    at logisticspipes.proxy.buildcraft.BuildCraftProxy.CreateRoutedItem(BuildCraftProxy.java:198)
    at logisticspipes.pipes.PipeItemsProviderLogistics.sendStack(PipeItemsProviderLogistics.java:176)
    at logisticspipes.pipes.PipeItemsProviderLogistics.enabledUpdateEntity(PipeItemsProviderLogistics.java:244)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:403)
    at buildcraft.transport.TileGenericPipe.func_70316_g(TileGenericPipe.java:169)

-- Tile entity being ticked --
Details:
    Name: logisticspipes.pipes.basic.LogisticsTileGenericPipe // logisticspipes.pipes.basic.LogisticsTileGenericPipe
    Block type: ID #1513 (tile.null // logisticspipes.pipes.basic.LogisticsBlockGenericPipe)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (702,8,264), Chunk: (at 14,0,8 in 43,16; contains blocks 688,0,256 to 703,255,271), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
    Actual block type: ID #1513 (tile.null // logisticspipes.pipes.basic.LogisticsBlockGenericPipe)
    Actual block data value: 0 / 0x0 / 0b0000
    LP-Version: 0.7.4.dev.53:false
    Pipe: logisticspipes.pipes.PipeItemsProviderLogistics
    Transport: logisticspipes.transport.PipeTransportLogistics
    Router: ServerRouter: {ID: 2, UUID: 7bd8c01f-d1ba-419b-bc02-7e41fe5c641e, AT: (0, 702, 8, 264), Version: 6), Destroied: false}
    stillNeedReplace: false
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2209)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:552)

-- Affected level --
Details:
    Level name: New World
    All players: 1 total; [EntityPlayerMP['KOJAN'/34092, l='New World', x=698,34, y=8,00, z=264,63]]
    Chunk stats: ServerChunkCache: 441 Drop: 0
    Level seed: -7134519336429333386
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 2;7,3x1,4x42;2;
    Level spawn location: World: (699,4,249), Chunk: (at 11,0,9 in 43,15; contains blocks 688,0,240 to 703,255,255), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
    Level time: 12414 game time, 6207 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 8408 (now: false), thunder time: 148516 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:666)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:585)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:175)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:582)

-- System Details --
Details:
    Minecraft Version: 1.6.2
    Operating System: Mac OS X (x86_64) version 10.9
    Java Version: 1.7.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1130162272 bytes (1077 MB) / 1742491648 bytes (1661 MB) up to 4151836672 bytes (3959 MB)
    JVM Flags: 3 total; -Xmx4096m -XX:+AggressiveOpts -XX:+UseFastAccessorMethods
    AABB Pool Size: 168 (9408 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 60
    FML: ?aKDev Group | ?bmine-craft.su
    mcp{8.04} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    FML{6.2.62.871} [Forge Mod Loader](Forge.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Forge{9.10.1.871} [Minecraft Forge](Forge.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    CodeChickenCore{0.9.0.5} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    NotEnoughItems{1.6.1.3} [Not Enough Items](NotEnoughItems_1.6.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Novamenu{1.1.2} [Novamenu](Novamenu1.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    SomniaCore{1.0.3} [SomniaCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    AppliedEnergistics-Core{rv13.c} [AppliedEnergistics Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    mod_bspkrsCore{v3.05(1.6.2)} [bspkrsCore](bspkrsCorev.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BiomesOPlenty{1.1.2} [Biomes O' Plenty](BiomesOPlenty-universal-1.6.4-1.1.2.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    CarpentersBlocks{v1.84} [Carpenter's Blocks](Carpenter.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ChickenChunks{1.3.3.2} [ChickenChunks](ChickenChunks_1.3.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ConfigMod{v1.0} [Extended Mod Config](ConfigMod_for_MC_v1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    CoroAI{v1.0} [CoroAI](CoroAI_for_MC_v1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    EnderStorage{1.4.3.3} [EnderStorage](EnderStorage_1.4.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ExtendedRenderer{v1.0} [Extended Renderer](ExtendedRenderer_for_MC_v1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    AppliedEnergistics{rv13.c} [Applied Energistics](appeng-rv13-c-mc162.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    extracells{1.4.5} [ExtraCells](ExtraCells-universal-1.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    GregsLighting{1.9.0} [Greg's Lighting](GregsLighting-1.9.0-mc1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    IC2{2.0.239-experimental} [IndustrialCraft 2](industrialcraft-2_2.0.239-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    IC2NuclearControl{1.6.2c} [Nuclear Control](IC2NuclearControl-1.6.2c-ic2-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Core{4.1.0} [BuildCraft](buildcraft-A-1.6.2-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Builders{4.1.0} [BC Builders](buildcraft-A-1.6.2-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Transport{4.1.0} [BC Transport](buildcraft-A-1.6.2-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Silicon{4.1.0} [BC Silicon](buildcraft-A-1.6.2-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Forestry{2.3.0.2_ic2.ex} [Forestry for Minecraft](forestry-A-2.3.0.2_ic2.ex.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    LogisticsPipes|Main{0.7.4.dev.53} [Logistics Pipes](LogisticsPipes-MC1.6.2-0.7.4.dev.53.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ForgeMultipart{1.0.0.171} [Forge Multipart](ForgeMultipart-universal-1.6.2-1.0.0.171.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ProjRed|Core{4.0.1.4} [Project: Red-Core](ProjectRedBase-1.6.2-4.0.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    TConstruct{1.6.2_1.4.5} [Tinkers' Construct](TConstruct_1.6.2_1.4.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ProjRed|Compatability{4.0.1.4} [ProjectRed-Compatability](ProjectRedCompat-1.6.2-4.0.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ProjRed|Integration{4.0.1.4} [ProjectRed-Integration](ProjectRedIntegration-1.6.2-4.0.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ProjRed|Transmission{4.0.1.4} [ProjectRed-Transmission](ProjectRedIntegration-1.6.2-4.0.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ProjRed|Exploration{4.0.1.4} [ProjectRed-Exploration](ProjectRedWorld-1.6.2-4.0.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ProjRed|Illumination{4.0.1.4} [ProjectRed-Illumination](ProjectRedWorld-1.6.2-4.0.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Energy{4.1.0} [BC Energy](buildcraft-A-1.6.2-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Factory{4.1.0} [BC Factory](buildcraft-A-1.6.2-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    QuarryPlus{1.5.4} [QuarryPlus](QuarryPlus-1.6.2-1.5.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Railcraft{8.0.2.0} [Railcraft](Railcraft_1.6.2-8.0.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Somnia{1.0.1} [Somnia](Somnia-Pre1d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    TConstruct|CompatMineFactoryReloaded{0.1} [TConstruct Compat: MFR](TConstruct_1.6.2_1.4.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    TimeScaler{1.1} [TimeScaler](TimeScaler.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    TreeCapitator{Forge 1.6.2.r05} [Treecapitator](TreeCapitator.Forge.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    fodc{1.4.0} [Ore Dictionary Converter](fodc-1.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ImmibisCore{56.0.3} [Immibis Core](immibis-core-56.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    LiquidXP{56.0.2} [Liquid XP](liquid-xp-56.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    gregtech_addon{MC162} [GregTech-Addon](gregtechmod.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    IronChest{5.3.20.549} [Iron Chest](ironchest-universal-1.6.2-5.3.20.549.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    magicalcrops{3.0.6 BETA} [Magical Crops](magical_crops_1.6.2_3.0.6_BETA.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    MapWriter{2.0} [MapWriter](mapwriter-2.0.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    TEOreGen{0.1} [TEOreGen](mod_TEOreGen_0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Mystcraft{0.10.6.00} [Mystcraft](mystcraft-uni-1.6.2-0.10.6.00.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    McMultipart{1.0.0.171} [Minecraft Multipart Plugin](ForgeMultipart-universal-1.6.2-1.0.0.171.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ForgeMicroblock{1.0.0.171} [Forge Microblocks](ForgeMultipart-universal-1.6.2-1.0.0.171.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 6 (336 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['KOJAN'/34092, l='New World', x=698,34, y=8,00, z=264,63]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by GUIpsp** [comment]
Not a mem leak, you just ran out of permgen space. Increase it with `-XX:PermSize=64m`

**Comment by miuirussia** [comment]
Thanks!
