### ISSUE TITLE
Bug with logistics crafting table

### ISSUE THREAD

**Issue by miuirussia** [RS485/LogisticsPipes#196]
![2013-10-03_10 21 09](https://f.cloud.github.com/assets/1270028/1259736/7162e096-2bf4-11e3-99f9-60d2600ad187.png)
Receipt
![2013-10-03_10 21 16](https://f.cloud.github.com/assets/1270028/1259739/8302feda-2bf4-11e3-94bb-9ccf136332ba.png)
When I click import:
![2013-10-03_10 21 21](https://f.cloud.github.com/assets/1270028/1259741/93bd9d20-2bf4-11e3-9e4a-29cc6d0a5d57.png)
Now I got this:
![2013-10-03_10 21 24](https://f.cloud.github.com/assets/1270028/1259743/a1c0d2b6-2bf4-11e3-8386-78d1270c43c9.png)
What should be:
![2013-10-03_10 33 48](https://f.cloud.github.com/assets/1270028/1259771/e20fc22c-2bf5-11e3-8f3c-5516a32fe3d2.png)

**Comment by GUIpsp** [comment]
Why should it be stacked?

**Comment by miuirussia** [comment]
Because this does not crafting (Not laser item, others)
why it takes Satellite slots

**Comment by miuirussia** [comment]
# More:

## Auto Workbench + Logistics Crafting Pipe

In Workbench:
![2013-10-03_18 57 04](https://f.cloud.github.com/assets/1270028/1262240/4941de44-2c3c-11e3-8368-67d4f0b2fa94.png)
In Logistics Crafting Pipe after clicking Import:
![2013-10-03_18 57 06](https://f.cloud.github.com/assets/1270028/1262241/4b58ae74-2c3c-11e3-87cb-864388704573.png)

## Logistics Craft Table + Logistics Crafting Pipe

In Craft Table:
![2013-10-03_18 57 11](https://f.cloud.github.com/assets/1270028/1262267/c17859d8-2c3c-11e3-99e7-759feabdeb2f.png)
In Logistics Crafting Pipe after clicking Import:
![2013-10-03_18 57 13](https://f.cloud.github.com/assets/1270028/1262270/cb604122-2c3c-11e3-87cf-60e2ea4ec688.png)

But expect the same results

**Comment by bziemons** [comment]
Sorry, but I cannot guess what version are you using?

**Comment by miuirussia** [comment]
LogisticsPipes-MC1.6.2-0.7.4.dev.53.jar  from Jenkins

**Comment by davboecki** [comment]
Can you retest with build dev.54 ?

**Comment by miuirussia** [comment]
Yes)

**Comment by miuirussia** [comment]
Thanks, with dev.54 working good
