### ISSUE TITLE
Crash With Thaumic Tinkerer

### ISSUE THREAD

**Issue by esKaayY** [RS485/LogisticsPipes#198]
Crash on Instance startup:

So I'm getting a 3-way mod conflict, whenever I have these mods:
Logistics Pipes (0.7.4dev56)
NEI (1.6.1.4)
Thaumic Tinkerer (2.0-20)
And there respective pre-requisites (CCC 0.9.0.5, Thaumcraft 4.0.1b, Buildcraft 4.1.0, CodeChickenLib #24)
I get this crash log: http://pastebin.com/CaaP2aXb
Full log: http://pastebin.com/frMKXwkR
Forge 871

This is also replicable in 1.6.4
Logistics Pipes (0.7.4dev56)
NEI (1.6.1.5)
Thaumic Tinkerer (2.0-20)
And there respective pre-requisites (CCC 0.9.0.6, Thaumcraft 4.0.1b, Buildcraft 4.1.0, CodeChickenLib #36)
I get this crash log: http://pastebin.com/w9hbXSLG
Full log: http://pastebin.com/XZjB38HX
Forge 923

I narrowed the problem to these 3 mods because deleting either one of them allows minecraft to load. I am cross-posting this for all 3 mods.

Edit:http://www.minecraftforum.net/topic/1813058-thaumic-tinkerer-thaumcraft-addon-evolve-knowledge-20-30k-downloads/page__st__940#entry24896731

Edit: Also, I tested this with the new version #57 and it gives the same error.

**Comment by davboecki** [comment]
Could you retest this with build 58. The problem probably is a combination between the way LP handles it's dependent Interfaces, the way Thaumic Tinkerer does it, CCC trying to precache some stuff and a cache Minecraft it self keeps from invalid classes. So this is neither a problem for LP nor Thaumic Tinkerer. But I added a smal fix to LP that should prevent this problem for now.

**Comment by esKaayY** [comment]
Ill test with the new build when I get home, it's thanksgiving in Canada lol

**Comment by esKaayY** [comment]
Build 63 fixes it! I'll let Vazkii know
