### ISSUE TITLE
[INFO] Hey, don't get routers for pipes that aren't ready

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#201]
FTB Mod Pack: Unleashed
Version 1.1.5
Mod Causeing issues: Logistic Pipes
Pastebin to Server Error: http://pastebin.com/EstvnzTc

Since the upgrade to 1.1.5 I keep getting the above errors continually spammed inside my console there has been no change in performance so I guess its not affecting resources on the system but it throws that above error continually every minute or so.

Any suggestions would be greatly appreciated

Logistics Build in 1.1.5 Unleashed is #631
Latest Logitics Pipes Dev Version on there jenkins site is #691

I just dont wish conflicts by trying the latest dev version of logistic pipes till I am sure.that the mod was not specifically put in the ftb pack due to compatability issues with other mods.

**Comment by davboecki** [comment]
That's a realy old bug. that has been fixed in newer LP versions.

**Comment by ghost** [comment]
Thanks for the reply but has not really answered the question i had asked.  Not sure why FTB is distributing a build from back in August in there latest updates as of yesterday in FTB Unleashed 1.1.5 

Can this be updated to the current build without comparability issues with the rest of there modpack not really getting much assistance on either there site or here really.......

May just remove the mod due to lack of support 

thanks

**Comment by davboecki** [comment]
i'm not aware of any compatibility issues with thw newest dev verion for 1.5. You should be able to update without a problem.

**Comment by ghost** [comment]
Thanks have given it a shot seems to be working fine :) have llet creeperhost know since they probably be also inundated with the same support requests. Not sure why FTB are using such a old build in there latest updated pack if it has these old bugs in it. 

Thanks agaiin
