### ISSUE TITLE
NoClassDefFoundError from pipe renderer [MC 1.6.4, LP 0.7.4.dev.64, BC 4.1.1]

### ISSUE THREAD

**Issue by SisterJacq** [RS485/LogisticsPipes#206]
I know that you haven't updated for about a week, and 4.1.1 came out on the 24th, but it also happened in 4.1.0. I know it is for 4.0.0 so I don't expect help immediately, I just want to alert you. :)
                                -Mortvana
[Damn you GitHub, y u no accept .txt files?]

**Comment by davboecki** [comment]
LP is now compatible with the BC version 4.1.2.

**Comment by SisterJacq** [comment]
Thanks :)
