### ISSUE TITLE
POWER_USAGE_MULTIPLIER is int, should be double/float

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#208]
https://github.com/RS485/LogisticsPipes-Dev/search?q=POWER_USAGE_MULTIPLIER&ref=cmdform

An int does not let users scale power usage to something below the default.

**Comment by LizzyTrickster** [comment]
The default is 1, why would it need to go any lower than that? If you're looking to disable power requirements theres a different option for that...

**Comment by AEnterprise** [comment]
i think he means putting it on 0.5 for example so he can make his system use only half the required power

**Comment by AartBluestoke** [comment]
@sadris is there any specific section of power usage that you feel is too hungry?

**Comment by ghost** [comment]
Compared to AE, LP has much more sane power usage.
