### ISSUE TITLE
Provider only pulls items from one half of a double chest

### ISSUE THREAD

**Issue by Jean0** [RS485/LogisticsPipes#21]
If I have a chassis with a provider attached to the right side of a double chest, the requester pipe will list the full content of the chest but will only be able to request the items on the top 3 rows of the chest(displays 'you are missing' if it's an item on the lower 3 rows). If I put the chassis on the left side of the chest it is reversed and will only be able to request them from the lower 3 rows. (in dev 194)

**Comment by ArtForz** [comment]
Hurrm, guess we're missing a InventoryHelper call somewhere (which is what we use to hande vanilla doublechests)

**Comment by ArtForz** [comment]
Should be fixed in Dev 195, please retest

**Comment by Jean0** [comment]
It works
