### ISSUE TITLE
Blocks don't work

### ISSUE THREAD

**Issue by AEnterprise** [RS485/LogisticsPipes#211]
![2013-11-05_21 36 03](https://f.cloud.github.com/assets/5206666/1477363/04a64602-465a-11e3-993d-ff7f99f6ef5e.png)
in the inventory slots are all 4 of the blocks that logistic pipes adds and, and on the place of the cursor i placed one of them but it is the same problem with the other blocks, they are invisibe, pipes won't connect and the GUI won't open

**Comment by davboecki** [comment]
Have you checked for ID conflices?
In order to help you we will need a full FML log.

**Comment by AEnterprise** [comment]
EDIT: found it, it has an id conflict with portal gun, it works now, thanks alot, the first time i checked i must have overlooked it
