### ISSUE TITLE
crasch with buildcraft4.1.2

### ISSUE THREAD

**Issue by villain79** [RS485/LogisticsPipes#212]
http://pastebin.com/6mxqxSUU

**Comment by davboecki** [comment]
Why is this supposed to be an LP bug?

**Comment by AEnterprise** [comment]
this is a buildcraft crash and it has nothing to do with LP according to the log

**Comment by GUIpsp** [comment]
@AEnterprise Yeah, no need to bump the issue.

**Comment by AEnterprise** [comment]
i'm not bumping issues, i'm just telling him that he should report it to buildcraft

**Comment by bziemons** [comment]
@AEnterprise But one month later and you might have forgotten that all subscribers get an email. Just dont answer on closed tickets without a good reason please. There is nothing against your help, that is good.
