### ISSUE TITLE
Providerpipe on barrels provide wrong available amount of items (63/64 max) to LP system

### ISSUE THREAD

**Issue by Ioandar** [RS485/LogisticsPipes#214]
- requestpipe shows 63/64 items available. (63/64 depends on mode of providerpipe)

My 1.4.7 world has lots of barrels and LP working flawless with correct amount

edit:forgot to mention my versions, sorry

minecraftforge-installer-1.6.4-9.11.1.946.jar
LogisticsPipes-MC1.6.2-0.7.4.dev.65.jar
Factorization-0.8.04beta17.jar

edit2: same with build70

LogisticsPipes-MC1.6.2-0.7.4.dev.70.jar

edit3: 63/64 is depending on mode of provider pipe (normal/leave 1 item)

**Comment by AartBluestoke** [comment]
what version of lp?

**Comment by Ioandar** [comment]
LogisticsPipes-MC1.6.2-0.7.4.dev.65.jar
Factorization-0.8.04beta17.jar

**Comment by davboecki** [comment]
Should be fixed by: https://github.com/RS485/LogisticsPipes-Dev/commit/91459fd872b178447d588c83151ab6e7e12ab333
