### ISSUE TITLE
Liquid Supplier Pipe - Forestry

### ISSUE THREAD

**Issue by gu471** [RS485/LogisticsPipes#216]
A system of a Liquid Supplier Pipe, Liquid Provider Pipe and a Carpenter will request fluid, even if the Carpenter is full, so the fluid is wasted. (tested with water)
The Carpenter is filled by this pipe. With IC2exp machines this setup works fine.
Forestry 2.3.0.6
IC2x b288
LP b73

**Comment by AartBluestoke** [comment]
It is more that there will be a specifically sized liquid buffer which
doesn't exist in ic2. No liquid is destroyed. (worst case scenario is that
it will bounce off a full inventory if other liquid somehow ends up in
there, invalidating the request while it is on route.

On Tue, Nov 12, 2013 at 2:51 PM, Marcus Ullrich notifications@github.comwrote:

> A system of a Liquid Supplier Pipe, Liquid Provider Pipe and a Carpenter
> will request fluid, even if the Carpenter is full, so the fluid is wasted.
> (tested with water)
> The Carpenter is filled by this pipe. With IC2exp machines this setup
> works fine.
> Forestry 2.3.0.6
> IC2x b288
> LP b73
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/RS485/LogisticsPipes-Dev/issues/216
> .

## 

“Getting information off the Internet is like taking a drink from a fire
hydrant.”
_– Mitchell Kapor_

**Comment by gu471** [comment]
I think, I don't understand your comment. IC2 machines also have an internal buffer. If this is full, the Supplier Pipe stops requesting. At the Carpenter it is still requesting liquid. First the Carpenter is filled, then the pipe at the Carpenter is filled with water (inblock with the Crapenter), then the (placed) pipe Block besides the Carpenter is filled, and after this, the Pipe is still requesting water and the incoming items are animated as they where thrown to the ground, if they were normal items.

**Comment by AartBluestoke** [comment]
if you try to supply more than the internal capacity then it will overflow
and destroy the liquid; make sure that the supplier is not requesting more
than the buffer size.

if it persists, could you post a sscreenshot of your setup here so we can
see what you are doing.

finally, you if you put a sink on the source then any extra over-flow can
bounce off a full inventory, and then get sunk somewhere (like what happens
with items)

On Tue, Nov 12, 2013 at 3:25 PM, Marcus Ullrich notifications@github.comwrote:

> I think, I don't understand your comment. IC2 machines also have an
> internal buffer. If this is full, the Supplier Pipe stops requesting. At
> the Carpenter it is still requesting liquid. First the Carpenter is filled,
> then the pipe at the Carpenter is filled with water (inblock with the
> Crapenter), then the (placed) pipe Block besides the Carpenter is filled,
> and after this, the Pipe is still requesting water and the incoming items
> are animated as they where thrown to the ground, if they were normal items.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/RS485/LogisticsPipes-Dev/issues/216#issuecomment-28269264
> .

## 

“Getting information off the Internet is like taking a drink from a fire
hydrant.”
_– Mitchell Kapor_

**Comment by gu471** [comment]
The Carpenter can hold 10 Buckets, I want to keep it 1 Bucket.
After this Bucket, the pipe still requests water from the provider.

I
![2013-11-12_07 40 58](https://f.cloud.github.com/assets/2853451/1519590/0d5d2c8c-4b66-11e3-8c88-26ae3f2ce1a5.png)
![2013-11-12_07 41 16](https://f.cloud.github.com/assets/2853451/1519591/0d5e1bce-4b66-11e3-84b4-cbae1fdead96.png)
![2013-11-12_07 41 46](https://f.cloud.github.com/assets/2853451/1519592/0d5f2d8e-4b66-11e3-8753-756b4d1aa658.png)
![2013-11-12_07 42 46](https://f.cloud.github.com/assets/2853451/1519593/0d6085c6-4b66-11e3-8dff-f5efdcf6ff94.png)
![2013-11-12_07 44 23](https://f.cloud.github.com/assets/2853451/1519594/0d618764-4b66-11e3-8474-d749a0a8d09a.png)
![2013-11-12_07 41 23](https://f.cloud.github.com/assets/2853451/1519595/0d62ec12-4b66-11e3-96fb-a1ac2902bbfe.png)

**Comment by davboecki** [comment]
OK I found the problem. The carpenter doesn't return it's internal tanks when you ask for them. We could fix that with a special proxy for forestry's carpenter. Question is, if this should be consisted a forestry bug.

**Comment by gu471** [comment]
I created an issue at Forestrys bugtracking: https://bitbucket.org/sengir/forestry/issue/650/liquid-supplier-pipe-forestrys-internal

**Comment by davboecki** [comment]
If this doesn't get fixed from forestrys side, we probably should fix that from our side, at test for so long, till sengir get's time to fix this.
So i'm going to need a list of all things inside forestry, that have a tank and doesn't work with the supplier pipe, so i don't have to do this again and again.

**Comment by gu471** [comment]
Every Forestry block with a tank is affected: Analyzer, Biogas Engine, Biogenerator, Bottler, Carpenter, Fermenter, Moister an the Still.

While testing I mentioned another issue: The Forestry Analyzer can only accept liquid honey. But for example you can request water with a connected pipe to it. The Analyzer won't fill up with water, but the pipe do. So the pipe will be blocked to request other fluids. (You have to break and replace it)
It may be good, that the SupplierPipes only request fluids, if the connected machine can handle this fluid. I don't know, if the ForestryAPI have an interface for this, but if it's possible an implementaion may be great.

**Comment by bziemons** [comment]
Says resolved on the forestry side. Can you confirm that?

**Comment by AEnterprise** [comment]
to confirm it they have to implement it in LP first

**Comment by gu471** [comment]
still existing with 
forestry 2.3.0.7
and LP build 80

**Comment by AEnterprise** [comment]
you'll have to wait for at least build 81 (the next one) to confirm it, forestry added a method that enables mods to ask for liquid levels in the tank of the machine, LP now has to use them

**Comment by davboecki** [comment]
If forestry uses the standard forge method like it should, than LP don't need to update. And the update fpr forestry isn't available. The issue was closed yesterday and the forestry version 2.3.0.7 is from Nov 07. So you will have to wait to test.

**Comment by AEnterprise** [comment]
ah, cause it worked i knew one had to be updated but it is somehing added so i guessed LP had to implement it. wrong gues

**Comment by gu471** [comment]
It works with the new forestry update :)
