### ISSUE TITLE
Pipes keep exploding

### ISSUE THREAD

**Issue by AEnterprise** [RS485/LogisticsPipes#217]
I have a logistic pipe conected to a chest set to default route this works but when the chest overflows items keep stuck in the pipe until there are to many items in that pipe then it explodes but when the pipe explodes it doesn't break it just keeps exploding until you manange to get to your powersource and cut the power. But it also causes the server to kick everybody (end of stream) so you have about 3-5 seconds before you are kicked from the server again.

EDIT: it also causes to drop basic logistic pipes but the pipe that should explode and fall on the ground remains

**Comment by GUIpsp** [comment]
Intended, use itemsink modules.

**Comment by AEnterprise** [comment]
and the part that it drops extra pipes? with this i can get infinite basic pipes, i just let them explode a while and i have 2 stacks of free pipes

**Comment by AEnterprise** [comment]
could somebody relabel this? this is a valid bug, i get that it is intentional that the pipe explodes but not that it keeps exploding forever kicking people out of the game and dropping extra pipes

**Comment by Turmfalke2** [comment]
Could this be an issue with the security station protecting the pipe?

**Comment by Obbi89** [comment]
Looks like some plugin interacting. 
Can you give more information about your Setup?
Do you have Towny, Factions, WorldGuard or similar? -These often cause infinite explosions when misconfigured, even in other mods like Industrialcraft.

**Comment by AEnterprise** [comment]
nope it was on a forge server not a bukkit server. It heapened when a default route chest was full but stuff kept comming and it kept trying to place it in the chest but it was unable and it just kept exploding until i cut the power

**Comment by davboecki** [comment]
This should be fixed, because LP's items don't trigger BC's pipe explosions anymore.
