### ISSUE TITLE
Implement RF support for when Thermal Expansion 3 releases?

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#218]
https://github.com/KingLemming/CoFHLib/tree/master/cofh/api/energy

RF is Redstone Flux, the new Thermal Expansion energy system. A few mods are working on support for it and its supposed to be a nice system to work with. Just thought Logistics Pipes could be ready for it when the time comes.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes-Dev/commit/2402086c4133bcb0bf9963b9e8341e4fa41712d1
