### ISSUE TITLE
crafting and suplier module?

### ISSUE THREAD

**Issue by AEnterprise** [RS485/LogisticsPipes#219]
Almost all the logistic pipes have there equivalent in a module but not the provider and crafting pipe. Would it be possible to make those?

**Comment by GUIpsp** [comment]
Crafting module is not possible.

**Comment by ghost** [comment]
Well, it is possible. It would not work with any other modules though, making a crafting module useless.

**Comment by AEnterprise** [comment]
why wouldn't it work? and i ment suplier module not profider, sorry

**Comment by AartBluestoke** [comment]
The code only allows for 1 crafting source per pipe, some work was done
towards allowing multiple crafts per pipe and hence allowing crafting
modules, but it was never completed.

If I remember correctly it was to do with guaranteed delivery to a sub pipe
destination, and conflicts in the crafting tree. Lp goes a long way out of
its way to ensure that you can not start a craft without having all the
ingredients, and having multiple crafts at 1 location breaks the ownership
model for a request.

**Comment by AEnterprise** [comment]
alright, but would it be possible to make a pipe that combines 1 suplier and 1 crafting pipe? or do i have to keep that 2 pipes?

**Comment by AartBluestoke** [comment]
may i ask what the use case is?

if it is keeping a buffer, then it is safe to put a supplier and a provider
on the same chest, and it won't request from itself.

On Mon, Nov 18, 2013 at 7:55 PM, AEnterprise notifications@github.comwrote:

> alright, but would it be possible to make a pipe that combines 1 suplier
> and 1 crafting pipe? or do i have to keep that 2 pipes?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/RS485/LogisticsPipes-Dev/issues/219#issuecomment-28685860
> .

## 

“Getting information off the Internet is like taking a drink from a fire
hydrant.”
_– Mitchell Kapor_

**Comment by AEnterprise** [comment]
no it is to use on a logistic crafting table with IC2, to make plates you need an hammer and an ingot, one hammer has 80 uses but i don't like having it create 80 plates at once when i only need 1 or 2 so i have it set to 1 ingot is one plate and suply the hammer with a seperate suply pipe

**Comment by GUIpsp** [comment]
byproduct extraction upgrade, or have a supplier pipe on another side.

**Comment by AEnterprise** [comment]
alright i'll stick to my system with the sepeate supplier then, i think it's better not to use a byproduct extration upgrade cause it'll create extra hammers when you request multiple items at the same time then

**Comment by AEnterprise** [comment]
closing this, i got my anser so no need to have this open
