### ISSUE TITLE
Mod based sink child mod support

### ISSUE THREAD

**Issue by MrTJP** [RS485/LogisticsPipes#22]
it gets annoying when buildcraft has core, energy, silicon, etc.  This is the  same with rp2, TE, etc.  With the 9 mod limit, its hard to fit them all in.  I think the ModBased sink should check for child mods and sink those items as well.

**Comment by ArtForz** [comment]
You can put multiple modsinks in a chassi.

**Comment by MrTJP** [comment]
i understand that this is easily fixed like that.  Based on the fact that this module is more intended for new users, i dont think its as intuitive for them.  It would better serve its purpose if you can simply say which mod, and to have it sink those items.

**Comment by ArtForz** [comment]
No child mods is equally annoying, try keeping bees out of your forestry chest...

**Comment by MrTJP** [comment]
Option to include child mods, like a check box? let me whip up a PR real quick and see if you like it...

**Comment by MrTJP** [comment]
nvm, there isnt anything i could see in forge that would handle such a thing...
