### ISSUE TITLE
Request pipe doesn't show contents of barrels

### ISSUE THREAD

**Issue by Renadarain** [RS485/LogisticsPipes#220]
Hello :)

I have a sorting system using a mixture of barrels (Factorization) and chests.  Each one has a MK2 chassis with a Polymorphic module and a provider module. 

The system works great until you use a request pipe.  The items show are only those in the chests.  Nothing from the barrels show up.

Not sure if I'm doing something wrong or if it's a bug.

Edit: I forgot to say that all these pipes go into the back of the chests/barrels as they are all stacked along a wall.

Regards,
Renada

**Comment by ghost** [comment]
Try using sneaky upgrades or attaching the pipes to the bottom of the barrels.

**Comment by Renadarain** [comment]
Could you please tell me how to use sneaky pipes? I've been all over YouTube and the forums trying to find out how to do this.  I can't attach them to the bottom of the barrels as they're all stacked on top of each other and side by side.  The only free side is the back.

Thanks :)
Renada

**Comment by Flow86** [comment]
hey you can use a sneaky upgrade with the corresponding side to allow the pipe to use the "upgraded" side without being physically attached. ie:
- insert into barrel (only from up): put pipe in the back, add sneaky-upgrade-up to the pipe -> pipe can insert into barrel

**Comment by Renadarain** [comment]
Hi :)

I'm sorry I really don't understand what you mean.  Where exactly do I put the sneaky upgrade? Which pipe takes it? Would it be a satellite pipe?

Thanks :)
Renada

**Comment by AEnterprise** [comment]
make an upgrade mananger, and klick the pipe (any logistic pipe can accept upgrades) it opens an inventory, put the upgrade in there

**Comment by Renadarain** [comment]
Hi :)

Thanks for helping :)  I've done as you said but the upgrade isn't working in as much as the upgrade goes into the pipe but the request pipe still doesn't see the barrels.  I've tried with each single sneaky upgrade and tried with the combination and each one (one at a time) and then all of them together (combination top row the rest in the second row).  Putting the sneaky pipe in the MK2 Chassis first then trying it in the request pipe itself.  The request pipe just doesn't seem to see what's in the barrels.

I know I'm probably having a blonde moment but would appreciate any help.

My barrels are like so:   

---

|          |
|          |

and stacked 4 high.

EDIT: arrghhh diagram didn't show properly - the barrels are lined up 3 sides of a square and 4 high :)

Thanks :)
Renada

**Comment by AartBluestoke** [comment]
Try Placing the chassi on the bottom (out) side with a sink, provider, and
sneaky up upgrade.

I believe a provider on a barrel used to not need to be on the right side,
but that may have changed.

**Comment by Renadarain** [comment]
ahhh ok then I think I'll have to replace my barrels with chests then because the only free slot on the barrel is the back :(

Thanks for helping though :)

Regards,
Renada

**Comment by AEnterprise** [comment]
i'll test this in my test world and see if i can find a solution for you to fix this

**Comment by Flow86** [comment]
I put two sneaky upgrades in there (up and down) - then it works from the back

**Comment by Renadarain** [comment]
@AEnterprise  Thank you, I appreciate the help :)

@Flow86 Not sure how you have that set up but it didn't work on my system. Which pipe did you put your upgrades into?  All my barrels have MK2 chassis with a Polymorphic Item-Sink and Provider module.  The chest where you dump all the blocks to be sorted has a MK2 chassis with a quick-sort and item-sink module.

Thanks all :)
Renada

**Comment by AEnterprise** [comment]
you put the upgrades intro that logistic chasis pipe and it schould work

**Comment by Renadarain** [comment]
@AEnterprise  But which one? The chest where you dump everything in to be sorted or on each individual barrel chassis?

Thanks :)
Renada

**Comment by Flow86** [comment]
you have to put the upgrade into the barrel-chassis

**Comment by Renadarain** [comment]
@Flow86 Thanks :) I've tried that but no dice :(  I'll faff around on a test world for a bit and get back to you.  

I just want to thank all of you for your patience and your help, it's much appreciated :)

Regards,
Renada

**Comment by davboecki** [comment]
What version are you using?
I updated factorisation barrel support a few weaks ago.
@Flow86 Two sneaky upgrades don't work. Only if you use a sneaky cobination upgrade. Otherwise only the first upgrade counts. Sneaky upgrades are ment for input mostly. Provider pipes are supposed to be magical and work from every side on barrels automaticaly.

**Comment by Renadarain** [comment]
@davboecki Hi :)  I'm using MCPC+ 98 MC 1.6.2 LP MC1.6.2-0.7.4.dev.66 (still waiting on a couple of mods before upgrading to 1.6.4).

I did use the combination upgrade with the UP/DOWN upgrades.

Regards,
Renada

**Comment by davboecki** [comment]
http://ci.thezorro266.com/job/LogisticsPipesMC1.6.2-Dev/73/changes
So newer builds should fix your problem. These builds should still be 1.6.2 compatible.

**Comment by Renadarain** [comment]
@davboecki Ohh thank you sooooo much, 73 worked a treat without the use of any sneaky upgrades. 

Again, thank you to all of you who tried to help :)

Regards,
Renada
