### ISSUE TITLE
problems with crafting pipe

### ISSUE THREAD

**Issue by ghosty1911** [RS485/LogisticsPipes#222]
Hi
I have find a bug withe the crafting pipe.
I have bild a logistig system with a Electric furnace from the ic2 experimentals mod.
The furnace burns sand to glass and when i request 1 stack of glass its work fine but when i reqest for example 7 stacks of glass its make 6 stacks and some blocks not 7 stacks. I can see that the crafting pipe is not ready but its came no more sand to the pipe its only make all stacks whenn i put manuel the last sandblogs into the furnace.
I have test it withe a other furnance from the mekanisn mod to but the thame problem.

My logistig system config:
Chest withe basic pipes to provid the items in it
A crafting pipe withe sand as input and glass as output
A request pipe mk2 withe a chest

Version of logistig pipes
162 dev build 79

**Comment by AEnterprise** [comment]
the problem is that you probably used a crafting logistic mark I, you need a mark II or III, the pipe has an internal buffer but when that gets full it just drops the items on the ground

**Comment by ghosty1911** [comment]
i have test it with the mar II or mark III to but the thame problem!

**Comment by AEnterprise** [comment]
then u think you found a bug

**Comment by davboecki** [comment]
This has been fixed.
