### ISSUE TITLE
Ars magica 2 not giving items back

### ISSUE THREAD

**Issue by silverches** [RS485/LogisticsPipes#223]
When crafting a greater focus in a logistics request table your items disappear, except the lesser focus, if you  try to craft it but don't have the right level for crafting it. 
In a normal crafting table the items drop on the ground, and a message will be displayed, if you are unable to craft it. 
Using Ars Magica 2 1.0.2b and LP 0.7.4.dev.64

**Comment by bziemons** [comment]
Logistics Pipes does not support any special crafting that is based on the vanilla crafting system. This is not a bug and it is not planned to be included.
