### ISSUE TITLE
Liquid Provider Pipe can't pull water from iron tank(railcraft)

### ISSUE THREAD

**Issue by kghost** [RS485/LogisticsPipes#225]
I set up a simple system, where the supplier fluid pipe connected to buildcraft tank (right) requesting 3000mb water form iron tank (railcraft,left), but only 250mb water is transferred, the provider fluid pipe refuse to provide any more water.

![lp](https://f.cloud.github.com/assets/154702/1701399/9d6176f8-6056-11e3-9033-ef947395b267.png)

**Comment by kghost** [comment]
My env:

MC 1.6.4
buildcraft-A-1.6.2-4.1.2
LogisticsPipes-MC1.6.4-0.7.4.dev.79
Railcraft_1.6.2-8.2.0.0

**Comment by kghost** [comment]
I can check the tank current water volume by using a request pipe, so the iron tank is reporting the correct volume.

**Comment by kghost** [comment]
Checked in railcraft, the iron tank has a flow limit of 250mb/tick (https://github.com/CovertJaguar/Railcraft-IssueTracker/issues/112)

is there any method to let LP drain fluid that way ?

**Comment by Distorti0n** [comment]
I've come across the same problem. The work around i have come up with is to use a single Buildcraft tank as a buffer between the Railcraft tank valve and the provider pipe. You can use a standard emerald or wooden fluid pipe to fill the Buildcraft tank.

**Comment by davboecki** [comment]
Should be fixed inside newer builds.
