### ISSUE TITLE
Logistics Item Card has wrong ID&texture [dev78, dev80]

### ISSUE THREAD

**Issue by NoX-programer** [RS485/LogisticsPipes#228]
I have I:logisticItemCard.id=6869 in config of server and client, but there is no ID 6869 in game, but it is Logistics Item Card with ID 7125 and it has Nano Hopper texture o_O.
However it even can be placed into Log Inv Sys Connector, but texture and ID...
By the way it is correctly registers (with wrong ID) on client and server:
[FINE] [fml.ItemTracker] Adding item logisticspipes.items.LogisticsItemCard(7125) owned by LogisticsPipes|Main

upd: it is actually ALL item (not solid) IDs are not match the config.

**Comment by davboecki** [comment]
For the shifted ID, that's just minecrafts standard 256 ID shifting. For the textures: We havn't found out what the problem is. It seems to be random in larger mod packs, but the cause of this is unknown and hard to identify. Nothing we can do about that, sorry.

**Comment by NoX-programer** [comment]
You're absolutely right: it was mod_macros_0.9.10_for_1.6.2 broke some textures of your mod. Why textures of only that items?
Logistics Broken Item
Upgrade Manager
Logistics Item Card
Logistics Disk
Network monitor
Crafting Sign Creator

Why only textures of LP? Seems to be I'll never know...
