### ISSUE TITLE
Integration with ExtraCells Fluid Interface

### ISSUE THREAD

**Issue by ruifung** [RS485/LogisticsPipes#233]
It would be nice to have similar integration with Liquid Provider Pipes and the ExtraCells Fluid Interface as with the regular AE Interface and Providers. 

Pretty sure it has to be done on both sides.
https://github.com/M3gaFr3ak/ExtraCells/issues/116

**Comment by M3gaFr3ak** [comment]
I think I have to implement that, using the LP api (kinda)

https://github.com/RS485/LogisticsPipes-Dev/issues/250

**Comment by davboecki** [comment]
See #250.
