### ISSUE TITLE
Ticking tile entity

### ISSUE THREAD

**Issue by mazen** [RS485/LogisticsPipes#236]
Not sure if this is related to LP or TE, but i get a ticking tile entity crash using both.

See TE bugtracker: https://code.google.com/p/thermalexpansion/issues/detail?id=596&thanks=596&ts=1388219339

**Comment by AEnterprise** [comment]
looks like an lp bug, it crashes when trying to insert intro the top

**Comment by bziemons** [comment]
Our TE Api needs an update

**Comment by davboecki** [comment]
Should be fixed.
