### ISSUE TITLE
LP corrupting world save

### ISSUE THREAD

**Issue by AEnterprise** [RS485/LogisticsPipes#237]
when lp tries to put stuff intro the last free slot of a chest at the same time you are putting another item there causes a crash

https://gist.github.com/AEnterprise/8158596

also the world save is corrupted, the region files are intact but minecraft doesn't recognize it anymore as a minecraft save, reverting to a backup and replacing the region files with the ones from afther the crash fixes it

**Comment by GUIpsp** [comment]
Update lp.
