### ISSUE TITLE
item detector pipe

### ISSUE THREAD

**Issue by Goten87** [RS485/LogisticsPipes#24]
well i have the idear of a pipe that can count what item go true it
and then dump it in a file or with the FE mod in a database
so we can see how many items we mined

ps can also be with a computer count with CC if that nicer

**Comment by ghost** [comment]
I thing I understand what you want, but lets make it simpler.

Instead of writing to a file everytime an item passes through and recording item data, why not just make the pipe emit a redstone signal? Basically have a pipe that is the poor man's version of the RP2 item detector.

**Comment by davboecki** [comment]
Can't that be handled trough a gate condition?
