### ISSUE TITLE
IDeepStorageUnit interface implementation

### ISSUE THREAD

**Issue by Nargon** [RS485/LogisticsPipes#241]
Hello, can you add support for Interface IDeepStorageUnit from MineFactory Reloaded API: http://www.minecraftforum.net/topic/2016680-
I want to use Logistic pipes and Barrels from Jabba: http://www.minecraftforum.net/topic/2182366- This barrels use IDeepStorageUnit, but in Request Logistic Pipe i see only one stack of items from this barrel.

Applied Energetics shows correct number of items from this barrels.

Thanks for positive reaction.

**Comment by davboecki** [comment]
We already support the IDeepStorageUnit, but only if MineFactoryReloaded is installed itself. Probably gonna need a workaround for that.

**Comment by M3gaFr3ak** [comment]
@davboecki you could use Class.of("") to find the thing, jsut look if the interface exists ;)
