### ISSUE TITLE
Crash with latest version of cofh Thermal Expansion 3.0.0.0 and 0.7.4.DEV.80

### ISSUE THREAD

**Issue by llaughlin** [RS485/LogisticsPipes#242]
http://pastebin.com/hpRf4gX5

This is happening on TE3 machines (tested so far: Pulverizer, Redstone Furnace) after the Thermal Expansion 3.0.0.0 update. I'm running Logistics Pipes 0.7.4.DEV.80 on Resonant Rise 2.5.5.1.

**Comment by davboecki** [comment]
Just Update LP.
