### ISSUE TITLE
Logistics Request Table inventory should be accessible with a Provider module to the LP network.

### ISSUE THREAD

**Issue by sircrimer** [RS485/LogisticsPipes#248]
When crafting items the table should incorporate its own inventory for a crafting request.

**Comment by GUIpsp** [comment]
Give some really good arguments for this please.

**Comment by AartBluestoke** [comment]
The space in the lrt is so that it can craft complex things without a
buffer. A better but fix would be for the table to use items in its
inventory for crafting without ordering replacements, but that would stop
it being used as a buffer, with enough items for 16 crafts preloaded.

**Comment by sircrimer** [comment]
I like to automate a lot, but not all of my crafting. As i have a lot of fun crafting mashines with the LRT.  It just bothered me that i had to close the LRT gui, deposit a crafted item into my storage, then open the LRT gui again. Im not sure if making the inventory accesible by  provider pipe is the correct thing to do here. Maybe just add a slot that autoejects items that get placed into it into the network.

**Comment by ruifung** [comment]
@sircrimer Doesn't the table already have a slot that autoejects items in to the network? The slot with a X ?
@AartBluestoke I agree the table should take into consideration what items it has in its inventory when ordering. - But maybe have a button to toggle it to get around the issue you mentioned?

**Comment by sircrimer** [comment]
Oh i didnt know that. That resolves my issue.
