### ISSUE TITLE
Logistics Request Table improvements.

### ISSUE THREAD

**Issue by ruifung** [RS485/LogisticsPipes#249]
The Mechanist's workbench from ThermalExpansion has this nifty feature where recipes can be set using NEI. Can it be added to the Logistics Request Table?
1. To make space for NEI, the request portion of the GUI could be hidden with a toggle? It would hide NEI when the request side is open and vice versa.
2. If for some reason, using NEI to set recipes is decided against, could NEI recipe overlay support be added at least?
3. The deposit to network slot is not exactly clearly marked, Maybe put a label on it? There is a lot of UI space to use after all.
4. Allow for shift clicking between the table inventory and player inventory? Also shift clicking to craft should behave like vanilla crafting.

**Comment by davboecki** [comment]
Added everything except 4. Because that would require a Lot of code In combination with the dummySlots. But hopefully that will come sometimes. But that's a dublicate of https://github.com/RS485/LogisticsPipes-Dev/issues/207.
