### ISSUE TITLE
Mac keyboard "delete" key not working

### ISSUE THREAD

**Issue by plusparth** [RS485/LogisticsPipes#251]
In the logistics crafting table, my delete key is not working. On the mac keyboard, the delete key is backspace. If I press fn+delete, which does the equivalent of a windows delete key, it does what the windows delete key should - delete chars in front of the cursor.

**Comment by davboecki** [comment]
Does anybody know the keycode for the delete key on a mac. I don't own a mac so I can't test it. Without the keycode I don't have a chance to fix that bug. So if anybody knows I would be able to fix this without I can't.

**Comment by jeffreykog** [comment]
For me, on mac, 51 is backspace, 117 is fn + backspace (delete)

**Comment by plusparth** [comment]
This did not work for me. I did update to the latest build of Logistics Pipes.
EDIT: Maybe you could ask someone like Chickenbones about what he does for NEI.

**Comment by zostay** [comment]
A work around that works for me until this is fixed is to right click in the search box to clear it, which is usually faster than backspace would be anyway.

**Comment by davboecki** [comment]
Should now be fixed.
