### ISSUE TITLE
Enhancement: Console Configuration for Pipes and Meta Ignore Mode

### ISSUE THREAD

**Issue by mikeloeven** [RS485/LogisticsPipes#256]
I was wondering if you could add advanced functionality for the supplier pipes that gives you a console where you enter a list of blockid's as an alternative to the gui. this would allow configuration of the sorting without having to physically possess the block your trying to configure.

additionally there is an amazing feature in the TE item ducts that you may consider borrowing. the ability to ignore metadata and NBT data. this is very useful when dealing with wood since you can allow the pipe to accept any type of wood just by loading in an oak log. and the same applies to any block with massive variations that don't really effect crafting

**Comment by AartBluestoke** [comment]
a fuzzy item sink ignores nbt/metadata.

**Comment by davboecki** [comment]
You can use ComputerCraft and a Request pipe to request a list of item Id's.
