### ISSUE TITLE
[Bug} Data not cleared on pipe-break.

### ISSUE THREAD

**Issue by Sakata-MC** [RS485/LogisticsPipes#257]
Seems that broken pipe's information is not being cleared.
Satellites are the easiest to show this with. Get a pipe, set its ID, then some time later, break the pipe and replace it, and the broken Satellite ID can't be re-used.
Also seems to be affecting other pipes -- crafting not forgetting requests when broken (serious PITA when servers restart), and such.

**Comment by davboecki** [comment]
Could you post a full FML log and a list of all mods involved?
