### ISSUE TITLE
[Suggestion] Throttle pipes/modules, BC broke(removed) pipe.maxitems

### ISSUE THREAD

**Issue by Sakata-MC** [RS485/LogisticsPipes#258]
This seriously hoses Extractor MK3 cards, and Provider MK2's.
Pipes are now very explody.  There appears to be a hard-coded limit now, instead of a user-configurable option.

**Comment by Silwing** [comment]
I also ran into this problem with exploding pipes. However I just realized that my system was poorly setup, so everything was requested forwards and backwards constantly.

I have used an Extractor MK3 for a while without running into trouble with exploding pipes.
