### ISSUE TITLE
[Suggestion] Throttle based on what's in-between pipes?

### ISSUE THREAD

**Issue by Sakata-MC** [RS485/LogisticsPipes#259]
TE tesseracts have broken LP in another way.  In conjunction with BC removing the config for pipe.maxitems, TE tesseracts now eject items super-slowly.

This will invariably lead to exploded pipes on the tesseract exit side on large orders, or orders with a moderate to large number of sub-item iterations, as when the items appear on the other side of the tesseract, they are slowed to a crawl -- which leads to a ton of items being in the pipe at one time.

Even a moderate order, like ordering a stack of BC tanks, generally explodes pipes when a provider MK2 is used.

**Comment by ghost** [comment]
Tesseracts shouldn't rate limit all that much, they should be able to send a stack per tick. Try placing the tesseract directly onto an inventory?

**Comment by Sakata-MC** [comment]
The issue is not the tesseract throttle, it's the tesseract resetting the
speed. And connecting the tesseract to an inventory defeats the purpose of
having l.p. being able to network through one.

This message was sent via phone. Please excuse any typos, as my phone loves
to 'autocorrect' to the wrong words.

**Comment by davboecki** [comment]
Could you check if the newest commit did the trick?

**Comment by Sakata-MC** [comment]
I'll check it out soon.  have to wait for 'patch day'  :D

**Comment by davboecki** [comment]
LP routed items shoudln't trigger BC's exploding pipes anymore.
