### ISSUE TITLE
[BUG]Supplier pipe or crafting

### ISSUE THREAD

**Issue by kid101000110** [RS485/LogisticsPipes#260]
Hey guys I am automating lzh condensator cooling and I set up an LP system with an auto crafting table and all. When I use a request pipe to request the lzh with 0 durability to be crafted with 3 lapis to bring it to full durability, it works fine. But when I have a supplier pipe set to supply full lzh's the supply pipe doesnt request them. I tried the same system with furnaces and it works. 
![2014-01-29_14 55 59](https://f.cloud.github.com/assets/6544754/2040390/aac9ea36-89b5-11e3-8682-bfcebd03e33f.png)

**Comment by davboecki** [comment]
The probelm is probably, that when you set up the supplyer pipe with the lzh, It has different settings than the one programmed in the crafting pipe. Try using the same result lzh to set up the supplier pipe and the crafting pipe result slot.

**Comment by kid101000110** [comment]
Nope the lzh had the exact same damage values I triple checked everything

**Comment by davboecki** [comment]
You know that there are also NBT values? They can also be different.
