### ISSUE TITLE
Issues with Forestry

### ISSUE THREAD

**Issue by vmsh0** [RS485/LogisticsPipes#263]
Hello,
I was not able to get the Liquid Supplier Pipe working with a Forestry Still and a normal Supplier Pipe to provide Saplings to a Fermenter.
The Liquid Supplier Pipe only provides 100mB of liquid to the machine whichever is the quantity of liquid to supply I select in the GUI.
The Supplier Pipe seems to only work sometimes, and sometimes stops working randomly.

**Comment by davboecki** [comment]
You probably need to update your forestry version. What tank is the liquid comming from?

**Comment by vmsh0** [comment]
The liquid is coming from a Railcraft Iron Tank. The saplings are coming from a Diamond Chest (from the Iron Chest mod).
Forestry is updated to the last version.

**Comment by davboecki** [comment]
Update LP to the newest build. That should fix RailCraft tank support.

**Comment by vmsh0** [comment]
Ok, it is fixed.
The problem with the saplings is still there :(
Here's a screenshot with my pipes configuration, in case I am doing something wrong.
![screenshot 2014-02-06 17 04 03](https://f.cloud.github.com/assets/1955497/2100565/eaccc7f4-8f49-11e3-872b-5914e37b5019.png)

**Comment by vmsh0** [comment]
I'm sorry, I just noticed that Forestry has got his own ID for saplings, to implement all the genetics thing, and as I built that map in creative, I just put a vanilla sapling into the supplier from the creative inventory.
Thank you very much for your help!

**Comment by davboecki** [comment]
Glad I could help.
By the  way, nice pic. :-)
