### ISSUE TITLE
Supplier pipe requesting WAY more items than needed

### ISSUE THREAD

**Issue by Cabu** [RS485/LogisticsPipes#264]
I have a supplier pipe in Infinite mode to fill a buffer chest of crafted items. But when it trigger to refill 4 or 5 stacks, the pipe request 2000-3000 more items than really needed :/ It is particularly visible with slow crafting (eg: metal former without boosts)
Is it possible for the supplier pipe to only request some more items only if the previous request is fulfilled?

**Comment by AEnterprise** [comment]
you set it to infinite mode, so it requests all it can, if you want it to only keep 4 or 5 stacks, put 4 or 5 stacks in the pipe and put it on either partial, bulk50 or bulk100

**Comment by AartBluestoke** [comment]
Infinite refill should still respect space constraints, like all deliveries.
Space is reserved on send, and should be checked before any send. The
exception is links which takes over 5(iirc) seconds to deliver, they time
out and release their space reservation, allowing more to be sent in the
case of a dropped item, or other exceptional conditions.

**Comment by Silwing** [comment]
It might be possible to "fix" this by adding a dynamic "reservation time" in the supplier pipe GUI, so that suppliers for request that might take a long time can have the reservation time bumped up to a higher value.

**Comment by davboecki** [comment]
This should be fixed in the newest build.
