### ISSUE TITLE
[Bug] [IC2] EnergyNet.addTileEntity: (spam)

### ISSUE THREAD

**Issue by Maokuma** [RS485/LogisticsPipes#268]
Using latest LogisticPipes dev.106 and updating from dev.102. on a server. The forgemModLoader log gives me a constant spam of 5 worldleaks, spamming the console with a variation of from both versions:
[WARNING] [IC2] EnergyNet.addTileEntity: logisticspipes.blocks.powertile.LogisticsPowerJunctionTileEntity@3cce4dab (logisticspipes.blocks.powertile.LogisticsPowerJunctionTileEntity@3cce4dab) is conflicting with logisticspipes.blocks.powertile.LogisticsPowerJunctionTileEntity@c4d34bd using the same position (already added, prev. te not removed, overlapping), aborting

And:
[IC2] EnergyNet.removeTileEntity: logisticspipes.blocks.powertile.LogisticsPowerJunctionTileEntity@50447132 (logisticspipes.blocks.powertile.LogisticsPowerJunctionTileEntity@50447132) wasn't found (added), skipping

Until server dies. ID'n are tripelcheckt and not overlapping in config. And the pipes works fine ingame on server. Ive tried to update IC2 to latest dev to no vail.

/Thanks for your hard work on this awesome mod

**Comment by Maokuma** [comment]
Pastbin of server errors: http://pastebin.com/KivN9vYv
LogisticsPipes-Request log wile server was running: http://pastebin.com/N4eQ0uKv

**Comment by davboecki** [comment]
What happens, if you switch back to the LP version 102 ?

**Comment by Maokuma** [comment]
(edited due to misinformation)
Also, "greater powers forbidden" I removed your mod (dev.106) and the memory leaks were gone. Just some minor ticket bombs from Mekaniks and Buildcraft. And a broken machine from Forestry. I did remove these issues to see if Logistics pipes changed.

**Comment by davboecki** [comment]
If you could track down the build number where this problem happens the first time, that would realy be helpfull because I have no idea what change can possibly Introduce this problem.

**Comment by Maokuma** [comment]
I am puzzled to what the conflict could be. Due to the problems taking ages to appear in dev.102 I missed it and its there. Also best way to trigger the errors is to log into, run around in pipe area, and log out from the game. I guess it has with passive chunk-loading to do and I'll try different things.
Forgot to mention that the server is started from a clean state with dev.102.

/I really hope I am not wasting your time, so I'll continue to test and pinpoint it.

**Comment by davboecki** [comment]
Are you using a clean Forge build, or is MCPC or something similar involved?
What IC2 version do you use?

**Comment by Maokuma** [comment]
Forge universal build 965 with MyMcAdmin.
IC2 version 389 updated yesterday to test.

**Comment by Maokuma** [comment]
It took a wile to find the error and the server runs fine now!
A combination Chicken Chunks 1.3.3.3 and logistic pipes trigged the leak/spam.
This error was solved in Chicken Chunks 1.3.3.4. For those who need it, my working combination of mods is as follows:
Logistic pipes 108
Industrialcraft (IC2) 397
Chicken Chunks 1.3.3.4
CodeChickenCore 0.9.0.9

/Thanks again for the hard work on Logistic pipes and support!
