### ISSUE TITLE
Satellite pipe not connecting

### ISSUE THREAD

**Issue by Turmfalke2** [RS485/LogisticsPipes#269]
hi,
I have satellite that sometimes lose it's connection to the rest of the network.
http://ibin.co/1CDOs3Fc5r2C
The network monitor shows for this pipe a routing table of size 1, while the pipe above it has one of ~700. A right click with an empty hand on the pipe above it shows that it is aware of the pipe below it. The same with the satellite pipe shows no routes.

This is on a server with mcpc+ and tons of mods. This is with LP in version .104, the machine the pipe is attached to is from mekansim 6.0.0.233 (don't see how that matters).

The interesting thing is, this is the 2th time this has happened with this satellite pipe. It never happened with any of the other 24 satellite pipes.

**Comment by davboecki** [comment]
Could you replace the pipe above the satelite pipe with a normal cobblestone or stone pipe, and see if this problem happens again?
