### ISSUE TITLE
BeeSink Module causes items to bounce when drone slot of apiary is filled

### ISSUE THREAD

**Issue by Jean0** [RS485/LogisticsPipes#27]
I have an apiarist chest with analyzed drones and attached a chassis with an extractor and drone terminus module. This has piping to a chassis with a BeeSink module with Any Bees selected on top of an apiary. The first bee fills the drone slot, but the extractor module keeps extracting bees which go to the chassis near the apiary and then bounces back to the apiarist chest.(in dev 332)

**Comment by AartBluestoke** [comment]
is this with the newest main? - extractors and qsorts not over-stuffing inventories was recently fixed?

**Comment by Jean0** [comment]
I haven't tested main release yet but so far it happened in dev 332 and dev 321 after setting this up. For regular items, I use an input buffer for my furnace which uses a similar layout but with an extractor and itemsink with defaut route in the chasis on the chest and a chasis with itemsink with default route on the furnace. which works fine with overloaded items going back to the input buffer and staying there until there is space for an item.

Maybe it's a problem with the apiary as the queen slots and output slots might be mistaken as free inventory

**Comment by AartBluestoke** [comment]
latest main is about dev 297, no reason to check. since then extractors
only send when the sink reports free space.

On Mon, Mar 4, 2013 at 7:19 PM, Jean0 notifications@github.com wrote:

> I haven't tested main release yet but so far it happened in dev 332 and
> dev 321 after setting this up. For regular items, I use an input buffer for
> my furnace which uses a similar layout but with an extractor and itemsink
> with defaut route in the chasis on the chest and a chasis with itemsink
> with default route on the furnace. which works fine with overloaded items
> going back to the input buffer and staying there until there is space for
> an item.
> 
> Maybe it's a problem with the apiary as the queen slots and output slots
> might be mistaken as free inventory
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/RS485/LogisticsPipes-Dev/issues/27#issuecomment-14371144
> .

## 

“Getting information off the Internet is like taking a drink from a fire
hydrant.”
_– Mitchell Kapor_
