### ISSUE TITLE
Oredict issue with JABBA

### ISSUE THREAD

**Issue by jztech101** [RS485/LogisticsPipes#270]
Currently, the JABBA barrels are set up so that when you insert say IC2 copper into a barrel, it allows all the other types of copper into the same barrel. However the polymorphic item sink does not recognize this and chooses to send any other type of copper else where. profmobius has suggested to implement ore-dict integration into the polymorphic item sink module.

**Comment by davboecki** [comment]
I will see what I can do. Probably a special support for the JABBA barrel, To check for OreDict Itemtypes.

**Comment by AartBluestoke** [comment]
polymorphic +oredict should trivially work? the sink is only a destination for items that it thinks it can actually sink (ie, the hasSpace calc shows enough for everything in flight, and the new items) so for items which contain Copper A, it will be "interested in" all copper types, but the space check will fail unless the inventory lets it be sunk -- that would also mean that you could easily do "chest of any type of copper". But a standard barrel would go "i'm interested in it, but i can't sink it"

**Comment by jztech101** [comment]
I suggest automatic ore-dict unification, but thats just me.

**Comment by davboecki** [comment]
You mean an extra pipe for that?
Or treat every of the same oreDict value the same?
Or every item that enters LP will be convertet into the first oreDict item of the same type.
(I don't really like either of the above, maybe the first one but aren't there already machines on some mods that can do that?)

**Comment by jztech101** [comment]
I mean like a new module - perhaps polymorphic Mk.2? or a config option within the module? So that every item that enters that pipe immediately gets converted to the oredict of that item. So if were were dealing with copper here, the module would essentially the actively tell the system, "I can accept all types of copper", and then unificate the copper as they enter pipe to the copper in the inventory it is hooked up too. (Then inserting it into the inventory)

**Comment by AartBluestoke** [comment]
Sounds like a good idea for polymorphic mk 2

**Comment by Shirkit** [comment]
Why not use a Chasis pipe with a OreDict Module?

**Comment by jztech101** [comment]
Because when you have 200 barrels, that gets ANNOYING

**Comment by Shirkit** [comment]
You do it once or there could exist a tool to automatically import into Baisc Logistics Pipe or the ItemSink module to do that for you.

**Comment by AartBluestoke** [comment]
You would only need to setup things that need ore dict conversion. 1
copper, tin, etc. The rest would be handled by polymorphic sinks. Only 20
Manuel things isn't too bad.

**Comment by jztech101** [comment]
Until you have GregTech.

**Comment by Sakata-MC** [comment]
Problem there is if gregtech is installed the person is automatically assuming some expectations.
- Gregtech tends to like extra steps and slowing automation down. (unless his view has has changed)
- Installing Gregtech generally voids any support due to his messing with oredict/etc incorrectly - just like optifine generally removes ability to gain support with any mod.

On the other hand, I would like to see the oredict handled more gracefully.  So far though, no mod that I've seen that does automagic crafting can handle this.  Imagine it would end up causing huge overhead since for each recipe it would have to iterate through the whole dictionary to check for supply on each request/iteration.  That is a considerable amount of time in processing.

**Comment by AartBluestoke** [comment]
The extra cost of checking the full dictionary is minimal in lp as we keep
a global list of available item types, so if no one can offer it, we don't
even bother searching for a supplier for the item.

**Comment by davboecki** [comment]
LP now respects that barrels can accept several type of items (Oredict).
