### ISSUE TITLE
DW20 Logi pipes crash

### ISSUE THREAD

**Issue by jadedcat** [RS485/LogisticsPipes#271]
http://forum.feed-the-beast.com/threads/direwolf-20-1-6-4-public-beta.35476/page-63#post-553412

A lot of the users of DW20 seem to be getting crashes similar to this with various machines. 

Modlist for DW20 1.0.14 : https://feedthebeast.atlassian.net/wiki/display/PML/Direwolf20+%281.6.x%29+1.0.14

I am guessing this is a cross mod error but I am unable to pin down where the problem is.

**Comment by AEnterprise** [comment]
known bug, already fixed

for the users with the problem: replace the region files with region files from a backup, otherwise try to find the corrupt file and delete it

**Comment by davboecki** [comment]
@AEnterprise So it was an invtweak mod bug ?

**Comment by jadedcat** [comment]
What do I need to update in the packs to resolve this?

**Comment by GUIpsp** [comment]
I don't see anything in the recent commit logs that could have fixed this on lp's side.

**Comment by davboecki** [comment]
I don't think that that is even an LP bug. Looks more like InvTweaks is not checking the size of the Container.

**Comment by jadedcat** [comment]
So something I need to talk to InvTweaks about then?

**Comment by GUIpsp** [comment]
Yup, looks like it. :)

**Comment by AEnterprise** [comment]
@davboecki i had the same thing heapen to me several times until i updated LP, not sure about the version that fixed it but it doesn't heapen anymore for me
