### ISSUE TITLE
Crash with CC1.6

### ISSUE THREAD

**Issue by jztech101** [RS485/LogisticsPipes#272]
https://www.dropbox.com/s/t0wdlyqbvf6ppo0/GTCrash.txt - Crashing upon worldgen. Greg is busy telling me that the NPE is on yourside for a null check. ._.

**Comment by davboecki** [comment]
The real problem is java.lang.ClassNotFoundException: dan200.computer.shared.TileEntityComputer
Untill CC 1.6 is released I can't change that.
