### ISSUE TITLE
Quick sort module crash

### ISSUE THREAD

**Issue by Zimon88** [RS485/LogisticsPipes#277]
http://pastebin.com/wJEHpv8k

i play DW20 1.0.17 mod pack

I have connected chassi pipe to ME interface with quick sort module. When pipe try pull item from ME network to LP network game crash

**Comment by davboecki** [comment]
That looks like an error in the ME interface, becaue LP ask's the Me interface what items are there and how much, and when LP asks to get them the ME interface returns null for some reason.

**Comment by miuirussia** [comment]
Need try catch

**Comment by davboecki** [comment]
No this doesn't need a try catch. It is/was a problem on the AE side.

**Comment by miuirussia** [comment]
But minecraft crash, if you do this without try … catch
25 àïð. 2014 ã., â 22:15, davboecki notifications@github.com íàïèñàë(à):

**Comment by bziemons** [comment]
@miuirussia But you know that if there are actually errors in a code, an Exception is thrown exactly because of that and it's intended behavior?
