### ISSUE TITLE
Apiary Refiller not working

### ISSUE THREAD

**Issue by dewdkorn6969** [RS485/LogisticsPipes#280]
have tried numerous different methods of using the apiary refiller and cant get it to work.. tried using a couple of different versions of forestry.. created a test world with nothing but forestry, buildcraft and logistic pipes and it still doesnt work.. 

As i understand it the module is supposed to work by just placing it into a chassis pipe attached to the apiary and put two purebred bees (1 drone and 1 princess of the same type) into the apiary and let them breed.. the module is supposed to automatically extract the combs and other products as well as the drones and princesses after the queen dies and instantly reinsert 1 princess and 1 drone while the rest get inserted into the logistic system to be routed(provided you have a default or higher route for the bees and stuff to go).. but it appears as tho something isnt working.. no log messages or anything

**Comment by Unknown-Zombie** [comment]
Same problem here. Using Forestry 2.3.1.1, Binnie Mods 1.8.0, and Logistics Pipes 0.7.4.dev.121.

Placing the chassis pipe on any side of the apiary, or using any sneaky upgrades makes no difference.
