### ISSUE TITLE
Fluid Provider Pipe not working correctly [0.7.4.dev.102]

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#283]
Placing a Fluid Provider Pipe on a valve of a steel / iron tank makes it malfunction. The pipe seems to fill up with fluid, but not send out any containers. It also doesn't seem to handle requests.

![2014-03-06_19 19 08](https://f.cloud.github.com/assets/6491055/2348762/ebc8ae34-a55b-11e3-90e9-791a8eb9d9a8.png)

**Comment by Obbi89** [comment]
Which one are you refering to?
As far as I know, you cannot drain fluids from the bottom layer, even though Railcraft-Wiki states otherwise.
I currently use this Setup with Basic Fluid Pipe and Valve on top and Provider Pipe on the side of the Tank to drain fluids.

**Comment by ghost** [comment]
@Obbi89 Can't you use the valves on the bottom just like you can with fluiducts? The Thermal Expansion Fluiducts drain and distribute the liquid just fine. Whilst the Provider Pipe just fills up with fluid and does nothing.

**Comment by samtrion** [comment]
Same problem for me. (Version 0.7.4.dev.108)
To fix this, i must place a openblocks or ThermalExpansion tank between Railcraft Valve and Fluid Provider Pipe.

**Comment by davboecki** [comment]
Could you retest what happens in dev build 134.

**Comment by samtrion** [comment]
Problem still there in dev build 134.

**Comment by davboecki** [comment]
OK. This is now fixed.
As a sidenode. You will need to put the provider pipe on the side of the tank as railcraft doesn't allow us to drain from the bottem or any other sidelevel than the bottom level.
