### ISSUE TITLE
Logistics Pipes not working with Forge Multipart

### ISSUE THREAD

**Issue by SisterJacq** [RS485/LogisticsPipes#286]
Like the title said, I am currently using the latest versions, LP v0.7.4.113 and FMP v1.0.0.250. I know it used to work, maybe updating FMP broke it.

**Comment by davboecki** [comment]
It NEVER worked with FMP. Only BC facades.

**Comment by SisterJacq** [comment]
Oh, I thought I saw Direwolf use FMP, than again my memory is crap.

**Comment by davboecki** [comment]
He used facades.

**Comment by SisterJacq** [comment]
Oh, well, I'm in trouble for using a Marble and Basalt Workshop :P

**Comment by AEnterprise** [comment]
he used facades but it is possible he said covers, he sometimes mixes them up
