### ISSUE TITLE
Unable to Start MC1.6.2-0.7.4.dev.102 and 113

### ISSUE THREAD

**Issue by mvanderlee** [RS485/LogisticsPipes#287]
when trying to start the mod on a server the following error occurs

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen

Running  FTB Direwolf20 1.6.4. (LogisticsPipes-MC1.6.4-0.7.4.dev.102)
Also tried with last jenkins build http://ci.thezorro266.com/job/LogisticsPipes-Dev/113/

full crash log
http://pastebin.com/109BpNFg

**Comment by davboecki** [comment]
Since when is inv tweaks needed on a server?
Could you try to start without it.

**Comment by loordgek** [comment]
inv tweaks is a client side mod

**Comment by mvanderlee** [comment]
Without works fine. I'll open a ticket with FTB since it doesn't belong on the server.
