### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by DanielBo** [RS485/LogisticsPipes#288]
Bug Type:  Type? i could use an enum with valid types, but for now its just an Exception which Minecraft throws  Bug Description  i was building an engine block with electrical engines, wooden conductive pipes, golden conductivepipes within a netherbrick building.  Log Crash Or Picture / Demonstration of The Bug:  These are 2 Crash reports, both with the same world. First report is while running on a root, 2nd is running on local system as singleplayer.  http://pastebin.com/DJUxEWPq http://pastebin.com/Y26A5rCb  Any Extra Mods Installed: Buildcraft Version: Forge Version:  the three points above should be incluceded within the pastebins.

**Comment by davboecki** [comment]
This is MC 1.5.2. I'm sorry but there woun't be any bug fixes for MC 1.5.2 anymore.
