### ISSUE TITLE
Unable To Startup Server Had To Disable And It Work Crashlog down below

### ISSUE THREAD

**Issue by GnomesStalkChildren** [RS485/LogisticsPipes#290]
https://www.dropbox.com/s/fvhhcn87zj9je9x/crash-2014-03-20_12.50.57-server.txt it was basically crashing every time i started up the server

**Comment by davboecki** [comment]
This is realy bad because it tells that there is an error when it trys to generate another error message. And the error is actualy inside the minecraft part of that. I have no idea what's going on.

**Comment by davboecki** [comment]
However this has happend, It shoudn't happen anymore.
