### ISSUE TITLE
TE Pipe T junctions and LP

### ISSUE THREAD

**Issue by ElgarL** [RS485/LogisticsPipes#293]
It seems any TE pipe intersection requires a Basic LP as items will bounce out of the system and thrown on the floor if items enter the system by any other method than some kind of LP insertion.

Feeding a redstone furnace with a Basic pipe set to accept resin and wood.
connected to that pipe is a TE duct going to a T section. No other pipes are used.
If items reach the basic pipe but are not accepted they are ejected from the network onto the floor.
It seems like the TE pipes ask the LP pipe if it's a valid destination for the item and gets an always yes. When the item reaches that point the LP pipe tries to bounce the item back but is rejected by the TE pipe and the item is ejected to the floor.
If you replace the T junction with another basic pipe the network is happy and bounced items stay in the network till there is a valid destination.

**Comment by davboecki** [comment]
Could you retest this with dev build 134?
