### ISSUE TITLE
TE to LP inserted via TE method ejects to floor.

### ISSUE THREAD

**Issue by ElgarL** [RS485/LogisticsPipes#294]
Pulling items from a farm with a TE pipe + pneumatic servo into a run of TE pipe.
Items have no valid destination, so TE is waiting to pull the items.

Connect an LP power module to the TE pipe with a basic LP.

TE will start pulling items and sending them to the LP pipe as it's seen as a valid destination.

When the items get to the LP module they are rejected and LP tries to reinsert the items back into the TE pipe run.
The TE pipe rejects them and all items and spilled on the floor.

**Comment by AartBluestoke** [comment]
Shouldn't rejected items get default routed? We ask any inventory 'can you
store this' before trying to sink. Items are only routed to inventories
which answer 'yes, I have room for that' Do you have a default route?

**Comment by ElgarL** [comment]
In this test there was no default route else the items would have had a valid destination and invalidate the test.

If the network is all TE ducts the pneumatics don't pull items unless there is somewhere valid for them to go.
Adding a single basic pipe allows TE to pull items even though there is still nowhere for them to go. LP is telling TE it's a valid destination until the items get to the LP and it spits them on the floor.

In an all TE duct network if a pneumatic pulls an item and it gets rejected at the receiving end it's bounced back to the sending point (or closest) and blocks the duct until there is somewhere for that item to go. LP is alwasy saying it's a valid destination.

**Comment by davboecki** [comment]
Could you retest this with dev build 134?
