### ISSUE TITLE
Ticking tile entity [gregtechmod]

### ISSUE THREAD

**Issue by CAJIO** [RS485/LogisticsPipes#30]
Description: Ticking tile entity

java.lang.NoClassDefFoundError: gregtechmod/api/IDigitalChest
    at logisticspipes.proxy.specialinventoryhandler.DigitalChestHandler.isType(DigitalChestHandler.java:38)
    at logisticspipes.utils.InventoryUtilFactory.getUtilForInv(InventoryUtilFactory.java:44)
    at logisticspipes.utils.InventoryUtilFactory.getHidingInventoryUtil(InventoryUtilFactory.java:56)
    at logisticspipes.pipes.PipeItemsProviderLogistics.getAdaptedInventoryUtil(PipeItemsProviderLogistics.java:194)
    at logisticspipes.pipes.PipeItemsProviderLogistics.getSpecificInterests(PipeItemsProviderLogistics.java:426)
    at logisticspipes.routing.ServerRouter.updateInterests(ServerRouter.java:818)
    at logisticspipes.routing.ServerRouter.update(ServerRouter.java:731)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:303)
    at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
    at yc.h(World.java:2597)
    at in.h(WorldServer.java:701)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:956)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:857)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:744)
    at fy.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.ClassNotFoundException: gregtechmod.api.IDigitalChest
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:218)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 16 more
Caused by: java.lang.NullPointerException
    at org.objectweb.asm.ClassReader.<init>(Unknown Source)
    at codechicken.core.asm.ClassHeirachyManager.transform(ClassHeirachyManager.java:80)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:261)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:206)
    ... 18 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at logisticspipes.proxy.specialinventoryhandler.DigitalChestHandler.isType(DigitalChestHandler.java:38)
    at logisticspipes.utils.InventoryUtilFactory.getUtilForInv(InventoryUtilFactory.java:44)
    at logisticspipes.utils.InventoryUtilFactory.getHidingInventoryUtil(InventoryUtilFactory.java:56)
    at logisticspipes.pipes.PipeItemsProviderLogistics.getAdaptedInventoryUtil(PipeItemsProviderLogistics.java:194)
    at logisticspipes.pipes.PipeItemsProviderLogistics.getSpecificInterests(PipeItemsProviderLogistics.java:426)
    at logisticspipes.routing.ServerRouter.updateInterests(ServerRouter.java:818)
    at logisticspipes.routing.ServerRouter.update(ServerRouter.java:731)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:303)
    at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)

-- Tile entity being ticked --
Details:
    Name: logisticspipes.pipes.basic.LogisticsTileGenericPipe // logisticspipes.pipes.basic.LogisticsTileGenericPipe
    Block type: ID #0
    Block data value: Unknown? (Got -1)
    Block location: World: (2016,66,811), Chunk: (at 0,4,11 in 126,50; contains blocks 2016,0,800 to 2031,255,815), Region: (3,1; contains chunks 96,32 to 127,63, blocks 1536,0,512 to 2047,255,1023)
Stacktrace:
    at yc.h(World.java:2597)
    at in.h(WorldServer.java:701)

-- Affected level --
Details:
    Level name: world
    All players: 1 total; [iq['Warlock3000'/431, l='world', x=2026.95, y=73.00, z=807.56](Warlock3000 at 2026.9545692226652,73.0,807.5576837724075)]
    Chunk stats: ServerChunkCache: 425 Drop: 0
    Level seed: 3760182584959179809
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (26,68,-7), Chunk: (at 10,4,9 in 1,-1; contains blocks 16,0,-16 to 31,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 39233321 game time, 42319094 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 119594 (now: false), thunder time: 103660 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:956)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:857)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:744)
    at fy.run(ThreadMinecraftServer.java:16)

   Warnings: DEFAULT
   Threads: { WAITING Thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:186), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), cpw.mods.fml.relauncher.FMLRelaunchLog$ConsoleLogThread.run(FMLRelaunchLog.java:68), java.lang.Thread.run(Thread.java:722)], TIMED_WAITING Thread-5: [java.lang.Thread.sleep(Native Method), hp.run(DedicatedServerSleepThread.java:23)], RUNNABLE Thread-6: [java.io.FileInputStream.readBytes(Native Method), java.io.FileInputStream.read(FileInputStream.java:242), java.io.BufferedInputStream.fill(BufferedInputStream.java:235), java.io.BufferedInputStream.read(BufferedInputStream.java:254), java.io.FilterInputStream.read(FilterInputStream.java:83), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader$1.read(ConsoleReader.java:167), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:267), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:204), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:995), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1167), hq.run(DedicatedServerCommandThread.java:37)], TIMED_WAITING pool-1-thread-12: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1043), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1103), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603), java.lang.Thread.run(Thread.java:722)], RUNNABLE Listen thread: [java.net.PlainSocketImpl.socketAccept(Native Method), java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:396), java.net.ServerSocket.implAccept(ServerSocket.java:522), java.net.ServerSocket.accept(ServerSocket.java:490), hu.run(ServerListenThread.java:83)], TIMED_WAITING LogisticsPipes Packet Compressor Server: [java.lang.Thread.sleep(Native Method), logisticspipes.ticks.ServerPacketBufferHandlerThread.run(ServerPacketBufferHandlerThread.java:217)], WAITING PermissionsEx-Cleaner: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:503), java.util.TimerThread.mainLoop(Timer.java:526), java.util.TimerThread.run(Timer.java:505)], TIMED_WAITING pool-1-thread-8: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1043), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1103), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603), java.lang.Thread.run(Thread.java:722)], TIMED_WAITING pool-1-thread-5: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1043), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1103), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603), java.lang.Thread.run(Thread.java:722)], TIMED_WAITING Spigot Watchdog Thread: [java.lang.Thread.sleep(Native Method), org.bukkit.craftbukkit.v1_4_R1.util.WatchdogThread.run(WatchdogThread.java:49)], WAITING LogisticsPipes RoutingTableUpdateThread #2: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:186), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043), java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:537), logisticspipes.ticks.RoutingTableUpdateThread.run(RoutingTableUpdateThread.java:35)], TIMED_WAITING pool-1-thread-10: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1043), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1103), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603), java.lang.Thread.run(Thread.java:722)], TIMED_WAITING pool-1-thread-4: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1043), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1103), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603), java.lang.Thread.run(Thread.java:722)], RUNNABLE DestroyJavaVM: [], WAITING LogisticsPipes RoutingTableUpdateThread #3: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:186), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043), java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:537), logisticspipes.ticks.RoutingTableUpdateThread.run(RoutingTableUpdateThread.java:35)], TIMED_WAITING pool-1-thread-3: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1043), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1103), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603), java.lang.Thread.run(Thread.java:722)], RUNNABLE Connection #3 write thread: [java.net.SocketOutputStream.socketWrite0(Native Method), java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109), java.net.SocketOutputStream.write(SocketOutputStream.java:153), org.bouncycastle.crypto.io.CipherOutputStream.write(Unknown Source), java.io.BufferedOutputStream.write(BufferedOutputStream.java:122), java.io.DataOutputStream.write(DataOutputStream.java:107), dt.a(Packet56MapChunks.java:203), ef.a(Packet.java:209), cg.h(TcpConnection.java:201), cg.d(TcpConnection.java:561), ci.run(TcpWriterThread.java:25)], TIMED_WAITING pool-1-thread-2: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1043), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1103), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603), java.lang.Thread.run(Thread.java:722)], TIMED_WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], TIMED_WAITING Spigot Metrics Gathering Thread: [java.lang.Thread.sleep(Native Method), org.bukkit.craftbukkit.v1_4_R1.util.TimedThread.run(TimedThread.java:22)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:503), java.lang.ref.Reference$ReferenceHandler.run(Reference.java:133)], WAITING Chunk I/O Executor Thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:186), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1043), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1103), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603), java.lang.Thread.run(Thread.java:722)], WAITING LogisticsPipes RoutingTableUpdateThread #0: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:186), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043), java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:537), logisticspipes.ticks.RoutingTableUpdateThread.run(RoutingTableUpdateThread.java:35)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151), java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:177)], TIMED_WAITING process reaper: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1043), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1103), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603), java.lang.Thread.run(Thread.java:722)], TIMED_WAITING pool-1-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1043), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1103), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603), java.lang.Thread.run(Thread.java:722)], RUNNABLE pool-1-thread-6: [java.net.PlainSocketImpl.socketConnect(Native Method), java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:337), java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:198), java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:180), java.net.SocksSocketImpl.connect(SocksSocketImpl.java:391), java.net.Socket.connect(Socket.java:579), java.net.Socket.connect(Socket.java:528), sun.net.NetworkClient.doConnect(NetworkClient.java:180), sun.net.www.http.HttpClient.openServer(HttpClient.java:388), sun.net.www.http.HttpClient.openServer(HttpClient.java:483), sun.net.www.http.HttpClient.<init>(HttpClient.java:213), sun.net.www.http.HttpClient.New(HttpClient.java:300), sun.net.www.http.HttpClient.New(HttpClient.java:316), sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:992), sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:928), sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:846), sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1296), java.net.URL.openStream(URL.java:1035), net.sacredlabyrinth.phaed.simpleclans.AutoUpdate.run(Unknown Source), org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53), org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603), java.lang.Thread.run(Thread.java:722)], TIMED_WAITING File IO Thread: [java.lang.Thread.sleep(Native Method), aiw.b(ThreadedFileIOBase.java:49), aiw.run(ThreadedFileIOBase.java:27), java.lang.Thread.run(Thread.java:722)], TIMED_WAITING Keep-Alive-Timer: [java.lang.Thread.sleep(Native Method), sun.net.www.http.KeepAliveCache.run(KeepAliveCache.java:172), java.lang.Thread.run(Thread.java:722)], TIMED_WAITING pool-1-thread-7: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1043), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1103), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603), java.lang.Thread.run(Thread.java:722)], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Thread.java:1618), org.bukkit.craftbukkit.v1_4_R1.CraftCrashReport.call(CraftCrashReport.java:27), l.a(CrashReportCategory.java:103), a.h(CrashReport.java:59), a.<init>(CrashReport.java:41), a.a(CrashReport.java:320), yc.h(World.java:2601), in.h(WorldServer.java:701), net.minecraft.server.MinecraftServer.r(MinecraftServer.java:956), ho.r(DedicatedServer.java:309), net.minecraft.server.MinecraftServer.q(MinecraftServer.java:857), net.minecraft.server.MinecraftServer.run(MinecraftServer.java:744), fy.run(ThreadMinecraftServer.java:16)], TIMED_WAITING pool-1-thread-11: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1043), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1103), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603), java.lang.Thread.run(Thread.java:722)], RUNNABLE Connection #3 read thread: [java.net.SocketInputStream.socketRead0(Native Method), java.net.SocketInputStream.read(SocketInputStream.java:150), java.net.SocketInputStream.read(SocketInputStream.java:121), java.io.FilterInputStream.read(FilterInputStream.java:133), org.bouncycastle.crypto.io.CipherInputStream.nextChunk(Unknown Source), org.bouncycastle.crypto.io.CipherInputStream.read(Unknown Source), java.io.FilterInputStream.read(FilterInputStream.java:83), ef.a(Packet.java:150), cg.i(TcpConnection.java:325), cg.c(TcpConnection.java:553), ch.run(TcpReaderThread.java:23)], TIMED_WAITING pool-1-thread-9: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1043), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1103), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603), java.lang.Thread.run(Thread.java:722)], RUNNABLE Signal Dispatcher: [], WAITING LogisticsPipes RoutingTableUpdateThread #1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:186), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043), java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:537), logisticspipes.ticks.RoutingTableUpdateThread.run(RoutingTableUpdateThread.java:35)],}
   Recent tasks from 258-288{Essentials:com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener$1@317,Essentials:com.earth2me.essentials.EssentialsPlayerListener$1@317,}
    FML: MCP v7.26a FML v4.7.35.556 Minecraft Forge 6.6.2.534 28 mods loaded, 28 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2 [IndustrialCraft 2](IC2_231.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core [BuildCraft](buildcraft-A-3.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders [BC Builders](buildcraft-A-3.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport [BC Transport](buildcraft-A-3.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon [BC Silicon](buildcraft-A-3.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forestry [Forestry for Minecraft](forestry-A-2.0.0.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerCore [RedPower](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerBase [RP Base](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerMachine [RP Machine](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerCompat [RP Compat](RedPowerCompat-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerWiring [RP Wiring](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerLogic [RP Logic](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerLighting [RP Lighting](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerWorld [RP World](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerControl [RP Control](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy [BC Energy](buildcraft-A-3.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory [BC Factory](buildcraft-A-3.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GregTech_Addon [GregTech-Addon](gregtechmod.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LogisticsPipes|Main [Logistics Pipes](LogPipes_343.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2NuclearControl [Nuclear Control](NuclearControl.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest [Iron Chest](ironchest-universal-1.4.7-4.5.4.217.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AdvancedSolarPanel [Advanced Solar Panels](mod_AdvancedSolarPanels_3_3_2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GraviSuite [Gravitation Suite](mod_zGraviSuite_1_6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 146 (8176 bytes; 0 MB) allocated, 146 (8176 bytes; 0 MB) used
    Player Count: 1 / 100; [iq['Warlock3000'/431, l='world', x=2026.95, y=73.00, z=807.56](Warlock3000 at 2026.9545692226652,73.0,807.5576837724075)]
    Is Modded: Definitely; Server brand changed to 'mcpc,craftbukkit,forge,fml'
    Type: Dedicated Server (map_server.txt)

**Comment by AartBluestoke** [comment]
that is caused by an out-of-date gregtech version.
