### ISSUE TITLE
Text Filter Pipe

### ISSUE THREAD

**Issue by loordgek** [RS485/LogisticsPipes#301]
http://mod-buildcraft.com/forums/index.php?topic=326.0
can we get some thing like this ?

**Comment by davboecki** [comment]
The biggest problem with something like this is still the fact that servers don't have a language.

**Comment by ruifung** [comment]
Perhaps make them match against the textual ID's used in 1.7 onwards? Maybe provide 2 options, regular expressions / substring matching.
Of course, this would only be workable in 1.7 and onwards.

**Comment by bziemons** [comment]
There could be at least something like that with the Ore Dictionary. Not sure if it should be in the mod.

**Comment by bziemons** [comment]
Should be covered by *Mk2 OreDict item sink with text field and wildcard support via asterisk*
