### ISSUE TITLE
Satellite Pipe and/or Logistics Crafting Table not working, build #117.

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#302]
Basically I setup a standard network with some provider pipes, a default, some logistics crafting tables, etc. When I tried to use an iron chest adjacent to the table it would not pull the items needed from the chest. I am 100% sure the recipe was correct, non stacking items were set to satellite ID correctly, all of that stuff. The table just appears to not pull items from adjacent chests anymore.

**Comment by davboecki** [comment]
LCT never supported pulling from a side Chest. Simply use the Internal buffer for unstackable items.

**Comment by ghost** [comment]
My apologies, I was used to the pre-1.6 system using BuildCraft Automatic Crafting Tables.
