### ISSUE TITLE
Fluid Crafting Pipe to craft fluids

### ISSUE THREAD

**Issue by AnimeniacYuuto** [RS485/LogisticsPipes#303]
I think it would be cool to have a pipe where you can specify how to craft a Fluid opposed to an Item with several of the mechanics that craft fluid, Tinkers Construct, Thermal Expansion, Forestry, Buildcraft ect.

**Comment by Polyana-Fontes** [comment]
I was going to suggest this feature right now, that would be awesome

**Comment by hron84** [comment]
Refined Storage has a feature for it, basically it registers the fluids with the required amount into the recipe and gets the fluid from the registered providers (fluid cards, fluid storage buses) on the network. Interesting solution but I do not know if it would be work with LP...

**Comment by bziemons** [comment]
Covered by *Crafting with fluids as results* in https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
