### ISSUE TITLE
Server crash on build 141

### ISSUE THREAD

**Issue by tambry** [RS485/LogisticsPipes#305]
Starting from build 141 my server crashes when starting up.
Log (Couldn't pastebin whole log):
http://pastebin.com/c8Rianmr

**Comment by davboecki** [comment]
Thanks for the report. Should be fixed in newer builds now. Can you confirm that?

**Comment by tambry** [comment]
@davboecki Will confirm that in hour or two when I get home.

**Comment by tambry** [comment]
@davboecki Can't confirm it, the build has failed.

**Comment by davboecki** [comment]
Builds are working again. Could you test this now?

**Comment by tambry** [comment]
@davboecki tested with build 144, another crash. This time with trying to find render/find fonts on server, it seems.
Log:
http://pastebin.com/suHXuB3X

**Comment by davboecki** [comment]
That should now be fixed.

**Comment by tambry** [comment]
@davboecki Thank you, it is fixed now and works fine.
