### ISSUE TITLE
[Request] One-way setting in inventory system connector pipe

### ISSUE THREAD

**Issue by Silwing** [RS485/LogisticsPipes#306]
I have toyed around with the inventory system connector pipes and Railcraft locomotives. For that purpose it would be very useful to have a setting to make the inventory connection "one-way" since a loader and unloader pair can only transport items one way not both. Maybe simply a button stating "input", "output" or "both" with "both" being the default setting.

**Comment by davboecki** [comment]
Have you tried using an Iron pipe for One way routing ?

**Comment by Silwing** [comment]
I tried using one on the output side which then also blocks power. It was then I discovered the bug with the firewall pipe. But now I came to think that I could actually move the iron pipe to the input side which will then still allow power to go through. That way it would be more usable. Maybe not that necessary then :)

**Comment by davboecki** [comment]
Any news on this one?

**Comment by Silwing** [comment]
I haven't got around to trying the iron pipe thing, but I don't see why it should work just fine. So I'll close this for now. Can be reopened later if a specific use case comes up :)
