### ISSUE TITLE
Firewall pipe not blocking item sinks

### ISSUE THREAD

**Issue by Silwing** [RS485/LogisticsPipes#307]
I have encountered a problem with the firewall pipe. If I block everything except for power flow the system will still try to route through the firewall pipe but as soon as it hits a logistic pipe (basic or any other) the firewall pipe block goes through and the item will pop out into the world.

I have made a very simple setup to reproduce the bug which can be seen here:

![2014-04-17_18 39 51](https://cloud.githubusercontent.com/assets/186144/2734226/74a0d036-c651-11e3-8481-6b347b555a5c.png)

The firewall pipe is set to blocked on everything except power flow. Then placing a few stacks of cobblestone in the chest with the quick sort module (the one to the left in the image) will show the problem. Some particles will show in both chassis pipes and after a while the cobble will pop out into the world.

**Comment by davboecki** [comment]
The newest build should fix this.

**Comment by Silwing** [comment]
Yup seems like it works well :) thanks for the fix!
