### ISSUE TITLE
Bee Analyzer Module exception

### ISSUE THREAD

**Issue by doushio9967** [RS485/LogisticsPipes#310]
Right-clicking with a bee analyzer module in your hand and changing auto-extract to 'off' kicks the player off the server, and the following appears in the server log
http://pastebin.com/kGSmg6U2
Putting the module into a chassis pipe and changing the setting from in there works fine tho.

LP dev.156

**Comment by davboecki** [comment]
Could you retest this with the newest build ?
Should be fixed there.

**Comment by doushio9967** [comment]
Yes, confirmed to be fixed in 157.
Thank you.
