### ISSUE TITLE
[BUILD#163] Item amount Spec. in Supl. pipe not working

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#317]
Somehow my supplier pipes dont accept higher item Numbers than 1 in their configuration GUI. Even if you rightclick a half-stack it only accepts one. Older Setups still work the way they should but reconfiguring them is not possible either. Break/replace doesnt help.

**Comment by davboecki** [comment]
Should work correct again.

**Comment by SonOfTheStars** [comment]
Thanks
ill keep hunting some bugs down
