### ISSUE TITLE
[BUILD#166] Power Transport renderer all over the Place

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#320]
Testing the new Power Transportation mecanism, i found the following bugs:

As Energy gets Transported, some of the beams are spinning around the Y-Axis, with different length. this only happens if the beams are transfering power along the X- or Z-Axis, Beams transfering along the Y-Axis work fine.

Some of the beams aren't drawn at the right Location as it seems and beams traveling along positive Z-Axis are completely missing:

![2014-04-25_23 03 20](https://cloud.githubusercontent.com/assets/3910862/2805763/e3078944-ccbd-11e3-95f6-d5755a4e7050.png)
![2014-04-25_23 03 23](https://cloud.githubusercontent.com/assets/3910862/2805766/e7f0a6a2-ccbd-11e3-9afc-95e2b6248f39.png)
![2014-04-25_23 03 44](https://cloud.githubusercontent.com/assets/3910862/2805768/e9bda4da-ccbd-11e3-9cbb-bad144215115.png)

Additionally, if a Player is near the Pipes wich transfer Energy and he looks at a block such that he gets the block Highlighter shown, he sees a Tron-like Effect in the Energy-beams Color, covering his screen:
![2014-04-25_23 03 09](https://cloud.githubusercontent.com/assets/3910862/2805785/235babec-ccbe-11e3-93e8-ef258c105c81.png)

(Same effect if one uses TE-Itemducts)

**Comment by davboecki** [comment]
What graphic card do you use?

**Comment by SonOfTheStars** [comment]
MSI Radeon HD R7770 Gigabyte Edition

**Comment by bziemons** [comment]
I cannot reproduce it, but I also have an NVidia card. Have you tried updating LWJGL and your graphics card driver?

![2014-04-26_00 17 03](https://cloud.githubusercontent.com/assets/1096713/2806363/1c35dd4c-ccc8-11e3-9050-4ed011d0683d.png)
![2014-04-26_00 18 19](https://cloud.githubusercontent.com/assets/1096713/2806371/4363819e-ccc8-11e3-810f-f3870e4b7618.png)

BTW: The pictures might not show it, but I have tried it on every direction, just to be sure ;)

**Comment by SonOfTheStars** [comment]
Drivers are up to date im gonna test updating LWJGL tomorrow and tell you about the results

**Comment by SonOfTheStars** [comment]
Okey i updated both of them (Driver just got an update today) but its still the same. Zero improvement
