### ISSUE TITLE
[Enhancement] Converting energy

### ISSUE THREAD

**Issue by miuirussia** [RS485/LogisticsPipes#329]
Please, make converting BC to EU/RF and EU/RF to BC with new Power Transportation

**Comment by bziemons** [comment]
Nah, the idea behind power transportation is to not convert energy. We do not want that, as that is not our deal.

**Comment by AartBluestoke** [comment]
Do you think we could transport other forms of power, unconverted though...
We manage to transport different item and liquid typed,why not energy,
especially as the power junction runs of many different energy sources.

@devs, thoughts?
I haven't looked at how we transport power...

**Comment by bziemons** [comment]
@AartBluestoke go and look at how we transport power :)
