### ISSUE TITLE
Fluid Request pipes do not appear to have CC commands

### ISSUE THREAD

**Issue by theron61** [RS485/LogisticsPipes#330]
Would it be possible to enable CC functionality for Fluid Request pipes?  It would be helpful to request liquid types and quantities for those systems that need more than one fluid in specific amounts.

**Comment by bziemons** [comment]
Correct. But to do this, there needs to be a CC integration of the Fluid Identifier. @davboecki please? :)

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
