### ISSUE TITLE
code standards.

### ISSUE THREAD

**Issue by AartBluestoke** [RS485/LogisticsPipes#333]
BuildCraft has instituted some code formatting standards, I thought I would link the relevant discussion here as lp doesn't have any formal standards.

https://github.com/BuildCraft/BuildCraft/issues/1662#issuecomment-42110416

**Comment by bziemons** [comment]
I would not put it as "they have it, so we should have it(/think about it) as well".
The question is: Do we need it?

**Comment by davboecki** [comment]
I think it would be a good idea. Currently nearly every class looks different inside LP. Some have headers some don't. A general style would also free most diffs from code cleanups

**Comment by GUIpsp** [comment]
I'd like no headers with sun's standards

**Comment by davboecki** [comment]
My proposal would be: https://github.com/RS485/LogisticsPipes/tree/mc16_cleanup/style
It contains an eclipse formater settings file and an checkstyle file. The checkstyle file is based on sun's standard but reduced by several options.
The branch itself shows the result. It is formated and all checkstyle issues have been resolved.

**Comment by davboecki** [comment]
@AartBluestoke @ArtForz @GUIpsp 
Any comments on the proposed checkstyle and eclipse formatter settings?

**Comment by bziemons** [comment]
Actually I would like a tool that works with Gradle and Jenkins. Is there something like that?

**Comment by bziemons** [comment]
Everyone can comment on this, if they want to.

**Comment by GUIpsp** [comment]
https://wiki.jenkins-ci.org/display/JENKINS/Checkstyle+Plugin

**Comment by bziemons** [comment]
Yeah, sounds good. @davboecki ?

**Comment by davboecki** [comment]
The files I added contain a setting for eclipse and a checkstyle file. So the checkstyle part could be done on jenkins as well.

**Comment by bziemons** [comment]
To make this up-to-date: Checkstyle will actually be applied when there is no need to merge another version anymore, e.g. mc17-0.9
