### ISSUE TITLE
Power junction connection issues to pipes above and below

### ISSUE THREAD

**Issue by Hanse00** [RS485/LogisticsPipes#337]
Hello there,

I have a little bug report for you today, although it might not be a "bug" as much as what I would consider expected behavior, that's not implemented.

**Version**:
- Minecraft 1.6.4
- Forge 9.11.1.965
- BuildCraft 4.2.2
- Logistics Pipes 0.7.4.dev.190

**Steps to reproduce:**
1. Place Logistics Power Junction
2. Place any logistics pipe below or above the Logistics Power Junction

**Actual behavior:**
- The logistics pipe does not connect to the power junction

**Expected behavior:**
- The logistics pipe should connect to the power junction

**Screenshots:**
![2014-05-07_18 38 01](https://cloud.githubusercontent.com/assets/1231254/2905864/d26f41f8-d609-11e3-8690-aaefe3791e6a.png)
Pipes connecting to the sides of the power junction

![2014-05-07_18 38 13](https://cloud.githubusercontent.com/assets/1231254/2905873/e9e9443c-d609-11e3-9ce1-c1991c9dfa1b.png)
Pipes not connecting to the top and bottom of the power junction

![2014-05-07_19 03 59](https://cloud.githubusercontent.com/assets/1231254/2905875/f281c182-d609-11e3-9750-030fe078eaa7.png)
Logistics pipes not receiving power from the junction below

If the power junction was never meant to work with pipes above or below it, you should probably just ignore this whole bug report, but it seems to me like it should work with pipes on every side.

**Comment by davboecki** [comment]
The Power junction is only designed to connect to pipes on sides. Top and bottem are excluded.

**Comment by Hanse00** [comment]
That seems rather silly though.

Why should it not work with pipes placed above or below the block?

**Comment by davboecki** [comment]
That's the way it was initialy designed. It the way the texture shows it.
There was a bug that allowed the pipes to the top and bottom but that has been fixed.
