### ISSUE TITLE
Itemducts Support

### ISSUE THREAD

**Issue by Mevansuto** [RS485/LogisticsPipes#341]
I keep getting this crash when I enable itemduct support.

http://pastebin.com/XKWCkXZt#

Using most recent TE and LP.

**Comment by davboecki** [comment]
Fixed by https://github.com/RS485/LogisticsPipes-Dev/commit/954aba1eb090cc5298e84e8a960b54ca567c02ba
TE version 3.0.0.7 is not marked as supported currently. if you want to use the itemduct support you have to use TE 3.0.0.5.
