### ISSUE TITLE
Graphics bug/Possible items stuck

### ISSUE THREAD

**Issue by LyingCak3** [RS485/LogisticsPipes#344]
Updated to version 195 and noticed that items seem to be getting stuck in the pipes.  
![2014-05-11_11 51 14](https://cloud.githubusercontent.com/assets/5199260/2939225/6dfd3f04-d93d-11e3-948c-bf697dc4ff97.png)

Breaking the pipes does not seem to fix it but the items do not drop so it looks like a graphics bug.

Here is a small vid of the bug 
http://youtu.be/hWUdZQEpgG4

**Comment by davboecki** [comment]
Reconnecting should fix that. It's a server/client sync bug.

**Comment by LyingCak3** [comment]
Have tried reconnecting and restarting the server with no chance in the glitch and other players are also reporting it.  Have also tried other servers and have had the same problem.  It is not happening in a single player world.

**Comment by davboecki** [comment]
I think I know what is causing this. Will check it as soon as I can.
