### ISSUE TITLE
Pipes not respecting disconnection upgrades.

### ISSUE THREAD

**Issue by Unknown-Zombie** [RS485/LogisticsPipes#345]
I have pipes that contain Disconenction Upgrades and after upgrading to dev.196, stuff is being transferred to disconnected pipes.

In the screenshots below, the Liquid Pipe has a disconnect upgrade (as evidinced by how it is not connected to the transport pipe beside it), but items are travelling between them anyway.

Note that I removed the disconnect upgrade and reinserted it which did not resolve the problem. Destroying the item transport pipe and replacing it also did not resolve the problem.

Screenshots:
![2014-05-11_15 04 34](https://cloud.githubusercontent.com/assets/2162191/2939457/ed5c3d86-d947-11e3-9b1b-f454e5ab1467.png)
![2014-05-11_15 03 51](https://cloud.githubusercontent.com/assets/2162191/2939458/029c84da-d948-11e3-8345-4f02769f68d6.png)

**Comment by davboecki** [comment]
Am I correct that only the right pipe sends stuff to the left pipe and not the other way around ?

**Comment by Unknown-Zombie** [comment]
Yes, that is correct. As items make their first trip up that item pipe, they are transferred from the right pipe to the left pipe (across the disconnect). From there, they are looping back through the wall and back into that Basic LP  you see in the corner of the room. From there, once they have made that loop, they travel up the pipe as expected.

Screenshot with wall torn away for better clarity:
![drawnpath256](https://cloud.githubusercontent.com/assets/2162191/2939874/5f8dcb74-d95f-11e3-8eaa-a10f9a69ca6d.png)
