### ISSUE TITLE
Thermal Expansion 3.0.0.7 no longer supported?

### ISSUE THREAD

**Issue by tambry** [RS485/LogisticsPipes#346]
As of build 193 TE 3.0.0.7 is suddenly no longer supported:
http://pastebin.com/haK5cDPy

Is this intended?

**Comment by davboecki** [comment]
Yes. Item duct support is currently only possible with TE version 3.0.0.5. In previous versions the check just wasn't handled correctly.

**Comment by tambry** [comment]
@davboecki Thank you for your response.
