### ISSUE TITLE
How to use CC Based QuickSort and ItemSink modules?

### ISSUE THREAD

**Issue by Polyana-Fontes** [RS485/LogisticsPipes#347]
I searched a lot but I couldn't find how we use it.

Can you please provide a small example of how we could use it?

I tried the following code but I'm not receiving events...

``` lua
pipe=peripheral.wrap("bottom")
pipe.setTurtleConnect(true)
print(os.pullEvent())
```

I also tried:

``` lua
pipe=peripheral.wrap("bottom")
pipe.setTurtleConnect(true)
module=pipe.getModule(3)
module.help()
```

but the only method exposed is hasGui()

**Comment by SinusoidalC** [comment]
just check official wiki

**Comment by Polyana-Fontes** [comment]
I'm afraid I couldn't find that information in the official wiki, I found only information about the normal QuickSort and ItemSink modules and about the ComputerCraft API but I couldn't find information about "CC Based QuickSort Module" and "CC Based ItemSink Module" that were added at April 27th (https://github.com/RS485/LogisticsPipes-Dev/commit/0c161062370146ec95f287e38c0af020454fe665)

CC Based: (404)
http://rs485.thezorro266.com/wiki/CC_Based_QuickSort_Module
http://rs485.thezorro266.com/wiki/CC_Based_ItemSink_Module

Normal:
http://rs485.thezorro266.com/wiki/QuickSort_Module
http://rs485.thezorro266.com/wiki/ItemSink_Module

**Comment by davboecki** [comment]
The ItemSInk module triggers an event on a connected computer which than can determine if it can sink the item or not.

**Comment by gudenau** [comment]
I can not seem to find documentation myself, and no event is fired when an item is injected into the network.

Edit:
And looking at the code, I am unable to figure it out so far.

**Comment by bziemons** [comment]
@gudenau if you are having problems figuring this out, please open a new issue, as yours might be unrelated to this one. Also describe what exactly you are trying to do and what pipes/computers are involved.

**Comment by gudenau** [comment]
Ok, will do. If you want I could make a video.

**Comment by bziemons** [comment]
@gudenau if that helps, of course. Most of the times one can describe it in text faster than recording, cutting, uploading a video though.

**Comment by gudenau** [comment]
Ok, but who cuts videos? I don't so far.
