### ISSUE TITLE
Massive ammounts of console spam

### ISSUE THREAD

**Issue by LyingCak3** [RS485/LogisticsPipes#349]
My server crashed while I was asleep and, once I restarted it, I started getting massive amount of console spam saying Unknown Texture to power, then is went thru every pipe that was using the new power system.  Breaking the pipes does not stop it and removing the. Removing all the power upgrades does stop the spam but replacing them starts it back up again.

**Comment by davboecki** [comment]
Log, FML log?

**Comment by LyingCak3** [comment]
Could not post it to pastebin due to the 500 kb limit so here is a download of the log.  Have to scroll down rather far to see the logi pipes spam.

https://www.dropbox.com/s/mu1xxehev4jiabm/ForgeModLoader-server-2.log

**Comment by davboecki** [comment]
Can you see if build 204 fixes this.

**Comment by LyingCak3** [comment]
Tried 204 and 206, no change.  I watched my machines power by Logi pipes and it looks like the texture for pipes that are powering two machines from different mods are not rendering correctly. 

Edited to point out it is not just IC2 machines.

**Comment by davboecki** [comment]
Build 207 should fix this.

**Comment by LyingCak3** [comment]
Yep, console spam has stopped and textures look correct. =D  Thanks for the great mod!! Keep it up!
