### ISSUE TITLE
Power Provider: "rays" of energy rendering incorrectly

### ISSUE THREAD

**Issue by Garagoth** [RS485/LogisticsPipes#351]
Hi.

I have connected TE and BC power providers to my LP net and some receivers, all pipes has power transportation upgrade and proper suppliers. Generally it all works except for blue and red rays of energy inside pipes render incorrectly.
All rays have length that would be sufficient to reach next LP pipe, but they are rotating in each pipe (see screenshots).
BC kinesis pipes render rays correctly, if that matters, and there are no other visual bugs (that I can see).

Also, as a side note, there is no info on power transportation on your wiki (I could write that sections but apparently your wiki does not offer registration).

My MC version: 1.6.4, FTB direwolf20 pack 1.0.23 (BC 4.2.2, LP 0.7.4.dev.172).

Regards,
Garagoth.
![mc_lp_power_provider_bug](https://cloud.githubusercontent.com/assets/916161/3010871/3a4f7c74-df20-11e3-8e7f-241686e32af2.png)
![mc_lp_power_provider_bug_2](https://cloud.githubusercontent.com/assets/916161/3010873/47cc26fe-df20-11e3-93b1-aa3b482b95e6.png)

**Comment by davboecki** [comment]
Please update to the newest build before reporting a bug. This one is already fixed.

**Comment by Garagoth** [comment]
Sorry, could not find it in issues anywhere or in git commit messages. I will update and check few other issues with power.
Anyway, you should consider updating wiki.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes-Dev/commit/7868bf18070fa3e6c200e40352d8145b1af5aacd
