### ISSUE TITLE
Build #192 broke BC tank + fluid provider pipe

### ISSUE THREAD

**Issue by Silwing** [RS485/LogisticsPipes#352]
I have tested this with build 192 and 202 and both fail, build 191 works. To reproduce do the following:

Setup a small logistic system with a power junction, BC tank A with a fluid provider pipe and BC tank B with a fluid supplier pipe. Fill tank A with any liquid (tested with water, fruit juice and biomass), set supplier pipe on tank B to request the provided liquid. Result: nothing happens.
It is also possible to see the problem if you place a fluid request pipe on the system. No fluid will be available.

Fluid extractor pipes works fine with a tank and a fluid basic pipe accepting the given liquid.

This seems to be the case for BC tanks only. Railcraft Iron Tanks and Steel Tanks works fine.

**Comment by davboecki** [comment]
Should be fixed with build 204.

**Comment by Silwing** [comment]
Confirmed fix in build 204.
