### ISSUE TITLE
[Bug/Crash/Compatibility] Crash when TE Itemduct integration is enabled with TE 3.0.7

### ISSUE THREAD

**Issue by AnimeniacYuuto** [RS485/LogisticsPipes#354]
Logistics Pipes is still looking for TE 3.0.5 when TE item duct integration is enabled, TE has updated to 3.0.7

**Comment by SinusoidalC** [comment]
see this：
https://github.com/RS485/LogisticsPipes/issues/346

**Comment by AnimeniacYuuto** [comment]
my apologies, i did not see the issue when i posted this for some reason, shame though i really enjoyed this feature
