### ISSUE TITLE
BeeSink & Multiple Indexers: No Connection to 2nd & ^

### ISSUE THREAD

**Issue by MBfromOK** [RS485/LogisticsPipes#356]
I noticed an issue with the indexer and BeeSink as well...

UPDATE: I noticed that this only happens when there isn't a bee in the indexer... As soon as you add one bee to the indexer the BeeSink connects and works.

Setup:
I was trying to setup 1 indexer for princesses and queens, a 2nd indexer for purebreds, and a third indexer for the remaining bees.

The 1st indexer connects and can even be sent bees, but when I placed the 2nd and 3rd indexers the BeeSinks wouldn't connect (Screenshot below). I moved the setup to the center of my area and the BeeSink wouldn't connect to any face of the indexer (either by moving the BeeSink & piping from one side to another or moving the indexer).

Forestry 2.3.1.1
Binnie Core (Extra Bees, Extra Trees) 1.8.0
Logistics Pipes 0.7.4.dev.151

![2014-05-19_00 42 00](https://cloud.githubusercontent.com/assets/7131008/3010666/0871f7ea-df1b-11e3-8985-f1afcc7bad21.png)

**Comment by SinusoidalC** [comment]
try update to newset verison to see if the bug have been fixed

**Comment by MBfromOK** [comment]
@SinusoidalC  - Aye Aye!  

As of LogisticsPipes 0.7.4.dev.205 for mc 1.6.4 BeeSinks still will not connect to an empty indexer.  Connection completes when any bee is added to the indexer manually.

**Comment by davboecki** [comment]
Do other BC pipes connect to the indexers?

**Comment by MBfromOK** [comment]
The indexer piping connection works as long as a bee has been (manually) placed in the indexers' inventory. After the bee has been added it can be removed (leaving the indexer empty) and the piping will continue to work.

I don't remember any issues with vanilla BC pipes but will have to check when I get off work.

**Comment by MBfromOK** [comment]
Ok, See attached screenshots... If the indexer is placed and piped before a bee is inserted no pipes connect, after a bee has been placed in the inventory (even for a second) any pipe BC/LP will connect.

No bee added:
![2014-06-03_16 36 34](https://cloud.githubusercontent.com/assets/7131008/3167020/f06190e4-eb67-11e3-91d0-661ff5908d58.png)

Bee Added & removed, then piped
![2014-06-03_16 37 14](https://cloud.githubusercontent.com/assets/7131008/3167021/f061f444-eb67-11e3-9ea2-4e4f8c5ccae3.png)

Version info:
![2014-06-03_16 38 56](https://cloud.githubusercontent.com/assets/7131008/3167019/f060ab02-eb67-11e3-8697-17d94c13c65a.png)

**Comment by davboecki** [comment]
If BC pipes also don't connect then I suspect it's a problem with the Indexer. I think that for some reason it says it has an Inventory Size of 0 when there is no item inside the indexer itself.
