### ISSUE TITLE
LP System Seems to Have No Power After Update

### ISSUE THREAD

**Issue by Flexico** [RS485/LogisticsPipes#357]
I just updated LP to version 205, and my pipes stopped working, as if they don't have power. I tried several different power setups, and none of them worked.

My log file: http://www.mediafire.com/view/t2559p3r1ex9sc8/2014-05-20_07.38.12_ForgeModLoader-client-0.log

**Comment by davboecki** [comment]
Did you make sure, that your LP pipes are on the side of the power junction?
Could you post screenshots.

And as a side note, your TE version is outdated resulting in 
`2014-05-20 07:44:17 [SEVERE] [LogisticsPipes|Main] Disabled ThermalExpansionProxy for Mod: ThermalExpansion. Cause was an Exception`

**Comment by Flexico** [comment]
I fixed it. Turns out there was some conflict between an IC2 MV transformer and a TE RF conduit that was mucking up my power grid. XD Crashed my game a few times before I figured it out.

And thanks for the heads up, I got TE all updated.
