### ISSUE TITLE
Question/Feature Request: Forestry Analyzer with LP

### ISSUE THREAD

**Issue by MBfromOK** [RS485/LogisticsPipes#358]
1.  I am loving the improvements and Highly appreciate the efforts of the Dev Team... I am trying to learn how to program in the hopes that I can be a part of the team, but I am a noob programmer and don't know where to start so it might be a while...

To my question:  Does the BeeSink / Bee Analyzer have a counterpart / function for Forestry Trees and Butterflies?

Currently Forestry 2.3.1.1 (703) will analyze bees, trees, and butterflies when you drop them in the analyzer, however, With the current abilities of LP to get just the saplings and butterflies (AFAIK) would require a modItemSink with filtering to drop it down to just the saplings and butterflies... unless the the bee analyzer will / can be modified to also work with Trees & Butterflies.  Is there a way in place? Are there plans for an analyzer pipe / module that is generic?  

Thanks!

**Comment by Garagoth** [comment]
There are several items with genome information that are all accepted by analyzer: bees, saplings, butterflies, pollen (you get that by killing a butterfly that gathered pollen from a forestry tree), bottles with butterflies, larvae (for both bees and butterflies). Just type "genome" in NEI (with waila)...
Maybe generalize bee pipes to process items with genome information, not just bees?

**Comment by AartBluestoke** [comment]
Do they have a separate analyser blocks... I know the are sperate hand held
devices.

The change to make the analyser sink accept anything with a genome is not
hard.

**Comment by Garagoth** [comment]
There is a separate block called "analyzer" (from forestry ofc) and it runs on liquid honey. It will accept and analyze anything with genome information.
It would be nice that bee sink module/pipe would allow not only bees, but any genome specification as well... so I can have, for example, pure saplings in one chest, pure bees in second, and all apple pollen in third.

**Comment by MBfromOK** [comment]
@AartBluestoke No, there is only one analyzer... The analyzer block is crafted in the forestry carpenter machine / block using any one of the 3 individual handheld devices and results in a generic analyzer that is usable for all genome possessing items.

There are two setups likely to be desired: 
1. A single (new / modified / upgraded) analyzer pipe would route everything that contains genome information to a single analyzer.
2. Multiple (new / modified / upgraded) analyzer pipes would route specified types (Bee, Tree, or Butterfly) to the attached analyzer (using modules?!?)

Either way, the BeeSink would need to be modified / changed (or new TreeSink, and ButterflySink LPs' created) to allow the routing of analysed items to the Apiarist / Arborist / Lepidopteroligist (butterfly)/ Vanilla chests.

I would think the handheld devices could / should be used in the LP recipe to determine whether the crafted LP is a bee sync, butterfly sync, or tree sync.

**Comment by bziemons** [comment]
Added in *Forestry bee/tree/butterflies/idontevenknow add-on!* on https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
