### ISSUE TITLE
CC bad methods for Logistics Pipes

### ISSUE THREAD

**Issue by KuCZik** [RS485/LogisticsPipes#359]
Minecraft version: 1.6.4
ComputerCraft version: 1.57
Logistics Pipes version: 0.7.4.dev.172 (same problem in dev.215)

Using FTB Direwolf20 Modpack 1.0.23

Problem: When I trigger method getAvailableItems() on CC with wrapped Request Pipe MK2, it says "lua:52: attempt to call nil". When i trigger listMethods(), it says this available methods:
getActivationEnergy()
getAdvancedMethodsData()
getMJStored()
getMaxMJReceived()
getMaxMJStored()
getMinMJReceived()
getTankInfo()
listMethods()

So method getAvailableItems() is missing.
Is it problem in CC, LP or am I doing something wrong?

**Comment by SinusoidalC** [comment]
Use CC 1.58 or higher verison.

**Comment by KuCZik** [comment]
With LP 0.7.4.dev.215 (or 172, same result) and CC 1.58 nothing changed.

**Comment by SinusoidalC** [comment]
How about 1.63?

**Comment by KuCZik** [comment]
CC 1.63 with LP 0.7.4.dev.215 works on new clean world. But I can't use it on server, because it seems to have problems with other mods and world. I think I will wait to next update of Direwolf20 modpack. But thanks

**Comment by SinusoidalC** [comment]
oh,that must be some CC Peripheral mods do not compatible with CC 1.6x.

**Comment by KuCZik** [comment]
Yes, i tried update OpenPeripherals Core and Addons, OpenBlocks and OpenModsLib, but still getting so many errors.

**Comment by KuCZik** [comment]
Nevermind, it's not automatic now, just semiautomatic with remote orderer. But i hope after update it will work.

**Comment by davboecki** [comment]
Let's hope that this fixes it: https://github.com/RS485/LogisticsPipes/commit/4c5cc4365c878e86d6130e8609f2cf4fc23c6690

**Comment by KuCZik** [comment]
Thanks, I will try it.
