### ISSUE TITLE
Logistics Crafting Table CC integration

### ISSUE THREAD

**Issue by J15t98J** [RS485/LogisticsPipes#360]
Pulling this over from the old repo since it is now deprecated, and there's been no response to the ticket for at least half a year...

"It would be really helpful to be able to use the Logistics Crafting Table as a peripheral in order to set the recipe automatically. I suggest setRecipe(id, id, id, id, id, id, id, id, id),  where the arguments are the slots in the crafting table, left to right, top to bottom (no item in that slot would be nil)."

See also: https://github.com/RS485/LogisticsPipes-Deprecated/issues/722

**Comment by bziemons** [comment]
I can understand your frustration, but as long as there is no developer picking it up, it won't be in the mod.
If someone from outside the team does it, he can make a pull request, we will make one (or more) reviews and then it will be in the mod. Until then: wait :(

PS: closing the old ticket then. Thanks for moving it here.

**Comment by J15t98J** [comment]
Might give it a go sometime soon then. Ty anyway

**Comment by bziemons** [comment]
There were a few changes about CC integration on our Solid Blocks. This is still not an "easy task", but it can be done more easily now.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests in *Being able to change suppliers/extractor filters/crafting tables/... via OC/CC*
