### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#364]
The paste is too big to post the whole thing in pastebins, but I left a good amount left.
http://pastebin.com/bd1a6iRR

I didn't really look into it much, just I listened to your request to post it here in the log. It's happened multiple times, but it's not terribly frequently.

[This happened when a client connected to a server]

**Comment by davboecki** [comment]
Try disabling the watchdog and see if you can join the game. If so you either have to leave the watchdog off or use a higher trigger time.
