### ISSUE TITLE
Logistics Fluid Supplier and Honey

### ISSUE THREAD

**Issue by Garagoth** [RS485/LogisticsPipes#365]
Hi,

I have a squeezer (forestry) => logistics fluid insertion pipe => basic fluid pipe (set to accept Honey) => BC tank.
And this works, tank is filled with honey.
Then part two which does NOT work:
BC tank with honey => fluid provider pipe => fluid supplier => analyzer
BC tank with honey => fluid provider pipe => fluid request pipe => carpenter

Above works with water and seed oil, but honey does not arrive.
There are golden particles inside supplier pipe (like it is requesting something?), but no logistics fluid containers arrive, no honey in internal tank.
Tried replacing machine with a BC tank: same results, any other liquid works, honey does not work.

Fluid request pipe does see honey in BC tank and proper amount.
Also, I can fill bucket from tank with honey (right-click) and fill a machine using that bucket (right-click again).

As a side issue: when there are dozens of fluids registered, cycling them all to find proper one is kinda troublesome. Maybe a drop-down or search by name field?

LP version: build 217
Modpack: FTB direwolf 1.0.23 (MC 1.6.4)

Regards,
Garagoth.

**Comment by Garagoth** [comment]
Fruit juice (from Forestry mod) behaves same as honey.
I noticed one more thing:
When there is squeezer connected via fluid extractor pipe and it extracts, then fluid supplier is able to supply required amounts of liquid - more then is extracted, properly draining from tank, but not as often as it should (it waits with resupply for few extraction cycles)
When squeezer is idle (and there is fruit juice in tank) nothing happens (just golden particles, no juice supplied).

G.

**Comment by Garagoth** [comment]
In newest build (230) fluid request pipe is also having hard time supplying Seed Oil to Carpenter (from forestry).
There is a message "Request successfull", but no fluid arrives.
Oddly, crafting pipe with fluid satellite is able to provide required fluid - but not every time as I constantly find wood in carpenter and no seed oil.

When fluid request pipe was destroyed and placed again, it started properly requesting fluid again.
In serwer logs there is nothing connected with LP, just lots of those messages, not sure if connected to the issue:
[ForgeModLoader] The world 679b9888 (world) may have leaked: seen 670 times.

On the other side, I broke and replaced fluid supplier on analyzer just now - and it started supplying honey.
No other changes were made in piping.

G.

**Comment by Garagoth** [comment]
More testing and a lightbulb... fluid providers were connected not to the bottom BC tank but to second or third in vertical stack.
It always says that request successfull, but when liquid level was too low it was in reality a failed request.

G.

**Comment by AartBluestoke** [comment]
The ability to set preferential draw aiding to the height on a rank would be a nice feature. I would keep the current delivery mechanism and fix the 'can supply'check,rather than the reverse, as that would allow for 'we are getting low, so use a secondary supply, or stop doing x' gate condition based on 'can supply'

**Comment by ArtForz** [comment]
Looks like Providers not working properly if not on bottom tank of tank stack is at least partially a BC bug (see https://github.com/BuildCraft/BuildCraft/commit/08edcf1759c884cb95b66c53427bbd4b3f3d9751).
This causes the Provider to claim to be able to provide X fluid, but on actually trying to send it fail the drain() and do a sendFailed(). So then the supplier would remove that off the pending requests and try to get that amount the next time. At which point the same provider again claims to be able to provide X fluid. Repeat.
