### ISSUE TITLE
Items disappearing during transit of Logistics Network

### ISSUE THREAD

**Issue by Zymus** [RS485/LogisticsPipes#366]
I'm having an issue with the logistics pipes. I have a quarry which is connected to two chests, one with a logistics chassis mk 1 with an itemsink module set for cobblestone, and one with a basic logistics pipe connected to it. What happens is whenever a non-cobblestone item gets sent into the logistics chassis, it either disappears (ie. doesn't show up in the chest) or gets dropped on the ground, and doesn't make it to the other chest. I'm using MC 1.6.4 with LogisticsPipes-MC1.6.4-0.7.4.dev.217 and buildcraft-A-1.6.4-4.2.2

**Comment by bziemons** [comment]
Have you set the Basic Logistics Pipe to a default route, so that the system knows where items other than cobblestone need to go?

**Comment by Zymus** [comment]
Yes, the second pipe, the one not with an itemsink module is set at default route.

**Comment by davboecki** [comment]
Should be fixed.
