### ISSUE TITLE
Allow ItemSinks to ignore damage values/metadata

### ISSUE THREAD

**Issue by HaniiPuppy** [RS485/LogisticsPipes#368]
Something that's a pain when I'm sorting items is that there's no way to get itemsinks to ignore item metadata nor damage values. It's annoying when working with tools/weapons/armour that take damage, and things like extra utilities drums. It would help immensely to have an option to neglect to take into account the damage value, the metadata, or both.

I was surprised there hadn't been a ticket for this already.

**Comment by AartBluestoke** [comment]
there is a fuzzy sink, enchantment sink, and a few others sink types that will probably be capable of providing the functionality you desire.

**Comment by HaniiPuppy** [comment]
I'm afraid I only see the ItemSink, Polymorphic ItemSink, BeeSink, Mod
Based ItemSink, (the immensely useful) OreDict ItemSink, and the Thaumic
AspectSink, which version were those added in?

EDIT: Nevermind, sorry. I'm looking through the change logs now. I'm playing on a server
on a private pack and I hadn't realised that our admin was using a
three-month-old version of the mod. Sorry to have bothered you.

**Comment by HaniiPuppy** [comment]
I just tried the newest version and, while I can see more itemsinks, I still can't see the fuzzy item sink - and the only references to them I can find are issues on this github.

**Comment by bziemons** [comment]
As a workaround you can use ComputerCraft with the CC Item Sink module right now.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
