### ISSUE TITLE
Crash when initiating game

### ISSUE THREAD

**Issue by JuanCtan** [RS485/LogisticsPipes#370]
this is what hapens i think it has to do with ic2 recipies or something like that
please help!! i need to set it up for single player and can`t figure out please help!!

```
  Minecraft has crashed!      
  ----------------------      
```

Minecraft has stopped running because it encountered a problem; Failed to start game

A full error report has been saved to C:\Users\JuanAntonio\AppData\Roaming.minecraft\crash-reports\crash-2014-06-06_18.47.12-client.txt - Please include a copy of that file (Not this screen!) if you report this crash to anyone; without it, they will not be able to help fix the crash :(

--- BEGIN ERROR REPORT 2ff54212 --------
Full report at:
C:\Users\JuanAntonio\AppData\Roaming.minecraft\crash-reports\crash-2014-06-06_18.47.12-client.txt
Please show that file to Mojang, NOT just this screen!

Generated 6/06/14 18:47

-- System Details --
Details:
    Minecraft Version: 1.5.2
    Operating System: Windows 8.1 (x86) version 6.3
    Java Version: 1.7.0_55, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 283867624 bytes (270 MB) / 519110656 bytes (495 MB) up to 1037959168 bytes (989 MB)
    JVM Flags: 2 total; -Xms512m -Xmx1024m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v7.51 FML v5.2.5.685 Minecraft Forge 7.8.0.685 Optifine OptiFine_1.5.2_HD_D2 61 mods loaded, 61 mods active
    mcp{7.44} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    FML{5.2.5.685} [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Forge{7.8.0.685} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    CodeChickenCore{0.8.6.6} [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    NotEnoughItems{1.5.2.13} [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    mod_PandorasBox{1.4.4} [mod_PandorasBox](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    mod_ReiMinimap{v3.3_05 [1.5.2]} [mod_ReiMinimap](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MoreExplosives{Release 3.5 for Minecraft 1.5.1} [More Explosives Mod](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    mod_InstantWMansion{1.0.0} [mod_InstantWMansion](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    mod_Barn{1.0.0} [mod_Barn](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    mod_Castle{1.0.0} [mod_Castle](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    mod_Fset{1.0.0} [mod_Fset](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    mod_GreenHouse{1.0.0} [mod_GreenHouse](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    mod_HouseV3{1.0.0} [mod_HouseV3](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    mod_Mansion{1.0.0} [mod_Mansion](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    mod_Nset{1.0.0} [mod_Nset](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    mod_SpawnZom{1.0.0} [mod_SpawnZom](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    mod_Tower{1.0.0} [mod_Tower](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    mod_waterbase{1.0.0} [mod_waterbase](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    mod_largeCastle{LOL} [mod_largeCastle](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    DynamicLights{1.1.9} [Dynamic Lights](DynamicLights_1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    DynamicLights_onFire{1.0.2} [Dynamic Lights on burning](DynamicLights_1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    DynamicLights_creepers{1.0.2} [Dynamic Lights on Creepers](DynamicLights_1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    DynamicLights_dropItems{1.0.2} [Dynamic Lights on ItemEntities](DynamicLights_1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    DynamicLights_mobEquipment{1.0.0} [Dynamic Lights on Mob Equipment](DynamicLights_1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    DynamicLights_flameArrows{1.0.0} [Dynamic Lights on Flame enchanted Arrows](DynamicLights_1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    DynamicLights_otherPlayers{1.0.2} [Dynamic Lights Other Player Light](DynamicLights_1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    DynamicLights_thePlayer{1.0.4} [Dynamic Lights Player Light](DynamicLights_1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    DamageIndicatorsMod{2.6.4} [Damage Indicators]([1.5.1]DamageIndicators v2.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    camping{1.0.1c} [The Camping Mod]([1.5.2] The Camping Mod 1.0.1c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    extendedWorkbench{1.1.8} [Extended Workbench]([1.5.2]ExtendedWorkbench v1.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BattleTowers{1.3.3} [Battle Towers](BattleTowers_1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Fyrestorm_BorderlandsWeaponMod{0.0.8e} [The Borderlands Weapon Mod](Borderlands-Weapon-Mod-v0.0.8e-1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Core{3.7.1} [BuildCraft](buildcraft-A-3.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Builders{3.7.1} [BC Builders](buildcraft-A-3.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Energy{3.7.1} [BC Energy](buildcraft-A-3.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Factory{3.7.1} [BC Factory](buildcraft-A-3.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Transport{3.7.1} [BC Transport](buildcraft-A-3.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Silicon{3.7.1} [BC Silicon](buildcraft-A-3.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ClaySoldiersMod{9.1} [Clay Soldiers Mod](CSM_v911.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    mod_YMTLib{152v1} [mod_YMTLib](YMTLib_152v1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    mod_HariboteAirCraft{152v1 ulysses} [mod_HariboteAirCraft](HariboteAirCraft_152v1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    IC2{1.115.287-lf} [IndustrialCraft 2](industrialcraft-2_1.115.287-lf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    inventorytweaks{1.54b} [Inventory Tweaks](InventoryTweaks-1.54b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    IronChest{5.2.4.391} [Iron Chest](ironchest-universal-1.5.1-5.2.4.391.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    SlimevoidLib{2.0.1.1} [Slimevoid Library](SlimevoidLib-Universal-v2.0.1.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    LittleBlocksMod{2.1.0.0} [Little Blocks](LittleBlocks-Universal-v2.1.0.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    LogisticsPipes|Main{0.7.3.dev.666} [Logistics Pipes](LogisticsPipes-MC1.5.2-0.7.3.dev.666.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
    mod_thx{Minecraft THX Helicopter Mod - mod_thx-v023-mc_151} [mod_thx](mod_thx_helicopter_mc152_v024.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ProjectRed{${build.release.mod.version}.@BUILD@} [Project: Â§4Red](Project-Red-Mod-1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    RopesPlus{1.4.0} [Ropes+](RopePlus_1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    AS_Ruins{10.0} [Ruins Spawning System](Ruins_1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    SAP_Man{1.4.2} [SanAndreasPs Managers](SAP_ManPack_v142.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    TStormFix{1.0} [Thunderstorm Fix](SAP_ManPack_v142.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    SGCraft{0.5.2} [SG Craft](SGCraft-0.5.2-mc1.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    mod_Timber{1.5.1r2} [Timber!](Timber! %281.5.2%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    adnantheclydeTravellingHouse{1.0.0} [Travelling House](TravellingHouse_1.5.1_v1.0.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    TwilightForest{1.17.2} [The Twilight Forest](twilightforest-1.17.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    AS_UpdateCheck{1.0.8} [AtomicStryker Update Check Mod](UpdateCheckerMod_1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    TheWarsMod{3.4.1} [The Wars Mod by Resinresin](Wars Mod Universal 1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    weaponmod{1.5.2 v1.12.0} [Balkon's WeaponMod](WeaponMod.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    LWJGL: 2.4.2
    OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3379, Intel
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Texture Pack: OzoCraft-1.5.zip
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: ic2/api/recipe/Recipes
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:142)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:696)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:206)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:447)
    at net.minecraft.client.MinecraftAppletImpl.func_71384_a(SourceFile:56)
    at net.minecraft.client.Minecraft.run(Minecraft.java:732)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: ic2/api/recipe/Recipes
    at logisticspipes.proxy.ic2.IC2Proxy.addCraftingRecipes(IC2Proxy.java:108)
    at logisticspipes.LogisticsPipes.postInit(LogisticsPipes.java:396)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:494)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:165)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:98)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:695)
    ... 5 more
Caused by: java.lang.ClassNotFoundException: ic2.api.recipe.Recipes
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:238)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 32 more
Caused by: java.lang.NullPointerException
    at org.objectweb.asm.ClassReader.<init>(Unknown Source)
    at codechicken.core.asm.ASMHelper.createClassNode(ASMHelper.java:105)
    at codechicken.core.asm.ClassHeirachyManager.transform(ClassHeirachyManager.java:90)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:352)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:225)
    ... 34 more
--- END ERROR REPORT 4fa05710 ----------

**Comment by davboecki** [comment]
LP only works with the experimental version of IC2.

**Comment by JuanCtan** [comment]
oh well... thanks for the reply anyways
but then, why is this versión of LP for 1.5.2 if the exprimental ic2 is for 1.7.x?
asking just in case im stupid and dont have to upgrade my whole list of mods for 1.7.x

**Comment by davboecki** [comment]
There are also versions of IC2 experimental for 1.6.4.
If you look at their jenkins you probably have to look at the changes to find the last version for mc 1.6.4. It's the same job there.
