### ISSUE TITLE
Please add gate support for fluid pipes (as item LP pipes have)

### ISSUE THREAD

**Issue by Garagoth** [RS485/LogisticsPipes#372]
Fluid pipes are missing gate support that their item counterparts have.
Would be nice if you could add that in mean time...

Regards,
G.

**Comment by davboecki** [comment]
As gate support is probably going to be dropped in the 1.7 update I don't see the point of adding those features.

**Comment by bziemons** [comment]
Gate support will not be added until the BuildCraft rewrite. After that there needs to be a new request about adding gate support, if possible.
