### ISSUE TITLE
should Advanced Extractors extract things when they have no filter?

### ISSUE THREAD

**Issue by AartBluestoke** [RS485/LogisticsPipes#373]
Currently it looks like advanced extractors, when they have no filter set, do not send to default routes.

chest->advanced extractor mk 3 -> default sink -> chest

only things specified in the fitler get sent. nothing gets sent with a blank filter.

Not sure if this is intended behavior or a bug.

**Comment by Garagoth** [comment]
There is "Included" and "Excluded" option.
In "Exclude" mode and no filter set it extracts everything and sends to default route.
Just tested that (build 230)

Soo.... working properly IMHO...

G.
