### ISSUE TITLE
BC Power Provider Crash

### ISSUE THREAD

**Issue by DarkholmeTenk** [RS485/LogisticsPipes#374]
http://pastebin.com/ETCT5EXt

Using a slightly out of date (217) version, but that was the last one in which the LogisticsPowerProviderTileEntity was modified. Seems to only be the BC power provider causing a crash; the RF one (which is placed 2 blocks away) doesn't seem to. The RF one has been there for several days, but the BC one caused crashes after a day.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/d4ab1bf2ee1d56801bb9f4470e9db56cbb426bed
