### ISSUE TITLE
NullPointerException in NewGuiHandler.openGui

### ISSUE THREAD

**Issue by narc0tiq** [RS485/LogisticsPipes#377]
Using [Jenkins build 241](http://ci.thezorro266.com/view/Logistics%20Pipes/job/LogisticsPipes-Dev/241/) made from 56b15c2eb68d, replacing the Logistics Pipes version normally in TPPI v1.0.4 (build 183). This is a client-side crash only, server continued to operate normally.

[Crash report is on OpenEye](http://openeye.openmods.info/crashes/5d44222b83c7cb4cbd57d4c9e2c107dc). Bug is not present in build 236.

Steps to reproduce (possibly not minimal):
- Place ME interface
- Place Chassis Mk 2 connected to ME interface
- Install Provider module
- Install ItemSink module
- Open chassis pipe GUI with a right-click from a Crescent Hammer
- Click [!] next to the ItemSink to open its GUI.

**Comment by ArtForz** [comment]
Easier steps to reproduce:
Place Chassi Mk2+
Place ItemSink or Extractor in any slot except the first
Try to open module GUI.

I'm pretty sure we're missing a .setSlot() _somewhere_ in the new GUI path, but not quite sure where.
Likely candidate would be ChassiGUI.ProcessPacket

**Comment by davboecki** [comment]
That is correct. There is a setSlot missing.

**Comment by narc0tiq** [comment]
I updated to build 242 and can confirm the crash is no longer occurring. Thanks a bunch, guys!
