### ISSUE TITLE
[enhancement] Redstone control for Pipes

### ISSUE THREAD

**Issue by Sidorion** [RS485/LogisticsPipes#378]
A while ago I wanted to start or stop a RC boiler based on the amount of steam stored in a tank. I had a supplier pipe supplying fuel to the boiler. Because you can't turn off LPs I had to add an extra tank and a TE liquiduct which I then controlled instead.
That way I did not only loose the full fuel tank in the boiler, but also the amount in the fluiduct every time the boiler 'turned off', for this setting did not allow me to have just one bucket in the boiler (which would have been possible with a fluid supplier). Additionally the boiler kept boiling for a long period. 
This was a big overhead for a simple task and I'm sure, I'm not the only one who wanted to turn off pipes based on certain conditions.
So, it would be cool if single pipes could be turned on and off with redstone signal (Maybe with an upgrade). If turned off, all functionality stops except for basic routing, e.g. a provider pipe stops providing, a supplier won't do any requests, a basic pipe isn't default route or passive item sink any more, a crafting pipe won't craft.

**Comment by AartBluestoke** [comment]
You can place BC pipe gates on LP pipes, where there is a 'disable pipe' action. That will stop all actions on the pope, but not disable item flow through the pipe.

**Comment by AartBluestoke** [comment]
Please re open this if pipe gates do not have the functionality you are looking for.

**Comment by Sidorion** [comment]
Hello,

thanks alot for this info. Somehow I didn't think of gates, stupid me.
