### ISSUE TITLE
Bee analyzer pipe to stack when possible?

### ISSUE THREAD

**Issue by rowlock** [RS485/LogisticsPipes#380]
It would be great if the bee analyzer pipe was able to stack identical incoming drones in the Analyzer's inventory.

Right now, if more than six identical bees pass the pipe (a common occurrence with high productivity apiary/alveary setups) only the first six are pulled and analyzed, because they are inserted into individual inventory slots and fill the inventory. They are able to be manually stacked, however, leaving six bees in one slot and five free slots.

It would be great if the pipe added bees to stacks where possible, so an entire glut of drones could be queued for analysis. This would also save a lot of honey, because analyzing an individual bee costs the same as analyzing a whole stack. Potentially a six-times honey saving.

Thanks!

**Comment by davboecki** [comment]
Could you test what plain BC pipes do. IIRC they don't stack them either.

**Comment by Unknown-Zombie** [comment]
Just tested with plain BC pipe; it does not stack them up inside the analyzer.

**Comment by AartBluestoke** [comment]
Any reason we can't stack bees, I think we manage to stack them going into
chest, and the apairist pipe has its own item delivery code,..

**Comment by ArtForz** [comment]
Pretty sure getInventoryStackLimit() returning 1 is a decent reason.
