### ISSUE TITLE
Allow selection of which ore dictionary entry to use for item sinking

### ISSUE THREAD

**Issue by StarkRG** [RS485/LogisticsPipes#383]
Sometimes an item will have more than one ore dictionary entry and the primary one isn't necessarily the one a user wants to use to sort by.

Here's my current situation: I want to sort my Pam's Harvestcraft crops, as there are so many even a diamond chest from iron chests can't cope with them all. She creates ore dictionary entries based on the type of crop (veggies, fruits, nuts, raw meat, cooked meat, seeds, etc.) however they are often listed in several ore dictionary lists. For example, a plum is listed under both cropPlum (so it'll work in recipes from other mods calling for plums) and listAllFruit (so there can be a recipe calling for any type of fruit), but cropPlum is the primary list. I'd like to be able to shove all fruits into one chest, all veggies into another, all seeds into another, etc. The ore dictionary item sink module only grabs the primary entry and there doesn't seem to be any way to select another.

One possible solution would be to simply add ALL the entries and require the user to remove the ones they don't want. Ideally, though, there'd be a dropdown list of the available entries for the selected item.

**Comment by davboecki** [comment]
The OreDictionary was never designed for this. Modders who add several names for ItemTypes simply do it wrong. There is no way to get more than the first entry out of the OreDictioary.

**Comment by StarkRG** [comment]
How is it, then, that NEI is able to list multiple entries for any item that has them?

Example, this onion:
![2014-06-20_02 22 50](https://cloud.githubusercontent.com/assets/451657/3330197/23fa4ca8-f7ce-11e3-90e9-670196d6b109.png)

**Comment by OvermindDL1** [comment]
Yes the oredict is designed for multiple entries.  You should handle it properly.

**Comment by OvermindDL1** [comment]
An example that is just in base forge is Lapis, as gemLapis and dyeBlue.
