### ISSUE TITLE
Issue with LP and StargateTech2

### ISSUE THREAD

**Issue by LizzyTrickster** [RS485/LogisticsPipes#384]
When attempting to put a Fluid Supplier pipe next to a shield controller from StargateTech2 i get a java.lang.ArrayIndexOutOfBoundsException: 6
Console log: http://puu.sh/9v3ci/3686255194.txt
Crash report: http://puu.sh/9v3ie/2bb7190a38.txt

I reported this to StargateTech2's developer first and he said that the issue was on your end.
If you need any more information, tell me

**Comment by davboecki** [comment]
This is not an issue on our end. We ask the conected block for the unsided tank information (ForgeDirection.UNKNOWN). Stargatetech2 apears to be missing either a check for unknwon or needs to extend a some arrays.

**Comment by LordFokas** [comment]
What happens if connection on 'unkown' is refused?
Do you go for the side you're actually connected to?
