### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SneakingShadow** [RS485/LogisticsPipes#389]
In build 0.7.4.dev.172
Having multiple tesseracts connected to a single basic logistics pipe, causes the game to crash if you use a request table or pipe.

**Comment by AartBluestoke** [comment]
Tesseracts are only guaranteed to work when there is a 1 to 1 connection,
many->1 still shouldn't crash though....

In build 0.7.4.dev.172
Having multiple tesseracts connected to a single basic logistics pipe,
causes the game to crash if you use a request table or pipe.

—
Reply to this email directly or view it on GitHub
https://github.com/RS485/LogisticsPipes/issues/389.

**Comment by AartBluestoke** [comment]
LP does understand one way connections so it might be possible to support
this usage case.

**Comment by SneakingShadow** [comment]
I had two tesseracts, going to two different locations, connected to a single basic logistics pipe. And that caused a crash

**Comment by davboecki** [comment]
A crashreport would help.

**Comment by SneakingShadow** [comment]
It was 2 or 3 am, so I forgot it. Now i can't find it... It isn't in the crash-reports.. sorry..

**Comment by SneakingShadow** [comment]
I remember something about the gui..

**Comment by davboecki** [comment]
I'm sorry but without a crashreport we can't help you.
