### ISSUE TITLE
A crafting monitor like block from Ae

### ISSUE THREAD

**Issue by Doty1154** [RS485/LogisticsPipes#394]
I was in the irc and was told to post this here as a [Enhancement], but as i was trying to setup my crafting system it was getting quite annoyed having things just get lost and my not knowing what went south. So i thought maybe a block that would ping all crafting pipes and see what they were doing and would report what was with them. I realize that the crafting station block (Of sorts) has a crafting monitor upgrade but that only helps with that specific crafting session, i also know there are hud glasses but its really a pain when you have a huge system and going through all the crafting pipes checking. I just thought this was a interesting idea, i hope im not clogging this github report too much.

 Thanks for a awesome mod.

**Comment by bziemons** [comment]
Added in a2a50b6e465f09fcfec620ee07f3e2bbf7339985.
