### ISSUE TITLE
Logistics Pipes aren't connecting

### ISSUE THREAD

**Issue by PontiacFirebird** [RS485/LogisticsPipes#4]
Logistics Pipes aren't connecting, I have tried multiple versions of buildcraft and forge. I have also tried breaking and replacing.

This is using 
Forge: 6.6.0.516
BuildCraft: 3.4.2 and also happens with 3.4.1
Logistics Pipes: Dev  0.7.0.76

![2013-01-27_19 52 27](https://f.cloud.github.com/assets/2208781/101754/8b3387ec-68ee-11e2-924e-bb5f1630c964.png)

**Comment by AartBluestoke** [comment]
devs 75,76 were broken by a patch in 74; 77 fixes it.

On Mon, Jan 28, 2013 at 12:02 PM, 1971CHALLENGER
notifications@github.comwrote:

> Logistics Pipes aren't connecting, I have tried multiple versions of
> buildcraft and forge.
> 
> This is using
> BuildCraft: 3.4.2 and also happens with 3.4.1
> Logistics Pipes: Dev 0.7.0.76
> 
> [image: 2013-01-27_19 52 27]https://f.cloud.github.com/assets/2208781/101754/8b3387ec-68ee-11e2-924e-bb5f1630c964.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/RS485/LogisticsPipes-Dev/issues/4.

## 

“Getting information off the Internet is like taking a drink from a fire
hydrant.”
_– Mitchell Kapor_
