### ISSUE TITLE
Logistics pipes has trouble crafting Mekanism things

### ISSUE THREAD

**Issue by StarkRG** [RS485/LogisticsPipes#401]
After my server updated their version of logistics pipes in order to fix the fluid selection crash bug my network is now unable to make mekanism's steel casings. The request table also isn't able to make them. Additionally I've discovered it isn't able to use non-stackable items when crafting (or even request them properly from the network, I have to request them manually), before the update the request table was able to use most non-stackable items (though it had trouble with some)..

**Comment by StarkRG** [comment]
To clarify:
When I request the network craft a steel casing the steel and osmium ingots go into the logistics crafting table as normal, but the crafting table won't create the casing so the ingots just collect inside the crafting table and the request is never satisfied.

**Comment by ArtForz** [comment]
Tested here, seems to work fine.
Do you have the same ingots in the logicstics crafing table/pipe respective request table recipe area and inventory?
Neither Request Table nor Logistics Crafting Table are terribly oredict aware, in most cases they want the exact items set in the recipe area, not oredict substitutes.

**Comment by StarkRG** [comment]
I haven't changed anything between updates. It was working before, now it
doesn't. So, yes, I am using the correct ingots.

When I click the crafting request button in the request table it won't
request energy tablets from the logistics crafting table and pipe that are
set up for crashing energy tablets, instead it says that they aren't
available. However if I use the request pane on the right to request them
manually I can request them just fine.

As for the steel casing, the request occurs and the required items are sent
to the logistics crafting table but it doesn't actually craft anything.

The particular thing that isn't working in the request table is the rotary
condensentrator. All the required items are in the table's inventory, but
when I click to craft nothing happens.

**Comment by StarkRG** [comment]
The request table also won't make dynamic tank blocks (have the materials,
clicking the item to craft does nothing)

**Comment by StarkRG** [comment]
Advanced solar generator is also having this issue (I made one using the
request table before the update without a problem).

**Comment by ArtForz** [comment]
What LP build are you testing with? dev.280 should have fixed a good chunk of these.

**Comment by ArtForz** [comment]
Just set up a complete crafting chain, the only problematic part is the energy tablet.
Somehow LP considers the one NEI-shiftclick sticks in a LP ghost crafting grid different from the result of actually crafting one.
Using a actual crafted tablet to replace the one NEI put in the condensetrator recipe in the LCT and re-importing on that crafting pipe made things work.
Same thing in the request table. NEI in condensetrator recipe, request a set - "Missing: 1 Energy Tablet". request energy tablet in orderer interface - works. Use that tablet to replace the one in the grid, request a set again - works.
Edit:
Solar generators show the exact same problem. NEIed one != crafted one...

**Comment by StarkRG** [comment]
Ok, you were right, the 285 update fixed all the issues except the energy tablet, which, as you say, works when I use a real energy tablet to fix the recipe. (our server probably won't be doing any updates for a while so I hope that  there isn't anything more too terribly broken)
