### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by jztmanyl** [RS485/LogisticsPipes#407]
Hello, I recently installed mystcraft and logisticspipe to my crackpack server, the server runs fine with both mods installed, but the clients crashes on minecraft load screen, we're running 0.7.4 dev.290 of logisticspipes.
I have uploaded the crash report to pastebin:
http://pastebin.com/F9xS6569 

EDIT: Client runs fine without logisticspipes

**Comment by davboecki** [comment]
`LogisticsPipes|Main{${lp.version.full}} [Logistics Pipes] (LogisticsPipes-MC1.6.4-0.7.4.dev.290.jar) Unloaded->Errored`
You are using a jar that was not compiled by us. If you want support for your problem please use the jar's provided by our jenkins.

**Comment by jztmanyl** [comment]
Actually I used this link
http://ci.thezorro266.com/job/LogisticsPipes-Dev/ 
Which is linked from the official logisticspipes minecraftforum thread

**Comment by davboecki** [comment]
Did you remove the Meta-Inf information?

**Comment by jztmanyl** [comment]
No, if you mean in the LogisticsPipes jar, if you mean in the minecraft jar I use the atlauncher and I think it does it by default.

**Comment by davboecki** [comment]
Could you redownload the LP jar and try again?

**Comment by jztmanyl** [comment]
Yea give me a sec

**Comment by jztmanyl** [comment]
I am gonna try to use a manual install but the same thing happend with a fresh LP

**Comment by davboecki** [comment]
Could you please post a full fml log.

**Comment by jztmanyl** [comment]
So what I did was to place the LP in mods instead of the default location jarmods that atlauncher places jar mods in, and it seemed to fixed it. I dunno what the problem was and I hope I was to any useful information.

**Comment by davboecki** [comment]
If it works that way it's something the ATlaucher does which we can't fix. That's up to them.
