### ISSUE TITLE
Crash Item Damage out of range

### ISSUE THREAD

**Issue by LakyPL** [RS485/LogisticsPipes#408]
Hi. Can you help ?

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 15.07.14 21:41
Description: Ticking tile entity

java.lang.IllegalArgumentException: Item Damage out of range
    at logisticspipes.utils.item.ItemIdentifier.get(ItemIdentifier.java:250)
    at logisticspipes.utils.item.ItemIdentifier.get(ItemIdentifier.java:268)
    at logisticspipes.utils.InventoryUtil.getItemsAndCount(InventoryUtil.java:61)
    at logisticspipes.modules.ModuleActiveSupplier.createSupplyRequest(ModuleActiveSupplier.java:308)
    at logisticspipes.modules.ModuleActiveSupplier.tick(ModuleActiveSupplier.java:218)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:460)
    at buildcraft.transport.TileGenericPipe.func_70316_g(TileGenericPipe.java:178)
    at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_70316_g(LogisticsTileGenericPipe.java:111)
    at net.minecraft.world.World.func_72939_s(World.java:2209)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:550)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at logisticspipes.utils.item.ItemIdentifier.get(ItemIdentifier.java:250)
    at logisticspipes.utils.item.ItemIdentifier.get(ItemIdentifier.java:268)
    at logisticspipes.utils.InventoryUtil.getItemsAndCount(InventoryUtil.java:61)
    at logisticspipes.modules.ModuleActiveSupplier.createSupplyRequest(ModuleActiveSupplier.java:308)
    at logisticspipes.modules.ModuleActiveSupplier.tick(ModuleActiveSupplier.java:218)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:460)
    at buildcraft.transport.TileGenericPipe.func_70316_g(TileGenericPipe.java:178)
    at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_70316_g(LogisticsTileGenericPipe.java:111)

-- Tile entity being ticked --
Details:
    Name: logisticspipes.pipes.basic.LogisticsTileGenericPipe // logisticspipes.pipes.basic.LogisticsTileGenericPipe
    Block type: ID #516 (tile.null // logisticspipes.pipes.basic.LogisticsBlockGenericPipe)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (184,147,277), Chunk: (at 8,9,5 in 11,17; contains blocks 176,0,272 to 191,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Actual block type: ID #516 (tile.null // logisticspipes.pipes.basic.LogisticsBlockGenericPipe)
    Actual block data value: 0 / 0x0 / 0b0000
    LP-Version: 0.7.4.dev.291:false
    Pipe: logisticspipes.pipes.PipeItemsSupplierLogistics
    Transport: logisticspipes.transport.PipeTransportLogistics
    Router: ServerRouter: {ID: 20, UUID: 473b2fca-b995-4302-9e1d-17db49af3c16, AT: (0, 184, 147, 277), Version: 1), Destroied: false}
    stillNeedReplace: false
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2209)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:550)

-- Affected level --
Details:
    Level name: world2
    All players: 1 total; [EntityPlayerMP['LakyPL'/251, l='world2', x=163,37, y=56,00, z=302,30]]
    Chunk stats: ServerChunkCache: 749 Drop: 0
    Level seed: 6592781234626770946
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (236,64,216), Chunk: (at 12,4,8 in 14,13; contains blocks 224,0,208 to 239,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 8499287 game time, 72752 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 67411 (now: false), thunder time: 159169 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 8 (amd64) version 6.2
    Java Version: 1.7.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 883027456 bytes (842 MB) / 1826619392 bytes (1742 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G
    AABB Pool Size: 3034 (169904 bytes; 0 MB) allocated, 2772 (155232 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 18, tcache: 0, allocated: 6, tallocated: 62
    FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 67 mods loaded, 67 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{6.4.49.965} [Forge Mod Loader](minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{9.11.1.965} [Minecraft Forge](minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppliedEnergistics-Core{rv14.finale2} [AppliedEnergistics Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Aroma1997Core{1.0.1.0} [Aroma1997Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{0.9.0.9} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    denLib{3.1.35} [denLib](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PowerCrystalsCore{1.1.8} [PowerCrystals Core](PowerCrystalsCore-1.1.8-9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct-Preloader{0.0.1} [Tinkers Corestruct](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SPCForge{1.1} [SPC Forge](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    betterstorage{0.7.3.38} [BetterStorage](1.6.4.BetterStorage_0.7.3.38.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bspkrsCore{v4.3(1.6.4)} [bspkrsCore]([1.6.4]bspkrsCorev4.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArmorStatusHUD{v1.15(1.6.4)} [ArmorStatusHUD]([1.6.4]ArmorStatusHUDv1.15.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_bspkrsCore{v4.3(1.6.4)} [bspkrsCore]([1.6.4]bspkrsCorev4.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TreeCapitator{Forge 1.6.4.r06} [Treecapitator]([1.6.4]TreeCapitator.Forge.1.6.4.r06.Universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    nohero_morehealth{5.3} [More Health Forge]([Forge-1.6.4]More Health Enhanced 5.3 Universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{4.2.2} [BuildCraft](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{4.2.2} [BC Factory](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{4.2.2} [BC Transport](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{4.2.2} [BC Silicon](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    APUnofficial{2.6.0} [Additional Pipes](AdditionalPipes2.6.0-BC4.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2{2.0.299-experimental} [IndustrialCraft 2](industrialcraft-2_2.0.299-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AdvancedMachines{5.2.3} [IC2 Advanced Machines Addon](AdvancedMachines_1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AdvancedPowerManagement{1.2.1-IC2-2.0.238-experimental} [Advanced Power Management](APM-IC2-Ex-1.2.1-IC2-2.0.238-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppliedEnergistics{rv14.finale2} [Applied Energistics](appeng-rv14-finale2-mc16x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Aroma1997CoreHelper{1.0.1.0} [Aroma1997Core|Helper](Aroma1997Core MC.1.6.4 v.1.0.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Aroma1997s Dimension{1.0.2.11} [Aroma1997's Dimensional World](Aroma1997s Dimensional World MC.1.6.4 v.1.0.2.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Backpack{1.28.37} [Backpack](backpack-1.28.37-1.6.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BattleTowers{1.4.2} [Battle Towers](BattleTowers_1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{4.2.2} [BC Builders](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{4.2.2} [BC Energy](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BCTools{1.4-a-17} [Buildcraft Tools](bcTools-v1.4-a-17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BetterChests{1.1.0.0} [BetterChests](BetterChests MC.1.6.4 v.1.1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.5.3} [BiblioCraft](BiblioCraft[v1.5.3].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Additional-Buildcraft-Objects{1.0.6.182} [Additional Buildcraft Objects](buildcraft-Z-additional-buildcraft-objects-1.0.6.182.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CompactSolars{4.4.19.209} [Compact Solar Arrays](compactsolars-universal-1.6.4-4.4.19.209.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CompactWindmills{1.0.2.2} [CompactWindmills](CompactWindmillsMC.1.6.4v.1.0.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ComputerCraft{1.57} [ComputerCraft](ComputerCraft1.57.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CCTurtle{1.57} [ComputerCraft Turtles](ComputerCraft1.57.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    craftguide{1.5.2} [CraftGuide](CraftGuide-1.6.7.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    eplus{1.16.5b} [Enchanting Plus](EnchantingPlus-1.16.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderStorage{1.4.3.6} [EnderStorage](EnderStorage-1.6.4-1.4.3.6-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forestry{2.3.0.7} [Forestry for Minecraft](forestry-A-2.3.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2NuclearControl{1.6.2c} [Nuclear Control](IC2NuclearControl-1.6.2c-ic2-experimental.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.56} [Inventory Tweaks](InventoryTweaks-MC1.6.2-1.56-b77.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{5.4.1.642} [Iron Chest](ironchest-universal-1.6.4-5.4.1.642.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LogisticsPipes|Main{0.7.4.dev.291} [Logistics Pipes](LogisticsPipes-MC1.6.4-0.7.4.dev.291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AdvancedSolarPanel{3.4.3} [Advanced Solar Panels](mod_AdvancedSolarPanels_3_4_3_IC_EXP.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MoreSwordsMod{2.5.5} [More Swords Mod](More Swords Mod 2.5.5. For 1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NetherOres{1.6.2R2.2.2} [Nether Ores](NetherOres-2.2.2-55.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Railcraft{8.2.0.0} [Railcraft](Railcraft_1.6.2-8.2.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PowerConverters{1.6.4R2.3.2B1} [Power Converters](PowerConverters-1.6.4-22.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMultipart{1.0.0.191} [Forge Multipart](ForgeMultipart-universal-1.6.4-1.0.0.191.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Core{4.0.5.12} [Project: Red-Core](ProjectRedBase-1.6.4-4.0.5.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.6.X_1.5.1} [Tinkers' Construct](TConstruct_1.6.4_1.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Compatability{4.0.5.12} [ProjectRed-Compatability](ProjectRedCompat-1.6.4-4.0.5.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Integration{4.0.5.12} [ProjectRed-Integration](ProjectRedIntegration-1.6.4-4.0.5.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Transmission{4.0.5.12} [ProjectRed-Transmission](ProjectRedIntegration-1.6.4-4.0.5.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Exploration{4.0.5.12} [ProjectRed-Exploration](ProjectRedWorld-1.6.4-4.0.5.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Illumination{4.0.5.12} [ProjectRed-Illumination](ProjectRedWorld-1.6.4-4.0.5.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    QuantumCraft{1.02_mc164} [qCraft](qCraft1.02_mc164.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    QuarryPlus{1.5.5.3} [QuarryPlus](QuarryPlus-1.6.4-1.5.5.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TwilightForest{1.20.5} [The Twilight Forest](twilightforest-1.6.4-1.20.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AS_UpdateCheck{1.1.1} [AtomicStryker Update Check Mod](UpdateCheckerMod_1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_ZanMinimap{0.9.4} [Zan's Minimap](ZansMinimap1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    McMultipart{1.0.0.191} [Minecraft Multipart Plugin](ForgeMultipart-universal-1.6.4-1.0.0.191.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMicroblock{1.0.0.191} [Forge Microblocks](ForgeMultipart-universal-1.6.4-1.0.0.191.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct Environment: Sane and ready for action. Bugs may be reported.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 1470 (82320 bytes; 0 MB) allocated, 1338 (74928 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['LakyPL'/251, l='world2', x=163,37, y=56,00, z=302,30]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by bziemons** [comment]
No clue where that comes from, does anyone get this crash with any of the newer versions?

**Comment by SoraNoIseki** [comment]
I got the same crash report with build 82, buildcraft version is 6.1.8 stable, pls help...

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 14-11-20 09:44
Description: Ticking block entity

java.lang.IllegalArgumentException: Item Damage out of range
    at logisticspipes.utils.item.ItemIdentifier.get(ItemIdentifier.java:237)
    at logisticspipes.utils.item.ItemIdentifier.get(ItemIdentifier.java:255)
    at logisticspipes.utils.InventoryUtil.getItemsAndCount(InventoryUtil.java:61)
    at logisticspipes.modules.ModuleActiveSupplier.createSupplyRequest(ModuleActiveSupplier.java:310)
    at logisticspipes.modules.ModuleActiveSupplier.tick(ModuleActiveSupplier.java:220)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:423)
    at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_145845_h(LogisticsTileGenericPipe.java:180)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at logisticspipes.utils.item.ItemIdentifier.get(ItemIdentifier.java:237)
    at logisticspipes.utils.item.ItemIdentifier.get(ItemIdentifier.java:255)
    at logisticspipes.utils.InventoryUtil.getItemsAndCount(InventoryUtil.java:61)
    at logisticspipes.modules.ModuleActiveSupplier.createSupplyRequest(ModuleActiveSupplier.java:310)
    at logisticspipes.modules.ModuleActiveSupplier.tick(ModuleActiveSupplier.java:220)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:423)
    at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_145845_h(LogisticsTileGenericPipe.java:180)

-- Block entity being ticked --
Details:
    Name: logisticspipes.pipes.basic.LogisticsTileGenericPipe // logisticspipes.pipes.basic.LogisticsTileGenericPipe
    Block type: ID #618 (tile.null // logisticspipes.pipes.basic.LogisticsBlockGenericPipe)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-324,100,292), Chunk: (at 12,6,4 in -21,18; contains blocks -336,0,288 to -321,255,303), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Actual block type: ID #618 (tile.null // logisticspipes.pipes.basic.LogisticsBlockGenericPipe)
    Actual block data value: 0 / 0x0 / 0b0000
    LP-Version: 0.8.2.82:false
    Pipe: logisticspipes.pipes.PipeItemsSupplierLogistics
    Transport: logisticspipes.transport.PipeTransportLogistics
    Router: ServerRouter: {ID: 1, UUID: 90401dd6-d20c-4132-b27d-e6f7b80de193, AT: (0, -324, 100, 292), Version: 1), Destroied: false}
    stillNeedReplace: false
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

**Comment by SoraNoIseki** [comment]
I think that i found the reason: I connect a Supplier pipe to a Kinetic Wind Generator of ic2 expermental(build 650), and there is an iron rotor with 41% rotorhealth inside the generator, then MC crashes. But it doesn't happen while no rotor or a 99% healthy rotor inside the generator. 

I hope this cound help you to fix the problem.

**Comment by davboecki** [comment]
Should be fixed by: https://github.com/RS485/LogisticsPipes/commit/14a53c5354c621807cecaa33d44c5b6e8388db77

**Comment by bziemons** [comment]
As a note: this fix is only implemented in LP 0.9.x

**Comment by F3UR10** [comment]
Hi, is there a opportunity to get a download for a pre release version of LP0.9.X where this bug is fixed?

**Comment by bziemons** [comment]
@F3UR10 Yes, apparently now there is. Have a look at http://ci.thezorro266.com/job/LogisticsPipes1.7-0.9/

**Comment by F3UR10** [comment]
@theZorro266 thx for that :) it saved my world (had a crash with 0.8.3.108, loaded world with 0.9. than back). Now i know which item it causes at my server. Its the Turning Blank from IC2 experimental. After I moved it to my AE2 Storage server crashed.
