### ISSUE TITLE
Toggling between displayed HUDs or disabling them using the HUD goggles

### ISSUE THREAD

**Issue by techno156** [RS485/LogisticsPipes#409]
I recently set up a literal wall of barrels in my machine room due to issues with a distinct lack of storage, and made a set of Logistics HUD Goggles. Upon wearing them, I was flooded with GUIs from the wall of barrels, and the other pipes nearby, creating a large amount of lag. I am wondering if it is possible to either bind a key to disable HUD displays, or a filter of some sort that could allow for the interface of a certain pipe be selected, or a pipe that is being 'selected' by the player via use of the crosshair.

**Comment by davboecki** [comment]
If you take the HUD into your hand and click it you are able to define what HUD types will be shown. If you want to highlight one HUD sneak/press shift and the HUD you are looking at will become the focus.

**Comment by AartBluestoke** [comment]
I learn things about LP every day.

Is this documented anywhere?

**Comment by davboecki** [comment]
I don't think it is.

**Comment by bziemons** [comment]
Still: It would be nice to enable/disable the HUD while wearing it, because laziness. And/Or configure it while wearing it.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
