### ISSUE TITLE
supplier on vanila furnacerequests items when it can not sink them

### ISSUE THREAD

**Issue by AartBluestoke** [RS485/LogisticsPipes#41]
place a supplier on the top of a vanilla furnace. place charcoal in the top and bottom.
set a supply of wood to the furnace. wood will be requested and bounced (main 93)

**Comment by davboecki** [comment]
a supplyer is A Basic pipe. It doesn't check the inventory it's targeting for space. It only count's the items to see what's missing. Chassie pipes are the only pipes that check for space before sinking items.
