### ISSUE TITLE
accept power from a tesseract as if it was a power junction, for power routing

### ISSUE THREAD

**Issue by AartBluestoke** [RS485/LogisticsPipes#410]

**Comment by davboecki** [comment]
How is this supposed to work? Because the LP power system is based on requesting power from a buffered provider, and the tesseract don't realy has a buffer.

**Comment by StarkRG** [comment]
It really isn't needed since the pipes will communicate and transmit power between each other through the tesseract anyway, as long as your LP system has power and is chunk loaded the pipes on the other side of the tesseract will have power too.

**Comment by AartBluestoke** [comment]
2 parts: a tesseract should allow power to be routed into it (I think it
would already do so)
When next to a tesseract a pipe with a power upgrade gains a small power
buffer purely for recording power from the tesseract.... Not sure how that
one would work.

Alternatively, fake it. Render the line through the tesseract, and just
draw the power straight from the source.

**Comment by davboecki** [comment]
I would take way two while only aloowing it if the tesseract is configurred to transport power. But I don't know if the current system will take that way easily.

**Comment by bziemons** [comment]
I think it is actually fine as it is right now. Any other opinions?
E.g. Power can get routed through tesseracts, if there is an LP pipe on each side.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
