### ISSUE TITLE
[suggestion] Generalize Electric Manager and Electric Buffer modules

### ISSUE THREAD

**Issue by StarkRG** [RS485/LogisticsPipes#411]
It would be great to be able to use these modules with any chargable items from other mods than just IC2. For example things charged with TE's RF power (such as Tinker's Construct tools with the redstone flux modifier), or Mekanism's tools. Additionally it should be able to work with things that don't charge with energy such as Mekanism's hydrogen-charged jetpack and oxygen=filled scuba tank or galacticraft's oxygen tanks.

Because some mods don't show a fully undamaged item when it's actually fully charged (but others do), you'd have to have some system of removing things that are showing 99% undamaged after a short period of not changing.

This change would have to coincide with a recipe change or add additional recipes for other mods

**Comment by bziemons** [comment]
Those two modules were done by a previous contributor. Basically they are not being maintained at all.
I would also like to hear more opinions about this..
I disagree when it comes to more and more integrations with other mods.

**Comment by StarkRG** [comment]
I'd say two things could be done to improve integration without requiring special coding for each mod.

One is a damage-based system (maybe as upgrades for item sink (regular, dictionary, and mod-based) and extractor modules) where users select the damage level, and greater than or less than (eg. Set to 90%, and less than will activate the module for items that have a damage of less than 90%)

Another would be to expose NBT data and use that to sink or extract items. Accept an item as a template, then asks the users to choose which NBT tags to look for and values to trigger on.

**Comment by bziemons** [comment]
Hell, that damage-based item sink idea sounds awesome :)
Maybe not as an upgrade for everything, but giving it one item and telling it a min/max value for damage sounds fair and useful.
