### ISSUE TITLE
What work has to be done on the 1.7 port?

### ISSUE THREAD

**Issue by asiekierka** [RS485/LogisticsPipes#412]
I looked at the mc17 repo and I'm not sure where to pick up, while I really want LP for my 1.7.10 pack.

**Comment by davboecki** [comment]
That's probably a question for @ArtForz.
But iirc everything needs to be checked. The pipesystem is supposed to get some work to lose it away from BC. the network code needs some work, the packet compressor and decompressors. And there is probably a lot more to do.

**Comment by asiekierka** [comment]
The BuildCraft deconnection is not important to me, as I am forking BuildCraft to keep just its pipes.

My problem is that I want to use LP ASAP, even if somewhat buggy, and I want to know, as a developer, what's left to do for it to work. Right now, putting the code in Eclipse gives me about 1.8k errors still :/

**Comment by davboecki** [comment]
You use the mc17 branch?

**Comment by asiekierka** [comment]
Yes. I guess I'll try re-creating it, maybe I broke something during the setup.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/issues/419
