### ISSUE TITLE
LG don't craft bronze ingots.

### ISSUE THREAD

**Issue by bschoenmaeckers** [RS485/LogisticsPipes#414]
when I request bronze ingots the tin and copper ingots are going into the LG crafting table but the table craft nothing. the crafting pipe is working because  sparkles.

**Comment by davboecki** [comment]
screenshots please.

**Comment by AartBluestoke** [comment]
I would suspect an ore dictionary issue.

**Comment by bschoenmaeckers** [comment]
here same screenshots:
![1](https://cloud.githubusercontent.com/assets/7943856/3654798/d94956d8-1170-11e4-8456-9860d8944342.jpg)
![2](https://cloud.githubusercontent.com/assets/7943856/3654799/d949c870-1170-11e4-999f-8e848bc50220.jpg)
![4](https://cloud.githubusercontent.com/assets/7943856/3654800/d949e76a-1170-11e4-9fa5-01ab9ed47141.jpg)

**Comment by bschoenmaeckers** [comment]
I think it is a bug in logistics pipes shapeless crafting
it also has problems with crafting of fluix dust.

**Comment by davboecki** [comment]
Did you make sure, that the items inside the crafting table inventory match those inside the recipe area. Not only the name but also ID and damage value?

**Comment by bschoenmaeckers** [comment]
Yes I did.

**Comment by AartBluestoke** [comment]
That looks like a reasonable sized network. Would you be able to collect
some performance stats on it?

If you are, and you are using sun Java then jvisualvm, found as part of the
sun Java sdk, recording in cpu 'sample' mode (maximum frequency) would
provide the most information for a minimal performance impact.

When using jvisualvm, you should be aware that 'profiling' an application
has a significant performance penalty, which can only be reversed by
restarting the app. ( that performance change would obscure the stats we
are trying to collect)

**Comment by bschoenmaeckers** [comment]
I have done what you said. I hope I did it correctly. I made an snapshot of the CPU sample thing in jvisualvm when I loaded my world and opened my inventory while standing in the middle of my base.
link: https://www.dropbox.com/s/we9k3ad6js04pev/logistics%20pipes%20snapshot%20file.nps

**Comment by bziemons** [comment]
Is this still an issue? I didnt have any issues with crafting on the latest versions.

**Comment by bschoenmaeckers** [comment]
I haven't tried it.

**Comment by hron84** [comment]
@theZorro266 
If it makes any sense, I checked it in Flux Galaxy modpack few months ago and I had no issues with this crafting. ATM I have no idea which version is applies to FG, but I think its something 0.8.x
