### ISSUE TITLE
Missing recipe for Active Supplier Module

### ISSUE THREAD

**Issue by HadesDurin** [RS485/LogisticsPipes#415]
I updatet to latest 0.7.4 dev 292 from 0.7.4 dev 242 and notice in changes log, that an active supplier module was added.
I cannot find any information about this module in game (Nei and craftguide)...

**Comment by davboecki** [comment]
The module was added to the code but it is not activated inside the builds you can find on jenkins. So there is also no recipe for it.

**Comment by Flexico** [comment]
Does it function though? I could just add a recipe in MineTweaker or something if so.

**Comment by davboecki** [comment]
You can try. I know that some people are using it and we didn't have any reports of problems. And my tests didn't indicate any problems.

**Comment by hron84** [comment]
@davboecki it is already active in 0.8 or 0.9 branch?

**Comment by bziemons** [comment]
@hron84 if I may answer: it is in both versions.
