### ISSUE TITLE
Buildcraft Pipe -> Fluid Provider Pipe

### ISSUE THREAD

**Issue by HadesDurin** [RS485/LogisticsPipes#416]
I update to latest 074 dev #292 and have a problem with Fluid Provider Pipes they are not connecting to Gold Fluid Pipes from Buildcraft and if i connect the Fluidm Provider direct to the Tank no liquid gets out...
![screenshot_1](https://cloud.githubusercontent.com/assets/5231067/3663229/5b5a6cba-11d1-11e4-8b19-c127ba9a47d9.jpg)

**Comment by davboecki** [comment]
They never worked that way. And they never worked on the bottom of railcraft tanks. You need to put them on the side of railcraft tanks. (Limitation from railcraft)
