### ISSUE TITLE
[Suggestion] Add 'dumb' pipes that can be made opaque

### ISSUE THREAD

**Issue by K-tron** [RS485/LogisticsPipes#418]
I recently started playing around with a minecraft server running on an old computer laying round collecting dust, and am quickly coming to the realization the lag that buildcraft causes.  It would be nice to have 'dumb' pipes that can be made opaque like all other logistics pipes in order to help reduce lag.  I am thinking a basic logistics pipe in a crafting table gives you 8 'dumb' logistics pipes that can only accept an opaque upgrade.  I know if i downgrade thermal expansion I can use itemducts, but I prefer my pipe system be uniform in size/look.

**Comment by bziemons** [comment]
See LP config: B:OpaquePipes
Although I am not sure if that is it actually, what makes you lag.

**Comment by K-tron** [comment]
Most of the lag is probably coming from the BC pump I have running in the nether.  I have opaque logistics pipes turned on via the config file, but it is the BC pipes connecting them that 'dumb' logistics pipes would be nice to use as a low lag consistent look replacement.

**Comment by davboecki** [comment]
Why don't you just turn of BC's dynamic rendering ?

**Comment by K-tron** [comment]
I did not realize that BC had that option, thanks.
