### ISSUE TITLE
[1.7.10][IC2 Enet Error with power Junction]

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#422]
Got this crash when i tried placing an Powerjunction into the World.
Using IC2 Build 2.2.596 experimental
Latest LP Jar compiled

**Comment by SonOfTheStars** [comment]
http://pastebin.com/xs6jLGVj

**Comment by davboecki** [comment]
The mc17 branch is not ready to be used with other mods. See: https://github.com/RS485/LogisticsPipes/issues/419
