### ISSUE TITLE
(1.7.10) Jabba and Waila incompatability 

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#425]
When placing a Logistics Chassis behind a Jabba barrel my entire server crashed with this error: http://pastebin.com/PhchzPaQ

I am using the latest version of Logistics Pipes on a standard Forge server.

When testing in single player I received this crash after placing a chassis behind a regular chest: http://pastebin.com/FuAmsYUH

This one seems to be a Waila incompatibility.

**Comment by davboecki** [comment]
Should both be fixed.

**Comment by ghost** [comment]
You have to be one fastest devs, thanks a million.
