### ISSUE TITLE
Craft with objects wich have durability

### ISSUE THREAD

**Issue by FirstCrusader** [RS485/LogisticsPipes#427]
We want to craft things wich need objects with durability, like with Greg Tech wrenches, but we have the issue, that the fuzzy crafting table build new wrenches for each item to craft and we thought, that we can extract the wrenches with byproduct extractor upgrades but this don´t work.

Is there an Bug with the upgrade, is it not posssible like this way or ist there another way to craft such recipes (e.g. Iron Bars with Greg Tech in 1.6.4)

we recently tried also the cleanup Upgrade but it doesnt work anyway

Sorry if i did some language mistakes :)

**Comment by davboecki** [comment]
The best way to do something like this is to use a supplyer pipe. Don't include the tool that will get damage in the crafting pipe. The supplyer pipe will request a new tool once the old one is used. IIRC you don't even need a fuzzy crafting table for that way.
