### ISSUE TITLE
Fix AE2 integration not getting access to the AE2 stored items.

### ISSUE THREAD

**Issue by davboecki** [RS485/LogisticsPipes#429]
@AlgorithmX2 What is the correct way to access an AE2 interface from LP without knowing what player is trying to access the AE2 interface?

**Comment by AlgorithmX2** [comment]
You'll probably start here,
https://github.com/AlgorithmX2/Applied-Energistics-2-API/blob/28f21f334f117630ad4344bfd79897ab9cd3401e/implementations/tiles/ITileStorageMonitorable.java#L13

and get a IMEMonitor, when extract or injecting items you'll use,
https://github.com/AlgorithmX2/Applied-Energistics-2-API/blob/28f21f334f117630ad4344bfd79897ab9cd3401e/networking/security/MachineSource.java

for your IActionHost since you don't implement the AE2 grid, you'll want to make a dummy class that uses the data the IGridHost in your talking to, and provide getActionableNode as the node for the specific side face your interfacing with.

I believe this should work without any issues.

**Comment by davboecki** [comment]
I've gotten untill https://github.com/RS485/LogisticsPipes/blob/mc17/common/logisticspipes/proxy/specialinventoryhandler/AEInterfaceInventoryHandler.java#L34 .
But whenever I use this https://github.com/RS485/LogisticsPipes/blob/mc17/common/logisticspipes/proxy/specialinventoryhandler/AEInterfaceInventoryHandler.java#L80 to get the Items the system has I don't get anything because I don't provide a player. And that let's AE2 reject my request because it couldn't check for permission. But I could be doing something wrong...

**Comment by AlgorithmX2** [comment]
Your fake IActionHost should provide the data of the host your talking to, it will do the security stuff for you.

Also don't use ForgeDirection.UNKNOWN, you'll want to make sure your talking to the correct side of the block, otherwise you won't be able to talk to the multipart stuff properly.

**Comment by davboecki** [comment]
How do I get the Host Data of the connected Tile. Is there an interface?

The part with the Direction sounds more easy than it actually is for LP at that level. Let's see how I can fix that.

**Comment by AlgorithmX2** [comment]
Yeah, you'll want to use the IGridHost on the same tile as the ITileStorageMonitorable, more often then not these will be paired.

**Comment by davboecki** [comment]
OK, thanks I will try that.
Is there a way in the api to trigger a crafting task from the ME Interface (from LP). I'm thinking about allowing the user to trigger a crafting task from LP out (To finally get some sort of crafting integration from LP with AE)

**Comment by AlgorithmX2** [comment]
see,
https://github.com/AlgorithmX2/Applied-Energistics-2-API/tree/rv1/networking/crafting

and specifically,
https://github.com/AlgorithmX2/Applied-Energistics-2-API/blob/rv1/networking/crafting/ICraftingGrid.java

those are the AE2 crafting API entry points.

**Comment by davboecki** [comment]
OK thanks. The Inventory Access works now. Thanks for the help.

**Comment by tomevoll** [comment]
is accessing crafting from LP implemented yet? i can see all stored items with a provider on AE interface but none of the items that has run out and need crafting is visible

**Comment by davboecki** [comment]
No crafting is not implemented.

**Comment by AartBluestoke** [comment]
Do you know if ae has a notification system, as one passivity would be to
just issue crashing requests, and just push the responsibility for
ingredients to the ae side, when it is used for crafting?

**Comment by bziemons** [comment]
Doesn't "OK thanks. The Inventory Access works now. Thanks for the help." mean that the issue can be closed? @davboecki
