### ISSUE TITLE
[Suggetion] crafting upgrades on chassis pipes

### ISSUE THREAD

**Issue by AnimeniacYuuto** [RS485/LogisticsPipes#431]
It would be awesome if you could apply crafting upgrades to chassis pipes so the crafting modules could have access to them, or perhaps just a way to apply the upgrades to the modules them selves. This would be extremely helpful for automating ore processing as well as dealing with ISided Machines.

**Comment by davboecki** [comment]
Implemented with upgrades by modules in v0.9
