### ISSUE TITLE
Request table needs 'clear recipe' button

### ISSUE THREAD

**Issue by AT611** [RS485/LogisticsPipes#433]
Just like one in AE crafting terminal

**Comment by bziemons** [comment]
Yep, this is actually accepted.

**Comment by hron84** [comment]
@davboecki is there any ETA for this?

**Comment by davboecki** [comment]
No currently not.

**Comment by 1n5aN1aC** [comment]
Added by https://github.com/RS485/LogisticsPipes/commit/2d49c8e81745e60106190fa2b26c8dbd84e65944  and it works pretty darn awesome, except for the minor visual bug in #824 Still probably one of the best quality-of-life improvements in a while.
