### ISSUE TITLE
ME Interface and disappearing Chassis

### ISSUE THREAD

**Issue by Sohala123** [RS485/LogisticsPipes#434]
One of my player base was trying to put a Provider module into a Mk2 chassis, that was connected to an ME interface. The result was both of them disappearing.

I went on to try it with each chassis with the provider module and two other random ones (in this case, extractor and bee analyzer), each time the chassis vanished after adding the module.

Best I can tell nothing else does this. We are currently running on your 1.6.4-0.7.4 dev 289 build.

**Comment by Confuseh** [comment]
In addition, that includes Provider and Provider Mk2 pipes, but the catch is that someone have ME Interface connected to Provider pipes and they don't disappear. 

EDIT: I tried to place ME Interface disconnected from ME System, pipe didn't disappear but as soon I connected it to ME System via ME Cables, pipe automatically gone.

**Comment by davboecki** [comment]
We are going to need a video or some screenshots and some logs becuse this is something totaly unexpected.

**Comment by Confuseh** [comment]
Ok, this is getting random, I tried again to connect chassis with provider module to ME Interface and all the sudden it didn't disappear...

**Comment by bziemons** [comment]
If this happens again, please give us some more information and open a new issue.
