### ISSUE TITLE
(bug) show content is not working on provider module 

### ISSUE THREAD

**Issue by loordgek** [RS485/LogisticsPipes#436]
but it is working w/ the provider pipe
didn't test provider module MK2\
using logisticspipes-0.8.0.51.jar

**Comment by davboecki** [comment]
logs, modlist and some screenshots please.

**Comment by loordgek** [comment]
https://www.youtube.com/watch?v=WrgRCxITcj0&feature=youtu.be
http://paste.ee/p/PU2yH

**Comment by davboecki** [comment]
OK that looks interesting. Will take a look at that when I find the time.
