### ISSUE TITLE
update to RF (for BC 6.1.1)

### ISSUE THREAD

**Issue by loordgek** [RS485/LogisticsPipes#437]
BC has updated to the RF power system 
https://github.com/BuildCraft/BuildCraft/commit/ccaeffe76343604b3a383ced9fb2a7ca21534f3e

Edit (by davboecki) [from other issue]:
yes i know you have RF support
but the MJ api is removed (for 6.1.1) BC is now using RF

**Comment by davboecki** [comment]
We already support RF since mc 1.6. And we currently only support BC 6.0.x versions.

**Comment by davboecki** [comment]
And what sould that change for us? What do you think needs to be done if BC moves to that API. Except that we will have to update to BC 6.1.x at some point?
