### ISSUE TITLE
lp items dont show in ae

### ISSUE THREAD

**Issue by popcorn9499** [RS485/LogisticsPipes#439]
I can't find lp items in ae when attaching a request pipe to a regular interface but when i use a provider to see the ae items in lp it works. so I'll be happy when this is fixed thank you

**Comment by davboecki** [comment]
What MC version are you using?
Did you report this to AE as well?

**Comment by popcorn9499** [comment]
im using 1.7 i should of pu in the build and everything srry minecraft 1.7.10 AE2 rv 0 stable 10 logistics pipes 0.8.0.51

**Comment by popcorn9499** [comment]
Also i should say i just reported it to AlgorithmX2 and he said that its gonna be added soon

**Comment by AlgorithmX2** [comment]
This is planned for AE2 I just haven't gotten to it yet.

**Comment by AlgorithmX2** [comment]
Was looking into this, there seems to be some changes to how BC did pipes, and theres no longer a method to get the internal pipe as part of the api.

**Comment by davboecki** [comment]
LP pipes are no longer BC pipes, and I forgot to add a replacement for the getPipe BC API Interace. Will fix this as soon as posible.

**Comment by davboecki** [comment]
@AlgorithmX2 Trough this https://github.com/RS485/LogisticsPipes/blob/mc17/common/logisticspipes/api/ILPPipeTile.java you should be able to access the old interfaces. They should work in the same way as they did in MC 1.6.

**Comment by AlgorithmX2** [comment]
ok, I'll give it a try later tonight.

**Comment by bziemons** [comment]
Planned for AE2, not much to do here on the LP side.
