### ISSUE TITLE
Inventory Filler

### ISSUE THREAD

**Issue by AartBluestoke** [RS485/LogisticsPipes#44]
sometimes you want an inventory to be full (eg, supply a shop for trading) - current suppliers are unable to do this with 9 stacks of 127 items the most that can be requested.

A "fill this up" infinite count supplier module would be useful.

**Comment by ghost** [comment]
Maybe we should do this as a button on the supplier pipe gui rather than a new module, just place an item in the slots and select restock till full.

**Comment by Flow86** [comment]
I like the idea +1

**Comment by AartBluestoke** [comment]
New Supply modes : 
Infinite (request until inventory full)
Bulk50% - only re-order at 50% stock
Bulk100 - only re-order when the inventory is out of stock.
