### ISSUE TITLE
[enhancement] Add Fuzzy upgrade to Request Table

### ISSUE THREAD

**Issue by RAnders00** [RS485/LogisticsPipes#440]
I have had this problem for a while that the request table does not support the ore dictionary when requesting. There should be a really expensive upgrade to the table (Fuzzy Logistics Request Table), maybe some diamond and pulsating chipsets in the soldering table.

I hope you like my idea.

This shoud also affect crafting. Example: Ender IO basic gear and BC Stone gear is ore-dictionaried, i have none of both, but i can craft the BC Gear. Then it should also support that.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/issues/176
