### ISSUE TITLE
[suggestion] logistics fluid basic pipe interface change

### ISSUE THREAD

**Issue by AT611** [RS485/LogisticsPipes#441]
With such mods installed as GregTech, Thermal Expansion and Binnie Mods list of fluids in Logistics Fluid Basic Pipe becomes quite a large one. Sometimes it takes a few minutes to find required fluid, even if you know from which side (the end or the beginning of the the list) to look for it. I think Logistics Fluid Basic Pipe interface needs a review.

**Comment by davboecki** [comment]
What would you propose would be the change needed for this GUI?
You know that you can click into the slot witha fluid container to set the filter as well?

**Comment by AT611** [comment]
I think that a simple small list (7-8 rows large, sorted by localized fluid name, optionally grouped by mod name) with a vertical scroll bar will be sufficient, so at least one can easily scroll to the middle of the list, because I presume that in nearest future registered fluid list will only increase.
There is currently 303 fluids in my mod pack, according to NEI.

No, I didn't knew about clicking with a fluid container, but this feature actually would help me may be only one or two times, since I did not have some of them stored (except those that is currently in the machines) and some of this fluids has no associated container (or easy obtainable one) except "Drum" from Extra utilities mod. Drums from Extra utilities is not working in GUI and some of the fluids will be hard to store in some sort of a portable container, so I mostly have no choice but to just clicking through those 303 fluids by hand.

And also, when clicking through the fluid list, if something happens (some kind of an emergency) and I need to close the pipe GUI, I need to ensure that fluid in the current selection is either not being extracted or not even exists in my machine setup, so it will not start to fill associated storage with this temporary selected fluid. This selection method is mostly fine (for item supplier pipes and etc.), but in current situation it is another reason for me to request a GUI change.

**Comment by AT611** [comment]
Disregard my rant about closing Fluid Basic Pipe Interface in the middle of the fluid selection: I should not select amount for it before I select a fluid, and I mostly do not. I didn't think about that.

**Comment by davboecki** [comment]
In v0.9 there is now a PopUp which will list all Fluids that are known to LP. Use the middle mouse button on an empty fluid slot to open it.
![2014-10-12_01 52 13](https://cloud.githubusercontent.com/assets/1119689/4604488/c56453ea-51a1-11e4-919c-846325cfb774.png)

**Comment by AartBluestoke** [comment]
Could we add tool tips to indicate that such a feature exists, or even
default to that behaviour?

**Comment by bziemons** [comment]
@AartBluestoke :+1: for tooltip, maybe even default

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/d049f59641f0200e15eec28ed547050379d2aadd Made it the default behaviour. The ToolTip would have been more diffcult to implement.
