### ISSUE TITLE
(1.7.10) Crafting Table + Ender IO Gear = Crash

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#443]
Using the latest Jenkins release, attempting to craft a gear from Ender IO produced a fake player crash.

Pastebin: http://pastebin.com/x5aTBWjC

I haven't tried to craft anything else. This is occurring on my multiplayer server. I haven't tried to produce the crash in single player.

**Comment by davboecki** [comment]
Could you report this to Ender IO please. There is nothing we can do about this.
