### ISSUE TITLE
build 43 can extract items from AE interface, 56 can not

### ISSUE THREAD

**Issue by tomevoll** [RS485/LogisticsPipes#447]
I have a setup where a AE interface keeps x amount of items avalible in the interface, build 43 worked fine with a provider pipe, in build 56 it will not extract the items (i have not tested any builds between 43 and 56), AE2 build is beta 21

**Comment by davboecki** [comment]
We fixed the AE2 integration in 47 and 48. Now you can access the complete AE2 storage with the provider on an ME interface.

**Comment by tomevoll** [comment]
yes but you can not extract items from a AE interface now, you can set a me interface to keep x amount of items in it, and pulling those items out worked before, that does not work at all now, not sure if that is intentional

**Comment by tomevoll** [comment]
And im using a provider on the me interface and the items are not extracted, i had to pull them out manually put them in a chest and let the provider do it from there, the items are craftable items, so ME interface is set to keep 1 of them at all times in the interface or craft more if it is missing. so there is none of this item available in storage, only available in the interface
