### ISSUE TITLE
Supplier Pipe is not working on bottom of Thaumcraft Alchemical Furnace (fuel input)

### ISSUE THREAD

**Issue by Ioandar** [RS485/LogisticsPipes#448]
I tried a SupplierPipe  on the bottom side of a Thaumcraft Alchemical Furnace to supply it with fuel (as I did in 1.6.4)

Cannot get it to work.

LogisticPipes: 1.7.10-57
Buildcraft: 6.0.18
Thaumcraft: 4.2.0.1
Forge: 1208

**Comment by davboecki** [comment]
Have you tried if the Thaumcraft Alchemical Furnace even accepts items from below. Try using a normal BC pipe or pipes from any other pipe mod to see if the Furnace even supports it.

**Comment by Ioandar** [comment]
yes, I tried chest/wooden pipe with redstone engine and generic bc pipes. works like charm...

Pipe is green on network side and has red stripe on the furnace side. supplier pipe on a chest works at that spot... LP-Pipes on IC2 machines have red stripe on machine side too but they work nicely. 

lp-setup
http://www.directupload.net/file/d/3748/lcdbjsni_png.htm

bc-setup
http://www.directupload.net/file/d/3748/9vl5on4a_png.htm

**Comment by Ioandar** [comment]
I just installed the new version of Thaumcraft and now Supplier LP works as it should....

Will do some further checking but it seems there was something wrong in Thaumcraft and this can be closed

Find Thaumcraft Update here:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292130-thaumcraft-4-2-1-3-updated-2014-10-07
