### ISSUE TITLE
Sandstone Transport Pipe is not connecting to Crafting Logistics Pipe or Satellite Logistics Pipe

### ISSUE THREAD

**Issue by Ioandar** [RS485/LogisticsPipes#449]
Sandstone Transport Pipe is not connecting to Crafting Logistics Pipe or Satellite Logistics Pipe

LogisticPipes: 1.7.10-57
 Buildcraft: 6.0.18
 Thaumcraft: 4.2.0.1
 Forge: 1208

**Comment by davboecki** [comment]
Could you post a screenshot of your setup?
It the Sandstone pipe not connecting at all to any LP pipe or only the Crafting and satellite pipe?

**Comment by Ioandar** [comment]
Seems to be any LP pipe for me. I only came aware of it because I needed to place a pipe and ran out of plugs near hopper :)

lets see if that works for you... picture -> http://www.directupload.net/file/d/3748/5iicakuy_png.htm

**Comment by davboecki** [comment]
Will be fixed with the release for BC 6.1.5.
