### ISSUE TITLE
Infinite recursion?

### ISSUE THREAD

**Issue by MrTJP** [RS485/LogisticsPipes#45]
in the latest dev, it seems that making crafting requests causes the server to bog down to the point where it seems like it crashed, except it doesnt crash, it just becomes so slow that you cant even log in.

**Comment by AartBluestoke** [comment]
latest dev is highly experimental - if you can get a trace of what is using cpu time it would be useful ; for a busy server i'd recommend using main for the next few dev versions.

There are situations where crafting requests are not combining correctly either - requests of requests seem to fail sometimes. -- more testing is needed to finish off debug/devel of the new code, but none of the LP devs have had much time in the last few weeks.

**Comment by MrTJP** [comment]
i will try, but i have downgraded already.  But definitely seems to be some infinite recursion.

**Comment by davboecki** [comment]
Is this still an issue with the current crafting code?
