### ISSUE TITLE
Multiple crafting modules block each others extraction

### ISSUE THREAD

**Issue by Omegatron9** [RS485/LogisticsPipes#450]
Have two crafting modules in a chassis pipe attached to a furnace, one with the recipe 8 iron ore and one coal (sent to a satellite pipe of course) makes 8 iron and the other with the recipe 8 gold ore plus one coal makes 8 gold (it could be different ores of course). 
Request one iron and, part way through that being crafted, one gold. 
All the iron ingots produced before the gold was requested will be extracted, as soon as the gold is requested the pipe will stop extracting iron ingots.

**Comment by davboecki** [comment]
This probably has something to do with the extra extration being skipped untill all orders from the chassis pipe have been handled, which in this case would be after ther gold would have been extracted.

**Comment by AartBluestoke** [comment]
It should be possible to defer send on each failed craft to cycle the list on each failed craft, so with the case of multiple things being crafted simultaneously (eg ore being sunk into set of machines) it would change to sending the next result any tick the current result is not available.

This might also handle the case of 1 crafting recipe being needed as input to another on the same pipe, even indirectly.

(Don't have eclipse in front of me ATM, but seems a simple change)

**Comment by davboecki** [comment]
The problem here is that extra handling isn't part of the orderer manager. If that would be the case sycling would already be implemented.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/fa06994445e4e90659ddc74192e4b89cc0ec4c44
