### ISSUE TITLE
MFR harvester not connecting to basic logistics pipes

### ISSUE THREAD

**Issue by AartBluestoke** [RS485/LogisticsPipes#451]
as seen on the rs485 server, forgot to create this issue after noticing it; stone connects, mfr doesn't connect to a basic logistcs pipe in the same location.

**Comment by loordgek** [comment]
rs485 server? can i join?

**Comment by bziemons** [comment]
@loordgek I guess you are wrong here in the issues section.

And yup, something is weird with the Harvester and non-liquid LP pipes.

**Comment by davboecki** [comment]
Caused by IPipeConnection.ConnectOverride.CONNECT being ignored.

**Comment by davboecki** [comment]
Will be fixed with the release for BC 6.1.5.
