### ISSUE TITLE
Experiencing PermGen issues with Logistic Pipes (see the comment)

### ISSUE THREAD

**Issue by Nexey** [RS485/LogisticsPipes#457]
I'm having a permGen issue when logging into a world. The game crashes when LP is loaded whereas the world works fine with just BC and a bunch of other mods. If you want a log, I'll paste it here, but it is mostly spamming "PermGen". As I said, this is strange since I've been playing with over 30 mods with no problems, enabling LP crashes my game. I also tried disabling the particle effect as well as setting the opaque cables option to true but that didn't help at all.
I also want to point out that I'm using the version .58 of the mod for forge .208

**Comment by Nexey** [comment]
Version .59 of the mod freezes the entire game at the menu, right after the console is done loading the mods.

**Comment by davboecki** [comment]
Google how to set your permGen Space to a higher amount. This is not a mod bug this is just somerthing with java.

**Comment by Nexey** [comment]
I was expecting this answer. As my computer doesn't allow me to allow more than 1 gb of ram, this is impossible to me, but the real issue is that my game allows me to play with a lot of mods but your mod.

**Comment by AartBluestoke** [comment]
@dav, do you know is it is possible to dump the contents of the permagen
space, with the amount of reflection done by lp, there could be some areas
for improvement... (A Requirement for 256 mb for just class definitions is
beginning to get a little excessive)

**Comment by dav** [comment]
Guessing you meant @davboecki
