### ISSUE TITLE
Crafting LP MK2 does not craft 16 Items at a time in Autocrafting Table

### ISSUE THREAD

**Issue by Ioandar** [RS485/LogisticsPipes#462]
MK2 should craft 16 Items in one job but behaves like the normal Crafting LP and does 1 at a time

**Comment by bziemons** [comment]
Our Logistics Crafting Table?

**Comment by Ioandar** [comment]
the one from buildcraft (BuildCraft Auto Workbench - 4 wooden gears and a workbench)

I will replace it and check with LP Crafting Table...

update: LP Crafting Table works perfect! Seems I missed that one and learned something new today :)

I think we can close that. tyvm for pointing me in the right direction!

**Comment by bziemons** [comment]
Yeah, the BC Autocrafting table does not support crafting multiple items at once, sorry.
