### ISSUE TITLE
[Suggestion] Allow declaring Fluid Satellite pipes in the Advanced Satellite Interface

### ISSUE THREAD

**Issue by HCSarise** [RS485/LogisticsPipes#463]
It would be nice to be able to declare fluid satellite pipes when you upgrade to an advanced satellite upgrade. A very simple example/use for this would be the Vat from Mariculture. Tell it I want to send one bucket of water and one bucket of lava to the Vat to make obsidian.

**Comment by bziemons** [comment]
The Fluid Satellite Pipes do not work with buckets, but instead with the fluid system built into LP. So set up some tanks with water and lava and have a Fluid Provider Pipe sitting on each of them.
Put two Fluid Crafting Upgrades on your crafting pipe that is on that Vat, then have one or two Fluid Satellite Pipes on the correct sides on your Vat, enter the recipe then and you should be good to go.
