### ISSUE TITLE
Crafting not fuzzy aware when missing items.

### ISSUE THREAD

**Issue by sulljason** [RS485/LogisticsPipes#465]
When crafting a railcraft commercial steam engine using a fuzzy crafting table with a fuzzy upgraded crafting pipe. We were missing iron plates so when I tried to request it, it said I was missing iron gears and iron plates, but we already had 10 compatible iron gears. When it checked if we had the materials it didn't consider that we might have ore dictionary compatible materials.

![Iron Gear Crafter](http://i.imgur.com/u89kpRx.png)

![Commercial Engine Crafter](http://i.imgur.com/3xKLKqR.png)

![Missing Error](http://i.imgur.com/xxtvgMi.png)

**Comment by 1n5aN1aC** [comment]
I'd just like to add that this appears to just be an annoying visual issue where when one item doesn't exist, and the crafting would notify you that that item(s) are missing, it doesn't continue to care about fuzzy-ness when listing what else you are out of.

So this leads you to believe you are also out of something else, or your secondary crafting system is completely buggered, when really just adding the first item is plenty, and it will be able to craft the second itself.
