### ISSUE TITLE
lp build 65 power transport problems

### ISSUE THREAD

**Issue by popcorn9499** [RS485/LogisticsPipes#467]
the power transport lasers dont seem to want to work until i cause a block update on the pipes near the provider.
this only happens every time the chunk reloads

lp build 65
minecraft 1.7.10

**Comment by bziemons** [comment]
So it is only a visual bug?
Because the lasers do also bug, when you are far away, your client does not see the chunk and they power on.

**Comment by popcorn9499** [comment]
srry i didnt check the notification but ya that was the problem
