### ISSUE TITLE
Integer overflow, server crash

### ISSUE THREAD

**Issue by bziemons** [RS485/LogisticsPipes#470]
https://gist.github.com/theZorro266/b2ac10410ca8867779d7
Probably Integer overflow

**Comment by bziemons** [comment]
This will take a little longer to fix. It is actually caused by power outage and Inventory System Connector derp.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/63431d7d7d15126c7af9466af69de0cd139f3c6d
