### ISSUE TITLE
client crash when putting on hud glasses

### ISSUE THREAD

**Issue by peltco** [RS485/LogisticsPipes#472]
I just put on the hud glasses and now i crash instantly (and even when relogging i crash instantly)

http://pastebin.com/c9pd6pkP

**Comment by peltco** [comment]
extra info, i modified the player file to fix the issue in i was ooking at a tinkers construction table with in the corners of my view een logistic request table and a thermal expansion redstone furnace (reinforced) with hopper and mekanism universal cables attached

**Comment by davboecki** [comment]
What build are you using?
Are you sure your log is the correct one?
Could you post the crash log?

**Comment by bziemons** [comment]
Could you provide that info, @peltco?
