### ISSUE TITLE
support for buildcraft 6.1.2?

### ISSUE THREAD

**Issue by mvdhoning** [RS485/LogisticsPipes#473]
Buildcraft 6.1.2 seems to have been released yesterday (18-10-2014) at (bringing rf power):
http://mc.shinonome.ch/doku.php?id=wiki:buildcraft
Unfortunately logistics pipes seems to be expecting a lower version and thows an exception causing minecraft to stop working. (maybe its a good thing and protects me from horror later on :-) )

logisticspipes.proxy.VersionNotSupportedException: The BC Version '6.1.2' is not supported by this LP version. Please use '6.1.1' at logisticspipes.proxy.buildcraft.bc61.BuildCraftProxy.(BuildCraftProxy.java:149)

**Comment by asiekierka** [comment]
Give them time. I personally propose that you work on 6.1.2 support now and release it alongside the much fixed 6.1.3 on Friday, which should work with 6.1.2 code.

Also, at LP developers - if you need any APIs inside BuildCraft for easier Logistics Pipes support, don't hesitate to contact me!

**Comment by bziemons** [comment]
@asiekierka @davboecki might have already started. And he might also want to talk to you about the last thing you mentioned ;)
@mvdhoning basically every new BC version does not need a new issue here. We try to keep up as we can.

**Comment by mvdhoning** [comment]
@theZorro266 Sorry for posting it then. Did not realize you worked so closely together. Keep up the good work on your awesome mods.
