### ISSUE TITLE
Some items are not craftable

### ISSUE THREAD

**Issue by JasonMcRay** [RS485/LogisticsPipes#477]
I am not sure if this is intended (these items were added for testing purposes without recipes) or someone forgot to add those recipes. But i think i will, just in case, report it.

Unable to craft: Crafting Modules (all 3 tiers) and Active Supplier Module.

**Comment by bziemons** [comment]
Yup, not 100% done yet. You can let this issue be, because it will be done and the issue can be closed then.

**Comment by bziemons** [comment]
Actually these were added in f627df787fc5db4fea6039634f256e9bcbeb7181
