### ISSUE TITLE
Test builds for 1.5.1

### ISSUE THREAD

**Issue by ddos666TB** [RS485/LogisticsPipes#48]
my 1.5 branch 
[README](https://github.com/gejzer/LogisticsPipes-Dev)
[builds on dropbox](https://www.dropbox.com/sh/tjzx65jqfrwvd73/qpX4mfApUZ)

**Comment by helinus** [comment]
build 17.

Gui buttons are weird: http://imgur.com/zkjVXvG
Missing textures: http://imgur.com/IcaMGMQ
Crafting sign creator does not do anything when rightclicking a crafting pipe, no error in fml log.

Have tested Request pipe, chassi mk2 with itemsink and provider, power junktion and crafting pipe mk1 and mk2.

**Comment by AartBluestoke** [comment]
gejer,
thanks for setting up the 1.5 build; i'll see if i can pass a PR or 2 :).

**Comment by modpir8king** [comment]
Getting this error with forestry: 

[SEVERE] [Forestry] logisticspipes.LogisticsPipes failed validation. Halting runtime for security reasons. Please replace your mods with untampered versions from the official download sites.
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by AartBluestoke** [comment]
I'm sorry, that is a forestry deliberately crashing because it tries to implement a type of DRM, and finds that the linked build is not code-signed.

It tries to check that there is no third party edits to other mods and deliberatly crashes MC when it finds non-signed mods, pleas report this bug to the forge forums, and to forestry.

3 solutions. 1: @gejzer should code-sign his builds 2: 3 davboeki sets up a 1.5 jenkins, and he or I pull gejzer's code changes (which is what will happen soon anyway), 3: detect forestry and (at runtime) edit their deliberately crashing code out, so that forestry does not crash in this situation.

**Comment by ddos666TB** [comment]
i ill look around this:)
thx for feedback, and check fresh builds

**Comment by ddos666TB** [comment]
lastest build 25 is signed now

**Comment by modpir8king** [comment]
Thanks for looking into the problem yet it still persists I am getting these two lines:
2013-04-19 22:14:43 [SEVERE] [LogisticsPipes|Main] Certificate not correct
2013-04-19 22:14:43 [SEVERE] [LogisticsPipes|Main] This in not a LogisticsPipes version from RS485.
and the forestry error above.  But before this I get a duplicate mod source warining from forge regarding Buildcraft-Transport in both this and buildcraft I was able to by pass this via removing the buildcraft transport.class from this jar then hit the above warnings.  I am using the the 119.119 build of buildcraft and the 2.1.2.17 build of forestry.  I hope I have given you enough information.

**Comment by xxdolcexx** [comment]
2013-04-19 14:27:52 [SEVERE] [ForgeModLoader] Found a duplicate mod BuildCraft|Transport at [F:\14.7 mc 15 april\instances\1.5.1\minecraft\mods\LogisticsPipes-MC1.5.1-0.7.1-dev.25.jar, F:\14.7 mc 15 april\instances\1.5.1\minecraft\mods\buildcraft-A-3.5.0.jar]

**Comment by GUIpsp** [comment]
> 2013-04-19 22:14:43 [SEVERE] [LogisticsPipes|Main] Certificate not correct
> 2013-04-19 22:14:43 [SEVERE] [LogisticsPipes|Main] This in not a LogisticsPipes version from RS485.

This is not an error and can be ignored

**Comment by xxdolcexx** [comment]
2013-04-19 15:13:16 [SEVERE] [Forestry] logisticspipes.LogisticsPipes failed validation. Halting runtime for security reasons. Please replace your mods with untampered versions from the official download sites.
Minecraft exited with code 1.
Minecraft has crashed!

**Comment by nvx** [comment]
@SirSengir Nobody asked you to act as mod police here... Just stop before you make even more of a fool out of yourself...

**Comment by CannibalVox** [comment]
He started doing the same thing with EE3.  Apparently Sengir doesn't believe in open source.

**Comment by nvx** [comment]
@cpw And this is why FML needs to implement a SecurityManager that explicitly prohibits mods from checking signatures of other mods. As has been quite clearly demonstrated mod authors can not be trusted to do the right thing in this respect. Forestry has absolutely no business checking the certificates of LogisticsPipes, EE3, or any other mod that isn't written by Sengir for that matter.

**Comment by ddos666TB** [comment]
yep my jenkins got crazy(sry for that) rebuilding correct one

EDIT: NVM go 
http://ci.thezorro266.com/job/LogisticsPipes-Dev/

**Comment by davboecki** [comment]
RS485 builds are avaliable now.
