### ISSUE TITLE
disconnection upgrades 

### ISSUE THREAD

**Issue by loordgek** [RS485/LogisticsPipes#480]
take a look at ic2 auto eject
you set the side by clicking w/ the item on a block

**Comment by bziemons** [comment]
???

**Comment by AartBluestoke** [comment]
i think this is asking for a simpler way to handle disconnection, by clicking a generic disconnection upgrade on a specific side  of the pipe.

**Comment by bziemons** [comment]
Implemented in 0.10, but there will be more changes to it.
