### ISSUE TITLE
Soldering station template bug, no autocrafting possible

### ISSUE THREAD

**Issue by bziemons** [RS485/LogisticsPipes#482]
When trying to autocraft with the soldering station, it will not put iron in the right slot, and it will not distribute other items between all slots in the recipe.
E.g. autocrafting the nano hopper

**Comment by ghost** [comment]
Any update on this? I am using the latest version of 0.8 and this bug still exists, I can't automate the soldiering station using wooden or crafting pipes. I am waiting until the weekend to move to 0.9 and would like to know if has been fixed.

**Comment by gudenau** [comment]
Seems to occur in the latest release as well.

**Comment by tod** [comment]
It would be nice if you could just use the placement rules upgrade with crafting pipes.

**Comment by hron84** [comment]
It'd be better if soldering station should work more like how vanilla furnaces work, accept "fuel" (in this term: iron) from different side than the crafting materials.

**Comment by bziemons** [comment]
@hron84 isn't really related to this issue, but a good idea, I think.

**Comment by cleverca22** [comment]
this bug kind of defeats the purpose of having the extra lock slot in the top right

**Comment by agowa** [comment]
I tried automating using a hopper on the top. After I placed hoppers inside it (for creating the nano hopper) they just disappeared.

**Comment by Rsge** [comment]
So wait - this Bug existed since 2014?  Oo
It's 2016 and still not fixed in LP 0.9.3.128 (newest as of the time of this post)
Any chance there's ever gonna be a fix?
Cause as cleverca said, the lock-slot defies it's purpose ; )

Edit: Added the info in brackets

**Comment by bziemons** [comment]
The soldering station will probably be replaced in 0.10

**Comment by hron84** [comment]
@theZorro266 with what?

**Comment by bziemons** [comment]
@hron84 I guess that is a surprise ;)

**Comment by hron84** [comment]
@theZorro266 awww, surprises... can't wait :-)

**Comment by hakanai** [comment]
I love surprises!

**Comment by bziemons** [comment]
> I love surprises!

surprises like someone adding a comment to an issue from 2016? :smile:

**Comment by hakanai** [comment]
Surprises like issues from 2016 not having been fixed when playing a modpack in 2020.

I'm kidding of course. :)

**Comment by bziemons** [comment]
That shouldn't be surprising, there are tons of those :D
