### ISSUE TITLE
Make new supplier pipe GUI

### ISSUE THREAD

**Issue by bziemons** [RS485/LogisticsPipes#484]
Because the old one is hard to use. Stacks are limited to 127, shift/right/left clicks are horrible in terms of usability. And the 3x3 grid just does not fit at all.

**Comment by Chaots** [comment]
As a suggestion:

The request logsitics pipe gui may be a good alternative for this pipe,
One could select the item to provide and set the count to keep supplied in the inventory.
Tiering the pipe could change the ammount of different items a pipe can keep stocked. Not the total count to be stored in the inventory. MK1 1 item, MK2 8 items, MK3 64 items.
The tiered pipes could work with pages for every given item to be supplied. (pages as in the programmable rednet controllers behavior)
A pipe's "main page" could give an overview of items the pipe is setup for. this could look like the inventory of a chest, or like the rows of slots a diamond pipe has. once a player clicks a space, the gui jumps to the (free)page that handles configuration of the item to be supplied.
A placement rules upgrade could be used to designate specified slots in the inventory. This upgrade has to be page specific

Greets,
Chaot_s

**Comment by bziemons** [comment]
It is not planned to make a huge redesign on it..
Also your suggestion does not really fit into the rest of LP's GUIs

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
