### ISSUE TITLE
Powerjunction combined with firewall pipe crashes server

### ISSUE THREAD

**Issue by Chaots** [RS485/LogisticsPipes#489]
MC Verserion 1.6.4 (tekkit main modpack)
LP Version: 0.7.4.dev.205
Java Version: 1.7.0_65 (X64)

Bug description:
Placing a logistics power junction so it connects to a power feed (RedstoneFlux) and a firewall pipe, set to only allow power to traverse, results in a server that stops "ticking" (no actual crash). And all connected players disconnect with a "server timeout". The server does not recover from this state and has to be "killed" and restarted. After the restart nearing the location where said firewall and junction are located "locks" the server again. restarting the server several times and removing the firewall pipe stops the error from occuring.

Error log:
http://pastebin.com/Key6xQpf the "java.lang.UnsupportedOperationException: OneList doesn't have this kind of iterator" error block re-appears every other second.

Replication:
screenshot of the live server with the first occurence of the bug: http://picpaste.com/2014-10-28_14.36.23-EektDVcq.png

Replication of the bug in a test world:
The Diamond block is where the power junction is placed.
The block on the right side of the conductor is a bc power producer.
the top half of the pipe network pulls (adv extr mk3) oreblocks from the ender chest and dumps them in the pulverizer.
The pulverizer then dumps the results in the basic logistics pipe below (main network), where it gets lead to a default route / furnace depending on the given item.
Picture URL: http://picpaste.com/2014-10-28_14.36.23-EektDVcq.png 
Picture URL: http://picpaste.com/2014-10-30_14.03.03-6UPMZBsE.png 
Picture URL: http://picpaste.com/2014-10-30_14.03.37-dxDcsd5W.png 
Picture URL: http://picpaste.com/2014-10-30_14.04.41-dCMoaN8H.png 

Expected behavior: Power junction and/or firewall pipe should ignore each other when placed against each other. As far as i know only a basic logistics pipe should connect and provide an entrypoint for logistic pipe networks.

Greets,
Chaot_s

**Comment by bziemons** [comment]
I had a look into this and could not reproduce the server freezing.
However I did fix the error spamming, which also lead to not updating the routing table in 24bd5f44ba63d42a83d9d7cf418c4940693f323c

If the server freezing still persists with a recent version of LP, please open a new issue.
