### ISSUE TITLE
Crash with Buildcraft 6.1.5

### ISSUE THREAD

**Issue by Xen1290** [RS485/LogisticsPipes#492]
Hi with logisticspipes-0.8.1.75 and Buildcraft 6.1.5 I get this crash: http://pastebin.com/QvHFQaEH

**Comment by UnPure** [comment]
Take a look at line 7.
"The BC Version '6.1.5' is not supported by this LP version. Please use '6.1.1'"
We have to wait for an update.. :x

**Comment by davboecki** [comment]
Updated.

**Comment by Xen1290** [comment]
Thank you for your work.

**Comment by mt-xing** [comment]
You, sir, are amazing.
