### ISSUE TITLE
Recipe suggestion for unrouted pipes

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#494]
Newly added Basic unrouted pipe not dropping itself on block removal in survival mode

Also: Recipe suggestion:

craftingManager.addRecipe(new ItemStack(LogisticsPipes.BasicTransportPipe, 8), CraftingDependency.Basic, new Object[] {
“SGS“,
“ R “,
Character.valueOf('S'), Blocks.stone,
Charakter.valueOf('G'), Blocks.glass,
Charakter.valueOf('R'), Items.redstone
});

This would make them easy to access, and simillar to BC Pipe recipes.
Possibly add them instead of Cobblestone pipes into the Recipe for BasicLogisticsPipes

**Comment by bziemons** [comment]
Not a bug. They are in development. The recipe is a suggestion though.

**Comment by SonOfTheStars** [comment]
Never meant to be a bug just a reminder ;)

**Comment by SonOfTheStars** [comment]
Thats why i marked it [ALPHA]

**Comment by bziemons** [comment]
Well "Unrouted pipes not dropping" as the title describes it as a bug.
I don't know why people put tags in the title in their brackets. That is "not their business", instead it is much more important what the issue (and the title as representation) contains.

Edit: And also: no offense, thanks for the issue. I am just expressing why I said what I said.

**Comment by SonOfTheStars** [comment]
No Offense taken ill respect that the next time

**Comment by SonOfTheStars** [comment]
The Recipes, featuring the Unrouted Transport Pipe are in the 0.9 Branch as Beta Recipes!
