### ISSUE TITLE
StackOverflow

### ISSUE THREAD

**Issue by ghosty1911** [RS485/LogisticsPipes#495]
I become this Crash Report
Description: Ticking block entity

http://pastebin.com/XUJAtGBG

**Comment by bziemons** [comment]
And I become rather uncomfortable, if you just paste the whole crash report here.

Additionally this info should be provided along:
Forge: 10.13.2.1231
BC: 6.1.5
LP: 0.8.2.76

**Comment by ghosty1911** [comment]
Ok for next time i know

**Comment by bziemons** [comment]
Thanks
