### ISSUE TITLE
AE and lp crash with provider pipe and chassis and provider module

### ISSUE THREAD

**Issue by popcorn9499** [RS485/LogisticsPipes#500]
i seemed to crash with any version of ae and the latest lp build number 77. It only seems to crash when i add this module to the pipe or place a provider pipe next to the ae interface to try and get it on every end.

http://pastebin.com/GyNtGYXF this is the crash log i get.
if you need anything else ask and i will give you it.

Thank you for the help and i hope this helps your mod :)

**Comment by AartBluestoke** [comment]
it would be nice if we didn't take out a server with this error - perhaps a
message to to all ops on the server and a critical message in the log,
then ignore all future instances of this error -- net effect, when AE-LP
integration doesn't work we don't kill the server?

On Mon, Nov 10, 2014 at 9:22 AM, popcorn9499 notifications@github.com
wrote:

> i seemed to crash with any version of ae and the latest lp build number
> 77. It only seems to crash when i add this module to the pipe or place a
> provider pipe next to the ae interface to try and get it on every end.
> 
> http://pastebin.com/GyNtGYXF this is the crash log i get.
> if you need anything else ask and i will give you it.
> 
> Thank you for the help and i hope this helps your mod :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RS485/LogisticsPipes/issues/500.

## 

“Getting information off the Internet is like taking a drink from a fire
hydrant.”
_– Mitchell Kapor_

**Comment by popcorn9499** [comment]
idk why you couldnt just build in a failsafe thing so when it doesnt work it just submits a crash log for that block and quits trying to do  that anymore?

**Comment by LuQ3** [comment]
https://github.com/BevoTechPack/BevoTechPack/issues/713

**Comment by ruifung** [comment]
This error isn't happening with the regular provider pipe for me, in fact the provider is working as expected. However using chassis pipes and the provider modules results in the exact same error. (I play with forge set to automatically remove erroring tile entities instead of crashing the game - maybe you should set that in forge.cfg so it doesn't take your server down.)

**Comment by ruifung** [comment]
Same as #481, #498, Should probably merge all 3 issues somehow.. =P
