### ISSUE TITLE
Texture Suggestion for Modules

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#502]
So, we all know the LP-Modules for the Chassipipes look like they could use a Facelifting....
Here are some ideas for that:
blank: (a little bad to see because white on white... XD)

![](http://i.imgur.com/W3cNch4.png)

Provider:

![](http://i.imgur.com/T3UBTaw.png)
Extractor:

![](http://i.imgur.com/uPa89PW.png)
Itemsinks:

![](http://i.imgur.com/yD5wkTw.png)

![](http://i.imgur.com/haS8aHW.png)

![](http://i.imgur.com/O3orlEd.png)

![](http://i.imgur.com/plYovRB.png)

textures are 64x64 Pixel, since that allows for more detailed work and fancier looks
Hope you like them!

**Comment by SonOfTheStars** [comment]
Other ones are in the Works!

**Comment by loordgek** [comment]
that is cool looking WOW
but i dont like the text on the side
Extractor and the Provider

**Comment by SonOfTheStars** [comment]
Yeah i figured that. 
Did it for easy visual understanding for the user, so they can look for it and say: “THERE it is!“
But the Provider and Extractor look a little odd i agree

**Comment by SonOfTheStars** [comment]
Goin to be a public Texturepack.
