### ISSUE TITLE
AE2 Power sharing?

### ISSUE THREAD

**Issue by ruifung** [RS485/LogisticsPipes#504]
I know that in AE1, LP could use power from the AE network and vice versa. However this appears to be gone with AE2? Or is it that I cant figure out how to do it..?

**Comment by bziemons** [comment]
Applied Energistics 2 is not fully supported yet. I don't know if the energy will ever be shared again.

**Comment by loordgek** [comment]
will it done on lp ore ae side?

**Comment by davboecki** [comment]
That would be AE side.
