### ISSUE TITLE
Unclear wiki / ingame usage of Power Transportation

### ISSUE THREAD

**Issue by ruifung** [RS485/LogisticsPipes#506]
According to the wiki:

```
There must be a logistics pipe with a power transportation upgrade at each corner that the power must flow down in the pipe network, the power lasers can't turn corners but can go in straight lines through any other type of pipe.
```

But the power laser wont go through basic logistic pipes without the upgrade, eventhough its in a straight line where regular buildcraft pipes work just fine there.

**Comment by davboecki** [comment]
I don't know what wiki you are refering to but the content is not 100% correct. It is intended that every logistics routed pipe along the way needs a power upgrade and that every corner needs one.

**Comment by ruifung** [comment]
This wiki? http://rs485.thezorro266.com/wiki/Power_Transportation_Upgrade

**Comment by SonOfTheStars** [comment]
Well seems like the Wiki needs a overhaul

**Comment by bziemons** [comment]
Fixed on http://rs485.network/wiki/Power_Transportation_Upgrade
