### ISSUE TITLE
Soldering station is not working

### ISSUE THREAD

**Issue by Algalish** [RS485/LogisticsPipes#508]
I am trying to craft something with soldering station but it is not working. After I put ingredients into the soldering station and put iron there the object that I need is shown. But nothing happens. I am connecting soldering station(it needs BC power,right?) to the gold power pipe from BC but it is not connected(not from the top, not from the bottom).  It was working in a very old build in MC 1.6.4.

I use  LP(0.8.2.82) and BC (6.1.8)   MC 1.7.10

Thank you for all your great work.

**Comment by davboecki** [comment]
You need to connect the Soldering station to your LP network. It requires LP since MC 1.7.
