### ISSUE TITLE
Fluid provider pipe doesn't work with Railcraft tanks

### ISSUE THREAD

**Issue by NickIAm** [RS485/LogisticsPipes#509]
To reproduce: 
1. Build railcraft iron or steel tank
2. Fill with some kind of liquid
3. Attach fluid provider pipe to a tank valve in the bottom layer of the multiblock
4. Set fluid supplier pipe to keep another tank stocked with liquid from the provider pipe

Using LP build 82
The work around i'm using is to attach a BC tank to the Railcraft tank valve and attach the provider pipe to that.

**Comment by davboecki** [comment]
You can NOT connect the provider pipe to the bottom layer you need to connect it to the bottm side. That is a Railcraft limitation.
