### ISSUE TITLE
Power junction will not connect to BuildCraft power sources.

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#512]
Using BuildCraft 6.1.8 and Logistics Pipes 0.8.2.82, the power junction will not connect to BuildCraft kinesis pipes or Buildcraft engines. (The Minecraft version is 1.7.10, in case that's relevant.)

Engines also don't seem to recognize the power junctions as valid connections either.

Just to clarify, this is not merely a visual bug, kinesis pipes running by the junction do not deliver power, as well as not visually connecting.

Here's a screenshot showcasing it. (Note: the pipes are only lined up for the screenshot. The issue still occurs when using single pipes.)
![power junction issue](https://cloud.githubusercontent.com/assets/3688103/5155270/fb8b32c6-7245-11e4-9433-8b8c07f94f1b.png)

**Comment by davboecki** [comment]
You need to have Thermal Expansion installed in order for our RF support to be enabled.

**Comment by ghost** [comment]
So there's no way to power them with open source mods now? That's a bit disappointing.

**Comment by bziemons** [comment]
Todo: Make extra RF power api proxy

**Comment by ghost** [comment]
One minor thing I thought might be worth mentioning, Universal Electricity (or Mekanism, which supports RF power) support could work too, if one of them would be easier to add.

**Comment by bziemons** [comment]
I don't think it would be easier to do that. Right now we just have Themal Expansion and their power API combined in one "soft dependency". That means both only work with TE installed. The plan is to grab the power api part and make an extra "soft dependency", so TE does not need to be installed.

I don't know how it stands with UE right now, but their API was always changing at the time it came out, so we prefered to not support that directly.

**Comment by ghost** [comment]
Fair enough. I may have to set up a development environment myself soon and
take a crack at it.

**Comment by ruifung** [comment]
I don't think mekanism has a specific power system, AFAIK it's not a UE mod, not anymore. And it can output in pretty much any form of power that i've used it for. (Which in 1.7.10, just happens to be RF only) So I think for mekanism support, just supporting RF in general would be sufficient.

**Comment by Islarf** [comment]
davboecki you referenced me here but it doesn't help, I don't have either TE3 or IC2 available... this answers none of my questions #530

**Comment by ruifung** [comment]
@DarrenBellew  It does actually. All 3 of the mods you mention uses the RF power system (Except mekanism, which supports multiple power systems, but as LP doesn't enable support for any of them without the respective mod installed...), which means its the exact same issue as this one: RF Support isn't enabled without Thermal Expansion installed. (for now)

**Comment by bziemons** [comment]
@DarrenBellew exactly as @ruifung pointed out: Your issue would be solved, when this issue is solved.

**Comment by Islarf** [comment]
@ruifung @theZorro266 well with Buildcraft's now using RF API, Logistics Pipes is no longer solely dependent on Buildcraft but Thermal Expansion aswell... The power mods I have available are:
BC, Ender IO, Mekanism and Forestry(Not using this as any source however).

**Comment by bziemons** [comment]
Right now that is true, if you do not have Industrial Craft 2. But you are right and this will be fixed soon :tm:

**Comment by Islarf** [comment]
Could you reply back here when it is fixed as i currently have power requirement disabled in config to suffice atm but I'm uncomfortable using this as also the soldering Station and such recipies are unaccessable

**Comment by asiekierka** [comment]
@theZorro266 - make it depend on the presence of CoFHLib. It's the smaller mod unit including the RF API. Or perhaps make it dependent on BuildCraft OR ThermalExpansion (both bundle the RF API).

**Comment by davboecki** [comment]
Fixed. Made it so it depends on the CoFHAPI|energy.
