### ISSUE TITLE
'LogisticsPipes_dummy.jar'

### ISSUE THREAD

**Issue by lichbane1401** [RS485/LogisticsPipes#513]
I seem to be getting this crash, might be a derp, not sure.
http://pastebin.com/xwQ8PdX7

**Comment by SonOfTheStars** [comment]
I suspect you have runned LP in an IDE like Eclipse or IntelliJ.
Please read the crashed before posting:
"If you are running MC from an IDE make sure to copy the 'LogisticsPipes_dummy.jar' to your mods folder"(@lichbane1401, line 8-9)

**Comment by lichbane1401** [comment]
Nope, just from the minecraft launcher

**Comment by SonOfTheStars** [comment]
Okey nevermind...
What BC version are you on?
Have you tried without Optifine?

Also please dont post raw Crashlogs into a Github issue. use pastebin or a simmilar sharing website. Those are free and better to overlook, plus it keeps your post easy to overlook

**Comment by lichbane1401** [comment]
6.1.5n and just tried without optifine still crashing

**Comment by SonOfTheStars** [comment]
Very Strange....
Ill ping davboeki and/or zorro

**Comment by davboecki** [comment]
Redownload LP and put the jar into the mods folder without using any other progamm. Then check if the jar still has the META-INF folder inside.

**Comment by lichbane1401** [comment]
Downloading it again fixed it, and yes there was a meta-inf folder
