### ISSUE TITLE
Send to player clientside.

### ISSUE THREAD

**Issue by MyEternity** [RS485/LogisticsPipes#520]
Client console spam with errors like "[Client thread/INFO] [STDERR]: [logisticspipes.proxy.MainProxy:sendToPlayerList:176]: sendToPlayerList called clientside !"

Action ingame: Configuring active request pipe with wrench.
Full client logfile here: http://paste.ee/p/ZljgR

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/issues/464
