### ISSUE TITLE
Crash when connecting logisticspipes with an Applied Energistics interface

### ISSUE THREAD

**Issue by leroy** [RS485/LogisticsPipes#521]
Connected the blocks which resulted in my client/server crashing.

Getting the following error:
http://pastebin.com/eXSngujm

**Comment by CourtArtanis** [comment]
#507 Is it of any relation to this @CupCoffee ? I had a similar error connecting a supplier pipe to an ME Interface. I guess the same might apply to a Supplier Module.

**Comment by bziemons** [comment]
Could you tell me your Applied Energistics 2 version? (I suspect you are using rv2, please try stable rv1 if I am correct and of course tell us about your results)

**Comment by leroy** [comment]
We are using the rv1 stable version of AE2.

I fixed it using a world editor but i figured you guys wanna solve this nontheless.
We just encountered another "version" of this issue using a ME chest. When connecting a logisticspipe and a ME chest with a storage cell in it. if i were to pull the storage cell out of the ME chest the logisticspipe would throw an error again. Resulting in the server not being able to run with that world.

**Comment by hron84** [comment]
@davboecki which version of AE2 is currently supported by LP? Do you support rv2 branch?

**Comment by bziemons** [comment]
There was an API change in rv2. Right now we do not fully support it. I don't know if it actually works though.

@CupCoffee we will look into that.

**Comment by hron84** [comment]
@davboecki thanks for the response. do you plan rv2 support in some time, or you'll wait rv3 with support from other end?

**Comment by bziemons** [comment]
rv2 beta just came out
