### ISSUE TITLE
Crash during autocrafting setup

### ISSUE THREAD

**Issue by Vineg** [RS485/LogisticsPipes#522]
http://pastebin.com/7XSZgZuV

Edit: I added crafting without input(I set crafting pipe to output glass, but I not added sand yet) and then supplier pipe requested glass from crafting pipe and game crashed on ticking supplier pipe.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/58b9eca9f154a95b7af096091039ac4b4aa11ed0
