### ISSUE TITLE
java.lang.NullPointerException: Unexpected error

### ISSUE THREAD

**Issue by Sailren** [RS485/LogisticsPipes#523]
this happened when i used /help 2

http://paste.ubuntu.com/9334950/

**Comment by bziemons** [comment]
May I ask what language setting you are on? Does it help switching the language to English (US) ?

**Comment by Sailren** [comment]
im using standard language afaik

ich benutze die standard sprache so viel ich weiß

**Comment by bziemons** [comment]
You don't know exactly on which language you play Minecraft? Standard? Does that mean English?

**Comment by Sailren** [comment]
yeah the language which is enabled by default, i think it US cuz it all looks like english to me

**Comment by ghost** [comment]
I've been having the same problem for some time, but it happens when I type "/help 3", presumably because there are more help entries in my modpack.
http://pastebin.com/raw.php?i=UkgFu6e8
I use the default language, English (US).
