### ISSUE TITLE
Fuzzy Crafting Broken

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#524]
The Fuzzy Crafting in Logistics Crafting Tables(either with a Fuzzy table or a Fuzzy Pipe or both), is currently not working.

It doesnt Match the Items via Ore-dict and only Pulls exact matches.

Applies to both Milestone 0.9 and 0.8

**Comment by SonOfTheStars** [comment]
Somehow it seems like the Fuzzy Flag simply gets Ignored. Like if it was never Set through the GUI.

**Comment by davboecki** [comment]
But it is not forgotten by the pipe, is it? If you reconnect/restart are they still there?

**Comment by SonOfTheStars** [comment]
it is till there but the flag seems not to transfer into the Logic
