### ISSUE TITLE
Storage Drawers Integration

### ISSUE THREAD

**Issue by jaquadro** [RS485/LogisticsPipes#525]
I'm the author of the Storage Drawers mod (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2198533).

Someone was reporting funky behavior between supplier pipes and storage blocks.  Since the drawers are basically multi-slotted JABBA barrels, this will require integration support on your side.

I export a basic API for manipulating storage.  Based on the existing JABBA and DSU support code, I can probably scrape together a PR for you, but I'm really sketchy on some of your architecture surrounding the proxies and could use some guidance.  Or if you want to write the integration yourself, that also works.

**Comment by bziemons** [comment]
Sounds good. Just fast-linking the API here: https://github.com/jaquadro/StorageDrawers/tree/master/src/com/jaquadro/minecraft/storagedrawers/api
