### ISSUE TITLE
Integration: AE2 - Question

### ISSUE THREAD

**Issue by ddos666TB** [RS485/LogisticsPipes#528]
I have question: Does LP integration work bidirectional (accessing items), I can access items from AE 2 network via Request pipe but can't access LP stored items from AE 2 Terminal.
I connect AE2 with LP via ME interface with Provider & Request Pipe.
Am I doing sth wrong, or it's a bug/missing feature?

**Comment by ruifung** [comment]
The integration needs to be done on both sides - LP has done it on its side, but for AE you should see this issue https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/21
