### ISSUE TITLE
LP can't seem to specify Ender IO Filled Soul Vials

### ISSUE THREAD

**Issue by HCSarise** [RS485/LogisticsPipes#529]
Hiya,

I'm trying to get my autocrafting setup working for Dimensional Tranceivers, and the only issue I have come across is getting my logistics system to recognise the specific kind of filled soul vial I need (enderman). If you leave the crafting pipe as is, the system tells you it is missing the soul vial (even though one is provided). If you add the fuzzy crafting upgrade, you can get it to work by ignoring NBT, but this also means that if any other kind of filled soul vial is provided (ie, not enderman), it will grab that out as well.

I'm not really sure what kind of tags Ender IO uses for its filled soul vials, but no combination of anything I tried could get logistics pipes to recognise it properly.

Is there anything to remedy this? Is there such thing as a "precise" crafting upgrade or something?

I've actually made a tutorial out of it - and it will give you a good idea of my setup so you can see if I am missing anything http://imgur.com/a/Xplae

**Comment by AartBluestoke** [comment]
It sounds like soul vials are each different in some way, so that 2
enderman vials are not completely identical (do the have a 'charge' or the
like?) We would need a mod specific handler to define a new type of item=
just for this case.

**Comment by HCSarise** [comment]
Do they have a charge? Well they don't have a durability bar ala flux-tools if that's what you mean. Otherwise I'm really not sure.

**Comment by HCSarise** [comment]
Two filled vials of the same mob type will not stack together in an inventory, if that helps at all.

**Comment by ArtForz** [comment]
They're basically EnderIOs version of the MFR safari ball.
Now why'd they end up with different NBT if you capture 2 otherwise identical mobs (same health/armor/held item/...) ... no idea.

**Comment by HCSarise** [comment]
So is this an Ender IO issue instead?

**Comment by tterrag1098** [comment]
Every mob's NBT is different, I'm sure you would have this same issue with MFR safari nets.

**Comment by bziemons** [comment]
I love issues that clear up by themselves.
@HCSarise great tutorial by the way :smile:

**Comment by HCSarise** [comment]
Awe thank you! :)
