### ISSUE TITLE
AE2 Crafting Integration

### ISSUE THREAD

**Issue by ruifung** [RS485/LogisticsPipes#53]
refer to https://github.com/RS485/LogisticsPipes-Deprecated/issues/531

Just making copy of that request here.

**Comment by ruifung** [comment]
Hmm, with the new AE2 crafting system I suppose this might work out somewhat better with it? I don't really understand the intricacies of the LP crafting system so I can't really say... but AE2 can do materials calculation for crafting jobs now...

**Comment by AartBluestoke** [comment]
<edit> possibly wrong comments about AE's internals removed.

**Comment by ShadowDrakken** [comment]
That's not true of AE2. AE2 reserves items for crafting as well.

**Comment by ruifung** [comment]
Maybe have it work something like this?
1. Send autocrafting request to AE system, checking for missing materials.
2. If AE reports missing materials, check LP network for materials and send them into the AE network.
3. If not wait for result and extract from AE when complete.

Although with the inevitable differences between LP and AE2, some things might need to be taken into account. Like which crafting CPU to use, and if there isn't enough crafting storage for the request.

Although in the second case it might be worked around by spltting the request up into smaller requests that can fit into the crafting storage.
And in the first case, maybe use crafting cpu's in ascending order based on their available crafting storage.

As I am not familiar with the code of LP and the AE2 API, I am uncertain of the feasibility of this. However if this combined with 2 way access between LP & AE would make for almost seamless integration.

**Comment by Ioandar** [comment]
from AE2 issue tracker...
"Are there any developer docs that would point me in the right direction to start the integration?"
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/21#issuecomment-87269815

I dont have enough knowledge to help but maybe somebody else has?

**Comment by ruifung** [comment]
Any progress on this?

**Comment by bziemons** [comment]
There is the mod Logistics Bridge
