### ISSUE TITLE
Logistics Vs TConstruct

### ISSUE THREAD

**Issue by Tyrantin** [RS485/LogisticsPipes#534]
Trying to connect Logistic pipe to a Smeltery from TConstruct and Cannot get it to function. Is this a known issue or am I doing something wrong!?

**Comment by Tyrantin** [comment]
Trying to create a Molten storage system

**Comment by loordgek** [comment]
can you post a pic?

**Comment by Tyrantin** [comment]
How do you wat to see it

**Comment by loordgek** [comment]
http://imgur.com/

**Comment by Tyrantin** [comment]
https://www.dropbox.com/sh/ycvfrws5yidkjh7/AACcdUzlCRmoJOmOC_lu2YXaa?dl=0

Try that

**Comment by bziemons** [comment]
The provider does provide from a (liquid) storage to crafting, request or supplier. What you need instead of the Liquid Provider is a Liquid Extraction Pipe in this instance.

**Comment by Tyrantin** [comment]
Thank you. Much appreciated Zorro. Keep up the awesome work! This mod will stay in my personal mods faves!!!!
