### ISSUE TITLE
Api problem with GregTech items

### ISSUE THREAD

**Issue by yenon** [RS485/LogisticsPipes#536]
GregTech items havn't got their real name assigned to them, but something like "gt.metaitem.xx.xxxx.name" in the ComputerCraft-Api.
This might not be your fault, but i wanted to report this strange behavior to you.

example code (in the lua console):
request_pipe=peripheral.wrap("back")
items=request_pipe.getAvailableItems()
print(items[1].getValue1().getName())

output:
gt.metaitem.01.2849.name (this is just an example, this one is different for every item of GregTech)

The only strange behaviour i noticed too was that those items got the right name in the GUI of the Request-Pipe. This might be because that one might use Oredictionary names?

I could observe this kind of behaviour in 2 cases:
1. If the items were stored in a AE2-Network
2. If the items were stored with LP

Used versions:
buildcraft-6.2.6.jar
logisticspipes-0.8.2.84.jar
gregtech_1.7.10-5.06.06.jar
industrialcraft-2-2.2.658-experimental.jar
appliedenergistics2-rv1-stable-1.jar

**Comment by davboecki** [comment]
CC gets the name from the server where no language is available. The ingame GUI uses the client name setting. You can try to run "/lp tn" as OP. That should help out with most of the names on simple items. But other than that there is nothing anybody can do.
