### ISSUE TITLE
BuildCraft 6.3.0 API

### ISSUE THREAD

**Issue by asiekierka** [RS485/LogisticsPipes#539]
Please implement it ASAP, as BC 6.3.0 release is imminent and I want to use BC 6.3.0 in the Magnum Opus pack.

Changes:
- no more GateMatrix/FacadeMatrix/..., instead, there is a separate PluggableState you need to listen for,
- a lot of pluggable-related pipe code got rewritten (actually lowering the amount of pluggable code on the pipe's side, IIRC),
- TileGenericPipe extending will BREAK if BuildCraftCompat is installed, as BuildCraftCompat adds a TileGenericPipeCompat extending TileGenericPipe and BlockGenericPipeCompat extending BlockGenericPipe. Either add a listen for that, as BC did, or extend Compat classes and depend on BCCompat.

**Comment by bziemons** [comment]
Duh, it's nice that you tell us, but I do not care what your personal reasons are. It's rather for the whole community.

**Comment by davboecki** [comment]
I won't be able to work on LP for the next couple of weeks. 
As for the tilegenericpipe. We aren't BC pipes anymore. We only connect to them and have support for gates, facades and plugs.

**Comment by asiekierka** [comment]
I'll look into it over the next few days myself.

**Comment by Tyrantin** [comment]
Sorry didn't realize that it was recently posted. I looked, but apparently over looked this post. Just curious on an ETA for update?

**Comment by bziemons** [comment]
There is no ETA.

**Comment by davboecki** [comment]
I know that @asiekierka was looking into it. I don't know how far he got but on the other hand I should be able to take a look at it myself in the next couple of days. Then I will know more about the work amount required.

**Comment by Tyrantin** [comment]
Sweet! thx. My Fluid management system is down> :(

**Comment by asiekierka** [comment]
@davboecki - I'm not doing it without a complete rewrite. I don't fancy maintaining one pipe implementation in BC and one in LP at all.

NOTE: Most of BC code now looks for IPipeTile and not for TileGenericPipe. This might make things simpler. But please, please, PLEASE rewrite it into something coherent, as I cried when I saw the way you're doing things now.

**Comment by asiekierka** [comment]
I decided I'm going to try and make the BCPipe/TileParts just extend TileGenericPipe and Pipe respectively, while making the BC pipe code a bit more generic to stop code duplication. BC 6.3.2+, then.

**Comment by davboecki** [comment]
Sounds good :D
If you need any help just say so. I know LP isn't the best and cleanest code^^

**Comment by Tyrantin** [comment]
Just wondering if you have found what you need to change in the LP code to make it compatible for BC update? Really cannot due without your mod.

**Comment by xJon** [comment]
No pressure, eh? but I wish to know if I should wait for the update (AKA it will be out pretty soon) - or I should not wait for it.
Thanks.

**Comment by davboecki** [comment]
It's always the best not to wait. Even when I say i'm nearly done RL can get in the way and delay the update.
While we are at it, I have completed most of the basework for the BC 6.3 update. Still need to fix some bugs and probably will need to make a PR to BuildCraft. So it's still some time left untill I can commit the update.

**Comment by xJon** [comment]
Understandable.
The thing is that I'm a modpack creator, and I wish to know if I should wait for LogisticsPipes or remove it - but only if the mod is dead - it's not - I'm not going to remove it. I will wait, it's okay. LogisticsPipes can do things that no other mod can.
I just can hope it will be out soon, thank you for your answer. [:

**Comment by davboecki** [comment]
Updated

**Comment by Casper-O** [comment]
Lovely, cant wait to try it out - great mod :)
