### ISSUE TITLE
Thaumcraft/Logistics request pipe crash

### ISSUE THREAD

**Issue by Renadarain** [RS485/LogisticsPipes#54]
Logistics Pipes 400
Thaumcraft 3.04c

When requesting items from the request pipe the client crashes.

http://pastebin.com/0FGiXmdU

Thanks for any help solving this :)

Regards,
Renada

**Comment by davboecki** [comment]
Should be fixed.

**Comment by Renadarain** [comment]
Confirmed working with Logistics 405

Thank you very much :)
