### ISSUE TITLE
Texture Pack support is not complete

### ISSUE THREAD

**Issue by DrTerr** [RS485/LogisticsPipes#541]
Logistic Pipes do not pick up items textures from texture packs, only block textures.
I belive items texture loading is incorrect and doesn't consult texture packs as it should.
This makes developing texture pack significantly harder as only way to properly apply is to patch jar file.

**Comment by bziemons** [comment]
I cannot confirm this. I have had texture packs overriding pipe's and module's textures without accessing the jar. If I am wrong, please tell me though.

**Comment by hron84** [comment]
@DrTerr always specify LP version you using and affected block/item name. Also post some comparison pictures to let developers know your problem. They cannot help you without any specific information as they not playing with your environment.
