### ISSUE TITLE
Problem with request pipe

### ISSUE THREAD

**Issue by HadesDurin** [RS485/LogisticsPipes#542]
ok here a short notification:
i use latest
logistic pipes 0.8.2.89 build
buildcraft 6.2.6
applied energistics 2 rv2 beta 1
and
forge 10.13.2.1264

problem is i store around 300k stone in a deep storage unit and request things manually with a request pipe mk2 from the dsu.
while all other numbers looks fine to me the first item stone (stein in german) looks strange

Pictures as prooves:
![2014-12-28_14 46 44](https://cloud.githubusercontent.com/assets/5231067/5564130/40df9962-8eab-11e4-9c38-621f9432524b.png)
![2014-12-28_14 46 50](https://cloud.githubusercontent.com/assets/5231067/5564129/40de8cac-8eab-11e4-915d-5409ea04bfe1.png)
![2014-12-28_14 47 14](https://cloud.githubusercontent.com/assets/5231067/5564131/40e7e9fa-8eab-11e4-82e3-4eeba6c64fd4.png)
![2014-12-28_14 47 23](https://cloud.githubusercontent.com/assets/5231067/5564128/40dcd560-8eab-11e4-9ff1-f17870f0f097.png)
![2014-12-28_14 47 30](https://cloud.githubusercontent.com/assets/5231067/5564132/40e83fc2-8eab-11e4-9ebf-43c4d3233830.png)
![2014-12-28_14 47 38](https://cloud.githubusercontent.com/assets/5231067/5564133/40e8ec2e-8eab-11e4-88ce-170bbf9e446a.png)

**Comment by AartBluestoke** [comment]
0M3 is short for 0.3M, which matches with the 360k stone you had available.
Perhaps it could have been rounded up to 0m4, but I believe that number is
always rounded down. There is a key shortcut which will show the they count
in the mouse over (shift iirc)

**Comment by bziemons** [comment]
Yeah.. shift or ctrl.. I use it without thinking about it ;) Question is answered, I guess?
