### ISSUE TITLE
Supplier pipe works only in 'Infinite' Request mode.

### ISSUE THREAD

**Issue by BoboSims** [RS485/LogisticsPipes#543]
Having added build #89 to DireWolf20's modpack v1.0.3, I find that the supplier pipe works in only one request mode: Infinite. This is, however, not always (or even hardly ever) a good mode to work with if you want the requested item to be distributed between multiple destinations.

**Comment by 61352151511** [comment]
Give a bit more detail, the supplier pipe when on bulk50 mode works fine for me. Having it attached to a furnace and being kept stocked with 64 fuel, any time it reaches below 32 (50% because bulk50) it sends another 32 to the furnace.
