### ISSUE TITLE
Conflict between LogisticsPipes and Railcraft, NEI, MineChem, MineTweaker, AE2 : NoClassDefFoundError

### ISSUE THREAD

**Issue by ynerant** [RS485/LogisticsPipes#544]
I use LP build 89, Railcraft 3.4.0.0 and NEI 1.0.3.78. When I searched a recipe for a Railcraft's item, it made this crash : http://pastebin.com/qVkHDxDF.

**Comment by SinusoidalC** [comment]
……have you tried update your NEI to 1.0.3.74?

**Comment by ynerant** [comment]
Sorry, I wanted to say 1.0.3.78

**Comment by davboecki** [comment]
Now that one is strange. It says that our static initialiser for the IdemIdentifier class failed to run. That is realy strange because there is nothing out of the ordinary in there.
