### ISSUE TITLE
crash with buildcraft 6.3

### ISSUE THREAD

**Issue by Sailren** [RS485/LogisticsPipes#547]
http://paste.ubuntu.com/9682508/

**Comment by loordgek** [comment]
use 6.2.x

**Comment by TheOldOne822** [comment]
LP blacklists newer versions even if it would otherwise work it deliberately crashes if the version number is newer

**Comment by Sailren** [comment]
for what reason?

**Comment by asiekierka** [comment]
@Sailren - BC 6.3 rewrote some pipe code and it would crash instantly if you tried to go around it. I know as I did.

**Comment by TheOldOne822** [comment]
I don't know why the crash on version check is there but I do know more often then not it would crash anyway.

**Comment by bziemons** [comment]
The crash is to prevent crashing you ingame and protect your saves from possible corruption. We do that, because an incompatible BC version does lead to a crash sooner or later anyway (as stated above).
Duplicate of #539 .
