### ISSUE TITLE
Ignore NBT/damage option in basic item sink

### ISSUE THREAD

**Issue by StarkRG** [RS485/LogisticsPipes#554]
I'd love a way to be able to sink items while ignoring NBT data, this would make it a lot easier to use Extra Utilities filing cabinets. If adding this option seems too advanced to include in the basic item sink module and basic pipe, then perhaps a separate, special module would be more appropriate.

**Comment by hron84** [comment]
Polymorphic module should include this option too

**Comment by Hakameda** [comment]
Could this actually have the option to ignore NBT and Meta Data? Would help with GT ore processing.

Or even an ore dictonary filter?

**Comment by StarkRG** [comment]
Hakameda: the OreDict Item Sink will do ore dictionary filtering. 

Having an option to Ignore NBT and Meta Data is exactly what I was requesting.

**Comment by Hakameda** [comment]
I tried the oreDict item sink, But it was not working properly. I assumed it didnt work for what i needed.

**Comment by StarkRG** [comment]
Hrm... Slightly related. Although itemsinks require exact NBT/Damage matches, advanced extractors don't.

The way I discovered this was trying to set up Pam's Harvestcraft bees (completely different to Forestry bees) to be automatically be inserted when at full durability and extracted when fully depleted. Unfortunately, even though I've set the extractor to only pull fully depleted bees it removes the brand new, undamaged ones.

**Comment by davboecki** [comment]
ItemSinks don't require exact match. As long as the item is damagable it is ignored. Same goes for the Advanced Extractor. I will add the ability to add the Fuzzy Upgrade to the Basic Pipe and ItemSink module as well. It will than allow you to tell it to ignore the NBT and/or Data value.

**Comment by davboecki** [comment]
Implemented inside the 0.9 Beta builds.
