### ISSUE TITLE
Pipes generating constant chunk updates

### ISSUE THREAD

**Issue by Amelia-** [RS485/LogisticsPipes#558]
Starting with version 0.8.3.92 or 91 (I have not tried 90) each logistics pipe I place down generates about 6 chunk updates per second (atleast I think it is per second anyway? what it displays in the top if you press F3).
If I test this in a flat world world in creative mode I can place down quite a few of them before this starts to take down the frame rate, hundreds of chunk updates constantly but if I do this in a more complex world it starts to cause a lot of lag after just placing a few pipes.
I have tested it with several different kinds of logistics pipes and they all seem to do it.

I have tested this in creative mode with no other mods besides Logistics Pipes 0.8.3.92 and Buildcraft 6.3.3 oh and Forge 10.13.2.1277.

I found out about it after I tried to load up a world that was made with 0.8.2.89 and Buildcraft 6.2.6 and has some complex logistics pipes systems which run great on those versions of the mods but does about 3 or 4 FPS on my computer after updating to the latest versions.

Buildcraft pipes placed down do not have this problem.

**Comment by Ioandar** [comment]
After updating to bc6.3.3 (and therefor updating lp to .92) I had massive fps issues.

maybe related? I have many lp pipes and many lp-autocrafting-tables

---

buildcraft-6.2.6.jar
logisticspipes-0.8.2.89.jar
30 fps

---

buildcraft-6.3.3.jar
logisticspipes-0.8.3.92.jar
3fps

**Comment by AartBluestoke** [comment]
Would you be able to record a jvisualvm performance performance profile in
sampling mode?

Jvisualvm can be found in the Java SDK bin folder.

Note: there are 2 recording modes- sample and profile

sampling is low impact. "Profiling" has a large impact, which may persist
until you restart the application as it adds tags to each function so it
can count how many times they run. This adds a fraction of a second to
every function call, and some functions are used many thousand of times per
second.

'Sampling' is a low impact performance monitoring method which simply
notes, a few times per second, what the application is doing. You might
want to sample as quickly as possible (100 or 200) ms, and record for at
least 30 second. Long term recording (an hour or 2 on a busy served) is
good for noticing trends and general performance hogs. Short term recording
(1 to 5 second) is good for spikes, assuming you can record a second that
contains the spike.

**Comment by davboecki** [comment]
Should be fixed by: https://github.com/RS485/LogisticsPipes/commit/dd8bd94fbfd6f41a0ee4115baa08a2674312c234
