### ISSUE TITLE
Crash when loading existing world with build 93

### ISSUE THREAD

**Issue by Amelia-** [RS485/LogisticsPipes#560]
After updating to build 93 I get the following crash when I try to load my existing world with logistics pipes in them:
http://pastebin.com/WYGBMAhx

This world does load with build 92.

Edit: Oops I see someone reported it just before me, #559 .

**Comment by Ioandar** [comment]
ye, seems we posted close to each other. 

is there a way to combine those 2 or just delete mine (i have no pastebin in it)

edit: I have closed the other so we dont have 2...

**Comment by davboecki** [comment]
Should be fixed.
