### ISSUE TITLE
TE Power Provider won't power machines

### ISSUE THREAD

**Issue by StarkRG** [RS485/LogisticsPipes#561]
LP pipes with the TE Power provider upgrade installed won't provide power to Thermal Expansion, EnderIO, or Minefactory Reloaded machines. They do seem to work with Buildcraft machines, and will work with EnderIO energy conduits.

I saw someone mentioned this in the forum post as being a known issue, however I couldn't find any open issues here about it. I figured I'd wait until the BC 6.3 compatibility update before bugging you guys (because, honestly, that was the bigger issue, so thanks for doing that as quick as you did).

**Comment by Amelia-** [comment]
I have seen this happen too but they still connect to Thermal Expansion energy cells so you can kind of bypass it with those but it's not ideal. Maybe it has something to do with the version of the RF API?
It worked fine a little while ago but that was a few updates back on LP and the CoFH mods.

**Comment by Barhandar** [comment]
RF API update broke that nearly across the entire board, the only two mods which _still_ get power directly from supplier are Mekanism and GalactiCraft.

**Comment by Ioandar** [comment]
I power the machines from forestry and extra-bees with LP pipes RF Power provider. works flawless for me

**Comment by StarkRG** [comment]
Loandar: that's probably because forestry and extra bees aren't Thermal Expansion, Ender IO, or MFR and are closer to being like buildcraft machines.

**Comment by davboecki** [comment]
Ok this is fixed now.
