### ISSUE TITLE
Packet error when returning to overworld from arroma's mineing world

### ISSUE THREAD

**Issue by Starhero** [RS485/LogisticsPipes#563]
I haven't tested other dimensions yet.

Going to the mining causes nothing.

Coming back home from the mining world crashes shortly after the "legs breaking" sound associated with portals.

http://paste.ee/p/H9gvi

**Comment by Starhero** [comment]
PipePositionPacket now is the new packet that is crashing...

**Comment by Starhero** [comment]
After doing a complete upgrade on all mods I still am receiving errors.

http://paste.ee/p/9E0SZ

logisticspipes.network.packets.pipe.PipeSignTypes.processPacket(PipeSignTypes.java:34 referring to a null pointer..

**Comment by Starhero** [comment]
Seems it is crashing when

msg.packet.processPacket(msg.player);

calls

((CoreRoutedPipe)pipe.pipe).handleSignPacket(types);

Assuming signpacket types object is invalid.

I have no signs on any pipes. I do have autocrafting system.

This also does not happen when there is nothing going through any pipes in my entire base..only when going the portal back to my base it triggers when something is traversing my pipe network...

This is making it hard to get a quarry going in the mining world. When the error triggers, I am brought back to the connect menu, as if I was disconnected by the internal server in SSP.

**Comment by Starhero** [comment]
new error after build 96
http://paste.ee/p/bDz9E

also wondering if chunks are actually being loaded by my chunk loader (chicken chunks).

**Comment by bziemons** [comment]
Aroma's mining world has it's problems related to stopping the day-night-cycle alltogether.
We cannot support any mod combination, maybe you want to have a look at another mod that does similar things as the aroma's mining world.
Other than that the pasteee links are gone. I prefer GitHub gists..

**Comment by hron84** [comment]
@theZorro266 this problem can occur if you return from any dimension that stops day/night cycle, or it's a problem with the way how the mining world does it?
@Aroma1997 could you please comment on this?

**Comment by bziemons** [comment]
@hron84 I am not entirely sure, if stopping the day-night-cycle causes the errors, which I cannot see because of pasteee. But I did use that mod and did have problems using other mods in that mining world (e.g. MFR). LP did not cause any problems though. Mystcraft however can stop the day-night-cycle without causing problems at all. So I just suspect that the way Aroma's mining worlds are done, they have to cause problems.

**Comment by Aroma1997** [comment]
It's fixed in the 1.8 version. Will do a backport soon.

**Comment by hron84** [comment]
@theZorro266 thanks for clarify this.

@Aroma1997 thanks for your assistance
