### ISSUE TITLE
Request Logistic Pipe --> ME Interface ---- no Items from LP Network visible in AE2

### ISSUE THREAD

**Issue by Ioandar** [RS485/LogisticsPipes#567]
I have a Request Logistic Pipe connected to an ME Interface.

Problem: No Items from LP Network are visible in AE2

> logisticspipes-0.8.3.98.jar
> appliedenergistics2-rv2-beta-8.jar | appliedenergistics2-rv1-stable-1.jar

Connecting a MK2 with ModItemsink/Provider modules at the ME Interface WORKS FINE
-> Items from AE2 are available in LP
-> AE2 Items will be routed into the AE2 systems

No idea which side it may be...

**Comment by davboecki** [comment]
AE2 doesn't handle this. Nothing we can do.

**Comment by Ioandar** [comment]
ty, will ask  AlgorithmX2 if he can have a look in AE2. cheers

edit:  AE2 lost LP Integration in transition...
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/21
