### ISSUE TITLE
BC Gates not working with LP

### ISSUE THREAD

**Issue by RikuSS4** [RS485/LogisticsPipes#569]
I am using Logistic Pipes 0.8.3.98 and BuildCraft 6.3.4. Whenever I put a gate, tried diamond and iron gates, on a LP pipe and right click to open GUI, I get an error in chat log: "Disabled BCProxy for Mod: BuildCraft|Transport. Cause was an Exception." Then the LPs no longer connect to other pipes until server/game restarted. Tried all different versions of LP 0.8.3 and BC 6.3. Tried using Java version 8u20 and version 8u31. Gates work with BC 6.2 and LP 0.8.2.

Log: http://pastebin.com/XZUERAHx

**Comment by Ioandar** [comment]
Maybe too new? I think LP is updated to BC 6.3.2

http://ci.thezorro266.com/view/Logistics%20Pipes/job/LogisticsPipes1.7/changes

**Comment by davboecki** [comment]
Could you try if it depends on the direction you click on the gate. (I thought I fixed that)

**Comment by RikuSS4** [comment]
I tried using BC 6.3.2-6.3.4 and LP 0.8.3.90-0.8.3.98 in different combinations seeing if any particular build combo was the issue. Happened with all combos. I tried clicking from different angles and with the gate on different sides of the pipe, same thing happens.

**Comment by davboecki** [comment]
Should be fixed.
By the way you don't need to restart the game when an Proxy is disabled trough an exception. There is a command to reenable it. `/lp wrapper enable [proxyname]` in this case `/lp wrapper enable BCProxy`
