### ISSUE TITLE
Crash opening existing world with 8.3.100

### ISSUE THREAD

**Issue by spidey1958** [RS485/LogisticsPipes#570]
I getting this error when I try to open any existing world with logistics pipes updated to 8.3.100

http://pastebin.com/8yKvjvb3

**Comment by davboecki** [comment]
Not our problem. Caused by `TheCampingMod_2.1d`

**Comment by spidey1958** [comment]
Every time I remove a mod (I've removed 25 mods so far)causing error, a new mod cause an error. But as soon as I remove logistics pipes I have no errors.

**Comment by davboecki** [comment]
Remove `TheCampingMod_2.1d` and post a new crash report then.

**Comment by spidey1958** [comment]
Next mod was Ancient warfare

http://pastebin.com/fW6hvdsq

Removed and ran again with a restored copy of world

Natura caused the next bomb

http://pastebin.com/qWQcV3T0

If I go back to Logistics pipes .89 and Buildcraft 6.26 I do not the problem So I guess could also be a Buildcraft issue. I have no problems with a new world created. But even If I just create a world under .89 and 6.26 when I open it get errors and this screen
![image](https://cloud.githubusercontent.com/assets/2867630/6099223/a71981f6-afb8-11e4-8a8d-eaedae83afd6.png)

It actually gets into the worlds shows the chat text then bombs out

**Comment by davboecki** [comment]
Could you check if the problem happens with BC alone, without LP. And can you check if it's the same problem when you only update from build 89 to 90?

Because all errors you posed are caused by broken item mappings (which the screenshot seems to indicate as well)

**Comment by davboecki** [comment]
Can you post a full FML log as well please. One of your original update attempt.

**Comment by spidey1958** [comment]
Looks like I was wrong and it's actually new buildcraft that is causing the error which you need with new logistics. Guess it's a new world for me.
