### ISSUE TITLE
Texture error of facades

### ISSUE THREAD

**Issue by Towdium** [RS485/LogisticsPipes#576]
It occurs to me that the facades is not using correct texture when the facade is maded by blocks whose ID contents several blocks with different textures.(sorry for my awkward long sentence) For example, when I put facade of colored wool, it always uses the texture of white wool and this issue also occurs to facades made by MFR decoratative blocks, chisel blocks(I use the mod called chiselfacades to add them) and many other blocks.
By the way, when the facades are put onto BC pipes, they show correctly. So I put the issure here.
Using BC 6.3.6, LP 0.8.3.100.
Sorry again for my poor English :)

**Comment by SonOfTheStars** [comment]
Can you show a Picture?

**Comment by cdfa** [comment]
I kinda have the samen problem, only with me the facade renders the black/purple square texture and i'm using a chisel facade. Here is a picture:
![image](https://cloud.githubusercontent.com/assets/8250462/6203333/7566cff6-b51c-11e4-9d2a-7a912f4d374b.png)
