### ISSUE TITLE
Bee modules recipe uses fluid.honey instead of honey

### ISSUE THREAD

**Issue by estebes** [RS485/LogisticsPipes#578]
Can't craft beesink modules and apiary refiller modules because the recipe uses fluidd.honey instead of honey. Probably has to do with forestry changing honey

**Comment by SonOfTheStars** [comment]
If you have Thermal Expansion Installed, try to craft it with a Cyclic Assembler, since it supports liquid crafting

**Comment by SonOfTheStars** [comment]
Ill take a look at it

**Comment by SonOfTheStars** [comment]
Oh right!
You need the Carpenter to do all those ;)

**Comment by estebes** [comment]
I was able to craft them because some of extra bees combs still produce fluid.honey instead of honey but it is kind of buggy. it has no texture and cant be put into capsules or buckets. Found another bug which has to do with this config parameter

```
# Whether or not the Carpenter is required to craft Forestry related pipes/modules.
B:mandatoryCarpenterRecipes=true
```

when set to false at least two things happen. First the recipes don't change at all (they still require the carpenter and thus this can't be used to bypass this fluid.honey thing) and the apiary refiller module doesnt work correctly (it still extracts stuff from apiaries but it doesn't replace the princess and drone and instead takes them to the default route destination).

**Comment by SonOfTheStars** [comment]
Ill take a look at it. Probably refers to their outdated forestry Proxy

**Comment by Ioandar** [comment]
I dont know if that is related but I just had fluid.honey showing up on my squeezer when updating forestry to the beta.

Gone back to 'forestry_1.7.10-3.4.0.7' and normal 'honey' showed again. I had to break squeezer, honeyCarpenter, Analyzer and Pipes to make all look normal again. 

forestry_1.7.10-3.4.0.7
logisticspipes-0.8.3.100

edit: tested going to newest 'unstable' forestry and squeezer, honeyCarpenter, Analyzer and Pipes remain working fine even when breaking/replacing them. Maybe in my case I broke mine by using an older 'unstable' version of forestry...

forestry_1.7.10-3.5.0.471-unstable
logisticspipes-0.8.3.100

**Comment by Amelia-** [comment]
Forestry changed their honey a little while ago.
Logistics pipes uses the old honey which you can only get from certain combs from Binnie's mods for now until he updates it I guess.

Forestry allows you to turn the old honey into the new honey using a still but not the other way round so it's probably best to change logistics pipes to use the new honey.

**Comment by Ioandar** [comment]
new build 103 fixed all my fluid.honey problems and works flawless with bc6.4

honeyCarpenter can now craft all needed Pipes/Modules and recipes are all well in NEI for me too.

I think this can be closed now, no?
