### ISSUE TITLE
Logistics HUD

### ISSUE THREAD

**Issue by megamanzteam** [RS485/LogisticsPipes#58]
I tested with build 407 and the displays will not render. I don't know if it is due to being a Dev. build and has not been implemented yet or if it is an unknown issue yet. So if you guys are aware you can ignore this report.

**Comment by davboecki** [comment]
Can't reproduce. For me they work fine.

**Comment by megamanzteam** [comment]
I managed to see errors from MultiMC's console. I uploaded the log, perhaps that can help? http://www.mediafire.com/view/?22cabl6smlia4ed

**Comment by davboecki** [comment]
Ok thanks for that. I now know where the bug is thanks. will be fixed soon.
