### ISSUE TITLE
Logistics Pipes Facades Textures Mismatch

### ISSUE THREAD

**Issue by jurplel** [RS485/LogisticsPipes#580]
![2015-02-16_13 45 40](https://cloud.githubusercontent.com/assets/10716694/6217464/20a4ea18-b5e2-11e4-8138-601113bafbc9.png)
When fitted abyssal stone facades are placed upon a logistics pipe, it shows as abyssal stone brick. This does not occur on vanilla buildcraft pipes.

**Comment by davboecki** [comment]
Duplicate: https://github.com/RS485/LogisticsPipes/issues/576
