### ISSUE TITLE
BeeSink Module does not sink <unknown genome> Drones in Drone Mode

### ISSUE THREAD

**Issue by Ioandar** [RS485/LogisticsPipes#581]
I have an MK2 with a BeeSink Module that is set to sink "Drones"

Analyzed Drones will be sunk into that Drones-Chest like expected but not yet analyzed  Drones ('unknown genome') will land in my 'default-route-import-chest'

Can someone please crosscheck this to make sure that I am not just 'doing it wrong'? thx

logisticspipes-0.8.3.100

edit
http://s14.postimg.org/hxcflthfl/lp_beesink.png

**Comment by davboecki** [comment]
BeeSink only works on Analyzed Drones. You need to analyze them before you can sort them.

**Comment by Ioandar** [comment]
tyvm for the quick answer and all the work you and the team put into LP pipes!

I totally love this mod! cheers
