### ISSUE TITLE
Bee Analyzer Logistics Pipe fails to insert Bee (Bee pops out of Pipe when trying to insert)

### ISSUE THREAD

**Issue by Ioandar** [RS485/LogisticsPipes#582]
I tried the Pipe in both modes and on different sides on an Analyzer (ExtraBees). Bee pops out.

I also tried the Pipe on an vanilla Hopper/Chest. Same result. Bee just pops out

I have no idea what I am doing wrong. A bug? Do I use it wrong?

Manually inserting that Bees into Hopper/Chest/Analyzer works just fine. Piping in Bees into the Analyzer using BC Pipes also works.

I want to sink un-analyzed bees into a chest. That Pipe should do the trick, no?

logisticspipes-0.8.3.100

**Comment by SonOfTheStars** [comment]
The Be Analyser Pipe/Module are made to Interact with the Analyser Block from Forestry.
It will not Work with the Analyser provided by ExtraBees!

I recommend you switch to a Forestry Analyser, or you use the bee-sink.
Greetings,
Bitterholz

**Comment by Ioandar** [comment]
ty for the quick answer, I will try that. 

BeeSink Module does not work since it only sinks already analyzed bees. I will try Forestry Analyzer...

cheers

edit01: Forestry Analyzer works perfect. tyvm for the help (and all the work on LP). 

Only glitch is that the visual state of the analyzer is not updated when the bee enters or leaves the analyzing state. 
The Forestry Analyzer normaly shows the bee that is currently analyzed in the Model, so you can see from outside which bee is currently be worked on. But that maybe on Forestry side, I dont know. I will try pumping in a Bee with BC Pipe and see if it shows...

edit02: Same visual glitch with piping in via BC Pipe so I assume it is on forestry side. I will report it over there... All works fine now, tyvm. If it is not too much hassle maybe a sink of an un-analyzed bee into a vanilly chest would be great but has low prio from my side since now all is working great for me. 
3 cheers for LP and the team!

**Comment by SonOfTheStars** [comment]
LP doesnt change any Rendering of other Mods stuff, So its probably on their Side.

**Comment by Ioandar** [comment]
It is indeed on forestry side and mezz added it to the bugtracker of forestry...

https://github.com/ForestryMC/ForestryMC/issues/519#issuecomment-75361288

**Comment by Ioandar** [comment]
jepp, rendering bug was on forestry side. mezz put it on the list and fixed it!

**Comment by hron84** [comment]
@Bitterholz is there any argument against supporting more analyzing blocks other than vanilla Forestry one? Just kindly asking, I can accept if there is any.

**Comment by SonOfTheStars** [comment]
Not really something against it, but wich analyzers  would you Support other than vanilla Forestry?

**Comment by Silwing** [comment]
Binnies mod Genetics has its own Analyser (with an S). I think that might be what @hron84 is referring to?

**Comment by bziemons** [comment]
@hron84 please open a new issue, if you want to make a suggestion. That should not be discussed off-topic in an old issue.

**Comment by hron84** [comment]
@theZorro266 I am really sorry. Btw, done.
