### ISSUE TITLE
TC Mana Beans and JABBA Barrels

### ISSUE THREAD

**Issue by Sidorion** [RS485/LogisticsPipes#583]
1. When I pur a JABBA barrel next to the request pipe and request beans they don't enter the barrel but bounce back instead
2. Filtered item sink modules don't react on beans entering the system. Tried normal sink modules and polymorphic. The beans always go to the default route instead.
   Both works fine when I use chests or strongboxes instead of the barrels
   Providing beans from JABBA barrels works fine.
   I use:
   JABBA 1.2.0a
   Thaumcraft 4.2.2.1
   LP 0.8.2.89

**Comment by SonOfTheStars** [comment]
Is the Barrel Empty?
If its Occupied or Locked(little lock on Bottom Right from a Shift-RightClick), this behavior is only natural.
Mana Beans have different NBT Data so you cannot fit 2 Sorts of Manabeans into 1 Barrel, since they are treated as different ItemStacks
Greetings,
Bitterholz

**Comment by Sidorion** [comment]
I'm well aware of the fact, that different bean types can't be stored in one barrel, thank you.
Of course I used an empty barrel repectively filtered the same bean type in the sink as in the barrel.
When I put a single piece of normal BC pipe between the request pipe and the barrel, the beans enter the barrel without any problem.

**Comment by hron84** [comment]
@Sidorion could you please attach a screenshot from your setup, or maybe a short video? Also, could you please try to update LP and TC to the latest version and try it out again?

**Comment by Sidorion** [comment]
There's nut much of a setting. Just a MKII on a barrel with provider and item sink module. In the sink one bean from the barrel as filter.
Updating is a bit of a hassle since I'm not the server owner, but I'll try and test the newest versions in a SSP test world this evening.

**Comment by Sidorion** [comment]
Tested it with the actual versions, still the same problem.
I got a chest w. extractor, one item sink and one barrel - no extraction. As soon as I replace the barrel with a second chest, the beans are pulled out of the first and send to the second chest.

btw. DSUs from MFR don't work either, so I wildly guess it's the DSU-API.

**Comment by bziemons** [comment]
And you can put the requested item into the barrel manually?
I can't see why it should not work with exactly that type of items, when most items work with the DSUs and Barrels, so I suspect the error somewhere else.

**Comment by hron84** [comment]
@Sidorion I still recommend you to post some pictures and/or some video about your problem otherwise we cannot help you more based on your comments.

Hint: you can take a screenshot by pressing F2 on your keyboard.
