### ISSUE TITLE
Newest thermal expansion and LP

### ISSUE THREAD

**Issue by crunkazcanbe** [RS485/LogisticsPipes#584]
As the title says http://pastebin.com/fqSW4tTN

The game does not crash I just see this in the console while its loading .

Thank you!

-Crunk

**Comment by SonOfTheStars** [comment]
Its working for me, and Im on a Modified version of LP Milestone 0.9, into wich Ive hand-ported the Changes that weren´t allready over.

**Comment by crunkazcanbe** [comment]
How is what u said relevant to what i said? I am talking about the latest public release .100 . Not a custom version you ported.

**Comment by crunkazcanbe** [comment]
Are you saying i should compile the source here on Git?

**Comment by davboecki** [comment]
What Forge version are you using. Could you try with forge build 1291.

**Comment by crunkazcanbe** [comment]
LogisticsPipes is not working with the new stable builds of COFH mods .

**Comment by crunkazcanbe** [comment]
BTW I am using forge 1301 I think it is , but I know its a newer forge then 1291

**Comment by SonOfTheStars** [comment]
you know 1301 is a 1.8 Build right?

**Comment by crunkazcanbe** [comment]
My bad its forge 1307 i am running not 1301 its the newest forge for 1.7.10

**Comment by SonOfTheStars** [comment]
Ahm...quick reminder to you, every forge above 1291 is for Minecraft 1.8....

**Comment by crunkazcanbe** [comment]
Wrong go to the page you download forge click 1.7.10 builds and you will see. I have a 400 mod mod pack running with forge 1307 .

**Comment by crunkazcanbe** [comment]
1307*

**Comment by crunkazcanbe** [comment]
http://files.minecraftforge.net/minecraftforge/1.7.10

**Comment by crunkazcanbe** [comment]
I find 1307 to be more stable then 1291 tbh i am also having higher fps

**Comment by hron84** [comment]
@crunkazcanbe do not confuse branches with versions. You talking about 1.7.10 branch however on the main page (http://files.minecraftforge.net/) if you select 1.7.10 from the dropdown the latest available forge is 1291. Despite your private opinion, could you please test it with 1291?

**Comment by crunkazcanbe** [comment]
Ok ill test that when i get off work , but i always run the latest forge option on the multimc launcher . If 1291 makes a diffrance for this mod then somthing is not coded right because out of 400 mods not one other mod has a issue with forge 1307.

**Comment by bziemons** [comment]
@crunkazcanbe that may be correct, but the reason you should try 1291 is to find out the reason of the error.
My guess is though, that this: https://github.com/CoFH/ThermalFoundation/commit/9f93994f7b504257619cecfe73b8fc8eea070a5e happened to Thermal Expansion as well.

**Comment by davboecki** [comment]
fixed.
