### ISSUE TITLE
Item duplication using the request table

### ISSUE THREAD

**Issue by Turmfalke2** [RS485/LogisticsPipes#586]
hi,
I just stumbled over a bug that alloweds any item that can be crafted in a request table to be duplicated.
In my test setup I have the following mods:
 CodeChickenCore-1.7.10-1.0.4.35-universal.jar
 NotEnoughItems-1.7.10-1.0.4.83-universal.jar
 buildcraft-6.3.3.jar
 logisticspipes-0.8.3.95.jar

Steps to duplicate an iron bucket:
1. open the gui of a request table
2. clear the crafting grid in the top left corner
3. shiftclick the iron bucket recipe from nei into the table
4. place a single iron bucket in the table's inventory
5. double click the iron bucket

At this point it pulls the iron bucket from the output slot of the recipe and stacks it with the one already in the inventory. The table now displays that 3 iron ingots craft to nothing.
If you close and open the gui again the bucket is once again displayed in the output slot, but the duplication can't be repeated (you get fake/desync buckets) unless step 2 and 3 are repeated.

**Comment by SonOfTheStars** [comment]
Thats wierd,
Ill give it a reproduce
