### ISSUE TITLE
None of the item sinks work with pure breed forestry tree saplings

### ISSUE THREAD

**Issue by estebes** [RS485/LogisticsPipes#588]
I have a forestry multifarm and cant find a way to store my forestry saplings because they don't seem to be considered stackable by logistics pipes so they dont get extracted from the farm. not even a oredict item sink can do the job. is this a bug?

**Comment by SonOfTheStars** [comment]
the saplings are different in both Meta and NBT, LP needs a special case for them

**Comment by SonOfTheStars** [comment]
AH i know the problem!
The spalings you gave it to Store are Analysed! The ones that come from your Treefarm are un-analysed!
Those are in deed 2 Different Items ;)

**Comment by estebes** [comment]
Original post lacks information, my bad :D. It does work with chests but not with dsus, barrels, jabba barrels or te caches. I've searched a bit and found some issues that say that lp has nothing to deal with  both nbt and metadata except the cc based itemsink module but i dont really want to use cc. is there no fuzzy module or something?

**Comment by SonOfTheStars** [comment]
Fuzzy Upgrades for the Itemsink is on the Enhancement List ;)

**Comment by estebes** [comment]
here is a simple setup. http://i.imgur.com/AFKT0TQ.jpg
 both of the forks request saplings http://i.imgur.com/J2shNJJ.png http://i.imgur.com/JnwohFE.png but the one without the gold pipe doesnt input items into the cache. I just want to be able to attach a simple mk2 pipe with a provider and itemsink module that works with forestry saplings but im unable to do so

**Comment by SonOfTheStars** [comment]
Think that might be related to the CoFH Caches...
Does it behave the same with chests and/or JABBA Barrels?

**Comment by estebes** [comment]
Yes and with dsus too. With chests works fine but it defeats the purpose of what i want to do.

**Comment by SonOfTheStars** [comment]
And the Saplings are all analyzed? Not like, the original ones you put in being Analyzed and the new ones aren´t?

**Comment by estebes** [comment]
None of them are analyzed. They are pure breed and come directly from the tree farm. But it doesnt really matter if they are analyzed, the problem happens in both cases

**Comment by Sidorion** [comment]
I think, it's the same issue as the mana bean thing. The problem is the DSU-API as all the mentioned containers use it. I beg it won't work with storage drawers, either.

**Comment by estebes** [comment]
If that is really the problem where can i report it?

**Comment by Sidorion** [comment]
Well, as the clay pipes from BC work very well with the barrels (and therefore with the DSU-API) it seems that it's a LP issue. So here's the right spot to report.

**Comment by bziemons** [comment]
might be.. _links to #583_

**Comment by hron84** [comment]
@Bitterholz a side question: do you plan supporting forestry saplings/flowers in LP (as well as we have bee analyzer/terminus/etc pipes)?

**Comment by ab9rf** [comment]
It would be useful to have tree analogs to the beesink, bee analyzer, and drone terminus modules/pipes.  This would also resolve this issue.

**Comment by hron84** [comment]
Or just simply make the existing pipes work with the other two breedable stuffs (ok, then the "Bee" in their name is not so correct but... that is a minor issue).
