### ISSUE TITLE
Logistics Request Table doesn't check it's own inventory for crafting.

### ISSUE THREAD

**Issue by MikeLydeamore** [RS485/LogisticsPipes#589]
As can be seen here: http://puu.sh/g7xny/af042d5377.jpg, the logistics request table doesn't seem to check the items in it's own inventory before requesting for crafting. This causes a number of "false positives" (negatives?) on the items required.

I've tried using a provider pipe on the table, however this causes items to be pulled out of the table and put back in the system constantly.
This makes the logistics request table difficult to use for the "one-off" jobs, as every item must be put back into the system and sorted.

**Comment by SonOfTheStars** [comment]
For a quick and easy fix, you can have a MK1 Chassi under the Table, bearing an Extractor upgrade, mounbted with a BC gate, wich disables the pipe oon a RS-Signal.
If you then put a Pressureplate infront of the Table, your Items will stay in the Table as long as you stand infront of it.
As soon as you leave the table, your Items will get resorted.

Otherwhise, yooure right, the Table should really do that!

**Comment by davboecki** [comment]
It is intended, that the request by + doesn't respect the inventory.

**Comment by MikeLydeamore** [comment]
Can I ask why this is intended? It seems a little annoying considering the request table would be used for "one-off" crafting jobs.

Also, my workaround of using a provider pipe on the inventory of the table doesn't work (I expect by design).

**Comment by Silwing** [comment]
I too have found this behavior annoying, so +1 to the question of why this is intended behavior?

**Comment by davboecki** [comment]
If you hit the + 3 times to be able to craft 3 sets of your item, you will get into trouble if the inventory inside the table is checked every time the + is hit. If you want to request what is missing just remove those items from the crafting grid, hit the + (for it to request there doesn't have to be a valid receipe) and add them back info the crafting grid from the inv below.

**Comment by Silwing** [comment]
Removing the items from the crafting grid sounds like a reasonable way of doing it :) hadn't thought of that. Thanks for the explanation, the intention makes sense now.
