### ISSUE TITLE
Craft sign not rendering 2d items

### ISSUE THREAD

**Issue by megamanzteam** [RS485/LogisticsPipes#59]
Here is a screenshot from build 407 where the vanilla stick and buildcraft gear do not render on the sign, but 3d blocks are getting rendered.
![2d sprite sign](https://f.cloud.github.com/assets/4212359/435157/b552aea8-afa8-11e2-9db8-322d0d7c4186.png)

**Comment by davboecki** [comment]
Should be fixed now.
