### ISSUE TITLE
How to change font size?

### ISSUE THREAD

**Issue by dingziran** [RS485/LogisticsPipes#590]
There is B:useTerminalUseLargeFont=false In AE2 config file.
So how to make the font size smaller in request pipe gui?

**Comment by loordgek** [comment]
you cant

**Comment by dingziran** [comment]
@loordgek  Are you sure? I found that in somebody's video, his font is smaller than mine. He was using lp for 1.6.2 and I am using lp for 1.7.10. Is this the reason? Or in somewhere I can config it using Optifine or Betterfont or anything else?

**Comment by loordgek** [comment]
you can use the GUI scale option in minecraft it self 
do you have a link to that video?

**Comment by SonOfTheStars** [comment]
The fonts automatically go smaller when your stored numbers go above 3Digits.
Optifine is not a thing ppl should use for real...

**Comment by davboecki** [comment]
@Bitterholz That is AE2 and not LP. We simply reduce the numbers to display
