### ISSUE TITLE
Bee Analyzer Logistics Pipe does not work anymore after update to v101 (from 100)

### ISSUE THREAD

**Issue by Ioandar** [RS485/LogisticsPipes#591]
I updated LP from 100 to 101 and after that the Bee Analyzer Logistics Pipe did not sink any unanalyzed Bees into Forestry Analyzer anymore

Reverting LP back to 100 solved that and it worked as expected again...

logisticspipes-0.8.3.101
forestry_1.7.10-3.5.0.471-unstable
forge-1.7.10-10.13.2.1291

**Comment by SonOfTheStars** [comment]
VERY strange!
None of the actual module code was changed in ANY way!
It did work for me...
Im on Frge build 1230, maybe thats related...

**Comment by Ioandar** [comment]
okay, I will go back to good old 1230 and report...

**Comment by Ioandar** [comment]
back with some cross-testing info. Because I had updated other mods too (CofH, Pneumatic,...) I wanted to make sure those updates did not interfere with the LP update. Happy to have daily backups from my WHS :)

Reverted back to original setup (forge1230, LP100, forestry471)
-> all works fine (BeeSinkModule, BeeAnalyzerPipe, ApiaryRefillerModule)

updated LP to 101 (forge1230, LP101, forestry471)
-> NONE worked (BeeSinkModule, BeeAnalyzerPipe, ApiaryRefillerModule)

updated LP to 102 (forge1230, LP102, forestry471)
-> NONE worked (BeeSinkModule, BeeAnalyzerPipe, ApiaryRefillerModule)

I am using java 1.7 normaly because it is more agile on my win7/64 but tried with java1.8 just to make sure it is not related to that (jre1.8.0u25, forge1230, LP102, forestry471)
-> NONE worked (BeeSinkModule, BeeAnalyzerPipe, ApiaryRefillerModule)

back to original setup (jre1.7u67-64bit, forge1230, LP100, forestry471)
-> all works fine (BeeSinkModule, BeeAnalyzerPipe, ApiaryRefillerModule)

Hmm, currently out of ideas... Since it works on your system it has to be something on my side. 

I will try new LP with old stable forestry 3.4.0.7 next and maybe a different BC build (I am using 6.3.6 atm). Any hints highly welcome :)

**Comment by Ioandar** [comment]
now with new LP and BC (jre1.7u67-64bit, forge1230, LP102, BC6.4.0, forestry471)

-> normal BC/LP operations work flawlessly
-> NONE worked (BeeSinkModule, BeeAnalyzerPipe, ApiaryRefillerModule)

I just saw that BeeSinkModule, BeeAnalyzerPipe and ApiaryRefillerModule have no recipe in NEI anymore in this setup. 

I DO see the Items in NEI but when I click the item in NEI recipe mode or request the recipe with 'R' while hovering mousepointer over that Item then they do not show up. All other Items are showing their recipes as expected

Maybe that is related?  With BC6.3.6, LP100, forestry471 I can see them in NEI and their recipes are shown (showing fluid.honey for ApiaryRefillerModule in Carpenter but thats another story)

**Comment by SonOfTheStars** [comment]
Anything above BC 6.3.2 isnt really tested for the current LP Versions. It might be the cause of your problems. 
As for Sinks not working, there was nothing done in Build 101 that touched anything else than a missing if clause regarding recipes for Forestry. If you could Check the LP config and set Mandatory Carpenter Recipies to true, it should defenitly show recipes.
As for carpenter recipes, it could be your NEI Integrations not working correctly, could you try to use the carpenter and see if the recipes are there after all?

**Comment by SonOfTheStars** [comment]
Its defenitly super wierd. Im sniffing a problem with outdated proxy code for forestry.
Ill go through forestrys changelog and try to figure out if there where changes made that are related to this.

**Comment by Ioandar** [comment]
ty, this is very strange indeed but I am sure we will corner it in :)

I will go back to BC 6.3.2 and test it with stable forestry and LP101 and report back if recipes actualy work even if they are not shown in NEI.

I will also check/set the mandatory carpenter recipes to true in config

I will report back shortly :)

I quickly checked config first... It was already set to 'true'

->Whether or not the Carpenter is required to craft Forestry related pipes/modules.
->B:mandatoryCarpenterRecipes=true

recipes not shown in 101/102 I will now degrade to BC6.3.2 and check if those carpenter recipes work even when recipe is not shown

**Comment by SonOfTheStars** [comment]
found the actual problem behind the actual issue with fluid.honey, since forestries honey is now tagged “for.honey“.
Fixing that soon.

**Comment by Ioandar** [comment]
yay! 3cheers to you!

**Comment by davboecki** [comment]
I suspect that the recipe changes somehow crash the ForestryProxy causing it ti be disabled at startup.
Look into your logs and look for something like "Disabled ForestryProxy. cause was an Exception" and past the stacktrace trough pastebin here.

**Comment by Ioandar** [comment]
yes, ForestryProxy was disabled by exception. I could not pastebin the full file but here is the part (it is 5.8mb and pastebin said it is too big)

http://pastebin.com/miMCce4J

**Comment by davboecki** [comment]
@Bitterholz 

```
java.lang.NullPointerException
at net.minecraft.item.crafting.CraftingManager.func_92103_a(CraftingManager.java:230)
at logisticspipes.proxy.forestry.ForestryProxy.addCraftingRecipes(ForestryProxy.java:452)
```

**Comment by SonOfTheStars** [comment]
@davboecki 
Right on!
Seems like i derped somewhere
Plus going to fix the fluid.honey problem

**Comment by SonOfTheStars** [comment]
@davboecki I cant seem to find an issue that would cause an NPE, plus my DEV-Env is broken again, so i cant really test
Would like to talk to you

**Comment by Ioandar** [comment]
checked the new version against my install

updated LP to 103 (forge1291, LP103, forestry471)
-> all works fine (BeeSinkModule, BeeAnalyzerPipe, ApiaryRefillerModule)
-> crafting ApiaryRefillerModule in HoneyProvider worked also
-> all recipes are shown in NEI with correct fluid (honey)

checked LP103 with new TE in new world
-> all loads fine

checked LP103 for my playWorld 
-> crash -> http://pastebin.com/E2BhsJTF

I have an RF Power Provider in that world. It provides RF-Power to various machines in my LP network.

I started a new world again and could not find the RF Power Provider in NEI... Only the recipe for the EU Power Provider is shown. The recipes for the RF modules (that go on the LP Pipe that is connected to the machine) are still shown in NEI. Only the RF Provider Block is missing...

edit: I posted that over in #595 to have the TE update related things all in 1 place and we can close this one...

**Comment by SonOfTheStars** [comment]
Have you tested the Configurable option?
Would like to see no NPEs

**Comment by Ioandar** [comment]
@Bitterholz

I just checked with same setup (forge1291, LP103, bc6.4, forestry471)  and only change config-option to 'false'

> Whether or not the Carpenter is required to craft Forestry related pipes/modules.
> B:mandatoryCarpenterRecipes=false

NPE, ForestryProxy was disabled by exception...

http://pastebin.com/sXCGHVyz

I will now revert config option and see if it works again to ensure it is only the option setting and nothing else

edit: after reverting config option and restart that NPE is gone. Only exception that remains for LP is the one for the TE that might be the reason for losing the RF Provider Block...

http://pastebin.com/fRJV922y

**Comment by davboecki** [comment]
fixed
