### ISSUE TITLE
Errow with latest CoFH mods

### ISSUE THREAD

**Issue by Xen1290** [RS485/LogisticsPipes#592]
With latest version of CoFH mods out today, there is a problem with LogisticPipes, here is the log
http://pastebin.com/cW8Dr8iK

**Comment by davboecki** [comment]
What Forge version are you using? Please update to the lastest forge build (1291)
Duplicate of: https://github.com/RS485/LogisticsPipes/issues/584.

**Comment by Xen1290** [comment]
Forge 1291 @davboecki
