### ISSUE TITLE
crafting module recipe

### ISSUE THREAD

**Issue by DrummerMC** [RS485/LogisticsPipes#594]
the crafting module has no recipe

**Comment by SonOfTheStars** [comment]
These modules are kind of untested and Beta-Content. If you want, grab MIneTweaker and add a recipe ;)
I also have a Modified version of LP handy wich adds recipes to them ;)

**Comment by bziemons** [comment]
Duplicate of https://github.com/RS485/LogisticsPipes/issues/477 (yeah.. that was a while ago, sorry)

**Comment by hron84** [comment]
@bitterholz could you provide your recipes somewhere to users who wants to do beta testing?

**Comment by SonOfTheStars** [comment]
you could allways cheat them in ;)
But if you relly want I could give you that Private Version Of LP when @davboecki  is OK with that.
But beware, it got some very new stuff in it wich im developing

**Comment by davboecki** [comment]
As LP is under MMPL I'm totaly cool with it, and when I have some time I will add receipes for them into the 0.9 branch and make beta builds available for people to test.

**Comment by SonOfTheStars** [comment]
Allright!

**Comment by SonOfTheStars** [comment]
I need to sort out a few Bugs but ill put it op soon @hron84

**Comment by hron84** [comment]
Cool, thanks
