### ISSUE TITLE
logisticpipes API for computercraft

### ISSUE THREAD

**Issue by MrTatio** [RS485/LogisticsPipes#597]
For Version 0.8.3.103 
the API doesn't work. I get a Java exeption thrown when i use this API. Pleas fix this api

**Comment by davboecki** [comment]
The most likey thing is, that you provide the wrong arguments to the method. In previous versions of CC it would just print the message of the java exception and not only say that there was a Java exception. That's the reason LP throws Java Exceptions when you use the wrong amount/type of arguments.

**Comment by MrTatio** [comment]
please Update the LP API on the wiki. Or can you gave me the way to use a Computer and a requestpipe, also an example on the item stone

**Comment by MrTatio** [comment]
please Update the LP API on the wiki. Or can you gave me the way to use a Computer and a requestpipe, also an example on the item stone

**Comment by MrTatio** [comment]
Sry for two Same comments

**Comment by MrTatio** [comment]
With computercraft 1.65 i can use this API but i have this thrown and with computercraft 1.72 this API doesn't work

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/issues/585

Will look at 1.72 when I get the time.

**Comment by davboecki** [comment]
Will look at 1.72 when I get the time.

**Comment by davboecki** [comment]
LP works correctly with CC 1.7. But as a result no longer with 1.6

**Comment by MrTatio** [comment]
please gave me an example for makeRequest with the material "Stone"

**Comment by MrTatio** [comment]
i need the ItemIdentefiry... please help me

**Comment by davboecki** [comment]
look at #585 for information on how to use the CC API.
