### ISSUE TITLE
[LP_0.9][BUG]Client Crash on Module Insertion

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#598]
Currently, the LP 0.9 Client crashes once you insert any Modules into a Chassi Pipe.

Log:
http://pastebin.com/c2CvfG7y

This needs urent Fixing! It happens Randomly, mostly with Value 8, sometimes 4.

Breaking addition was part of f0b43dbc7fc2c214f9c5a41dd28437f31845f232

**Comment by SonOfTheStars** [comment]
Might have allready found the issue, if its really that...
If so I blame @davboecki for coding shinanigans :D

**Comment by davboecki** [comment]
You mean the missing if statement inside the ensureCapacety function?

**Comment by SonOfTheStars** [comment]
Didnt think about that actually,
I went more into the direction of Array.length()-1

**Comment by SonOfTheStars** [comment]
Closed: a89e27c6284984eebfceea3e425eb3724c6449c1
