### ISSUE TITLE
LP Build 108 / Facades Block Connections

### ISSUE THREAD

**Issue by Waremaster** [RS485/LogisticsPipes#603]
I remember in 1.6.4 that facades were used to tidy up open walls with pipes, but would still allow  connections to chests, inventories, and machines.

I am now seeing the facades are blocking those connections to chests, machines, and inventories in 1.7.10. So how are we supposed to tidy up our LP systems?

**Comment by Silwing** [comment]
I think Buildcraft changed facades so you now have to create hollow facades to allow pipes to go through them. They should be alongside the normal facades in the assembly table.
