### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Tyrantin** [RS485/LogisticsPipes#605]
https://www.dropbox.com/s/nno275rhpg9miqj/crash-2015-03-06_16.12.20-client.txt?dl=0

**Comment by bziemons** [comment]
The BC Version '6.3.3' is not supported by this LP version. Please use '6.4.0'

**Comment by Tyrantin** [comment]
not that. just changed back to an older version of Optifine and it is working now. must have conflict with the HD ultra B5
