### ISSUE TITLE
Another crash after update of LC

### ISSUE THREAD

**Issue by Tyrantin** [RS485/LogisticsPipes#606]
https://www.dropbox.com/s/bsexbc941t8h80n/crash-2015-03-06_16.34.19-client.txt?dl=0

**Comment by davboecki** [comment]
logisticspipes.proxy.VersionNotSupportedException: The BC Version '6.3.3' is not supported by this LP version. Please use '6.4.0'

**Comment by Tyrantin** [comment]
Do you have a link because I'm not finding it

**Comment by Tyrantin** [comment]
NVM found it
