### ISSUE TITLE
Question Don't know where to post it.

### ISSUE THREAD

**Issue by Tyrantin** [RS485/LogisticsPipes#607]
Does LP work with Better barrels? If so, is their a Youtube video? and if so can you provide me with a link?

**Comment by SonOfTheStars** [comment]
Better Barrels? Like JABBA or what?

**Comment by SonOfTheStars** [comment]
Jes they do work, its simply hook up your pipes on any side and LP will treat them as a valid storage device.
You can hook up any Pipe, though for best results, I recommend you use the MK2 Chassie Pipe, with a Provider Module set to “Leave one item per Type“ and a Polymorphic Itemsink. Boom, drop an item into the Barrel and your LP-Network will use it as storage device for that Item ;)

**Comment by Tyrantin** [comment]
Ok, tried it with the MK3 for an extra spot and it would not deposited the cabblestone into the barrel. Any suggestions? And yes the jabba barrels! 😁

**Comment by SonOfTheStars** [comment]
You might wanna show a picture of your setup, plus if there are other valid places for cobble on the same priority, it will head to the closest first.
You can try forcing the Type with an normal Itemsink.

By the way, wich milestone you use? 0.8 or 0.9

**Comment by davboecki** [comment]
Make sure you insert items from the top.

**Comment by hron84** [comment]
@davboecki as i know Better Barrels (read: JABBA barrels) can accept items any side b/c they use DSU API. only FZ barrels are side-specific.

**Comment by davboecki** [comment]
Even DSU's don't accept from any side only if you configure them to. And I'm sure that you need a sneaky upgarde if you want to place the pipe anywhere other than the top.

**Comment by hron84** [comment]
I tried w/ BC clay pipes, and they can insert items into any side of the JABBA barrels. I can imagine this is not applies for LP pipes however I think it's definitelly an LP issue/feature and not a barrel restriction. I never heard clay pipes should be sneaky.

Same experience with EIO conduits too - and EIO conduits definitelly respect side restrictions if there is any.

Also, JABBA barrels aren't providing a possibility to configure their accepting side.

**Comment by davboecki** [comment]
I just checked and you are correct LP doesn't have this restriction. At least not inside the code.

**Comment by bziemons** [comment]
We used JABBA barrels on our server and inserted/pulled into/from the back @davboecki
