### ISSUE TITLE
Soldering Station doesn't respect power config

### ISSUE THREAD

**Issue by 61352151511** [RS485/LogisticsPipes#608]
It seems I can't use the soldering station when I have power usage config disabled. I checked through the code and didn't see anything about it checking the config to see if it should take power or not, it just attempts to

**Comment by davboecki** [comment]
Have you tried placing it next to a basic pipe? The pipe should know that it doesn't need to consume power iirc.

**Comment by 61352151511** [comment]
No I haven't tried that, that will probably work, however maybe it should skip the check for pipes if the config is disabled?

**Comment by SonOfTheStars** [comment]
we could also make it Consume Coal when its noot set to draw LP-Power

**Comment by Tyrantin** [comment]
Or xp

**Comment by hron84** [comment]
Or kill kittens.
