### ISSUE TITLE
Crash on entering Render Distance

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#615]
http://pastebin.com/iYyPkffH

This somehow happens when your Client gets a LP-Pipe into render distance, and a lot of Items currently traverse through it.

Its really a bummer!

**Comment by davboecki** [comment]
Still needs to be looked at why the item can be corrupt on the client side.

**Comment by SonOfTheStars** [comment]
Seems lo be a fail on Chunkload, but the fix has pretty much prevented it, no occurances so far after the Hotfix!

**Comment by SonOfTheStars** [comment]
I can confirm it doesnt happen anymore in the new versions!
