### ISSUE TITLE
Crash when attaching pipe to AE2 interface

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#616]
Hi! I wanted today to use some LP pipes to access my items in the AE system. The problem is that when I place a request pipe or chassis pipe next to a ME Interface the game crashes. In an older world(made with AE rv2 beta 7 and LP build 90) this STILL works fine.

When I DID manage to place a chassis with a provider module next to the second interface, then place a request pipe next to it, no items show up. Note: both of the interfaces have patterns for autocrafting. 

P.S: The pipes WERE powered with a logistics power junction.

Crash: http://pastebin.com/D583R1VS
- From now my console gets spammed wth "The world may have been leaked! Seen n times".

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/issues/612 https://github.com/RS485/LogisticsPipes/issues/600 and probably more.
