### ISSUE TITLE
Feature: inverted sink

### ISSUE THREAD

**Issue by alexvins** [RS485/LogisticsPipes#624]
Add new pipe / module with:
1) priority same as regular itemsink
2) passive route
3) (optional) blacklist configuration
4) accept item than do not have _configured_ destination. (Does not accept items that has configured destination that can not accept item, f.e. full chest)

**Comment by SonOfTheStars** [comment]
How about using a Itemsink for Basic route, paired with a Quicksort?
Plus, if you want stuff not extracted when there is no space for it, use Quicksorts instead of Extractors!

**Comment by alexvins** [comment]
In case of quicksort I want to have destination A for some particular items and B for all _other_ items. (B cant be basic sink or terminus or default route.)

**Comment by bziemons** [comment]
I do not really understand how point 2 and 4 plays together and what they mean exactly.
Could you provide a use-case of your new pipe/module?

**Comment by alexvins** [comment]
Use case example:
1) destination A - chest with some ores
2) destination B - TE pulverizer with by-product augment
3) destination C - TE pulverizer with speed augment
I want some particular ore, f.e. ferrous to go to B and all others to go to C.

**Comment by AartBluestoke** [comment]
I believe the problem here is that the default sink across everything, even
those things which have other destinations specifically interested in them.

This could be easy to implement, default sink, but don't sink anything with
a specifically interested sink.

**Comment by hron84** [comment]
@alexvins a bit specific but working solution: put oredictionary modules onto mk1 chassis pipe on B and C pulverizer and configure the specific ores to it. It simply directs affected ores into the right pulverizer.

**Comment by alexvins** [comment]
@hron84, i`m using smth like this already.

**Comment by hron84** [comment]
@alexvins as I think there is similar solutions for possible problems. I do not think we need additional pipe for these tasks. LP system - as I saw - tries to do everything to prevent dropping items from BC pipes (checks inventory slots, routes items back correctly if there is no enough room) so only some very complex scenarios can make sense for making a new pipe for these problems. I did not saw similar solution in other pipe systems as well.

**Comment by bziemons** [comment]
@alexvins I always used exactly what @hron84 described: Quite a few item sinks which have all possible ores as input on them.

I have thought about this and yes it is currently possible to do this without being complicated. You need a firewall pipe though. I have made (and tested) the following setup:
![ferrous-ore-setup](https://cloud.githubusercontent.com/assets/1096713/7026901/ed2240c2-dd4c-11e4-86a0-f113d8874722.png)

With the following firewall pipe configuration:
![firewall-configuration](https://cloud.githubusercontent.com/assets/1096713/7026914/f8b13dc6-dd4c-11e4-85b6-36f25cc95dfa.png)

The setup is easily stackable with several item sinks and several pulverizers, there is just one limitation: The default item sink to the upper chest needs to have the longest distant from all other default item sinks for the ores. The ores will then bounce back and forth between pulverizers, but that shouldn't be a big problem, as Logistics Pipes' pipes (heh) won't explode. Watch out with BuildCraft pipes though (if they still do explode [???]).

I hope this helps.

**Comment by davboecki** [comment]
`Watch out with BuildCraft pipes though (if they still do explode [???]).`
No they don't explode trough LP items. They still do if you use them for normal item transport.

**Comment by bziemons** [comment]
Thanks for clarifying :)
