### ISSUE TITLE
[0.9]Idle Improvements

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#625]
The idle improvements seem to work, BUT
As soon as you issue and active request, the server starts running ~8000Ticks behind.
Up to the point where it Kicks you due to Timeout.
Task gets not issued, everything just completely lags out!

**Comment by davboecki** [comment]
Do you know how to use visualVM? Could you create a sampling of the minecraft server?

**Comment by SonOfTheStars** [comment]
nope never heared of that until now

**Comment by davboecki** [comment]
@Bitterholz When you have time contact me in irc.

**Comment by SonOfTheStars** [comment]
Next Monday will probably bee good @davboecki

**Comment by SonOfTheStars** [comment]
@davboecki could it be, that LP is causing alot of Chunk updates even if its in Idle mode?
(Speaking of pre-Build#80)

**Comment by davboecki** [comment]
That should actually be improved as well with the idle improvments. The only thing I can think of is that the crafting improvments made in a prev. commit somehow causes problems. [Which it shouldn't]

**Comment by SonOfTheStars** [comment]
it seems to, because as soon as you issue a Crafting uperation in Build 80 you get lagged the heck out

**Comment by davboecki** [comment]
So with build 79 it's fine?

**Comment by SonOfTheStars** [comment]
Jes, im testing with build 84 right now on SSP...
Still afraid of putting stuff on the server. We still need to meet for the Testing

**Comment by SonOfTheStars** [comment]
Build 84 seems more Stable. Still experiencing occasinal lagspikes when issuing a Craft or active request, especially laggy when adding/removing something from the network aka pipes/recipes/chests

**Comment by davboecki** [comment]
@Bitterholz Do you have time this afternoon or within the next few days?

**Comment by SonOfTheStars** [comment]
Sure
If you want to we can doo that VisualVM right now

**Comment by davboecki** [comment]
@Bitterholz Contact me on IRC when you can.

**Comment by bziemons** [comment]
Ah and stop using f words in public space @Bitterholz

**Comment by davboecki** [comment]
I couldn't find any significant Performance issues caused by LP while testing with your backup.
