### ISSUE TITLE
Logistics Pipes v0.9 issue with Thermal Dynamics

### ISSUE THREAD

**Issue by jznomoney** [RS485/LogisticsPipes#627]
I put a bug on thermal dynamics here
https://github.com/CoFH/Feedback/issues/350
They referred me to you here is a copy of the crash log

http://pastebin.com/dVem1XZi

**Comment by SonOfTheStars** [comment]
lel thats a odd one

**Comment by davboecki** [comment]
Does it crash if you remove LP from your mods?

**Comment by jznomoney** [comment]
just close this I think it was an issue I created myself when I update my mods I wanted to start a new map and I think it tried to use an old map instead.
