### ISSUE TITLE
Dupe bugs caused by request table

### ISSUE THREAD

**Issue by Omega-Haxors** [RS485/LogisticsPipes#628]
While playing with Logistics Pipes, I've noticed a few duplication bugs with both tesseracts and inventorytweaks. I'm currently running on an older version so take this with a grain of salt.

If you place a tesseract directly onto a logistics request table, and then make a request in the table, it will transfer the item directly into the table and then drop the same item nearby. This is probably caused because tesseracts will transfer items directly into adjacent inventories, but logistics pipes still sent the item anyway.

~~~ Disregard below ~~~

You can also use inventorytweaks to pull the output slot of the crafting area in the table. If you take the result, and then click it in a certain way (I find double clicking works the best) all of the items will go into your mouse slot. Normally the server will catch this and delete the fake item, but in some cases it gets tricked and all you have to do to make it a real item is drop the entire item stack into the sort box and have it go into the network.

**Comment by Omega-Haxors** [comment]
Some searching through the closed issues has proven that the second issue has already been sorted out (hopefully) so it's just a matter of getting things updated.

I used GitHub's search feature and didn't see anything about it so I assumed it wasn't reported yet, but 3 seconds of looking through closed reports, it was obvious that it was already taken care of.

As it stands, i'm sure the first issue is still relevant, though.

**Comment by bziemons** [comment]
I have tried this and quite the opposite happens. The item wanders into the tesseract, because it seems to have a destination, but the Request Table won't accept it nor throw anything anywhere. So the item is stuck in the world between the tesseracts.
