### ISSUE TITLE
AE2 does not interface with LP

### ISSUE THREAD

**Issue by Omega-Haxors** [RS485/LogisticsPipes#629]
For some reason, no matter what I do, I cannot get AE to connect to LP properly. The only feature that works is getting LP to read and request from AE's cells like an inventory.

The power sharing, being able to read LP's network from AE's terminal, and extending an LP network through an AE system is completely non-functional.

I am currently running LP 0.8.3.100 and AE2 rv2-beta-8 so take this with a grain of salt.

**Comment by Omega-Haxors** [comment]
Turns out this is a long-standing bug. No point reporting it since it's probably been reported a million times.

**Comment by bziemons** [comment]
Yeah and it's not even on our side ;) It is still a feature request on AE2.
