### ISSUE TITLE
satellite pipe add material to the output

### ISSUE THREAD

**Issue by SwissPegasus** [RS485/LogisticsPipes#63]
Hy there

Forge: 7.7.1.660
Buildcraft 3.5.0
LogisticsPipes-MC1.5.1-0.7.2.dev.405
iron chest: 5.2.4 build 372

With this version the satellite pipe add the material in a furnace to the wrong place, goes to the output slot instead of the burn material slot.

Tested with several materials, iron --> iron ingot, sand --> glas, cobblestone --> stone

Feels like a general bug.

btw i try to use the newest build, but not work,  minecraft got errors on startup.

**Comment by davboecki** [comment]
should be fixed.
