### ISSUE TITLE
System Connector Pipe sometimes gets stuck

### ISSUE THREAD

**Issue by Omega-Haxors** [RS485/LogisticsPipes#630]
When transporting a large amount of items through a system connector pipe, using an ender chest as a medium, sometimes the item stack will change a little bit due to minecraft's stacking.

The issue arises from the fact that the pipe will only accept the itemstack or one of greater value that the request was made for, so modifying the existing stacks it will cause the system to freeze up. For example, if a request of 10 cobblestone was made, and 100 were inside the inventory, it would take the 10 from the first stack. The next request of 64 would see the first slot (containing 54 cobble) and not even bother to check the rest of the chest to see that it's available.

This is most common when many requests are going in and out through the pipe. The easiest fix is to recirculate the contents of the inventory, forcing them into full stacks, but I would prefer the bug be fixed properly rather than having to rely on work-arounds.

**Comment by davboecki** [comment]
This should be covered trough the rewrite of the extraction code in the 0.9 branch to support Special inventorys like AE.

**Comment by Omega-Haxors** [comment]
Sweet, thanks.
