### ISSUE TITLE
Inventory Connector Pipes through AE2 bugged

### ISSUE THREAD

**Issue by Omega-Haxors** [RS485/LogisticsPipes#632]
Using two connnector pipes to connect one side of an ME system to another will display as normally, but any requests you make on one side will go into the ME system on the other end and never come to the requested location. It gets stuck along the way.

The strangest thing is, it will show as if you have double of the item you requested. Pulling the item out of the ME system and putting it back in will fix this, and attempting to request any fake items will result in a "not enough items" failure.

**Comment by davboecki** [comment]
what branch are you on ?

**Comment by Omega-Haxors** [comment]
I am running LP 0.8.3.100 which is a little outdated, but due to having to update a whole lot of other mods, is not really within the realm of possibility with the current setup to update.

Hope that helps.

**Comment by davboecki** [comment]
Like I saied in https://github.com/RS485/LogisticsPipes/issues/630 the InvSysCon got some work done inside the 0.9 branch so this should be covered by that.
