### ISSUE TITLE
Crashing when trying to launch server: Ticking block entity

### ISSUE THREAD

**Issue by cgoeller919** [RS485/LogisticsPipes#634]
I've been working on a custom server for some friends and there was a crash with a description of Ticking Block Entity. I saw issue #481 with a similar situation, but the crash reports are different. 

http://pastebin.com/mqif3UZq

Modlist:
https://docs.google.com/spreadsheets/d/1lonFgKdmLrsNnNzGt9ROlvgwGkVfYCBjpCfr49qW6W4/edit?usp=sharing

**Comment by davboecki** [comment]
Update and it should be fixed.
