### ISSUE TITLE
BC Robot improvements

### ISSUE THREAD

**Issue by davboecki** [RS485/LogisticsPipes#636]
- [x] Make robot's use the BC zones instead of a fixed radius to determine their workarea.
- [ ] Add gates to controll the robot
  - [ ] Allow to disable AutoCharging robots
  - [ ] Allow to disable routing connection
- [ ] Add support for the filter gate action.
- [x] Make the radius a config option.
- [ ] Make Charging through LP a config option.
- [ ] Balance Power coast for the LP Boards.

**Comment by asiekierka** [comment]
- [x] Refactor the item insertion/extraction process into a separate AI with a different energy cost to match BC's robot energy usage mechanics

(reserved - might edit later)
