### ISSUE TITLE
Feature: Easier satellite pipe configuration

### ISSUE THREAD

**Issue by TheLoneWolfling** [RS485/LogisticsPipes#639]
Currently when you reach a moderately sized network, configuring satellite pipes becomes a... pain, shall I say? Clicking 100+ times for each crafting pipe isn't exactly ideal. (Its gotten to the point where I have an autoclicker that clicks 100 times to set a crafting pipe to the last satellite pipe in the system.)

(If you are wondering about the 100+ clicks part, that is actually an _under_estimate: I am currently "only" at ID 35 or so, but many of the crafting pipes I am adding require advanced satellite upgrades as they have 4+ items that need to go to a satellite pipe, and each one of the items needs to be configured individually. (35+)*(4+), for each pipe, adds up. Assembly tables are a pain.) 

So, a couple of ideas, any/all of which would help:
1. An item that, when clicked on a satellite pipe, remembers the pipes ID. Then when clicked on a crafting pipe sets the crafting pipe to that satellite pipes ID. Bonus if it sets the satellite pipes ID if it isn't set already. I do not know how to make this work with the advanced satellite upgrade, however. Perhaps just setting all of the "None" slots to that ID. On a related note: An easy way to set one of the slots in the advanced satellite upgrade to "None" would be great.
   - Perhaps shoehorn this into BCs "gate copier" item somehow? Or the pipe controller?
2. Changing satellite pipe IDs by 10/100/etc by using shift / etc, like with setting numbers of items in the crafting pipe interface.
3. Making the satellite pipe interface wrap, in that if you are at the lowest ID and you hit "down" it will go to the highest ID in the system. (and vice versa?)
4. Having a way to change all of the satellite pipe IDs simultaneously when you have an advanced satellite upgrade on a crafting pipe. Perhaps just a 10th set of up/down buttons that changes them all up/down.

(If any/all of these are already implemented, perhaps a note in the wiki that they are would be good.)

**Comment by AartBluestoke** [comment]
If you go backwards to -1, it selects the physically closest satellite
(unless that code has changed since it was written)

**Comment by TheLoneWolfling** [comment]
That doesn't seem to work for me.

Looking at [it](https://github.com/RS485/LogisticsPipes/blob/mc17/common/logisticspipes/modules/ModuleCrafter.java#L532), it seems the code you mention isn't there - and hitting previous when it's at "off" does nothing on my main save. Not surprising.

There's also the problem that that wouldn't actually help me in this case (the way it's laid out, (almost) none of the crafting pipes are closest to their satellite pipe), but that's another matter.

**Comment by AnimeniacYuuto** [comment]
Perhaps making a pop-up text dialogue for setting the satellite number? (also could allow the naming of satellite pipes as opposed to remembering the number similar to WR-CBE)

**Comment by Xuerian** [comment]
Is it impossible to switch to named satellites? Or provide a popup list/menu of linked satellites ordered by distance? Ideally displaying the block name it is attached to.

**Comment by hron84** [comment]
Or make a tesserract-like system: numeric addresses with named aliases.

**Comment by Sarioah** [comment]
Scrolling the mouse while hovering over one of the arrows or maybe the number itself could rapidly change the number, much like it already does in the request table for request size.

+/- 1/10/100 buttons aren't much use, since we need something consistent across all satellite interactions like the crafting cards, advanced satellite and fluid crafting guis, and those are cramped enough as it is.

**Comment by bziemons** [comment]
Since satellite pipes are named now, I close this.
