### ISSUE TITLE
gate trigger icons not rendering

### ISSUE THREAD

**Issue by AartBluestoke** [RS485/LogisticsPipes#64]
latest dev, LP pipe triggers (eg: need more power on the logistics junction) do not render, even though they work.
![no_acton_icon](https://f.cloud.github.com/assets/1892829/438473/a2a51f16-b0ca-11e2-8f00-c5c871463dd8.png)
.

**Comment by ddos666TB** [comment]
it was working :D

**Comment by davboecki** [comment]
Fixed. That was just an id mixup.
