### ISSUE TITLE
Crash with newest forge

### ISSUE THREAD

**Issue by Syer10** [RS485/LogisticsPipes#645]
In the newest forge there was a breaking change that removed FluidID's or something like that. Its not a major issue but you should update to the newest.
http://pastebin.com/v3Chqd9E

**Comment by bziemons** [comment]
I suggest using the recommended build: 10.13.2.1291
We will see if that change is an actual change or not. Right now it's only breaking compatibility with many mods and it's the newest build, so do not expect us to move there instantly. With our builds we always try to keep up with the recommended builds of Forge, which is what everyone is advised to use.

**Comment by SonOfTheStars** [comment]
Even never builds fix it allready

**Comment by SonOfTheStars** [comment]
The issue was on forges side. They fixed it and LP now has no Problemo

**Comment by bziemons** [comment]
So "We will see if that change is an actual change or not." has come true ;)
