### ISSUE TITLE
Creative tab ItemSink module

### ISSUE THREAD

**Issue by Xuerian** [RS485/LogisticsPipes#647]
A functional alternative or compliment to the Mod Based ItemSink module, a creative tab version would operate as named, allowing a more intent-focused filter instead of bluntly by mod.

I'd like to say "It should be easy", but that usually just means it isn't.

**Comment by SonOfTheStars** [comment]
Great suggestion! I +1 This!

Keep all the BC Facades at bay XD

**Comment by hron84** [comment]
+1 this. Sometimes the mod-based filtering is not specific enough.

**Comment by davboecki** [comment]
We will need to check if the creative tabs exist on servers as well. Otherwise we will run into the same problem as with the name based filtering.

**Comment by SonOfTheStars** [comment]
@davboecki I think technically they SHOULD exist....Ive not seen a mod that restricts its Tabs specificly to a Side so far...

I might be completely wrong though XD

**Comment by davboecki** [comment]
This is not possible because
`@SideOnly(Side.CLIENT)
    public CreativeTabs getCreativeTab()
    {
        return this.tabToDisplayOn;
    }
`
. It's client side only. And we need it to be accasable on the server as well.

**Comment by davboecki** [comment]
Ok scratch that. I might have found a way around that. Trough it will only work on the main creative tab the item is on and not on all of them.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/f0c2f6e85b8f12ba5ca149626407414fb634914a
