### ISSUE TITLE
Oredictionary Item Sink enhancements

### ISSUE THREAD

**Issue by hron84** [RS485/LogisticsPipes#649]
Currently I ran into the cap of the list in the mentioned module. Sadly much more ore exists in the world than I can set up in the module. Even if I technically can work it around (put two module to a mk2 pipe or make a double chest with two pipe) it would be better if the list could be hold more list items - and possible become scrollable. 

My second suggestion would be allow manually typing oredic filters to the GUI to not require an actual item to program it up. Currently when I start the game I start to collect ore samples to the future programming because there is no other way to program it up without the actual ore.

**Comment by davboecki** [comment]
The second suggestion sounds reasonable but the first thing is intended and will not change. It is designed to require an higher tear chassis and an additional module.

**Comment by hron84** [comment]
@davboecki OK, I accept the first it is intended.

**Comment by SonOfTheStars** [comment]
Jeah i would love to be able to just Type the oreDict name into the Module!
+1

**Comment by Xuerian** [comment]
The ability to use partial names would really be helpful when you add the second thing, however judging by your opinion of the first, it may warrant an upgraded module.

**Comment by bziemons** [comment]
This issue is actually a duplicate of #231 then.
