### ISSUE TITLE
java.lang.RuntimeException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by loordgek** [RS485/LogisticsPipes#651]
http://paste.ee/p/IHH4f
forge 1365

**Comment by hron84** [comment]
@loordgek could you please provide more details if it is possible? What did you do, what is your setup and what fluid caused this issue?

**Comment by SonOfTheStars** [comment]
Use Forge  Builds 1369+
In there, your Problem gets adressed.

**Comment by bziemons** [comment]
I would like to stop new issues coming in from the newest unstable Forge builds, especially when the issue opener is not responding to questions..
So please no issues about crashes or problems with the newest Forge.
