### ISSUE TITLE
Crash after updating forge version.

### ISSUE THREAD

**Issue by quedral** [RS485/LogisticsPipes#655]
Everything works fine in Forge 1291 however updating to 1355+ (as newest COFH requires) causes this crash when starting.

http://pastebin.com/Tsk6daDv

Hope it helps.

**Comment by SonOfTheStars** [comment]
Use at least build 1358!
in there is a fix for  your issue.
/close

**Comment by quedral** [comment]
Yeah that worked. Thanks a bunch
