### ISSUE TITLE
Server Crash on Gate Placement

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#656]
As soon as you place a Gate on a LP Pipe, The Server instantly Crashes and wont start up anymore!

Urgent fix needed!
LP Build 0.9.0.89
Buildcraft 6.4.8
Forge 1370

Stacktrace:
http://pastebin.com/XyYicG06

Sounds like a missing null Check for me.

**Comment by davboecki** [comment]
Please check if your proxy got disabled. And look for the stacktrace there.

**Comment by bziemons** [comment]
> <Bitterholz> davboecki:  gate stuff seems to be fixed!
