### ISSUE TITLE
Polymorphic item sink does not look at item of a locked empty JABBA barrel

### ISSUE THREAD

**Issue by bziemons** [RS485/LogisticsPipes#658]
Look if it is possible to get the item from a locked but empty JABBA barrel and still sink items of the type to that barrel.

Partly a bug, but might not be fixable.

**Comment by Bitterholz** [comment]
It should be fixable, because I think the Barrels Expose the Itemstack they can accept.

**Comment by theZorro266** [comment]
Practically that comment is as useless as this comment.

**Comment by Bitterholz** [comment]
I havent yet looked into their API, im just making assumptions

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/blob/mc17/common/logisticspipes/proxy/specialinventoryhandler/JABBAInventoryHandler.java#L93
and
https://github.com/RS485/LogisticsPipes/blob/mc17/common/logisticspipes/proxy/specialinventoryhandler/JABBAInventoryHandler.java#L83
are probably the reasons why it currently isn't working.

**Comment by SonOfTheStars** [comment]
So guess we probably only need to remove the itemstack.size>0
BTW are we handling TE Caches the same way?

**Comment by davboecki** [comment]
Probably.
IIRC we currently don't handle TE Caches at all.

**Comment by bziemons** [comment]
https://github.com/RS485/LogisticsPipes/blob/mc17/common/logisticspipes/proxy/specialinventoryhandler/JABBAInventoryHandler.java#L94
"items.stackSize-(_hideOnePerStack?1:0)" should not make it -1 though.

And it is needed to see where the methods are used and to see, if the check for the itemstack size is needed there instead.

**Comment by bziemons** [comment]
That change looks inconsistent..

**Comment by davboecki** [comment]
Why? The only places that ask for the method are Specific Interests and The Polymorphic ItemSink.

**Comment by bziemons** [comment]
The current state is fine with it, but inconsistencies can break future code. Those two methods should not differ in the amount of item types they return. When you just look at their names (and/or the missing Javadoc) that does not make sense.
