### ISSUE TITLE
items sinking into furnace wrong

### ISSUE THREAD

**Issue by AartBluestoke** [RS485/LogisticsPipes#66]
furnace on the left (LP) delivers coal only to the output slot. the furnace on the right (basic BC) delivers _only_ to the correct fuel slot (drops all further items it tries to insert). 
edit: replacing the chassi with a basic pipe has the same behavior - no fuel inserting to fuel slot on the bottom.
![furnace](https://f.cloud.github.com/assets/1892829/438494/c21a0dec-b0cb-11e2-932a-f6ec5da81438.png)

**Comment by davboecki** [comment]
Caused by the new ISidedInventory from minecraft not handled by BC.

**Comment by AartBluestoke** [comment]
this is a problem that _only_ lp has -- the gold pipe on the right sinks correctly, the lp pipe on the left fails.

**Comment by davboecki** [comment]
Should be fixed now.
