### ISSUE TITLE
Ducts cause Lagspikes!

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#660]
Having TD Ducts instead of a Basic-Pipe in an Intersection causes the Client/Server to find the Route using TD Routing, wich is fine by itself.
But if hooked by LP, it causes a lagspike wich exponetially grows the more Intersections there are.

@davboecki  you saw my Crafting setup in the Server World I passed to you...
It was basicly a Giant Lagspike Generator! All those connections not being Basic Pipes but Warpducts instead made for up to 6 seconds of completely locking the server, if you only issued a One-task craft.
It totally shrekt the server!

Even the few Warpducts being intersections at my chests(6) allready caused 2 Seconds response time.

I just swopped them out for all basic pipes in the Intersections and im Lagfree again.
BTW to those who think im dumb not using basic pipes @davboecki and I actually had a Chat where he promised me that  it would work fine without them.

Guess the Profiler lied @davboecki...seems like we have to profile again.

**Comment by davboecki** [comment]
This: https://github.com/RS485/LogisticsPipes/blob/mc17-0.9/common/logisticspipes/proxy/td/TDDuctInformationProvider.java#L175 needs to be cached and maybe this too: https://github.com/RS485/LogisticsPipes/blob/mc17-0.9/common/logisticspipes/proxy/td/TDDuctInformationProvider.java#L146 (for the other implementations as well)

**Comment by SonOfTheStars** [comment]
Jeah caching would help alot instead of each time go through all the 4 LP-Connections on the Duct.

I was suprised it wrecks the performance that hard...almost exponentially

**Comment by davboecki** [comment]
@Bitterholz Can you test if this helps: https://dl.dropboxusercontent.com/u/33855125/LogisticsPipes/logisticspipes-0.9.0.testbuild.jar. And can you test that build for other crafting related bugs as well. It should also fix problems with fuzzy crafting. (It also includes a null check to fix your other crash)

**Comment by SonOfTheStars** [comment]
Thanks @davboecki ! Goonna test right away!

**Comment by SonOfTheStars** [comment]
I think ill spend the night Building a Enormous LP system just for testing purpose :D

**Comment by SonOfTheStars** [comment]
@davboecki first one:
http://pastebin.com/XAwNWFm2

**Comment by davboecki** [comment]
Does that one come up every time?

**Comment by SonOfTheStars** [comment]
@davboecki Fuzzy crafting is still broken. Its not pulling items out even though ther valid items now get supplied.

**Comment by davboecki** [comment]
Remember that currently the result needs to match exactly. So e.g. crafting wood from a different type won't work. [For now. that's part of the reason for my work on the RequestTreeNode]

**Comment by SonOfTheStars** [comment]
Allright. Otherwhise it seems like you fixed the main issue.
thanks alot

**Comment by SonOfTheStars** [comment]
I can confirm your changes seem to have fixed the issue almost completely!

Crafting still needs to be looked at.
