### ISSUE TITLE
Crash when place a liquid extractor/satellite pipe

### ISSUE THREAD

**Issue by redace0001** [RS485/LogisticsPipes#662]
Hello !

Yesterday i tryed to play minecraft after updating my modpack but my map doesn't start ... after a moment my game crashed and if I delete logistics pipes from my mods , no problems comes ... so here is the crash report 
PS: If you want the modpack and/or the map , say it and i give it to you ^^

Thanks to you for your help

https://gist.github.com/theZorro266/5a8e95aeb3d9c5598653

**Comment by SonOfTheStars** [comment]
You probably need to check your other mods for Updates. They seem to add null fluids.

Forge and LP are good, but if some other mod doesnt register their fluids right, like railcraft and such, you get a crash like this.

So after all, this is not the fault of LP

**Comment by Bitterholz** [comment]
And please, do not put raw Crashlogs onto github.
I suggest you use https://pastebin.com for these. They make you a nice shoort link for it

**Comment by redace0001** [comment]
OK thanks for reply but do you have an idea about the mod whit problem? I think it only can be a cofh mod or directly buildcraft. OK I will make à Dropbox file next time ^^

**Comment by redace0001** [comment]
OK I will make à Dropbox file next time ^^

**Comment by loordgek** [comment]
no https://pastebin.com not Dropbox

**Comment by SonOfTheStars** [comment]
@redace0001 the problem is it could be any mod that adds fluids...
If you can remember what fluid you tried to process, you can probably Track down the mod wich causes you problems.

Anyways, apart that, I suggest you Update all mods that add fluids if they offer a newer Version than yours. Many mods have issues with the newest forge because they do Not register their fluids  the right way

**Comment by redace0001** [comment]
OK i'm gonna try ... The problem come when I try connect fluid extraction
pipe to a water tank ... I will wait for update of cofh because it was the
tank of thermal expansion when game crash ...
I will put my crash report in ther forums

**Comment by SonOfTheStars** [comment]
@redace0001 You might want to Upgrade to(at least) Forge build 1377 or higher.
In there they fixed "Junk"-Fluids being contained in the Fluid Registry. That might help you and alot of Others as well!
Greetz
Bitterholz

**Comment by bziemons** [comment]
I do not want the race "who is the best hoster for log files", but please just use GitHub gists (https://gist.github.com/). If you are making an issue here, you have a GitHub account anyway.
It is a fact that Gists can hold multiple files AND also have larger file sizes (for full FML logs, if you are asked for those).
I know that is a bit off-topic, but please suggest Gists instead of pastebin when possible.

**Comment by StarkRG** [comment]
I'm getting the same error, however it happens for me when I place a fluid satellite pipe. I didn't even get a chance to connect it to a logistics network OR open the config gui nor was there a crafting pipe with fluid crafting upgrade yet.

http://pastebin.com/LcgU27bR

Any advice for narrowing down which mod might be adding a null fluid? (other than going through them one-by-one)

**Comment by redace0001** [comment]
Hello !
Sorry guys but updtating forge don't repair the problem , I tryed to launch whit 1.7.10 - 10.13.3.1381 (more recent versions are corrupted) but nothing has changed ...
I have sended the link of this topic to COFH team to see if they can make something ... i'm waiting for them...
Do you want i give to you my modpack and the map for testing ?

Thanks to you

---

@StarkRG Did-you use a tank from COFH (thermal expansion) or another ?
I've no problem with Tanks from buildcraft ...

**Comment by redace0001** [comment]
@StarkRG Did-you use a tank from COFH (thermal expansion) or another ?
I've no problem with Tanks from buildcraft ...

**Comment by StarkRG** [comment]
@redace0001 No tank, it was a fluid satellite pipe, not an extraction pipe. I placed it next to a mariculture vat which was empty. It continues to crash whenever I load up that world.

---

New datapoint: simply placing a fluid satellite pipe causes the crash. It's not connected to anything else, no tank, no vat, no other pipes.

**Comment by StarkRG** [comment]
New datapoint: simply placing a fluid satellite pipe causes the crash. It's not connected to anything else, no tank, no vat, no other pipes.

**Comment by redace0001** [comment]
same with extraction pipes ...

---

somebody has tryed with only buildcraft and logistics pipes ?

---

I've changed the name of the topic now it's liquid Extractor AND Satellite Pipes !

**Comment by redace0001** [comment]
somebody has tryed with only buildcraft and logistics pipes ?

**Comment by redace0001** [comment]
I've changed the name of the topic now it's liquid Extractor AND Satellite Pipes !

**Comment by StarkRG** [comment]
I made a dump of the fluid database using NEI Integration. There's a lot of nulls in there but I don't think they're the issue as they've been there all along.

http://pastebin.com/iGKUAn8t

**Comment by bziemons** [comment]
Can you use Forge 10.13.2.1291 please?

**Comment by SonOfTheStars** [comment]
Its mainly the fault of mods not implementing their fluids the right way. Nothing LP has to take account for.

**Comment by redace0001** [comment]
sorry @theZorro266 but my modpack need a version >10.13.3.XXXX so cannot do that ...

---

Ok i've soething new ... I tryed to launch the game whitout all my "Chickenbones mods" deleted and now my game don't crash instantly ... I can "play" during 2/3 seconds before crash ! But the crash-report give the same error "Cannot create a fluidstack from a null fluid"

---

i will try recreate the bug with one by one disabled mods of my modpack ... but tomorrow because is midgnight for me in France ^^

**Comment by redace0001** [comment]
Ok i've soething new ... I tryed to launch the game whitout all my "Chickenbones mods" deleted and now my game don't crash instantly ... I can "play" during 2/3 seconds before crash ! But the crash-report give the same error "Cannot create a fluidstack from a null fluid"

**Comment by redace0001** [comment]
i will try recreate the bug with one by one disabled mods of my modpack ... but tomorrow because is midgnight for me in France ^^

**Comment by SonOfTheStars** [comment]
I can only suspect its one of the main fluid mods that didnt yet have an update and therefore still Register null fluids. Probably Railcraft, Thermal Expansion, Buildcraft or Tinkers Construct...

**Comment by StarkRG** [comment]
The only possible culprits are buildcraft or logistics pipes (unless you think it could be NEI, which is pretty damn unlikely).

http://pastebin.com/vW5K77a1

I could try it without buildcraft but will LP run without buildcraft?

EDIT: The answer is no, it will not.

---

Ok, trying with the absolute latest version of Forge: 10.13.3.1389... nope.

Looks like there's been a lot of fluid-related activity in Forge over the last few days: http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.3.1389-1710ls/forge-1.7.10-10.13.3.1389-1710ls-changelog.txt

What version are you guys building against?

**Comment by StarkRG** [comment]
Ok, trying with the absolute latest version of Forge: 10.13.3.1389... nope.

Looks like there's been a lot of fluid-related activity in Forge over the last few days: http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.3.1389-1710ls/forge-1.7.10-10.13.3.1389-1710ls-changelog.txt

What version are you guys building against?

**Comment by asiekierka** [comment]
This is an issue with Forge 1355+. Their FluidStack logic changed and does not allow null or invalid fluids now. BC has patched this throughout 6.4.9-6.4.11, you might need to mimic the changes.

**Comment by bziemons** [comment]
Forge will soon get a new recommended build and we will program against that. Any issues will be solved when the new recommended build for MC 1.7 comes out. Until then use the current recommended build or wait.

**Comment by StarkRG** [comment]
Virtually every other major mod has updated to the new forge versions. Mekanism was one of the last holdouts but made the change a few days ago.

The recommended forge version is extremely outdated and won't work with the latest releases of a large portion of mods (Extra Utilities and Mekanism to name a couple). I implore you to change your mind and make the change now.

**Comment by SonOfTheStars** [comment]
I would suggest as well we should update the Forge version against wich we build more frequently.

**Comment by hron84** [comment]
@StarkRG but the latest Forge has serious problems very often and I absolute understand and agree why LP and some other mod developer builds against the recommended Forge. Forge should change their mind and don't release any change that _can_ broke mods and mark it as stable.

**Comment by StarkRG** [comment]
@hron84 I get that, and most of the time that works fine, but it's been several months since the recommended Forge version was released and most mod developers have moved to supporting the newer versions. In my really, really big pack the only mod that isn't compatible with the new fluid changes is LP.

**Comment by StarkRG** [comment]
Thanks guys, you're all freakin' awesome!

**Comment by bziemons** [comment]
Thank @portablejim for finding a compatible and easy solution to the problem.

**Comment by redace0001** [comment]
Thanks for the fix @portablejim. It work! No problems now!
