### ISSUE TITLE
Logistics Fluid Pipes do not connect to fluid BC pipes anymore

### ISSUE THREAD

**Issue by Casper-O** [RS485/LogisticsPipes#664]
Have Logistics Liquid Connector Pipe been removed?

I can only find it in the language files, anything else regarding it seems to be missing. I stumble over this when I was trying to connect a Fluid pipe to my Logistic network, and it should be used to connect the Logistics Liquid Insertion Pipe with the fluid pipe, as far i can understand on different wiki sites that have information regarding Logistic Pipes.

I have tried most other things, but nothing else seems to work. The work around I have is making a BC tank and use the Logistics Liquid Extractor Pipe to connect it to my LP network.

**Comment by bziemons** [comment]
I have no knowledge of it being removed, but I can confirm this..

**Comment by Casper-O** [comment]
thx, good to know that i'm not just getting insane...

The question is, was it a mistake?

**Comment by bziemons** [comment]
Nah, the fluid pipes with the new system are supposed to connect to BC fluid pipes directly. I tested that and it did not work. So this needs some closer look.

**Comment by asiekierka** [comment]
Is this still the case with BC7?

**Comment by Casper-O** [comment]
I have not tested yet since i had other issues connecting pipes between LP and BC
