### ISSUE TITLE
ComputerCraft method getPipeForUUID seems to always return null

### ISSUE THREAD

**Issue by oafx** [RS485/LogisticsPipes#667]
Hi,

i'm not quite sure if i'm doing anything worng but tbh i don't think so: Placing two (Request-)Pipes+Computers, inserting the CC remote modules, getting the UUID for pipe A via getRouterUUID() and trying to get the pipe object via getPipeForUUID(UUIDofpipeA) at pipe B always returns nil. It does though throw the expected Permission Exception if i remove the CC remote module.

I'm using LP build 0.8.3.116

Thanks in advance

**Comment by bziemons** [comment]
We will have a look into that. Actually needs to be tested on our side
