### ISSUE TITLE
Cannot control LP through OC

### ISSUE THREAD

**Issue by Omega-Haxors** [RS485/LogisticsPipes#670]
I'm not sure if LP has OC compatability, but as it stands now the OpenComputers mod will read the Logistics Pipes as "bc_pipe" and offers no additional functionality over normal buildcraft pipes. Even requests tables will show up as pipes, oddly enough.

I would really like to have an automatic program to extend my LP network even further into automation.

**Comment by davboecki** [comment]
LP 0.8 has support for OC v1.3,
LP 0.9 has support for OC v1.4.
What versions are you using?

**Comment by Omega-Haxors** [comment]
I need to update. Disregard.
