### ISSUE TITLE
Why is this not a thing!? (Numerical Requests)

### ISSUE THREAD

**Issue by Omega-Haxors** [RS485/LogisticsPipes#673]
I was quite shocked to find out that there's no way to request a certain number of items.

Don't get me wrong, the "+,++,+++" system works great, but sometimes I don't want to click the +++ button 90 times to get my very large process completed.

Simply add a button that allows you to type how many items you want to request.

(Unrelated, but this is why I had to process all 3 million of my cobblestone. I just didn't have the patience to press the +++ button over 9000 times so I just (against better judgement) did Control+A instead)

**Comment by davboecki** [comment]
You know that you can use the scrool wheel of the mouse to switch pages as well as change the amount? Just hold down shift.

**Comment by Omega-Haxors** [comment]
Thanks for the tip, but that still doesn't address the core issue at hand.

If I want to request a large amount of items anywhere between 9000 and 9000 million, using the existing system is a complete pain. I either have to click +++ until my hand falls off, or do Control+A and request every avalible resource of that type.

There's no in-between and AFAIK no way to just tell it that I want 9001 of something.

**Comment by hron84** [comment]
Also the current system is not very precise. You can accidentally miscount clicks and if you want 6 stuff that contains a crafting item made from 4 diamond per each (as I know +/++/+++ buttons can handle automatic craftings too), and you accidentally request 7 or 8... then you wasted 4-8 diamond. Entering a number can make it more precise and less error-prone.

**Comment by bziemons** [comment]
I wouldn't try requesting 9000 million items. Anything over ~2.14 billion (2^31) will cause problems :)
See https://github.com/RS485/LogisticsPipes/blob/mc17/common/logisticspipes/utils/item/ItemIdentifierStack.java#L25

Numerical requests themselves sound fine though. I don't understand @hron84's problems though, because with requesting you see the number of requested items, before you click "Request", anyway?

**Comment by hron84** [comment]
Oh, I misunderstood the problem, I thought this ticket is about Logistics Request Table because there is no feedback about number of requested items.

**Comment by bziemons** [comment]
Ah, you mean when you craft an item and click on the request button there? Yeah, I see.
