### ISSUE TITLE
More Basic Pipes with Tiers

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#676]
So, I figured since there are so many Issues with integrating Thermal Dynamics Ducts,
Why not give our Users a even better experience!
Not just featuring Ducts and relying on warp ducts as Top Tier Transport.

Logistics Pipes makes its way into being a Standalone and a nifty thing to have would be different Tiers of Basic Logistics and Unrouted Transport Pipes.
Users will Start out with the very Basics of Pipes, wich would be the normal Versions, but  bit more slow in Transporting.
Tiers could be:
- Basic(T1) Pipes, slow-ish speed of Transfer
- Intermediate(T2) Pipes, sligthly faster than current Pipes, draws more Power
- Advanced(T3) Pipes, Stupidly Expensive, similar Model like Thermal Dynamics Cry-Stabilised Fluxducts, sends Items Instantly from Point A to B with cost of Power for each Item for each Pipe.

Effectivly, speeds of Transfer could be:
- Basic: 60% of Current
- Intermediate: 120% of Current
- Advanced: Instant Point A to B

Effectivly Power usage could be:
- Basic: 50% of Current(Basic Logistics Pipe only! Unrouted Pipe is free of Power usage)
- Intermediate(Basic Routed): 130% of Current
- Intermediate(Unrouted): 10 LP per ItemStack transfered(Counts for each pipe the ItemStack passes)
- Advanced: 80 LP per Itemstack transfered(Counts for each pipe the ItemStack passes)

Implementing these, we allow the User to advance their System while they Progress throught their Modpack.
Additionally, we keep up with the latest Trends and therefore stay in the game because we can Compete with Lategame AE2 and Thermal Dynamics.

Though, it gets Problematic when it comes to recipes.
We cannot rely on things like Enderium or Electrum to exist in the Game, cause that would make us hard-dependant on Thermal Foundation.
Sure most Packs today don´t even try to run without all the CoFH Mods, but we can still not rely on that.
So we need to come up with a Creative way to allow things to be increasingly expensive.

Question is, Do we want to add new ressources? Do we want to add something like Enderium and Electrum ourselfs or do we want to rely on Thermal Foundation?

**Comment by bziemons** [comment]
First of all: No tags in the title.. They are ugly and don't really help.
As usually I disagree with being more like other mods and I would not agree with nerfing the current basic pipe. Having a second tier of that pipe with more speed sounds good though, as I always wanted more useful speed upgrades for the late game (and huge distances) anyway. 

The instant teleport pipe sounds ridiculous though. I see why people might want it, but I suggest using a different mod then. I would be fine, if they make their way into the mod, but I wouldn't use them.

**Comment by hron84** [comment]
@Bitterholz "Sure most Packs today don´t even try to run without all the CoFH Mods"

I saw a lot of pack with only CoFHCore that makes these metals and alloys unavailable since they're available only if ThermalFoundation is installed.

If you really want to rely things like that, you can make a recipe system like MFR b/c it can make its items and blocks more like to fit into TE/EIO recipes if any of them is available and use vanilla items if not.

**Comment by SonOfTheStars** [comment]
"If you really want to rely things like that, you can make a recipe system like MFR b/c it can make its items and blocks more like to fit into TE/EIO recipes if any of them is available and use vanilla items if not"~ @hron84 

Sure do that! We need to have own Recipes. That was what I was planning to do!

**Comment by davboecki** [comment]
I don't see the reason for an instant item traveling pipe inside LP. People who want that should use the integration with other mods LP has. LP is all about routing and moving the items around not about magically teleporting them.

Regarding the "Intermediate" pipe proposal. I had the thought of making a new fast transportation tube that would be a multiblock structure and use multiple blocks to transport items. It would use 4 blocks to speed items up/down, 3x3 blocks to make a side turn and 4x2 blocks to elevate/lower items by one block. They should be called `High Speed Tubes (HS-Tubes)`. Speeding items up or slowing them down consumes energy, which comes from either an external power source or the LP system.

**Comment by SonOfTheStars** [comment]
@davboecki So Red Power Magtube style? Sounds great!

Regarding Instant Travel, Its not Mgaically, Its "Transporting Matter over Distances vcery quickly by creating a  Zero Friction Space inside a vacuum, contain the Matter in a ferromagnetic container and accelerate it with Gauß´s Magnetic Induction principle"
That would be a very good explaination of reaching speeds of multiple Sonic Speed. Wich is totally possible in Real Life, given there is enough Energy.
And since Items would Travel at Mach3 its would be very much Instant.

**Comment by bziemons** [comment]
Tell that to the 90 degree corners in your Logistics System. Your item would probably explode out of the pipe. Slowing items down in one direction instantly and speeding items up (to Mach3 or similar) instantly is unrealistic as well. Though I am not saying that everything should be realistic as Logistics Pipes is not realistic in all cases, but it's good to find a trade off, when having high speed transportation. I support @davboecki's idea.

**Comment by hron84** [comment]
@theZorro266 
Well, even if not too hard to point to a difference between MineCraft and real world, I think it's a good idea if some newly implemented features keep as close to the real world as it is possible if it's not break the classic MineCraft physics.

**Comment by SonOfTheStars** [comment]
@theZorro266 Ender Physics being a thing in Minecraft, its very well possible. BTW if there is enough Magnetic Force pulling on the Container, even 90° Corners arent a Problem.
And ive seen many many Cases where the Users just say: okey LP is to slow from this Point, go AE!
Wich is not what we want to see.

After all, (If I got this right) LP wants to be a Mod thats useable in all Stages of a Minecraft World Experience and is attractive to the Users by offering different Ways of Transport Speed and a Huge variety of fine selected Utilities to route things just the Way you like it.. isnt it?

Im hating being a Copycat but it would be a hell of alot easier if we had our own Warp-Pipes, based on Ender Physics and/or Super Conduction. Because when our Users go for Warp Itemducts anyways later on, why not offer some of our own, wich we don´t have to modify via ASM and are Independant from other Mods.

**Comment by bziemons** [comment]
> And ive seen many many Cases where the Users just say: okey LP is to slow from this Point, go AE!
> Wich is not what we want to see.

That is a decision users make. Going "mainstream" to prevent that from happening makes LP too similar to others and that, instead, is what I really don't want to see.

I already use LP in all stages of my world and when I used something else I wished LP back. I do not see how any other mod can replace LP in the way I use it. And that makes it unique and useable in any state of the game for me. I have heard a similar view from other users.

All I want to see is a different style in LP and I think the multiblock high speed tubes are different from other mod's items in their way. They will be faster and already a few people liked the idea. I hope everyone will like and use them.

I don't want to use those T3 pipes, which route, teleport and do whatever you tell them, because it **is** magic and far too easy in terms of a logistics system, ever. And as I said: **if** I am the only one with that opinion it **would** be fine if they make their way into the mod, but I will never use them.

**Comment by ghost** [comment]
Little bit unrelated, but what mods work with Inventory System Connector pipes? I have been trying to speed up my very large network by subdividing into segments and linking them that way. 

I know that CB ender chests work but they bug out occasionally. TE4 Tesseracts aren't working but I might be able to rig something up using vanilla chests and ducts to act as intermediaries. Additional Pipes teleport pipes seem to not work either.

**Comment by SonOfTheStars** [comment]
@DZCreeper, TE4 Tesseracts require just a Basic Pipe on each Side. Enderchests from Chickenbones EnderStorage run well with it.

@theZorro266 How about T3 Pipes that do warp, but ONLY unrouted and only in Straight lines like the Laser System we allready have for the Power Routing?
Plus, Stupidly Expensive, upgraded version of the Multiblock T2 Pipes?

**Comment by ghost** [comment]
Thank you for that tip about the tesseracts requiring a Basic Pipe. I had tried that but this time I placed the tesseracts after the pipes and the link worked. I don't really think stock LP needs higher speed options, people can use item teleport options for that. The idea of having to compete in terms of features just to be a good mod is silly.

**Comment by SonOfTheStars** [comment]
@DZCreeper As LP wants to be somewhat standalone, we need more options for speed.
And competition for Users between Software is natural.
If we want to bring LP to a new shine again, like it was pre AE, we need to offer more options.

Not making it easy, multiblock pipes as T2/T3 pipes is very unique and allows for making stuff more Complicated as well as Appealing for the user.

@theZorro266 Keep in mind, we make LP for the Users. At least I hope so.
And because we didnt go with the time, 90% of the former users just went straight for AE. 
Im not saying we need to make stuff as easy as AE, since we still  rely on basic storage. We can offer less buggy versions of warp ducts in a unique multiblock way, and rely less on other mods.
because otherwhise Users just go for other mods.

And as you said before, we can OFFER IT, doesnt mean anyone has to use it

**Comment by bziemons** [comment]
@Bitterholz I think I have said everything on this topic in my previous comments. Please discuss that with davboecki instead, as he is making the new tubes.

**Comment by SonOfTheStars** [comment]
@theZorro266 hes allready on it? Damn son! 

@davboecki So, what are your plans on the Pipes? Im super Interested how you Imagine them!

**Comment by bziemons** [comment]
Accepted as in what @davboecki said here: https://github.com/RS485/LogisticsPipes/issues/676#issuecomment-102660443

Parts of the tubes are already in 0.10.0
