### ISSUE TITLE
Crash while loading a singleplayer world

### ISSUE THREAD

**Issue by qib18664** [RS485/LogisticsPipes#677]
When I am trying to join my singleplayer world my game keeps crashing. I am using the Infinity Modpack Version 1.3.4. I played a few hours on this world and last placed something from Logistic Pipes days ago and until now the world loaded perfectly. Only Block out from this Mods I am using are for the Remote Orderer on my AE2 Interface.
Crash Report:

https://gist.github.com/theZorro266/f7fd64157fe37c71bfc9

Hopefully someone can help me
~LuxuryMiner

**Comment by bziemons** [comment]
Please put your crash logs and any bigger files into a https://gist.github.com.
Could you please try installing version 0.8.3.114 or newer? The issue should be fixed in there.

**Comment by qib18664** [comment]
Sorry for the long text, but this is my first post and I did not know how to make this with https://gist.github.com/. I will do this in future!
Thank you for your help, I tried loading the world and it worked fine
