### ISSUE TITLE
LP 0.8 ignores "B:checkForUpdates=false" config option

### ISSUE THREAD

**Issue by Barhandar** [RS485/LogisticsPipes#679]
YOUR LOGISTICSPIPES VERSION IS OUTDATED

Not a dupe of #657, using LP 0.8 build 119. I disabled the bloody update checker for a reason, it, unlike every single other one, sends the "update found" message on _every world load_ instead of only the first.

**Comment by davboecki** [comment]
Single Player or Server ?

**Comment by bziemons** [comment]
Maybe it's set on the client and not the server

**Comment by SonOfTheStars** [comment]
It does it on every World load for me too. But only after a Shutdown (Client and Server). The Script is bugged anyways especially for 0.9 but for 0.8 as well.

Still don´t know why ppl still use 0.8...0.9 is so freaking fancy XD

**Comment by hron84** [comment]
@Bitterholz because there is so many modpacks in the wild that do not want to jump to an another a main version without a wide test of intercompatibility. And ppl love using modpacks regardless which version of mods contained in it.
