### ISSUE TITLE
Mouse scroll wheel not working

### ISSUE THREAD

**Issue by grydian** [RS485/LogisticsPipes#68]

**Comment by grydian** [comment]
Sorry about that..  I cant use the mouse wheel to change the number of items to request with a request pipe...

**Comment by davboecki** [comment]
Is a mod Conflict with Modular Powersuits.

**Comment by grydian** [comment]
Should I contact machinemuse or is there a fix on LP's end?

**Comment by davboecki** [comment]
There probably is no way for LP to fix it.

**Comment by davboecki** [comment]
Fixed On LP end.

**Comment by grydian** [comment]
Awesome thanks guys!
