### ISSUE TITLE
Extractor Mk3 no longer extracts saplings from Multifarm

### ISSUE THREAD

**Issue by CourtArtanis** [RS485/LogisticsPipes#687]
Hi,
After updating to the unstable Forestry build as per recommendation https://github.com/ForestryMC/ForestryMC/issues/684

My LP Extractor mk3 module will no longer extract saplings from the farm hatch. I also tried changing the extract orientation to see if that would change anything.
The module happily extracts sand/logs/apples, but leaves the Apple Oak saplings in the farm inventory. I've also tried an Advanced module to specify extraction. No change.

Worth noting: The saplings also will no longer drop from a hopper into a JABBA barrel after placing them manually in the hopper, this worked prior to the update (Farm Extract via LP > vanilla hopper > JABBA)

LP version logisticspipes-0.8.3.122

Is there a workaround for this? Or is a downgrade the best option?
Thanks

**Comment by SonOfTheStars** [comment]
Id rather upgrade to LP 0.9.

Try it with the 0.9 branch.

It works just fine for me!

**Comment by CourtArtanis** [comment]
@Bitterholz Thanks for replying, but this did not fix my issue.

**Comment by SonOfTheStars** [comment]
@CourtArtanis  Are you using Advanced extractors or just the Normal ones? On wich side is your Extractor attached? Wich build of Forestry do you use?(Exact Number pls)

**Comment by SonOfTheStars** [comment]
OH BTW the Farm will FIRST Supply its own internal Buffer for Saplings(8 Stacks) before making them available for output!

**Comment by CourtArtanis** [comment]
It was my fault, for some reason the route set for saplings had unset(?) itself, so the saplings had nowhere to go, therefore the extractor wasn't pulling the saplings from the output inventory. It was a stupid mistake, apologies for wasting time.

**Comment by SonOfTheStars** [comment]
@CourtArtanis no problem mate ;)
