### ISSUE TITLE
Logistics fluid provider pipes won't connect to the network

### ISSUE THREAD

**Issue by FnordMan** [RS485/LogisticsPipes#688]
This is 1.7.10 - 0.9 (yes I know, potential bugs, however it's been working great up until now)
Worked fine on build 109, something between then and build 117 broke things. 
Hopefully attaching a screenshot here. For now i'll just revert to build 109

![2015-05-30_09 42 23](https://cloud.githubusercontent.com/assets/7041560/7897806/6c3f7762-06b0-11e5-830b-3ab7d077ed81.png)

**Comment by SonOfTheStars** [comment]
Try breaking and replacing the Pipe directly next to it. There is some problems with the Validation of Pipes ATM

**Comment by FnordMan** [comment]
Didn't change anything, break pipe (fluid basic pipe), put pipe back and no connection to the provider pipe. 

Forgot to mention earlier: I did break and replace the provider pipe to no effect.

**Comment by SonOfTheStars** [comment]
Try breaking the unrouted Pipes. BC ones or TD Ducts.
if they dont route, break all unrouted pipes between the routed ones.

Tell me if that helps

**Comment by Casper-O** [comment]
![2015-06-06_22 14 51](https://cloud.githubusercontent.com/assets/956154/8021265/1f9554e2-0c99-11e5-978f-54469bc257ba.png)

I just updated to BC 7.0.6 and LP 0.9.1.11 from BC 6.4 and LP 0.8 - breaking the pipes and replacing them dont make them reconnect

**Comment by FnordMan** [comment]
Looks like everything's fixed after updating BC to 7.0.8 and LP to 0.9.1.11
