### ISSUE TITLE
BC 3.5.3

### ISSUE THREAD

**Issue by MrSapient** [RS485/LogisticsPipes#69]
Happens every time with latest BC 3.5.3 and latest forge

http://pastebin.com/WVDNZkwp

**Comment by Flow86** [comment]
happens also on 3.5.1

had the same issue on Additional Buildcraft Objects - seems to be a kind of reobfuscation-issue. don't know why the deobfuscation "removes"/renames the "pipes"-field in that class (even if it exists in class-file)
