### ISSUE TITLE
What is the current recommended build for BC v7

### ISSUE THREAD

**Issue by xJon** [RS485/LogisticsPipes#696]
Is it Logistics Pipes 0.9, or 0.10? What should I grab?
Thanks!

**Comment by SonOfTheStars** [comment]
I Suggest you go for the 0.9.1 Series of Builds ;)
Its called BC7-Stable

Use this: http://ci.thezorro266.com/job/LogisticsPipes-0.9-mc17-bc7/

**Comment by xJon** [comment]
@Bitterholz Alright, thanks :)

**Comment by bziemons** [comment]
Marked the Jenkins jobs as stable. Thanks for the feedback
