### ISSUE TITLE
Referencing to RenderBlock on server site

### ISSUE THREAD

**Issue by klusekrules** [RS485/LogisticsPipes#698]
When client login on the server occurs this error: 
http://pastebin.com/JnkCqYsY

Minecraft: 1.7.10
Forge: 10.13.3.1401
BC: 7.0.8
BC-compact: 7.0.7
LP: 9.1.13 for BC7

**Comment by theZorro266** [comment]
Always provide your version information about Forge, BC and LP, please

**Comment by klusekrules** [comment]
Minecraft: 1.7.10
Forge: 10.13.3.1401
BC: 7.0.8
BC-compact: 7.0.7
LP: 9.1.13 for BC7

**Comment by klusekrules** [comment]
Did this fix will be added on the LP version for BC7? I see it only for LP version for BC6.4.

**Comment by bziemons** [comment]
There was just another bug I ran into, so I had to fix that first. Fixed in 0.9.1.14 for BC7 and 0.9.1.126 for BC6.4.
