### ISSUE TITLE
[Enhancement] adding support for RP2 BT Batteries for the Electric Manager Module

### ISSUE THREAD

**Issue by thatsIch** [RS485/LogisticsPipes#7]
Minecraft 1.4.7
BC 3.4.2
LP LogisticsPipesDev 0.7.0.122

Got a normal setup for IC2
Extractor Module on left Chest
Manager + Extractor on the center
ItemSink + DefaultRoute on right Chest
does work

![2013-02-03_16 45 20](https://f.cloud.github.com/assets/2210496/121968/ea19c1ca-6e18-11e2-8bd6-1973134f70bc.png)

Same setup for BT Batteries, but doesnt work.

![2013-02-03_16 45 25](https://f.cloud.github.com/assets/2210496/121970/279a59ba-6e19-11e2-9c74-3b74de4edaa6.png)

**Comment by MrTJP** [comment]
Ic2. Only.

**Comment by thatsIch** [comment]
so no support for RP2 intended?

**Comment by MrTJP** [comment]
Ic2 has an API that can be used. Rp2 does not. I was looking into it but there didn't seem like a good way to do it. I may look into it some more.

**Comment by thatsIch** [comment]
ok cause a simple setup where to check the different damage values of the items doesnt work with a simple
- extractor
- itemsink (empty battery) + extractor
- itemsink (full battery)

The battery is getting extracted from the left chest and directly moved to the right chest

![2013-02-03_17 05 45](https://f.cloud.github.com/assets/2210496/121991/9d70a0ca-6e1b-11e2-93c8-17e975fbd2c2.png)

**Comment by MrTJP** [comment]
Because eloraam does it differently. She even had to code her own transposers, etc. to pay attention to the charge. Of coarse, we cans do that because no API.

**Comment by thatsIch** [comment]
aww too bad, ok I close this for now since there is no other way right now.
Thank you for explanation

**Comment by davboecki** [comment]
Well The main problem for this would be to get permission from eloraam to interact with redpower. The charge tag could be read from the damage value.

**Comment by thatsIch** [comment]
yea and getting in contact with her is so hard :3

**Comment by thatsIch** [comment]
apparently BC Gate Logic can read the Battery State

**Comment by davboecki** [comment]
If anybody has an idea on how to contact eloraam to ask for permission i would ask but i seriously don't have any plan on how to contact her.

**Comment by MrTJP** [comment]
don't hold your breath :) i tried everything… i think she will be around once 1.5 comes up though.

**Comment by ArtForz** [comment]
Active requests honor damagevalue.
Provider+Supplier on chest + crafting pipe on battery box works for "crafting" empty into full batteries.

**Comment by thatsIch** [comment]
so to discharge them you would have to reverse it via providing empty and supplying full ones? interessting

**Comment by AartBluestoke** [comment]
<sinp - mistaken thoughts about tags removed>

We may consider extending the manager to be a general "damaged item sink" -- that would allow you to work with rp batteries, and any other mod that : eg repairs pickaxes ...

**Comment by ArtForz** [comment]
there is no nbt tag.
the charge on rp2 batteries is stored as damage only. and they're marked as damageable.
