### ISSUE TITLE
LP not connecting to BC7 pipes

### ISSUE THREAD

**Issue by demethan** [RS485/LogisticsPipes#702]
BC 7.0.9
LP 9.1.13

after upgrading the server. BC pipes and LP pipes are not connection. Even after breaking them and putting them back. 

Pure LP network works fine.  Pure BC pipe setup works fine.

**Comment by Michal-MK** [comment]
The same thing happens with: logisticspipies-0.10.0.5

**Comment by demethan** [comment]
Works correctly with LP 9.1.15 and BC 7.0.9

**Comment by bziemons** [comment]
Well 0.10.0.5 has the same fixes as 0.9.1.15, so we still need to look at this.
Could you both look into your server and client logs to see, if there were errors logged with Logistics Pipes?

**Comment by Michal-MK** [comment]
When I loged in today it worked fine...  I searched through the sunday logs and found this: http://pastebin.com/BYGVUwQa 

Edit: Now it happed again, so I tried replacing the BC pipes but they connected normally. So this is not causing it.

**Comment by davboecki** [comment]
Are you sure the version you mentioned is correct?

**Comment by Michal-MK** [comment]
Checked the mods folder and the "Mods" button in Minecraft menu. Both say 0.10.0.5

For me its working now so unless the OP doesn't reply, I'd focus on other things.

**Comment by bziemons** [comment]
As we cannot reproduce this, there is nothing we can do about it.
