### ISSUE TITLE
Server and client crash using Fluid Supplier Pipe

### ISSUE THREAD

**Issue by Migul90** [RS485/LogisticsPipes#718]
Used LogisticsPipes 0.9.1.15 to set up a system with Thermal Expansion 1.0.0-176
everything works very well but when you use a Phytogenic Insulator from TE With a Fluid Supplier Pipe
it causes the game to crash and corrupts the server world. Can reproduce it when i configure the sides of the TE Machine when the Pipe is connected
usage with other mods is fully working

sorry for the long crashlog and thanks for helping

https://gist.github.com/theZorro266/f2ab76b46efbf73da23a

**Comment by bziemons** [comment]
Please put the crash log into a https://gist.github.com. I have done that for you now.

**Comment by theZorro266** [comment]
I can reproduce it, but BON does not work for Forge 1448 and TE does not have dev builds nor is open source, so I cannot do anything.

**Comment by bziemons** [comment]
Fixed in Thermal Expansion 4.0.3B1.
