### ISSUE TITLE
BC Gates on Logistics pipes

### ISSUE THREAD

**Issue by Michal-MK** [RS485/LogisticsPipes#719]
Is it intetional that you can not place BC Gates on any Logistics pipe ?

**Comment by bziemons** [comment]
Forge, BC, LP version information please.

**Comment by Michal-MK** [comment]
Forge = 10.13.3.1408
Buildcraft = 7.0.9
Logistics Pipes = 0.10.0.5

**Comment by Leytek** [comment]
I have 
Forge = 10.13.4.1481
Buildcraft = 7.0.13
Logistics Pipes = 0.9.1.15 (Where did you get 0.10.x ?)
and everything fine, but i dont see Gate triggers on LP pipes like "Pipe Waiting for Crafting" on Crafting pipe and "Supplier failed" on Supplier pipe. Is it normal ?

**Comment by bziemons** [comment]
0.10 is our dev branch and we published a few builds of it already. We took the download down, because there is no difference in 0.9.1 for the user, except instability, because of new features, which no-one can use.

**Comment by Leytek** [comment]
What about Gate triggers ? It was removed or smth else ? I remember i used this gate triggers in my LP system in Minecraft 1.6.4, but now they even not exist.

**Comment by bziemons** [comment]
Not relevant anymore in the new LP version. Gates are currently not supported.
