### ISSUE TITLE
Using crafting sign on crafting pipes above a crafting table causes light issues

### ISSUE THREAD

**Issue by tomevoll** [RS485/LogisticsPipes#721]
I got a double row of 10 tables 2 wide all having a crafting pipe on top with a crafting sign.
When a sign is added to the pipes it causes light issues, crafting table can turn black, some pipes are flashing black and then bright.

It also affect other vanilla blocks like chests, items rendered on barrels + +.

this has been present in all the versions i tried after it got the new pipe design, old versions with the square pipe design does not have this issue.

mc version 1.7.10
BC 7.0.11
LP 0.9.1.15

**Comment by tomevoll** [comment]
http://www.mediafire.com/view/l872gmh8hdb5l47/2015-06-26_23.50.12.png
http://www.mediafire.com/view/omstd5k3zwwemcr/2015-06-26_23.50.38.png

2 screenshots to show what exactly is happening

This is the same no matter if i use a texture pack or not, just to clarify it is not the texture pack causing it.

**Comment by tomevoll** [comment]
"some pipes are flashing black and then bright." i meant signs

**Comment by tomevoll** [comment]
Using pipe controller to disable new render fixes the issue, all lighting goes back to normal with it turned off, (i just found out that item existed).

**Comment by bziemons** [comment]
Do you use any mods that are similar to Optifine or Optifine itself?

**Comment by tomevoll** [comment]
no

**Comment by tomevoll** [comment]
also i noticed turning off the new render, lightning seems smoother on the pipes and crafting tables, like the floor is in the screenshots, with the new render its almost like steps on the light from block to block

**Comment by tomevoll** [comment]
i can list the mods directory and paste it on pastebin to be sure you got a full list of the mods if you like

**Comment by tomevoll** [comment]
and i supose i should mention fastcraft is installed

**Comment by tomevoll** [comment]
here is the list of mods.
http://pastebin.com/xE0KDMXQ

**Comment by loordgek** [comment]
04/02/2015  03:13 PM           116,959 fastcraft-1.21.jar
 fastcraft is similar to Optifine

**Comment by hron84** [comment]
Just asking (i found some similar issues but not with LP) is the lighting problem changes/become fixed if you place and broke a torch near the blacked out tables?

**Comment by tomevoll** [comment]
no, it causes a update, but only temporary

Edit;
It causes the black blocks to be brighter, but lighting is still not right, they will go black again randomly, i  if you move to far away from them and go back again

**Comment by tomevoll** [comment]
Removing fastcraft do not solve the issue

**Comment by hron84** [comment]
@tomevoll okay sir, thanks for more information and a bit of testing.

**Comment by Nex4rius** [comment]
I have a similar problem with the signs
https://www.youtube.com/watch?v=xSFK5SwjD3M&feature=youtu.be
also happens without fastcraft
<a href="http://imgur.com/hidw7hQ"><img src="http://i.imgur.com/hidw7hQ.jpg" title="source: imgur.com" /></a>

logisticspipes-0.9.1.15
Infitech2 modpack v3.1.4
