### ISSUE TITLE
Bug in Soldering Station

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#722]
In Soldering Station i used the correct recipe and add iron on respective slot but it don't connect with cables from Mekanism and Ender IO.. In Image i use cable of mekanism 
Obs: Logistic Pipes 0.9.1.15

![2015-06-27_01 52 59](https://cloud.githubusercontent.com/assets/7724449/8390533/55b7496e-1c6f-11e5-9836-fff0a92b3478.png)

**Comment by davboecki** [comment]
The Soldering Station uses LP power. It doesn't work with any other power since mc1.7 .

**Comment by Cristinoo** [comment]
I Connect him in what cable or what ?? Because i don't found on Web anything talk about that...

**Comment by AartBluestoke** [comment]
I believe you could put a lp power node at that last bit of cable. It will
also automatically draw power from an attached lp network.
