### ISSUE TITLE
Cannot step over to a Basic pipe from a BC pipe

### ISSUE THREAD

**Issue by hron84** [RS485/LogisticsPipes#723]
Logistic pipes seems like a bit taller than a BC pipe, if i stand on a BC pipe and I have no room to jump (2 block tall corridor where the pipe is the ground) then I cannot step over to a Basic pipe from a BC pipe. I am not sure if it is an issue, but previously it wasn't a problem since LP pipes had exactly same hitbox like BC pipes.

Since LP piping is needs mining corridors, height is matter. But I can accept if it was intended.

LP 0.9.1.133 / BC 6.4.7

**Comment by davboecki** [comment]
To support the new Pipe model, the bounding box was enlarged. So this is probably a result of that.
