### ISSUE TITLE
Logistics Pipes World Gen Crash

### ISSUE THREAD

**Issue by momokli** [RS485/LogisticsPipes#727]
Cauldron Server crashes when approaching Build-craft Buildings with logistics pipes world gen.
Logs: https://gist.github.com/iMontouch/810580ad3e290b5d7fe1

The used OS seems irrelevant. I am using KCauldron version 1.7.10-1448.121. 
Switching to Forge fixes the problem. I tried the newest KCauldron version but using it, my server wont start at all (other mods causing problems).

User micmou reported this over at the resonant rise forums:
http://www.resonant-rise.com/topic/6499-logistics-pipes-world-gen-crash

**Comment by bziemons** [comment]
I thought you fixed that "post null-check", @davboecki ?
https://github.com/RS485/LogisticsPipes/blob/dev/common/logisticspipes/proxy/buildcraft/BCPipeInformationProvider.java#L42-L50

**Comment by momokli** [comment]
Since its resonant rise modpack, It could be an older version? I will try updating

**Comment by davboecki** [comment]
@iMontouch Please use 0.9 builds. Don't use 0.10, they arn't stable.
@theZorro266 I didn't have the time to fix that.

**Comment by bziemons** [comment]
@davboecki ah okay, but now you have an issue for it ;)
@iMontouch you should be able to downgrade to 0.9.1 easily, but it will warn you about a few blocks that are not present in 0.9.1. That should not be a problem though, because I do not think you use them anyway.

**Comment by momokli** [comment]
I just downgraded and confirmed the missing blocks..worked out fine! Thanks for your help guys!

**Comment by bziemons** [comment]
fixed in https://github.com/RS485/LogisticsPipes/commit/bbe180c5eb608e9b2825cde125a12686dec3ca71#diff-df91b51b15b84b9afa4794d84d159943R41
