### ISSUE TITLE
Inventory System Connector ignores disconnection upgrade

### ISSUE THREAD

**Issue by QORTEC** [RS485/LogisticsPipes#729]
From here on in **Inventory System Connector** as **ISC**

Bug: ISC connects to inventories of disconnected blocks

How to reproduce:
- Setup a ISC
- Place a ender chest on top of the ISC
- Place an disconnection upgrade (up) and/or a pipe plug on the ISC
- Place a 2nd chest directly beside the ender chest
- Send items over the ISC

Current Behaviour:
- When there is a block with an inventory above the ISC the ISC will attempt to place all received blocks into that inventory. This happens regardless of wither that or not the pipe is connected to the block above.

Expected Behaviour:
- The ISC would send items to the inventory of a connected block

Versions:
- Forge: 10.13.3.1408
- BuildCraft: 7.0.13
- LogisticsPipes: 0.9.1.15

---

Welcome to my temporary testing world!

Over here you can see I have a ISC connected to a diamond chest with an ender chest on top of it, the ISC has a Disconnection Upgrade (UP)
![2015-07-01_15 51 04](https://cloud.githubusercontent.com/assets/4239654/8463780/5178c2f2-200b-11e5-937f-78438caa2b79.png)

Over here you can see the disconnected ender chest sending items to the other side of the network
![2015-07-01_15 52 42](https://cloud.githubusercontent.com/assets/4239654/8463786/5ad55e32-200b-11e5-8cb7-104f4ab25b13.png)

Over here I flipped the diamond and ender chests, you can see all the items going into the diamond chest. (one water made it through for some reason)
![2015-07-01_15 55 40](https://cloud.githubusercontent.com/assets/4239654/8463793/6d6acfdc-200b-11e5-8b3b-4986267f0d84.png)

Lastly here is a view of all the items in my disconnected diamond chest on top of the ender pipe, when its full it still doesn't send items to the correctly connected ender chest. 
![2015-07-01_15 57 29](https://cloud.githubusercontent.com/assets/4239654/8463797/723215d4-200b-11e5-8293-35abde9db8de.png)

Side Note:
I setup two of these system right beside each other, and the 2nd one is duping and I can't figure out why, both systems are identical. What happens is that the item is put into the chest and then a second later the item is also sent through the other ISC (2 stacks of wood for 1 transfer)
All screenshots where of the non-duping system

**Comment by bziemons** [comment]
Hey, I have seen your message on IRC. Let me check this real quick. I am sorry that there weren't any updates on this for a while, but life is busy.

**Comment by bziemons** [comment]
I can confirm the items always going into the upper chest and ignoring the disconnection upgrade. I couldn't find a dupe bug caused by this though.

**Comment by QORTEC** [comment]
Thank you for your quick response;

Don't worry about the lack of updates, I rather have my issue never resolved then you to burn out due to overwork. 
Based on the fact that no-one else commented on this issue I suspect its not really "important" to anyone but me; the only reason I found this bug is because I enjoy doing compact builds and noticed a lack of items.  

If there is anything I can to do help let me know.

On the  **dupe bug**, I was only able to recreate a couple of times, I won't worry about it as much since its not easily creatable. [kinda like my tesseract bug]

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/5841b5e09d023dff0a5a47a940030cd53499ddbb
