### ISSUE TITLE
Compatibility with latest Forestry stable (3.6.x)

### ISSUE THREAD

**Issue by p-schneider** [RS485/LogisticsPipes#733]
[Crash log `java.lang.NoSuchMethodError: forestry.api.apiculture.IBee.isPureBred(I)Z`](https://gist.github.com/p-schneider/18c12dff9369029aa29f)

The Forestry API changed from using the Integer ordinal of EnumBeeChromosome to using the interface IChromosomeType itself. ([deprecated since `ForestryAPI|genetics:2.3.0`](https://github.com/ForestryMC/ForestryAPI/commit/d6d724bbd787f432e08a38304ba6bac3cf5bf303) - [removed since `ForestryAPI|genetics:3.0.0`](https://github.com/ForestryMC/ForestryAPI/commit/ad56526b55a42cd44352f8d844564b5e8554c7b3))

If you update the Forestry API ([download-api.xml](https://github.com/RS485/LogisticsPipes/blob/stable-bc7/download-api.xml#L19) / zip file hosted on rs485.theZorro266.com) and update [common\logisticspipes\proxy\forestry\ForestryProxy.java](https://github.com/RS485/LogisticsPipes/blob/stable-bc7/common/logisticspipes/proxy/forestry/ForestryProxy.java#L350) this should be easily fixed. Just search for `root.getMember(bee).isPureBred(EnumBeeChromosome.` and remove the `.ordinal()` at the end. (It should occur in 4 places.)

I compiled and tested it myself and got my world working again.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/1ff3fef0a54e3983b868e78e08b13be8a50cd3d8
