### ISSUE TITLE
crashing game on item request using remote orderer

### ISSUE THREAD

**Issue by zigtronik** [RS485/LogisticsPipes#736]
i believe the issue is caused from having multiple provider modules (i used 3 mk.2) in a chassis, i had this connected to an AE2 interface, when i requested items using the remote, the game would immediately crash, i then removed two of the modules and it didnt crash me anymore, dont know why this is an issue, but hope it can be fixed

Versions
Forge 1448
Logistics Pipes 0.9.1.1.15
Buildcraft 7.0.12

**Comment by bziemons** [comment]
Could you please provide a crash log uploaded to https://gist.github.com?

**Comment by hron84** [comment]
@theZorro266 a side question, what is the current state of AE2 support? Since, if I remember correctly, it is not bidirectional atm, but I always forget which part is not working...

**Comment by bziemons** [comment]
@hron84 we can request items from AE storage, but cannot request crafted items. There is no power share as there was with AE1 and AE2 cannot access anything on the LP side, which is their task.

Other than that this is closed because of a missing crash report.

**Comment by hron84** [comment]
@theZorro266 thx
