### ISSUE TITLE
Bee Analizer Module crash

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#737]
Using Bee Analizer Module with the Forestry Analyzer crashes and corrupts the game.  I can't re-enter the game.  Crash happens when the bee enters and completes the analysis.

MC 1.7.10
LP 9.1.15
BC 7.0.13
Forge 1456
Forestry 3.6.2.19

**Comment by loordgek** [comment]
try to go back to Forestry 3.5.xx.xx

**Comment by ghost** [comment]
Just tried but Forestry 3.5 is incompatible with the Forge version.  And reverting the Forge leads to compatibility issues with other mods.

**Comment by davboecki** [comment]
Can you please post a crash report and Logs.

**Comment by bziemons** [comment]
Might be a duplicate to #733

**Comment by ghost** [comment]
https://gist.github.com/taz1004/93c429db1614459f5d40

**Comment by ghost** [comment]
While trying to reproduce the crash, I realized this might be apiary refiller module issue rather than analyzer module.  Analyzer module works if I have it hooked up to a chest with extractor module.  But crashes if I connect it to apiary with apiary refiller module.

**Comment by hron84** [comment]
@taz1004 could you please put your crash log to a gist and link that gist here instead of paste a wall of text? We would really appreciate this.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/1ff3fef0a54e3983b868e78e08b13be8a50cd3d8
