### ISSUE TITLE
System Connector Pipe does not work between dimensions

### ISSUE THREAD

**Issue by Flow86** [RS485/LogisticsPipes#74]
The System Connector Pipe does not work correctly.

I connected 2 enderstorage-enderchests (proper color code) via 2 system connector pipes, both sides have power and the correct frequency card.

In the Request pipe, all items appear, but I cant request anything. it gets requested, but items are not transported.

Connection via Item Tesseracts like in 1.4.7 dont work either.

**Comment by davboecki** [comment]
What build did you use to test?

**Comment by Flow86** [comment]
latest one (430)

oh inside one dimension it works correctly, but not between.

**Comment by davboecki** [comment]
Sorry but i can't reproduce this bug. In MC 1.5.1.
The Item Tesseract bug should be fixed.
Did you load both sides with chunkloader?
What does the HUD give you for information after you have requested some items.

**Comment by Flow86** [comment]
I'm on 1.5.2.

yes both sides have an admin anchor placed (and I tested it with 2 users too, one in each dimension)

I can request the items (it says successfully requested ...) but they never get transported.

The other way round doesnt work either:

In one dimension: default item sink connected to a chest, pipe network to enderchest/system connector.
Other dimension: obsidian pipe connected to pipe network and enderchest/system connector.
I throw an item into the obsidian pipe -> next logi pipe drops item out due to lacking valid destination.
That works inside one dimension too.

Perhaps 1.5.2 handles dimensions differently?

**Comment by Flow86** [comment]
interesting - after I restarted the server (due to another bc-bug it crashed...) the inter-dimension connection works magically O.o
