### ISSUE TITLE
Setting satellite id on crafting module in hand

### ISSUE THREAD

**Issue by Nex4rius** [RS485/LogisticsPipes#743]
When you try to configure the crafting module in your hand and try to set a satelite pipe for the input you get "Connection Lost A fatal error has occured, this connection is terminated"

logisticspipes-0.9.1.15

**Comment by bziemons** [comment]
Could you upload your client log to https://gist.github.com with the error, when that happens?

**Comment by Nex4rius** [comment]
Is the minecraft/logs/fml-client-latest.log the correct one?
If it is then here https://gist.github.com/DarknessShadow/c09ecacfa10a46a8e83a

**Comment by bziemons** [comment]
Can you look for logs, of the time when you crashed, in the crash-reports folder of your server and client instance? I thought it might be the client crashing or a local instance, but your latest log just shows the client shutting down.

**Comment by Nex4rius** [comment]
My client does not give me a crash report and I'm playing on a server where I don't have access to the files. :(

**Comment by bziemons** [comment]
Are you able to reproduce it locally on a new world in your client?

**Comment by Nex4rius** [comment]
No it does not happen in singleplayer.

**Comment by bziemons** [comment]
Would you then kindly ask the server owner to provide the logs here?
Otherwise we will try to reproduce it on our own, but if we cannot do that, there is no way we could do anything for you.

**Comment by QORTEC** [comment]
I just tested this on my server, and I got the following errors:

**Server** [fml-server-latest.log]:
    https://gist.github.com/QORTEC/50224fd4c3359f8d0c42

**Client** [fml-client-latest.log]:
    https://gist.github.com/QORTEC/68518b24e54f6a93e149

To get the error I right clicked on the Crafting Module and attempted to set a Satellite Pipe.
Nether the client or the server crashed. The client was disconnected form the server.

If you need the full logs I can upload them, be warned the full server logs are very large its not for the faint of heart.

**Versions:**
Forge: 10.13.4.1448
Buildcraft: 7.0.16
LogisticsPipes: 0.2.17

**Comment by davboecki** [comment]
@QORTEC Thank you, that should be all we need. But looks like we will have to disable setting satelite pipe id's in hand. This currently doesn't work because it tryes to cycle trough all connected Satelite pipes but in hand there arn't any connected pipes.

**Comment by JasonMcRay** [comment]
I can confirm this issue still present in 0.9.3.68.
Wouldn't be possible to allow setting "any" Satellite ID in hand? And if plugged into the chassis pipe in network it will either stay as you set it (if that satellite ID pipe exists) or be reset to Off  (if it will not find any Satellite ID pipe)?
