### ISSUE TITLE
bug at the firewall pipes an totaly world was killed and nothing time you can load it again

### ISSUE THREAD

**Issue by Mastergeneral97** [RS485/LogisticsPipes#744]
Die firewall pipes von logistic pipes sind buggy sie verursachen einen absturz wenn man items oder ähnliches darüber leitet auch in Kombination mit craften oder ähnliches über die pipes jegliches craften über firewall rohre egal ob erlaubt oder verboten funktioniert nicht das spiel crashed und die welt ist nicht mehr lad bar das problem dabei ist irgentwie items normal gehen aber sobald irgentwas mit crafting statfindet stürzt es ab aber als fehler ist ticking entity block firewall pipes logisticpipes genannt und die welt ist nach dem bug nicht mehr ladbar und vorhanden ist der bug bei beiden versionen der neuesten 7 logistic pipes version und der neuen 6 logisticpipes version für 1.7.10

**Comment by DarknessShadow** [comment]
Einfach mal ohne Punkt und Komma schreiben ... perfekt.
Bei so einem Bug ist glaub ich ein CrashReport immer sehr hilfreich.

**Comment by hron84** [comment]
Could you please re-phrase your bug report in English? LP has a staff who can speak German, however it's not true for all people. Please help their work with an english bug report.
Also, please include following informations to your bug report:
- Exact Logistics Pipe version (e.g. 0.9.1.143)
- Exact BuildCraft version if you use BuildCraft
- Exact Forge version
- A screenshot about your setup
- A crash report if it is possible.

Every single piece of information you share with us can improve the speed of solving your annoying problems/bugs.

**Comment by Nex4rius** [comment]
https://github.com/JasonMcRay/InfiTech-1.7/issues/305#issuecomment-124251446

**Comment by bziemons** [comment]
Should be fixed in https://github.com/RS485/LogisticsPipes/commit/e2111489f76e3f7384b9eb75c00a6ba87370e556.
