### ISSUE TITLE
Fluid Crafting

### ISSUE THREAD

**Issue by Nex4rius** [RS485/LogisticsPipes#745]
Right now we can only use fluids (with Fluid Crafting Uprade) as inputs but not as outputs in crafting recipes.
It would be good to craft fluids (molten metals are requires in some recipes).

Some recipes need filled cells instead of the liquid which is why a "inverted" Fluid Container Supplier would be good or alternatively a crafting table that allows those recipes using a liquid instead of filled cells.

**Comment by bziemons** [comment]
Sounds like #635?

**Comment by Nex4rius** [comment]
Oh .... I did not see that
