### ISSUE TITLE
Crash when using GregTech cells and container supplier pipes

### ISSUE THREAD

**Issue by 123FLO321** [RS485/LogisticsPipes#749]
http://pastebin.com/XNaw860W

**Comment by hron84** [comment]
Could you please try to upgrade your LP to the latest 0.9.1.143? You can grab this from [here](http://ci.thezorro266.com/job/LogisticsPipes-0.9-mc17-bc6.4/lastSuccessfulBuild/artifact/build/libs/logisticspipes-0.9.1.143.jar)

**Comment by 123FLO321** [comment]
it actually corrupt your save file.
And yes still happening in newest version

**Comment by 123FLO321** [comment]
http://pastebin.com/ixM7Es7Q (LP 0.9.1.145)

**Comment by davboecki** [comment]
What forge version do you use?
Please try using forge 1448.

**Comment by 123FLO321** [comment]
"FML: MCP v9.05 FML v7.10.85.1272 Minecraft Forge 10.13.2.1272 151 mods loaded, 151 mods active"
I'll try once i am back home at my pc (about 8h)

**Comment by bziemons** [comment]
@123FLO321 could you please tell, whether the Forge update worked and solved this issue?

**Comment by 123FLO321** [comment]
I had trouble updating my ModPack to MinecraftForge 1448 since Forge 1445-1481 breaks GT Multiplayer.
So i only installed IndustrialCraft 2.2.756 GregTech 5.08.25, BuildCraft 6.4.9 and Logistics Pipes 0.9.1.146.

And yes it still crashes.

http://pastebin.com/2SJkJkbM

Somehow new render is broken. If i change it in the logstics pipes controller it doesnt apply. All other settings apply.

**Comment by 123FLO321** [comment]
Also, the crafting clean up should possibly pull items after every single item because machines could get stuck and you need a huge buffer when requesting lots of items at once.

For example: 

GT Plast Furnace: (2 Output slots)
1 Iron --&gt; 1 Steel + 2 small coal dust.

64 Iron --&gt; 64Steel + 128 small coal dust.
It will craft 32 Steel but after that the coal dust blocks the second output so it cant craft more steel.

under 32:
[0 Steel][x Dust]
over: 32
[x Dust] [64Dust]

**Comment by bziemons** [comment]
I don't think this applies to the most recent versions of LP anymore.
