### ISSUE TITLE
AE Power Integration

### ISSUE THREAD

**Issue by AlgorithmX2** [RS485/LogisticsPipes#75]
It appears that LP won't use an ME Interface for power unless its placed on the sides of the ME Interface ( the top and bottom do not work ).

I'll have a rv11 build with integration out soon, but I figured it might be obvious as to why that is.

**Comment by AlgorithmX2** [comment]
Also forgot, is there a way I can check to see if LP has power disabled so I can ignore LP's power if it isn't enabled? if not I can add a Config option on my side I suppose. Just trying to cover the bases.

**Comment by davboecki** [comment]
Have you used a Basic Pipe on the side of the ME Interface?
There is no way to get the config option through the API right now. You can either use reflection to access LPs Config class directly or i can add an method to the API if you want.

**Comment by AlgorithmX2** [comment]
Yes, the basic pipe is what I used to transfer power, it works fine on the sides, just not on the top or bottom, I figured this has something to do with the Power Junction in LP.

I'll just include some config options in AE to manage the power sharing and leave it up the the users.

**Comment by davboecki** [comment]
Yes the Basic Pipe is coded to only take power from the sides. Not the Power junction itself. Is that a problem?

**Comment by AlgorithmX2** [comment]
It just seems odd as in this case they are pulling power from a ME Interface instead which looks the same on all sides. I suppose I can explain it when I explain the feature but I have a feeling when people start using the feature they will quickly be asking for the "bug" to be fixed.

**Comment by davboecki** [comment]
I will see what i can do to get around this problem.

**Comment by ArtForz** [comment]
Implemented in Dev 534, basic pipe can get powered from non-powerjunction power provider on any side.
