### ISSUE TITLE
crafting with tools

### ISSUE THREAD

**Issue by Nex4rius** [RS485/LogisticsPipes#750]
Crafting with a tool works fine as long as the recipe only uses 1 tool but when a recipe needs 2 tools it does not work anymore.
Gregtech has lots of recipes with 2 or more tools (Maintenance Hatch has 8 tools in its recipe).

logisticspipes-0.9.1.15
(gregtech_1.7.10-5.08.24 if thats important)

<a href="http://imgur.com/HKqAp1P"><img src="http://i.imgur.com/HKqAp1P.jpg" title="source: imgur.com" /></a>
<a href="http://imgur.com/FUcM0uW"><img src="http://i.imgur.com/FUcM0uW.jpg" title="source: imgur.com" /></a>
<a href="http://imgur.com/b251Tvo"><img src="http://i.imgur.com/b251Tvo.jpg" title="source: imgur.com" /></a>

**Comment by Nex4rius** [comment]
Actually I think I made a mistake.
Recipes with 1 tool worked when I pressed OreDict IgnDamage IgnNBT and OrePrefix but some recipe with multiple tools dont work then.
They only work when only IgnNBT is on nothing else which is strange either work always with everything turned on or not.

**Comment by bziemons** [comment]
I have no idea what the problem is. I use the normal LP crafting table with the tools being supplied by a supplier pipe. The tools are used in the actual recipe, but do not show up in the crafting pipe, as you have shown it in your screenshot. That simply works for me.

**Comment by Nex4rius** [comment]
1) I closed this because if its only set to ignore NBT it works perfectly :D (and not just click all 4 like I did)

2) I tested a bit in sp and if the tools are set to ignore NBT and oreprefix AND are in the wrong order in the crafting tables storage space then it doesnt work

This does not work and it does not matter how long I wait
<a href="http://imgur.com/cVn03qG"><img src="http://i.imgur.com/cVn03qG.jpg" title="source: imgur.com" /></a>

But this does work perfectly
<a href="http://imgur.com/jhw35SZ"><img src="http://i.imgur.com/jhw35SZ.jpg" title="source: imgur.com" /></a>
