### ISSUE TITLE
Crafting Sign Creator

### ISSUE THREAD

**Issue by Nex4rius** [RS485/LogisticsPipes#751]
It does not work with crafting modules.
Please make them work with crafting modules.
They could just show the first crafting module and not all.
(mk2 chassis + crafting + acitve supplier for recipe with tools)

logisticspipes-0.9.1.15

**Comment by bziemons** [comment]
Not going to happen, as there can be too many exceptions with several crafting modules or none at all.

**Comment by Nex4rius** [comment]
You could make it that the crafting sign works on a chassis pipe if there is an attached crafting table and then it displays the recipe from the crafting table and does not care for any modules inside the chassis pipe.

**Comment by Nex4rius** [comment]
Hm..ok next idea:

You could let us specify what item is the output on the signs if they are rightclicked on a pipe thats not a crafting pipe so that it wont check anything at all.
Because that would be better than attaching regular signs.
<a href="http://imgur.com/GNjh1ZR"><img src="http://i.imgur.com/GNjh1ZR.jpg" title="source: imgur.com" /></a>

**Comment by hron84** [comment]
@DarknessShadow regardless what devs respond: I recommend you to check new BiblioCraft Fancy Signs, it allows not only to write anything on the sign but it also allows to put an item picture to it (IIRC it does not take the item).

**Comment by bziemons** [comment]
Or use item signs instead of crafting signs. Sneak-right-click in the air with the Crafting Sign Creator.

**Comment by Nex4rius** [comment]
@theZorro266 
NICE its already in the game :)
btw it would be good if this feature would be documented somewhere ^^

**Comment by hron84** [comment]
@DarknessShadow it's up to you too. Write a blogpost, make videos, spread news.
