### ISSUE TITLE
Multiple Crafting Cards 

### ISSUE THREAD

**Issue by 123FLO321** [RS485/LogisticsPipes#756]
If you use multiple cards into crafting a chassi and request for example 3 Iron and Gold 3 while the output is 9 crafting the pipe will request 3 gold then 3 iron them 6 gold and finally 6 iron
This is anoying in machines with 1 output since there are quiet 6 gold left in thr machine but the pipe waits for 3 iron and then get stuck .

Not really a bug but Should defenitly get changed .

**Comment by bziemons** [comment]
I do not understand that really, but regarding crafting pipes/modules and the output of machines: the crafting pipe/module needs to take the output item out of the adjacent machine. So the machine is not allowed to automatically output into the system.

Maybe you give us a hint about what recipes you are using in your modules, which machine that is and what exactly happens.

**Comment by 123FLO321** [comment]
For example

2 Recepies for GT wiremill (1 ingot = 3 cables)
You request 2 gold and 2 copper cables at the same time
It will put 1 gold ingot in the machine
The machine will craft 3 cables
But LP will only pull out 2 gold wires
Then LP will put 1 copper ingot in the machine but it cant get processed because there is still 1 cable in the machine
It would pull the extra gold cable after the 2 copper cables are done. But that will never happen since The GT wiremill only has 1 output slot.

**Comment by bziemons** [comment]
Ah okay, I understood that. Thanks.

Edit: might be a duplicate to #450

**Comment by SonOfTheStars** [comment]
Havent yet had any issues like this...
Everything worked smoothly for me with up to 8 Modules in the MK5 Chassi.

Though ive been allways using MK3 Modules for their internal buffer.
Cant confirm the behavior on the MK3`s. MK1 and 2 might be a different story.

No problems with Extraction on MK3's as well...

**Comment by 123FLO321** [comment]
That only happens when the machine crafts more than 1 item at once.

**Comment by SonOfTheStars** [comment]
then you have the Problem I just stated, if you use a MK3 Crafting Card, you will not have such a problem.

**Comment by bziemons** [comment]
Well, it would still be a bug.

**Comment by SonOfTheStars** [comment]
I think its because the Item cannot go in, the Crafting request is going on, but the Items required are send back to the Storage and are forgotten about.
It seems not to re-issue the request when there is space in the inventory again

**Comment by 123FLO321** [comment]
No. It leaves the extra Item in the machine and doesn't pull it out until all other none-extra-craftings are done.

**Comment by 123FLO321** [comment]
Also, the crafting clean up should possibly pull items after every single item because machines could get stuck and you need a huge buffer when requesting lots of items at once.

For example:

GT Plast Furnace: (2 Output slots)
1 Iron --> 1 Steel + 2 small coal dust.

64 Iron --> 64Steel + 128 small coal dust.
It will craft 32 Steel but after that the coal dust blocks the second output so it cant craft more steel.

under 32:
[0 Steel][x Dust]
over: 32
[x Dust] [64Dust]

**Comment by SonOfTheStars** [comment]
Well thats less of a problem with LP...
You should just hook up an Extractor with filter for the secondary items and youre fine.

**Comment by 123FLO321** [comment]
I know thats what i am doing since the dust is usless. 
If the dust would be usefull and you want to autocraft it that might be a problem

**Comment by SonOfTheStars** [comment]
Unfortunatly, the current System only Supports single Item Results. Secondary can allways be pumped out and stored.
And I don't see a particular reason to change that...

**Comment by hron84** [comment]
@Bitterholz I think it is not 100% true in this form. We already have a byproduct upgrade.

**Comment by 123FLO321** [comment]
Oh sorry. I meant bybrodact upgrades not clean ups.

**Comment by SonOfTheStars** [comment]
@hron84 Guess thats true but you cannot currently upgrade Modules :/
Wich is a sad thing but kind of Logical. After all, there are ways to fix this Problem. Be it Byproduct Upgrades or Simply an Advanced Extractor... 

BTW there arent any recipes for Byproduct Upgrade yet am I right?
TO THE PULLREQUEST!!!

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/fa06994445e4e90659ddc74192e4b89cc0ec4c44
