### ISSUE TITLE
[Suggestion] Wildcard itemsink module

### ISSUE THREAD

**Issue by michelegargiulo** [RS485/LogisticsPipes#760]
What about a next tier of the oredict itemsink module that is able to request items based on a wildcard filter?

What I'm tinking about is a module very similar to The oredict one, With a similar GUI, Just With typing input that allows for flags like ingot\* and It will request any item With An oredict entry that starts with ingot, so all The ingots from all The mods will be Sent to The pipe containing such module. It may be useful for ore processing (ore*) or oredict conversion (*copper) to Sent all The types of copper nuggets/ingots/blocks/ore/plate to An automatic oredict converter.

**Comment by SmokeyTheBandicoot** [comment]
Sorry, I didn't know that The asterisk was used for italic text formatting. The words in brackets should have been "ore+" And "+copper" respectovely, With The asterisk instead of The plus.

**Comment by davboecki** [comment]
See: https://github.com/RS485/LogisticsPipes/issues/231
