### ISSUE TITLE
Crafting related upgrades NOT working with crafting cards 

### ISSUE THREAD

**Issue by Casper-O** [RS485/LogisticsPipes#764]
It is not possible to insert crafting related upgrades (like fluid crafting upgrade) into chassis that contains one or more crafting cards at the most recent build, I don't know if it has been possible since I just moved to LP 0.9 yesterday but could not find anything that said it was not implemented yet

**Comment by davboecki** [comment]
That's by design. If you want to upgarde crafting tasks use the pipes.

**Comment by Casper-O** [comment]
That is fair :)
