### ISSUE TITLE
[Request] API for Tile Entities which can connect spatially separate logistics pipes

### ISSUE THREAD

**Issue by DarkholmeTenk** [RS485/LogisticsPipes#765]
I was hoping for something along the lines of

``` java
public interface ILogisticsConnector
{
  /**@return the coordinates of all of the pipes which can be reached through this connector**/
  public Set<Coordinate> getConnectedPipes();
}
```

for use in my TARDIS mod. Basically, I want to be able to connect at least 2 spatially distant logistics pipes systems without having to have 2 power providers and inventory connectors. Apologies if this is already doable, but I couldn't spot any way to do it :P

**Comment by bziemons** [comment]
not a bad idea :+1:

**Comment by SonOfTheStars** [comment]
I can only say: :+1:

**Comment by SonOfTheStars** [comment]
Do we still have the Code for the old Teleport Pipes mod? would probably be good to take a look at for this

**Comment by DarkholmeTenk** [comment]
I was thinking more along the lines of ILogisticsConnector provides a set of other logistics pipes positions and the logistics network teleports items to the most appropriate one. As far as I remember, teleport pipes acted like dumb buildcraft pipes and just routed to a random one.

**Comment by bziemons** [comment]
Right, because there was no logic in teleporting items in AP.
This on the other side makes us teleport the item basically.
What about a second Method, but on your side:

```
/** @returns true, if the item was accepted and false, if rejected */
public boolean passItemStack(ItemStack itemstack, Coordinate targetPipe);
```

And you can inject items via `buildcraft.api.transport.IPipeTile#injectItem(ItemStack, boolean, ForgeDirection, EnumColor)`, where `IPipeTile` is on our `LogisticsTileGenericPipe`, the basic TileEntity. If you do not want to include the BuildCraft API, just use Reflection to get the method `injectItem` from our TileEntity

**Comment by DarkholmeTenk** [comment]
Seems reasonable, on top of the other side.
What about transferring LP and RF/EU power?

**Comment by bziemons** [comment]
That's another question. With allowing that the interfaces will need to grow a little more. I put this on hold and will talk with @davboecki about implementing the interfaces with power transfer. We will be posting a comment, when we got something worked out.

**Comment by DarkholmeTenk** [comment]
:+1: Sounds good, been using this version of Logipipes since 1.4.5 and I miss my big distant logistics system :3

**Comment by SonOfTheStars** [comment]
@DarkholmeTenk if you really need that ability, you CAN achieve this by using Thermal Expansion Tesseracts

**Comment by bziemons** [comment]
@Bitterholz that is not the point. He wants integration with his own mod. This is not about doing something ingame.

**Comment by SonOfTheStars** [comment]
Well he stated he misses Distance Logistics...wich tesseractsI assume is Ingame.

**Comment by SonOfTheStars** [comment]
But Anyways the API is a great idea, makes Integration far easier

**Comment by DarkholmeTenk** [comment]
Well the TARDIS can already handle AE networks, but that's so boring looking compared to logistics :3

**Comment by bziemons** [comment]
I am working on API code at the moment to finally make this happen. It definitely is not as easy. Also we don't have any hard BC dependency anymore, so we wont use their functions.
