### ISSUE TITLE
Minecraft freezes when lots of items go through a logistic pipe

### ISSUE THREAD

**Issue by michelegargiulo** [RS485/LogisticsPipes#771]
I placed a single Buildcraft Mining Well down, connected a few basic logistics pipes, one of which is default-routed to an ender chest for item sorting. As soon as the mining well gets powered and items starts flowing through the pipes minecraft Completely freezes.It doesn't crash, but always freezes and the server runs lots of ms behind. The console every now and then spams "the server is running x ms behing, y ticks will be skipped or something like that, where x and y increase over time. A single Mining well, placed in the twilight forest (tested in aroma1997's mining world and ExU deep dark with the same results), mines about a stack of items, that should go into the pipes. Both with powered or unpowered pipes minecraft freezes. No crash, no crash report, nothing in the log except the spam.

It seems strange because it didn't happen before.

Tested with:
Forge 1492
Logistics pipes 0.9.2.30 and 0.9.2.19
Buildcraft 7.0.20
Buildcraft Compat 7.0.11

Let me know if you need other Mods used and versions. I'm using fastcraft 1.22 test build13 if it matters, which I always used before and after it started freezing

**Comment by michelegargiulo** [comment]
Hey, I'm sorry I tried with Thermal Expansion Warp Itemducts (non opaque) and it frozen my game as well. Sorry If I tried now, only after having reported this issue, but now I think it is not on Logistics pipes side. I'll try using an older version of Buildcraft. Now trying with 7.0.18. No idea of what is causing this issue. My apologyzes.

**Comment by bziemons** [comment]
okay, thanks for letting us know.

**Comment by hron84** [comment]
@SmokeyTheBandicoot I recommend you to try run Opis against your server and check results. Also, check pure (opaque) itemducts too. I think it shouldn't a BC issue... I used a quarry with these stuffs (that machine emits **way** more items than a single mining well) and I had no freezes.

**Comment by michelegargiulo** [comment]
@hron84 The problem is that I put a single Ender chest on top of it and it worked fine. But if I place 16 each with its own separate Ender chest I get The freeze. Same thing with a single mining Well, with a single logistics pipe and a single Ender chest. I Tried using The lp first, and it frozen as soon as the items start flowing. Then i tried w/o The pipe and it worked, so i reported here, but then I tried itemducts and even Ender chest only. I didn't try leaving The well alone, letting it throwing items in The air, though

**Comment by bziemons** [comment]
So closed, as the issue seems unrelated to LP.
