### ISSUE TITLE
Build 31 client sync errors.

### ISSUE THREAD

**Issue by xannor** [RS485/LogisticsPipes#772]
I upgraded my install from build 29 to 31 and upon logging into my local server (not single player) all of my logistics pipes were invisible, and I could not interact with them. I could not move through nor place blocks in the space where they should be, and the system was till working on the server side because automatic functions where happening, I just could not see them nor use them. Stepping back to build 30 fixed this issue. I tried restarting both the client and server at separate times and ensured that both had the same config files. Only Logistics pipes pipes seemed to be affected, buildcraft and thermal dynamics pipes were fine, and the logistics machines where fine.

**Comment by bziemons** [comment]
whoops, yeah I can think of what went wrong there. Will fix soon.
