### ISSUE TITLE
Display Bug at chassis pipe / golden transport pipe intersection

### ISSUE THREAD

**Issue by lazerous42** [RS485/LogisticsPipes#774]
I am experiencing an issue that occurs when chunks containing logistics pipes are reloaded into memory.  The occurs during the initial launch of the game, as well as when the chunks are un/reloaded.  What happens is that in locations where I have normal buildcraft pipes attacking to logistics chassis pipes, the transport pipes surrounding the chassis pipes will appear as cobblestone support pipes.  This is a graphical effect only, the pipes still function normally but it is quite ugly.  The effect can be cleared out by forcing a bock update.  For example, placing a block next to the offending pipe will restore the correct textures.  I have included screenshots of the effect, and removing the effect by placing a torch (Top image is the corrected one).
![fixed with torch](https://cloud.githubusercontent.com/assets/13743079/9191331/ec9569c0-3fcd-11e5-9bc0-89dc78f5a8ff.png)
![golden pipe bad 1](https://cloud.githubusercontent.com/assets/13743079/9191330/ec924934-3fcd-11e5-8b83-db8d95c87d00.png)
![golden pipe bad 2](https://cloud.githubusercontent.com/assets/13743079/9191332/ec961d5c-3fcd-11e5-961e-5075df27dc7d.png)

**Comment by bziemons** [comment]
And you are using which BC, LP, Forge versions?

**Comment by loordgek** [comment]
and do you have optifine

**Comment by lazerous42** [comment]
Here are the versions of the mods I am using that are relevant to this
issue.

Buildcraft: buildcraft-7.0.20.jar
Logistics Pipes: logisticspipes-0.9.2.33.jar
Forge: forge-1.7.10-10.13.4.1448-1.7.10-universal.jar
Optifine: OptiFine_1.7.10_HD_U_B8.jar (_Not_ using Threaded chunk loading)

I tried out the newest optifine version with my pack but I was getting that
"see through the world" chunk loading bug and other graphical anomalies
related to JABBA barrels so I downgraded back to the B8 version that has
worked well for me (so far).  I'll try removing Optifine temporarily to see
if I still get the display issue.

**Comment by lazerous42** [comment]
Oik, I just ran a test pulling out Optifine.  The issue persists without
it.  also, I am using an NVIDIA GeForce GTX 680 with the latest drivers
(v353.62).  I am also using Fastcraft (fastcraft-1.21.jar).  Just let me
know if you need more information or have some test you would like me to
run.

**Comment by lazerous42** [comment]
One more thing, it looks like this is only affecting my golden pipes (where
they join to logistics pipes).  I just looked at my power room where I have
charcoal being pumped into dynamos by logistics pipes.  The source end of
the connection has gold pipe to accelerate the charcoal, but after a few
gold pipes I'm using quarts for the rest of the distance.  The intersection
between the quartz pipe and chassis MK1 pipes are not affected.  For
reference sake, the affected pipes are chassis MK2 pipes and one MK5 pipe

**Comment by lazerous42** [comment]
One further investigation, the MK5 pipe I have is not displaying the bug
(along with the MK1).  So only the MK2 chassis pipes are doing this.

**Comment by lazerous42** [comment]
Addendum 2: It looks like some of the basic pipes exhibit this problem as
well, not just chassis MK2 type pipes.  Maybe the type of pipe doesn't
actually play a role in causing the issue.  Sorry I keep sending messages
with occasionally conflicting information.  I am a programmer by trade
myself so I am naturally inclined to hunt for patterns in how bugs
manifest.  Just trying to help with the debugging process, I don't intend
to be a bother.
