### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by davboecki** [RS485/LogisticsPipes#778]
https://gist.github.com/davboecki/37ab207f5c385c4e5ef9

**Comment by hron84** [comment]
NPE... NPE everywhere! :smile:

**Comment by michelegargiulo** [comment]
Yeah, just got the same crash returning from the Twilight forest https://gist.github.com/SmokeyTheBandicoot/8a1bd49ef569a381118d

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/db9a750c4a043203645e050bac32429bffb324b4
