### ISSUE TITLE
Major Craft Issue

### ISSUE THREAD

**Issue by QORTEC** [RS485/LogisticsPipes#779]
**angelnc** mentioned a major crafting issue on IRC and I can confirm.

**Issue**:
- NEI doesn't show any crafting recipes
- You cannot craft any recipes in the vanilla crafting table (tried a dozen pipes/module recipes form memory)

The only exception to the above is you can only converting logistics blocks to basic pipes. (recipe can be seen by right clicking on basic fluid pipe in NEI)

**Versions**:
Forge: 10.13.4.1448
Buildcraft Core: 7.0.20
Buildcraft Silicon 7.0.20
Buildcraft Transport: 7.0.20
LogisticsPipes: 0.9.2.33
CodeChickenLib: 1.1.3.138
CodeChickenCore: 1.0.7.47
NotEnoughItems: 1.0.5.111

**Comment by bziemons** [comment]
Sorry, couldn't reproduce that. Could you try again with CodeChickenCore version 1.0.7.46 ?

**Comment by QORTEC** [comment]
Same, cannot cannot craft and NEI not showing recipes.

Java: 1.8.0_51
CodeChickenCore: 1.0.7.46

Tried without NEI; still cannot craft.

**Comment by QORTEC** [comment]
The recipes only work if **Buildcraft Robotics** is present.

**Comment by QORTEC** [comment]
**Buildcraft Robotics** is a required mod add it to the pack.
