### ISSUE TITLE
Config Option for Barrel Insertion from anywhere

### ISSUE THREAD

**Issue by Flow86** [RS485/LogisticsPipes#78]
Hi,
I would like to have a configuration option to enable the Barrel-Inventory-Handler to insert items from any side (not only from top, but with default on "up-only").
Perhaps simply a list from which directions insertion will be allowed.

I have large "walls" of barrels and it would be really cool to have the pipes "hidden" behind.

But I know it should only be a config option.

**Comment by davboecki** [comment]
Thats what the sneaky upgrades are for.

**Comment by Flow86** [comment]
ahh! of course havent thought of that.
