### ISSUE TITLE
Problem with Logistics Pipes causing server to slow to a halt

### ISSUE THREAD

**Issue by sctjkc01** [RS485/LogisticsPipes#781]
I seem to be having an issue where my game slows to a halt when I make use of Logistics Pipes... on the server side.  Client-side rendering is just fine, however anything that involves game processing - opening inventories (including the player's), moving things around, entity updates, etc - stops.

There is no crash log to report with, as it doesn't produce one.  While the pack is based on Resonant Rise 3 and is approximately 200 mods wide, I've been able to stop a single-player game on a Superflat with only the following mods:
- LogisticsPipes (0.9.2.33 and 0.10.0.1, lags out on both)
- Thermal Expansion ([1.7.10]4.0.1)
- Ex Nihlio (1.38-40)
- Ender IO (1.7.10-2.2.8.381)
- Extra Utilites (1.2.6)

16 Ex Nihlio Crucibles, powered by lava, and fed by vanilla Hoppers.
The Crucibles have Liquid Provider Pipes on it, while the Hoppers have Item Suppliers on it (keyed to infinite cobble).
On one side of the crucibles, an Ex Nihlio transfer node is generating cobblestone into a Resonant Cache, which is being provided to the LP System via an Item Provider Pipe.
On the other side, 12 Magmatic Dynamos face a bank of Vibrant Capacitors.  They have all three power augments inside each, and are fed via Liquid Supplier Pipes (keyed to 4000mB of Lava, Partial True, Minimum 1 Bucket).
The LP System is powered by a Logistics Power Junction directly on the capacitor bank.

![image](https://cloud.githubusercontent.com/assets/1090204/9291837/cc3cddd6-43a4-11e5-8bf6-d1c4d1ee1e42.png)

I can run around, fly, attract XP orbs, but only on the client side.  Everything comes to a dead stop on the server side.

If there's anything I can do, just let me know.

**Comment by SonOfTheStars** [comment]
Simillar setup, doesn't lag for me at all...

**Comment by sctjkc01** [comment]
Cross-commenting from [Reddit](https://www.reddit.com/r/FeedTheBeastCrashes/comments/3h5z6z/problem_with_logistics_pipes_effectively_stopping/)...

Opis is already installed, and its monitoring of the world comes to a complete stop as well. I can still interact with the interface, but all of the live output stops dead.
The tick time is nice and low when its working, approximately less than 10ms tick time. Soon as the one Provider Pipe to the Cobble is hooked up, dead stop. I could walk into the slime in the photo provided and it doesn't get pushed around.
Worth mentioning, I can still _pull Opis up_ via the /opis command.

**Comment by davboecki** [comment]
@sctjkc01 Do you know how to use visualVM. If so could you please profile minecraft with 20ms and upload the result.

**Comment by sctjkc01** [comment]
I don't know of VisualVM... but I think I can quickly get around it.  I'll just be a minute.

**Comment by sctjkc01** [comment]
So, I found out a few things, namely that A) **_I'm a dummy and didn't remove FastCraft first**_, and B) somehow it's possible to crash a Minecraft singleplayer server without crashing the rest of the game.  The server crashes and dumps me right back onto the main menu.

One moment as I test without FastCraft enabled.

**Comment by sctjkc01** [comment]
FastCraft's now removed, and yet I still come across the same issue.  [Here's a Sampling log, as requested](https://dl.dropboxusercontent.com/u/21179667/LP%20Issue%20781.nps).

Funny thing, everything was fine when the system idles.  And everything was fine when it was only routing items around (because I derped and didn't set up the Fluid Supplier Pipes on a fresh instance with the same mod set).  But as soon as I set one of the 12 Fluid Supplier Pipes, everything died.

**Comment by sctjkc01** [comment]
Additional things to list off:

Recreated build using a slimmed version of the same modpack.  Everything not related to the above-listed mods or their dependencies have been removed.  Used just a creative strongbox providing cobble instead of an ExUtil cobblegen:

![image](https://cloud.githubusercontent.com/assets/1090204/9297512/a54f81a4-446e-11e5-8e59-eb9aa43bc77e.png)

...and the server still dies.  I want to say that it's not the first Fluid Supplier Pipe that kills it, but in fact it's the second...

**Comment by SonOfTheStars** [comment]
Would you mind setting up nothing but 2 Fluid Supplier and a Provider between 3 Tanks of any kind. See if that crashes.

If not, perform the same Test with dynamos on the receiving end.
That way we Know if its inter mod related or purely an LP issue.

What I could imagine for your setup is the suppliers getting confused about such many Provider pipes.
Or the providers not likeing the fact they can pull from 2 seperate Sources each...

**Comment by sctjkc01** [comment]
I'm not certain if this is the test you're expecting, but this works:
![image](https://cloud.githubusercontent.com/assets/1090204/9298079/e3cd64f2-4476-11e5-99ac-32ef70ad93bb.png)
One Fluid Provider, one Fluid Supplier asking for 256B Lava.  Works just fine.
Adding a second Supplier and Resonant Tank doesn't stop it.

Switching Resonant Tanks for Dynamos doesn't change anything, the system still works fine:
![image](https://cloud.githubusercontent.com/assets/1090204/9298152/fb5b5e5c-4477-11e5-82e3-23a02b48675d.png)
( I did indeed start with only one dynamo at first - each Supplier is asking for 4B lava. )

Soon as I switch the tanks for Crucibles does the game lock up:
![image](https://cloud.githubusercontent.com/assets/1090204/9298183/7bf6ddfc-4478-11e5-8ae4-10d1c70c1912.png)
I guess this is an issue with just Ex Nihlio, then. That's good to know.

**Comment by sctjkc01** [comment]
The issue has been logged with [the dev(s) of Ex Nihlio](https://bitbucket.org/Erasmus_Crowley/ex-nihilo/issues/7/game-freezes-with-liquid-logistics-pipes).  Of note, three dynamos works fine on two Crucibles, but as soon as a fourth gets added, the game dies.

**Comment by hron84** [comment]
@sctjkc01 to make this valuable for Ex Nihilo devs, could you please try it out without LP, for example, with TD fluducts? And also with ExtraCells stuffs?

**Comment by sctjkc01** [comment]
@hron84 - I've done it with TD Fluiducts before.  The issue arose as I switched from TD Fluiducts to LP Fluid Supplier / Provider pipes.
