### ISSUE TITLE
Request Crafting when output is more than 1

### ISSUE THREAD

**Issue by JasonMcRay** [RS485/LogisticsPipes#792]
I am having slight issue with Crafting Modules attached to machines. When an item processed in the machine makes 2 or more "produce items" and I request number of items which will lead to excess "produce item" the machine will keep the excess, and will get stuck.

For example Wiremill from GregTech turns 1 ingot into 2 wires. I have two Crafting Modules attached to the machine. In Crafting Module A I have 1 Copper Ingot input, 2 Copper Wires output. in Crafting Module B I have 1 Tin Ingot input, 2 Tin Wires output.

When I request only 1 Copper Wire, all is fine. I will get 1 Wire and the 2nd is pulled out into the main storage (ItemSink module with Default Route: YES)
Problem happens when I request 1 Copper and immediately after 1 Tin Wire. It will process the Copper, but will extract only 1 Wire for me, and the second made will get stuck in the machine.

If I will add to the machine some extraction method (for example extraction pipe), it will extract the excess, but if the extraction ticks in and takes out what should be considered as crafting process it will not see the crafting process happened (because the Crafting Module, did not pulled out the item), making it stuck again, because its waiting for the item to come out via the Crafting Module.

Not sure if this can be viewed as a bug or I am just missing something. (of course sipmlest solution would be to make 1 machine for 1 recipe, but that would be bit overkill).

**Comment by SonOfTheStars** [comment]
Ive experienced this as well, it seems to not remove the last Excess Items if another request is pending! Especially noticeable when using MK III Crafting Modules

**Comment by davboecki** [comment]
This has been fixed.
