### ISSUE TITLE
Server Crash with Thermal expansion tubes

### ISSUE THREAD

**Issue by Michal-MK** [RS485/LogisticsPipes#794]
Placed unrouted pipe next to an Itemduct.
The server does not start up.

https://gist.github.com/MoonKill/1019c5bfa77acc428954

**Comment by davboecki** [comment]
Versions of all involved mods?

**Comment by Michal-MK** [comment]
Forge 1448
logisticspipes-0.9.2.33.jar
CoFHCore{1.7.10R3.0.3}
ThermalDynamics 1.7.10R1.1.0
ThermalFoundation: -[1.7.10]1.2.0-102
ThermalExpansion: -[1.7.10]4.0.3B1-218

If I missed anything, all the mods are listed at the end of the crash log with their version number.
