### ISSUE TITLE
Wrong type for fluid request pipe in ComputerCraft API

### ISSUE THREAD

**Issue by tsani** [RS485/LogisticsPipes#795]
I'm trying to interface LogisticsPipes with ComputerCraft, to programmatically shuffle fluids around. Calling `getType` on a wrapped Fluid Request Pipe simply returns `LogisticsPipes:Normal` as opposed to `LogisticsPipes:Request` or `LogisticsPipes:FluidRequest` (or anything to that effect). As such, nothing can be requested by the computer.

Are fluid pipes supported ?

I'm using ComputerCraft 1.74 and LogisticsPipes 0.9.2.29.

**Comment by davboecki** [comment]
There currently is no computer integration for fluid pipes. For that reason everything defauls back to the next type of pipe which has comupter craft commands, in this case that's the default pipe.

**Comment by tsani** [comment]
I understand.

I've been looking to get my hands dirty with Minecraft mod development; I have a background in software engineering. I might try to implement the integration for fluid pipes. Is it alright if I bug you on IRC with questions on how to get LogisticsPipes to build ?

**Comment by davboecki** [comment]
Sure, and if I'm not there maybe someone else will be able to help you as well.
