### ISSUE TITLE
Weird unnamed blocks

### ISSUE THREAD

**Issue by tristanrussell2000** [RS485/LogisticsPipes#796]
Opis reported many unnamed blocks, which identified as being from Logistics Pipes. I am also getting a lot of error events and wondering if the blocks are the cause of that. 

http://imgur.com/elev0l6,zlkkulT,MJSwa2i#1

**Comment by hron84** [comment]
@ironclaw2000 could you please add affected LP and Forge versions to your report? It would be good because it can help developers to find the problem and solve it for you. Thanks.

**Comment by SonOfTheStars** [comment]
The Unnamed blocks refer to the Unrouted Pipes as it seems...at least they get more if you place more

**Comment by davboecki** [comment]
I added the name for the pipe Block. and we don't cause that ERROR afaik.
