### ISSUE TITLE
And another NPE.

### ISSUE THREAD

**Issue by davboecki** [RS485/LogisticsPipes#797]
https://gist.github.com/davboecki/408a4704c4bec78e741f

**Comment by hron84** [comment]
It seems like NPEs chasing you... :smile:

**Comment by SonOfTheStars** [comment]
NPE's are any Devs Nemesis

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/db9a750c4a043203645e050bac32429bffb324b4
