### ISSUE TITLE
Visual bug when zooming out at crafting progress tree

### ISSUE THREAD

**Issue by 1n5aN1aC** [RS485/LogisticsPipes#799]
See image below:

Logistics Build #45.

Take a logistics request table,
install a crafting progress upgrade.
Request something that takes several steps.
Click on (more) to see the crafting progress tree.
Zoom out using the scroll wheel.

After which, you should see:
![Image Showing it](https://i.imgur.com/ExJnzqf.png)

**Comment by davboecki** [comment]
Fixed by https://github.com/RS485/LogisticsPipes/commit/697feeba6e8e423b0e30fcd1c178f09dca2078e7

**Comment by 1n5aN1aC** [comment]
Thanks!
