### ISSUE TITLE
[Enhancement] No NEI Recipe for the Mod-Based Itemsink

### ISSUE THREAD

**Issue by thatsIch** [RS485/LogisticsPipes#8]
5 Pages on NEI just how to reset up to 9 Mod-Based Itemsinks
- http://puu.sh/1WSv1
- http://puu.sh/1WSwF
- http://puu.sh/1WSwW
- http://puu.sh/1WSx5
- http://puu.sh/1WSxm

there is no actual way to craft them yet though they work just fine.

**Comment by MrTJP** [comment]
They are still in debug. The reset recipes are added automatically, but the crafting recipe isn't added because it isn't bug free yet.

**Comment by davboecki** [comment]
Like MrTJP saied. There is no recipe for the module jet. Those givven recipes are added automaticly for modules that save their state when taken out of an chassie pipe to allow to stack them again. Will add a recipe when the module has been tested a little bit more.

**Comment by MrTJP** [comment]
About that, dav, I think it's enough to have just one for one. I don't think there is a need to have multiple recipes like that because you can just put in a stack and shift click.

**Comment by davboecki** [comment]
If you have several unstackable Modules i like to put them all together into the crafting table and take them out at once. And they are added automaticly so there shouldn't be any problem.

**Comment by MrTJP** [comment]
O yea. There unstackable. Derp.

**Comment by ArtForz** [comment]
Dunno how feasible, but couldn't we hide [most of] the reset recipes from NEI?

**Comment by MrTJP** [comment]
thats what i was thinking.  and the recipes for dying the remote orderer shows a whole bunch instead of just cycling to the oredict.

**Comment by ArtForz** [comment]
For orderer recoloring using "any" meta cuts down massively on the recipe #s ...

**Comment by ArtForz** [comment]
Both of those implemented in #9, could be easily modified to not have reset recipe show up at all in NEI by implementing IRecipe instead of extending ShapelessRecipes in ShapelessResetRecipe
