### ISSUE TITLE
Idea: Foreground HUD Window under cursor

### ISSUE THREAD

**Issue by Flow86** [RS485/LogisticsPipes#80]
Hi,
if you have a close line of logistic pipes (i.e wall of chests/barrelst/whatever connected to a cascade of chassis) you can't read all huds from a specific location.

![pic](https://f.cloud.github.com/assets/656249/569068/05ccb32a-c6f0-11e2-80d0-2009563a0a28.png)

If the "active" hud would be drawn in the foreground on mouseover, you can view the partly-hidden huds with your cursor

**Comment by davboecki** [comment]
Added sneaking to hightlight pointed HUD.
