### ISSUE TITLE
Depending on LP from another mod?

### ISSUE THREAD

**Issue by knexer** [RS485/LogisticsPipes#800]
I can't set up a proper development environment (for Buildcraft Compat) with LP included as a dependency.  If I pull in the dev jar, LP refuses to start up (I think its coremod isn't being loaded for some reason: http://pastebin.com/GWTfVSUV).  If I put in the obfuscated jar, MC starts but the first time an obfuscated function is called MC crashes since that function's actually deobfuscated in my runtime (http://pastebin.com/5JANZRGV).

For the record - I have been able to set up a working LP environment.  I can proceed with the work in LP rather than BuildcraftCompat, at least for now.

**Comment by SonOfTheStars** [comment]
Have you put the Logistics Pipes Dummy jar in the Mods folder of your dev environment?

**Comment by knexer** [comment]
That did fix it, brilliant, thank you.  Noting this in README.md would be helpful (I see something along these lines was removed in 5cec22246dd7f5875670aad861e06f1b47c98ab4)

**Comment by SonOfTheStars** [comment]
Its actually stated in the Eclipse Log when youre launching the dev environment ;)
