### ISSUE TITLE
Internal LP gate triggers and actions are unavailable

### ISSUE THREAD

**Issue by knexer** [RS485/LogisticsPipes#801]
BC 7.0.19
LP 0.9.2.29

Internal triggers (e.g. the crafting pipe's "Waiting for Crafting") do not appear in the Gate GUI.  The sole external trigger, "Needs More Power" of Power Provider fame, works correctly.  The disable pipe action is also available.

**Comment by HadesDurin** [comment]
you should update lp to latest build which is 0.9.2.46
and after that you will see if it happens again or it is fixed

**Comment by knexer** [comment]
I can still reproduce on the tip of dev (afdef4abc)

**Comment by knexer** [comment]
And also on tip of stable-bc7 (697feeba6e8e423b0e30fcd1c178f09dca2078e7) which corresponds to 0.9.2.46.

**Comment by bziemons** [comment]
Might be an incompatibility to BC7.

**Comment by Leytek** [comment]
Please, pay attention to this issue. I miss this triggers so match, especially "Waiting for crafting". I haven't enough knowledge in Java and Minecraft modding, so i can't understand why TriggerProvider don't work correctly.

**Comment by bziemons** [comment]
Closing in favor of #1135
