### ISSUE TITLE
Connecting pipes

### ISSUE THREAD

**Issue by parkitka** [RS485/LogisticsPipes#803]
I Installed Logistic pipes and wanted to try it but I can`t connect normal gold pipe from build craft (or any other pipe from BC) to any of the logistic pipes. I was trying all of the combinations cobblestone pipe, stone pipe etc. I don`t know what is wrong. I have also "Industrial craft 2 experimaental" "Rei`s minimap and some others little mods. And also, craft guide and not enough items don`t show me how to craft those pipes.

**Comment by davboecki** [comment]
Versions of all involved mods?

**Comment by parkitka** [comment]
1.7.10

**Comment by parkitka** [comment]
![logistic problem](https://cloud.githubusercontent.com/assets/8067940/9747813/49c641a0-5680-11e5-8230-b7a1a9a8c756.png)

**Comment by SonOfTheStars** [comment]
Why are those mods of yours named so wierd? If you didn't rename them, youre not having original Files. Plus the Filesize is suspiciously small! Buildcraft is WAY bigger than just 1758 KB

Please do not use mods Distributed by sites like minecraft-mods or equal. These are not originals and can contain malicious content!
ALLWAYS use the Original Versions, Distributed by the Mods own Website, Minecraft-Forum or Curse!

**Comment by parkitka** [comment]
I didn`t rename them, I will check if it will help

**Comment by SonOfTheStars** [comment]
The question is: where did you download those mods from! Because those are NOT ORIGINAL FILES!

**Comment by parkitka** [comment]
9minecraft http://www.9minecraft.net/

**Comment by davboecki** [comment]
Don't use those Redisribution Webpages. They make money of other peoples work, they don't care for licenses, they sometimes distribute viruses and they always lie about versions. Use either the minecraft forum, curse or the mods original web page to download your mod.

**Comment by davboecki** [comment]
By the way my guess is that you have a serously outdated BC version. The LP version you are using requires BC 7 at least.

**Comment by parkitka** [comment]
Thanks for Help guys :)

**Comment by SonOfTheStars** [comment]
For latest BC builds, please Go here: http://mod-buildcraft.com/
For latest Idustrialcraft, check: http://ic2api.player.to:8080/job/IC2_experimental/
For latest NEI, check: http://chickenbones.net/Pages/links.html
For latest Iron Chests, check: http://files.minecraftforge.net/IronChests2/

These Sites are **ORIGINALS** and will allways provide you with safe, licensed and up to date Versions of the Mods! **Never Trust 9minecraft or something else**!

If you want improved Minecraft Performance, I recommend using: http://forum.industrial-craft.net/index.php?page=Thread&threadID=10820

Other great mods I recommend for your full Modding Experience:
**Thaumcraft**: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292130-thaumcraft-4-2-3-5-updated-2015-2-17
**CoFH Mods**: http://teamcofh.com/
**Tinkers Construct**: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2218638-tinkers-construct
**Extra Utilities**: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1443963-extra-utilities-v1-1-0k
**Botania**: http://botaniamod.net/

Hope this helps you to improve your Modded Minecraft Experience!

**Comment by hron84** [comment]
And, the most interesting thing: [list of the sites that are allowed or not allowed to provide mod downloads](https://github.com/VictiniX888/Illegal-Mod-Sites/blob/master/SITES.md)

**Comment by SonOfTheStars** [comment]
@hron84 arent all of those Sites actually illegal and could be shut down by law since they violate TOS of the mods?

**Comment by Nex4rius** [comment]
@Bitterholz lol "by law" now the big question which law exactly?
usa, german, french, spain, russian, chinese or from one of the other 200 countries?

It will never work because there will always be two new website up when you shut one down.

**Comment by hron84** [comment]
@Bitterholz no, check the description of the page. Some sites (these are scored to 1) are legal if the legal is means they uses the original download link of the mod. The #stopmodreposts collection is not makes difference between posting mods illegally or re-hosting mods or just providing the final URL instead of adf.ly or similar pay-for-click link shorteners, all category is listed here. Basically, telling stories about mod and providing the original URL is not illegal in any term, I think. 

@DarknessShadow yeah, this is not a perfect solution, but we have to do something that can teach non-skilled users to make difference between sites about Minecraft. Not the best, but the best possible solution.

**Comment by hron84** [comment]
@DarknessShadow i think modifying someone other's work without explicit permission and distributing it without mentioning the nature of modification should be prohibited in all first world countries especially if this modification makes the work to host malware code.
