### ISSUE TITLE
Use old renderer as default by configuration option

### ISSUE THREAD

**Issue by Unknown-Zombie** [RS485/LogisticsPipes#804]
Is there a chance that we could get a setting in the config file for using the old renderer? It would be nice to have the option of making it default for new worlds.

**Comment by SonOfTheStars** [comment]
May I ask why you preffer the old renderer over the new one?

**Comment by bziemons** [comment]
@Bitterholz you would also start a discussion about why someone likes the color blue more than red?

**Comment by SonOfTheStars** [comment]
@TheZorro266 id just like to Know, why the Person prefers it. If they dislike the new one?

**Comment by Unknown-Zombie** [comment]
1. The old renderer matches the look of BC pipes. Mixing new renderer's pipes with BC pipes looks odd.
2. Minecraft is a game with low-fi graphics. The world is made out of 3-feet-cubed blocks. High resolution models look out-of-place in my humble opinion.

I'm not sure who made the new models; I'm not saying I dislike them. I'm sure it took whoever made them a significant amount of effort, and I appreciate what they've done. It's just my opinion that they don't match the aesthetics. It is purely my opinion.

**Comment by bziemons** [comment]
Just fyi: You can manually switch the renderer in the Logistics Pipe Controller ingame.

**Comment by Unknown-Zombie** [comment]
Yeah, I would just like to also have the option available from the config file. If it were available as a config option then it could be set as default.
