### ISSUE TITLE
BC pipe element removal from LP pipe freezes the server

### ISSUE THREAD

**Issue by AT611** [RS485/LogisticsPipes#809]
Most of the times when you remove any BC pipe element (pipe wire, pipe plug, etc.) from a LP pipe (chassis or basic one, doesn't matter) our server hangs up with no error in the console or anything. No response in the console on commands, sometimes Ctrl+C works and I can shut down the server somewhat "nicely", but not always. The freeze happened like 10 times already in a few days, so it's not a rare bug for us.
Can't tell if it strictly needs to be adjacent to any BC pipe or not, but players on my server crashed the server with the LP pipe adjacent to a machine when removing the plug.

Versions:
BC 7.0.23, LP 0.9.2.46, Forge .1424 (may test with a more recent one, if it needs to).

How to reproduce:
Place pipe plug or pipe wire on any connected logistics pipe, shift + right click the pipe with empty hand, watch as nothing happens and the server stops responding.

**Comment by SonOfTheStars** [comment]
Do you have access to VisualVM check your server and get us a Sample of the Moment the Freeze happens? If you have questions Regarding VisualVM, I bet @davboecki  will help you out!

**Comment by AT611** [comment]
https://www.dropbox.com/s/xo80brv4aliozsq/lp_bc_pipewire_removal_freeze.nps?dl=0
It's the first time I've exported a snapshot from VisualVM, so idk if I did everything right, but I've started data collection in 5 seconds before the freeze.
Can redo the testing any way you want if the current file will not help.

**Comment by davboecki** [comment]
Same as: https://github.com/RS485/LogisticsPipes/issues/807
