### ISSUE TITLE
Newer BC builds broken with LP.

### ISSUE THREAD

**Issue by andejx** [RS485/LogisticsPipes#81]
https://github.com/BuildCraft/BuildCraft/commit/2451b6925f2db679891d74a4a227b3892ea180e4

this commit onwards it seems broke something, if I use a build prior to this then everything works fine.

spam in log on startup but game loads fine http://pastebin.com/JhXf3Euj

soon as you look at a log pipe either placed in world or in creative/nei game crashes.

full log : http://paste.ubuntu.com/5712535/

tested without optifine too cos I know it hates everything, but happens without optifine too.

Wish I could help more but I'm a java noob. Cheers.

**Comment by davboecki** [comment]
Fixed
