### ISSUE TITLE
Crash when placing pipes

### ISSUE THREAD

**Issue by AT611** [RS485/LogisticsPipes#810]
I was testing some issues for #809 by placing some pipes, and somehow this happened:
http://pastebin.com/bW8F4bEq

**Comment by davboecki** [comment]
Are you using the new or the old renderer?
Have you played around with your texture packs before the crash?

**Comment by AT611** [comment]
Actually it was the old renderer, for some reason. I didn't touched any settings, just installed the mods into a new instance of Minecraft.
No, I'm not using any texture packs.
