### ISSUE TITLE
Client Crash on Ordering (new post per dev req)

### ISSUE THREAD

**Issue by Sakata-MC** [RS485/LogisticsPipes#812]
Making a new issue posting per Dav's request on #739.

This happens sometimes when ordering an item with multiple steps in crafting.  I've still not figured out the exact cause of the issue.  Sometimes I can order a part, then the next time, cannot, the client is kicked with no output on client side logs.
https://gist.github.com/Sakata-MC/7e2336263d7676be439a#file-crashola

**Comment by hron84** [comment]
@Sakata-MC could you please attach the affected version numbers of following mods:
- Forge
- BuildCraft (if you have)
- LogisticsPipe

and also a screenshot and/or a description about your setup? It would be very good as these information can speed up the debugging process for the developers.

**Comment by Sakata-MC** [comment]
Meh, read the previous post, also read the included logfile, as  it has all this information - if you cared to look, aside from a screenshot.
