### ISSUE TITLE
NoSuchMethod crash with EnderIO transceiver

### ISSUE THREAD

**Issue by Terpo** [RS485/LogisticsPipes#817]
http://pastebin.com/u5rd7R7g

EnderIO-1.7.10-2.3.0.415_beta
logisticspipes-0.9.2.49
Forge #1448 

I'm building a large server update at the moment and it seems to be stable. If I'm trying to join a base of one of our builders the server closes.

EnderIO Build 408 works fine.

**Comment by davboecki** [comment]
Does this also happen, when you use non-beta versions of EnderIO ?

**Comment by Terpo** [comment]
As written above the beta 408 works fine. We are working with the beta builds for a long time now without any problems. Between 408 and 415 should be a change or something. http://ci.tterrag.com/job/EnderIO/changes
Maybe this one: https://github.com/SleepyTrousers/EnderIO/commit/9320c00618a8ce30ba91bac0cdf1757df2534ec5

**Comment by hron84** [comment]
Also I'm not sure you can downgrade your server to a non-beta EIO build.

**Comment by Terpo** [comment]
The new version is still beta but he has official released it on curseforge. I took my build from the jenkins server like the last five updates.

**Comment by Terpo** [comment]
Just a short update:
I told my member to take look at the "crash base" and he removed some of the direct connections between EIO transceiver and LogiPipes. Now the version 0.9.2.50 of LP and EnderIO-1.7.10-2.3.0.417_beta are working fine.

**Comment by davboecki** [comment]
The problem here is, that If we update LP will not work with old EnderIO versions. At least not if we don't add a system to load a seperate class if the old version is available.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/c6cf698ae4e9d9a7866089444f521799e5ddee12
