### ISSUE TITLE
LP network get's confused by pipe plugs

### ISSUE THREAD

**Issue by AEnterprise** [RS485/LogisticsPipes#818]
if you use pipe plugs to seperate 2 pipelines the system gets confused, a pipe will send it to the pipe that is has a plug but it won't go that way due to the plug so it continues down the line until it hits another basic pipe, then it gets send back where it came from and it just keeps bouncing between the 2 basic pipes

using a basic pipe with a disconnection upgrade instead does work

**Comment by davboecki** [comment]
could you make a screenshot which shows the problematic setup.

**Comment by AEnterprise** [comment]
for some reason the pipe plug doesn't render in my single player test world but you can see it's there in waila, using an unrouted or a basic pipe also makes no difference
![2015-10-02_17 25 54](https://cloud.githubusercontent.com/assets/5206666/10250384/c48019c2-692a-11e5-9baa-c28679c0577d.png)

**Comment by bziemons** [comment]
Could you provide your BC, LP versions?

**Comment by AEnterprise** [comment]
BC 7.0.21
LP 0.9.2.49

**Comment by HCSarise** [comment]
I had this happen too, was using pipe plugs to block off excess routing to my laser power lines and the chipsets I was trying to craft kept getting stuck in a loop trying to go through the plugged pipe.

**Comment by davboecki** [comment]
I'm not able to reproduce this.

**Comment by hron84** [comment]
@AEnterprise could you try to reproduce it with the latest LP and BC? I checked it too, and I weren't able to reproduce the problem.

**Comment by AEnterprise** [comment]
there is a pack update soon so i'll check again

**Comment by AEnterprise** [comment]
doesn't seem to heapen anymore, sorry for bothering with this, didn't try the latest cause i didn't see anything related to it in the changelogs
