### ISSUE TITLE
Modules and Upgrade

### ISSUE THREAD

**Issue by Bellwar** [RS485/LogisticsPipes#819]
I love how the new pipes have infotmation what thay do, but few modules dont have the pipe type so its hard to know what they do (Terminus and some others) and same for some upgrades i cant get for what i should use them (sneak upgrade) or the power ones. And wiki isnt so good for information and modspotlights are littlebit old too. Im just new into this mod and its very very hard to get the basic for now.

**Comment by SonOfTheStars** [comment]
Allready on the todo List, ETA: Unkonw

**Comment by Bellwar** [comment]
Hope it will be as fast as you can :smiley:
