### ISSUE TITLE
hud (glasses) for upgrades

### ISSUE THREAD

**Issue by Flow86** [RS485/LogisticsPipes#82]
Hi,

I dont know if it already exists somehow, but it would be nice to have a "hud"-view for upgrades too, not only for the plain pipes. Does that already exist? Or could it be added, I dont think it should be too much problem. Perhaps using a recipe like hud-glasses + upgrade-manager-item or something like that.

**Comment by bziemons** [comment]
Personally I like the idea. Would need some coding of course, but as we do have the HUD glasses..

**Comment by bziemons** [comment]
Needs evaluation of work and comments, if being accepted.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
