### ISSUE TITLE
Pipes not detected by OpenComputers 

### ISSUE THREAD

**Issue by LizzyTrickster** [RS485/LogisticsPipes#821]
When trying to use OpenComputers to interface with LP Pipes, their expected component ( as shown [here](https://github.com/RS485/LogisticsPipes/blob/dev/common/logisticspipes/proxy/opencomputers/OpenComputersProxy.java#L18) ) does not show up.

Setup in world:
![World setup with pipe + adapter](http://puu.sh/kykoa/e8ea8a3b5c.jpg)

Component listing in Lua
![component list](http://puu.sh/kykqa/8c31751b1c.png)

When converging with @fnuecke in the OpenComputers channel, he said it may be due to [this](https://github.com/RS485/LogisticsPipes/blob/83c09c7bab0cd71362464fc58853020b50f22be0/common/logisticspipes/pipes/basic/LogisticsTileGenericPipe.java#L89) meaning it would only work for OC 1.3 (which is outdated now).

Mod Versions:
LP: 0.9.3.52 (from Jenkins)
OC: MC1.7.10 1.5.16.728-dev-universal (From the OC Jenkins)

**EDIT**:
The in game command `/oc_spawnComputer` may help for getting a prebuilt computer to test with

**Comment by AT611** [comment]
Does not work for me:
- Forge 1492
- buildcraft-7.1.12
- logisticspipes-0.9.3.68
- OpenComputers-MC1.7.10-1.5.19.37-universal

Brand new instance of Minecraft. Only the "bc_pipe" is available, except OC stuff.

**Comment by LizzyTrickster** [comment]
Woo, I'll test when I get home :)

**Comment by bziemons** [comment]
May still be not fixed, as @AT611 pointed out (GitHub autoclosed the issue, because of the merge from `stable-bc7` to `dev`).

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/2494d9050659cb488bb94b486eeaeee548ca7b03 fixes the integration.

**Comment by LizzyTrickster** [comment]
What build will it be in?

**Comment by davboecki** [comment]
build 92 and higher.

**Comment by karouvirae** [comment]
I can't seem to properly get this working on build 100. I use the same setup as seen in the screenshots above (request-pipe to adapter; only "bc_pipe" is shown in the components).
- logisticspipes-0.9.3.100.jar
- OpenComputers-MC1.7.10-1.5.22.46-universal.jar

**Comment by civilwargeeky** [comment]
Hello,
I just wanted to let you know that the logistics pipes support for OC no longer works with the most recent 1.7.10 versions of both.

Using
logisticspipes-0.9.3.128
OpenComputers-MC1.7.10-1.6.0.7-rc.1-universal

Also if they matter
buildcraft-7.1.18
buildcraft-compat-7.1.5
Forge 10.13.4.1566-1.7.10

It is just the same as previously happened, the component show up as "bc_pipe" with no logistics pipes support.

Thanks so much for the awesome mod!

**Comment by bziemons** [comment]
@cilvilwargeek could you please open a new issue? Just copy your text over.
