### ISSUE TITLE
Visual bug when opening and closing request view in request table

### ISSUE THREAD

**Issue by 1n5aN1aC** [RS485/LogisticsPipes#824]
LogisticsPipes Build#53

By the way, great addition, huge quality-of life improvement!

If you open the Logistics crafting table:
![1](https://cloud.githubusercontent.com/assets/735325/10400128/c118b7ee-6e6b-11e5-9998-8c1b88254328.png)

Click hide; There is a visual bug in the location of the hide & show buttons, putting them in the wrong places.
![2](https://cloud.githubusercontent.com/assets/735325/10400136/c97992e6-6e6b-11e5-9974-eb611015388f.png)

Click "hide" again (to show it :wink:) and the hide button will ghost to remain in the position it was in:
![3](https://cloud.githubusercontent.com/assets/735325/10400166/fdcc5bfa-6e6b-11e5-9154-103a660140ec.png)

Finally, closing and re-opening the GUI fixes it:
![4](https://cloud.githubusercontent.com/assets/735325/10400189/2429ee16-6e6c-11e5-9e0c-592ce16a8687.png)

This appears to happen without regard to GUI scale or screen size.

**Comment by 1n5aN1aC** [comment]
mmm additional non-impacting, but annoying bug, somewhat related:

You cannot remove the output from a recipe from the logistics request table.  Whether by clicking the remove recipe [x] button, or clicking on the output itself, the ghost item is still there upon re-opening the GUI.

**Comment by 1n5aN1aC** [comment]
Thanks!  https://github.com/RS485/LogisticsPipes/commit/6bc324039e4073de3d841f207ef9cee314ac07d1 MOSTLY fixes this bug.

Although, the GUI is still a little wonky the same way it was before if you click the [?] in NEI, putting the recipe in the request table:
![untitled](https://cloud.githubusercontent.com/assets/735325/10419808/a1d88508-7037-11e5-89d8-1aaf1d6d8578.png)
(This is after clicking the [?] in an NEI recipe.  Other than that, the GUI appears to be completely fixed!)

**Comment by davboecki** [comment]
Just a reminder for myself: https://github.com/RS485/LogisticsPipes/blob/stable-bc7/common/logisticspipes/gui/orderer/GuiRequestTable.java#L181

**Comment by davboecki** [comment]
Recipe not updated client side...
