### ISSUE TITLE
NPE with getBlockTextureFromSide

### ISSUE THREAD

**Issue by AT611** [RS485/LogisticsPipes#831]
http://pastebin.com/Ukp5b8Ru

**Comment by AT611** [comment]
Update:
There was a bug with the fluid texture: Helium-3 from GT (or not?..) inside a GT centrifuge had no texture, probably the crash was related to that.

**Comment by SonOfTheStars** [comment]
Funky GT Fluids being Funky with LP Fluid Containers....

**Comment by AT611** [comment]
I've heard that this issue was related to the fluid conflict between GT and Galacticraft, so maybe it's not the GT who's funky.
Resolved the "instant crash after login" problem using /setblock command to remove the pipe anyway.

**Comment by davboecki** [comment]
Add NPE check here: https://github.com/RS485/LogisticsPipes/blob/stable-bc7/common/logisticspipes/renderer/LogisticsRenderPipe.java#L598
