### ISSUE TITLE
[enhancement] Change Crafting Recipie of Pipe Speed Upgrades to Produce Batches of 8

### ISSUE THREAD

**Issue by mikeloeven** [RS485/LogisticsPipes#832]
Logistic pipes are crafted in batches of 8 pipes and due to the implementation i assume the pipe speed upgrades need to be applied to all pipes in the line.

this results in a need for hundreds of these upgrades ergo they should be produced in batches of 8 just like the standard pipes to mitigate the excessive cost of upgrading long pipes lines 

While the upgrades themselves are not expensive the problem arises due to the sheer quantities needed 

Of course i am assuming these upgrades function the same way as similar modules on a per pipe basis of course since none ever bothered to add an entry to the rs485 wiki page i cannot easily confirm their behavior due to Server TPS issues IE how many pipes are effected and whether or not they stack

Disregard this post if the acceleration persists across moderate Straightaways

**Comment by SonOfTheStars** [comment]
Actually Items sped up by the Pipe they get accelerated in should remain on that speed...Since LP has absolutely 0 Drag on its pipes.

I can't (Yet) confirm this ill test It out.
Maybe @davboecki will state clearance on this.

Note on the Wiki: Highly outdeated, im the only contributer ATM and my Time is fairly limited...

**Comment by mikeloeven** [comment]
Ah ok the items flicker in and out of existence while traversing the pipes so i couldn't notice any difference in speed between upgraded and straight runs of golden pipes. is there a notable difference between the max speed of items passing through a gold pipe vs the upgraded routing pipe

**Comment by davboecki** [comment]
LP pipes speed up items by using LP-energy. The speedup upgrade just increases the target speed. While LP pipes don't slow items down, BC pipes do. I'm not 100% sure but iirc even bc pipes have a limit, which LP speedups exceed. You don't need Speedup upgardes in every pipe. Puting some at your main intersection will speedup most items and already help your speed.

Or you can just use warp ducts in places to provide a fast connection way.
