### ISSUE TITLE
Pipe Issue

### ISSUE THREAD

**Issue by StarfireSky** [RS485/LogisticsPipes#834]
When I put the chips in the chassis and then and then leave the game then come back to the game later on in the day the chips disappearing from the chassis what is going on.

**Comment by davboecki** [comment]
Please provide a reproducable step by step guide. 

Please also post your Forge, lp and be versions. 
And add a mod list.

**Comment by StarfireSky** [comment]
I would have ten chassis lay down with chips in them then I get off the game for a little while then  come back to the game lay down another ten chassis with chips in them leave the game and when I get back on the game the second group of chassis that had the chips in them I look and the chips are gone when they were there before I shut the game down.
Forge I am using is 10.13.4.1492  version is 1.7.10 Logistics mod

**Comment by davboecki** [comment]
Can you reproduce this bug? Sounds like something crashed and prevented your world from being saved. Doesn't have to be an LP problem.

**Comment by hron84** [comment]
@StarfireSky Maybe you should check the crash-reports folder, there are files named by date when they're created. Please check if you have a file created at same time when you shut down the game, and if you do, post it to https://gist.github.com/ (it uses your GitHub account to log you in), and paste the URL of the Gist here.

This will help us to determine what's going on, and what's your issue come from, LP or something other.
