### ISSUE TITLE
invalid id

### ISSUE THREAD

**Issue by Trixz2018** [RS485/LogisticsPipes#835]
newest build: Invalid id 11945 - maximum id range exceeded.

http://pastebin.com/V0K6t3kU

**Comment by XFactHD** [comment]
That's not LPs fault. Item and block IDs are generated dynamically by forge. If the range of IDs is exceeded, your modpack is simply to large. How many mods does it contain?

**Comment by Trixz2018** [comment]
not enough, but it happened when i added gregtech but im gonna try to downsize it to see if it helps
