### ISSUE TITLE
[Enhancement] Mechanic to List Installed Upgrades and Remove Them Without Breaking the Pipe

### ISSUE THREAD

**Issue by mikeloeven** [RS485/LogisticsPipes#840]
When configuring my system i noticed that installing a upgrade is a rather strange situation you right click the pipe and the upgrade is removed from the players inventory. the issue is that the pipe can take multiple upgrades of the same type and there is no indicator as to how many or what types of upgrades are installed in said pipe. Even using the logistics hud glasses there is no indicator and no method of listing the upgrades that each pipe possesses unlike chassis which have card slots. 

What is needed is both a method of seeing what upgrades are in each pipe as well as the ability to remove specific upgrades without destroying the pipe which causes disruptions in the system

**Comment by davboecki** [comment]
Right clicking upgrades into pipes is just a convenient feature. The normal way would be to use the pipe controller. There you can remote, resort, add and view all installed upgrades as well as pipe statistics. More features for the pipe controller are planed for the future.
