### ISSUE TITLE
Hud Not Functioning after Update to FTB Infinite 2.0.2

### ISSUE THREAD

**Issue by mikeloeven** [RS485/LogisticsPipes#841]
After Update Hud is not displaying any Information. Breaking and replacing provider pipes will restore the hud UI but only for that pipe. Due to the size of some systems this is simply not doable for most players. you should include a button in the HUD Configuration for re initializing it or simply have the huds re initialize when the pipe systems are power cycled (turned off than on)

**Comment by SonOfTheStars** [comment]
Please inseret the actual version of LP, Nobody here has the Time to Go and Look up the Version of LP featurted in FTB Infinity 2.0.2...
Without the LP version Annotated, your Bug report is Kinda Useless

**Comment by bziemons** [comment]
Or in other words: It would be nice, if you could provide the Logistics Pipes version with your issue, so that we can help you.

**Comment by hron84** [comment]
I tried to figure it out but the Confluence of the FTB modpacks is not contains this version...

**Comment by mikeloeven** [comment]
Listed as 0.9.3.61

More observations. Problem occurs each server restart and appears to have something to do with chunk loaders 

Pipes that are not chunk loaded do not suffer this issue the hud can be reset by disabling all chunk loaders in the vicinity teleporting to spawn and back. 

looks like part of the hud initialization required the chunk to unload and chunk loading prevents this from occuring

**Comment by ZZaphodd** [comment]
possible laborious workaround? http://m.ftbwiki.org/Crafting_Sign_Creator

**Comment by Landrash** [comment]
I'm having the same problem so any kind of debugging I can do just ask.

**Comment by bziemons** [comment]
:broom:
