### ISSUE TITLE
Rendering issue with LP - up to freeze on world load

### ISSUE THREAD

**Issue by JasonMcRay** [RS485/LogisticsPipes#845]
When I get Fluid Supplier Pipe with some GT Lubricant stuck in it it will cause huge spam (about GL) in the logs. I talked to @techbrew about this, because it was happening only with JM (5.1.1rc1) installed. He said to me some bits and bobs which I dont understand at all :). But I asked him if I should report it in here as well, and he said that it will be good idea and maybe you will be able to provide some insight into it and help out.

Minecraft log with the spam: https://paste.ee/p/wdZFP
Journeymap log: https://paste.ee/p/aySHN

Forge: 1490 (tested also with 1448)
LP: 0.9.3.69
GT: 5.09.11
JM: 5.1.1rc1

**Comment by techbrew-mc** [comment]
JourneyMap is just checking GL11.getError(), so it's possible that the fluid in the logistics pipe is putting something in the error queue an not clearing it.  Be worth checking.  In the meantime I'll try to defensively clear the errors before JourneyMap starts drawing.

**Comment by AEnterprise** [comment]
looks to me that eighter LP or GT is having a push/pop call to much or is missing one causing

**Comment by JasonMcRay** [comment]
Confirmed that its not a JourneyMap issue. Its still happening without JM installed (no idea why i havent noticed before). So either GT (already reported) or LP.

**Comment by Nonsanity** [comment]
We're seeing a similar error, but with a twist. If you look at the LP, the game freezes—mostly. The screen stops updating at least, though I found I could still hit ESC and click the (invisible) buttons, logging off and back onto the server. But the screen stayed stuck as it was in the game. I ended up editing the region file in MCEdit to remove the LP pipe. No freeze after that when I logged back in.

So then I put the pipe back—no freeze. But when I turned the system on that started sending Liquid XP through the pipe and turned around to look at it, the screen froze again. Can't really get more red-handed than that. :)

While searching for the specific block that was causing the freeze, I got the best glimpse of it by looking up form the floor suddenly. Attached is the view when it froze, and you can see the LP pipe across the room attached to the Tesseract.

![screen shot 2015-11-14 at 3 27 56 pm](https://cloud.githubusercontent.com/assets/3012708/11166883/7f026e12-8b18-11e5-9a31-383e911fdb0e.png)

This is BBoldt's Unabridged modpack, which does not have GregTech.

logisticspipes-0.9.3.69
EnderIO-1.7.10-2.3.0.418_beta
integratedcircuits-1.7.10-0.9r37

[14/11/2015 11:44:02 AM] [Client thread/WARN] [integratedcircuits]: Shaders not supported, disabling aura effect :(
[14/11/2015 11:44:02 AM] [Client thread/WARN] [journeymap]: GL Error in TileDrawStep: 1281
[14/11/2015 11:44:02 AM] [Client thread/WARN] [journeymap]: GL Error in TileDrawStep: 1281
[14/11/2015 11:44:02 AM] [Client thread/WARN] [journeymap]: GL Error in TileDrawStep: 1281

**Comment by BBoldt** [comment]
Hey, I'm the Unabridged guy, just thought I should let you know that people didn't start getting these issues until my last update, where we went from logisticspipes-0.9.3.59.jar to logisticspipes-0.9.3.69.jar.

The version of forge we are using is 1492.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/ea6a08a7b0a9604f963ff4bdc1c821d20edcc95b
