### ISSUE TITLE
Modpack

### ISSUE THREAD

**Issue by TheDWPCer** [RS485/LogisticsPipes#848]
Need help again

http://pastebin.com/6wBAtwAL

And once I remove logistics pipes this happens

http://pastebin.com/kEhLuEVs

so I need your help

**Comment by bziemons** [comment]
I am sorry, but this is not a forum for modpack creators.

**Comment by hron84** [comment]
@TheDWPCer I think you using too new Forge for one or few mods or you set too small PermGen space. Try asking on [MinecraftForum](http://www.minecraftforum.net/), there are an experienced modpack creators, they can help you. Regardless this, you should remove all the mods from the mods folder, and put back one-by-one 'til you get the issue again, and remove the wrong mod from your pack.

**Comment by TheDWPCer** [comment]
I know about taking the mods out 1 by 1 but I have 326 mods in my pack and it takes a 1 hour no joke to start with my AMD C-50 dual core processor, 1 by 1 not a option.    I will go to MinecraftForum.

Thank you for your feedback :)
