### ISSUE TITLE
Fuzzy Upgrade Cannot Be Placed into Chassis Pipe

### ISSUE THREAD

**Issue by mikeloeven** [RS485/LogisticsPipes#851]
If you have a section that has multiple functions in a single pipe such as crafting supplying or item sinks it is impossible to configure fuzzy behavior as the chassis will not accept the fuzzy upgrade and there exists no crafting recipe for fuzzy variations of these modules

**Comment by SonOfTheStars** [comment]
Upgrades on Modules are in the Workings. Ask @davboecki for further Information!

**Comment by bziemons** [comment]
Yeah, I would also say this is part of the module for module upgrading. I'll assign davboecki for that then.

**Comment by Keridos** [comment]
Any news on this?

**Comment by mikeloeven** [comment]
I am not sure its possible to implement this this until they fix the fuzzy crafting system's base code. last time i tried setting up fuzzy crafting i was getting constant client crashes and occasionally sending the server into a deadlock state there is a ticket regarding that issue around here ... somewhere

though i haven't played minecraft for a few months so it may already be fixed

**Comment by bziemons** [comment]
The fuzzy upgrade can be applied to the crafting module by using the module upgrade on the chassis pipe.
