### ISSUE TITLE
Update Forestry proxy

### ISSUE THREAD

**Issue by Tsyklop** [RS485/LogisticsPipes#853]
Error in log file http://pastebin.com/BSWL2A9B

logisticspipes-0.9.3.69

**Comment by davboecki** [comment]
The forestry proxy didn't load. Please post your versions.

**Comment by Tsyklop** [comment]
@davboecki forestry_1.7.10-4.1.1.46

**Comment by SonOfTheStars** [comment]
seems like we have to update the Proxy Again @davboecki

**Comment by hron84** [comment]
Forestry development got a mk3 speed upgrade as I see... :-)

**Comment by Zenopheus** [comment]
Does anyone know what problems this might cause? Is there a work around until the problem is resolved?

**Comment by bziemons** [comment]
Fixed in newest BC7 Stable for Forestry 4.2.x
