### ISSUE TITLE
[issue] Disconnecting with a fatal error upon requesting some fuzzy recipes.

### ISSUE THREAD

**Issue by HaniiPuppy** [RS485/LogisticsPipes#854]
I have three recipes in my LP auto-crafting system using fuzzy crafting tables, connected to MK2 crafting pipes - pistons, chests, and JABBA barrels. Pistons and chests can accept any wooden planks with the oredict entry "plankWood", and JABBA barrels can accept any log with the oredict entry "logWood", so I've set it to take planks (oak in the recipe), and logs (oak in the recipe), with oredict turned on in the recipe. Requesting these to be crafted from a request table using this fuzzy recipe causes the client to immediately disconnect (but not crash) with a fatal error.

There's nothing to paste from the log, because nothing is written to the log specifically pertaining to logistics pipes.

The planks/logs currently in my sorting system, and thus available for this recipe, are oak, birch, spruce, fir (BoP), Eucalyptus (Natura), and Greatwood (Thaumcraft).

Interestingly, greatwood planks get used for the chest/piston recipes first for me, despite greatwood planks not having the plankWood oredict entry, according to the show oredict entries mode. Although this happens even if I remove greatwood planks from the system.

This seems to be fixed/avoided by no longer using the oredict option on the planks/logs.

I can record a video showing this if requested.

This is under version 0.9.3.68, under FTB Infinity Evolved version 2.1.2.

**Comment by SonOfTheStars** [comment]
Can you get us the Server's Logfile somehow? Would be great!
Maybe the logfile can give clearance.

**Comment by mikeloeven** [comment]
Had something similar occur just tonight fuzzy crafting table any time i requested andthing that reqired copper or steel ingots the client crashed. All recipes had fuzzy configurations for copper and steel it seems that this crash occurs when a fuzzy table tries to explicitly convert a block of one mod to an ingots of another In my case the tables are producing Thermal Foundation Ingots and the crash occurs when they receive TInkers Construct Blocks

**Comment by SonOfTheStars** [comment]
@mikeloeven Sounds very interesting. The Fuzzy Code isn't the best, so probably Conversion with Fuzzy tables is not the Best way of doing it. Will look into it!

Question: Are all the Ingot Types enabled or maybe removed via Minetweaker?

**Comment by mikeloeven** [comment]
The fuzzy code is the best way to do this in theoretical the only other alternative is to have suppliers hooked up to a bank of MFR Unifiers (Lexicon in a Machine Block) and have them request all types of blocks except the type you want which is alot harder and more cumbersome to set up than a fuzzy table that doesent care which block your inputting the main issue with the unifiers

**Comment by mikeloeven** [comment]
So it looks like the instance of this crash can be reduced (but not entirely eliminated) by including ignore NBT and ignore Damage in the fuzzy configuration

EDIT: 
Does not work looks like the reason it appeared to work was because i was only requesting one item using the fuzzy table any fuzzy requests for more than one item or chained requests cause the issue to re emerge

**Comment by oninoni** [comment]
I think this relates to/Is the same as: https://github.com/RS485/LogisticsPipes/issues/784

**Comment by bziemons** [comment]
#784 was fixed. If this issue or some other bug occurs, please open a new issue refrerring to this.
