### ISSUE TITLE
Ticking Block Entity

### ISSUE THREAD

**Issue by Morketh** [RS485/LogisticsPipes#855]
This happened just as i broke my Request table I was trying to pick it up after i realized a Mk5 chassis pipe had locked the network up crafting several stacks of item casings from IC2 ( #843 ) as these were unneeded i decided to just remove the block that made the original request (the RequestTable) and the server promptly shut down.

Crash report (copied): https://gist.github.com/theZorro266/c5f9afb22637c3919212

**Comment by davboecki** [comment]
This is a bug yes, but breaking the crafting table will not cause the request to be canceled it will just sort the crafting result into your system.

**Comment by Morketh** [comment]
@davboecki well that's good to know. so for future reference how do i cancel an operation?

**Comment by davboecki** [comment]
You can't. That's not the way LP is designed.

**Comment by tomatheb** [comment]
I had the same, or very similar, crash breaking a crafting pipe. If you want another crash log for comparison, you can find it here: 
https://gist.github.com/tomatheb/a5ad7e5cdae8b76da279d8f265c5e739 
At the time there was a craft request registering on a passive provider pipe for the pipe in question that it was refusing to fulfill. It had the materials but would not extract them. This was attached to a draw controller with the materials available.

Modpack: FTB Infinity Evolved 2.4.2
Mod Version: 0.9.3.95

**Comment by bziemons** [comment]
Might just have been fixed in 0.9.3.130
