### ISSUE TITLE
When Selecting Out Put of Fuzzy Recipies Please Display Mod and Block ID on Mouseover

### ISSUE THREAD

**Issue by mikeloeven** [RS485/LogisticsPipes#857]
configuring fuzzy tables is damn near impossible since when you get the little arrows to select the different ingots / blocks these are only displayed by item name but do not list the mod or block id making it damn near impossible to determine which ingot you have selected since they all appear as Insert material here Ingot.

**Comment by SonOfTheStars** [comment]
+1 On this! Would be super Nice!

**Comment by boggis2** [comment]
+1

**Comment by davboecki** [comment]
See: https://github.com/RS485/LogisticsPipes/issues/920
