### ISSUE TITLE
Fluid Extractor Pipe needs a MKII / MKIII version 

### ISSUE THREAD

**Issue by mikeloeven** [RS485/LogisticsPipes#858]
On a high capacity refinary i found myself needing about 10 fluid extraction pipes on my refining block to keep up with the rate of fuel production there needs to be a MKII and MKIII Upgrade for these fluid extraction pipes

**Comment by davboecki** [comment]
Probably not a bad idea.

**Comment by bookerthegeek** [comment]
This sounds like a great idea.

**Comment by joral** [comment]
Do you guys have any thoughts about how much faster the MK2 / MK3 extractors should go?  Should each one just be double the one before (MK2 is 2x, MK3 is 4x the normal one) or is that not high enough of a jump?

**Comment by Keridos** [comment]
Since there is a lot of improvement in extraction rate for the item extraction I suggest the same for the fluid pipes. Also large reactors from IC2 and BR require and produce large amounts of fluids (BR f.ex 2000mb/t).

**Comment by bookerthegeek** [comment]
An exponential increase per level of pipe should work

**Comment by bziemons** [comment]
I would suggest having an Mk2, where you can control the throughput. Because I wouldn't like going up to Mk10, because just another mod spawned that needs 100 000 mB/t.

**Comment by hron84** [comment]
@theZorro266 "just another mod spawned" :laughing: 

Serious part: I could imagine some stackable upgrades as a "throughput control". As many upgrades you put into the pipe, as much mB/t you can achieve.

**Comment by HadesDurin** [comment]
+1 i am a fan of this idea
makes it easier to get my fluids sorted around my base

**Comment by bziemons** [comment]
@davboecki is this pipe covered by the upgrades?
