### ISSUE TITLE
Assembly-Table Support for Crafting-Pipe

### ISSUE THREAD

**Issue by Flow86** [RS485/LogisticsPipes#86]
Hi,

the crafting pipe doesnt work with bc's assembly table (but it would be cool if so)

**Comment by Sakata-MC** [comment]
It is being looked into last I heard.  The issue is that the L-ACT (laser ACT as I call it) autoejects items.
Currently it does not check unrouted items that enter the pipe for crafting result (but does assign a destination to sink it).

**Comment by bziemons** [comment]
If possible, we'll make that work. But as @Sakata-MC said, there was a bug with the assembly table before.

**Comment by ArtForz** [comment]
Implemented by 6dc96d0cc0 in Dev 610
