### ISSUE TITLE
JABBA Barrels : Provider Module - Leave First/Last Stack not working

### ISSUE THREAD

**Issue by Xhat3** [RS485/LogisticsPipes#862]
I got my Better Barrels with 0 upgrades, just a default one, which is holding iron ingots connected to a chassis mk2 having Provider Module and ItemSink Module.

I tried to set the Provider Module to Leave 1st stack, Leave last stack, leave both, leave 1 item per stack.

Nothing of thoses options is working, when the amount of iron ingots is hitting 64 it still send items in the network. At least the leave 1 item per type is working, but I'm keeping only 1 of the item in the barrel...

The one that are requesting the iron ingots are chassis mk2 with active supplier module in partial mode and extractor module connected to a blast furnace.

I'm getting wrong the goals of those options or is it really not working ?

I'm not the administrator of the server.  And I'm playing on the version used in the modpack FTB Infinity.

**Comment by bookerthegeek** [comment]
What version of inf?

**Comment by Xhat3** [comment]
2.1.3

**Comment by SonOfTheStars** [comment]
Id rather Ask, wich versions of LP and JABBA...

**Comment by Xhat3** [comment]
logisticspipes-0.9.3.68
Jabba-1.2.1a_1.7.10

**Comment by davboecki** [comment]
That's the way it is currently designed. Barrels have one big slot to store items. So if we would ignore the first or last slot, we would ignore the whole barrel so only the leave one item mode is implemented.

**Comment by hron84** [comment]
@davboecki slot != stack. In this case, I would leave exactly 1 stack item (i think max stack size should be queried somehow) instead of leaving the latest slot.
