### ISSUE TITLE
Placing upgrades on pipe feeding controllers.

### ISSUE THREAD

**Issue by iampyrex** [RS485/LogisticsPipes#864]
Running FTB Infinity 2.1.3 Expert Mode

Logistics Chasis causing crash on storage drawer controller.  Not sure why this is doing this, I think it may have to do with upgrading the pipes to the controllers, possibly having more than on in the same loop?

http://pastebin.com/SWimQuHM

**Comment by 1n5aN1aC** [comment]
Probably a duplicate of #802 ?

Do you think you could join that thread, and offer your insight?  I haven't been able to reproduce the problem yet.
