### ISSUE TITLE
Detected pipe with unknown key: forestry.core.items.ItemCrated

### ISSUE THREAD

**Issue by Morketh** [RS485/LogisticsPipes#865]
Last time i checked items.ItemCrated wasnt a pipe......?
So i turned my server on for the time in almost a week and got a rather odd [console report](https://gist.github.com/Morketh/788f8b1ea428be5dc53b) before the server crashed with a [fatal computercraft report](https://gist.github.com/Morketh/e703c2e7a63263b3c461) i have also [notified Forestry](https://github.com/ForestryMC/ForestryMC/issues/993) as well as [Dan200](https://github.com/dan200/ComputerCraft/issues/18) of this but simply put im using a series of computercraft computers (Issue #859) to monitor a factory as item counts reach an excess of 4K (dirt, cobblestone, sapplings, wood, etc) i have them being sent to a carpenter to be crated and then off to a storage room. No mods were removed and nothing upgraded, replaced, or even added since i safely shut the server down a week ago. Im not really sure if these 3 mods are the root/cause of the issue or even if there related (other then fact that i have them all connected in game) just figured id cover all my bases by notifying the modders in charge.

**Comment by Morketh** [comment]
Updated to latest version of Forestry and LP same issue. i can provide a mod list + world upload if any one like to verify the issue

**Comment by bookerthegeek** [comment]
Please:
-mod list plus versions

**Comment by Morketh** [comment]
I have a theory. Single player doesn't do that (although I haven't played
the same map or the same length of time) it's just the server map that does
it upgraded both LP and forestry + computer craft same issue so removed
forestry confirmed and loaded the server right up (same log messages but
this was exactly what I was expecting on this load) but all the block ID
some how ended up corrupted. I will get a mod list for server and client
(as I have some 1 sided mods running) later tonight. But the theory is
maybe it's the map itself? Some how during a safe shutdown in December it
possibly got corrupt so when I loaded it up yesterday day it just stopped
working.  I run a dedicated server and the box has been mothballed since so
it's highly unlikely a system change has occurred

EDIT: lack of grammar and spelling due to HTC desire626. My apologies it's hard to type on smart phone.

**Comment by davboecki** [comment]
As there is no way to reproduce this or find the cause of the problem, which may just be a corrupted save, this will be closed.
