### ISSUE TITLE
Satellite pipes not resetting free ID's

### ISSUE THREAD

**Issue by ilightwas** [RS485/LogisticsPipes#867]
Instead of explaining everything in text, I did a video to make it easier to see. This is on a multiplayer server, playing the FTB Infinity Evolved pack (Hard mode) 2.1.3, with logisticspipes-0.9.3.68

https://youtu.be/p0ZSHkUZl7g just uploaded it, still processing the quality

Not sure what is going on but the ID's from the satellite pipes get used and never come back. As you can see in the video there's a part where I take a satellite pipe with ID 4 and change it. After that I can't go back to the old ID 4. That happens even if there isn't a crafting pipe using those IDs

**Comment by ilightwas** [comment]
Ok, I talked with the admin of the server and after resetting every crafting and satellite pipe in my network, the server was restarted and the satellite id's got freed. Still, I think there might be a issue behind this erratic behavior.

**Comment by bziemons** [comment]
There is a new system for satellite ids coming up in 0.10. @davboecki 
We could use this issue as a reminder for that.
