### ISSUE TITLE
Autocrafting issues sometimes put the server in an unresponsive state

### ISSUE THREAD

**Issue by gnargh** [RS485/LogisticsPipes#871]
I was playing Infinity Evolved expert mode and automated all the steps to create enderium ingots.
Now when I order e.g. 12 enderium ingots me and everyone else on the server was timed out. No crash, nothing in the log, just timing out everyone and the server ends up in an unresponsive state. Only restart helps.

However if I was lucky and didnt get timed out, the system put all of the materials I had into the machine with the satellite pipe.

(for example bucket of liquid ender: The system put all my iron into the metal former on sat.id.1 and when I pull it out, a new stack comes flying through the pipes. Meanwhile all of my enderpearls were inserted into a chest by sat-pipe no2. (the chest distributes buckets/pearls to the magma crucible/fluid transposer) Same thing, if I take out enderpearls from the chest, once there is room, the rest of my enderpearls keep getting reinserted.)

I've noticed this happening with a bunch of recipes that require a lot of crafting steps. The ordered item includes satellite crafting and crafting pipes with tables. It did not happen to me, when I was ordering crafting recipes only, without satellite crafting.

Manually ordering the required steps worked without crash.

**Comment by UntouchedWagons** [comment]
I have experienced the same issue with Railcraft's Blast Furnace bricks. Using Infinity Evolved.

**Comment by bookerthegeek** [comment]
1. Can you please attempt to recreate on single player
2. Server is running forge/cauldron/etc?
3. Pictures help. :)

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/27d823e02ee319980795b65b689d010d845bf110
