### ISSUE TITLE
Gui Problem with some blocks and pipes 

### ISSUE THREAD

**Issue by nizarnizario** [RS485/LogisticsPipes#872]
Hello, 
i have an issue that you can see here : 
http://imgur.com/a/nFgcB
as you can see : the gui is messed up 
i have just installed the mod correctly with the appropriate version of BC
the mods i'm using : 
http://imgur.com/zFOrkIc

**Comment by nizarnizario** [comment]
Any help here????

**Comment by 1n5aN1aC** [comment]
Really looks like a graphics issue of some kind personally, though I can't be sure.

**Comment by nizarnizario** [comment]
so do you think it's a graphics card issue? or what :)
some other blocks/pipes work fine

**Comment by 1n5aN1aC** [comment]
It's possible.

Have you tried downloading Logistics Pipes again, in case something got messed up?

It seems a bit weird that it would be a graphics card issue, since it's a relatively common GUI system...

I think I would try loading it up with just LP & BC, and see if it works then.  If it does, we can try pinpointing what's causing it.

**Comment by nizarnizario** [comment]
i already tried , i removed all the other mods + i reinstalled MC ( + removing the .minecraft folder) and it's still there , 
that happens with some blocks only like the crafting pipe , request table and the logistics crafting table while that doesn't happen with the MK2 pipes and MK3....

**Comment by 1n5aN1aC** [comment]
Well, sorry to say that I really don't have any other ideas then.  :frowning:

**Comment by nizarnizario** [comment]
why sorry? :) thanks for taking time and replying on this post 
well i'm going to use it anyway ;)

**Comment by bziemons** [comment]
That is not reproducible and the first time I have seen this. Double check that you are on the newest version of your graphics driver and that you download LP from the official download site: http://ci.rs485.network/
