### ISSUE TITLE
Gui Open GL Error

### ISSUE THREAD

**Issue by MyEternity** [RS485/LogisticsPipes#876]
![2015-12-20_02 07 29](https://cloud.githubusercontent.com/assets/4238023/11915737/886bf89c-a6c5-11e5-9b17-c4a914fa84d3.png)
Some issie with luquids. To reproduce: set up GT5 distilation tower + with oil in it to produce.
Then use LP Fluid Extractor + LP Fluid Basic Pipes to allow fluid flow.

**Comment by SonOfTheStars** [comment]
We've been expieriencing Render Issues with GregTech Fluids a long time now. And its mostly because GT fluids are rendering wierd. Not much we can do ATM

**Comment by MyEternity** [comment]
![2015-12-22_01 02 08](https://cloud.githubusercontent.com/assets/4238023/11942459/c6e54f5a-a847-11e5-8d2d-39304581503b.png)
This solves the problem. Can you use such code for GT Fluids?

**Comment by Nanabell** [comment]
hmm well i get the open gl error aswell and i dont have gregtech installed

~edit but i do have reika's mods installed e.g rotary- reactor and electricraft

**Comment by bziemons** [comment]
If this was on our side, it would happen with every fluid.
