### ISSUE TITLE
LP and HQM incompatibility

### ISSUE THREAD

**Issue by JasonMcRay** [RS485/LogisticsPipes#882]
Not sure if the incompatibility comes from LP or HQM. I can't seem to put LP items into quests. I put them in, everything is fine, but when i restart minecraft all items in quest books gets replaced by bedrock. Also in the logs i can see this:
[15:06:18] [Client thread/ERROR] [HQM]: Attempted to read an item that doesn't exist LogisticsPipes:logisticsSolidBlock
[15:06:18] [Client thread/INFO] [HQM-EDIT]: Changed invalid item to bedrock.
For all the items I put in

Full log: https://paste.ee/p/tHu2N

**Comment by Timeslice42** [comment]
Why are LP items being loaded in postInit? Items should always be loaded in preInit.

**Comment by bziemons** [comment]
Historic reasons.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/7a80dd41c0e893a7c5690c127f9d512ab8dcae87
