### ISSUE TITLE
No crafting recipes

### ISSUE THREAD

**Issue by jordsta95** [RS485/LogisticsPipes#887]
I am only using Buildcraft Core, Silicon, and Transport (not the full mod), and there are no recipes for any blocks/items for Logistics Pipes in NEI. Or when spawning in a soldering station, when trying to view the recipes through that, it won't show anything.

Builcraft Core: buildcraft-7.1.14-core.jar
Silicon: buildcraft-7.1.14-silicon
Transport: buildcraft-7.1.14-transport.jar

Logistics Pipes: logisticspipes-0.9.3.70.jar

**Comment by hron84** [comment]
Did you tried to install the full BC?

**Comment by jordsta95** [comment]
No, mainly as it isn't something I want in the pack. I only installed what LogPipes said it depended on (Silicon and Transport)

**Comment by bziemons** [comment]
It also depends on Robotics, see #780.

**Comment by SonOfTheStars** [comment]
@jordsta95 If you want the Buildcraft independant Recipes, wich work completely without BC stuff, you will have to set "EnableBetaRecipes" to "true" in th config file.

That way you will get the Modernized version of all recipes.
