### ISSUE TITLE
Integration new BC 3.6.0

### ISSUE THREAD

**Issue by vavraCZe** [RS485/LogisticsPipes#89]
LP v482
BC v3.6.0
Forge v7.8.0.723

Crafting with request pipe isn´t conjunction with auto workbanch from BC.

**Comment by vavraCZe** [comment]
Ou... change in buildcraft

 Changed: Rewrote the Auto Crafting Table from the ground up. Now called “Auto Workbench”. 100 % compatible with vanilla hoppers. Items that cannot stack can’t be used in them anymore. They will not pull from adjacent inventories anymore, use hoppers/chutes instead. Crafting now has a time cost, the auto workbench does however not require power. (CovertJaguar)

Change name is bug

**Comment by davboecki** [comment]
An Logistics Crafting table is on the way.
