### ISSUE TITLE
[BUG?] Mod-Based itemSink module and XU Cabinets not playing well

### ISSUE THREAD

**Issue by hron84** [RS485/LogisticsPipes#890]
I set up a Filling cabinet for Loot Bags from Loot Bags mod and configured a Mod-Based ItemSink module to route all loot bags to this cabinet (this mod has only 6 different items and only one that is not a loot bag, but it's a block and I do not need more than one, so no need for store it). I also have a simple vanilla chest with a Chassis MK1 + QuickSort module to quickly put all my stuffs into the warehouse system. However, QS module does not remove loot bags, even if they could go somewhere (Filing cabinet) and having a default route too.

If I try to insert problematic bags into the cabinet manually, it accepts them, so there is no overcapacity issue or incompatibility issue (the cabinet already has all type of this bags, so it is "formatted" for it).

Loot bags basically share an item id, and they're only differs in metadata ID, like how vanilla wools works. The only difference from wools they have a custom tooltip and NBT data that describes what's their content.

Affected versions:

LP 0.9.3.70
ExtraUtilities 1.2.12
Loot Bags 1.8.1
Forge 1472

**Comment by Timeslice42** [comment]
Thermal Dynamics item pipes also have issues with inserting into ExU cabinets. I suspect there is some common interface the pipes are trying to use that the cabinet either isn't providing, or has incorrectly implemented.

Out of curiousity, do you see any issues if you pump loot bags from a chest with a redstone engine, past a cabinet connected via a clay insertion pipe, and finally terminating in another chest?

**Comment by bookerthegeek** [comment]
Loot bags have hidden NBT data containing the contents. Different for bags that have different items in them, regardless of the type of bag.

**Comment by Timeslice42** [comment]
The fuzzy upgrade still doesn't work for itemsinks, right?

**Comment by hron84** [comment]
@Timeslice42 I did not check with a pure BC-based system since I planned to use LP pipes only for my LP system, but I'll let you know when I'm able to try it out in development. Also, I'd like to use Chassis MK2 later anyway because I'd like to provide these bags too for my auto-extractor system that I'll implement later.

**Comment by hron84** [comment]
@bookerthegeek yep, but they can stack in cabinets since it's ignores NBT data (regardless it's hidden or not) and builds stacks based only on id/name and metadata, so you can stack enchanted books too.

**Comment by bookerthegeek** [comment]
True. The point I was making though is that you need to make sue your piping system ignores that hidden nbt data.

**Comment by hron84** [comment]
@bookerthegeek As we talking about **Mod**-Based Itemsink, I assume this type should ignore all data other than which mod is adds the specific item here. Again, I do not filtering by the looting bag type, partially because I do not have one from each type, but more like I went through same arguments and I decided to use Mod-Based since I expected it to filter by only the mod, not anything other.

**Comment by bookerthegeek** [comment]
Ah... my bad. Did not see that......   

So, I'm out of ideas.

**Comment by bziemons** [comment]
Going to have a closer look at it in the current LP 0.9
I tried using a polymorphic item sink with a XU cabinet today and that worked with a quick sort.

**Comment by hron84** [comment]
Sorry for the long silence I had a busy year. I have no access to my test system anymore since the server I played is moved to 1.10. @theZorro266 can you confirm this works with Mod-based sinks too?

**Comment by bziemons** [comment]
Will try that.

**Comment by bziemons** [comment]
Just checked this with the current version and the filing cabinet from UsefulStuffs-1.12.2-2.5.7. It all works as expected :)
