### ISSUE TITLE
Ticking Block Entity w/ Fluid Container Supplier Pipe [SSP World]

### ISSUE THREAD

**Issue by Timeslice42** [RS485/LogisticsPipes#891]
Full log: https://gist.github.com/theZorro266/fc58cc5711ce6a85d5d7
I have a fluid container supplier pipe attached to the bottom of an Extra Utilities drum set to supply gregtech oxygen cells to the drum. When the cell gets to the drum is when this exception happens. I'll also see instances of #889 around this issue. After the crash the pipe must be deleted with an editor before the world can be loaded again.

What I'm expecting to happen is that the logistic system will send oxygen cells to the drum until it supplies the amount specified while returning the empty cells back to be sorted.

**Comment by davboecki** [comment]
The only thing I can find is:

```
java.lang.NullPointerException
    at xk.xact.api.CraftingHandler.findAndGetRecipeIngredients(CraftingHandler.java:424) ~[CraftingHandler.class:?]
```

Did you upload the correct log?

**Comment by Timeslice42** [comment]
It was the right log when I posted the issue... it's since been overwritten by another ticket I posted on a different repository. I'll have to post a new log.

**Comment by Timeslice42** [comment]
https://www.dropbox.com/s/hr2332c71b52xld/LP-I891.zip?dl=0

Stupid github won't let me attach it. ("Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.)

Edit: I added the logfile in a [gist](https://gist.github.com/) to the first post /theZorro266

**Comment by bziemons** [comment]
Cannot reproduce.
