### ISSUE TITLE
Extra info for download sites on Logistics pipes

### ISSUE THREAD

**Issue by Zaflis** [RS485/LogisticsPipes#893]
It should be mentioned that if not using a "all-in-one" version of buildcraft, the Logistics pipes depends on BC-Transport, BC-Silicon and most likely BC-Core. I found this out the hard way from crash log.

Descriptions at:
http://www.curse.com/mc-mods/minecraft/232838-logistics-pipes
http://minecraft.curseforge.com/projects/logistics-pipes

**Comment by hron84** [comment]
And don't forget BC Robotics too - at least temporary while you get rid on this dependency.

**Comment by Zaflis** [comment]
I don't get server crash while not having robotics. Are they required for LP itself? I'm new to the mod and haven't gotten to learn the details yet.

**Comment by hron84** [comment]
Yep, but IIRC not at startup. There was an issue regarding to runtime dependency to Robotics.

**Comment by bziemons** [comment]
This will not be relevant in 0.10 anymore, because BC independence. I guess people have lived with it for 0.9 and therefor a wontfix now.
