### ISSUE TITLE
[Enhancement] Request Table oredict popup should display mod name to entries

### ISSUE THREAD

**Issue by hron84** [RS485/LogisticsPipes#894]
I enjoy this new (at least, new for me) popup that helps the LP request table to clarify the recipes (when I shift+click on `?` button in NEI) but it should show not only the name, but the mod ID of the item too. Sometimes really hard to make difference between two Copper ingot from two different mod just by the item name and the texture. Some texture packs makes it even harder too.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/issues/920
