### ISSUE TITLE
Power Transportation with Logistic Pipes not working in FTB Infinity Evolved

### ISSUE THREAD

**Issue by DiogoSaraiva** [RS485/LogisticsPipes#897]
Power Transportation with Logistic Pipes not working in FTB Infinity Evolved

**Comment by hron84** [comment]
@DiogoSaraiva could you explain this a bit more, maybe with screenshots/video with your current setup?

**Comment by SonOfTheStars** [comment]
FTB Infinity is using an Outdated Build of LP! Please contact the Packs Author so he can grab our latest Stable version!

**Comment by hron84** [comment]
@Bitterholz Usualy, FTB staff tracks all affected mods but because there is a release cycle of their packs, they neccessarily not up-to-date. Could you please confirm the latest versions are contains a fix for the mentioned issue?

**Comment by loordgek** [comment]
FTB Infinity Evolved is using logisticspipes-0.9.3.70.jar and said build is the last build
http://ci.thezorro266.com/view/Logistics%20Pipes/job/LogisticsPipes-0.9-mc17-bc7/

**Comment by SonOfTheStars** [comment]
@DiogoSaraiva You don't even provide enough Information on your "Issue" that we can actually confirm any Issue! Saying nothing but "X is not wroking please Fix" is equal to saying "the Sky is Blue Today".
Here is some simple Logic that gets your Issue Resolved Quickly:
1. Do you get a Crash?
   - **Yes: Provide a Pastebin link with the Full Crashlog and idealy a Modlist w/ Versions AND a Picture/Video of your crashing Setup**
   - **No: See points 2 and 3**
2. Do you get Internal Server Errors or similar Kicks of the World?
   - **Yes: Provide a Pastebin Link of your Servers/Clients Logfiles AND Idealy a Modlist w/ Versions AND a Picture/Video of your Setup**
   - **No: See Point 3**
3. If you neither get an Instance of Point 1 or 2
   - **Explain your Problem in Detail with the help of Pictures/Videos AND Modlist w/ versions so we can ensure this is actually a Bug or just you derping!**

**Comment by hron84** [comment]
@Bitterholz I absolute agree, however a simple question: should it work (e.g. it is not disabled, not broken atm)?

**Comment by ilightwas** [comment]
I can say with certainty that it's not broken, I used that A LOT in the previous server I played. And it was Infinity evolved expert. You are doing something wrong.

**Comment by hron84** [comment]
@SamDiego thanks for clarification.
