### ISSUE TITLE
Question about mod support

### ISSUE THREAD

**Issue by Speiger** [RS485/LogisticsPipes#904]
Since i stopped the lp support in my mod. (Because i am not able to do it with this indirect api) i started to try to understand how you are going to support the other mods. Factorization, Jabba and all that stuff..
And i nodest one thing (which made my thing impossible) you never implemeted sided support.
Factorization barrels can only extract from the Bottom or Back or insert into the top or into the back.
But with logistic pipes it should be always possible. From any side... Which makes no sence to me...

Why did you not add sided support?

**Comment by 1n5aN1aC** [comment]
I thought LP did simulate whatever side it was connected to?

Furthermore, you can use sneaky upgrades, to make the pipe pretend it's attached to the bottom when it's actually attached to the side, for example.  This makes many things possible that would otherwise not be possible.

**Comment by Speiger** [comment]
@1n5aN1aC Nope i checkt the code. And the SpecialInventoryHandler does not even care about the side... The Sneaky Upgrades are only for ISidedInventories... And they still have the bad Copy of BC which causes with some addons lag...

**Comment by davboecki** [comment]
We decided to make provider pipes sneaky a long time ago. Same goes for crafting pipes. That's why we don't handle the sides inside your InventoryHandlers.

**Comment by Speiger** [comment]
@davboecki thats stupid.... With that you guys make it impossible to get support from other mods...
I wanted to support my mod and that is impossible because the class you provide is pure crap....

**Comment by davboecki** [comment]
The SpecialInventoryHandler has evolved in the past years. It has seen many changes. That's why it has no clear structure. And that our Special connectors don't care about sideness does not mean whey don't know what side they are on. The getUtilForTile method has the side.

**Comment by Speiger** [comment]
Thats why it needs a clear structure... Else LP will die by the same reason why MJ did die... Just faster...
And ignoring the side is the most stupid thing i have ever seen... And the thing also is getUtilForTileNeeds to mark if it is for Exporting or Importing Items... Else the system does not work if sided access allow only import or export...

**Comment by Speiger** [comment]
Oh and before i forget call mark dirty after you extract something... Else bugs with mods can happen...

**Comment by AEnterprise** [comment]
@Speiger LP shouldn't call markDirty on your TE's just call it yourself from the extraction or insertion functions

**Comment by davboecki** [comment]
If I had the 500+ hours to rewrite stuff in LP I would probably rewrite the compliete mod, but I just don't have that time. There are lot's of parts that are not good inside LP. It's been coded by lot's of different people without clear direction so it's a combination of different language styles with different oppinions about what should be done in what way.
If LP dies because of this it would be sad, although I don't think it will. If you think I'm doing a horrible job at maintaining this mod feel free to make a PR or fork it and create your own version. I'm doing the best I can with what I've got for such a big and complicated mod.

**Comment by Speiger** [comment]
@AEnterprise well if i do that i would rely on blocktick or do it like Jabba which are very laggy... And only LP has that problem...
@davboecki oh well i wish you luck

**Comment by bziemons** [comment]
@Speiger I wish you luck at learning how to be nice to people. Your argumentation does not even make sense.
