### ISSUE TITLE
Logistics Pipes and BuildcraftCompat comaptible

### ISSUE THREAD

**Issue by darkbumerang** [RS485/LogisticsPipes#905]
Logistics Pipes 0.9.3.70, BC Compat 7.1.13 and BC 7.1.14, minecraft 1.7.10.
Crash Error in uploaded file
http://pastebin.com/vnhupnML
what to do?
Without BCCompat mod, game starts normally with plug logistics pipes

**Comment by SonOfTheStars** [comment]
First of all: Please post Crashlogs as link of a www.pastebin.com upload of your crash(Simply Copy Pasta the content over)

Second: This is NOT caused by LP, its an error on the side of BC-Compat.

**Comment by darkbumerang** [comment]
Thank you, I will decide.

**Comment by hron84** [comment]
@darkbumerang please report it to [BuildCraft/BuildCraftCompat](https://github.com/BuildCraft/BuildcraftCompat/issues) to let @asiekierka know about this issue.

**Comment by asiekierka** [comment]
This looks like an API conflict, as we bundle the necessary APIs. Not with LP, tho...

**Comment by loordgek** [comment]
@darkbumerang try take Additional-Buildcraft-Objects out and see is that helps

**Comment by darkbumerang** [comment]
Asekirka thanks for the reply. The problem was solved by adding a plug-in CoFHLib, everything works correctly.
/Проблема решилась добавлением плагина CoFHLib, плагин теперь работает корректно, клиент запускается и трубы взаимодействуют между друг другом.
