### ISSUE TITLE
Ticking block entity/IllegalArgumentException with Supplier Pipes

### ISSUE THREAD

**Issue by NexAdn** [RS485/LogisticsPipes#907]
I wanted to use the Supplier Pipe to transfer oak saplings to (1) an MFR Planter and (2) to a normal Minecraft chest. In both cases I got a java.lang.IllegalArgumentException and a ticking block entity (the Supplier pipe) and my game crashed. The game just produced the error when I put a sapling in the Supplier Pipe configuraion. I used the FTB Infinity Modpack.
Crashreport:
https://gist.github.com/NexAdn/4f6637f55d4679254628

**Comment by bookerthegeek** [comment]
Please for the love of readability put that in a ghist or a pastebin and link to it.

**Comment by NexAdn** [comment]
https://gist.github.com/NexAdn/4f6637f55d4679254628

**Comment by bookerthegeek** [comment]
.... now, can you remove it from the first post please? 

Also, you could have put the link into the first post. ;)

**Comment by SonOfTheStars** [comment]
Cant reproduce this error. You might have catched a bad download of the Pack wich corrupted LP. Have you tried redownloading?

**Comment by hron84** [comment]
For safety: use [this](http://ci.thezorro266.com/job/LogisticsPipes-0.9-mc17-bc7/) download page for get the right package. All other sites (except maybe Curse and CurseForge) are subject to contain wrong or corrupted version.

**Comment by davboecki** [comment]
No answer to track down the bug.
