### ISSUE TITLE
LogisticPipes extraction Bug

### ISSUE THREAD

**Issue by Speiger** [RS485/LogisticsPipes#908]
Logistic Pipes are not calling markDirty after they extracted items.
How i can tell that.
Well i placed a transdimensionalTinyChest on top of a Extracting Chassy pipe and they picked only the first 9 stacks. While there were thousends of stacks inside, but to push items into the outputslots you need to call markDirty (that causes the inventory to check the output inventory and insert missing items) well and since it is not autorefilling means that lp does not call the functions it has to...

**Comment by hron84** [comment]
@Speiger could you please describe which mods are involved in this issue, with versions? We need also LP version too. 
Also, if you can, please try out provider pipes/provider modules in chassis pipe to make sure what is the root cause of the issue.

**Comment by Speiger** [comment]
we are using on a vanilla forge server: logisticspipes-0.9.3.70
I tried also a provider setup and it does not even call mark dirty to. What this means simply is: The items in the outputslot get removed but since there is no mark dirty call the outputslot will be not refilled... and i am not planning to make a recaclulate on slotModify thing... thats laggy enough on jabba barrels.

**Comment by Speiger** [comment]
@hron84

**Comment by SonOfTheStars** [comment]
@Speiger can i get a dev Version of your mod(I believe its yours youre talking about) so i can fiddle with the markDirty() call in the extractoin code?

**Comment by Speiger** [comment]
@Bitterholz give me a way to send you a PM and you can have it...
Also i would like to support that LP can see how much is inside a Transdimensional TinyChest but without sided lock there is going to be no support. And do not tell me that it is possible... You guys removed the sided support for Factorization barrels. (Blocked sides can be accessed with LP which i do not want with my Chests)

**Comment by SonOfTheStars** [comment]
@Speiger just put it in a dropbox or something

**Comment by Speiger** [comment]
@Bitterholz that is not the problem. The problem is it is a none release mod yet... So no share with open world.... Thats why i ask for PM

**Comment by Speiger** [comment]
@Bitterholz can you give me now a way to send you a pm so you can have the mod to test with?
Reason for that is simply because the mod is not released and i do not plan to throw the mod anywhere public out now...
Or just support mark dirty on the Extraction...

**Comment by SonOfTheStars** [comment]
@Speiger you could join my Discord via https://discord.gg/0mIbHZOLZ7PmxyFX
You can then PM me with a link to a DL
