### ISSUE TITLE
balance discussion: should remote requester request from other dimensions?

### ISSUE THREAD

**Issue by AartBluestoke** [RS485/LogisticsPipes#91]
atm almost everyone with LP and ender chests runs around with ender pouches and remote requesters.

If almost everyone does something, it is probably OP.

At the moment there is no incentive to use request pipes vs remote requesters and an ender chest.

I propose
a) remote requester only works in the same dimension as the pipe.
b) there is a cost of X lp per item requested, based on the block distance to the pipe, from the remote requester. This energy cost should be shown on the GUI.

Comments?

**Comment by davboecki** [comment]
I personaly really like the ability to request across dimensions. So i don't like propose a.
But propose b is something I personaly would support. Maybe even higher the lp amount when you are in another dimension even more.

**Comment by Flow86** [comment]
I like the ability too, but proposal b sounds okay for me.

**Comment by GUIpsp** [comment]
I propose that every LP operation using remote requesters should be multiplied by the log2 of the distance between the dimension ids + 2:
![](http://i.imgur.com/RQn2Iyc.gif)
where n is the distance between the dim ids.

This makes a curve a curve that I think is good for balancing this mechanic:
![](http://i.imgur.com/SWttTJ7.gif)

**Comment by Sunrage** [comment]
I love the ability very usefull,it's a GREAT bonus in LP 
exemple  in mystcraft age, hop i open my remote and i have my inventory

**Comment by thatsIch** [comment]
I vote for b) since I dont like a)

**Comment by ArtForz** [comment]
We implemented (a) accidentally a few times... it sucks.
I'd say (b) + nix remote orderer search capability + higher power cost per requested item for remote request pipes.
Power based on distance also sounds neat but "what is distance cross-dimension" is tricky to define.

**Comment by Sakata-MC** [comment]
I'd say b) myself, keep search function but make it cost LP to search based on the number of items it has to check +|or|\* the cost of ordering.

Near end-game this would be fairly expensive in energy.

**Comment by bziemons** [comment]
What @ArtForz said. "Power based on distance also sounds neat but "what is distance cross-dimension" is tricky to define."
I do see it similarly as the majority. Please not (a), but yes to (b)

**Comment by thatsIch** [comment]
It would be funny, if you could make it more expsensive
how different the age is.

like if you live in a normal overworld and go to another dimension which is void only you probably far far away, but thats probably impossible to determine ^^

**Comment by bziemons** [comment]
Type of dimension, hmm.. I don't think there is a general command to find out, how that dimension looks like ;) That would mean we have to support all the mods with dimensions?

**Comment by thatsIch** [comment]
Yea figured,
What about, the energy cost rise the longer you keep the interface up? like it would simulate how difficult it is, to keep the "frequency" up to another dimension.

**Comment by AartBluestoke** [comment]
Remote request pipe now costs energy to bring up the gui 1 per x,y,z from the destination, 500 MJ extra if in another dimension. (for comparison 100mj is the amount of energy it takes a quarry to break 1 block then move to the next).

There is no range limit, except your energy storage

**Comment by bziemons** [comment]
Didn't we talk about capping the cost somewhere?
