### ISSUE TITLE
Rework all Tooltips to work like normal minecraft ones.

### ISSUE THREAD

**Issue by davboecki** [RS485/LogisticsPipes#920]
Make all Tooltips displayed by LP also call all handles from other mods to display information like WAILA, Thaumcraft aspects.....

**Comment by mikeloeven** [comment]
Nice to see this finally making it into the UI do you have an estimate on when this will be implemented ?

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/10af17d5dec0353aa59d5129b9cc34cced627aa5
