### ISSUE TITLE
Crash with Crafting Pipes/Crafting Tables

### ISSUE THREAD

**Issue by JasonMcRay** [RS485/LogisticsPipes#922]
I just updated my private server to latest LP (0.9.3.80) but after it started I received an immediate crash: http://pastebin.com/8EiAphNN

Afterwards I used forge function to remove erroring entities/tile entities, and it removed 5 of my MK2 Chassis pipes with 2 modules in them (Crafting Module and Active Supplier Module). Those were conected to Logistic Crafting Tables (Fuzzy) with recipes coded in.

I then tried to replace them. I have put down MK2 Chassis Pipe, put in Crafting Module, imported recipe, removed GT tools from the recipe (in the crafting module). Then I in hand coded the Supplier Module, to supply GT tools to the table, and immediately after I put the Supplier Module into the Chassis pipe, it crashed again with the same crashlog.

I decided to not use Supplier Modules for the time being, and just used Crafting Pipes, without specified tools (I have put the tools manually into the crafting table). It was fine, as long as I did not requested any crafting process. When I did... boom crash again.

It was all working perfectly fine before (0.9.3.70).

Edit: The crash also happend with Crafting Pipes cinnected to machines. When requested the crafting and the item hit the pipe. Crash

Modpack: InfiTech 2

**Comment by davboecki** [comment]
Could you check if the newest build fixes this?

**Comment by JasonMcRay** [comment]
just would like to say thanks. It fixed it.
