### ISSUE TITLE
Auto Enable Beta Recipes

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#923]
When Builddcraft isnt Present, should we Auto-Enable th alternative Recipes?

**Comment by davboecki** [comment]
As Logistics Pipes doesn't start without BC, there is no need for this at the moment.

**Comment by SonOfTheStars** [comment]
Im talking about, when its not able to find the crafting Parts. 

there is a check like somewhere down in the main Class wich bugged me

**Comment by bziemons** [comment]
Actually for the 0.10 (dev) version we are currently thinking about making all new recipes, which do not require BuildCraft parts. We already have all the blocks and a few items. The current beta recipes are okay, but especially the 32x32 images do not match most Minecraft texture packs. Also I prefer having basic 16x16 delivered by mods themselves.

**Comment by SonOfTheStars** [comment]
@theZorro266 the moment you Look at 1.8 Mods, most of them deliver 32x and even higher textures.

Visual appealing Items and Blocks are important for many People. Id say give a Config option for low end Textures, and have standard 64x textures.

And even then, if a players machine cant handle a Pack of 64x textures, they probably cant even load MC.
Trying to match stuff desperatly is bad practice, rather create something uniwue that ppl will like. They can do Texturepacks anyways if they don't like it

**Comment by bziemons** [comment]
Everything you said there is correct. And still we are going to have 16x16 textures, because we like them more. Uniqueness can also be achieved with low resolution images.

**Comment by hron84** [comment]
@theZorro266 what if you ship both? I mean, make 16x textures but ship current 32x too as opt-in.

**Comment by SonOfTheStars** [comment]
@hron84 @theZorro266 It would be nice if LP shipped with higher Res Textures right off the bat, allowing users to use a Config value to switch between resolutions. That way, everyone is happy.

**Comment by bziemons** [comment]
@hron84 @Bitterholz that's what texturepacks are for?

**Comment by hron84** [comment]
@theZorro266 Partially, but nothing prevents you to provide an alternative texture like how Botania does this, even if @Vazkii is also know the existence of texture packs. In this way, you can provide a choice for us.

**Comment by bziemons** [comment]
And why do you think texture packs aren't a choice for you?

**Comment by hron84** [comment]
Because it has small chance to a random texture pack will include the current 32x texture rather than you make it available for us. Except if the LP-Zorro-32 texture pack comes out. :smile:
