### ISSUE TITLE
Rework of the Pipes Model

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#925]
Rework of the Pipes Model to severely reduce the Mesh Count and therefore drop the draw() calls
wich results in improved Framerate and less spiking on placement.
Additionally it could be moved to standart forge OBJ  Loading instead of raw rendering.

Id offer to rework the Model and implement the OBj loading if @davboecki and @theZorro266  approve

**Comment by bziemons** [comment]
I would decline this. The new model is meant to be pretty and I haven't had any lag because of it yet.

**Comment by SonOfTheStars** [comment]
Im not talking about any Change. More like move from Code based rander and a bunchload of Meshes inside the OBJ file to something more Solid.

**Comment by loordgek** [comment]
@theZorro266 i get stupid amuont of fps "lag" if i am not at my base i get 200 to 300 fps in my base 
i drop as low as 1o fps
my spec
`Operating System
            Windows 10 Home 64-bit
        CPU
            Intel Core i5 4570 @ 3.20GHz    34 °C
            Haswell 22nm Technology
        RAM
            8,00GB Single-Channel DDR3 @ 665MHz (9-9-9-24)
        Motherboard
            Gigabyte Technology Co. Ltd. G1.Sniper B5-CF (SOCKET 0) 28 °C
        Graphics
            SMBX2431 (1920x1080@60Hz)
            Acer AL1717 (1280x1024@60Hz)
            Intel HD Graphics 4600 (Gigabyte)
            3072MB ATI AMD Radeon R9 200 Series (ASUStek Computer Inc)  42 °C
            CrossFire Disabled
        Storage
            223GB Crucial_CT240M500SSD1 (SSD)
            1397GB SAMSUNG HD154UI (SATA)   24 °C
            186GB Seagate ST3200822AS (SATA)    46 °C
            298GB Hitachi HTS545032B9A300 USB Device (SSD)
        Optical Drives
            HL-DT-ST DVDRAM GH22NS40
        Audio
            Realtek High Definition Audio`

**Comment by XFactHD** [comment]
RAM at 665 MHz? That doesn't look like it is correct.

**Comment by SonOfTheStars** [comment]
@XFactHD Thats the DRAM Frequency there. You have to double that.

I can confirm that the shere presence of a big LP netwrok causes your FPS to have a huge drop.

**Comment by XFactHD** [comment]
I can't say anything on that because I am even to dumb to transfer some liquid over a single pipeline made of LP's fluid pipes :).

**Comment by SonOfTheStars** [comment]
The HS Tubes look alot Better! Way less Meshes...

**Comment by bziemons** [comment]
This is not relevant anymore. We do not want to change the current model.
