### ISSUE TITLE
LPTickHandler leaks World instances

### ISSUE THREAD

**Issue by fraenkelc** [RS485/LogisticsPipes#930]
Versions:
- FTB Infinity 2.3.5
- logisticspipes-0.9.3.70.jar
- mystcraft-1.7.10-0.12.3.01.jar

We are currently encountering severe memory leaks on our FTB Infinity Instance. We currently run out of memory roughly every 90 minutes. We took some heap dumps which revealed the following:
- The total memory usage is 3.1GB
- 65 Instances of `com.xcompwiz.mystcraft.world.profiling.ChunkProfiler` take up 1.874.922.416 bytes
  ![image](https://cloud.githubusercontent.com/assets/4005102/13408658/4b5e941c-df2f-11e5-84e8-f21a29853b46.png)
- Of these **one** is reachable via `net.minecraft.server.dedicated.DedicatedServer`. The rest are only reachable via `logisticspipes.ticks.LPTickHandler` (the retained heap values are misleading):
  ![image](https://cloud.githubusercontent.com/assets/4005102/13408802/fe94ced4-df2f-11e5-98c3-10b0ab67dc55.png)

To see how long these World instances where alive I've grouped the values of      `logisticspipes.ticks.LPTickHandler.LPWorldInfo.worldTick`:
  ![image](https://cloud.githubusercontent.com/assets/4005102/13408942/b133883c-df30-11e5-9e86-c91d68c16cee.png)
as seen, most of these instances live for just shy of a minute (this report also includes non-mystcraft worlds (rftools) which do not have a ChunkProfiler)

This leads me to the conclusion that `logisticspipes.ticks.LPTickHandler.worldInfo` needs to use a hashmap with weak / soft keys. (That, or the map needs to be cleaned in another way)

**Comment by davboecki** [comment]
```
new MapMaker()
       .weakKeys()
       .makeMap()
```

should do it.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/724b165c4d4df23cbf05702d8cacdf02ed59acd9

**Comment by Bogdan-G** [comment]
`com.google.*` libs? it is certainly not slow down performance?
