### ISSUE TITLE
Regression with Storage Drawers compatibility

### ISSUE THREAD

**Issue by tahg** [RS485/LogisticsPipes#932]
Up to version 83, the polymorphic item sink was able to insert items into a Storage Drawer system that currently had a 0 count (locked drawers).  Starting with version 84 this is no longer possible.  Build 84 was a compatibility update for Storage Drawers.

Whether the new functionality was intended or not, I'd like to see the old way reintroduced.  The current builds are presenting a bit of a challange when I take items out and then want to put them back in.

**Comment by hron84** [comment]
Workaround: configure Provider modules to leave one item per type. This solves the issue.

Also, could you pelase specify the StorageDrawers version too? Just for the records.

**Comment by tahg** [comment]
Storage Drawers 1.9.3 currently, previously 1.9.2 and 1.8.0.  I'll agree the workaround does work, but is a bit of a pain when I want something I might have few of, for instance chipsets, or when I grab a bunch of items manually for a build because the requesting table takes a while.

**Comment by hron84** [comment]
I'm an impatient guy so I solved the problem in a very easy way. I put down and Ender Chest from EnderStorage next to my drawer storage system, placed a remote request pipe below it, and i linked the ender chest to and ender pouch. In this way as soon as i order something from the remote orderer, nearly immediatelly lands in my ender chest. 

About chipsets or other "precious" items: not everything worth to have an own drawer. When I building an LP system, I make few double chests or golden chests that have mod-based itemsink module, and i route all problematic or "precious" items here. If you pay attention, and build this system _after_ the drawer wall, the drwer wall takes precedence when it can (polymorphic) and then the mod-based sink catches all remaining stuff. 

I agree these problems exists however easy to get rid on them. for my specific case it is not even happening for me.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/5482ed0356a2494c321705e486d104b193a8fa51
