### ISSUE TITLE
Compat crash causing lockup

### ISSUE THREAD

**Issue by XFactHD** [RS485/LogisticsPipes#933]
I just started MC and put it in the background to do its thing. When I clicked on the window again, it still said "Loading - Initializing mods Phase 1". When I looked at the log, I saw this: http://pastebin.com/tUpx0QL8. The first part until line 263 makes sense but the rest seems to point at some issue with how you are creating this crash.

EDIT: I am using the latest version of LP but not the latest one of BC.

EDIT 2: You might want to look at this: https://github.com/MinecraftForge/FML/blob/master/src/main/java/net/minecraftforge/fml/relauncher/FMLSecurityManager.java

**Comment by davboecki** [comment]
"The BC Version '7.0.17' is not supported by this LP version. Please use '7.1.5'"

**Comment by XFactHD** [comment]
I know. That's why I wrote this: "The first part until line 263 makes sense but the rest seems to point at some issue with how you are creating this crash." This issue is not about me not knowing what the cause of this crash is, this issue is about how some mod (likely LP) tried to close MC when the crash occured. If you look at the class I mentioned in my second edit, there is a comment saying that only MC itself and FML are allowed to close the process.

**Comment by davboecki** [comment]
We don't close MC. That stack trace shows that it is MC itself trying to close the game.

**Comment by XFactHD** [comment]
This doesn't make sense because when you look at the linked class in my first post, it allows MC to close itself.

**Comment by davboecki** [comment]
I don't realy see the problem. There is a crash and that messes things up. It works fine when you take care of the correct BC version.

**Comment by hron84** [comment]
@XFactHD There is nothing that LP does for closing MC. The crash is caused by throwing exception [here](https://github.com/RS485/LogisticsPipes/blob/dev/common/logisticspipes/proxy/buildcraft/BuildCraftProxy.java#L103). As you can see, it's a simple, plain old Java exception, with no call for System.exit. I think because the exception is caused in very early stage, MC somehow attempts to close itself, but FML traps this attempt and breaks it.

**Comment by XFactHD** [comment]
Ok, I am gonna try reporting this to FML and see if what they have to say. Thanks nonetheless.
