### ISSUE TITLE
logistics pipes are hard to tell apart

### ISSUE THREAD

**Issue by hihellobyeoh** [RS485/LogisticsPipes#934]
at least in the inventory of the latest stable build for BC 7.1.5+, please note atm i am too tired to compile the code that is right here to see if it is changed, but in NEI, and inventory it is hard to tell the pipes apart, perhaps add an inventory only icon? just a suggestion and i don't know where to give suggestions so i chose to do it in the issues section.

**Comment by SonOfTheStars** [comment]
Since build 83 or so, Pipe Models in Inventory AND NEI do /NOT/ include the inner Side Texture wich is the only way to visually destinct them from each other @davboecki. Sth got messed up there

In world they display just fine tho

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/71299d156e884503110d472499f88bd30724b63a
