### ISSUE TITLE
Crafting Module not keeping Satellite ID

### ISSUE THREAD

**Issue by TimAST** [RS485/LogisticsPipes#935]
Using version 0.9.3.95. Crafting modules are not keeping their Satellite ID, (reverting to "off") when world restarted, or chunks unloaded.

**Comment by davboecki** [comment]
In item form or inside a chassi pipe?

**Comment by TimAST** [comment]
Inside a chassis pipe, (mk4). The routing still seems to work, just the display in the crafting module gui shows "off". I am running the FTB Infinity evovled pack, and manually updated LP from 0.9.3.70, where the item routing didn't work at all.

**Comment by TimAST** [comment]
The Crafting Pipe retains its Satellite ID after restart/chunk unload.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/da71f4dbfdc7c671c4b49e737ed79afe4b60f3a8
