### ISSUE TITLE
ID setting for satelite pipes keeps resetting on singleplayer launch

### ISSUE THREAD

**Issue by 016Nojr** [RS485/LogisticsPipes#942]
Using the latest version of FTB Infinity Evolved (2.4.2). Which is using Log. Pipes (0.9.3.95). 

Whenever I restart my singleplayer world, all my crafting modules in a Chassis Mk5 pipe resets the ID for the satelite pipe, setting it to "Off". The satelite pipe itself is still on it's own ID "1".

This does NOT happen to Crafting Pipes!

**Comment by SonOfTheStars** [comment]
Did you actually put something into the Sattelite Slot of the Module?
like an actual Item to provide?

**Comment by 016Nojr** [comment]
Yes

**Comment by 016Nojr** [comment]
Turns out there is more that doesnt save correctly.
- Logistics Request Table: The Show/Hide button on the top middle to show/hide the inventory on the right resets every time the interface is reopened

**Comment by davboecki** [comment]
The Hide/Show is only a status for the current GUI. If you reopen it you have a new GUI, so the reset is  intended. The Satellite ID resetting inside the GUI is of course not intended and needs to be investigated.

**Comment by 016Nojr** [comment]
oh ye, I am a derp

**Comment by bziemons** [comment]
Related to #1460
