### ISSUE TITLE
CRASH REPORT!

### ISSUE THREAD

**Issue by civoldem** [RS485/LogisticsPipes#944]
Hi all. At first i would like to congrat all the developers from this magnificent mod. 

We start a server with mods with no problems including the version of this mod: logisticspipes-0.9.3.68
Then we put some basical pluggins and no problems appeared.

But now, with no reason the server CRASH in this way: we start the server with no problem, but when any player enter the server it CRASHES! If we quit the mod if works with no problem. And if we quit the mod with the same world but with any pipe in using it works well. But if we put the world in the first crash time it doesnt work.

I copy the CRASH LOG:

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 19/03/16 22:47
Description: Exception in server tick loop

java.lang.RuntimeException: java.io.EOFException
    at com.google.common.base.Throwables.propagate(Throwables.java:160)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:144)
    at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:576)
    at net.minecraft.server.management.ServerConfigurationManager.disconnect(ServerConfigurationManager.java:437)
    at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:945)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:162)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException
    at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268)
    at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
    at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
    at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
    at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
    at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:29)
    at logisticspipes.config.PlayerConfig.readFromFile(PlayerConfig.java:124)
    at logisticspipes.LogisticsEventListener.getPlayerConfig(LogisticsEventListener.java:312)
    at logisticspipes.LogisticsEventListener.onPlayerLogout(LogisticsEventListener.java:201)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_225_LogisticsEventListener_onPlayerLogout_PlayerLoggedOutEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    ... 9 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
    Java Version: 1.8.0_74, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 24688131744 bytes (23544 MB) / 30341070848 bytes (28935 MB) up to 30341070848 bytes (28935 MB)
    JVM Flags: 2 total; -Xmx30000M -Xms30000M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 65 mods loaded, 65 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](KCauldron-1.7.10-1448.121-server.jar) 
    UCHIJAAAA   Forge{10.13.4.1448} [Minecraft Forge](KCauldron-1.7.10-1448.121-server.jar) 
    UCHIJAAAA   kimagine{0.1} [KImagine](minecraft.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.5.118} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
    UCHIJAAAA   se{0.4.1} [Super Enchants](minecraft.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJAAAA   deconstruction{2.2.1} [The Deconstruction Mod]([MC 1.7.10]deconstruction[2.2.1].jar) 
    UCHIJAAAA   Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) 
    UCHIJAAAA   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJAAAA   BiblioCraft{1.11.4} [BiblioCraft](BiblioCraft[v1.11.4][MC1.7.10].jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.0.3} [CoFH Core](CoFHCore-[1.7.10]3.0.3-303.jar) 
    UCHIJAAAA   BuildCraft|Core{7.1.14} [BuildCraft](buildcraft-7.1.14.jar) 
    UCHIJAAAA   Forestry{3.6.12.3} [Forestry for Minecraft](forestry_1.7.10-3.6.12.3.jar) 
    UCHIJAAAA   BinnieCore{2.0-pre7} [Binnie Core](binnie-mods-2.0-pre7.jar) 
    UCHIJAAAA   Botany{2.0-pre7} [Botany](binnie-mods-2.0-pre7.jar) 
    UCHIJAAAA   ExtraBees{2.0-pre7} [Extra Bees](binnie-mods-2.0-pre7.jar) 
    UCHIJAAAA   ExtraTrees{2.0-pre7} [Extra Trees](binnie-mods-2.0-pre7.jar) 
    UCHIJAAAA   Genetics{2.0-pre7} [Genetics](binnie-mods-2.0-pre7.jar) 
    UCHIJAAAA   Botania{r1.7-229} [Botania](Botania r1.7-229.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.1.14} [BC Builders](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.1.14} [BC Transport](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.1.14} [BC Energy](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.1.14} [BC Silicon](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Robotics{7.1.14} [BC Robotics](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.1.14} [BC Factory](buildcraft-7.1.14.jar) 
    UCHIJAAAA   ChickenChunks{1.3.4.19} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
    UCHIJAAAA   chocolateQuest{1.0} [Chocolate Quest](chocolateQuest-1.7.10-1.0.jar) 
    UCHIJAAAA   customnpcs{1.7.10d} [CustomNpcs](CustomNPCs_1.7.10d.jar) 
    UCHIJAAAA   wonderfulwands{1.4.2} [Cyano's Wonderful Wands](CyanosWonderfulWands-1.4.2.jar) 
    UCHIJAAAA   ImmibisCore{59.1.1} [Immibis Core](immibis-core-59.1.1.jar) 
    UCHIJAAAA   DimensionalAnchors{59.0.3} [Dimensional Anchors](dimensional-anchor-59.0.3.jar) 
    UCHIJAAAA   eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UCHIJAAAA   EnderStorage{1.4.7.37} [EnderStorage](EnderStorage-1.7.10-1.4.7.37-universal.jar) 
    UCHIJAAAA   farlanders{1.2b} [The Farlanders](farlanders-1.7.10-v1.2b.jar) 
    UCHIJAAAA   flansmod{4.10.0} [Flan's Mod](Flans Mod-1.7.10-4.10.0.jar) 
    UCHIJAAAA   InfernalMobs{1.6.0} [Infernal Mobs](InfernalMobs-1.7.10.jar) 
    UCHIJAAAA   mod_Invasion{1.0b} [Invasion](Invasion-mod-by-unstoppablen-1.7.10.jar) 
    UCHIJAAAA   inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) 
    UCHIJAAAA   IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCHIJAAAA   ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    UCHIJAAAA   ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
    UCHIJAAAA   LogisticsPipes{0.9.3.100} [Logistics Pipes](logisticspipes-0.9.3.100.jar) 
    UCHIJAAAA   Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) 
    UCHIJAAAA   ForgeMultipart{1.1.2.331} [Forge Multipart](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    UCHIJAAAA   Mekanism{8.1.9} [Mekanism](Mekanism-1.7.10-8.1.9.265.jar) 
    UCHIJAAAA   MekanismGenerators{8.1.9} [MekanismGenerators](MekanismGenerators-1.7.10-8.1.9.265.jar) 
    UCHIJAAAA   MekanismTools{8.1.9} [MekanismTools](MekanismTools-1.7.10-8.1.9.265.jar) 
    UCHIJAAAA   NEIAddons{1.12.13.38} [NEI Addons](neiaddons-1.12.13.38-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Developer{1.12.13.38} [NEI Addons: Developer Tools](neiaddons-1.12.13.38-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|AppEng{1.12.13.38} [NEI Addons: Applied Energistics 2](neiaddons-1.12.13.38-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Botany{1.12.13.38} [NEI Addons: Botany](neiaddons-1.12.13.38-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Forestry{1.12.13.38} [NEI Addons: Forestry](neiaddons-1.12.13.38-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|CraftingTables{1.12.13.38} [NEI Addons: Crafting Tables](neiaddons-1.12.13.38-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|ExNihilo{1.12.13.38} [NEI Addons: Ex Nihilo](neiaddons-1.12.13.38-mc1.7.10.jar) 
    UCHIJAAAA   neiintegration{1.0.11} [NEI Integration](NEIIntegration-MC1.7.10-1.0.11.jar) 
    UCHIJAAAA   ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.1.0-161.jar) 
    UCHIJAAAA   tts{0.6} [Tube Transport System](TubeTransportSystem_1.7.10-0.6.jar) 
    UCHIJAAAA   McMultipart{1.1.2.331} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    UCHIJAAAA   ForgeRelocation{0.0.1.3} [ForgeRelocation](ForgeRelocation-1.7.10-0.0.1.3-universal.jar) 
    UCHIJAAAA   MCFrames{1.0} [MCFrames](ForgeRelocation-1.7.10-0.0.1.3-universal.jar) 
    UCHIJAAAA   RelocationFMP{0.0.1.2} [RelocationFMP](ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
    UCHIJAAAA   MrTJPCoreMod{1.1.0.27} [MrTJPCore](MrTJPCore-1.7.10-1.1.0.27-universal.jar) 
    UCHIJAAAA   ForgeMicroblock{1.1.2.331} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    CoFHCore: -[1.7.10]3.0.3-303
    ThermalFoundation: -[1.7.10]1.2.0-102
    ThermalExpansion: -[1.7.10]4.0.3B1-218
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
    ThermalDynamics: -[1.7.10]1.1.0-161
    Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Bukkit, Cauldron, or other Bukkit replacement
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 2 / 20; [EntityPlayerMP['CIVOLDEM'/5392, l='world', x=267,22, y=115,50, z=1672,37](CIVOLDEM at 267.2199885992462,115.5,1672.3726318278068), EntityPlayerMP['MisterMedinaYT'/12030, l='world', x=40,27, y=68,00, z=68,00](MisterMedinaYT at 40.272093873655194,68.0,67.99565029644842)]
    Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
    Type: Dedicated Server (map_server.txt)

PLEASE HELP us!

**Comment by hron84** [comment]
Logistics pipes stores the player info under `logisticspipes/${PLAYER_UUID}.info` (where ${PLAYER_UUID} will be replaced with a UUID taken from Mojang servers), and these files became corrupted.

<strike>
Not sure if you restore just these files from older backup solves the problem or not, I strongly recommend you to restore the whole world to an older backup, or at least playerdata and this folder.
</strike>

**Comment by SonOfTheStars** [comment]
It appears that, due to something going incorrect while writing, the file is Corrupted and the Parser reaches the end of the File in hte middle of Parsing. Hence the EOFException.

<strike>
Simply restoring, or even better, deleting the playerdatas for the player it happens to, if his inventory isnt that full of worthy stuff, should help get rid of this Issue.
</strike>

**Comment by bziemons** [comment]
jeez, are we in a mood of bad advise in here?
The player config that we talk about just contains some rendering options for a player.
There is no need to make a full world restore, neither is it necessary to delete any playerdatas with inventories.

The files we are talking about are in the worlds folder under `logisticspipes` and it is only necessary to delete `<player uuid>.info`. You should be able to obtain that player uuid from the `usernamecache.json` file in your server's main directoy.

I believe you @hron84 @Bitterholz just try to help, but please do not, if you don't know the details.

**Comment by KajesLorian** [comment]
Should I wait before pushing the LogisticsPipes{0.9.3.100} update to my server then? (The mod is great btw)

**Comment by Bitterholz** [comment]
You can update as you wish sir. 

All you need to do is this:

> The files we are talking about are in the worlds folder under `[YourWorldName]\logisticspipes` and it is only necessary to delete `<player uuid>.info`.You should be able to obtain that player uuid from the `usernamecache.json` file in your server's main directoy.

If you dont know the specific Player that causes the crash, delete those files all together and you should be just fine.

**Comment by bziemons** [comment]
@KajesLorian this just happens occasionally and it has not even happened to our server once. I guess it is a very rare bug that can happen with any LP version right now.
