### ISSUE TITLE
new icons for modules?

### ISSUE THREAD

**Issue by Ghoughpteighbteau** [RS485/LogisticsPipes#946]
I see the modules for logistics pipes are MSpaint levels of simple, so I made a cut up some component pieces to use in a template in blender, and produced a whole bunch of modules in a different style. 

Examples: http://imgur.com/a/d7ifi

Considering the 6 base colors, the presence of stripes, and the presence and color of two chips, that makes 384 individual graphics to pick and choose between. 

Whether or not you want to use them, they're yours, no attribution, and the blend file if you care to modify some of the parameters (though you'll need a familiarity with blenders compositor and animation system, I can change things if you want). 

here's the blend file: https://www.dropbox.com/s/hsh84ppu6u7b83z/logistics3.blend?dl=1

here's a zip of the generated modules: https://www.dropbox.com/s/p8ntaxcx2hes0je/tmp.zip?dl=1

Gonna work on the upgrades next if you think the effort is worth it.

**Comment by SonOfTheStars** [comment]
10/10 new Module textures get!
Looks 10x better

**Comment by hron84** [comment]
I like the new icons too, except I am not sure in this angle they would not appear a bit small in-game. But I definitely like the new style!

**Comment by SonOfTheStars** [comment]
@hron84 they are still 16x16 i assume so ingame they wold appear just the normal Size i think. Maybe a lil smaller, but modules allready appear ridic big for the pipes you insert them into

**Comment by Ghoughpteighbteau** [comment]
for comparison regarding size and legibility:

![1](http://i.imgur.com/75qM5DT.png)  ![2](https://raw.githubusercontent.com/RS485/LogisticsPipes/dev/resources/assets/logisticspipes/textures/items/itemModule/ModuleElectricManager.png)

![1](http://i.imgur.com/6inYFQS.png)   ![2](https://raw.githubusercontent.com/RS485/LogisticsPipes/dev/resources/assets/logisticspipes/textures/items/itemModule/ModuleItemSink.png)

![1](http://i.imgur.com/shqEsV0.png)   ![2](https://raw.githubusercontent.com/RS485/LogisticsPipes/dev/resources/assets/logisticspipes/textures/items/itemModule/ModuleTerminus.png)

I know where you're coming from though, when I first prototyped the icons I did it in 32x32, "They must be this large, right?"

**Comment by SonOfTheStars** [comment]
@Ghoughpteighbteau just as a tip: most mods, including LP ship only 16x16 textures by default. though I hope you cvan convince the devs to get some 32x ones in too...they look so much better!

**Comment by bziemons** [comment]
![1](https://cloud.githubusercontent.com/assets/1096713/14024918/deb0d800-f1eb-11e5-9abe-6f3ccfd50a54.png) ![2](https://cloud.githubusercontent.com/assets/1096713/14024921/e14a9394-f1eb-11e5-8eab-e7bb6c514a0a.png) ![3](https://cloud.githubusercontent.com/assets/1096713/14024925/e3970448-f1eb-11e5-8ff0-e0a0f3f4aeda.png)

That is about the size they will be displayed at. I think that is pretty solid. Also, I like the look of them. Good work @Ghoughpteighbteau and thanks.

**Comment by SonOfTheStars** [comment]
YAY! New module Textures Confirmed!!!!

**Comment by hron84** [comment]
:heart: Thanks @davboecki and @theZorro266 it will make this mod much better! :smile:

**Comment by Ghoughpteighbteau** [comment]
Upgrade modules doing the same kinda thing:

![1](http://i.imgur.com/CRUx8bu.png)

![2](http://i.imgur.com/woDaHIB.png)

same thing, changes available, I give up rights, take if you want, ect. 

I've got to find a better script-able compositing system other than blender.

**Comment by Ghoughpteighbteau** [comment]
so. these have arrow labels printed on them (6) + IC and TE labels, threw in stripes, for 10

5 base colors \* a fuzzy versions  \* the random chip configs makes for ~ 1500... 

A lot of these don't really work, particularly the ones with chips over top of labels, but it's easier to generate them systematically rather than pick and choose.

https://www.dropbox.com/s/53e2zuec55r8ic8/LogisticsUpgrades.zip?dl=1

blend file for generating and gimp file for the basic construction included.

**Comment by Landrash** [comment]
@Ghoughpteighbteau The new modules look really nice to =)

**Comment by Ghoughpteighbteau** [comment]
cool! 

I think I need to fix the fuzzy texture, doesn't look fuzzy enough. Maybe I'll just steal the wool texture. Come to think of it. I have no idea why I didn't do that in the first place...

Oh BTW. In the old upgrade cards, up and down was symbolized by having one of the two chips be blue, but there's actually a symbol for "up" and "down". 

http://www.physics.brocku.ca/PPLATO/h-flap/phys4_2f_10.png

So that's what the circle with the dot and the circle with the X are

**Comment by davboecki** [comment]
Modules and upgrade textures have been changed to these in the MC 1.12 update.
Thanks again, they look great.
