### ISSUE TITLE
LP 0.9.3.100 - BC 7.1.16 - requesting items from an obsidian chest causes CTD

### ISSUE THREAD

**Issue by b0bst3r** [RS485/LogisticsPipes#948]
Crash starts at line 791 
http://paste.atlauncher.com/view/f3134d2c

When I try to request an ingot from an obsidian chest using a logistics pipe, the game crashes back to the main menu. It seems to only affect ingots and metal blocks - gems, dusts, dirt, etc. does not cause the crash. The metals tested were iron, gold, tin, silver, copper both in ingot and block form. Nuggets and metal dusts, however, work fine.

https://github.com/BevoTechPack/BevoTechPack/issues/948

**Comment by davboecki** [comment]
Update LP
