### ISSUE TITLE
Seeing progress of crafting

### ISSUE THREAD

**Issue by krouma** [RS485/LogisticsPipes#949]
I like seeing progress of crafting/requesting when I hit the Request button in Logistics Request Table in the right side. But when I hit +/++/+++/~ button I can`t see that. Could you add that feature?

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/18e641005f9029a7496f815d9386a8d0a6241167

**Comment by krouma** [comment]
Thank you, it works. But other issue appears. Sometimes when I hit ~ button and I have some items already in Request table inventory, world crashes (not entire client) and in log is this: http://pastebin.com/Tx9fa5G3.

**Comment by davboecki** [comment]
Fixed by https://github.com/RS485/LogisticsPipes/commit/1bfa9eda1509770bb57c3bfdbcd6e2c7321fe296
Next time please open a new issue for a "new issue" you have.
