### ISSUE TITLE
"Multicrafting" Problem

### ISSUE THREAD

**Issue by Adrigorithm** [RS485/LogisticsPipes#952]
Hello

I just made a whole autocrafting setup to make as much high voltage solar panels as I request (Industrial craft classic). 
_http://prntscr.com/ameb07_
The problem is that it can't craft them properly because it doesn't seem to craft first tier components which you need to get higher tier components and finally the item I want (High voltage solar panel). However, for some reason it works when I make another setup which is not complex at all, but has the same principe, I request chests, the provider sends logs to the crafters, which makes them into planks, then the planks get send to the crafting part for chests, tadah, this works.

I can't figure out why it isn't working for my complex setup, I'd appreciate some help...

I case you want/need to watch my setup closely, I made this on the tekkit legends modpack from the technic launcher, My world can be found here:
_https://mega.nz/#!rMsQEQzL!Q_eQeRRWg0_AmjBS-Iiha-Ubv3Tde87lIotsLKbQN0U_

**Comment by davboecki** [comment]
What LP version do you use?

**Comment by Adrigorithm** [comment]
logisticspipes-0.9.3.70

**Comment by davboecki** [comment]
The current version is logisticspipes-0.9.3.108. Please update und try again.

**Comment by Adrigorithm** [comment]
Uh, seems like I have to make a custom 1.8.9 modpack to get the most recent version.
Hold on.

**Comment by Adrigorithm** [comment]
I found out that there's no version of industrial craft classic for 1.8.9, how can I do it then?

**Comment by davboecki** [comment]
Why are we suddenly talking about MC 1.8.9 ? There isn't even an LP version for MC1.8.

**Comment by Adrigorithm** [comment]
well, you said most recent version. Didn't it require Buildcraft? The buildcraft version I need is for 1.8.9 or am I wrong?

**Comment by davboecki** [comment]
The newest LP version is for BC 7.1.15 which is for MC 1.7.10 just like LP has only versions for MC 1.7.10

**Comment by Adrigorithm** [comment]
omg. Yeah, I saw 7.1.5+ and I was thinking about 50. I'm dumb.
Also, I've noticed that the items that cause the issue are chargable items: RE-battery and Energy Crystal from icc. This has been fixed already in that version I guess, since there're so many things about this issue on the internet already. I guess I'll have to contact the modpack authors to update these mods then^^

**Comment by bziemons** [comment]
Okay, thanks.
