### ISSUE TITLE
crafting pipe mk2 not rendering in inventory

### ISSUE THREAD

**Issue by loordgek** [RS485/LogisticsPipes#953]
![lpbug](https://cloud.githubusercontent.com/assets/4789835/14232269/c986e2ec-f9a4-11e5-9a38-c1d0a6d3a672.png)

**Comment by loordgek** [comment]
using logisticspipes-0.9.3.112
https://paste.ee/p/0KJjz

**Comment by davboecki** [comment]
Have you tried restarting minecraft and redownloading the lp jar?

**Comment by loordgek** [comment]
now it works, weird
