### ISSUE TITLE
forestry saplings dont get sorted to barrel

### ISSUE THREAD

**Issue by loordgek** [RS485/LogisticsPipes#956]
i have a Polymorphic ItemSink module on a jabba barrel but the saplings dont go in it

**Comment by Landrash** [comment]
@loordgek What version of the mod are you using?
Are you sure the sapling in the barrel are the same as the sapling your sending to it?
Does it work if you just use a normal logistics pipe?

**Comment by AEnterprise** [comment]
the problem is probably nbt, forestry tree breeding genetics

**Comment by SonOfTheStars** [comment]
I think the Polymorphic module is not comparing the items right. It seems to not be able to read NBT Info on one end, either the Barrel or the incoming item.

**Comment by bziemons** [comment]
Is this problem solved?

**Comment by loordgek** [comment]
no

**Comment by Landrash** [comment]
@loordgek Some more information like answering the questions asked could help find the problem your having

**Comment by bziemons** [comment]
Closed, because the OP failed to give more information.
