### ISSUE TITLE
CC Based ItemSink Usage?

### ISSUE THREAD

**Issue by gudenau** [RS485/LogisticsPipes#963]
I am attempting to use a CC Based ItemSink module to sort out the junk from my Minefactoryreloaded Grinder. I have an advanced computer next to a MK2 Chassis pipe with the module installed and using "print(os.pullEventRaw()) print(os.pullEventRaw())" in the Lua interpreter. The only event I get is the key event from hitting return. From what I can tell this should work, correct? Build 112 in the FTB Infinity Evolved Skyblock modpack.

**Comment by davboecki** [comment]
CC ItemSinks only with in connection with the CC Quick sort. Due to the computer implementation there is no way to handle normal sorting tasks like extractors with the CC ItemSink alone.

**Comment by gudenau** [comment]
If I understand this correctly, I need to use the other CC module to pull items?

**Comment by davboecki** [comment]
Yes
