### ISSUE TITLE
Items put in incorrect storage drawer

### ISSUE THREAD

**Issue by Kyprus** [RS485/LogisticsPipes#965]
HI,

I have a simple storage drawer setup using a chassis pipe with a Polymorphic ItemSink connected to a Drawer Controller. [Picture](http://i.imgur.com/guLsoE2.png)

The issue is when an item is sent into the controller, it is not put in the drawer where that item already exists. It will pick the closest open drawer it can find. In my picture, the obsidian ends up in the (initially empty) bottom-right drawer instead of the top left where there is already obsidian.

This setup worked perfectly in Infinity Evolved (LP version 0.9.3.95). But now in IE:S (LP version 0.9.3.112), it no longer works correctly. If there is anything other info I can provide, or I should be reporting this to Storage Drawers let me know. Thank you!

**Comment by Landrash** [comment]
You need to use sorting drawers for it to end up in the correct drawer. The controller doesn't try to be intelligent and you would get the same result if you used a hopper to insert into the controller.

A workaround is to only have one spot for each item available and no empty drawers.

**Comment by hron84** [comment]
@Landrash no, he not have to use sorting drawers. Locking all drawers is enough. If you lock an empty drawer, you can still format it with a single piece of item anytime.

**Comment by Kyprus** [comment]
@Landrash If I use an Itemduct I actually don't see the issue I described. The item goes to the correct drawer.

If you wouldn't mind, can you take a look at these two videos I just made? The first is with the previous versions of the mod that worked like I described. The second is the later versions where the behavior seems to have changed.

[First](https://www.dropbox.com/s/tjkqo3t8a63jjy4/lp-drawers-1.mp4?dl=0)
[Second](https://www.dropbox.com/s/xf6nfwnub4e8ydw/lp-drawers-2.mp4?dl=0)
If you download them the quality should be better.

As you can see, the iron ingots sort correctly in the first, and not in the second.

**Comment by 1n5aN1aC** [comment]
Hmmm, is it possible PR #921 Broke that functionality?

What is weird, is that I could have SWORN that previously it would cram them into the nearest available slot, and I had to work around that by locking any empty drawers in my previous setups....

**Comment by Landrash** [comment]
@hron84 I'm sorry, I stand corrected. That's odd, I tried it on my setup with the result I described above.

My suggestion with sorting drawers where with the assumption that the drawers are not locked for a reason.

**Comment by hron84** [comment]
I worked with drawers a lot, especially on Infinity Evolved, and I experienced two things:

1) yes, controllers are dumb. They works wonderful if they have to take out items from your hand but performs poorly when any automation inserts an item into them. This is how drawers work, and even if it should be better, we should deal with the current behavior.
2) making a full wall without any gap is a very-very hard thing. I personaly prefer to prepare a whole lot of storage space and format it later depending on requirements than crafting a drawer when my inventory is full with rotten flesh or similar things. There is no real reason why _not_ lock a drawer. Locking a drawer comes with a lot of benefit and literally no drawback. The key is ridiculously cheap (a gold ingot and some nuggets?) and takes no damage on locking/unlocking actions. One key belongs with you forever except if you lose it. At the point where you can make a controller, you can make a key too.

So, there is no valid point to why not lock a drawer when automating comes into the place.

**Comment by Kyprus** [comment]
@hron84 I agree with you; it's not a big deal to lock all the drawers. I'll do that.

I just wanted to point out a change in behavior that I saw, which seemed like some kind of regression. Maybe @jaquadro can chime in?

**Comment by jaquadro** [comment]
If someone would like to zip up a world with a test setup using these two mods, I'll take a look at it.  It's supposed to be smart enough to re-use existing slots.

**Comment by Kyprus** [comment]
@jaquadro [Here](https://www.dropbox.com/s/yc72bkc9ot3klzk/lp-drawers.zip?dl=0) is a world with the test case.

I did it using Logistics Pipes 0.9.3.112 and Storage Drawers 1.7.10-1.9.7. These are the versions from the FTB Infinity Evolved Skyblock pack. It also needs Thermal Expansion installed for power.

**Comment by jaquadro** [comment]
@Kyprus, I tested your world, and it behaved like it should -- it always put the iron ingots into the iron ingot slot.  I even tried moving them to different slots.  I'm not sure why it's behaving differently for you.

**Comment by Kyprus** [comment]
@jaquadro Strange, I can't get it to work no matter what I do. Maybe a conflict with another mod in the pack. if I'm able to narrow it down any further I'll let you know.

Thank you all for the help

**Comment by codewarrior0** [comment]
Issue appears to still be present with `logisticspipes-0.9.3.128` and `StorageDrawers-1.7.10-1.9.9`

Polymorphic itemsink on drawer controller, item inserted via "Sort" box in Request table, item goes into empty drawer closest to controller instead of drawer containing item.

**Comment by bziemons** [comment]
Re-implemented in https://github.com/RS485/LogisticsPipes/commit/fc0bb26d82c9872343634499429f86a04a83dd15

Hopefully fixed all problems mentioned here
