### ISSUE TITLE
crash to desktop

### ISSUE THREAD

**Issue by DnTheMn** [RS485/LogisticsPipes#967]
##putting a sign creator on a basic pipe will cause you to crash to desktop and when you reload the save it crashes, if its on a server it only effects the user who placed the sign(you can join for 10-20 seconds then you crash and it dosent create a crash report) here is a log best i can do http://pastebin.com/0VDEn1pF

**Comment by davboecki** [comment]
http://www.minecraftforum.net/forums/support/unmodified-minecraft-client/1855986-minecraft-closes-randomly
