### ISSUE TITLE
The HUD glass do not all ways works

### ISSUE THREAD

**Issue by Dijkstra1-zz** [RS485/LogisticsPipes#972]
There seems to problem with the with HUD glasses where it will only so info about pipes that placed after I put them and if I want to show other I have to leave the dimension and come back and then for the crafting pipes i have to right click each one with an wrench, for the HUD to show what they craft.

**Comment by hron84** [comment]
Could you give us some more info about your system? A LP version, what mods are you using along with it, how your setup looks like... you know, help us to drill down to the problem.

**Comment by ZZaphodd** [comment]
I have same issues on FTB Infinity expert skyblock 1.10
When I restarted the game, all 'result' are empty.

Before rightclick with wrench.
![image](https://cloud.githubusercontent.com/assets/8099421/14584568/2d7006a6-0488-11e6-9f5b-1223e2ba4a83.png)

Update 'result' after rightclick with wrench
![image](https://cloud.githubusercontent.com/assets/8099421/14584569/392329a6-0488-11e6-8df5-134904d87ae1.png)

btw provider pipes have no problem
![image](https://cloud.githubusercontent.com/assets/8099421/14584620/6e7d91fc-048a-11e6-84dc-d0d72bf1f3cc.png)

**Comment by bziemons** [comment]
Could be related to #841

**Comment by Dijkstra1-zz** [comment]
@theZorro266, it does seem some what like #841

**Comment by Cerugon** [comment]
It doesn't occur in 0.9.3.61. It definitely occurs in 0.9.3.121. Haven't tested the versions in between yet.
Until I update the craftingpipes with a wrench, they also don't work. They just do nothing. The crafting is listed in the remote orderer, but if you request it, nothing happens. 
Need more data?
Edit: Also appears in 0.9.3.117.
Edit: Doesn't appear in 0.9.3.95.

**Comment by Tyronadre** [comment]
For me it works if i log out while logistic pipes is not in the player loaded chunks. If i log in then, most of the pipes getting an interface.
Edit: But Crafting Upgrades won't Show anything!

**Comment by bziemons** [comment]
:broom:

**Comment by Tomsn16** [comment]
will this be fixed in 1.7.10? i have the same problem user ZZaphodd describes, version logisticspipes-0.9.3.132
