### ISSUE TITLE
'Most likely' button crashes game.

### ISSUE THREAD

**Issue by ZZaphodd** [RS485/LogisticsPipes#975]
LP version : 0.9.3.114
modpack : FTB Infinity expert skyblock

I did't reproduced with minimal environment, but I have no problem using 'Most like' button with other recipes. 

Reproduce procedure, consistent result  : 
1. let them craft botania lexical.. something guidebook on Request Table, and click 'Most likely' button
2. game crashes and 'Payload may not be larger than 32k'

![image](https://cloud.githubusercontent.com/assets/8099421/14584581/b4d933ce-0488-11e6-9efe-fcad026e4b56.png)

![image](https://cloud.githubusercontent.com/assets/8099421/14584583/bdfa3bce-0488-11e6-8099-21dbb3a366b1.png)

**Comment by bziemons** [comment]
Is there any Java exception in your client or server log? If so, could you please post them to https://gist.github.com/ and link that here?

**Comment by Solidflip** [comment]
Having the same issue, here is my log
http://pastebin.com/5pDpEkv9

I cleared it just before clicking the Most Likely button.

**Comment by ZZaphodd** [comment]
https://gist.github.com/ZZaphodd/296e6ae321a08f7e72120a72daadd691

**Comment by ZZaphodd** [comment]
this recipe cause same problem(saplings)

![image](https://cloud.githubusercontent.com/assets/8099421/14759744/6b7b1302-0968-11e6-95d9-ea9ed996e2c5.png)
