### ISSUE TITLE
Logistic Pipe at version 1.8.9

### ISSUE THREAD

**Issue by Araton10** [RS485/LogisticsPipes#977]
Hi , sorry to disturb you so much, but how long will it take to get Logistic Pipes Mod for the 1.8.9 version?

**Comment by Lupus590** [comment]
they are working on it: https://github.com/RS485/LogisticsPipes/tree/dev-mc189

from what I have heard (I'm not a mod maker) going from 1.7.10 to 1.8.x is difficult, so it may take a while

**Comment by SonOfTheStars** [comment]
1.8 is a "Work in Progress" build and not working yet. but everyone whos skilled in 1.8 Modding may take part in Porting.

**Comment by mgdgfbhevdyeh** [comment]
@davboecki @theZorro266 @lupus590 @Bitterholz Does this mod is give up to MC1.8.9?
And BuildCraft released 1.11.2 The LogisticsPipes will be updated to 1.11.2?Or will the LogisticsPipes be updated to a later version of the MC?
I just think LogisticsPipes stayed at 1.7.10 for too long

sorry for my English

**Comment by hron84** [comment]
@mgdgfbhevdyeh As far as I know, no, just there is too much work and there's no enough hand for the port.

**Comment by mgdgfbhevdyeh** [comment]
I just want this mod no die or stay forever at 1.7.10

**Comment by Lupus590** [comment]
@mgdgfbhevdyeh learn to mod and then work on porting

**Comment by SonOfTheStars** [comment]
For people interested I AM working on a 1.10 "Spiritual Successor" to Logistics Pipes, from scratch. Progess is slow since im not a very professional modder or deeply into the Minecraft code.

So far tho we have a very promising new Look and Concept and networking is being done as I write this.
Yet we are far from any kind of real functionality.

But i can offer these little teasers: http://imgur.com/a/kbQEn and http://imgur.com/da9w11G.png

**Comment by Lupus590** [comment]
@Bitterholz ~~Github has misinterpreted your links, you may want to fix that.~~

**Comment by SonOfTheStars** [comment]
@lupus590 they should be fixed now might wanna reload the page

**Comment by Lupus590** [comment]
It looks cool. Are you going to open source it? Do you have a github repo that people can contribute to? 

Edit: is this the project? https://github.com/Bitterholz/LP2

**Comment by SonOfTheStars** [comment]
I do have a Repo but the code is crappy and Im not someone who loves to be told how bad their work is XD

**Comment by SonOfTheStars** [comment]
But since people are interested, you might as well take a look. Its publicly accesible anyways https://github.com/Bitterholz/LP2

**Comment by bziemons** [comment]
See https://github.com/RS485/LogisticsPipes#also-check-out
