### ISSUE TITLE
inserting Frames in Apiary not working

### ISSUE THREAD

**Issue by Casper-O** [RS485/LogisticsPipes#983]
After my latest upgrade of mod packages its not possible to insert Frames in Apiary with Logistic Pipes. Before i was using "Active Supplier Module" to make sure there was always 3 frames in my Apiary, but I just figured out its not even possible when i request them with the remote to the pipe connected to the Apiary.
- forge-1.7.10-10.13.4.1614-1.7.10
- logisticspipes-0.9.3.114
- forestry_1.7.10-4.2.8.56
- buildcraft-7.1.14
- buildcraft-compat-7.1.3

(I have more mods than this but these are what i think could be relevant for this issue)

**Comment by SonOfTheStars** [comment]
Not possible. Slots for Frames are /NOT/ exposed to automated inventory Access. This is a Design Choice by Forestry Dev Sir Sengir. Apiaries are meant to be semi manual.

Alvearies though, the expensive Multiblock version Allows it by default when a Frame Housing Block is part of the Multiblock. 

This aint a Bug this is Intentional.

**Comment by Casper-O** [comment]
Interesting, im pretty sure it worked for me before with a "Active Supplier Module" connected to the Apiary but I can be mistaken. Also it could have been a bug in forestry that allowed it for a short time

**Comment by SonOfTheStars** [comment]
@Casper-O Could be. Its defenitly NOT designed to be working that way.

**Comment by hron84** [comment]
Yeah, apiaries aren't fully automateable, at least frames aren't. IIRC only SFM can handle them, but it's definitely not sure. Alvearies the only devices that are automateable both in terms of bees and frames too.

**Comment by Casper-O** [comment]
I was just about to close my issue but since @theZorro266 have given the label "bug" i Think it should be up to him to make the call and relabel it If needed

**Comment by davboecki** [comment]
He also gave it the label needs validation. This is just for us to see what report is about a bug and what an enhancement. Even if the bug hasn't been verified.
