### ISSUE TITLE
Crafting get stuck

### ISSUE THREAD

**Issue by Mazzelfassel** [RS485/LogisticsPipes#984]
I've set up a system to craft Waterwheels form Immerive engineering, so the treated wood is being crafted successfully in a cyclic assembler from TE but then the wood goes into storage instead of the logistic crafting tables. If you remove all storage options the items will just being dropped at the assembler. But when you order a Waterwheel when the Wood is in Storage the crafting process as usual. I cant explain why the Items wont go directly into the crafting table.
Im using the FTB Infinity Evolved Skyblock Pack.

**Comment by SonOfTheStars** [comment]
You Probably have the Assembler Auto-Output into a Logistics Basic Pipe Right?
If so, i reffer thee to: http://rs485.network/wiki/Crafting_Logistics_Pipe

The Wiki is WIP but this page should help you solve your Problem

**Comment by bziemons** [comment]
You may not auto eject the item after crafting. The crafting pipe needs to take the item out of the attached inventory.

**Comment by Mazzelfassel** [comment]
Ty, I didnt knew that before, now it works perfectly.

**Comment by SonOfTheStars** [comment]
@Mazzelfassel if you have more questions the Wiki is allways there and there will soon be a Tutorial Series by Me
