### ISSUE TITLE
getUpgradeManager throwing an ArrayIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by ShaneCourtrille** [RS485/LogisticsPipes#985]
I'm getting a crash from a Crafting Module MK1 in a MK4 Chassis.  There are two other Crafting Module MK2s in the same chassis.  Those 3 modules + a normal crafting logistics pipe mk2 are all sharing a satellite pipe.

Crash Gist https://gist.github.com/ShaneCourtrille/9550f4ccbb9b92a9dbb3871061a7b6e2

**Comment by davboecki** [comment]
There is a wrong catch condition. There should be an >= instead of an >. Although this still doesn't, explain how the item got that wrong information.

**Comment by ShaneCourtrille** [comment]
More info & some things I've tried..
- My Logistics pipe system is connected to a Storage Drawers setup.  
- The crafting chassis is attached to a chest where the output ends up in.  
- Satellite pipe is connected to a hopper
- I am crafting an industrialcraft 2 gold plate from a gold ingot

Here are some things I've tried..
- Remove the crafting module MK1 and place it back in.. crashes
- New crafting module MK1 configured the same.. crashes
- Upgraded my crafting module to a MK2 and configured the same.. crashes
- Removed all other crafting modules from the chassis and put it in slot 1...stopped crashing
- Moved the crafting module to slot 3 and left the other slots empty.. crashes
- Broke the crafting chassis and placed it again with the crafting module in slot 3.. still crashes

At that point I realized that the chassis was connecting directly to a branching gold BC pipe.. replaced that branch pipe with a proper basic logistics pipe.. still crashes..

I stopped testing after that because sitting around waiting for the server to restart got boring but let me know if there is anything else you want me to try out..

**Comment by davboecki** [comment]
I've added a workaround for this although I can't reproduce it.
