### ISSUE TITLE
Crash with Fluid Suppliers and Extractors

### ISSUE THREAD

**Issue by tivec** [RS485/LogisticsPipes#987]
I'm playing the FTB Infinity Expert mode Skyblock pack, and have started using fluid pipes more extensively than before. I have started running into an ArrayIndexOutOfBoundsException crash. It does not seem to affect the server, but whenever I log in to the sevrver, the minecraft window turns blue, then it crashes.

The crash seems to happen when I have extractors or suppliers set to extract lava.

Here's the crash report:
http://hastebin.com/putigeqifu.cs

**Comment by tivec** [comment]
I have done some more testing on this issue. It seems to happen if I have a fluid supplier pipe on the side of a Ex Nihilio barrel - then it crashes immediately if there is fluid visible in the supplier pipe.

**Comment by XFactHD** [comment]
I found those two lines in the crash report:
at mrtjp.relocation.ASMHacks$.renderTileEntityAt(hacks.scala:30)
    at mrtjp.relocation.ASMHacks.renderTileEntityAt(hacks.scala)
Could you try to reproduce this without any of MrTJP's mods as this is known to cause compatibility problems, in ImmersiveEngineering it even caused a race condition leading to a CME.

**Comment by tivec** [comment]
I can do a test later, but I'm suspecting others might be getting these errors due to this being an unchanged FTB Infinity Expert Skyblock... Although, we're on an earlier version, we can try upgrading it as well.

**Comment by davboecki** [comment]
At the first glance this looks more like a problem on our side. Looks like it is trying to render more fluid than the tank can hold for some reason and the renderer is missing a catch for that.

**Comment by bookerthegeek** [comment]
May I ask what fluid is on the barrel?

**Comment by tivec** [comment]
This was lava going to the stone barrel.

**Comment by bookerthegeek** [comment]
Odd. We haven't received reports of this at our server. Can I get a screenshot of the setup and how the pipes are configured please?

**Comment by tivec** [comment]
I created a test setup to provoke the bug. This is as far as I got before it crashed on me.. 

http://i.imgur.com/qTjnRHQ.png

No chance to show the configuration of the provider pipe, sadly.

**Comment by bookerthegeek** [comment]
So your pulling from the tank and putting into the barrel?

**Comment by bookerthegeek** [comment]
Or vice versa

**Comment by tivec** [comment]
Supplier on tank, so I'm pulling from tank and putting into the barrel.
