### ISSUE TITLE
LP is slow at startup

### ISSUE THREAD

**Issue by AartBluestoke** [RS485/LogisticsPipes#99]
a) the new PacketHandler code takes 2/3 second to initialize, which is almost all the non-forge time in the fmlModConainer.constructMod. (the rest is reflection and hard to localize to a specific mod)
Loading the LP packetHandler takes quite a while, for some reason. (LP is the 
![image](https://f.cloud.github.com/assets/1892829/680222/c24c438a-d988-11e2-8f7b-e94b9ec59186.png)

b) also on post-init, LP is slow, holding 3rd place.

(edit: misplaced issue about rs485/nem removed)

**Comment by GUIpsp** [comment]
I don't think there is a way around a), unless we revert all the packet changes

**Comment by AartBluestoke** [comment]
could we limit our class loader to only load specific classes on demand, rather than re-parsing all existing classes?

**Comment by GUIpsp** [comment]
Could you put these benchmarks somewhere?

**Comment by AartBluestoke** [comment]
yeah, just need to re-capture them, computer crashed resuming from sleep, and the capture those screenies are from didn't get saved.

**Comment by AartBluestoke** [comment]
https://docs.google.com/file/d/0B84ffYKLW6CPRHB5bEJTMm5OYzQ/edit?usp=sharing - 600ms spent that startup; the first few seconds of capture are missing, I believe that sampling starts during the "Activating mod" message set at the begining of forge mod loading (5 or 6 seconds afteer the true start of MC)

**Comment by AartBluestoke** [comment]
new packet handling system makes this profile irrelevent
