### ISSUE TITLE
Crafting pipe sign crash

### ISSUE THREAD

**Issue by pkuyken** [RS485/LogisticsPipes#991]
I have a very simple crafting system and I regularly receive hard crashes when I try to place signs on the crafting pipe with the sign creator.  I don't know if it matter, but the item being crafted is a Chest.

Attached are the following logs:
[Logistical Construction/hs_err_pid12832.log](https://gist.github.com/pkuyken/c3e6261adeb11771798c24438265c139)
[fml-client-latest.log](https://gist.github.com/pkuyken/30889506756178fee638d0a6d47af68a)

**Comment by davboecki** [comment]
Please try to follow this guide: http://www.minecraftforum.net/forums/support/unmodified-minecraft-client/2583815-solved-low-fps-problems#c4
If it still craches you need to give us a new crash log and more information about your system. Like Forge version and LP version but also jwjgl version, graphics driver version, OS, if you are running on a notebook...

**Comment by BlueAgent** [comment]
I also experience this crash.
I play Minecraft with integrated graphics, so I know I can't expect much of it.

Interestingly, on a server, if I place a sign, I can view it and I won't crash but upon teleporting away and back, or login in near the sign, I will crash.
Once someone removes the sign I can log in again fine.

Unfortunately the HUD Glasses aren't showing the recipes for inactive crafting so I can't use that as an alternative either. But that's a different issue.

However, I've used both the crafting signs and HUD glasses without issues in past playthroughs.

**Comment by pkuyken** [comment]
@davboecki I will check that out as soon as I can (may be in a day or so).  Thanks for the quick reply.

I am running on a laptop with integrated graphics.

**Comment by pkuyken** [comment]
I stripped down the mod list to the absolute bare minimums (Buildcraft and LP) and am still having crashes to desktop.  While the linked video wasn't directly relevant, I did ensure that I am running the latest video drivers that I can find and have updated the lwjgl to the latest in the 2.9 line.  Let me know if there are any more details that are needed. 

I tracked the problem down to something to do with the March 10 changes to LogisticsRenderPipe.java.  The build http://ci.rs485.network/job/LogisticsPipes-0.9-mc17-bc7/98/ works fine, however build http://ci.rs485.network/job/LogisticsPipes-0.9-mc17-bc7/99/ crashes with the same crash detail as in the hs_err_pid log file.

I hope this helps in tracing down the issue.  Please don't hesitate to let me know if there are any tests that you would like me to run or any experimental builds you need tested.

**Mod List**
Buildcraft 7.1.16
LogisticsPipes 0.9.3.119

**Additional Details**
Minecraft 1.7.10
Forge 10.13.4.1448
lwjgl 2.9.3 (manually updated, also tried 2.9.1 with same results)

**Video Adapter/Driver Details**
GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.15.4279' Renderer: 'Intel(R) HD Graphics 4400' (latest according to Microsoft update and direct driver update from within 

**Computer Details**
Lenovo IdeaPad laptop 
i5-4200U CPU
8 GB RAM
Windows 10 Home 64 bit.

**Java**
Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_66

**Updated Log Files**
[hs_err_pid9352.txt](https://gist.github.com/pkuyken/8b39cdcef45c73e8a665ccbbe1e4c68e)
[latest.log](https://gist.github.com/pkuyken/91c245403f1fd2494d4e765a48f4637b)

**Comment by nullifiedcat** [comment]
Yeah me having the same issue. Crashes when it tries to render a sign; can't even log in to my world (running FTB Infinity Evolved modpack, LP version 0.9.3.114) 

[hs_err_pid264](http://pastebin.com/fQLjjMvm)

edit: the fact item being crafted is a chest matters. when placing same sign with, for example, sticks (simple item) it does not crash. chests and other complex-rendered items crash the client.

**Comment by LoghamLogan** [comment]
This issue is happening for us when a logistics sign is placed on a crafting pipe, set to craft a Chest (id:54). The player cannot log back into the server whilst this sign exists. This happens with both the new and the old logistics renderer selected.
[hs_err_pid](http://pastebin.com/p3DQ4ekY)
[system spec](http://pastebin.com/Wq1MitWC)

**Comment by HadesDurin** [comment]
you all need to update your logistic pipes version to latest 0.9.3.125
after doing so, update your other drivers and java
and then if it still happens report back

**Comment by bziemons** [comment]
We know of this issue, this might shed some light on the issue: http://stackoverflow.com/questions/4113989/why-were-display-lists-deprecated-in-opengl-3-1

**Comment by Ushupiuck** [comment]
@theZorro266, I've verified that this issue still happens with Logistic pipes 132, java 8 161. Here's the log, although it's mostly the same than the last ones... (besides maybe system specs).
[hs_err_pid1420.log](https://github.com/RS485/LogisticsPipes/files/1962145/hs_err_pid1420.log)
any workarounds reccomended?

**Comment by bziemons** [comment]
As display lists are not used anymore to render items on signs in the newest LP for MC 1.12, I will close this now. This wont be fixed for older MC versions.
