### ISSUE TITLE
i setup a satellite channel in a crafting module in a mk4 chassis to craft something (on a server) whenever i log out and relog in all the satellite channels in the crafting modules reset to (off) and i have to set them again and idk why that is happening

### ISSUE THREAD

**Issue by kingstas1** [RS485/LogisticsPipes#995]
i setup a satellite channel in a crafting module in a mk4 chassis to craft something (on a server) whenever i log out and relog in all the satellite channels in the crafting modules reset to (off) and i have to set them again and idk why that is happening (i am using the 1.7.10 pack) modpack

**Comment by bookerthegeek** [comment]
Um....
 1) Version?
 2) Mod list?
 3) Pictures of reproducible setup with minimal mod list to help with debugging?

**Comment by SonOfTheStars** [comment]
@kingstas1 
First: Dont write excessively long titles!!! A simple "Crafting Mod. Satellite Problem" does it FULLY.

Second: Are you SURE that the Satellite ID you set Exists within the network?

Third: There is a shitload of Modpacks for 1.7.10. Your Modpak **MUST** have a name or if its a private one, youll have to provide a **MODLIST**

Forth: **ALLWAYS** provide the Exact versions for:
- Minecraft Forge
- Logistics Pipes
- Buildcraft

Fifth: Provide aditional info like:
- Screenshots
- Videos
- Setup Descriptions

If you do all this, we'll propperly be able to adress your issue. If your issue contains **Neither** of these vital infos, your Issue can not be dealt with.

**Comment by loordgek** [comment]
@theZorro266 can you make the title shorter plz
