### ISSUE TITLE
I'm not sure if this is a cross mod issue with AE2 cables and LP craftingtable

### ISSUE THREAD

**Issue by Algester** [RS485/LogisticsPipes#996]
As of this moment I'm trying to find out on the AE2 side if this is an apparent issues with the RV2-stable build of AE2, as it seems the LP crafting tables keep on forgetting the cables exist in the game in the first place however I still havent, tried the AE2 method of crafting if they work so I'm still playing with how I'm going to go about that build

**Comment by Algester** [comment]
ok it seems it was the old reported bug back then dealing with NEI's crafting handlers it seems so putting the items manually to craft the ME cables work...

**Comment by SonOfTheStars** [comment]
@Algester Yes most likely that old bug where NEI [?] Button inserts items with random Metadata or NBT.

If youre experiencing Issues with that, just drop the items into the Crafting Logistics Tables Ghost Slots by hand and then Import them via the Pipe.
That should fix your issue!

MfG
Bitterholz
