### ISSUE TITLE
Cannot request items stored in AE2 when there is an AE2 security station in the network

### ISSUE THREAD

**Issue by michelegargiulo** [RS485/LogisticsPipes#997]
I have an AE2 network which I store items in. I attached a remote orderer pipe in a ME interface, and it works fine. As soon as I place a AE2 security station in my ME system, even if I insert a biometric card with all the permissions granted I cannot request anything using the remote orderer.

**Comment by bookerthegeek** [comment]
Is the card locked to you or blank?

**Comment by michelegargiulo** [comment]
The card is  locked to me, and I gave myself all permissions (introduce/withdraw items, break parts of network, modify network security and so on)

**Comment by XFactHD** [comment]
It has to be blank with all permissions added to it.

**Comment by SonOfTheStars** [comment]
@SmokeyTheBandicoot Sadly, AE Security with any specific Rules, makes it impossible for Logistics Pipes to access the Network.
For a good reason, since if LP would bypass your networks security, that would be a huge design Flaw.

**Comment by michelegargiulo** [comment]
Ok, thanks. The problem was that I had to connect a security station in order to use a wireless terminal. But once I connected the security station with the biometric card (w/ all the permissions) I couldn't access my network with my remote orderer. So I'll try the blank biometric card, I didn't try it before. If it works, then the problem is solved.

**Comment by SonOfTheStars** [comment]
@SmokeyTheBandicoot 
Simple solution: Request your Items via LP! Put 2 Enderchets up and ling Enderbags to it, One as request, one as Sorting. Have a Quicksort on the Sorting Chest and a Remote orderer Pipe on the Request chest. Link up a remote orderer to that pipe and you have GLOBAL Item requesting/Sorting

**Comment by michelegargiulo** [comment]
thanks @Bitterholz for the suggestion, seems interesting and, more important, something which I never made before. Will try this out!
