### ISSUE TITLE
oredict module and crafting module bug?

### ISSUE THREAD

**Issue by killmetohell** [RS485/LogisticsPipes#998]
Not sure if this because modpack or not using logistics pipe 0.9.3.120 modpack TolkienCraft II.
The bug seem that some reason my items that in my default chest that are not oredicted on the module seems to be ignored? not sure there but its acting like if was itemsink module that has no  item set on it i think. anycase is it accepting stone and sand for right witch is not a on oredict expample.
![2016-05-04_18 57 25](https://cloud.githubusercontent.com/assets/11909414/15034413/613fc2c8-122a-11e6-9702-8142c5e120ac.png)
![2016-05-04_18 57 50](https://cloud.githubusercontent.com/assets/11909414/15034414/613ff75c-122a-11e6-9199-ac05a20bba32.png)
![2016-05-04_18 58 42](https://cloud.githubusercontent.com/assets/11909414/15034415/61403f82-122a-11e6-8229-3bc391ebb2e6.png)

had to turn it off there.

but has you see its not working for some unknown reason do guys know why.

**Comment by bookerthegeek** [comment]
I am confused about what your issue is.  Please explain better.  Overview screenshots  are also helpful.  Along with what you are trying to do.

**Comment by killmetohell** [comment]
well in screenshots the top show what have in oredict module 2nd pic show after installing it show a stack of sand going in 3rd just show that sand go into there also just confirming that going in there it is recipe for it so it ok to go in there it just that it should not go in there because there no oreSand in the oredict.

**Comment by killmetohell** [comment]
ok figured it out don't know if this intended or not but if you have crafting module installed and oredict module installed it will make any or all items sort to there.

**Comment by SonOfTheStars** [comment]
I shall test this!

**Comment by killmetohell** [comment]
on the needs validation do i post pics for guys you or not?

**Comment by bziemons** [comment]
That's for us. We need to validate the issue.

**Comment by killmetohell** [comment]
oh ok

**Comment by SonOfTheStars** [comment]
@theZorro266 I can't confirm this. works just fine for me.

@killmetohell Could it be that you placed a Itemsink that was pre-configured by accident? Or anything simmilar?

**Comment by killmetohell** [comment]
maybe it just something that only wrong with the modpack i guess but i toke some screenshots just for the needs validation because i thought i might need some proof or something like that here some if you need it.
![2016-05-07_01 25 54](https://cloud.githubusercontent.com/assets/11909414/15115724/35194cbc-15b5-11e6-8c73-b4517e807ad2.png)
this my default chest and what was store in it.
![2016-05-07_01 26 02](https://cloud.githubusercontent.com/assets/11909414/15115763/58a4902e-15b5-11e6-8a18-3f445d1159a5.png)
this is the chassis before installing a crafting module.
![2016-05-07_01 26 06](https://cloud.githubusercontent.com/assets/11909414/15115789/827b6986-15b5-11e6-81ab-42ced3383a4b.png)
this one after.
![2016-05-07_01 26 16](https://cloud.githubusercontent.com/assets/11909414/15115911/feb46c1e-15b5-11e6-99c1-2068630708a1.png)
my attempt to take a screenshot to show items going though the pipe to the machine as you can see the sand.
![2016-05-07_01 26 22](https://cloud.githubusercontent.com/assets/11909414/15116006/6c7ab3b6-15b6-11e6-8bef-c06e4cbbe82e.png)
this is screenshot what got in there maybe should take screenshot before it happen :P.

**Comment by bziemons** [comment]
Is that still happening after a server restart?

**Comment by killmetohell** [comment]
its not on server so i guess yes? don't know i been mostly playing single player i guess i should add that 2.

**Comment by bziemons** [comment]
Cannot reproduce this. Might have been fixed already in the past.
